### ISSUE TITLE
want working with perttier 

### ISSUE THREAD

**Issue by Ttou** [vuejs/vetur#1002]
- [x] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: 0.14.2
- VS Code version: 1.29

## Problem

prettier with eslint standard rules dosn't work like expect，it will transform semi false to true and singleQuote true to false

![image](https://user-images.githubusercontent.com/4298437/49202966-6e636900-f3e1-11e8-8a51-cf57e824c2ad.png)

**Comment by Ttou** [comment]
> Repro?

git clone https://gitee.com/jh_shot/vetur-issue

VSCode settings:
![image](https://user-images.githubusercontent.com/4298437/49204005-5a216b00-f3e5-11e8-8959-9a932ba16ee8.png)

**Comment by octref** [comment]
Please read https://vuejs.github.io/vetur/formatting.html. You can either:

A: Include a `.prettierrc` in your project root and specify `semi: false`
B:
```
"vetur.format.defaultFormatterOptions": {
  "prettier": {
    // Prettier option here
    "semi": false
  }
}
```
C: Choose another option for `"vetur.format.defaultFormatter.js"`, such as `none` or `vscode-typescript`
