### ISSUE TITLE
Read [docs](https://vuejs.github.io/vetur/formatting.html) and include repro.

### ISSUE THREAD

**Issue by HappyLeiLei** [vuejs/vetur#1006]
_Originally posted by @octref in https://github.com/vuejs/vetur/issues/1005#issuecomment-443099198_

Before update configured files can be forced to single quotes and remove the ending semicolon, after the update.

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/49273999-a7c0c680-f42b-11e8-8f5b-1b23fcba3586.png)
