### ISSUE TITLE
Feature request: jump to template/script/style

### ISSUE THREAD

**Issue by amritk** [vuejs/vetur#1007]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

I thought it might be cool to have a keyboard shortcut for quickly scrolling to the top of the `<template>` `<script>` or `<style>` tag for single file components. Sort of like the bookmarks vscode plugin but setup by default. What do you think?

**Comment by amritk** [comment]
Still think this could be a cool feature, should I try making a pull request?

**Comment by octref** [comment]
I don't think it's a good idea:
- Vue SFC is usually small so scrolling is enough
- Discoverability is going to be a problem

**Comment by amritk** [comment]
Yea just thought it was convenient, all good.
