### ISSUE TITLE
template tag nesting issue with prettyhtml

### ISSUE THREAD

**Issue by Asces** [vuejs/vetur#1008]
Please check again, each </ template> tag has an open tag
This html code will produce the same error result
```
<template>
  <div>  
        <template>
          <span>test</span></template>
  <template >
  <span>
    test</span>
</template>
</div>
</template>
```

_Originally posted by @Asces in https://github.com/vuejs/vetur/issues/1004#issuecomment-443435972_

**Comment by Uninen** [comment]
Can't repro with the latest version, closing the issue.
