### ISSUE TITLE
<Frame> component gives error

### ISSUE THREAD

**Issue by KoenPaas** [vuejs/vetur#1014]
Well when using Frame component it gives the error:
![schermafbeelding 2018-12-03 om 20 19 09](https://user-images.githubusercontent.com/36813373/49396165-c8916080-f738-11e8-9673-d724af7bd954.png)

Frame component is being used in combination with Nativescript.

Vetur 0.14.3

**Comment by KoenPaas** [comment]
I already have they told me to open a new issue here

**Comment by octref** [comment]
Install a local dependency of `eslint` and `eslint-plugin-vue` > 5.0.0 and this error is gone.

**Comment by mollywoodnini** [comment]
I have the same issue. Installing local dependencies didn't work for me.

**Comment by octref** [comment]
@mollywoodnini Disable Vetur's built-in template check by `vetur.validation.template: false`. Otherwise, please give a repro (fork https://github.com/octref/veturpack and push your fork).
