### ISSUE TITLE
html formatting on *.vue not working

### ISSUE THREAD

**Issue by atiqorin** [vuejs/vetur#1021]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win 10 v1803 Build 17134.407
- Vetur version: 0.14.3
- VS Code version: 1.29.1

## Problem

Template html formatting does not work. Typescript code formats but html formatting do not happen. I press alt + shift + f, the typescript formats but nothing happens to template html in a .vue file.

## Reproducible Case

on any .vue file typescript code formats but html never formats.  I tried changing the Deafult formatter: HTML to js-beutify-html and still no luck.
I have format on save enabled. Disabling that and trying with alt + shift + f also don't work.
Tried everything mentioned on issue #196 and still no luck.
I have the following extensions,
TSLint 1.0.40
TSLint Vue 1.5.6
Vim 0.16.14
Bracket Pair Colorizer 1.0.61
html tag wrapper 0.2.3
Prettier - Code formatter 1.7.2

**Comment by RiFi2k** [comment]
These work for me right now, full formating and linting for vue files. It's not exactly what you got going on but I hope it helps.
https://github.com/RiFi2k/vscode-vue-vetur-eslint-prettier-airbnb

**Comment by superheri** [comment]
I had the problem today that VS Code was telling me that there was no formatter for vue files and restarting VS Code fixed it. Maybe that can help you.

**Comment by atiqorin** [comment]
I restarted, uninstalled all other extensions. Tried ESLint, and Vue extension by liuji jim and could not get it work. Tried to treat the file as plain html and format but that adds a space after each : so :src became : src. As of now I am back to formatting by myself.

**Comment by superheri** [comment]
I don't know if that makes a difference, but I'm using VS Code Insider. Maybe this is why it works for me. Otherwise, I don't know how to solve your problem...

**Comment by RiFi2k** [comment]
@atiqorin What do your vetur and vscode settings look like?

Try these in your workspace settings for the project.
```
"prettier.disableLanguages": [
    "vue"
  ],
  "vetur.validation.template": true,
  "vetur.format.defaultFormatter.html": "prettyhtml",
  "vetur.format.defaultFormatterOptions": {
    "prettyhtml": {
      "printWidth": 80,
      "singleQuote": false,
      "wrapAttributes": true,
      "sortAttributes": false
    }
  },
```
If you don't have prettier disabled for .vue files that could be your issue.

**Comment by atiqorin** [comment]
Unfortunately these settings also didn't work.

**Comment by atiqorin** [comment]
Oops by mistake closed issue.

**Comment by atiqorin** [comment]
> @atiqorin What do your vetur and vscode settings look like?
> 
> Try these in your workspace settings for the project.
> 
> ```
> "prettier.disableLanguages": [
>     "vue"
>   ],
>   "vetur.validation.template": true,
>   "vetur.format.defaultFormatter.html": "prettyhtml",
>   "vetur.format.defaultFormatterOptions": {
>     "prettyhtml": {
>       "printWidth": 80,
>       "singleQuote": false,
>       "wrapAttributes": true,
>       "sortAttributes": false
>     }
>   },
> ```
> If you don't have prettier disabled for .vue files that could be your issue.

Unfortunately these settings also didn't work.

**Comment by atiqorin** [comment]
> @atiqorin What do your vetur and vscode settings look like?
> 
> Try these in your workspace settings for the project.
> 
> ```
> "prettier.disableLanguages": [
>     "vue"
>   ],
>   "vetur.validation.template": true,
>   "vetur.format.defaultFormatter.html": "prettyhtml",
>   "vetur.format.defaultFormatterOptions": {
>     "prettyhtml": {
>       "printWidth": 80,
>       "singleQuote": false,
>       "wrapAttributes": true,
>       "sortAttributes": false
>     }
>   },
> ```
> If you don't have prettier disabled for .vue files that could be your issue.

these is my settings.
```
{
  "workbench.colorTheme": "Visual Studio Light",
  "vim.startInInsertMode": true,
  "vim.useCtrlKeys": false,
  "vim.easymotion": true,
  "vim.leader": "<space>",
  "editor.wordWrap": "on",
  "extensions.ignoreRecommendations": true,
  "window.zoomLevel": 0,
  "vetur.format.defaultFormatter.ts": "vscode-typescript",
  "vetur.format.defaultFormatter.js": "vscode-typescript",
  "emmet.includeLanguages": {
    "vue-html": "html",
    "vue": "html"
  },
  "typescript.preferences.quoteStyle": "single",
  "prettier.disableLanguages": ["vue"],
  "prettier.singleQuote": true,
  "vetur.validation.template": true,
  "vetur.format.defaultFormatter.html": "prettyhtml",
  "vetur.format.defaultFormatterOptions": {
    "prettyhtml": {
      "printWidth": 80,
      "singleQuote": false,
      "wrapAttributes": true,
      "sortAttributes": false
    }
  },
  "editor.formatOnSave": true
}
```

**Comment by RiFi2k** [comment]
There are so many factors that could be messing with it. Here is my advice if you want to get it working.

https://github.com/RiFi2k/vscode-vue-vetur-eslint-prettier-airbnb

That config is 100% working today with all the latest versions of everything. I'm actually using it right now as we speak so it's known good.

- Deactivate all your plugins and save your current configs in another file somewhere.
- Use the setup from my repo there and get it all working minus what you don't need from it.
- Start reactivating all your other plugins and adding in your other settings until it breaks then you will know what the culprit is. Also maybe you will get lucky and with that config all your other plugins and settings will be golden.

I personally use ESLint and eslint-plugin-vue to do the template part of vue, not vetur so you would be turning vetur validate template off and using ESLint instead if you go the same way as me.

**Comment by octref** [comment]
@atiqorin Do you see any errors from Output -> Vue Language Server?
Does it reproduce on https://github.com/octref/veturpack

**Comment by octref** [comment]
OK, if you can find a reproducible case, open a new issue.
