### ISSUE TITLE
Feature request: syntax highlighting for vue language code blocks in markdown

### ISSUE THREAD

**Issue by R0LA1mRifcF8yAkk** [vuejs/vetur#1024]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.14.3
- VS Code version: 1.29.1

## Problem

When writing documentation for `vue` SFCs, it's often needed to provide examples. It'd be great if those examples would be as readable as the real SFCs.

## Reproducible Case

Create a code block in markdown. Set the block's language to `vue`.

```
    ```vue
      ...

    ```
```

```vue
<template>
  <div class="custom-component">
    <slot />
  </div>
</template>

<script>
  export default {
    name: 'custom-component',
  };
</script>

<style lang="scss">
  .custom-component {
    padding: 1rem;
  }
</style>
```
GitHub highlights it, why shouldn't Vetur?

**Comment by octref** [comment]
That's an upstream issue:
- https://github.com/vuejs/vetur/issues/701
- https://github.com/Microsoft/vscode/issues/44056

@mjbvz Do you have any insights? Should we try to fix this?

**Comment by octref** [comment]
In short, this needs:

1. Markdown uses `vue` grammar injection (doable)
2. Markdown uses the `js`, `html`, `css` grammar injection inside the `vue` grammar injection (doesn't work in VS Code now)

**Comment by mjbvz** [comment]
New fenced code block highlighting can be contributed by extensions, see: https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example

**Comment by R0LA1mRifcF8yAkk** [comment]
Any progress or ideas on this?
