### ISSUE TITLE
Add framework support for Ionic

### ISSUE THREAD

**Issue by jthoms1** [vuejs/vetur#1025]
I would like to start the discussion on what we would need to do to get support for the Ionic Framework Support in Vetur.  We currently have a release of @ionic/vue@0.0.1 out. Because we use a compiler to generate or TS files and the `web-component.json` files for VSCode I would assume that generating the file format needed would be simple.

Thank you!

**Comment by octref** [comment]
The currently recommended way is similar to Quasar:

- Ship tags/attributes JSON files together with NPM dist
- Include a `vetur` key https://github.com/quasarframework/quasar/blob/dev/package.json#L109-L111

This works if there is an `ionic` package that is explicitly stated as (dev)dependency in each Ionic app.

**Comment by jthoms1** [comment]
This would mean that we could add this to all Stencil projects as well.  When we generate the web components we could create the json files as well.  So any developer building collections of components using Stencil would be able to have support in Vetur.

I will give it a try this week. Thanks!

**Comment by yoyo930021** [comment]
Fixed #2483
