### ISSUE TITLE
Use prettier to format template?

### ISSUE THREAD

**Issue by Jimexist** [vuejs/vetur#1028]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version:
- VS Code version:

## Problem

this is not a problem report, but rather a feature request to allow prettier to be configured to format HTML/Vue template instead of prettyhtml because it has more community support.

**Comment by octref** [comment]
#950.
