### ISSUE TITLE
Autocomplete import from single file component to .ts doesn't work

### ISSUE THREAD

**Issue by turbobuilt** [vuejs/vetur#1029]
- [x ] I have searched through existing issues
- [x ] I have read through [docs](https://vuejs.github.io/vetur)
- [ x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: ALL
- Vetur version: 0.14.3
- VS Code version: 1.30.0

## Problem
Hello,

I have a project with .vue files that uses typescript.  However I also have some plain old .ts files.  I need to import the exported component from the .vue file into the .ts file.  When I do it, there is no proper auto import, so I have to manually type the `import x from '...'`.  Is this something that can be fixed in Vetur?

Summary:

Import item exported by .ts into a .vue file - auto import works fine
Import item exported by .vue into a .ts file - auto import does not work

**Comment by octref** [comment]
Please follow #1029.

**Comment by turbobuilt** [comment]
HI @octref I'm still having this problem.  The issue that you tagged was this very issue. Would you please point me in the right direction to the duplicate issue?

Thank you!

**Comment by james-perretta** [comment]
@octref Sorry if I've missed something here, but the link you've posted seems to point back to this issue. Could you please advise me as to where I should look for updates on this issue?

**Comment by octref** [comment]
Sorry pointed to wrong issue: https://github.com/vuejs/vetur/issues/684
