### ISSUE TITLE
How to ignore prettier to format in template?

### ISSUE THREAD

**Issue by chang0022** [vuejs/vetur#1030]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.14.3
- VS Code version: 1.30.0 

## Problem

**Input:**
```
<p class="lottery-btn-text">XX<br>XX</p>
```
**Output:**
```
<p class="lottery-btn-text">XX
  <br>XX
</p>
```

I used `<!-- prettier-ignore -->`, but it don't work.
[https://prettier.io/docs/en/ignore.html](https://prettier.io/docs/en/ignore.html)
I don't know this issue for `vetur` or `prettier`?

But `css` works. 😂

**Comment by octref** [comment]
The template formatter is [prettyhtml](https://github.com/Prettyhtml/prettyhtml), not prettier. Follow #950 please.

**Comment by chang0022** [comment]
Thx
