### ISSUE TITLE
0.14.4 dont work

### ISSUE THREAD

**Issue by ltboy** [vuejs/vetur#1040]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: win64
- Vetur version: 0.14.4
- VS Code version:  1.30.1

## Problem

When I updated to 0.14.4, vscode could not recognize. Vue

**Comment by octref** [comment]
What doesn't work?

**Comment by Duncanxyz** [comment]
I encountered the same problem, and reinstallation is also useless.

**Comment by Duncanxyz** [comment]
@octref Highlighting, Snippet, etc.

**Comment by octref** [comment]
Are you both on Windows? Can you provide a screenshot?

Also any errors in Help -> Developer Tools?

**Comment by Duncanxyz** [comment]
> Anyway, please try this https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#no-syntax-highlighting--no-language-features-working and give more details.

Thanks! [Remove Vetur in your extensions folder and do a clean reinstall.]works. I'm sorry for ignoring the document.

**Comment by octref** [comment]
Like I said, VS Code have had problems installing extension updates...

**Comment by octref** [comment]
Feel free to open new issues if reinstall does not work for you.

**Comment by james868198** [comment]
I encountered the same problem on macOS. So I reinstalled the previous version.
