### ISSUE TITLE
No linting/formatting for <template> section of Vue files

### ISSUE THREAD

**Issue by EPinci** [vuejs/vetur#1041]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows
- Vetur version: 0.14.4
- VS Code version: 1.30.1
- ESLint: 1.7.2
- Prettier-VSCode: *not installed*

## Problem

FAQ pages states that there's no HTML formatting but looking at the changelog looks like that this has been reenabled with "prettyhtml" (that I can find in the default settings as well).

I have this settings in my VS Code:

    "eslint.validate": [
        { "language": "javascript", "autoFix": true },
        { "language": "vue", "autoFix": true },
        { "language": "html", "autoFix": true }
    ],
    "eslint.autoFixOnSave": true,

On all my .vue files:
- The script and style section lints and gets fixed on save
- The template section is never linted nor fixed.

I also checked https://vuejs.github.io/vetur/linting-error.html but still couldn't figure out what is going wrong.

Tried reinstalling vetur, and cleaning the code extension directory.

Thank you.

**Comment by octref** [comment]
> FAQ pages states that there's no HTML formatting but looking at the changelog looks like that this has been reenabled with "prettyhtml" (that I can find in the default settings as well).

Thanks for reporting. Fixed the FAQ.

> The template section is never linted nor fixed.

Vetur contains a built-in version of eslint-plugin-vue. The errors there are not auto-fixable. What you need to do:

- Install a local version of `eslint-plugin-vue`
- Enable eslint

Those errors should be auto-fixable.

**Comment by octref** [comment]
I have updated the docs. If anything is unclear, feel free to reopen.
