### ISSUE TITLE
Vue :class attributes are not being formatted properly

### ISSUE THREAD

**Issue by thesobercoder** [vuejs/vetur#1047]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows 10
- Vetur version: 0.14.5
- VS Code version: 1.30.1

### Panel -> Output -> Vue Language Server

```
Vetur initialized
```

### Screenshot

![error](https://user-images.githubusercontent.com/1915249/50725004-eaf21180-111c-11e9-8e5d-41af49f3b612.png)

## Reproducible Case

- Install Vetur
- Create a new `.vue` file with a `:class` attribute
- Try to format it by <kbd>SHIFT</kbd>+<kbd>ALT</kbd>+<kbd>F</kbd>
- Notice the spacing in the `:class` attribute not getting formatted properly

**Comment by octref** [comment]
Please file an issue for https://github.com/Prettyhtml/prettyhtml, disable the HTML formatter, or switch to js-beautify.
