### ISSUE TITLE
Syntax highlighting fails comment after top-level self-closed block

### ISSUE THREAD

**Issue by dsanders11** [vuejs/vetur#1053]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: All
- Vetur version: 0.14.5
- VS Code version: 1.30.2

## Problem

An HTML comment after a self-closed block causes syntax highlighting for the rest of the file to fail inside of blocks:

```html
<template />  <!-- No template -->

<script>
  // Syntax highlighting here fails
</script>
```

**Comment by octref** [comment]
This works fine enough now, we still have bugs for self-closing `<template />` but that shouldn't be much of an issue

![image](https://user-images.githubusercontent.com/4033249/52734201-78751c80-2f79-11e9-9593-9dcaf4b0dbf6.png)
