### ISSUE TITLE
How to disable format on save

### ISSUE THREAD

**Issue by tejasmanohar** [vuejs/vetur#1056]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Problem

How do I disable formatting on save entirely? I'd rather not make big diffs (eg when extending an existing project without a formatter) :-)

**Comment by octref** [comment]
`"editor.formatOnSave": false`.

**Comment by tejasmanohar** [comment]
I still wanted format on save for other languages/plugins in the project so I ended up setting each fo the vetur formatters to "none" in my preferences. It'd be nice if there was one setting -- "vetur.formatOnSave: false" to completely disable it

**Comment by b4dnewz** [comment]
is possible to disable it per-project?

**Comment by CaptainYouz** [comment]
`"vetur.format.enable": false`

**Comment by padcmoi** [comment]
hi,
per-files if you want @b4dnewz 
` 
 "[vue]": {
    "editor.formatOnSave": true
  },
`

**Comment by dhara15101991** [comment]
Where to add this code? Can anyone please guide me. How to find the config file for it?

**Comment by padcmoi** [comment]
> Where to add this code? I am new to it. Can anyone please guide me? How to find the config file for it on Visual Studio Code?

in settings.json
