### ISSUE TITLE
Formatter for html use prettyhtml

### ISSUE THREAD

**Issue by b1ngx** [vuejs/vetur#1057]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version:0.14.5
- VS Code version:1.30.2

## Problem

Sort results do not match [vue/attributes-order](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/attributes-order.md) and [Vue.js style guide](https://vuejs.org/v2/style-guide/index.html#Element-attribute-order-recommended) 

```
"vetur.format.defaultFormatterOptions": {
    "prettyhtml": {
      "wrapAttributes": true,
      "sortAttributes": true
    }
  }
```

format:
```html
<button
  @click="do"
  class="button"
>submit</button>
```

vuejs sytle guide and eslint expect
```html
<button
  class="button"
  @click="do"
>submit</button>
```

**Comment by thedamon** [comment]
@sumjur the 'sorting' is from [prettyhtml](https://github.com/Prettyhtml/prettyhtml) which according to their docs sorts alphabetically. I agree it would be awesome to have auto-sorting based on the style guide recommendations, but that would be a separate issue and have to be tackled by prettyhtml, which isn't meant to be Vue specific (so maybe through something like `customSortAttributes: []`.

**Comment by sumjur** [comment]
I have report this issue https://github.com/Prettyhtml/prettyhtml/issues/102

**Comment by octref** [comment]
Yeah, there's nothing I can help here. However, eslint-plugin-vue might be able to offer an autofix for such things.
