### ISSUE TITLE
Unable to get autocomplete with CommonJS

### ISSUE THREAD

**Issue by ZiFFeL1992** [vuejs/vetur#1059]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.14.5
- VS Code version: 1.30.2

## Problem
![image](https://user-images.githubusercontent.com/5492960/51146551-7a9f6a80-1857-11e9-8dbd-d23cd5e2a51b.png)

![image](https://user-images.githubusercontent.com/5492960/51146589-986ccf80-1857-11e9-80f7-e1d86c19e3a4.png)

Same file, changing `module.exports` to `export default` makes intellinsense work, is there a way to get it working with `module.exports`?

**Comment by ZiFFeL1992** [comment]
Bump... Can someone help?

**Comment by octref** [comment]
This is not supported. Sorry.

**Comment by thedelk** [comment]
@ZiFFeL1992 I apologize for necro-bumping, but I couldn't help but ask if you'd share your editor settings. Particularly the theme, font, letter-spacing, and line-height. It's gorgeous!

**Comment by ZiFFeL1992** [comment]
> @ZiFFeL1992 I apologize for necro-bumping, but I couldn't help but ask if you'd share your editor settings. Particularly the theme, font, letter-spacing, and line-height. It's gorgeous!

There you go:
```
"workbench.colorTheme": "One Dark Pro",
"editor.fontFamily": "Hack",
"editor.fontSize": 13,
"workbench.fontAliasing": "antialiased",
"editor.lineHeight": 30,
"window.zoomLevel": -2,
```
If you are missing any let me know, I'll be doing a post with all my setup (dotfiles, editor,..) soon, share your email with me and I'll send it you!

**Comment by thedelk** [comment]
@ZiFFeL1992 You're the best! And yes, I'd love to see that when you're done with it. Shoot it over to [ryan@thedelk.com](mailto:ryan@thedelk.com) if you remember.

Thank you again!
