### ISSUE TITLE
Prettier and stylus-supremacy unable to work together

### ISSUE THREAD

**Issue by Meesayen** [vuejs/vetur#1061]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.14.5
- VS Code version: 1.30.2

## Problem

If `stylus-supremacy` is used alongside Prettier to format `.vue` files, only the `<style lang="stylus">` block is formatted, if present; if not present, Prettier correctly formats both `<template>` and `<script>` blocks.

## Reproducible Case

VSCode user settings for Vetur, Prettier, ESLint and stylus-supremacy:
```
  "editor.formatOnPaste": true,
  "editor.formatOnSave": true,
  "vetur.format.defaultFormatter.html": "none",
  "vetur.format.defaultFormatter.css": "none",
  "vetur.format.defaultFormatter.js": "none",
  "vetur.format.defaultFormatter.less": "none",
  "vetur.format.defaultFormatter.postcss": "none",
  "vetur.format.defaultFormatter.scss": "none",
  "vetur.format.defaultFormatter.ts": "none",
  "vetur.format.defaultFormatter.stylus": "stylus-supremacy",
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "typescript",
    {
      "language": "vue",
      "autoFix": true
    }
  ],
  "prettier.eslintIntegration": true,
  "prettier.disableLanguages": ["json"]
```

**Comment by octref** [comment]
Yeah, prettier has no integration with stylus-supremacy. Open an issue for them.

**Comment by Meesayen** [comment]
@octref My thought was that, with that configuration, Prettier would run and format everything BUT the `<style lang="stylus">` block, and then Vetur formatter for Stylus would take care of the rest.
But the reality is that only Vetur formatter works, and Prettier refuses to format `template` and `script` tags, for some reason 🤷‍♂️

Sorry to have wasted your time, I obviously don't know how Prettier and Vetur formatters work together.

**Comment by octref** [comment]
@Meesayen That is indeed an issue, you should follow https://github.com/vuejs/vetur/issues/1121.

More context is at: https://github.com/Microsoft/vscode/issues/41882

The problem: VS Code only allows one formatter per file. Prettier can disable itself but Vetur can't (as of yet), so you want to wait for #1121.
