### ISSUE TITLE
How to use same linting rules for vue-cli and vetur?

### ISSUE THREAD

**Issue by Dealerpriest** [vuejs/vetur#1064]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win 10 x64
- Vetur version: 0.14.5
- VS Code version: 1.30.2

## Problem
I have vetur installed.
I'm creating a project with vue-cli.
When creating the project I chose to use typescript and class style components. I have concluded that vue-cli uses the tslint.json-file when I serve my app (`npm run serve`). But vetur's auto formatting introduces changes/rules that differ from what I've specified in the tslint.json.
Question: How can I make sure that the autoformatting won't conflict with the linting from vue-cli?

## Reproducible Case
Install vue-cli
Install vetur
create a project
autoformat a .vue-file
save
serve project with vue-cli (`npm run vue-cli`)
see how vue-cli outputs a lot of linting warnings.

**Comment by franciscolourenco** [comment]
Related:
- https://github.com/vuejs/vetur/issues/1144
- https://github.com/vuejs/vetur/issues/764

**Comment by octref** [comment]
There are 3 formatters for script section. `prettier`, `prettier-eslint` and `vscode-typescript`. None of them have support for TSLint.

**Comment by octref** [comment]
So your best bet is to configure them to match your linting setting, or follow https://github.com/vuejs/vetur/issues/170.
