### ISSUE TITLE
@babel/plugin-proposal-nullish-coalescing-operator support

### ISSUE THREAD

**Issue by dten** [vuejs/vetur#1065]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: n/a
- VS Code version: n/a

## Problem

I have a project using vue and babel 7 including using `@babel/plugin-proposal-nullish-coalescing-operator` and  `@babel/plugin-proposal-optional-chaining`
I use sublime text and added `vls` as a backend for it with the LSP plugin, but it gives error around the babel proposal code.
I am using `.vue` files and i just have `<script>` not specifying type

Is it supposed to work? I see another issue here implying it would work with babel https://github.com/vuejs/vetur/issues/825

![image](https://user-images.githubusercontent.com/1019038/51406796-0c59f100-1b52-11e9-8836-6b3102f11781.png)
![image](https://user-images.githubusercontent.com/1019038/51406848-33182780-1b52-11e9-9607-bb729b683bee.png)

auto competition etc are working 👍 but these spurious errors are killing it 

also if you're wondering I don't get these errors with my command line linting

**Comment by SagaciousLittle** [comment]
i need help too.

**Comment by octref** [comment]
#825 is unrelated. If this works with TypeScript language server, we might be able to support it. Does it work in JS/TS files in VS Code or https://packagecontrol.io/packages/TypeScript?

**Comment by zh-rocco** [comment]
I miss this error too.

![image](https://user-images.githubusercontent.com/23545037/55770988-e12fcf80-5ab8-11e9-907f-cca559e49390.png)

![image](https://user-images.githubusercontent.com/23545037/55771029-fefd3480-5ab8-11e9-8c0b-b3da5b74c577.png)

[Optional Chaining for JavaScript](https://github.com/tc39/proposal-optional-chaining) is a new feature in stage 1.

The Optional Chaining operator is spelled `?.`.

```js
obj?.prop       // optional static property access
obj?.[expr]     // optional dynamic property access
func?.(...args) // optional function or method call
```

Babel supports this syntax, [Typescript and plugin-proposal-optional-chaining](https://github.com/babel/babel-eslint/issues/727).

It looks like `?.` was treated as `condition ? expr1 : expr2`.

**Comment by octref** [comment]
You need to wait until TS supports it for it to work in Vetur.
TS won't support it until stage 3.

**Comment by zh-rocco** [comment]
> You need to wait until TS supports it for it to work in Vetur.
> TS won't support it until stage 3.

Thanks for your reply.

**Comment by andrew-boyd** [comment]
Is there any known way to add support to this syntax to the TS language server in VS Code? I'm using it in my project and everything is working except Vetur's syntax highlighting. If I disable Vetur and enable a different .vue syntax highlighter the syntax highlight errors go away, however I vastly prefer Vetur for it's overall robustness as a Vue solution.

**Comment by octref** [comment]
Vetur shares the syntax highlighting with TS files, so they should be identical.

**Comment by yepbug** [comment]
```json
"javascript.validate.enable": false,
"eslint.validate": [
    "javascript",
    "javascriptreact"
  ],
// if you use vetur
"vetur.validation.script": false
```
disable vscode's validation, use eslint.

**Comment by ffxsam** [comment]
@yepbug This works, but then TS type-checking in .vue files stops working.

**Comment by ffxsam** [comment]
IMO, Vetur shouldn't be in charge of any validation. It should be able to just rely on eslint 100% for determining what's invalid syntax, that way it's more "pluggable" and we don't have to wait for Vetur updates as the JS spec continues to evolve. Maybe this isn't realistic, as I don't know the inner workings of Vetur, but just a thought.

**Comment by dten** [comment]
https://github.com/tc39/proposal-optional-chaining it's stage 3 now 😁

**Comment by ffxsam** [comment]
Awesome! We really need support for this syntax in VS Code & Vetur.

**Comment by HerrBertling** [comment]
Just came across this and would also like to see this implemented. Anything anyone can do here?

**Comment by ThomasLaveto** [comment]
Is there any progress on this issue?

**Comment by octref** [comment]
https://github.com/vuejs/vetur/issues/1438#issuecomment-536015117

**Comment by MikeMitterer** [comment]
With VUE 2.6.12 this is still an issue - 
I'm using TS 4.0.3

This is how my babel.config.js looks like:

```javascript
module.exports = {
    "presets": [
        [
            "@babel/preset-env",
            {
                "targets": {


                    "node": "current",
                    "browsers": [
                        "last 2 Chrome versions",
                        "last 1 Safari versions",
                        "last 1 Firefox versions"
                    ]

                },
            }
        ],
        "@babel/typescript"
    ],

    "plugins": [
        ["@babel/plugin-proposal-class-properties", {
            // "loose": true
        }],
        "@babel/plugin-proposal-object-rest-spread",
        "@babel/plugin-proposal-optional-chaining",

        "@babel/plugin-proposal-nullish-coalescing-operator"
    ]
};
```

**Comment by octref** [comment]
@MikeMitterer Please open new issue by creating a repro case: https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md
