### ISSUE TITLE
Vetur doesn't recognize .d.ts file

### ISSUE THREAD

**Issue by newcat** [vuejs/vetur#1066]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows 10, Linux
- Vetur version: Tested with 0.14.0 and 0.14.5
- VS Code version: 1.30.2

## Problem

When I import my library in a Vue SFC, it does not recognize the index.d.ts file that is included with the library. On the other hand, when have the same import statement in a normal TS file, it recognizes the index.d.ts file. Either way webpack will run fine, so I guess it is a problem with Vetur.

## Reproducible Case

* Create a new Vue project with Typescript
* `yarn add baklavajs`
* Add the following line to `App.vue` and `main.ts`:
```ts
import { Editor } from 'baklavajs';
```

**Comment by newcat** [comment]
The problem was that apparently Vetur does need the `types` property in the package.json, whereas in normal Typescript files it was enough if there was a .d.ts file with the same name as the .js file in the same directory (e. g. `index.js` and `index.d.ts`).

**Comment by davidbludlow** [comment]
I was able to fix the problem by adding a [triple-slash directive](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html) to the first line of the script section of my .vue file. That is, I put something like `/// <reference path="../my-type-declarations.d.ts" />` right below the line of my .vue file that says `<script lang="ts">`
