### ISSUE TITLE
configuring the autoformatting. I'm truly going crazy here!

### ISSUE THREAD

**Issue by Dealerpriest** [vuejs/vetur#1069]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Problem
I've tried in so many ways now to have the autoformatting on save to work properly in .vue-files.
As of now, it switches between double and single quotes on every other save! I've tried all the combinations of enabled/disabled extensions and configs I can think of.
What is going on?! I'm truly desperate here. I feel I haven't been able to do actual work for 2.5 days. Any suggestions would be much appreciated!
**What I want to achieve:**
Reliably (i.e. not switching between single and double quotes) format my vue-files on save, according to the rules set in one single location.

**Comment by generousdesignr** [comment]
@Dealerpriest Disabling Text Editor / Formatting (On Pase, On Save, On Type) in VS Code settings worked for me.

**Comment by octref** [comment]
Running the command `Developer: Print available formatters...` could help you understand what's going on.

What settings do you have? (VS Code settings and local prettier settings)

**Comment by octref** [comment]
I think you are running into https://github.com/vuejs/vetur/issues/1069 which I'll fix in February.
