### ISSUE TITLE
Code Blocks Gets Unfolded When Formatting is applied

### ISSUE THREAD

**Issue by MG1093** [vuejs/vetur#1071]
- [ x] I have searched through existing issues
- [ x] I have read through [docs](https://vuejs.github.io/vetur)
- [ x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  Win 
- Vetur version: 0.14.5 
- VS Code version: 1.30.2

## Problem

When formatting document (OnSave or otherwise), code that was collapsed get's expanded.  Is it possible for this to stay collapsed, but still format the code.

**Comment by MG1093** [comment]
Some more information:

This behavior only occurs in large file sizes 600-700 lines of code in a file

**Comment by octref** [comment]
This is an upstream issue with VS Code. When your folded region changes VS Code expands it. I think the behavior is reasonable.
