### ISSUE TITLE
eslint-plugin-vue doesn't respect eslint-disable comment in .vue file in VSCode

### ISSUE THREAD

**Issue by lmsurpre** [vuejs/vetur#1074]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.12.6
- VS Code version:  1.25.1

## Problem

eslint-plugin-vue doesn't recognize eslint-disable comment within VSCode

I am just learning Vue.js and I loaded up the magical vue-element-admin (https://github.com/PanJiaChen/vue-admin-template/blob/54c2b2848ef4f37189e80b3a2673539895c6f4f9/src/views/layout/components/Sidebar/Link.vue#L3) in VSCode.

Once I installed this plugin, it started complaining about this one html template.  Given the existing comment, it looks like the issue is known/expected and should be ignored:

<img width="779" alt="image" src="https://user-images.githubusercontent.com/5478798/51934592-f3fb9900-23d1-11e9-9881-4587890efde6.png">

When I remove the comment, I start seeing the error reported on the command line as well.  However, when the comment exists in the code, the build is clean from the command line.

## Reproducible Case

1. checkout https://github.com/PanJiaChen/vue-admin-template, open in VSCode, and navigate to `src/views/layout/components/Sidebar/Link.vue`

Why doesn't it honor the eslint-disable comment?

**Comment by octref** [comment]
Please open an issue for eslint-plugin-vue.

**Comment by lmsurpre** [comment]
Can you share any information that I can use to point to this being an issue with the eslint-plugin-vue and not specific to the VSCode integration?

**Comment by octref** [comment]
I see your problem. Please read https://vuejs.github.io/vetur/linting-error.html

Vetur bundles a version of eslint-plugin-vue for beginner usage. It's outdated and doesn't honor eslint-disable (I'll update it). When you need more customization and are using locally installed eslint-plugin-vue, you need to do `"vetur.validation.template": false`.

**Comment by simeon9696** [comment]
Hi @octref Where would I need to put that line?

**Comment by octref** [comment]
@simeon9696 https://code.visualstudio.com/docs/getstarted/settings
