### ISSUE TITLE
prettier can format vue, but I can not use it for Vue templates

### ISSUE THREAD

**Issue by qiulang** [vuejs/vetur#1076]
- [X] I have searched through existing issues
I found https://github.com/vuejs/vetur/issues/491.   The issue was open at 2017, But prettier has supported vue & html, https://github.com/prettier/prettier/releases/tag/1.15.0 
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

- Platform: macOS
- Vetur version: 0.14.5
- VS Code version:1.30.2

## Problem

We just want to use prettier to format our vue codes because we use prettier extensively for all our codes and we don't want to introduce another format tool. 

But vetur uses prettyHtml for Vue templates and I can't change it to vue, .i.e I can not set  `"vetur.format.defaultFormatter.html": "prettier",`

So now when I save vue codes, vscode will format my code using prettyHtml, then our lint process will use prettier to format codes again. The result is quite different.

**Comment by qiulang** [comment]
I tried prettier, prettyhtml and vscode save on format with vetur and got 3 different results!  
If  I run `prettyhtml src/App.vue`, even though prettyhtml uses my prettiers setting, it indent all 3 sections <style> <template> <script>, while prettier just indent <template> section.

vetur format <template> section using prettyhtml (e.g. tabWidth 2 by default), format  <style> and  <script> sections using prettier. So it is different than the other two.

**Comment by octref** [comment]
You can follow #950 for using prettier in template.
