### ISSUE TITLE
`caret-color` CSS property not highlighted properly

### ISSUE THREAD

**Issue by benweedon** [vuejs/vetur#1078]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows 10 17763.253
- Vetur version: 0.14.5
- VS Code version: 1.30.2

## Problem

Does not syntax highlight CSS property `caret-color`:

![image](https://user-images.githubusercontent.com/2928612/52168613-ec453880-26e0-11e9-9f64-39a5a023f35d.png)

![image](https://user-images.githubusercontent.com/2928612/52168663-62e23600-26e1-11e9-81b5-a8be823cfe7b.png)

## Reproducible Case

Use the code shown in the screenshot (and included below) in a Vue single-file component's `<style>` section. This also repros with sass and less CSS flavors. Note hovering over the `caret-color` property still shows information.

```css
.testclass {
  caret-color: transparent;
  color: red;
}
```

**Comment by octref** [comment]
This is an [upstream issue](https://github.com/Microsoft/vscode/issues/66775#issuecomment-459135985) and has been fixed:

![image](https://user-images.githubusercontent.com/4033249/52432875-83830500-2ac0-11e9-9ede-c96ca16e0ce3.png)
