### ISSUE TITLE
Completion for Vue interpolations in HTML

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#1083]
This tracks completion for template interpolations inside Vue template interpolations.

Problem:

Currently there is no completion for the 4 places marked with `|`

```vue
<template>
  <div v-if="|" @click="|" :foo"|">{{ | }}</div>
</template>
```

The goal is to provide completions for `[ props | data | method | computed]`, and also `$store` / `$router` etc.

The plan is to create a virtual file that TypeScript Language Service can understand and get the current `this` completion and filter it down to useful items:

![image](https://user-images.githubusercontent.com/4033249/52523843-b0fbba00-2c4a-11e9-9f01-aa33e4846946.png)

**Comment by octref** [comment]
Here you go.

![template-completion](https://user-images.githubusercontent.com/4033249/52976246-97125380-337d-11e9-82b8-a1af506ffdf1.gif)

**Comment by hmexx** [comment]
Wow.. that looks amazing!!! Is there a flag to enable it though? I can't seem to get any completion after upgrading vetur on my end.

**Comment by octref** [comment]
@hmexx Can you put your setup in a repo and open a new issue? I probably need to do more work to support vue-class-component.

**Comment by victorgarciaesgi** [comment]
@octref Yeah that was my question. I suppose it does not work when using class component style?
Amazing work by the way!

**Comment by hmexx** [comment]
I can confirm that when I switch one of my components to non-class style it starts working, although that little type/preview box on the right (e.g. "My foo that does absolutely nothing") does not show up. All the props and methods show up though.

I will investigate further before submitting an issue ticket.

**Comment by zakkor** [comment]
That looks amazing. This is a naive question, but would this apply to any template lang supported by Vetur (for example Pug), or just HTML?

**Comment by jackkoppa** [comment]
Absolutely fantastic. Thank you, @octref, this is huge for us 😀

**Comment by octref** [comment]
> Do you still need a reproduction repo for testing vue-class-component?

@hmexx It's ok — I opened #1105. I know it wouldn't work.

@zakkor Just HTML for now. There is no language server for Pug, so completion does not work in it.

**Comment by ZiFFeL1992** [comment]
It doesn't work if we use `module.exports`, check: https://github.com/vuejs/vetur/issues/1059
