### ISSUE TITLE
Issue w/ 4 spaces (still no resolution so far as I can tell)

### ISSUE THREAD

**Issue by mikeerickson** [vuejs/vetur#1087]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Mac
- Vetur version: latest
- VS Code version: 1.31.0 Insiders

## Problem

I am seeing the error of too many indents because it is assuming 2 when it should be 4 in my `.vue` files

![image](https://user-images.githubusercontent.com/183153/52539694-1b3d5900-2d36-11e9-904d-53048b06a4c4.png)

**Comment by octref** [comment]
Config?

**Comment by mikeerickson** [comment]
I too have been having this issue and basically gave up.

**Comment by octref** [comment]
`"vetur.format.options.tabSize": 2`.
