### ISSUE TITLE
How to update version to 0.15?

### ISSUE THREAD

**Issue by aboutjquery** [vuejs/vetur#1092]
- [ 1] I have searched through existing issues
- [1 ] I have read through [docs](https://vuejs.github.io/vetur)
- [1 ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version: 0.12.4
- VS Code version: 1.23.1

## Problem

uninstall and search vetur plugin, show the lastest version is 0.15.0, but after i click install, my plugin show the version is 0.12.4

**Comment by Patcher56** [comment]
Try updating vscode to the latest version (depending on your platform - you didn't mention it in the issue description)

**Comment by aboutjquery** [comment]
problem solved by update vscode to lastest version.
