### ISSUE TITLE
Element attribute break highlighting when using "`" on single line reference values.

### ISSUE THREAD

**Issue by stgogm** [vuejs/vetur#1095]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: 0.15.1
- VS Code version: 1.31.1

## Problem

Element attribute break highlighting when using <code>&#96;</code> on single line reference values.

![image](https://user-images.githubusercontent.com/2774311/52789530-d3bf1180-3042-11e9-9227-5ae40219ed65.png)

If I add, let's say, a parenthesis, it works as expected:

![image](https://user-images.githubusercontent.com/2774311/52789651-31ebf480-3043-11e9-975c-310d95101124.png)

We use <code>&#96;</code> instead of `'` or `"` because it's easier to switch between single and multi-line values and the Pug compiler converts them to `"` anyways.

## Reproducible Case

Create a Vue component and add the following:

```
<template lang="pug">
section
  router-link.header.item(to=`/`)
    img(
      src=`/images/navbar-icon.svg`
      :alt=`title`
      )

  .right.menu
    navbar-menu
</template>
```

and everything down from the `.right.menu` element should be wrongly colored.

**Comment by octref** [comment]
Yeah we are just starting working on grammars, TextMate grammar is tricky so it takes some time to get it right...

@Patcher56 Wanna take a look?

**Comment by Patcher56** [comment]
I now know what the problem is. The problem is the [template literal tag syntax](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/template_strings#Tagged_Template-Strings). Javascript means the ` is the start of a tag function for strings, so it starts syntax highlighting it like this.

A simple workaround: just put a space at the end of the string, so js knows there is no string tag:
e.g.
```vue
<template lang="pug">
section
  router-link.header.item(to=`/`)
    img(
      src=`/images/navbar-icon.svg`
      :alt=`title `
      )

  .right.menu
    navbar-menu
</template>
```

If we want to prevent js from syntax highlighting as a string literal tag, the highlighter would be a bit more trickier, I think. What do you think @octref?

Nevertheless I simplified the vue-directive syntax highlighting a bit. Included in my last PR (#1093).

**Comment by octref** [comment]
Sorry just wondering, why you don't write this?

```vue
<template lang="pug">
section
  router-link.header.item(to="/")
    img(
      src="/images/navbar-icon.svg"
      :alt="title"
      )

  .right.menu
    navbar-menu
</template>
```

Why do you have to use backtick?

**Comment by Patcher56** [comment]
> We use `` ` `` instead of `'` or `"` because it's easier to switch between single and multi-line values and the Pug compiler converts them to `"` anyways.

I would also prefer to just use `'` or `"`

**Comment by octref** [comment]
> If we want to prevent js from syntax highlighting as a string literal tag, the highlighter would be a bit more trickier, I think. What do you think @octref?

Yeah you can give it a try, I suggest using negative lookahead on the `begin` clause.

But I don't think in general we should support users writing `` ` ``, since there is no observed benefit and they can just use `"` and `'` instead.

**Comment by octref** [comment]
> We use `` ` `` instead of `'` or `"` because it's easier to switch between single and multi-line values and the Pug compiler converts them to `"` anyways.

Thanks, just see that.

I have run into https://github.com/Microsoft/vscode/issues/20488 quite often. The inner grammar can leak very easily and make the rest of the document corrupt.

@Patcher56 You might want to give grammar injection a try, see https://github.com/mjbvz/vscode-comment-tagged-templates for an example.

**Comment by Patcher56** [comment]
Thanks, I will take a look.

**Comment by Patcher56** [comment]
We decided to drop support for the backtick literal as it makes the whole plugin a lot more complex.
Please use only the `'` or `"` symbol in the future. If you have so much code to make it multi-line, just put it into the `methods` section and call the method from the template.

Also discussed in PR #1093

**Comment by stgogm** [comment]
Sounds fair! Thank you!
