### ISSUE TITLE
Create a test environment for syntax highlighting.

### ISSUE THREAD

**Issue by Patcher56** [vuejs/vetur#1096]
As discussed in PR #1093 we need a test environment to test the grammar against any errors when changing something.

I like the idea how the guys from the [comment tagged templates](https://github.com/mjbvz/vscode-comment-tagged-templates/tree/master/test) solved.

They used a command from vscode to read out the colors and compared them to how they should be.

I will try this and commit it in the next few days.

**Comment by Patcher56** [comment]
Added basic automated grammar tests inspired by [vscode-comment-tagged-template](https://github.com/mjbvz/vscode-comment-tagged-templates).
It works like this:
- when running yarn test it checks if a `results` folder exists on `test/grammar`.
- if it does not exist, it creates some json files containing the color codes of the test files.
- if it exists, it checks if the color codes in results are the same as in the tested vue files
- if we change grammars and the tests fail and we are sure the syntax highlighting is right, we only have to delete the corresponding .json file and recreate it with `yarn test`

**Comment by octref** [comment]
Thanks, let me take a look tomorrow and get back to you. This is much needed for continued grammar fixes / development.
