### ISSUE TITLE
language server  'typeParameters' of undefined

### ISSUE THREAD

**Issue by sionmike** [vuejs/vetur#1097]
## Info

- Platform: Win
- Vetur version:0.15.1
- VS Code version:1.31
- language: typescript

## Problem

vetur always crash 

![image](https://user-images.githubusercontent.com/21998032/52896241-c307ca80-31ff-11e9-8500-540df70c3f3a.png)

**Comment by octref** [comment]
Should be fixed if you are using a more recent version of TS in your workspace and with   `"vetur.useWorkspaceDependencies": true`.
