### ISSUE TITLE
Intellisense is not working when .d.ts file contains import statement

### ISSUE THREAD

**Issue by Nandiin** [vuejs/vetur#1098]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.15.1
- VS Code version: 1.31.1

## Problem

![screen shot 2019-02-17 at 2 54 02 am](https://user-images.githubusercontent.com/10903833/52903962-2d505780-3260-11e9-9297-be54eccd4b03.png)

Intellisense is not working in certain case (I suppose it is related to `import` statement in `.d.ts` file)

>*If you're interested, the "1" after error icon in the status bar is about the incomplete statement `a.` in `index.ts`.*
><details><summary>screenshot of this irrelavant error</summary>
>
> ![screen shot 2019-02-17 at 3 32 03 am](https://user-images.githubusercontent.com/10903833/52904274-9df97300-3264-11e9-8fa6-8872ff021704.png)
></details>

## Reproducible Case

Four files for reproduction:

<details><summary><code>lib/foo.d.ts</code></summary>

```typescript
export type Foo = { prop: number }
````

</details>
<details><summary><code>lib/index.d.ts</code></summary>

```typescript
export const foo: import('./foo').Foo
```

</details>
<details><summary><code>index.ts</code></summary>

```typescript
import { foo } from './lib'

const a = foo
```

</details>
<details><summary><code>index.vue</code></summary>

```vue
<script lang="ts">
import { foo } from './lib'

const a = foo
</script>
```

</details>

<br>
<br>

**You may like to clone this reproduction [repo](Nandiin/vetur-intellisense-issue), or, generate those files with following script**

*IMPORTANT: RUN THIS SCRIPT IN AN EMPTY DIRECTORY*
```sh
mkdir lib
echo "export type Foo = { prop: number }" > lib/foo.d.ts
echo "export const foo: import('./foo').Foo" > lib/index.d.ts
echo -e "import { foo } from './lib'\nconst a = foo" > index.ts
echo -e "<script lang="ts">\nimport { foo } from './lib'\nconst a = foo\n</script>" > index.vue
```

### Steps
1. Hover over the `a` variable in `index.ts` file. There would be a popover widget indicating `a` is of type `Foo`
2. Hover over the `a` variable in `index.vue` file. There would be a popover widget indication `a` is of type `any`, which is WRONG.
3. In `index.ts` file, type in `a.`, then a popover shows and says there is a `prop` property of type `number` under variable `a`
4. Repeat step 3 inside `index.vue` and there would be no popover.

**Comment by Nandiin** [comment]
In addition, intellisense is working even in a `.js` file.

**Comment by Nandiin** [comment]
After digging into the source code, I found that the language server (i.e. `VLS`) is using `typescript@2.8.4`. And if I switch the `typescript.tsdk` of the vscode to a local typescript of version `2.8.4`, then same failure would reproduce in `*.ts` file.

![image](https://user-images.githubusercontent.com/10903833/52910767-3cbeb780-32d7-11e9-8b0f-8e2d35d24265.png)

**Comment by Nandiin** [comment]
After upgrading typescript dependency to ^3.3.0, fixing a few typescript-api-change related errors, and adopting the solution in #1045, it's now working in my machine.

I also tested my [fork](Nandiin/vetur) in a standalnoe [travis CI environment](https://travis-ci.org/Nandiin/vetur), but, sadly, it fails one test on linux (while passing all tests on macOS). I cannot proceed any further as I don't have a linux machine at my hand .

I'm leaving this issue open just in case anyone else would come to similar problem.

**Comment by octref** [comment]
Thanks. This will be resolved after we allow you to use a more recent version of TS with #682 and maybe upgrading Vetur to depend on a more recent TS.
