### ISSUE TITLE
Option for completing in CamelCase

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#1102]
Currently if you import a component in CamelCase, such as:

```js
export default {
  components: {
    CounterStrike
  }
}
```

Vetur will offer kebab case completion for `<counter-strike>`.
This option should toggle between camel case and kebab case.

**Comment by rickyruiz** [comment]
@octref When you set `"vetur.completion.tagCasing": "initial"`, the child component tag/attribute completion stops working.

Platform: Win 10, Vetur version 0.16.1

![image](https://user-images.githubusercontent.com/12017329/53045109-06557980-344a-11e9-9327-052a55ecea1c.png)

![image](https://user-images.githubusercontent.com/12017329/53045146-1e2cfd80-344a-11e9-8610-ab33dddc9b55.png)
___

These new releases are awesome, thanks for your hard work! 

I can submit this as a new issue with more details if you want me to.

**Comment by octref** [comment]
Ah I see I'll fix that.
