### ISSUE TITLE
Support analyzing vue-class-component

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#1105]
Continuing #1083

`ComponentInfo` is not able to analyze `vue-class-component` yet.

The source looks like below, so it needs a different AST visitor. Maybe we can use typing from `vue-class-component` to analyze it.

```ts
@Component({
  props: {
    propMessage: String
  }
})
export default class App extends Vue {
  // initial data
  msg = 123

  // use prop values for initial data
  helloMsg = 'Hello, ' + this.propMessage

  // lifecycle hook
  mounted () {
    this.greet()
  }

  // computed
  get computedMsg () {
    return 'computed ' + this.msg
  }

  // method
  greet () {
    alert('greeting: ' + this.msg)
  }
}
```

**Comment by dennis2k** [comment]
It is also important to note that vue-class-component is often used along with the [vue-property-decorator](https://github.com/kaorun343/vue-property-decorator) for defining props

**Comment by hmexx** [comment]
Is this going to be a tough one or are we likely to see in a near-future release?

**Comment by octref** [comment]
I'd like to limit this issue to only vue-class-component, which is officially supported.

There are many decorator libraries such as https://github.com/kaorun343/vue-property-decorator, https://github.com/itsFrank/vue-typescript, and one in the upcoming Vue 3 https://github.com/vuejs/rfcs/pull/17. Supporting them all is likely a lot of maintenance.

**Comment by hmexx** [comment]
> 
> 
> I'd like to limit this issue to only vue-class-component, which is officially supported.
> 
> There are many decorator libraries such as https://github.com/kaorun343/vue-property-decorator, https://github.com/itsFrank/vue-typescript, and one in the upcoming Vue 3 [vuejs/rfcs#17](https://github.com/vuejs/rfcs/pull/17). Supporting them all is likely a lot of maintenance.

I think that's a reasonable compromise.

**Comment by yoyo930021** [comment]
Hi anyone, I publish self-maintenance vscode extension.
This extension will be maintained until Vetur is reactivated.

https://marketplace.visualstudio.com/items?itemName=yoyo930021.vuter
