### ISSUE TITLE
 Add named v-slot shorthand # 

### ISSUE THREAD

**Issue by davidbernegger** [vuejs/vetur#1108]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  Win/macOS/Linux
- Vetur version: 0.15.1
- VS Code version: --

## Problem

Add the named slot shorthand # for  [v-slot](https://vuejs.org/v2/guide/components-slots.html#Named-Slots-Shorthand) 

![image](https://user-images.githubusercontent.com/16232537/53082846-06af4c80-34fe-11e9-8ef7-48d5b77e5753.png)

**Comment by octref** [comment]
@Patcher56 You might be interested, should be a relatively easy fix.

**Comment by TuringJest** [comment]
Is this not solved yet? Would like to use the shorthand, so we don't have to mix them with the other shorthands.
