### ISSUE TITLE
Syntax Highlighting in CSS blocks not working for @apply

### ISSUE THREAD

**Issue by benwinding** [vuejs/vetur#1109]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: 0.16.1
- VS Code version: 1.31.1

## Problem

Using the valid `@apply` function in a css block, as shown in [tailwind.css](https://tailwindcss.com/docs/what-is-tailwind/)

### Valid Css Code

``` html
<style scoped lang="css">
.container {
  @apply min-h-screen flex justify-center items-center text-center mx-auto;
}
</style>
```

### Broken Syntax Highlighting
![](https://i.imgur.com/HLKNhW3.png)

**Comment by octref** [comment]
This is not working in VS Code either. You should open an issue in VS Code repo.

![image](https://user-images.githubusercontent.com/4033249/53131154-da58f780-3520-11e9-922b-c41a1e51a6e2.png)
