### ISSUE TITLE
I would suggest changing name to vetur for Vue for better SEO

### ISSUE THREAD

**Issue by Almenon** [vuejs/vetur#1111]
See title - you would get more users if you changed your extension name to "vetur for Vue" so your extension appears when people search for vue in the extension search.  Currently when you search for vue your extension does not show up.

This worked great for me when changing [AREPL](https://marketplace.visualstudio.com/items?itemName=almenon.arepl#overview) to "AREPL for python"

On the other hand, you already have over 9 million installs so obviously getting users is not a major problem ¯\\_(ツ)_/¯

**Comment by octref** [comment]
#42890 and I won't fix it. We talked to MarketPlace team and they would fix their search.

**Comment by octref** [comment]
I meant to link to https://github.com/microsoft/vscode/issues/42890.
