### ISSUE TITLE
Extension breaks postcss syntax highlighting in *.css files

### ISSUE THREAD

**Issue by mattwaler** [vuejs/vetur#1115]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: MacOS
- Vetur version: 0.16.12
- VS Code version:  1.31.1

## Problem

When extension is installed, syntax highlighting for .css files is broken. Most specifically, [this extension](https://marketplace.visualstudio.com/items?itemName=cpylua.language-postcss). 

When opening a new VS code window, the .css file looks like this:

![re-open](https://user-images.githubusercontent.com/32300026/53266284-53398a00-36ae-11e9-8e02-5dfad92e589b.png)

You are able to fix it temporarily by disabling vetur, which then looks like this:

![re-enable](https://user-images.githubusercontent.com/32300026/53266273-4c127c00-36ae-11e9-95f7-053e29ee57ae.png)

## Reproducible Case

1. Install Vetur and language-postcss
2. Add files.associations to settings, set *.css to postcss
3. Use postcss plugins in a .css file (it may function properly before closing and re-opening VS Code)
4. Completely exit VS Code, and reopen the same .css file with postcss syntax
4. Toggle disable the vetur extension, and see highlighting switch from working to broken

**Comment by octref** [comment]
This is because both extension add a language called `postcss`. I renamed Vetur's to `vue-postcss`.

**Comment by mattwaler** [comment]
Thanks for the insanely fast fix.

Is there any possibility of using [this extension's](https://github.com/cpylua/vscode-language-postcss) syntax highlighting? It is much more reliable/expansive/consistent.

Thanks for making such an awesome extension!

**Comment by octref** [comment]
@mattwaler I didn't do any comparisons, do you have any cases in which that grammar is better than the one I include?

Here's what I'm using now.

**Comment by mattwaler** [comment]
@octref Yes, I have witnessed many cases where the mentioned extension highlights properly and Vetur does not. These screenshots illustrate a few cases, using very popular postcss plugins like tailwind and easy-media-queries:

## Vetur
![vetur-highlighting](https://user-images.githubusercontent.com/32300026/54482526-59d5a000-481b-11e9-88a9-4bce26157f70.jpg)

## VSCode Language PostCSS
![language-postcss-highlighting](https://user-images.githubusercontent.com/32300026/54482525-59d5a000-481b-11e9-9b1d-5fcd4380c9c6.jpg)

**Comment by octref** [comment]
The grammar seems to be taken from https://github.com/hudochenkov/Syntax-highlighting-for-PostCSS/blob/master/Syntaxes/PostCSS.tmLanguage. I replaced grammar and added credit.

I would need to change the scope to `source.css.postcss` from `source.postcss`. I'm not seeing the author of that extension fixing grammar issues so I don't want to depend on it yet.

**Comment by mattwaler** [comment]
Awesome! Thank you so much for all the extra effort. When can we expect to be able to update and reflect these changes?

**Comment by octref** [comment]
Probably later this week.

**Comment by mattwaler** [comment]
@octref

Looks amazing! Thanks so much for the fast push and additional stuff. Love using the extension.
