### ISSUE TITLE
Vue Language Server Crash on component tag with empty :is

### ISSUE THREAD

**Issue by kdlslyv** [vuejs/vetur#1116]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.16.2
- VS Code version: 1.31.1

## Problem

Mild inconvenience, if you do this, which doesn't make sense anyway:

`<component :is=""></component>`

it'll crash immediatly after.

![ErrorMessage](https://user-images.githubusercontent.com/13890151/53277691-7b080c80-3705-11e9-9395-6b1301a403f6.png)

## Reproducible Case

any *.vue file, write `<component :is=""></component>` it'll crash

**Comment by octref** [comment]
This is an error with https://github.com/vuejs/eslint-plugin-vue. Please report to them.

If you disable `vetur.validation.template` and don't use ESLint, you wouldn't see the error.
