### ISSUE TITLE
Question: Does VSL support JS language too?

### ISSUE THREAD

**Issue by mtangoo** [vuejs/vetur#1119]
I couldn't find instruction as to where should I ask but I need to use VSL with my custom editor. I wanted to know if the Server also supports normal JS file (like Code completion and goto for example) for normal JS/ES6 file. I guess it does since Vue is written in JS. But wanted to confirm the JS capabilities of the language server.

Thank you for the free server and I apologize if I was to ask somewhere else!

**Comment by octref** [comment]
It doesn't support normal JS files. For that, you need https://github.com/Microsoft/TypeScript/wiki/Using-the-Language-Service-API.

**Comment by mtangoo** [comment]
Thanks a lot for the answer!
