### ISSUE TITLE
insertSpaceBeforeFunctionParenthesis for prettier js formatter!

### ISSUE THREAD

**Issue by FarzadKaramouz** [vuejs/vetur#1122]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.16.2
- VS Code version: 1.31.1

## Problem

Currently when using prettier for js formatter, it removes spaces before function parenthesis in .vue files in script section.
I need "insertSpaceBeforeFunctionParenthesis" with prettier js formatter not vscode-typescript.
Is there any options in prettier to solve this problem?

**Comment by octref** [comment]
No, you should use `prettier-eslint` and ESLint will add the space (autofix) after prettier formatting.
