### ISSUE TITLE
Space at end of </template> close tag breaks syntax highlighting

### ISSUE THREAD

**Issue by Spetnik** [vuejs/vetur#1123]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows 10 17763.3116
- Vetur version: 0.16.2
- VS Code version: 1.31.1

## Problem

When there is whitespace in the </template> close tag, subsequent <script> or <style> block content loses its syntax highlighting.

## Reproducible Case
Create a .vue file with the following content:
```
<template>
  
</template>

<script>
  let a = 1;
</script>
```
![image](https://user-images.githubusercontent.com/1311919/53408320-cdeef780-3983-11e9-807f-0e0943b21191.png)

The `let a = 1;` line is highlighted, as it should be.

Now add a space to the `</template>` tag so it looks like this: `</template >`.
![image](https://user-images.githubusercontent.com/1311919/53408341-d9dab980-3983-11e9-8ac6-391e232bb709.png)

The script loses its highlighting.

**Edit:** This also occurs for nested `<template>` tags within the root template. I was unable to reproduce this issue with other tags.

**Comment by Patcher56** [comment]
Thank you for posting.
Is there a reason you have to put a space in there? Otherwise I see no problem, just delete the space.

**Comment by Spetnik** [comment]
Personally, I detest the space and I'm not even sure how it got there - I think it was automatically formatted that way or something (in my case it was a line-break). But it is valid syntax, so shouldn't it be supported? It seems to work for all other tags.

**Comment by Patcher56** [comment]
Ok, I will take a look - thanks for explanation.

**Comment by sbrieuc** [comment]
I would also like to see this fixed because indeed using Prettier it's often that the closing `>` is put on a newline, which breaks syntax highlighting for `<script/>` and `<style/>`

```
<template v-if="hasNextPage"
  >|</template
>
```

**Comment by baixiaoyu2997** [comment]
> I would also like to see this fixed because indeed using Prettier it's often that the closing `>` is put on a newline, which breaks syntax highlighting for `<script/>` and `<style/>`
> 
> ```
> <template v-if="hasNextPage"
>   >|</template
> >
> ```

same problems

**Comment by oddeirik** [comment]
Experiencing the same issue with a vue-cli created project where eslint/prettier is used.

Running lint the template tags tend to put the closing `>` on a newline, which breaks syntax highlighting for everything after the template section.

This is my eslint configuration, apart from the no-console rule I think it's pretty close to the default when you add prettier linting:
```
{
    "root": true,
    "env": {
        "node": true
    },
    "extends": [
        "plugin:vue/essential",
        "eslint:recommended",
        "@vue/prettier"
    ],
    "rules": {
        "no-console": 0
    },
    "parserOptions": {
        "parser": "babel-eslint"
    }
}
```

**Comment by oller** [comment]
Has anyone resolved this yet?  I'm sure i'd previously done something to stop this happening, but coming back to an old project, every auto-fix on save, puts this odd template formatting back in which breaks syntax highlighting!

**Comment by octref** [comment]
Tracking in #1211 instead. Fix is not trivial, see https://github.com/vuejs/vetur/issues/1211#issuecomment-490596644.
