### ISSUE TITLE
Stylus syntax highlight problem

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [vuejs/vetur#1124]
![image](https://user-images.githubusercontent.com/29608698/53441455-aa5c9900-39e5-11e9-85c0-e1f3d73ea2e7.png)

If you require or import something, put a comma, and put nothing after it the closing style tag gets weird its triggers me, anyway to solve it?

**Comment by Patcher56** [comment]
Can you post a reproducable snippet? Why didn‘t you use the issue template?
Need more info and pkease use the issue template.

**Comment by diego-lipinski-de-castro** [comment]
Well... its quite a simple problem, you can see in the image, but if I need to spend 10 minutes to post a issue, ok, will do it
