### ISSUE TITLE
Importing JSON files with destructuring syntax, gives linting error in .vue files

### ISSUE THREAD

**Issue by wahidrahim** [vuejs/vetur#1125]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux - Ubuntu 18.04
- Vetur version: 0.16.2
- VS Code version: 1.31.1

## Problem

Error in .vue file
![screenshot from 2019-02-27 14-34-34](https://user-images.githubusercontent.com/7417976/53517684-3978b800-3a9d-11e9-837d-996c2b832324.png)

No error in .ts file
![screenshot from 2019-02-27 14-38-02](https://user-images.githubusercontent.com/7417976/53517788-7b096300-3a9d-11e9-824a-0e3f20f69bd6.png)

## Reproducible Case
https://github.com/wahidrahim/vetur-json-destructuring-bug

**Comment by octref** [comment]
Seems resolved as of using TS 3.3.
Try `"vetur.useWorkspaceDependencies": true`.
