### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AltangerelG** [vuejs/vetur#1126]
[octref.vetur-unresponsive.cpuprofile.txt](https://github.com/vuejs/vetur/files/2912980/octref.vetur-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `vetur`
- Extension Version: `0.16.2`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/da-6/octref.vetur-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by mvolkmann** [comment]
#1051 is related.

**Comment by AltangerelG** [comment]
I read all the comments of #1051 . So the solution hasn't found yet. I'll inform you when I found any solution.

**Comment by mubaidr** [comment]
https://github.com/vuejs/vetur/issues/1051#issuecomment-470421284

**Comment by octref** [comment]
Sorry the profile would not be useful because it's the Language Client's profile. You need to profile the Language Server. Follow #1051 and #547 instead.
