### ISSUE TITLE
When a single vue file is too large, the Chinese input will be stuck

### ISSUE THREAD

**Issue by lhajh** [vuejs/vetur#1128]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.16.2
- VS Code version: 1.31.1

## Problem

When a single vue file is too large, the Chinese input will be stuck

![](http://ww1.sinaimg.cn/large/c1d3f45dly1g0m40aogtog20bn02sb2a.gif)

**Comment by octref** [comment]
There's no reproducible case so I can't help. Sorry.

**Comment by moliyadi** [comment]
@lhajh I have the same problem, have you fixed it?Thanks
