### ISSUE TITLE
TypeScript does not work as intended

### ISSUE THREAD

**Issue by vstrimaitis** [vuejs/vetur#1130]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.16.2
- VS Code version: 1.31.1
- TypeScript version: 3.3.1

## Problem

When I use TypeScript inside the `script` tag of a SFC, TypeScript support does not seem to work as intended. Two concrete examples:
* Unused values (imports, variables) cause an error instead of a warning. Also, the error cannot be automatically fixed (whereas the warning can):
    * Expected behaviour (also note that these can be auto-fixed):
![Expected behaviour](https://user-images.githubusercontent.com/14166032/53573555-6056ed00-3b76-11e9-9e6f-0295012f4dd5.png)
    * Actual behaviour:
![Actual behaviour](https://user-images.githubusercontent.com/14166032/53573556-6056ed00-3b76-11e9-9c56-511f2f076656.png)
* Renaming symbols does not work (it does work in an identical pure TS example).

## Reproducible Case

1. Setup the project like this:
    ```
    $ vue create vetur-ts-bug-example

    Vue CLI v3.4.1
    ? Please pick a preset: Manually select features
    ? Check the features needed for your project: Babel, TS, CSS Pre-processors, Linter
    ? Use class-style component syntax? Yes
    ? Use Babel alongside TypeScript for auto-detected polyfills? Yes
    ? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): Sass/SCSS (with node-sass)
    ? Pick a linter / formatter config: TSLint
    ? Pick additional lint features: (Press <space> to select, <a> to toggle all, <i> to invert selection)Lint on save
    ? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In dedicated config files
    ? Save this as a preset for future projects? (y/N) No
    ```
2. Add `Prop` (or some other unused import) to the imports list.
3. Add `"noUnusedLocals": true` to `tsconfig.json`
4. Copy the script part from `src/App.vue` to `src/App2.ts`

I also created a repository with the steps already executed: https://github.com/vstrimaitis/vetur-ts-bug-example.

This example should show that everything works as expected in the `App2.ts` file, but not in the `App.vue` file.

**Comment by octref** [comment]
With #682 (done) #1163 (not done), #1063 becomes possible (show unused).

#97 is for rename support.

Thanks for the good repro. I'll definitely come back to this issue when I'l fixing them.
