### ISSUE TITLE
Autosuggestions in TypeScript project pop up at wrong times

### ISSUE THREAD

**Issue by ffxsam** [vuejs/vetur#1131]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS 10.14.3
- Vetur version: 0.16.2
- VS Code version: 1.31.1

## Problem

Working with Vue + TypeScript, the autocomplete is popping up at unnecessary times, with irrelevant suggestions. It shouldn't pop up when I'm typing a closing quotation mark, for example:

![screencap](https://user-images.githubusercontent.com/12532733/53704214-5d5f3500-3de0-11e9-9fc5-ebff0ec39e12.gif)

**Comment by octref** [comment]
Thanks for the report. Can you give me a reproducible case?

**Comment by ktsn** [comment]
This seems not reproducible in the latest Vetur (v0.22.4).

@ffxsam Are you still seeing this issue on your end with the latest Vetur?

**Comment by ffxsam** [comment]
Seems ok now! Thanks!
