### ISSUE TITLE
no IntelliSense  for echarts lib in script part in vue file while IntelliSense is normal in JS file

### ISSUE THREAD

**Issue by OsmanOmar** [vuejs/vetur#1132]
recently I heavily used echarts (a data visualization library), I found that no IntelliSense  for echarts lib in script part in vue file while IntelliSense is normal in JS file;
**no IntelliSense scenario:** vue file script part, no IntelliSense after input echarts.
`import echarts from 'echarts';
echarts.
export default {
 
}`

**has IntelliSense scenario:** JS file, has IntelliSense after input echarts.
`import echarts from 'echarts';`

**Comment by OsmanOmar** [comment]
I found that it can has IntelliSense via `npm install --save-dev @types/echarts` in vue files;
but in JS file, it does without installing @types/echarts .
🤔 🤔 🤔

**Comment by octref** [comment]
You are running into #808. For Vue files, currently you need to install the types manually.
