### ISSUE TITLE
Slm syntax highliting breaks at nested quotes

### ISSUE THREAD

**Issue by mstssk** [vuejs/vetur#1134]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.16.2
- VS Code version: 1.31.1

## Problem

I wrote `v-if` attribute with nested double quotes and single quotes in Slm template.
Slm syntax highliting breaks at nested quotes.

![sc](https://user-images.githubusercontent.com/500072/53776933-10dc3c80-3f3b-11e9-83c0-1b0b42a3d9f8.png)

## Reproducible Case

Reproduction code.

```
<template lang="slm">
  div v-if="state === 'initialized'"
    slot
</template>
<script>
export default {
  data: {
    state: "foobar"
  }
};
</script>
<style>
</style>
```

**Comment by octref** [comment]
This is because I used `text.pug.slm` for embedded SLM, but it should be `text.jade.slm` with https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-slm.
