### ISSUE TITLE
No support for tag interpolation syntax highlighting

### ISSUE THREAD

**Issue by nmsmith22389** [vuejs/vetur#1139]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Mac
- Vetur version: 0.16.2
- VS Code version: 1.31.1

## Problem

When using the new Pug syntax highlighting tag interpolations aren't highlighted.

<img width="310" alt="screen shot 2019-03-06 at 9 25 09 pm" src="https://user-images.githubusercontent.com/8648114/53930270-59d4e380-4056-11e9-8b59-d37c347fe932.png">

_I should note that regular interpolations also aren't highlighted but that doesn't really matter since I don't think you can even use those with Vue._

**Comment by cheolhow** [comment]
There is also a problem in the pug template that the syntax highlight of the property is the same color as the other html tags.
 In any case, syntax highlighting does not work properly in the pug template.

![스크린샷 2019-03-13 오후 4 02 51](https://user-images.githubusercontent.com/25603134/54259824-55ef1700-45aa-11e9-8e99-8f034dd8b17f.png)

**Comment by cheolhow** [comment]
This screenshot was taken after removing vetur

![image](https://user-images.githubusercontent.com/25603134/54260213-a1ee8b80-45ab-11e9-8640-d5f376e3f18b.png)

**Comment by octref** [comment]
This has been fixed for a while (thanks to contribution from @Patcher56)

![image](https://user-images.githubusercontent.com/4033249/59649521-9bc50800-91b5-11e9-83c2-5b1c5048c127.png)
