### ISSUE TITLE
Outdated ES5 type definition (Parameters<T>)

### ISSUE THREAD

**Issue by pumpkinlink** [vuejs/vetur#1140]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: 0.16.2
- VS Code version: 1.31.1

## Problem
Vetur is apparently using an outdated version of es5 type definition, instead of the definitions from devDependencies/typescript. So if I try to use a more recent feature like Parameters<T> or ConstructorParameters<T>, it gives me an error, but NonNullable<T> works fine.

![screenshot from 2019-03-07 18-47-15](https://user-images.githubusercontent.com/11864620/53991485-73833300-4109-11e9-94ec-96445345bbbd.png)
If I ctrl-click (Goto definition) on `NonNullable`, I'm taken to `~/.vscode/extensions/octref.vetur-0.16.2/server/node_modules/typescript/lib/lib.es5.d.ts`:
![screenshot from 2019-03-07 19-07-05](https://user-images.githubusercontent.com/11864620/53992717-4dab5d80-410c-11e9-9720-3e131ec05770.png)

which is apparently outdated in comparison to my projects `node_modules/typescript/lib/lib.es5.d.ts`:
![screenshot from 2019-03-07 19-07-33](https://user-images.githubusercontent.com/11864620/53992722-51d77b00-410c-11e9-8162-51d6892dcf0c.png)

The Parameters<T> type was added on Typescript 3.1, my project is using TS 3.2.4

## Reproducible Case
``` vue
<template>
</template>

<script lang="ts">
import Vue from 'vue'

type nString = NonNullable<string> // works

const f = (a: string, b: number) => {}
type setupFilterParameters = Parameters<typeof f> // doesn't work, should return a type of [string, number]

export default Vue.extend({
  name: 'SetupFilterDialog',
  data: () => ({
  })
})
</script>
```

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/54790802-b3134a00-4bf4-11e9-99cd-07dc2273d7bc.png)

This seems to be solved in TS 3.3, which you can get by:

- `yarn add -D typescript@3.3` in workspace
-  `"vetur.useWorkspaceDependencies": true`

See #682 for details.

This issue will be completely gone after #1163.
