### ISSUE TITLE
Possible to configure html formatting via package.json or config file while using language server?

### ISSUE THREAD

**Issue by AgentCosmic** [vuejs/vetur#1144]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: I can't tell, I'm using coc-vetur 1.0.14
- VS Code version: N/A

## Problem

Formatting is ignoring tabWidth so when I format my .vue document everything is 4 spaces except for template tag which is 2 spaces.

**Comment by franciscolourenco** [comment]
Having a similar experience. The formatter seems to be ignoring the `eslingConfig` rules in package.json

```json
"eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "@vue/prettier"
    ],
    "rules": {
      "prettier/prettier": [
        "error",
        {
          "#": "prettier config in here :)",
          "singleQuote": true,
          "semi": false,
          "trailingComma": "es5",
          "useTabs": true,
          "bracketSpacing": false
        }
      ]
    },
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
```

**Comment by octref** [comment]
No. Use `  "vetur.format.options.tabSize": 2`. That's the only `tabWidth` setting we read.

**Comment by AgentCosmic** [comment]
Hi octref, sorry for my ignorance. But it seems like setting `"vetur.format.options.tabSize": 4` doesn't work whether I'm using package.json or jsconfig.json. I'm using coc.vim instead of VSCode.

package.json
```
{
  ...
  "vetur.format.options.tabSize": 4
}
```

jsconfig.json
```
{
  "vetur.format.options.tabSize": 4
}
```

If I've not mistaken, coc.vim uses the language server directly. Thanks.

**Comment by octref** [comment]
`"vetur.format.options.tabSize": 4` is a VS Code setting. You should open an issue for coc.vim for how to correclty pass settings to VLS.
