### ISSUE TITLE
Offer VLS through CLI

### ISSUE THREAD

**Issue by gaoshijun1993** [vuejs/vetur#1149]
Recently I changed some rules of my prettier config file, so I have to lint my whole project, and I could format my javascript file via prettier cli, but there is not such command for my vue file, so is it possible to support such command to format the whole project?

**Comment by octref** [comment]
Yes, this is doable. I'll provide a CLI tool for using VLS for formatting.

**Comment by octref** [comment]
Offering VLS on CLI would enable other things too such as template type-checking.

I've updated the title to track that.

**Comment by Yuyz0112** [comment]
https://github.com/Yuyz0112/vue-type-check
I have made a simple CLI that port the template type-checking feature.

**Comment by octref** [comment]
https://github.com/vuejs/vetur/issues/1635

![demo](https://user-images.githubusercontent.com/4033249/72225084-911ef580-3581-11ea-9943-e7165126ace9.gif)
