### ISSUE TITLE
The Vue Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by 13029852933** [vuejs/vetur#1152]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version:
- VS Code version:

## Problem

![image](https://user-images.githubusercontent.com/16774088/54415976-f4a97e00-4738-11e9-80a7-3635dd6d89e3.png)

**Comment by carestad** [comment]
you are not running the latest version of vetur. From the output there you have version 0.16.1, the latest is 0.16.2.

**Comment by octref** [comment]
@13029852933 Yeah, please follow for setup https://vuejs.github.io/vetur/linting-error.html. You likely don't want to use the bundled eslint-plugin-vue in Vetur.

@carestad Thanks for chiming in.

**Comment by stevematdavies** [comment]
Still an issue without eslint plugin and latest vetur.
