### ISSUE TITLE
Spaces (Whitespace) being removed between inline elements

### ISSUE THREAD

**Issue by eddiejibson** [vuejs/vetur#1153]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.16.2
- VS Code version:  1.32

## Problem

Is removing much needed white space within an inline element between nuxt-link elements and and normal paragraph elements.

## Reproducible Case

It should look like this:
```html
<span>
<nuxt-link to="/">Create an account</nuxt-link> or <nuxt-link to="/login">Login</nuxt-link>
</span>
```

However, it formats it like this, which is horrible
```html
<span>
<nuxt-link to="/">Create an account</nuxt-link>or<nuxt-link to="/login">Login</nuxt-link>
</span>
```

**Comment by octref** [comment]
Seems only repro in prettyhtml, please file an issue for them https://github.com/Prettyhtml/prettyhtml or use prettier as template formatter.
