### ISSUE TITLE
Error when using an SVG inside an SVG

### ISSUE THREAD

**Issue by sdras** [vuejs/vetur#1155]
Hey Pine!
How's it going? Could use your input on this:

- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.16.2
- VS Code version: 1.32.2

## Problem

I get an error when trying to use an SVG inside an SVG. Which is valid, and I use frequently. [Example (not mine)](https://hitokun-s.github.io/demo/path-between-two-svg.html)

Looks like it thinks I'm trying to close a tag that's already closed instead of the concept of nesting.

<img width="470" alt="Screen Shot 2019-03-17 at 7 05 17 PM" src="https://user-images.githubusercontent.com/2281088/54501043-56f4b100-48e8-11e9-9fd3-fce7d4975dea.png">

## Reproducible Case

Create an SVG inline, create another component that is also inline SVG (with no HTML markup surrounding- this is essential because it will fail for valid reasons)

Thanks!

**Comment by sdras** [comment]
Nope, nevermind, I typoed something. Carry on. 🤘

**Comment by octref** [comment]
No worries, the link is useful for my learning of SVG though 😄
