### ISSUE TITLE
Vetur 0.17.0 syntax highlighting not working

### ISSUE THREAD

**Issue by davepile** [vuejs/vetur#1165]
Windows 10 x64
VSCode 1.32.3

Vue file syntax highlighting stopped working yesterday. I played around uninstalling and reinstalling Vetur current and previous versions and got it working.

Assume it is the 2 day old release of 0.17.0.
0.16.2 works without issue.

I am new to VSCode and plugins, so the auto update extensions and reload features confused me as to which version was actually running.

When I install 0.16.0 and do a reload, syntax highlighting works. Then I notice Vetur auto installs 
0.17.0 but requires a reload, so syntax highlighting doesn't continued working until I close and re-open VSCode and 0.17.0 becomes active.

I have disabled auto updates for extensions

**Comment by octref** [comment]
That sounds like an issue with VS Code's extension upgrading. You should report to https://github.com/microsoft/vscode. fyi @sandy081

**Comment by davepile** [comment]
I am curious what makes you say it is a VSCode upgrade issue when installation of 0.16.2 works, yet after install 0.17.0 it doesn't work. The install/ uninstall seem to be working fine.

**Comment by octref** [comment]
Is this summary accurate for you?

- Installing 0.16 straight works
- Upgrading from 0.16 to 0.17 doesn't work
- Installing 0.17 straight works

**Comment by TakahiRoyte** [comment]
@davepile 
my colleague had same issue, and he fixed it with the following steps:

1. uninstall vue-snippets extension (or any other possibley related extensions)
2. uninstall vetur
3. reinstall vetur
4. close and reopen VScode

You could try disabling other extensions, before you uninstall it. I hope this works for you.

**Comment by davepile** [comment]
@octref I believe the third step 0.17 did not work, but I did a lot of install/ uninstall/ upgrade so I think I did this step and it did not work but cannot say for certain.

I have just uninstalled and re-installed (now 0.17.1) and that works. I guess we'll never know.

Thanks for the help. Thanks @TakahiRoyte.

**Comment by octref** [comment]
https://github.com/hollowtree/vscode-vue-snippets/blob/master/package.json#L32-L49

They contribute a language / grammar *.vue which conflicts with Vetur, so it won't work.

I updated the FAQ.

**Comment by chwech** [comment]
I have the same problem. my vscode version is 1.32.3 and vetur version is 0.17.1.

**Comment by octref** [comment]
@chwech Try these https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#no-syntax-highlighting--no-language-features-working
