### ISSUE TITLE
[FR] Support for Atom

### ISSUE THREAD

**Issue by rayfoss** [vuejs/vetur#1166]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: linux 
- Vetur version: latest
- VS Code version: 3.5

## Problem

Atom support would be nice. Not a fan of the VS Code maintainers.

## Reproducible Case

1. install VS Code
2. Get microsoft ads trojaned into your system https://github.com/Microsoft/vscode/issues/60989

**Comment by octref** [comment]
I don't have time for it. You can try contributing to https://github.com/rwatts3/atom-ide-vue.
