### ISSUE TITLE
Using a different syntax in <style lang="scss">

### ISSUE THREAD

**Issue by franciscolourenco** [vuejs/vetur#1169]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.17.1
- VS Code version: 1.32.3

## Problem

Using alternative syntaxes for scss.
Is it possible to use this syntax in `<style lang="scss">` blocks?

https://marketplace.visualstudio.com/items?itemName=macieklad.tailwind-sass-syntax

**Comment by octref** [comment]
`<style lang="sass">`.

**Comment by franciscolourenco** [comment]
@octref `scss`, not `sass`.

**Comment by franciscolourenco** [comment]
> Simple extension that adds tailwind grammar rules for **scss** and sass files to allow for framework directives syntax highlighting.

**Comment by octref** [comment]
What problem are you having?

**Comment by franciscolourenco** [comment]
Tailwind directives get flagged as errors. I.e @apply @tailwind

**Comment by octref** [comment]
You can use `"vetur.validation.style": false`, since `@tailwind` is not valid css (or scss).

**Comment by franciscolourenco** [comment]
That was clear from the beginning. It is the reason why being able to use alternative syntax definitions like this one, would be useful.

https://marketplace.visualstudio.com/items?itemName=macieklad.tailwind-sass-syntax

**Comment by octref** [comment]
That only deals with syntax, not error checking.
