### ISSUE TITLE
Can't auto import Typescript classes in SFC

### ISSUE THREAD

**Issue by EBMike** [vuejs/vetur#1170]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.17.1
- VS Code version: 1.32.3

## Problem

![image](https://user-images.githubusercontent.com/15325216/55236690-e6626400-5206-11e9-892b-ddbf2efd1766.png)

![image](https://user-images.githubusercontent.com/15325216/55236991-7dc7b700-5207-11e9-95ba-cd6b3cdbbc3f.png)

If you click quick fix (or `ctrl+.`) it shows...

![image](https://user-images.githubusercontent.com/15325216/55236762-0eea5e00-5207-11e9-854e-7351df185ce0.png)

## Reproducible Case

similar to #606

- In VSCode create a new project with vue cli `vue create .`
- Typescript only
- Component classes
- Go to App.vue and comment out the line `import HelloWorld from './components/HelloWorld.vue';`
- Hover over `HelloWorld` under components

(per #682 setting `"vetur.useWorkspaceDependencies": true` and using Typescript ^3.3 does not help)

**Comment by octref** [comment]
I would fix it together with #907 (currently path is messed up).

![image](https://user-images.githubusercontent.com/4033249/55258705-dc4d5f00-5220-11e9-91bc-045778082659.png)

**Comment by EBMike** [comment]
![image](https://user-images.githubusercontent.com/15325216/55579537-7bbd9680-56e6-11e9-8f53-13ba15d900da.png)

This issue says it should be fixed based on the Changelog... but it's not.

![image](https://user-images.githubusercontent.com/15325216/55579594-a1e33680-56e6-11e9-9c8b-2c70cc2c30fd.png)
