### ISSUE TITLE
Vue-script User Snippets

### ISSUE THREAD

**Issue by alivefromupstairs** [vuejs/vetur#1171]
- Vetur version: 0.17.1
- VS Code version: 1.32.3 (user setup)

## Problem
User Snippets for Vue-script don't exist

![image](https://user-images.githubusercontent.com/46059092/55276769-b2b33700-52f7-11e9-857a-a50253835295.png)

I tried to add a json file and name it vue-script but it's not recognized. if I add the snippets to vue.json I cannot use the snippets inside <script> tag. where and how can I add my own snippets to vue-script? 
##
Also, is it possible to stop Emmet for html/pug inside <script> and <style> and use indented sass Emmet?
![image](https://user-images.githubusercontent.com/46059092/55276828-8946db00-52f8-11e9-8337-a50f6471b9c3.png)
My settings regarding Emmet:
```
  "emmet.includeLanguages": {
    "vue": "jade"
  },
  "emmet.syntaxProfiles": {
    "vue": "css"
  },
```

**Comment by alivefromupstairs** [comment]
one possible hacky solution to Emmet (html/pug) being exclusive to <template>:
![image](https://user-images.githubusercontent.com/46059092/55278806-6f65c200-5311-11e9-99b1-3bb1ee88316e.png)
commenting out "vue" : "lang" as long as you're not in the template

**Comment by leandrocodes** [comment]
Same problem here

**Comment by octref** [comment]
> I tried to add a json file and name it vue-script but it's not recognized. if I add the snippets to vue.json I cannot use the snippets inside <script> tag. where and how can I add my own snippets to vue-script?

https://github.com/vuejs/vetur/issues/718

For now you can try to add snippets to `vue`.

> Also, is it possible to stop Emmet for html/pug inside <script> and <style> and use indented sass Emmet?

Sass is not supported, but if you write `<style lang="sass">` emmet shouldn't show up.

**Comment by KareemDa** [comment]
any idea about how to add a user snippet which works on script ?
