### ISSUE TITLE
When using shorthand function initializer on `computed`, `this.foo` shows error

### ISSUE THREAD

**Issue by jtsom** [vuejs/vetur#1175]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: MacOS
- Vetur version: 0.18.0
- VS Code version: Version 1.33.0-insider (1.33.0-insider)

## Problem
In a Vue application that is using just plain Javascript (<script>), setting 
```
  "compilerOptions": {
    "checkJs": true
  }
```
in `jsconfig.json` to enable the new features mentioned in 0.18.0 (  "compilerOptions": {
    "checkJs": true
  })
causes many things that were errors to show up as errors.

1. imports can't be found using the '@' shortcut:
<img width="489" alt="image" src="https://user-images.githubusercontent.com/13488/55402594-d0fc7b00-5521-11e9-8596-b3531a5b91a6.png">
<img width="828" alt="image" src="https://user-images.githubusercontent.com/13488/55402624-e4a7e180-5521-11e9-9cc9-b6cf0c20ce97.png">

Variables defined in a data() section are not recognized:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/13488/55402689-05703700-5522-11e9-961e-59d2db74b54b.png">

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/13488/55402702-102acc00-5522-11e9-8dd8-071e9bde9657.png">

## Reproducible Case
Create a new vue (cli) app, add some variables in a data statement, see the errors.
Try adding an import with a @.

**Comment by octref** [comment]
You need to setup path mapping: https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#vetur-cant-recognize-components-imported-using-webpacks-alias.

**Comment by jtsom** [comment]
That’s fine but I don’t think that will help the issue with not recognizing the variables defined in the data() section, nor the getters defined my the mapGetters/mapState

**Comment by octref** [comment]
Can you post a minimal reproducible example. Like the source of a full SFC.
`data` needs to return an object, so `const foo = 5` aren't bound to `this` instance. `return { foo: 5 }` is.

**Comment by jtsom** [comment]
This is the complete data statement:

<img width="816" alt="image" src="https://user-images.githubusercontent.com/13488/55433851-412bf080-5564-11e9-91d0-849f5e9521b3.png">

So yes, it returns an object.

**Comment by jtsom** [comment]
And the actions: 
<img width="651" alt="image" src="https://user-images.githubusercontent.com/13488/55433943-76384300-5564-11e9-8661-5c510139e707.png">

And the getters (computed):
<img width="416" alt="image" src="https://user-images.githubusercontent.com/13488/55433980-894b1300-5564-11e9-9312-8de375a2bf3a.png">

**Comment by octref** [comment]
By "minimal reproducible example" I meant put your project generated with vue-cli in a public GH repo.  
Minimal in that "make smallest edits from the generated code to show the problem".
I can't figure out how the rest of your file look like and how your whole project is setup.

**Comment by jtsom** [comment]
Here you go.

https://github.com/jtsom/VeturTest 

See the lines marked // NOT RECOGNIZED

**Comment by octref** [comment]
I wouldn't expect `cardData` to work, but this is surprising:

![lol](https://user-images.githubusercontent.com/4033249/55439314-0f615c80-5559-11e9-874a-b34b6257bdab.gif)

Also once you change the way you write computed, it started to work:

![image](https://user-images.githubusercontent.com/4033249/55439473-9282b280-5559-11e9-9353-28bbec628fdb.png)

I guess the issues are related to the typing upstream.

**Comment by jtsom** [comment]
I’m not seeing how you changed the way computed was written?

**Comment by jtsom** [comment]
And why wouldn’t “cardData” work? How would I make it work (not give an error)? Short of ignoring the error...

**Comment by octref** [comment]
Sorry that's overlapped behind the hover. Try `thisIsSelected: function() {`.

As for `mapState`. I didn't find your usage in the docs: https://vuex.vuejs.org/guide/state.html.

**Comment by jtsom** [comment]
Modules and namespaces: https://vuex.vuejs.org/guide/modules.html#binding-helpers-with-namespace

**Comment by Patcher56** [comment]
I can confirm that writing computed with explicit ’function()’ is the only way computed functions work well.
Writing them without them also removes type inference.

Working with TS.

**Comment by mrozekma** [comment]
Not sure if it helps, but the computed block parses correctly as long as _any_ entry uses the `name: function() {...}` syntax; it only breaks if every entry uses the shorthand `name() {...}`

**Comment by octref** [comment]
Upstream issue:

https://github.com/Microsoft/TypeScript/issues/30854

See this [comment](https://github.com/Microsoft/TypeScript/issues/30854#issuecomment-485893681). For now you can try to annotate the return type with JSDocs:

![image](https://user-images.githubusercontent.com/4033249/56701285-15a7ac00-66b3-11e9-8131-6818237c2583.png)

**Comment by octref** [comment]
Should be fixed as we upgraded to TS 3.6.3 in Vetur 0.22.3.
