### ISSUE TITLE
can not format .vue file

### ISSUE THREAD

**Issue by bulinme** [vuejs/vetur#1176]
- [ √] I have searched through existing issues
- [X ] I have read through [docs](https://vuejs.github.io/vetur)
- [X ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:Win
- Vetur version:0.18.0
- VS Code version:1.32.3

## Problem

right click without "format document" option.
![image](https://user-images.githubusercontent.com/19358996/55413520-09d93600-559c-11e9-98ab-520b9c6caf1c.png)
![image](https://user-images.githubusercontent.com/19358996/55413580-2aa18b80-559c-11e9-99c3-e4f84588bcf4.png)
![image](https://user-images.githubusercontent.com/19358996/55413589-2ffed600-559c-11e9-8e9a-f3e78c8dc1e4.png)
shift+alt+f
![image](https://user-images.githubusercontent.com/19358996/55413604-3725e400-559c-11e9-81b3-0466d1555cb0.png)
![image](https://user-images.githubusercontent.com/19358996/55413631-473dc380-559c-11e9-95df-15383fceef92.png)

**Comment by octref** [comment]
You need to open a workspace (like a folder) for Vetur to work.
