### ISSUE TITLE
Vetur settings don't take effect along with prettier

### ISSUE THREAD

**Issue by YuqiaoS** [vuejs/vetur#1178]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Ubuntu 16.04 
- Vetur version: 0.18.0
- VS Code version: 1.32.3

## Problem
The Vetur and prettier settings don't take effect.
I've set the tabSize on both vetur and prettier to 3 and 4 and still I'm getting 2 spaces.
When I autoformat, semi's are added to the end of the line, though I set it to false in prettier.
What does take effect is when I disable the Vetur formatter and try to autoformat, I get a notice that I don't have a formatter available.

I do have eslint extension as well, and a .eslinitrc.js in a subdirectory of workspace, but the autofix setting shouldn't affect the format until I save the file.

## Reproducible Case
```
    "html.format.wrapAttributes": "force-expand-multiline",
    "html.format.wrapLineLength": 150,
    "vetur.validation.template": false,
    "javascript.format.enable": false,
    "prettier.semi": false,
    "vetur.format.options.tabSize": 4,
    "prettier.tabWidth": 3
```
## Regarding settings
Also I don't quite understand the logic of the Vetur setting where you set opinionated settings like 
this in this [doc](https://vuejs.github.io/vetur/formatting.html#settings).

```
"vetur.format.defaultFormatterOptions": {
  "prettier": {
    // Prettier option here
    "semi": false
  }
}
```
The doc says the Vetur formatter aggregates all the formatters in the setting so if you indicate in the prettier setting the semi is false, then the Vetur formatter should read it no? Why do I need to set it explicitly in the settings.json?

**Comment by octref** [comment]
Vetur doesn't read settings from other scopes like `javascript`, `typescript`, `prettier`, because it confuses people where the settings come from.

There's no opinionated settings, the `"semi": false` is just an example, not the default.

You can set this as your user settings:

```
"vetur.format.defaultFormatterOptions": {
  "prettier": {
    // Prettier option here
    "semi": false,
    "tabWidth": 3
  }
}
```

**Comment by YuqiaoS** [comment]
So what does it mean when you assign formatter in vetur if it doesn't take those settings from that formatter? It simply takes the default settings? Don't get.

**Comment by octref** [comment]
```
"prettier.semi": true // Vetur doesn't care, it's Prettier extension's setting
"vetur.format.defaultFormatterOptions": {
  "prettier": {
    "semi": false // Vetur does care
  }
}
```

**Comment by YuqiaoS** [comment]
Oh, so basically you can define multiple formatters inside the vetur, then select among those defined there. But then you can just define whatever name you want, it seems that its got nothing to do with the extensions. Or does it mean that Vetur looks up or will pass the properties defined there to the specific extension, so that the properties names would actually need to match those defined by the formatter extensions instead of the Vetur setting names.

**Comment by octref** [comment]
https://vuejs.github.io/vetur/formatting.html
