### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by pablocm90** [vuejs/vetur#1179]
[octref.vetur-unresponsive.cpuprofile.txt](https://github.com/vuejs/vetur/files/3037809/octref.vetur-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `vetur`
- Extension Version: `0.18.0`
- OS Version: `Linux x64 4.18.0-16-generic`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/pablo/octref.vetur-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by octref** [comment]
Sorry the profile would not be useful because it's the Language Client's profile. You need to profile the Language Server. Follow #1051 and #547 instead.
