### ISSUE TITLE
Add to FAQ how to profile Vetur

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#1180]
For issues like https://github.com/vuejs/vetur/issues/1179.

- [x] Add `vetur.dev.vlsPort` setting to running VLS on a specific port
- [x] Include a doc for profiling language server

**Comment by gombosg** [comment]
I'm waiting for some useful instructions on how to do this, since I want to help track down this annoying high CPU use bug.

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/56996577-d61d0c00-6b59-11e9-85f0-29dc15e2e2aa.png)

**Comment by octref** [comment]
@gombosg You can follow https://github.com/vuejs/vetur/blob/master/.github/PERF_ISSUE.md to report new performance issues.
