### ISSUE TITLE
Linting support for Coffeescript (coffeelint)

### ISSUE THREAD

**Issue by phil294** [vuejs/vetur#1184]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

[Docs say](https://vuejs.github.io/vetur/linting-error.html#error-checking) there is no CS linting integrated yet.

There is [coffeelint](https://marketplace.visualstudio.com/items?itemName=lkytal.coffeelinter) which highlights syntax errors in `.coffee` files just fine. Is there any way to see coffee errors in Vue files as well?

The only solution I could think of right now is to `<script src="file.coffee"/>` so the code resides outside.

**Comment by octref** [comment]
I think this should be implemented by coffeelint, similar to how ESLint extension handles linting JS in Vue files.

**Comment by phil294** [comment]
@octref sorry if the issue was misambigious: There is no coffee syntax checking in Vue files *at all*. Coffeelint would just be one option. 

Currently, you can write whatever you want inside a `<script lang="coffee">` and while the syntax highlighting is right, errors are not shown.

What needs to change here so the integration works?

**Comment by octref** [comment]
Vetur does have coffee script syntax highlighting, but there's no plan to add any language features (including linting) to it. This is the same treatment for sass, pug, haml, etc.
