### ISSUE TITLE
vue-language-server fails to start if initializationOptions is undefined

### ISSUE THREAD

**Issue by louisbourque** [vuejs/vetur#1188]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: vue-language-server@0.0.49
- SublimeText version: 3.2.1
- [LSP](https://github.com/tomv564/LSP) version: 0.8.2

## Problem

When using SublimeText with the LSP plugin, with vue-language-server, I get the following error in the SublimeText console:

> LSP: Request initialize failed with message: Cannot read property 'config' of undefined

## Reproducible Case

I've traced the error back to this line: 
https://github.com/vuejs/vetur/blob/5f335241079eb476080c083f85a4b3b187210282/server/src/services/vls.ts#L93

If params.initializationOptions is undefined, a TypeError occurs, preventing the init function from continuing. This line was added in a recent commit here: https://github.com/vuejs/vetur/commit/7f498780ab6a6a96c6414438ad2986323f907e2a

In that same file, there is a check to ensure params.initializationOptions exists before attempting to access config:

```
if (params.initializationOptions && params.initializationOptions.config) {
      this.configure(params.initializationOptions.config);
}
```

If possible, I would like to submit a Pull Request for this, which would consist of this commit:
https://github.com/louisbourque/vetur/commit/3cc0b83827dda78ad2775e8688e6efd45b1d9318

**Comment by sgehrman** [comment]
I'm also on Linux/Vetur.  Says Language Server Crashed.  I just updated to the new VSCode, I assume that triggered it.

**Comment by octref** [comment]
The change looks good. Wanna send a PR?
