### ISSUE TITLE
How to lint style in .vue files as template linting?

### ISSUE THREAD

**Issue by ihaichao** [vuejs/vetur#1190]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Problem
I want to lint style in .vue files using custom plugin just as template linting using eslint-plugin-vue. 
So I need to make a new extension, but when I add a styleValidation.ts which imitate htmlValidation.ts, it doesn't work.
Here is the validation code.
```javascript
export function doValidation(document: TextDocument, engine: CLIEngine): Diagnostic[] {
  const rawText = document.getText();
  if (rawText.replace(/\s/g, '') === '') {
    return [];
  }
  const text = rawText.replace(/ {14}/, '<style scoped>') + '</style>';
  const report = engine.executeOnText(text, document.uri);
  return report.results[0] ? report.results[0].messages.map(toDiagnostic) : [];
}
```
Could you give some suggestions?

**Comment by octref** [comment]
What do you mean by `when I add a styleValidation.ts which imitate htmlValidation.ts`? Are you running a fork of Vetur? If so can you share it?

**Comment by ihaichao** [comment]
@octref yeah, I'm running a fork of Vetur and I have found a solution.
