### ISSUE TITLE
'#' mess up highlight after it in js template string

### ISSUE THREAD

**Issue by BlazerYang** [vuejs/vetur#1192]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.18.1
- VS Code version: 1.31.1

## Problem

when use "#" in Template strings(\`) in `<template></template>` tag, highlight went wrong after this character, but things goes well in 0.17.0, maybe there is a bug in new release after 0.18.*?

code in 0.18.1
![image](https://user-images.githubusercontent.com/24294658/55768812-dffaa480-5ab0-11e9-9905-de2aac2c9fac.png)

and code in 0.17.0
![image](https://user-images.githubusercontent.com/24294658/55768866-1f28f580-5ab1-11e9-96fc-b6f1f39aa5fc.png)

## Reproducible Case
```vue
<template>
    <router-link :to="{path: `/my/path#hash=${hash}`}">click me</router-link>
</template>

<script>
export default {
    data () {
        return {
            
        }
    }
}
</script>

```

**Comment by octref** [comment]
@Patcher56 FYI

**Comment by octref** [comment]
I fixed it in PR https://github.com/vuejs/vetur/pull/1193.
