### ISSUE TITLE
The Setting of Vetur in VSCode Not Working in Nuxt.JS

### ISSUE THREAD

**Issue by MarkSky** [vuejs/vetur#1195]
## Info

- Platform: Windows 10 64bit
- Vetur version: 0.18.1
- VS Code version: 1.33.0

## Problem
I have set those in VSCode settings.json:

> "vetur.format.scriptInitialIndent": true,

> "vetur.format.styleInitialIndent": true,

But when I formate .vue files in the NuxtJS project, it doesn't work.
It still displayed:
![nuxtjs](https://user-images.githubusercontent.com/4032734/55869654-83cf7780-5bb9-11e9-9211-ce9c085eea70.jpg)

If vetur doesn't support Nuxt.JS? Or Should I set others?

**Comment by octref** [comment]
If you have prettier extension, you might need to disable it for vue with `prettier.disableLanguages`.

**Comment by MarkSky** [comment]
I have add `"prettier.disableLanguages": ["vue"]` to the settings.json in VSCode.
It work now.
![nuxtjs2](https://user-images.githubusercontent.com/4032734/55926624-a0fd5800-5c44-11e9-925e-70b8aa2134d3.jpg)
But after I format, I got many errors.
![nuxtjs3](https://user-images.githubusercontent.com/4032734/55926659-c4280780-5c44-11e9-8b29-5c14fe6e3efd.jpg)
I just use `npx create-nuxt-app projectname` to create a NUXTJS project, and I don't set anything in the ptoject (like .editorconfig, .eslintrc.js,.prettierrc, etc.), but I get the eslint errors.

**Comment by octref** [comment]
https://vuejs.github.io/vetur/linting-error.html#linting

**Comment by MarkSky** [comment]
I find there is a different between in Vue project and Nuxt Project.
the .eslintrc.js in your link :
`"extends": [
    "eslint:recommended",
    "plugin:vue/recommended"
  ],`
but the .eslintrc.js in Nuxt:
`extends: [
        '@nuxtjs',
        'plugin:nuxt/recommended',
        'plugin:prettier/recommended',
        'prettier',
        'prettier/vue',
    ],`
Which one should I follow?

**Comment by 0njzy0** [comment]
@MarkSky Do you have this problem? #1161

**Comment by MarkSky** [comment]
No, I don't have this problem.
But I find I have to change the setting in .eslintrc.js:
The original in create-nuxt-app:
`extends: [
    '@nuxtjs',
    'plugin:nuxt/recommended',
    'plugin:prettier/recommended',
    'prettier',
    'prettier/vue'
  ],`
I have to change to:
`extends: [
        '@nuxtjs',
        'plugin:nuxt/recommended',
        'prettier',
        'prettier/vue',
        'plugin:vue/essential',
        'eslint:recommended',
    ],`
The error will be solved.
