### ISSUE TITLE
vue files lose typescript type info

### ISSUE THREAD

**Issue by oppianmatt** [vuejs/vetur#1196]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: linux/codesandbox.io
- Vetur version: 0.18.1
- VS Code version:

## Problem

Typescript code that is ok in a .ts file complains about type errors in a vue sfc file
Have found this with xstate.

I get this issue in my local vscode but confirmed it's not just me by trying it on codepen

![Screenshot from 2019-04-10 16-39-07](https://user-images.githubusercontent.com/48596/55893067-701f1380-5baf-11e9-8bdb-79322ddfba8b.png)

The same code in a .ts file does not complain.

Initially raised the issue with xstate as thought might be an issue there https://github.com/davidkpiano/xstate/issues/421

but the maintainer has confirmed it's strange

## Reproducible Case

https://codesandbox.io/s/82k8k8wmj2?fontsize=14&module=%2Fsrc%2FApp.vue

Note that it doesn't show up as an error when you first load. But touch the html part so that vetur kicks in and then you get an error.

**Comment by yoyo930021** [comment]
I think the problem was solved when codesandbox updated the vetur version.
