### ISSUE TITLE
Pug comment style changed in recent update

### ISSUE THREAD

**Issue by kieraneglin** [vuejs/vetur#1199]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.18.1
- VS Code version: 1.33.0

## Problem

Previously, commenting with `cmd + /` in a pug file would produce a comment like so: `//-`.  Within the last 2 days, comments have changed to just `//`.

There is an earlier issue observing the same thing, but it may be a different issue this time: #840

## Reproducible Case

1. Write any number of lines of valid pug in a Vue template file
2. Try to comment the line(s) with `cmd + /`
3. See that the lines are prepended with `//` instead of `//-`

**Comment by octref** [comment]
@Patcher56 You still need to declare jade as embedded languages, otherwise language configurations like https://code.visualstudio.com/api/language-extensions/language-configuration-guide wouldn't work.

**Comment by lxmfly123** [comment]
Can anyone demonstrate how to *declare jade as embedded languages*?

**Comment by kissu** [comment]
Thanks. :pray:
