### ISSUE TITLE
Support scoped slot on template diagnostic

### ISSUE THREAD

**Issue by ktsn** [vuejs/vetur#1203]
It currently just ignores `slot-scope` and `v-slot`. We need to add declared variables by scoped slot in local scope.

```vue
<template>
  <MyComp v-slot="{ foo }"> <!-- foo will be in local scope -->
    <p>{{ foo }}</p> <!-- should not provide error here -->
  </MyComp>
</template>
```

**Comment by shaneparsons** [comment]
Is my following issue related to this?

![Screen Shot 2019-04-24 at 2 08 38 PM](https://user-images.githubusercontent.com/5495493/56682909-8db5a800-669a-11e9-9fd1-981eae714c51.png)

This behaviour just started today, and I cant figure out why... If this isn't related, let me know and I'll open a new issue.

**Comment by ktsn** [comment]
Yes.

**Comment by m2de** [comment]
Also ran into this today.

![Screenshot 2019-04-25 at 11 35 31](https://user-images.githubusercontent.com/17720020/56729920-53a5de00-674e-11e9-87a6-96980ef95c99.png)

**Comment by Shamus03** [comment]
+1, also getting this issue:

![image](https://user-images.githubusercontent.com/739815/56763612-75ac5a00-6768-11e9-9d64-20f84d962a5c.png)

**Comment by rottenpen** [comment]
but i use vue 2.5 cant support v-slot

**Comment by mrg0lden** [comment]
I still get an error when I use slot variables for v-bind:class 
![image](https://user-images.githubusercontent.com/8347078/88962593-537c8280-d2af-11ea-982b-3a52959827c2.png)
![image](https://user-images.githubusercontent.com/8347078/88962533-3e075880-d2af-11ea-82df-71a7019efdfa.png)
![image](https://user-images.githubusercontent.com/8347078/88962562-46f82a00-d2af-11ea-872c-db6dcd88ae3c.png)

**Comment by amoshydra** [comment]
@mrg0lden 

Got the same issue too.

However, the problem doesn't exist if `v-slot` is used inside the `template` element, e.g.

```vue
<editor-menu-bar
  :editor="editor"
>
  <template v-slot="{commands, isActive, focused}">
    ...
  </template>
</editor-menu-bar>
```

I have logged a new issue here: https://github.com/vuejs/vetur/issues/2094
