### ISSUE TITLE
How to format mustache in vue template

### ISSUE THREAD

**Issue by edwards19900128** [vuejs/vetur#1217]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS 10.14.1
- Vetur version: 0.18.1
- VS Code version:1.33.1

## Problem
How to format vue template html mustache syntax 
```html
<span class="content">{{aaa}}{{bbb}}</span>

// i want the saved format is:
<span class="content">{{ aaa }} {{ bbb }}</span>
```

thanks for reply ~

**Comment by octref** [comment]
You can't, please file feature request for https://github.com/Prettyhtml/prettyhtml.
