### ISSUE TITLE
Multiple color pickers if more than one <style> block

### ISSUE THREAD

**Issue by leopiccionia** [vuejs/vetur#1219]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: 0.18.1
- VS Code version: 1.33.1

## Problem

It's a very specific, small bug, as far as I can reproduce.

If I have two `<style>` blocks, and both share the **same** `lang` (I can reproduce it with default, `postcss` and `scss`, but not `stylus`), each color literal will have two color pickers. If I have three `<style>` blocks, three color pickers, etc. 

The use of `scoped`, `module`, etc. doesn't seem to affect it.

![image](https://user-images.githubusercontent.com/9576518/56626380-cf513f00-6617-11e9-9a13-c2984ee2a665.png)

## Reproducible Case

Any code with two `<style>` blocks with same `lang` should work.
```vue
<style>
body {
    background-color: white;
}
</style>

<style>
h1 {
    color: #F72;
}
</style>
```

If needed, I can send a reproduction link.

**Comment by bxm0927** [comment]
same problem on win10 vetur 0.18.1, vscode 1.33.1

**Comment by Coolyang1996** [comment]
The same problem in a stylus file, maybe it's comes from vscode
![捕获](https://user-images.githubusercontent.com/34713301/56748139-e166e500-67b1-11e9-94d3-49ed146d20e6.PNG)

**Comment by leopiccionia** [comment]
@Coolyang1996 I think it's unrelated, because:
1. VS Code doesn't have built-in Stylus support, you need an extension for this;
2. That bug affects only rules with more than one selector, unlike the original reported bug;
3. That bug occurs even without Vetur.

You probably should file an issue on your Stylus extensions' repo.

**Comment by Coolyang1996** [comment]
@leopiccionia 
Maybe you are right. I tried again in a css file but still like this. If I disable the `language-stylus` extension, the problem was solved.
