### ISSUE TITLE
Error for protected members using vue-property-decorator not accessible in virtual template file

### ISSUE THREAD

**Issue by yoyoys** [vuejs/vetur#1224]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.19.0
- VS Code version: 1.33.1

## Problem

![image (2)](https://user-images.githubusercontent.com/22124891/56646806-dda06900-66b2-11e9-800f-24edbb174647.png)

## Reproducible Case
Project created with vue-cli 3.6.3, TSLint, airbnb.

I've just set a data as `protected`, then vetur told me it's not accessible.

I think they're the same object, this issue cause `protected` means I can't see myself.
And all my class members will set to `public`, that's ridiculous.

**Comment by ktsn** [comment]
This is because of how template diagnostics work. The component type and template diagnostics is separated under the hood. Unfortunately, I don't think we can solve this soon.

**Comment by pdmshrestha** [comment]
This happened suddenly after the update.

<img width="940" alt="Screenshot 2019-04-24 at 20 25 36" src="https://user-images.githubusercontent.com/2828010/56680340-bf953180-66cf-11e9-8bfc-40925886a19e.png">

**Comment by octref** [comment]
@yoyoys Can you show the full message code?

@ktsn What do you think about we filter out that specific error code?

@pdmshrestha Your issue is something else.
