### ISSUE TITLE
Vetur fail to start => vOnExp.body.map is not a function

### ISSUE THREAD

**Issue by ondrej-janosik** [vuejs/vetur#1227]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.19.0
- VS Code version: 1.33.1

## Problem

Vetur fail to start. Output: https://justpaste.it/6n1ik

**Comment by ktsn** [comment]
@ondrej-janosik Thanks for reporting this issue. Could you provide minimal reproduction which generate this error by cloning and editing https://github.com/octref/veturpack?

**Comment by ondrej-janosik** [comment]
Unfortunately, I can not. We found this bug in one pretty big project that I can not share with you. Can you help me where to look? I can send you just the broken .vue file. But I dont know how to find that one.

**Comment by ktsn** [comment]
No worries. I just figured out the cause.
If we have an arrow function in some `v-on` value, this error happens.

```vue
<template>
  <button @click="() => test = 123">click</button>
</template>
```

**Comment by dombavetta** [comment]
This started happening in my project as of yesterday. I stopped getting syntax highlighting for the script and style sections of one of my vue files. I lose all language support for the rest of my vue files too, syntax highlighting seems to be intact in all other vue files though.

**Comment by ktsn** [comment]
@dombavetta Syntax highlighting issue is probably a separated problem. Could you create a new issue for that with reproduction?

**Comment by ktsn** [comment]
Made a PR #1228

**Comment by dombavetta** [comment]
@ktsn Yeah I figured, I actually was just looking through the issues for users experiencing something similar and it appears theres already an issue created. I will try and get a reproducible project up but no promises, this comes from a very large project at work so I will try to strip out what I can and see if the issue is still present.

#1211

**Comment by ktsn** [comment]
@dombavetta Thank you for your help!

**Comment by ktsn** [comment]
@dombavetta 

> "Cannot find name 'temthis'."

Oh, I missed this problem. This would be also individual problem. It would be appreciated if you create an issue for that also 🙏

**Comment by ondrej-janosik** [comment]
Thanks for such a quick help! You were right. When I delete all arrow functions in v-on, VETUR works as expected
