### ISSUE TITLE
Template literal strings within the SFC template section show error "cannot find name tem*insert various characters here*. Vetur (2304)".

### ISSUE THREAD

**Issue by dombavetta** [vuejs/vetur#1230]
- [ X] I have searched through existing issues
- [X ] I have read through [docs](https://vuejs.github.io/vetur)
- [X ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.19.0
- VS Code version:  1.33.1

## Problem

Template literal strings within the SFC template section show error "cannot find name tem*insert various characters here*. Vetur (2304)".
![image](https://user-images.githubusercontent.com/33183744/56680734-6ad0c700-668d-11e9-8510-8d1ec5b33cc6.png)

## Reproducible Case
- Pull down [https://github.com/dombavetta/vetur-template-interpolation-issues](url)
- Lines 12 and 19 will present errors. [https://github.com/dombavetta/vetur-template-interpolation-issues/blob/master/pages/test.vue](url)

**Comment by ktsn** [comment]
Thanks for opening this issue!

Here is simplified repro.

```vue
<template>
  <div :title="`${test}`" />
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  data() {
    return {
      test: 'hi'
    }
  }
})
</script>

```
