### ISSUE TITLE
Vetur 0.19 seems heavily broken - applying TypeScript checks to a non-TS project

### ISSUE THREAD

**Issue by ffxsam** [vuejs/vetur#1236]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  macOS
- Vetur version: 0.19.0
- VS Code version: 1.33.1

## Problem

![image](https://user-images.githubusercontent.com/12532733/56695868-beeca300-66af-11e9-8956-dc3e3349185f.png)

## Reproducible Case

Closed source project, cannot share. Can't replicate in a fresh project.

**Comment by octref** [comment]
How is `displayCredentialPicker` bound to this instance?

If it's not props/data/methods it won't work as of yet.

**Comment by kinesias** [comment]
Can confirm. 0.19 is completely broken.

**Comment by ffxsam** [comment]
> How is `displayCredentialPicker` bound to this instance?
> 
> If it's not props/data/methods it won't work as of yet.

It's a computed property.

**Comment by octref** [comment]
@ffxsam Can you try to create a minimal repro?

![image](https://user-images.githubusercontent.com/4033249/56699711-8cd94200-66ab-11e9-851e-6afea29a68d0.png)

**Comment by ffxsam** [comment]
I tried, couldn't reproduce it. And now that I've been working on this Vue component more, the issue has strangely disappeared. Very odd.

**Comment by octref** [comment]
OK next time try to copy your Vue file into another file, and remove as much code as possible for minimal repros. They would be more helpful for me to diagnose the issue. Thanks!

Your issue might be fixed because you upgraded to 0.19.1 which has a few fixes.

**Comment by ffxsam** [comment]
@octref Got it. It's the usage of a template string that causes the issue:

```vue
<template>
  <div>
    <MyComponent :desc="`Some text ${hi}`" />
  </div>
</template>

<script>
export default {
  computed: {
    hi() {
      return "hi";
    }
  }
};
</script>

<style>
</style>
```

![image](https://user-images.githubusercontent.com/12532733/56702049-aa1c0980-66c7-11e9-8b29-aa6c313f89c8.png)

**Comment by ffxsam** [comment]
Another broken case below. It's underlining `:msg="whatever"`. It's not smart enough to know that I'm manually creating it in `created()`.

```vue
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
    <HelloWorld :msg="whatever"/>
  </div>
</template>

<script>
import HelloWorld from './components/HelloWorld.vue'

export default {
  name: 'app',
  components: {
    HelloWorld
  },
  created() {
    this.whatever = 'hey';
  }
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
```

**Comment by kinesias** [comment]
Shouldn’t  „whatever“ be declared in data object first?

**Comment by ffxsam** [comment]
@kinesias no, not necessarily. It's perfectly valid to set properties that are not reactive.

**Comment by octref** [comment]
> <MyComponent :desc="`Some text ${hi}`" />

That's definitely a valid bug. You can try the command "Vetur: Show corresponding virtual file and sourcemap" and it shows this snippet:

```ts
__vlsRenderHelper(__Component, function () {
    "\n  ";
    __vlsComponentHelper("div", { props: {}, on: {}, directives: [] }, ["\n    ", __vlsComponentHelper("mycomponent", { props: { "desc": template>
  <this.hiv> }, on: {}, directives: [] }, []), "\n  "]);
    "\n           \n\n        \n                \n             \n          \n                  \n     \n   \n  \n         \n";
});
```

For the second case, as @kinesias said, you didn't declare `whatever` in your data object.
