### ISSUE TITLE
Suggestion: experimental feature should be disabled by default

### ISSUE THREAD

**Issue by protodonuts** [vuejs/vetur#1246]
In recent case ( v0.19.0 , v0.19.1 ) it would be
```
"vetur.experimental.templateInterpolationService": false
```

An experimental feature which is not fully battle tested might confuse users when things are not going well.

Features in this stage should be able to be manually turned on, usually by people who know what they are doing, and/or have a need for the certain feature. And they can help you test the feature before it is ready to be enabled by default.

**Comment by octref** [comment]
> not fully battle tested

How would I battle test experimental features?

**Comment by octref** [comment]
I did assume people would read the release notes and docs, if something goes from broken to not broken, but that seems to be the wrong assumption...

But now thinking back, most JS users probably don't have their Vue component correctly typed, so I should have disabled that for `<script>` but not `<script lang="ts">`...

**Comment by protodonuts** [comment]
> How would I battle test experimental features?

You may `git clone` some random, active, seems-well-maintained vue projects on GitHub, open them with your new release candidate. And compare it with your last stable release?

Before major release at least have some look from the perspective of the end users.

**Comment by NoahStahl** [comment]
Agreed on disabling on first release. This sounds like a great feature, but upon opening my project today I found my components showing dozens of errors they didn't show a couple days ago, without any changes by me. As you can imagine, I was confused :) and went looking for the release notes, finding this. But probably better user experience to publish the same and ask for early adopters to turn on the setting to give it a shot. Not as much feedback perhaps, but better for trust.

**Comment by SDuck4** [comment]
> That's correct, there's no support for mixin yet. It's not easy to do this...
@octref
https://github.com/vuejs/vetur/issues/1232#issuecomment-486440569

I agree with this suggestion because many projects use mixin feature.
If experimental feature is **not perfact**, it should be disabled by default.

**Comment by octref** [comment]
I disabled it by default because upstream issues like https://github.com/vuejs/vetur/issues/1226 is not solvable through types yet, and `mapGetters` from vuex can't add members to `this` either.
