### ISSUE TITLE
Cannot find name 'scope'.

### ISSUE THREAD

**Issue by SssLiao** [vuejs/vetur#1247]
## Info

- Platform: Win
- Vetur version:0.91.1
- VS Code version:1.33.1

## Problem

```
<template slot-scope="scope"></template>
```

Using the above code in elementui will cause errors

Cannot find name 'scope'.Vetur(2304)

**Comment by zhouxinyong** [comment]
the same issue +1

**Comment by DWYW** [comment]
the same issue +1
hope it can be fixed as soon as possible.

**Comment by ktsn** [comment]
Duplicate of #1203
