### ISSUE TITLE
Vetur has an incorrect result in detecting code format

### ISSUE THREAD

**Issue by 1353619565** [vuejs/vetur#1249]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  Win7
- Vetur version: 0.19.1
- VS Code version: 1.33

### Vetur has an incorrect result in detecting code format.Details are shown below.
![image](https://user-images.githubusercontent.com/30641714/56724344-6683d700-677d-11e9-865e-1294060e8dc2.png)
![image](https://user-images.githubusercontent.com/30641714/56724492-b1055380-677d-11e9-8d4b-0d1c618a2dd7.png)
This character B is somehow ignored in detection。
I hope it's my problem, but I hope you can have a test.
## Reproducible Case

As shown in the figure above

**Comment by 1353619565** [comment]
Another picture.
![image](https://user-images.githubusercontent.com/30641714/56725216-068e3000-677f-11e9-981c-edd52fac8010.png)

**Comment by DWYW** [comment]
another problem
<img width="564" alt="WX20190425-172950@2x" src="https://user-images.githubusercontent.com/19439805/56725670-e1e68800-677f-11e9-8240-cbd393bf546c.png">

**Comment by cpgood** [comment]
install from vsix at 0.18.1

**Comment by vinayakkulkarni** [comment]
Temp solution would be to revert to `0.18.1`

**Comment by stefnotch** [comment]
Reverting to an older version is a bad solution. A much easier one is changing a single Vetur setting:

https://github.com/vuejs/vetur/issues/1246

**Comment by eljefedelrodeodeljefe** [comment]
I assume every single vetur installation has this problem.

**Comment by uniquejava** [comment]
I met this same issue today on macOS. yesterday all are fine.

**Comment by cecotw** [comment]
This has been driving me bat shit all day, thanks @stefnotch .

**Comment by octref** [comment]
> Reproducible Case

Sorry picture is not a reproducible case. Please fork https://github.com/octref/veturpack to create a "Minimal, Complete, and Verifiable example" https://stackoverflow.com/help/mcve and open new issue.
