### ISSUE TITLE
code 2345

### ISSUE THREAD

**Issue by PingChou** [vuejs/vetur#1250]
Issue Type: <b>Bug</b>

{
	"resource": "/Users/jirubo/project/eeo/eeo13/saas_dev/browser_vue/src/pages/pc/onlineTeaching.vue",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "2345",
	"severity": 8,
	"message": "Argument of type '{ data(): { functionList: { imgUrl: string; }[]; solutionList: { style: { width: string; }; imgUrl: string; }[]; schoolTypeList: ({ imgUrl: string; style?: undefined; } | { style: { width: string; }; imgUrl: string; })[]; }; components: { ...; }; }' is not assignable to parameter of type 'new (...args: any[]) => any'.\n  Type '{ data(): { functionList: { imgUrl: string; }[]; solutionList: { style: { width: string; }; imgUrl: string; }[]; schoolTypeList: ({ imgUrl: string; style?: undefined; } | { style: { width: string; }; imgUrl: string; })[]; }; components: { ...; }; }' provides no match for the signature 'new (...args: any[]): any'.",
	"source": "Vetur",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}

Extension version: 0.19.0
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/56779981-57f3ea80-6792-11e9-870d-f456fda54923.png)

**Comment by kbtzr** [comment]
@PingChou 
Either export your components using `export default Vue.extend({ ...` or disable template interpolation service by adding this line to your vscode settings: `"vetur.experimental.templateInterpolationService": false`
