### ISSUE TITLE
Cannot find name 'scope'

### ISSUE THREAD

**Issue by zyd** [vuejs/vetur#1252]
今天打开vscode，所有index.vue都报Cannot find name 'scope'
![image](https://user-images.githubusercontent.com/3446278/56790914-63015600-6838-11e9-917b-5c7e99d3b1c6.png)

**Comment by qingyl** [comment]
目前暂时降级就可以了

**Comment by BenoitPingris** [comment]
You can either add this to your settings `"vetur.experimental.templateInterpolationService": false` or rollback to the 18.1 I guess

**Comment by ktsn** [comment]
Could you provide a reproduction as example github repo or pasting the problematic `.vue` file?

**Comment by octref** [comment]
Dup of #1203.

**Comment by zyd** [comment]
> Could you provide a reproduction as example github repo or pasting the problematic `.vue` file?

https://github.com/zyd/bugImage/blob/master/index.vue

**Comment by ktsn** [comment]
Thanks, that's indeed dup of #1203
