### ISSUE TITLE
Error: Cannot find name 'directives'. Vetur(2304) [1, 1]

### ISSUE THREAD

**Issue by ndabAP** [vuejs/vetur#1253]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: 0.19.2
- VS Code version: 1.33.1

## Problem

Several error messages like:

> Cannot find name 'directives'. Vetur(2304) [1, 1]

![Screenshot from 2019-04-26 09-33-39](https://user-images.githubusercontent.com/8510570/56791043-667be980-6806-11e9-89ed-45144c2f897d.png)

## Reproducible Case

1. Checkout https://github.com/ndabAP/vue-command
2. Open `Stdin.vue`

**Comment by ktsn** [comment]
Hmm, cannot reproduce. Are you sure you are using v0.19.2? Because we have fixed such problem just that version.

Also what do you see when you run a command `"Vetur: Show corresponding virtual file and sourcemap"` in that file?

**Comment by Akumzy** [comment]
Am having the same issue but mine was caused `v-slot` is seems like `vetur` doesn't recognize `scope-slot` 
![Screenshot from 2019-04-26 12-54-38](https://user-images.githubusercontent.com/25849232/56806107-e3b55780-6822-11e9-85fc-9a75f1eee01a.png)

**Comment by ktsn** [comment]
@Akumzy That's another issue #1203

**Comment by ndabAP** [comment]
I'm sorry, I updated and restarted Visual Studio Code but it seems I had to manually click on "Reload" at the extension. Everything is fine!
