### ISSUE TITLE
Cannot find namespace 'google'. Vetur(2503)

### ISSUE THREAD

**Issue by tony19** [vuejs/vetur#1256]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS 10.14.4
- Vetur version: 0.19.2
- VS Code version: 1.33.1

## Problem

Vetur seems to have trouble resolving `google` from `googleapis` when declaring a field with type `google.auth.OAuth2`.

<img width="553" alt="Screen Shot 2019-04-26 at 7 42 45 PM" src="https://user-images.githubusercontent.com/26580/56842574-1af42a80-685c-11e9-9827-4bc02fec1a1b.png">

## Reproducible Case

1. Create a Vue CLI project with TypeScript
2. Install `googleapis` with `npm i -S googleapis`
3. Create a `.vue` file with these contents:

```vue
<script lang="ts">
import { Component, Watch, Vue } from 'vue-property-decorator';
import { google } from 'googleapis'

@Component
export default class FooClass extends Vue {
  private authCode = ''
  private oauth2Client: google.auth.OAuth2

  constructor() {
    super()
    this.oauth2Client = new google.auth.OAuth2(
      'CLIENT_ID',
      'CLIENT_SECRET',
      'http://localhost:8080/login',
    );
    this.oauth2Client.apiKey = 'API_KEY'
  }
}
</script>
```

 4. Observe the red line under the class field but not the instantiation in the constructor.

**Comment by ktsn** [comment]
This is expected behavior because `google` is not a type.
What you need is `OAuth2Client`.
https://github.com/googleapis/google-api-nodejs-client/blob/master/src/googleapis.ts#L25

```vue
<script lang="ts">
import { Component, Watch, Vue } from 'vue-property-decorator';
import { google } from 'googleapis'
import { OAuth2Client } from 'google-auth-library'

@Component
export default class FooClass extends Vue {
  private authCode = ''
  private oauth2Client: OAuth2Client

  constructor() {
    super()
    this.oauth2Client = new google.auth.OAuth2(
      'CLIENT_ID',
      'CLIENT_SECRET',
      'http://localhost:8080/login',
    );
    this.oauth2Client.apiKey = 'API_KEY'
  }
}
</script>
```
