### ISSUE TITLE
Syntax highlighting breaks when quote on single line

### ISSUE THREAD

**Issue by sacki5** [vuejs/vetur#1268]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.19.3
- VS Code version:  1.33.1

## Problem
When a quote is on single line on a attribute that takes js. The syntax highlighting becomes wrong. 
![Screenshot 2019-05-02 at 16 55 19](https://user-images.githubusercontent.com/25466424/57084712-1798ed00-6cfb-11e9-9ae5-ec128966924f.png)

## Reproducible Case
https://github.com/sacki5/veturpack/blob/master/client/views/Home.vue

**Comment by sam3d** [comment]
Any updates on this @octref ? I'm seeing the same issue occur on my end:

<img width="400" alt="Screenshot 2020-04-16 at 13 55 37" src="https://user-images.githubusercontent.com/8385528/79458623-f7387000-7fe9-11ea-924b-13417875d89b.png">

From inspecting the TM scopes, it seems as though it can't interpret the end of a quoted sequence when it's on a newline on its own:

When the quote terminates the end of the line:

<img width="447" alt="Screenshot 2020-04-16 at 13 56 59" src="https://user-images.githubusercontent.com/8385528/79458749-2d75ef80-7fea-11ea-93ac-f65525f3ea2a.png">

When the quote on its own is on the newline:

<img width="440" alt="Screenshot 2020-04-16 at 13 57 04" src="https://user-images.githubusercontent.com/8385528/79458810-44b4dd00-7fea-11ea-97c4-26704fcfd318.png">

**Comment by lcysgsg** [comment]
I tried to set `vue/max-len`  to handle it. i failed

**Comment by octref** [comment]
No longer repros:

![image](https://user-images.githubusercontent.com/4033249/89494699-51538000-d7e9-11ea-8f36-910d955fd0ae.png)

![image](https://user-images.githubusercontent.com/4033249/89494702-5284ad00-d7e9-11ea-86f5-7b8947091efd.png)

**Comment by kissu** [comment]
Any info on this one? It is pretty annoying to have several lines of code being broken and having to `eslint-disable` every 10 lines is not a way to go. I'm on latest Vetur version (`0.34.1`), using Vue2 (Nuxt), no TS.

`.prettierrc`
```json
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "embeddedLanguageFormatting": "auto",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": false,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "printWidth": 90
}
```

I do use those settings for Vetur
```json
{
  "vetur.format.defaultFormatter.js": "prettier",
  "vetur.format.defaultFormatter.css": "none",
  "vetur.format.defaultFormatter.less": "none",
  "vetur.format.defaultFormatter.postcss": "prettier",
  "vetur.format.defaultFormatter.scss": "none",
  "vetur.format.defaultFormatter.html": "prettier",
  "vetur.validation.style": true,
}
```

This kind of code breaks a lof of what is following after being formatted by Prettier
```html
<base-input-text
  @input="setFieldValueAt(modalItem, 'mealVoucherOrder', 'unitValue', Math.round($event * 100))"
>
  <template #icon>
    <svg-simple-euro></svg-simple-euro>
  </template>
</base-input-text>
```

![image](https://user-images.githubusercontent.com/5133074/121156641-27278000-c849-11eb-9633-6cd381d4fbad.png)

This is how it should look like below the end of `</base-input-text>`
![image](https://user-images.githubusercontent.com/5133074/121156684-36a6c900-c849-11eb-87d2-f612e2e3b915.png)

**Comment by Chadyka** [comment]
This is not closed and still happening just like @kissu explained

**Comment by Omar-kh** [comment]
In my case, I had an old [Babel extension](https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel) conflicting with the Vetur one

**Comment by rendomnet** [comment]
same here

**Comment by lars-berg-dxd** [comment]
> In my case, I had an old [Babel extension](https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel) conflicting with the Vetur one

this fixed it for me, thanks!
