### ISSUE TITLE
Vetur autocomplete not working if data() return type annotated as any

### ISSUE THREAD

**Issue by georgyfarniev** [vuejs/vetur#1271]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows 10
- Vetur version: 0.19.4
- VS Code version: 1.33.1

## Problem
First, thanks for working on vetur. I noticed the following problem:

If vue data() method return type annotated as any, then completion doesn't work properly at all, not only for data. I spend whole day figuring this out. I've seen many people here suffering from weird completion issues, so that maybe one of the cases. Hope this helps.

## Reproducible Case

```vue
<script lang='ts'>
export default {
  data(): any {
    return {
      foo: 'foo',
      bar: 123
    }
  },
  methods: {
    someMethod() {
       // to reproduce, type this. here, and see incorrect completions
       // remove any annotation from data() and everything is ok!
    }
  }
}
</script>
```

tsconfig.json (taken from veturpack repo)

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "strict": true,
    "noUnusedLocals": true,
    "noImplicitAny": true,
    "outDir": "dist",
    "sourceMap": true,
    "lib": [
      "es5", "es2015.collection", "es2015.promise", "dom", "es2016.array.include"
    ],
    "allowJs": true
  }
}
```

**Comment by georgyfarniev** [comment]
Also, I noticed that it doesn’t work without strict and noUnusedLocals. Does it worth creating separate issue for it?

**Comment by octref** [comment]
@georgyfarniev That's expected. If you change the return type of `data` the properties from its return type won't be bound to `this`.
