### ISSUE TITLE
Scroll-snap-align property unknown

### ISSUE THREAD

**Issue by jhechtf** [vuejs/vetur#1274]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows 10
- Vetur version: 0.19.5
- VS Code version: 1.33.1

## Problem

I'll be honest, I'm not sure if this should go here, or in the VSCode repo itself. I'm adding it here because I don't have this issue with pure CSS/SCSS files, making me think it is something with Vetur and not VSCode.

The `scroll-snap-align` property in SFC pops up with the little green squiggles. Mousing over them I get 'unknown property scroll-snap-align'. 

![Pure SCSS File](https://user-images.githubusercontent.com/8152471/57184388-b6465a80-6e6f-11e9-9bc6-8601b460a94d.png)

![Single File Component](https://user-images.githubusercontent.com/8152471/57184429-2d7bee80-6e70-11e9-8153-6ff95d7618ca.png)

I've checked this on both my windows PCs and my Ubuntu 19.04 install -- same thing on all of them. 

## Reproducible Case

1. Create a SFC with SCSS
2. Try to use the `scroll-snap-align` property, notice the green squiggles.

**Comment by octref** [comment]
This can be easily fixed by updating vscode-css-languageservice. I'll fix it soon.
