### ISSUE TITLE
Autocompletion VScode + Vetur in .vue files

### ISSUE THREAD

**Issue by orenmizr** [vuejs/vetur#1279]
- [y] I have searched through existing issues
- [y] I have read through [docs](https://vuejs.github.io/vetur)
- [y] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
## Problem

working in vue files i don't auto completion or intelligent completion in 
*template lang="pug"* --  no function and component completions
 *style lang="sass"*  -- no regular sass bg to background and more... i have to type that cr*p.

what i get is a bunch of nonsense regular word completion. i remember that use to work. i don't think i have anything that collides with it rather than emmet.

tried to reinstall - did not work. any ideas ?

**Comment by octref** [comment]
There's only syntax highlighting for pug and sass.

**Comment by fabruex** [comment]
> There's only syntax highlighting for pug and sass.

@octref is there the chance that it will be implemented?

**Comment by octref** [comment]
No, it's too much work and I don't have time.
