### ISSUE TITLE
Template Interpolation Service - @onClick MouseEvent

### ISSUE THREAD

**Issue by aphex** [vuejs/vetur#1281]
When using the new Template Interpolation Service with typescript a `@click=onHandleClick($event)` will get the error `Argument of type 'Event' is not assignable to parameter of type 'MouseEvent'.` When using the following handler

```
private onHandleClick (event: MouseEvent) { }
```

I believe this all comes down to this line here. Where the vOn transform assumes everything is of type `Event`. 
https://github.com/vuejs/vetur/blob/master/server/src/services/typescriptService/transformTemplate.ts#L196

Is there anyway to make this more specific? Check for all mouse related listeners and swap over to `MouseEvent`?

Not sure what the best workaround is at this point. I could do something like this
```
private onHandleClick (event: Event) {
    const mouseEvent = event as MouseEvent;
}
```
But this seems like a waste to add this extra variable assignment just to work around this issue. Plus it just feels wrong to have a handler with an incorrectly typed parameter.

Any thoughts are appreciated :) and I have no problem sending in a PR if its useful but I am guessing it's easier to just provide information at this point.

**Comment by ktsn** [comment]
Ideal solution would be to utilize [event map type](https://github.com/microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L5393) in `lib.dom.d.ts` and infer the `$event` type by using it.
