### ISSUE TITLE
.vue file Prettier format is broken in Vetur 0.20.0

### ISSUE THREAD

**Issue by cocody** [vuejs/vetur#1284]
- [ x] I have searched through existing issues
- [ x] I have read through [docs](https://vuejs.github.io/vetur)
- [ x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: mac & windows 10
- Vetur version: 0.20.0
- VS Code version: 1.33.1

## Problem
.vue file Prettier format is broken in Vetur 0.20.0

but in .js file is work file

**Comment by octref** [comment]
No repro -> closing.

**Comment by cocody** [comment]
vue -> js
![GIF.gif](https://i.loli.net/2019/05/09/5cd3a56c1d9ec.gif)

js file
![js.png](https://i.loli.net/2019/05/09/5cd3a56e42894.png)

vue file
![vue.png](https://i.loli.net/2019/05/09/5cd3a56ff29b4.png)

Vetur < 0.20.0, vue file is exist `Prettier √` status

**Comment by octref** [comment]
You should report a issue to https://github.com/prettier/prettier-vscode.

**Comment by jisi724** [comment]
have the same issue here, I believe it's vetur issue as it works fine with earlier version vetur @octref

**Comment by octref** [comment]
Please open new issue with repro case.
