### ISSUE TITLE
VLS requires init block, won't start without it

### ISSUE THREAD

**Issue by garyo** [vuejs/vetur#1291]
- [x ] I have searched through existing issues
- [ x] I have read through [docs](https://vuejs.github.io/vetur)
- [ x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

I'm using Emacs with the "eglot" package to connect to Vetur/VLS. When I recently updated VLS, it stopped working. I figured out that it's because vetur requires some initialization options, or else it won't start.

I fixed it (in emacs lisp) like this:

```
cl-defmethod eglot-initialization-options ((server eglot-vls))
  "Passes through required vetur initialization options to VLS."
  '(:vetur
    (:completion
     (:autoImport t :useScaffoldSnippets t :tagCasing "kebab")
     :grammar
     (:customBlocks
      (:docs "md" :i18n "json"))
     :validation
     (:template t :style t :script t)
     :format
     (:options
      (:tabSize 2 :useTabs :json-false)
      :defaultFormatter
      (:html "prettyhtml" :css "prettier" :postcss "prettier" :scss "prettier" :less "prettier" :stylus "stylus-supremacy" :js "prettier" :ts "prettier")
      :defaultFormatterOptions
      (:js-beautify-html
       (:wrap_attributes "force-expand-multiline")
       :prettyhtml
       (:printWidth 100 :singleQuote :json-false :wrapAttributes :json-false :sortAttributes :json-false))
      :styleInitialIndent :json-false :scriptInitialIndent :json-false)
     :trace
     (:server "verbose")
     :dev
     (:vlsPath ""))
    ))
```
(See https://github.com/joaotavora/eglot/issues/257)

Sorry I don't have a lot more info at this point. Hope this is helpful.

## Info

- Platform: Windows 10
- Vetur version: vue-langage-server@0.0.54
- VS Code version: none

**Comment by octref** [comment]
Thanks for reporting. This is tracked in #977.
