### ISSUE TITLE
.vue file Prettier format is broken in Vetur 0.20.0

### ISSUE THREAD

**Issue by lizy0329** [vuejs/vetur#1301]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: mac & windows 10
- Vetur version: 0.20.0
- VS Code version: 1.33.1

## Problem
.vue file Prettier format is broken in Vetur 0.20.0

but in .js file is work file

## Reproducible Case

It's very easy to Reproducible Case. 
1. Just create .js file and .vue file && install Prettier Plugin in vscode.
2. then setting `Prettier: Single Quote` is true. 
3. format and watching .js file and .vue file. then you can see that .js file `Double Quote => Single Quote`, .vue file `Double Quote => Double Quote`

vue -> js
![GIF.gif](https://i.loli.net/2019/05/09/5cd3a56c1d9ec.gif)

js file
![js.png](https://i.loli.net/2019/05/09/5cd3a56e42894.png)

vue file
![vue.png](https://i.loli.net/2019/05/09/5cd3a56ff29b4.png)

Vetur < 0.20.0, vue file is exist `Prettier √` status

#1284

**Comment by octref** [comment]
This is intended. See https://vuejs.github.io/vetur/formatting.html#settings.

Having two configs (.prettierrc and prettier.* settings in VS Code) is a source of confusion.

**Comment by lizy0329** [comment]
But I totally no .prettierrc in my work. I always use prettier setting to format my code.  this question is appearance in Vetur >= 0.20.0

√ Prettier: Single Quote.

In my .vue files, they are all become Double Quotes
In my .js files, they are still Single Quote

**Comment by octref** [comment]
Then you have to set

```
"vetur.format.defaultFormatterOptions": {
  "prettier": {
    // Prettier option here
    "singleQuote": true
  }
}
```

https://vuejs.github.io/vetur/formatting.html#settings

**Comment by sgehrman** [comment]
Doesn't work for me. This just started happening today.
