### ISSUE TITLE
Using :to in router-link with params breaks code

### ISSUE THREAD

**Issue by digiproductmarketer** [vuejs/vetur#1303]
- [ Y] I have searched through existing issues
- [ Y] I have read through [docs](https://vuejs.github.io/vetur)
- [ Y] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows 7
- Vetur version: 0.21
- VS Code version: 1.34.0

## Problem

https://www.dropbox.com/s/rnnadx4jm13ht2x/VeturScreenshot-2019-05-20-10.47.30.png?dl=0

## Reproducible Case

If I use :to and params in a router-link as shown in the image, and allow Vetur to auto-reformat, it breaks my code.

If I re-edit in an alternative editor, the code runs perfectly.

Returning to VSCode and Vetur and making any change, even just adding a blank space, and then allow Vetur to reformat it again ... breaks it once more.

**Comment by octref** [comment]
`vetur.format.defaultFormatter.html: "none"`. Or you can open an issue for the formatter you are using.

**Comment by digiproductmarketer** [comment]
Default Formatter for Style region: prettier
Default Formatter for Template region: prettyhtml
Default Formatter for Script region: prettier

**Comment by digiproductmarketer** [comment]
I just left everything as the defaults that were setuo on installation

I am using Quasar if that makes any difference

**Comment by octref** [comment]
Yes, set template region formatter to none or report issue to https://github.com/Prettyhtml/prettyhtml
