### ISSUE TITLE
The Vue Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted

### ISSUE THREAD

**Issue by zphhhhh** [vuejs/vetur#1304]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS 10.14.4
- Vetur version: 0.21.0
- VS Code version: 1.34.0

## Problem

The Vue Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

## Reproducible Case

(1~3 listed maybe not needed )

1. `rm -rf ~/.vscode`
2. `rm -rf ~/Library/Application\ Support/Code/`
3. remove VScode.app from Application
4. install VScode.app
5. install vetur
6. open a Vue project.

And I try https://vuejs.github.io/vetur/FAQ.html#no-syntax-highlighting-no-language-features-working but nothing good happens. related  #1239

**Comment by renestalder** [comment]
In case you're using TypeScript: I found that setting Vetur to use the project's TypeScript dependency to be the solution to that problem (it's a checkbox in the settings).

**Comment by octref** [comment]
If you provide no info for "Vue project", not even a stack trace, nothing I can help.

**Comment by renestalder** [comment]
@octref Why not helping the person to get and find the stack trace instead of just closing the ticket? Not everyone knows how to help debug these kind of issues.

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/58228595-10ef0b80-7ce4-11e9-8acc-71ea2aff1950.png)

![image](https://user-images.githubusercontent.com/4033249/58228737-80fd9180-7ce4-11e9-9b7f-98162890c087.png)

I can only work on issues with repro cases. My time is limited.

**Comment by zphhhhh** [comment]
My `jsconfig.json` causes the crash:
```json
{
  "include": [
    "./src/**/*"
  ],
  "compilerOptions": {
    "target": "esnext",
    "baseUrl": ".",
    "paths": {
      "@/**/*": [
        "src/**/*"
      ],
    }
  }
}
```

**Comment by zphhhhh** [comment]
I want to write `import BaseHeader from '@/components/BaseHeader';` but my filesystem is `components/BaseHeader/index.vue`.
It runs well but I cant jump to `BaseHeader/index.vue` file, so the `jsconfig.json` here, and then Vetur crashed.
Looks like Vetur couldnt identify the component correctly when I write `@/components/BaseHeader` but not `@/components/BaseHeader/index.vue`. I think `index.vue` should be added the default `require` list as same as `index.js`.
