### ISSUE TITLE
Template interpolation error - argument type is not assignable.

### ISSUE THREAD

**Issue by slushnys** [vuejs/vetur#1305]
- [√] I have searched through existing issues
- [√] I have read through [docs](https://vuejs.github.io/vetur)
- [√] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.21.0
- VS Code version: 1.34

## Problem

I don't get any errors in Vue Language Server output.

## Reproducible Case

Once I add `"vetur.validation.template": true,` and `"vetur.experimental.templateInterpolationService": true,` to my settings.json of VSCode I get an error in each .vue file I open. These files are SFC of vue. I'm using partially TypeScript and partialy JS in my code. tsconfig.js seems to be configured properly with includes of files and path of '@/*'.

> Argument of type '{ props: { message: { type: StringConstructor; default: string; }; id: { type: NumberConstructor; default: any; }; type: { type: StringConstructor; default: string; }; contentType: { type: StringConstructor; default: string; }; instanceType: { ...; }; coach: { ...; }; createdAt: { ...; }; startsAt: { ...; }; }; comp...' is not assignable to parameter of type 'new (...args: any[]) => any'.

> Type '{ props: { message: { type: StringConstructor; default: string; }; id: { type: NumberConstructor; default: any; }; type: { type: StringConstructor; default: string; }; contentType: { type: StringConstructor; default: string; }; instanceType: { ...; }; coach: { ...; }; createdAt: { ...; }; startsAt: { ...; }; }; comp...' provides no match for the signature 'new (...args: any[]): any'. Vetur(2345)

**Comment by ktsn** [comment]
Can you provide reproducible `.vue` file?

**Comment by octref** [comment]
Please open new issue with repro case.

**Comment by alukos** [comment]
my workaround was to add:
```<script>
import Vue from 'vue'
export default Vue.extend({
...
})
</script>
```

**Comment by J3m5** [comment]
I know this is an old issue but I'm encountering the same error, the workaround given by @alukos works but I'd prefer not to add this to all our components.
Is there anything to do ?
I use Quasar but not Typescript and it happens in any components even the most simple ones.
Even with something like 
```html
<template>
  <div>My component</div>
</template>

<script>
export default {
  data() {
    return {};
  },
};
</script>
```

> Argument of type '{ data(): {}; }' is not assignable to parameter of type 'new (...args: any[]) => any'.
  Type '{ data(): {}; }' provides no match for the signature 'new (...args: any[]): any'.

**Comment by J3m5** [comment]
Anyway, I can't reproduce this with a fresh Quasar project and I can't share the repository.

**Comment by micbra** [comment]
I had the exact same issue. Turns out that Vetur tries to resolve the version of Vue (or Quasar, Nuxt etc.) with the help of the `dependencies` array of the package.json whereas I had it in the `devDependencies`.

**Comment by vadimt2** [comment]
I have the same issue, How can I fix it?

**Comment by D4ITON** [comment]
![image](https://user-images.githubusercontent.com/35436405/135665897-c1327a32-0119-4968-aa33-70c61b2e7dce.png)
![image](https://user-images.githubusercontent.com/35436405/135665952-ea72b131-9f39-4f3a-97aa-caa9f3030629.png)

**Comment by yoyo930021** [comment]
> I'm getting the same error with the template tag, _without_ using `"vetur.validation.template": true` or `"vetur.experimental.templateInterpolationService": true` in settings.json, but when I open vscode to a folder one or more directories above my nuxt app.
> 
> @micbra is correct about vetur checking for a version of vue/nuxt/etc in package.json, commenting it out produces the same bug with the template tag, but vetur is probably also looking for a `package.json` file in the current working directory AND some other requirement. Copying the package.json to the top level directory does not solve the issue.
> 
> My current solution is to open vscode on the app folder.

Now, you can use `vetur.config.js`.
https://vuejs.github.io/vetur/guide/setup.html#advanced

**Comment by yoyo930021** [comment]
> ![image](https://user-images.githubusercontent.com/35436405/135665897-c1327a32-0119-4968-aa33-70c61b2e7dce.png)
> 
> ![image](https://user-images.githubusercontent.com/35436405/135665997-3a3978da-7d33-4259-b129-32c4ef72385b.png)
> 
> ![image](https://user-images.githubusercontent.com/35436405/135665952-ea72b131-9f39-4f3a-97aa-caa9f3030629.png)

We don't support `<template src="...">`.
If you want to ignore this error in vetur, you can open a new issue.

**Comment by yoyo930021** [comment]
The reason for this problem is very broad.
I will lock this issue, if you have a problem, open a new issue.
