### ISSUE TITLE
The $event is wrong when custom event

### ISSUE THREAD

**Issue by orblazer** [vuejs/vetur#1306]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: 0.21.0
- VS Code version: 1.33.1

## Problem

When use custom event the `$event` is wrong because this can be a value emited
 and not `Event`
![Screenshot_20190523_134404](https://user-images.githubusercontent.com/1344792/58254812-dc269700-7d6b-11e9-968f-5bc916c14b3b.png)

The event is emited with :
```ts
private value: Website.FieldValue = ''

@Emit('change')
private onChange () {
  return this.value
}
```

## Reproducible Case

1. Create component
2. Send an event with value, like :
    ```ts
    this.$emit('event', 'value')
    ```
3. Bind the event with inline value like :
    ```vue
    <component @event="onEvent('test', $event)" />
    ```
    The method :
    ```ts
    onEvent (type: string, value: string) {
      console.log(type, value)
    }
    ```

**Comment by ktsn** [comment]
Oh, I didn't know we can use `$event` value on component event. Maybe we should change `$event` type to `any` for now...
