### ISSUE TITLE
When project has jsconfig.json with path alias, ".vue" intellisense is slow

### ISSUE THREAD

**Issue by anuoua** [vuejs/vetur#1307]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: win
- Vetur version: 0.21.0
- VS Code version: 1.34.0

## Problem

when project with `jsconfig.json` has path alias, `.vue` intellisense is slow, `*.js`  normal.

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/@/*"],
       ...other 5 path maps,
      "$public/*": ["./src/$public/*"]
    }
  },
  "exclude": [
    "node_modules"
  ]
}
```

## Reproducible Case
`.vue`

![xccfxfsdfsd](https://user-images.githubusercontent.com/11324632/58255584-e5c9f200-7d9f-11e9-97aa-e1149b03d219.gif)

`.js`

![xccfxfsdfsd](https://user-images.githubusercontent.com/11324632/58255910-9afcaa00-7da0-11e9-8905-cb22e5ecbcae.gif)

**Comment by octref** [comment]
Can you either:
- Create a repro case out of https://github.com/octref/veturpack
- Follow https://github.com/vuejs/vetur/blob/master/.github/PERF_ISSUE.md and attach a profile here

**Comment by arnold-graf** [comment]
I have the same situation using TypeScript with my `tsconfig.json`. It seems like the more aliases I have, the slower it gets.

**Comment by kjleitz** [comment]
Related: [Possible diagnosis?](https://github.com/vuejs/vetur/issues/789#issuecomment-517787960)

**Comment by Kurtz1993** [comment]
Hello, guys.
I was experimenting this issues today and it seems related to my Path Autocomplete extension. As you can see in the gif below, when I uninstalled it, IntelliSense worked as expected.
Vetur version: 0.22.4
VS Code version: 1.39.1
macOS Catalina: 10.15
![Oct-12-2019 4-59-19 PM](https://user-images.githubusercontent.com/5412470/66708163-c5301380-ed11-11e9-8c32-a13581972264.gif)

**Comment by octref** [comment]
https://github.com/vuejs/vetur/issues/1286 should have improved this. If it didn't, please open a new issue with profile. Thanks.

**Comment by marvinside** [comment]
I setup path-mappings a few days ago.
Since then, Vetur is really slow.

It seems like Vetur is having a queue with file-states to analyze:
If i start typing something like `long_word`, i can often see errors like:

`'lon' is unknown`<br>
`'long_' is unknown` ( a few seconds later)<br>
`'long_wor' is unknown` (more seconds later)



I'll create a reproduction repository in the next few days.
