### ISSUE TITLE
Strange error with possible undefined property

### ISSUE THREAD

**Issue by orblazer** [vuejs/vetur#1308]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: 0.21.0
- VS Code version: 1.33.1

## Problem

I have strange error on `new Date` with potential undefined property
![Screenshot_20190523_173704](https://user-images.githubusercontent.com/1344792/58266162-69c0b180-7d81-11e9-92a2-4b818d3a5ffc.png)

The `user.createdAt` is defined in an interface with :
```ts
createdAt?: Date
```

## Reproducible Case

1. Create an property with potential property undefined like :
    ```ts
    test: { testVal?: Date } = {
      testVal: new Date()
    }
    ```
2. Try display that property with `{{ new Date(test.testVal || 0) }}`

**Comment by ktsn** [comment]
This is because `NewExpression` is currently not handled by template interpolation service. I'll add support for it.
