### ISSUE TITLE
Vetur Adding Semicolon to <script>

### ISSUE THREAD

**Issue by xon52** [vuejs/vetur#1320]
## Info
- Platform: Win
- Vetur version: 0.21.0
- VS Code version: 1.35.0

## Problem
![Screenshot_1](https://user-images.githubusercontent.com/30713944/59022844-ea0f0880-8891-11e9-82be-7d0fa8d8d817.png)

## Reproducible Case
VS Code settings.json:
```
	"prettier.semi": false,
	"prettier.jsxSingleQuote": true,
	"prettier.trailingComma": "all",
	"prettier.eslintIntegration": true,
	"prettier.singleQuote": true,
	"prettier.tabWidth": 4,
	"prettier.useTabs": true,
	"vetur.format.options.useTabs": true,
	"vetur.format.options.tabSize": 4,
	"vetur.format.scriptInitialIndent": true,
	"vetur.format.styleInitialIndent": true,
```

Just started recently without any known changes. Only affecting .vue files (prettier works fine in .js files).

**Comment by yoyo930021** [comment]
you can use `.prettierrc` file at project root.
or
```
"vetur.format.defaultFormatterOptions": {
  "prettier": {
    // Prettier option here
    "semi": false
  }
}
```

**Comment by xon52** [comment]
> you can use `.prettierrc` file at project root.
> or
> 
> ```
> "vetur.format.defaultFormatterOptions": {
>   "prettier": {
>     // Prettier option here
>     "semi": false
>   }
> }
> ```

I really didn't want to have a .prettierrc file for every project, so second option is perfect. Thanks for your help.

**Comment by TerraTech** [comment]
@xon52 any chance of this being added to the FAQ?  I went around in circles trying to figure out how to fix it before finding this issue and applying the fix in "settings.json".  Thanks!

**Comment by octref** [comment]
@TerraTech Wanna send a PR to clarify https://vuejs.github.io/vetur/formatting.html#settings? I'd be happy to review it. File to change: https://github.com/vuejs/vetur/blob/master/docs/formatting.md
