### ISSUE TITLE
When import .vue inside .js file it gives module not found in vscode

### ISSUE THREAD

**Issue by sagarrabadiya** [vuejs/vetur#1322]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.21.0
- VS Code version: 1.35.0

## Problem
When `.vue` file is imported from `.js` file and `checkJs` is `true` in `jsconfig.json` file vscode gives error that it can't find module even though `.vue` extension is included in the import please check the screenshot.

![vetur-problem](https://user-images.githubusercontent.com/5405403/59082199-a0650300-890f-11e9-80d2-8d34920757f5.png)

## Reproducible Case

Just create new app using vue-cli and in `main.js` try to `ctrl + click` on `App.vue` import it doesn't take me to the `App.vue` file.

**Comment by yoyo930021** [comment]
You need to add one file.
see https://github.com/microsoft/TypeScript-Vue-Starter/blob/master/README.md#single-file-components.

**Comment by sagarrabadiya** [comment]
Hi @yoyo930021 I have tried by adding `vue-shims.d.ts` but when I add `vue-shims.d.ts` file the module not found error is gone but the problem is when I try to find the module definition or try `ctrl + click` on the imported component it doesn't take me to the `.vue` file instead it shows the ts declared module as definition please check the screenshot
![image](https://user-images.githubusercontent.com/5405403/59142263-05d0f680-89d9-11e9-9c5d-f5f3cca08be1.png)

**Comment by yoyo930021** [comment]
jsconfig.json content?

**Comment by sagarrabadiya** [comment]
@yoyo930021 here is the `jsconfig.json` content

```json
{
  "include": ["./src/**/*"],
  "compilerOptions": {
    "module": "es6",
    "moduleResolution": "node",
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    },
    "checkJs": true
  },
  "exclude": ["node_modules"]
}
```

**Comment by yoyo930021** [comment]
I think it's a problem.
The `.ts` file have the same problem.

**Comment by sagarrabadiya** [comment]
Yes exactly, if i `ctrl + click` from `.vue` file then it works, meaning if i import `.vue` file inside `.vue` file's script tag then it navigates correctly but if `.vue` file is imported from `.js` or `.ts` file then it can't detect that module as .vue component

**Comment by yoyo930021** [comment]
When use `.ts` or `.js` files, VSCode use `typescript-language-server`.
It don't know `.vue` file, It use `vue-shims.d.ts` file to know.

When use `.vue` files, VSCode use `vue-language-server` in vetur.
It can know `.vue` file by itself, so can get more info.

The above is my guess.

**Comment by octref** [comment]
Depends on #673, for now you can take a look at https://github.com/HerringtonDarkholme/vue-ts-plugin.

**Comment by huoyuxin** [comment]
it just can not recognize and go to the definition the .vue import in .js / .ts
so, there is a little trick:
you can change .js / .ts to .vue, and use <script lang="ts"></script> to wrap the .vue import code, then everything goes perfect

**Comment by Joe-Joi** [comment]
for me, adding '.vue' extention is the only solution: `import App from "./App.vue";`
