### ISSUE TITLE
node_modules里面的所有文件报错

### ISSUE THREAD

**Issue by GaoXiaoBoGitHub** [vuejs/vetur#1327]
![image](https://user-images.githubusercontent.com/41282358/59167430-d1d60c80-8b63-11e9-906d-9a8aed76a584.png)
vscode和vetur都是最新版本，卸载此插件后不会出现问题

**Comment by yoyo930021** [comment]
ESLint error ?
Ignore it.

**Comment by GaoXiaoBoGitHub** [comment]
eslint关了不起作用，各种方法都试了，最后卸载vetur就不会出现这个问题

**Comment by yoyo930021** [comment]
可以給我相關的設定嗎？
是不是有 `jsconfig.json` 或是 `tsconfig.json` ?

**Comment by yoyo930021** [comment]
截圖下方狀態列 辨識成什麼類型的檔案？

**Comment by GaoXiaoBoGitHub** [comment]
所有配置全部删除也是没有，文件类型是node_modules里面的所有文件
![image](https://user-images.githubusercontent.com/41282358/59174667-d2cb6600-8b84-11e9-8f7a-9a9b2d29a189.png)

**Comment by yoyo930021** [comment]
可以給我一個最小重現專案嗎？
用 Vue CLI 開一個專案 把連結丟上來

**Comment by ShineKidd** [comment]
老版本的 VSCode 不会，vuter 是自动更新的， 手贱！升级 VSCode 到 1.35.0 后出现这个问题

**Comment by octref** [comment]
Please provide a repro case.

**Comment by chayin** [comment]
+1，请问有人解决了吗 😂
vscode：1.37.1
vetur：0.22.2

**Comment by Somefuture** [comment]
> 老版本的 VSCode 不会，vuter 是自动更新的， 手贱！升级 VSCode 到 1.35.0 后出现这个问题

呜呜呜哭了 我也是更新完就这样了

**Comment by chbro** [comment]
+1 请问有解决办法了吗

**Comment by hqzh** [comment]
`
<script lang="js">
   // lang="js" 
   // Error does not appear
</script>
`

**Comment by yoyo930021** [comment]
麻煩提供可重現的專案
不然沒有人能幫你們看發生什麼事
也自然沒辦法修復這個 bug
