### ISSUE TITLE
0.21.0 Request textDocument/definition failed.

### ISSUE THREAD

**Issue by pangxieju** [vuejs/vetur#1328]
## Info
- Platform: macOS Mojave 10.14.5
- Vetur version:0.21.0
- VS Code version:1.35.0

## Problem
Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 

## Reproducible Case
1.Open the ‘.vue’ file.
2.Hold down the shortcut key command+c.

Switching ‘Vetur 0.18.1’ does not have this problem.

Thank！

**Comment by octref** [comment]
Please open a new issue with repro case.

**Comment by pangxieju** [comment]
Thank！The latest vscode does not have this problem.
