### ISSUE TITLE
HTML properties in camelCase automatically correcting to lowercase breaks nativescript-vue

### ISSUE THREAD

**Issue by DKhalil** [vuejs/vetur#1332]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win 10
- Vetur version: 0.21.0
- VS Code version: 1.35.0

## Problem

Certain props like colSpan get autocorrected to lowercase. which breaks Nativescript-Vue, which requires certain props to be written in camelCase.

## Reproducible Case

Write colSpan in a tag and save.

**Comment by DKhalil** [comment]
Okay, so I got it fixed now by switching vetur's default HTML formatter from prettyhtml to prettier

![image](https://user-images.githubusercontent.com/497250/59430939-e88a9680-8de3-11e9-860a-e489f63d3164.png)

Apparently (according to the Nativescript Slack) this issue is coming up regularly, so I'll leave this open for now and let you decide what to do with it.

**Comment by octref** [comment]
See https://github.com/Prettyhtml/prettyhtml/issues/93. I think prettyhtml made a reasonable choice. If it doesn't work for you, you can use other formatters.
