### ISSUE TITLE
Syntax Highlight Issue with shorthand

### ISSUE THREAD

**Issue by mikeerickson** [vuejs/vetur#1333]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.21.0
- VS Code version: Insiders 1.36

## Problem

When using markup shorthand, the syntax highlighting has issues

![image](https://user-images.githubusercontent.com/183153/59392162-88381e00-8d2b-11e9-8154-a70d7f22f761.png)

## Reproducible Case

1. You can see from the above screenshot how to reproduce.  If i use the `v-on:click` it is highlighted correctly, however, if i use the `@click` shortcut, then it does not appear correctly.

**Comment by octref** [comment]
I can't repro. Please provide full file.

![image](https://user-images.githubusercontent.com/4033249/59742482-5df0de00-92a0-11e9-90e8-275df6bc11ab.png)

**Comment by mikeerickson** [comment]
@octref Here is an example Vue component which exhibits the issue I am reporting

```
<template>
    <div>
        <modal name="confirm" width="450px" height="auto">
            <div class="tw-ml-3">
                <h1 class="tw-pb-3 tw-pt-3">{{ title }}</h1>
                <p>
                    {{ description }}
                </p>
                <div class="tw-mr-3 tw-mt-5 tw-mb-1 tw-float-right tw-mb-3">
                    <button class="btn btn-secondary tw-pr-3" v-on:click="cancel">Cancel</button>
                    <button class="btn btn-primary tw-pr-3" @click="accept(12)">Submit</button>
                </div>
            </div>
        </modal>
    </div>
</template>

<script>
export default {
    props: {
        title: {
            type: String,
            default: 'Confirm'
        },
        description: {
            type: String,
            default: 'Description'
        }
    },
    data() {
        return {}
    },
    methods: {
        cancel() {
            this.$modal.hide('confirm')
            console.log('cancel')
        },
        accept(id) {
            this.$modal.hide('confirm')
            console.log('accept ' + id)
        }
    }
}
</script>
```

**Comment by octref** [comment]
It's probably a bug of your theme:

![image](https://user-images.githubusercontent.com/4033249/60283286-ac643500-98bd-11e9-965d-dfa3ea96c035.png)

You can use "Developer: Inspect TM Scopes" command to see why they are colored like so:

![image](https://user-images.githubusercontent.com/4033249/60283329-c56ce600-98bd-11e9-8cc6-f9c9bbe4696d.png)

I don't think there's anything I can do from Vetur. You can try to find a better theme.

**Comment by mikeerickson** [comment]
@octref OK, thank you very much for your efforts. I will review other themes and see how it goes.

**Comment by octref** [comment]
My theme is Nord if you want to give it a try. I also had good experience with Material theme. Bundled Dark+ is always a safe bet.

**Comment by mikeerickson** [comment]
I am using Material theme?

**Comment by mikeerickson** [comment]
I am using Material theme?

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/60290591-e6d5ce00-98cd-11e9-869f-7937eb660cf7.png)

You likely have some `workbench.colorCustomizations` settings, or you have some extensions that does weird things like inserting CSS.

**Comment by mikeerickson** [comment]
@octref perhaps. I will take a closer look and see what I might have done.
