### ISSUE TITLE
Templates in custom blocks are parsed as root elements

### ISSUE THREAD

**Issue by elevatebart** [vuejs/vetur#1336]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: MacOS
- Vetur version: 0.21.0
- VS Code version: 1.35.1

## Problem
When using `<template>` tag in a custom block, the valid-template-root from eslint throws.
When I run eslint I do not see a problem though.

## Reproducible Case

```
<template>
  <div>hello world</div>
</template>

<docs>
` ``vue
<foo>
  <template>
    <div>bonjour</div>
  </template>
</foo>
` ``
</docs>
```

**Comment by nicooprat** [comment]
Having this issue too, using https://github.com/vue-styleguidist/vue-styleguidist.

```
[vue/valid-template-root]
The template root requires exactly one element. eslint-plugin-vue
```

**Comment by lukenofurther** [comment]
I'm also having this issue in VS Code v1.39.0 on Windows

**Comment by lukenofurther** [comment]
So it should work if there is a value for styleguideDir in the config? I have styleguideDir set and am still seeing the issue.

![image](https://user-images.githubusercontent.com/3300647/67876147-5800e880-fb2f-11e9-8b1c-b8b4074bd463.png)

**Comment by schjetne** [comment]
Any progress on this issue? It's a bit distracting having the entire file marked as error when I know there's no error.

**Comment by dflock** [comment]
This is happening to me suddenly and is quite annoying. Affects any .vue file with a nested `<template>` anywhere inside the top level template block:

VSCode version info:

Version: 1.44.0-insider
Commit: e62c4302b0e4f3e28bbcb0f3b6e46bb00e39679c
Date: 2020-03-26T05:42:29.005Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-66-generic

Vetur version: 0.24.0

![image](https://user-images.githubusercontent.com/47756/77710150-87a30800-6f8a-11ea-9dca-5521c920dbea.png)

![image](https://user-images.githubusercontent.com/47756/77710171-94bff700-6f8a-11ea-86e5-4884f8377c2b.png)

**Comment by yapTim** [comment]
This issue pops up in my VSCode too. Is this going to get a fix soon?

**Comment by stupidcats99** [comment]
I've had this issue over a year. Any progress or workaround for this?
