### ISSUE TITLE
How to work with Remote Development

### ISSUE THREAD

**Issue by JMDC-SUN** [vuejs/vetur#1342]
## Info

- Platform: Win
- Vetur version: 0.21.0
- VS Code version: Version: 1.36.0-insider (user setup)
   with Remote Development
## Problem
I use it in Vscode +  Remote Development extension, but not work.
How to work in vscode with Remote Development.

**Comment by octref** [comment]
Please provide **reproducible** steps: https://stackoverflow.com/help/minimal-reproducible-example.
