### ISSUE TITLE
IntelliSense doesn't work with PostCSS Simple Variables

### ISSUE THREAD

**Issue by franciscolourenco** [vuejs/vetur#1345]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.21.1
- VS Code version: 1.35.1

## Problem
[PostCSS Simple Variables](https://github.com/postcss/postcss-simple-vars) is a plugin for Sass-like variables.

The syntax highlight supports `var(--variable-name)`, `--variable-name`, and dollar style variables `$variable`

IntelliSense doesn't seem to support dollar style variables `$variable`.

IntelliSense works before any `$variable` is used:
<img width="728" alt="IntelliSense works" src="https://user-images.githubusercontent.com/208149/60399480-2bc76200-9b65-11e9-8ea9-f62b5a4fe34e.png">

IntelliSense doesn't work after simple-var style `$variable` is used:
<img width="711" alt="Intellisense does not work" src="https://user-images.githubusercontent.com/208149/60399481-2ec25280-9b65-11e9-895e-eb5697df8001.png">

## Reproducible Case

1. Install https://github.com/postcss/postcss-simple-vars
2. Define a variable
3. Use a variable
4. Try to use intellisense in the line after the variable was used

**Comment by octref** [comment]
Vetur's CSS support is based on VS Code's CSS support, which only implements support for 2 kind of features:

1. Features in CSS Spec
2. Features in SASS / Less

There's no support for arbitrary postcss plugins.
