### ISSUE TITLE
Vetur not inferring types correctly, thinks computed property is a vuex `MutationMethod` 

### ISSUE THREAD

**Issue by ShailenNaidoo** [vuejs/vetur#1346]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows 10
- Vetur version: 0.21.1
- VS Code version: 1.35.1

## Problem
I am getting this weird error I am using `mapState` to bind `customItems` property to my component from vuex. I am spreading `mapState` into the `computed` property. When i use `customItems` anywhere in the component, Vetur thinks that `customItems` is of `type MutationMethod`

Here is the component:
![image](https://user-images.githubusercontent.com/26552540/60535156-c5c51100-9d03-11e9-8934-42a6989ffbc8.png)

Here is the error:
![image](https://user-images.githubusercontent.com/26552540/60535067-8bf40a80-9d03-11e9-9583-b1e2a897ee03.png)

## Reproducible Case

1. Create a Vue component
2. use `mapState` to bind a property from Vuex to the component
3. Try to use that property elsewhere in the component
4. You should get an error

**Comment by ktsn** [comment]
This is because return type of `mapXXX` is just a record type. You need to cast it by yourself currently.

```
...mapMutation({
  addCustomItem: 'form/ADD_CUSTOM_ITEM'
}) as {
  addCustomItem: (payload: any) => void
}
```

Closing as this is Vuex problem rather than Vetur.

**Comment by ShailenNaidoo** [comment]
Thanks
