### ISSUE TITLE
Couldn't resolve `'types' can only be used in a .ts file. Vetur(8010)`

### ISSUE THREAD

**Issue by shuta13** [vuejs/vetur#1347]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS 
- Vetur version: 0.21.1
- VS Code version: 1.35.1

## Problem

I tried to use Vetur in my project of TypeScript with Nuxt.js. Then, `'types' can only be used in a .ts file. Vetur(8010)` appeared.

<img width="500" alt="vetur-with-nuxt-2019-7-4-1" src="https://user-images.githubusercontent.com/38882716/60612989-ef199600-9e04-11e9-948a-381d6c27e7f6.png">

However, I found this message didn't appear when I tried to use Vetur in a project of TypeScript with Vue CLI.

Would you show me how deal with that message when using Vetur in TypeScript with Nuxt.js?

**Comment by ktsn** [comment]
It shouldn't be appeared if the block is `lang="ts"`. Can you provide a self-contained repro? (pasting .vue file, providing example github repo etc.)

**Comment by shuta13** [comment]
I found it is possible to solve this problem through removing `vue-property-decorator` and adding `nuxt-property-decorator`. So it is not problem of Vetur. I'm sorry.

**Comment by valentineus** [comment]
My solution to this problem:
I added `"allowJs": true` and `"checkJs": true` to file `tsconfig.json`.

**Comment by tbenyon** [comment]
My solution was to:
- Ensure I had `lang="ts"` as an attribute in my script tag (as described above)
- Restart VS Code

**Comment by nextmat** [comment]
In case this helps anyone else, I also ran into this issue when I had a `<script lang="ts">` block and later in my component I had an additional, leftover `<script>` block that was empty.

**Comment by MarianVasile** [comment]
For people using `@flow`, using `<script lang="js">` fixes the issue in a similar manner.

**Comment by tombohub** [comment]
I have installed fresh with Vite, choose Typescript, and have this error

**Comment by islomrakhimkulov** [comment]
I came across this issue in my Vue 3 TypeScript project. You should rename your file name and change it back again. For example: .vue rename to .ts and renaming it to back .vue from this aproach problem solved for me.
