### ISSUE TITLE
prettier overrides eslint

### ISSUE THREAD

**Issue by kingwins** [vuejs/vetur#1349]
I have Vetur set to prettier-eslint JS formatting. 

When I press Alt+Shift+F in .js file it is formatted properly to ES6 with ESlint

When I do it in .vue files it is getting formatted to ES5 (adding semicolons, removing space before functions parentheses etc),

I read internet, tried everything. HELP

**Comment by RCVarley** [comment]
Yeah I had the same issue.  As a temporary fix, I've disabled Vetur's formatter in my VSCode settings.

**Comment by octref** [comment]
You probably need to configure formatter settings correctly.
https://vuejs.github.io/vetur/formatting.html#settings
