### ISSUE TITLE
Syntax highlighting doesnt work with v0.21.1

### ISSUE THREAD

**Issue by rafagarcia** [vuejs/vetur#1351]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  . macOS Mojave 10.14.5
- Vetur version: 0.21.1
- VS Code version: 1.36.0 

## Problem

With version 0.21.1 syntax highlighting doesn´t work.
If i downgrade to 0.21.0 SH works perfectly.

**Comment by octref** [comment]
https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#no-syntax-highlighting--no-language-features-working

You likely need to force removal of Vetur and reinstall again.
