### ISSUE TITLE
custom block intellisense still not a thing?

### ISSUE THREAD

**Issue by synonymousz** [vuejs/vetur#1353]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.21.1
- VS Code version: 1.36.1

## Problem
As mentioned in this issue:
https://github.com/vuejs/vetur/issues/690#issuecomment-365330211
Syntax-Highlighting is the only thing supported by the custom blocks.

In our current development workflow we do have an `<php></php>` custom block in wich much logic is happening before giving out the response to the user. That is, because we are adopting our legacy application to .vue files. We have added the php-custom-block to do some of our legacy-stuff. With php configured as a custom-block we already have your highlighting wich is awesome already. The greatest thing for our dev-team would be to be able to use the php-intelephense extension with those  custom-blocks.
Is this still not gonna happen? If so, is there the possibility to add this in a fork and do you have tips though? (We are not into extension-development)

One more thing, not directly related to this:
We would like to see "xml" added to the supported languages for the custom-blocks :)

Thanks in advance

**Comment by octref** [comment]
I know nothing about PHP. I suggest you reference to an external PHP file.

I'm not opposed to it, if you do find a way to cleanly outsource the PHP functionality to PHP extensions and let Vetur just forward the LSP requests/responses in that custom `<php>` region.
