### ISSUE TITLE
`this` will become any type in vue methods if use typescript

### ISSUE THREAD

**Issue by shjyh** [vuejs/vetur#1356]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  win
- Vetur version: 0.21.1
- VS Code version: 1.36.1

## Problem

![code](https://user-images.githubusercontent.com/7910808/61210182-49342880-a72e-11e9-8a1c-07b63ea8ffd5.gif)

**Comment by ktsn** [comment]
You need to wrap the component options with `Vue.extend` in TypeScript.

https://vuejs.org/v2/guide/typescript.html#Basic-Usage
> To let TypeScript properly infer types inside Vue component options, you need to define components with Vue.component or Vue.extend:

**Comment by shjyh** [comment]
![code](https://user-images.githubusercontent.com/7910808/61215229-ca92b780-a73c-11e9-822f-a821e9124aef.gif)
I used it but it didn't work

**Comment by shjyh** [comment]
need include strict: true in tsconfig. thanks, it works
