### ISSUE TITLE
yarn install error due to private package registry

### ISSUE THREAD

**Issue by hikerpig** [vuejs/vetur#1357]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  Mac
- Vetur version:
- VS Code version:

## Problem

Try to run `yarn` but I failed while fetching packages, error log is

```
error An unexpected error occurred: "https://averi.at:4873/@types%2fjs-yaml/-/js-yaml-3.12.0.tgz: connect ECONNREFUSED 89.22.103.43:4873"
```

I found a strange registry `averi.at:4873` in yarn.lock, with several packages.

```
"@types/events@*":
  version "3.0.0"
  resolved "https://averi.at:4873/@types%2fevents/-/events-3.0.0.tgz#2862f3f58a9a7f7c3e78d79f130dd4d71c25c2a7"
```

Could these be replaced by npm public packages?

**Comment by octref** [comment]
@Patcher56 FYI, seems to come from you when you added some dependencies.

**Comment by Patcher56** [comment]
Oh yeah you're right, we use our own registry. Sorry!
