### ISSUE TITLE
render function intellisense not work smart suggestion for tags

### ISSUE THREAD

**Issue by joacub** [vuejs/vetur#1362]
intellisense doesn't work on render function with jsx, any configuration additional is necessary ?

**Comment by ktsn** [comment]
Please provide more detailed information and a reproduction. At least we need following info to work on an issue:

- Environement
    - Your Platform (Windows, macOS, Linux)
    - Vetur version
    - VS Code version
- Expected behavior
- Actual behavior
- Minimal reproduction (snippet or example github repo)
- Steps to reproduce the issue

**Comment by octref** [comment]
Closed as nothing is actionable.
