### ISSUE TITLE
Cannot view references to .vue files after using webpack alias

### ISSUE THREAD

**Issue by AFu-1993** [vuejs/vetur#1363]
## Problem Description

In VS code, hold down ctrl+click and you cannot jump to the App.vue file.
![image](https://user-images.githubusercontent.com/25973349/61757899-13a9d200-adf5-11e9-830a-b79e54ec6244.png)

## environment

**My project structure**
![image](https://user-images.githubusercontent.com/25973349/61758093-fb868280-adf5-11e9-806a-68e264bb0949.png)

I configured the jsconfig.json file as directed by my vetur documentation.
```  json
{
  "compilerOptions": {
      "baseUrl": ".",
      "paths": {
          "components/*": [
              "src/components/*"
          ]
      }
  }
}
```

**Comment by luxwarp** [comment]
Your jsconfig.json is the problem.  Change 

```
"paths": {
          "components/*": [
              "src/components/*"
          ]
```

To

```
"paths": {
          "@/*": [
              "src/*"
          ]
```

And you should be good ! :D

**Comment by octref** [comment]
See @luxwarp's answer. You should use path aliases.
