### ISSUE TITLE
Custom tags intellisense for local files

### ISSUE THREAD

**Issue by rohit-gohri** [vuejs/vetur#1364]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux (Ubuntu 16.04)
- Vetur version: 0.21.1
- VS Code version: 1.36.1

## Problem

I found that there is no (documented) way to specify a `tags.json` and `attributes.json` file for custom-tags in one's own project, that are not in any dependency.

I only found https://vuejs.github.io/vetur/framework.html#custom-tags-attributes. But that is only for modules being published on npm and being used as a dependency. What about custom-tags in own project?

I tried adding a "vetur" key to my project and adding corresponding files, but it didn't pick anything up.

I think this should be trivial to implement as the major work is already done.

**Comment by phiter** [comment]
This functionality also has no proper documentation whatsoever.

I could only have an idea of what is possible by looking at other framework implementations.

It shouldn't be that hard to make a table with the available options for both tags and attributes.

**Comment by rchl** [comment]
I see that PR adds an example for tags.json. It would be also nice to provide an example for attributes.json.

**Comment by octref** [comment]
@rchl I plan to have a more comprehensive doc for the format in by next release. I'll fix #1757 with it. Please subscribe to that issue.
