### ISSUE TITLE
Line Comments don't work in SCSS style block of SFCs

### ISSUE THREAD

**Issue by johndugan** [vuejs/vetur#1370]
Issue Type: <b>Bug</b>

Open any single file component where the `<style>` block includes a `lang="scss"` attribute. Place your cursor in front of any line and enter the keyboard shortcut for "Toggle Line Comment" (default is `ctrl+/`). This should result in a `//` inserted at the beginning of the line. Instead, it wraps the line in a `/* */` block comment.

While `//` is not valid for CSS comments, it is for SCSS. If you setup a key binding for "Toggle Block Comment" (mine is `ctrl+alt+/`), you should be able to toggle _both_ Line and Block comments in the `<style lang="scss">` block of any single file component (like you can in a .scss file).  

Extension version: 0.21.1
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (18.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|31.83GB (18.34GB free)|
|VM|0%|
</details>

**Comment by octref** [comment]
![scss-comment](https://user-images.githubusercontent.com/4033249/62643308-8a1df800-b8fc-11e9-8a3b-092420f112de.gif)

I can't repro.

**Comment by johndugan** [comment]
@octref appreciate quick visual.

I dug further - ended up being a conflict with the [vscode-styled-components extension](https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components). I've disabled that and Vetur is working as expected.
