### ISSUE TITLE
style and script tag initial indent does not follow editorconfig

### ISSUE THREAD

**Issue by trusktr** [vuejs/vetur#1375]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macos
- Vetur version: 0.21.1
- VS Code version: 1.36.1

## Problem

The initial indent for style and script tags is not following formatting options that I have specified in prettier, though this makes sense if Vetur is formatting each section separately, with different formatters, and has a separate formatter for the initial indent. (not obvious at first).

Perhaps is should respect the project's `.editorconfig`. Mine for example has:

```conf
# EditorConfig is awesome: http://EditorConfig.org

# top-most EditorConfig file
root = true

[*]
charset = utf-8
indent_style = tab
indent_size = 4
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
```

## Workaround

I was able to use the `Vetur > Format > Options: Tab Size` and `Vetur > Format > Options: Use Tabs` options to configure the initial indent.

If it followed editorconfig, that'd be sweet!

**Comment by trusktr** [comment]
Another good reason for following editorconfig is that settings may be different across projects.

**Comment by octref** [comment]
Vetur doesn't read editorconfig. Sorry.
