### ISSUE TITLE
Having typescript with class and "normal" components mixed causes errors

### ISSUE THREAD

**Issue by schnetzi** [vuejs/vetur#1378]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS 10.14.6
- Vetur version: 0.21.1
- VS Code version: 1.37.0

## Problem
I cannot call the methods from the data object.

![image](https://user-images.githubusercontent.com/5382986/62791842-4e3a8c80-bace-11e9-996c-522736ecfc33.png)

![image](https://user-images.githubusercontent.com/5382986/62791093-c0aa6d00-bacc-11e9-98f9-d03afe685d78.png)

## Reproducible Case
I made an example project with my problems:
https://github.com/schnetzi/vetur-problem

## What did I try so far
* I downgraded to v0.18.1

## Additional Question
* How do I give my scenarios in this case a type? I tried with type `Array` but then I get a lot more errors.

**Comment by ktsn** [comment]
This is Vue's typing issue. You cannot access methods in `data` hook.
See: https://github.com/vuejs/vue/issues/8721
