### ISSUE TITLE
Why is there no less or sass emmet hint for the style tag?

### ISSUE THREAD

**Issue by liby** [vuejs/vetur#1386]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.22.0
- VS Code version: 1.37.0

## Problem
- The following tags are not prompted in my editor. 
 - It was all normal before.
```
template with html
template with pug
script with JavaScript
script with TypeScript
style with CSS
style with CSS (scoped)
style with scss
style with scss (scoped)
style with less
style with less (scoped)
style with sass
style with sass (scoped)
style with postcss
style with postcss (scoped)
style with stylus
style with stylus (scoped)
```
![image](https://user-images.githubusercontent.com/38807139/62924968-d9c06000-bde3-11e9-8384-7bfa62761929.png)

![demo](https://user-images.githubusercontent.com/38807139/62924831-7f270400-bde3-11e9-8c95-95e74fa980d1.gif)

## Reproducible Case

There is no step that can be described, that is, the auto-complete prompt of the label suddenly disappears, and it is not suitable.

**Comment by showcheap** [comment]
Facing same issue after update vscode to 1.37.0, but autocomplete shown when we start with `<script...`

![Screenshot from 2019-08-13 20-27-17](https://user-images.githubusercontent.com/1310895/62945356-c83d7f00-be08-11e9-9526-5cd33439e87d.png)

**Comment by liby** [comment]
> 更新vscode到1.37.0后面临同样的问题，但是当我们开始时显示自动完成 `<script...`
> 
> ![截图2019-08-13 20-27-17](https://user-images.githubusercontent.com/1310895/62945356-c83d7f00-be08-11e9-9526-5cd33439e87d.png)

I am considering using the previous version of vscode to try

**Comment by octref** [comment]
The `scaffold` snippets have been renamed to start with either `<vue>`, `<style>`, `<script>` or `<template>`.

I'm sorry for removing the old `scaffold` snippets, but they are replaced by https://vuejs.github.io/vetur/snippet.html#customizable-scaffold-snippets.

**Comment by octref** [comment]
With that being said, I did add back postcss/stylus scaffold snippets.

**Comment by liby** [comment]
> 话虽如此，我确实添加了postcss / stylus scaffold snippets。

![demo1](https://user-images.githubusercontent.com/38807139/62959128-a654f400-be2a-11e9-8737-c7dd27507ecf.gif)
There will be prompts with with,But no stylus

**Comment by octref** [comment]
It's not released yet.

**Comment by octref** [comment]
Try 0.22.1

**Comment by liby** [comment]
> 试试0.22.1

- Thank you very much, I have already used it.
    - It’s better if you have a special document that explains these snipastes.
    - Similar to Vue 2 Snippets,This is friendly to first-time users.
    ![Snipaste_2019-08-14_09-26-43](https://user-images.githubusercontent.com/38807139/62988100-a7f7d980-be75-11e9-93b5-9663adebb6ed.png)

- Also I think some of the fragments are duplicates,Of course, these effects are not very big.
![image](https://user-images.githubusercontent.com/38807139/62988254-4126f000-be76-11e9-8e8c-a7df64bc0135.png)
![demo](https://user-images.githubusercontent.com/38807139/62988217-22285e00-be76-11e9-91a8-6a4ef6de45aa.gif)

**Comment by octref** [comment]
> Also I think some snippets are duplicates,Of course, these effects are not very big.

You can disable Vetur's builtin ones, or you can disable the other extension

I also added some docs for using the snippets.

**Comment by liby** [comment]
@octref 
- I only enabled vetur,But snippets are still duplicates
- I think only one of them shows a better one.
![image](https://user-images.githubusercontent.com/38807139/63066731-23bd5900-bf3e-11e9-85d7-e9d173c0ed8e.png)
