### ISSUE TITLE
The prompt of `type` in element ui has error

### ISSUE THREAD

**Issue by xrkffgg** [vuejs/vetur#1391]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  Win
- Vetur version: 0.22.1
- VS Code version: 1.37.0

## Problem

![](https://github.com/xrkffgg/Kimg/blob/master/vue/tab-error.png?raw=true)

- Element ui button component
- The prompt of `type` has error
- not `infor` 
- is `info`

**Comment by octref** [comment]
https://github.com/ElementUI/element-helper-json/blob/master/element-attributes.json#L219

Hey, @Leopoldthecoder @ShowJoy, I don't see much new commits to element-helper-json repo. Is it still actively maintained?

**Comment by Leopoldthecoder** [comment]
Hi @octref , sorry I have left the Element team, but I've brought this issue to their attention.

**Comment by iamkun** [comment]
fixed in 2.0.6

**Comment by octref** [comment]
Hi @iamkun, thanks for the quick fix. I have pulled in the changes.

Some other frameworks such as vuetify and quasar have started generating such JSON files as part of their build and distribute them with the packages. I'm wondering if Element team is interested in such effort? This means users always get the most up-to-date auto completion, hover information, etc in their editors when they are using Element UI.
