### ISSUE TITLE
Intellisense not working with @ absolute path in Vue CLI project

### ISSUE THREAD

**Issue by Mikilll94** [vuejs/vetur#1393]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.22.1
- VS Code version: 1.37.0

## Problem

For projects created with Vue CLI,  Intellisense in VS Code with Vetur extension is not working with absolute paths.

## Reproducible Case

Steps to Reproduce:

1. Create a new project using Vue CLI
2. Type in any javascript file or <script> section

`
import HelloWorld from '@/something/something'
`

3. After typing, '@/' Intellisense should prompt us with all available files and directories based on the path. Unfortunately, it is not working at all for absolute paths.

**Comment by octref** [comment]
Did you follow https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#vetur-cant-recognize-components-imported-using-webpacks-alias?

**Comment by Mikilll94** [comment]
The docs are wrong. It is written to create jsconfig.json (JSON extension). And below is the content of this file

`
// Webpack
module.exports = {
  resolve: {
    alias: {
      '@': 'src'
    }
  }
}
`

But this is not JSON format. It's a Javascript format.

**Comment by octref** [comment]
No, that's webpack. jsconfig/tsconfig.json are JSON:

![image](https://user-images.githubusercontent.com/4033249/63286258-7c596280-c26c-11e9-990b-15378f1b1117.png)

**Comment by Mikilll94** [comment]
@octref 
Ok. But where I have to put this webpack configuration in the project created using Vue CLI?

I put it in vue.config.js, but this is not working. I am receiving an error:
`
 ERROR  Invalid options in vue.config.js: "resolve" is not allowed
`

**Comment by octref** [comment]
vue-cli handles webpack for you. If you have vue-cli related question please open issues in their repo or StackOverflow. Vetur only cares about tsconfig/jsconfig.
