### ISSUE TITLE
Not working on Mac after updated to 0.22.2

### ISSUE THREAD

**Issue by leofachini** [vuejs/vetur#1394]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.22.2
- VS Code version: 1.37.1

## Problem

Vetur didn't highlight the code or any code intellisense work as you can see on the image below.

![image](https://user-images.githubusercontent.com/9139038/63133129-2188e800-bf9a-11e9-937e-984bc54b425b.png)

When I downgraded to previous patch version 0.22.1 everything went back to normal.

![image](https://user-images.githubusercontent.com/9139038/63133233-9fe58a00-bf9a-11e9-8759-d75128227f34.png)

## Reproducible Case

Just create a simple blank project using vue cli.

**Comment by octref** [comment]
https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#no-syntax-highlighting--no-language-features-working

**Comment by leofachini** [comment]
@octref I've already read the FAQ session and every possibility enlightened there to resolve the issue has been made. What should we do to warn that a new version come with a bug in a specific OS? 
FYI: I have the same project configured in a Ubuntu machine with the same settings as Mac OS and its working just fine on version 0.22.2. That's the reason why I have opened the issue.

**Comment by octref** [comment]
@leofachini What do you see in `~/.vscode/extensions/octref.vetur-0.21.1/syntaxes/vue-generated.json`? Also when you open VS Code -> Help -> Toggle Developer Tools -> Open a vue file, any errors there?

**Comment by jurajkocan** [comment]
i had same problem with last vscode update. version 1.37
downgreade to 1.36 working as expected.

@leofachini so as a temporary solution

**Comment by octref** [comment]
@jurajkocan If you can still reproduce this issue in 1.37 (I can't), can you send me any errors in:

> VS Code -> Help -> Toggle Developer Tools -> Open a vue file, any errors there?

**Comment by leofachini** [comment]
Hi @octref  I had just upgraded again the plugin and things went back to work properly. I had downgraded and updated the plugin on the same day I opened this issue and have no success back then.

Anyway,  here goes the [vue-generated.json](https://github.com/vuejs/vetur/files/3525980/vue-generated.json.zip)

Also there are no errors  in then console of the  VS Code Developer Tools.

Regards

**Comment by octref** [comment]
@leofachini Next time maybe you can try `reinstall`. VS Code keeps a cached copy of extensions for reinstall and this command forces re-downloading a fresh copy.

![image](https://user-images.githubusercontent.com/4033249/63448281-71303f00-c3f2-11e9-94ba-c2b3d9d87833.png)
