### ISSUE TITLE
Prettier dont work for Vue files

### ISSUE THREAD

**Issue by daviddiczhazy** [vuejs/vetur#1395]
Prettier dont work for vue files - it working before, but some days it dont work, maybe there was some update.

I have settings that prettier should format after save all files, also vue and it worked well, now it didnt work for vue files (all other files are OK).

Here my settings>

VS code: (version - 1.37.1)
{
    "cSpell.userWords": [
        "endforeach"
    ],
    "editor.matchBrackets": false,
    "emmet.showSuggestionsAsSnippets": true,
    "editor.formatOnSave": true,
    "editor.formatOnPaste": true,
    "vetur.format.options.tabSize": 4,
    "vetur.format.options.useTabs": true,
    "vetur.format.defaultFormatter.html": "none",
    "vetur.format.defaultFormatter.css": "none",
    "vetur.format.defaultFormatter.postcss": "none",
    "vetur.format.defaultFormatter.scss": "none",
    "vetur.format.defaultFormatter.less": "none",
    "vetur.format.defaultFormatter.stylus": "none",
    "vetur.format.defaultFormatter.js": "none",
    "vetur.format.defaultFormatter.ts": "none",
    "npm-intellisense.scanDevDependencies": false,
    "window.zoomLevel": 0,
    "prettier.disableLanguages": []
}

package.json>
{
  "name": "spaapp",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "axios": "^0.19.0",
    "core-js": "^2.6.5",
    "vue": "^2.6.10",
    "vue-router": "^3.0.3"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.10.0",
    "@vue/cli-plugin-eslint": "^3.10.0",
    "@vue/cli-service": "^3.10.0",
    "@vue/eslint-config-prettier": "^5.0.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.16.0",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-vue": "^5.0.0",
    "prettier": "^1.18.2",
    "sass": "^1.18.0",
    "sass-loader": "^7.1.0",
    "vue-template-compiler": "^2.6.10"
  }
}

.elintrc.js:
module.exports = {
	root: true,
	env: {
		node: true
	},
	extends: [
		'plugin:vue/essential',
		'plugin:prettier/recommended',
		'@vue/prettier'
	],
	rules: {
		'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
		'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off'
	},
	parserOptions: {
		parser: 'babel-eslint'
	}
}

.prettierrc:
{
	"tabWidth": 4,
	"semi": false,
	"singleQuote": true,
	"useTabs": true,
	"jsxBracketSameLine": true
}

**I want to have unified formating - that pretier will format all files, also .vue after save. Could you please help me?**

Thank you

**Comment by JW-LIAO** [comment]
me too, I also need for help, please.

**Comment by octref** [comment]
You should set `"vetur.format.enable": false` if you plan to use prettier fully. And you should open issue against https://github.com/prettier/prettier-vscode.

**Comment by StarkBrothers** [comment]
You should first forbidden vetur, and  then start it, maybe their order crash.
