### ISSUE TITLE
Do you support TypeScript Const assertions?

### ISSUE THREAD

**Issue by mya-ake** [vuejs/vetur#1397]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS Mojave 10.14.6
- Vetur version: 0.22.2
- VS Code version: 1.37.0

## Problem

I get the error "Cannot find name 'const'."
And, the type will be any without recognizing `as const`.

<img width="1432" alt="スクリーンショット 2019-08-18 11 44 14" src="https://user-images.githubusercontent.com/16383815/63219476-aa2ba200-c1ad-11e9-8537-f95f67f076e4.png">

## Reproducible Case

This is a project created with Vue CLI@3.10.0. 
There is a code that wrote const assertion in`/src/components/HelloWorld.vue`.

https://github.com/mya-ake/reproduction-vetur-const-assertion

**Comment by ktsn** [comment]
You probably don't set `Vetur: Use workspace dependencies` config and use old TypeScript version which does not support `const` type in SFC. Please try to configure it.

**Comment by mya-ake** [comment]
It was solved. Thank you very much!
