### ISSUE TITLE
vue formating cause my code wrong

### ISSUE THREAD

**Issue by 1057891494** [vuejs/vetur#1398]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version:0.22.0
- VS Code version:1.37.0

## Reproducible Case

I have this code in the vue template:
<template>
   <input v-input-check='[params.qrptfg,"select"]' @blur="toLogin('NO')" />
</template>
When I use formatting, the code becomes
<template>
   <input v-input-check=“[params.qrptfg,"select"]” @blur="toLogin('NO')" />
</template>
This caused my code to go wrong, I don't want to change my single quotes and double quotes when formatting, but I didn't find such a setting.

**Comment by octref** [comment]
I guess you are using prettyhtml the default HTML formatter. It'll inherit prettier config. Does this work for you?

```
"vetur.format.defaultFormatterOptions": {
  "prettier": {
    // Prettier option here
    "singleQuote": true
  }
}

**Comment by 1057891494** [comment]
I have tried this, which will cause the code to become like this:
<template>
   <input v-input-check='[TLECOD,"required"]' @click='toLogin('on')' />
</template>
Single quotes contain single quotes and the browser does not parse it correctly.
Can you provide a third option so that single and double quotes can not be changed?

**Comment by octref** [comment]
@StarpTech Wondering what's your thoughts on this.

**Comment by BrayanIribe** [comment]
Hello guys, I know this may not be here, but I want to post a solution for vetur formatter that I didn't can get it work all the day...

I needed singleQuotes in the HTML tags but it didn't was working, even with .prettierrc. So I ended with a config like this:

```
"vetur.format.defaultFormatter.css": "prettier",
  "vetur.format.defaultFormatter.html": "prettyhtml",
  "vetur.format.defaultFormatter.js": "prettier",
  "vetur.format.defaultFormatterOptions": {
    "prettier": {
      // Prettier option here
      "singleQuote": true
    },
    "prettyhtml": {
      "singleQuote": true
    }
  }
```

The **prettyhtml** part did the trick. I know this cannot be here, but I hope someone find this post useful!

**Comment by StarpTech** [comment]
@1057891494 please open a bug on the prettyhtml repository. @octref there are some open issues but at the moment I have no time to work on it. Feel free to send me a PR :smile:

**Comment by octref** [comment]
OK, @1057891494 please open an upstream issue. Thanks!
