### ISSUE TITLE
Debugging *.vue files puts breakpoints in wrong place

### ISSUE THREAD

**Issue by IzakMarais** [vuejs/vetur#1399]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.22.2
- VS Code version: 1.37.1
- npm version: 6.9.0

## Problem
Debugging in VSCode using Vetur does not set breakpoints at the correct location in *.vue files. When trying to set a breakpoint in a script segment of a *.vue file, the breakpoint is set at a different location in the same file.

In other files using the same settings, e.g. *.ts files, the debugging works correctly.

## Reproducible Case

-   Clone https://github.com/IzakMarais/reproduce-vuejs-debug-problem
-  From VSCode:
    -   install "Debugger for Chrome" extension
-   From the command line:
    -   npm install
    -   npm start
-   From VSCode:
    -   set a breakpoint in _App.vue_ at line 19
    -   set a breakpoint in _GraphConsumer.ts_ at line 11
    -   start debugging using "vuejs: chrome" debug config
    -   Note the the breakpoint inside _App.vue_ **moves** from line 19 to line 39 and is hit.
-   Open the Sources tab in Chrome dev tools, and note the breakpoint is at _webpack://./App.vue::39_. This file    does not resemble the _App.vue_ source file. It has comment headings _normalise component_ and _hot reload_. One of the other files,    _webpack://./App.vue?5361_, does match the source code, but the breakpoint is not set here.
-   Back in VSCode:
    -   _Continue_ past the first breakpoint
    -   Note the correct position of the second breakpoint in _GraphConsumer.ts_

**Comment by octref** [comment]
Not sure if you have taken a look at https://github.com/vuejs/vue-loader/issues/620 and https://github.com/Microsoft/vscode-recipes/tree/master/vuejs-cli yet, but AFAIK only certain webpack configs produce correct sourcemap for vue files. "puts breakpoints in wrong place" usually means bad sourcemap.

**Comment by IzakMarais** [comment]
Thanks for the quick feedback. 

> only certain webpack configs produce correct sourcemap for vue files

You have identified the problem. When I follow the vscode-recipe exactly, debugging works correctly. 

Our team is pretty new to JS, so we had tried to remove the perceived layer of abstraction of vue-cli and write our webpack configuration directly. 

However, based on the debugging problems highlighted in this issue, as well as [this suggested vue enterprise boilerplate (which also uses vue-cli) I think we will be switching back to vue-cli for webpack configuration management.

**Comment by gambolputty** [comment]
Had the same problem and solved it by removing `./` in front of `src` inside:
```
      "sourceMapPathOverrides": {
        // "webpack:///./src/*": "${webRoot}/*", <--- old, as described in the vscode-recipe
        "webpack:///src/*": "${webRoot}/*",
      }
```

**Comment by gangstar902** [comment]
> Had the same problem and solved it by removing `./` in front of `src` inside:
> 
> ```
>       "sourceMapPathOverrides": {
>         // "webpack:///./src/*": "${webRoot}/*", <--- old, as described in the vscode-recipe
>         "webpack:///src/*": "${webRoot}/*",
>       }
> ```
It does help, but also make some breaking point unavailable.

**Comment by gangstar902** [comment]
like this ![image](https://user-images.githubusercontent.com/11476249/70729288-e1662600-1d3d-11ea-8cdf-997eb43247e6.png)

**Comment by michaelsogos** [comment]
Dear @delicacyyy 

I have same issue, do you have a workaround?

**Comment by delicacyyy** [comment]
> Dear @delicacyyy
> 
> I have same issue, do you have a workaround?

not yet

**Comment by urielvan** [comment]
@delicacyyy @michaelsogos 

I keep both lines in the launch.json

```
"sourceMapPathOverrides": {
  "webpack:///./src/*": "${webRoot}/*",
   "webpack:///src/*": "${webRoot}/*",
}
```

And breakpoints in either .vue or .js works fine
