### ISSUE TITLE
Default Formater behavior conflicts with eslint-plugin-vue with strongly-recommended

### ISSUE THREAD

**Issue by GodofHope** [vuejs/vetur#1405]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.22.2
- VS Code version: 1.37.1

## Reproducible Case

Vetur contains `prettyhtml` as it's default html fixer. But , when I use `eslint-plugin-vue` against [plugin:vue/strongly-recommended](https://vuejs.github.io/eslint-plugin-vue/rules/#priority-b-strongly-recommended-improving-readability), it turns on the rule [singleline-html-element-content-newline](https://vuejs.github.io/eslint-plugin-vue/rules/singleline-html-element-content-newline.html), which is conflicted with prettyhtml formatting method.

I wonder if there is a way to solve this confilct. 
P.S.: I opened [Prettyhtml#115](https://github.com/Prettyhtml/prettyhtml/issues/115) already.

**Comment by octref** [comment]
I don't think there's a way I can solve it. You can also choose other formatters. If `eslint-plugin-vue` provides auto fixes, maybe we can use `prettier-eslint` to autofix the incompatibilities. (But that would be a new feature request -> new issue).
