### ISSUE TITLE
Vetur settings in vscode settings.json doen't respect .prettierrc. How can I fix it?

### ISSUE THREAD

**Issue by testgit-1** [vuejs/vetur#1407]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win 10
- Vetur version: 0.22.2
- VS Code version: 1.37.1

## Problem
If vetur format config is set in settings.json the setting in .prettierrc doesn't work.

![GIF](https://user-images.githubusercontent.com/22541150/63752014-19de1300-c8b9-11e9-96c8-ef3eba105fa9.gif)

## Reproducible Case
1. Set in project root file .prettierrc
```
{
    "tabWidth": 2,
    "useTabs": false,
    "singleQuote": true
}
```
2. Use formatting. It will use settings from .prettierrc
3. Set in settings.json
```
    "vetur.format.options.tabSize": 4,
    "vetur.format.options.useTabs": true,
```
4. Use formatting. It will use settings from setting.json.
But due to documentation it should "However, when a local config (such as .prettierrc) is found, Vetur will prefer it." ( https://vuejs.github.io/vetur/formatting.html#settings )

**Comment by octref** [comment]
I changed it to the exact setting you have, and it''s working fine for me: https://github.com/octref/veturpack/commit/a536a1cd621b3731ae330e8803dcf6b536586de5

Maybe you are using Prettier instead of Vetur's Formatter? You can check in the command "Format Document with...":

![image](https://user-images.githubusercontent.com/4033249/64369116-80a5af80-cfd0-11e9-8d34-bb97dd0c3111.png)

**Comment by Timmmm** [comment]
I don't have a `Format Document with` command (I assume because it only found one formatter), and I'm having a similar problem. Vetur seems to ignore `.prettierrc.js`. Is there any way to make it print the command it is running?

**Comment by octref** [comment]
In the next version you can set `"vetur.dev.logLevel": "DEBUG"` and Vetur will print prettier config that it loads:

![image](https://user-images.githubusercontent.com/4033249/74271158-451aba00-4cc1-11ea-84e4-410e0aa101c9.png)

Please include a reproducible case and open a new issue, if this still doesn't work.
