### ISSUE TITLE
[Feature Request] New html/style formatters, alternative formatter option to exec shell/npm script

### ISSUE THREAD

**Issue by zfeher** [vuejs/vetur#1408]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Feature request
First of all thank you for this great extension and pleas keep up workin on it.

Recently we are started to convert all our components to vue files where this extension came into play (at least for the VS Code users :)). After playing with the settings a little bit we found that we can't use the formatting part of Vetur as of now. We are using prettier-eslint + stylelint on commit hook so we tried to replicate the same behavior in Vetur with no success. Unfortunatelly Vetur has no `prettier-eslint` option for the `html/template` part where  prettier would pre format the template and than eslint (with eslint-plugin-vue) would fix additional problems.
The second problem we had was with the styles where we need to apply the same mechanism: run prettier than run stylelint fix to apply additional problem fixes. 

These problems can be solved via introducing `prettier-eslint` as a html formatter and `prettier-stylelint` as a style (scss/css/less/...) formatter. Would be nice to have these at hand.

Another alternative could be adding a new formatter option which could simply replace/override all other formatter options. An option which could execute a shell command or an npm script. This way we could reuse our existing scripts either from package.json or somewhere else. This feels like the most generic solution for all the exotic cases where the current configuration is not sufficient.

What do you think any of these reasonable and achieveable?

**Comment by octref** [comment]
> prettier-stylelint

#712

> prettier-eslint for template

I just opened #1416

> An option which could execute a shell command or an npm script.

It'd be hard to translate all options to CLI arguments.

**Comment by zfeher** [comment]
It seems it is more like an ESLint plugin bug. I've checked in the `veturpack` repo as well via opening the `Counter.vue` component and executing the `ESLint: Fix all auto-fixable Problems` command it only partly formats on each save. Running `eslint --fix` from the command line fixes/formats on the first run.
