### ISSUE TITLE
Wrong method reference not detected

### ISSUE THREAD

**Issue by babak-f** [vuejs/vetur#1412]
## Info

- Platform: Windows
- Vetur version: 0.22.2
- VS Code version: 1.37.1

## Problem

The IDE does not warn (or show error) about use of a non-existing method the template. 

For example, in the code snippet below, `onButtonClick2` doesn't exist in the class, but the editor doesn't detect it. 

## Reproducible Case

```vue
<template>
  <div>
    <p>Click below</p>
    <button @click="onButtonClick2">Click</button>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component
export default class HelloWorld extends Vue {
  onButtonClick(): void {
    alert('test');
  }
}
</script>
```

**Comment by ktsn** [comment]
Did you enable experimental template interpolation flag?
https://vuejs.github.io/vetur/interpolation.html

**Comment by babak-f** [comment]
Nope I hadn't. 

Now it works, thanks.
