### ISSUE TITLE
weex image component ,Formatting failed:Void elements do not have end tags "image"

### ISSUE THREAD

**Issue by MILIFIRE** [vuejs/vetur#1413]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.22.2
- VS Code version: 1.37.1

## Problem

weex image component ,Formatting failed:Void elements do not have end tags "image"
## Reproducible Case
![image](https://user-images.githubusercontent.com/13724148/64234243-78923500-cf28-11e9-8656-be5c44fa8145.png)

weex image component has end tags "image", but vetur  think is error

**Comment by octref** [comment]
Repros on https://prettyhtml.netlify.com/, so please report to https://github.com/Prettyhtml/prettyhtml.

**Comment by hi-yuwei** [comment]
Did you solve the problem? I did too
