### ISSUE TITLE
Request initialize failed with message: Cannot read property 'suggest' of undefined

### ISSUE THREAD

**Issue by FarseerD** [vuejs/vetur#1429]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Update

Fix it by removing setting folder (Mac: $HOME/Library/Application Support/Code/User/).

## Info

- Platform: macOS
- Vetur version: 0.22.2
- VS Code version: 1.38.1

## Problem

An error message "Request initialize failed with message: Cannot read property 'suggest' of undefined" occurs after launching VSCode.

Formatting function and Emmet are unavailable.

## Reproducible Case

1. Open a vue file.
2. Relaunch VSCode.
3. The error message above occurs.

**Comment by sherleenStar** [comment]
I have the same question, hope as soon as quick solved!

**Comment by sunyill** [comment]
你可以把setting的配置从源目录删除,然后重新生成一下setting,就OK

**Comment by chairuan** [comment]
+1

**Comment by chairuan** [comment]
额，删掉C:\Users\chairuan\AppData\Roaming\Code 文件夹 好了

**Comment by FarseerD** [comment]
> 你可以把setting的配置从源目录删除,然后重新生成一下setting,就OK

OK there, but why...

**Comment by instantcrush** [comment]
我也遇到了同样的问题，上面提到的删除文件夹的办法只是关掉了错误提示，vetur仍旧不能用，多次卸载安装后我发现是因为安装的vscode版本是user版，只要安装vscode管理员版就不会发生任何问题。
