### ISSUE TITLE
Validation of script references in vue html/template stopped working

### ISSUE THREAD

**Issue by alexeigs** [vuejs/vetur#1437]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

What I'm using

- VSCode
- Quasar (Vue)
- Typescript
- Eslint/@typescript-eslint
- Vetur / Prettier / prettierhtml

Until recently, injected script in the of vue files (e.g. onSignIn in `<div @click="onSignIn">` was checked against available variables/methods in the `<script lang="ts">` part. This has now stopped working and I couldn't figure out what's the reason. Playing around with VSCode/Vetur/eslint settings wasn't successful either so far.

As the above hasn't worked earlier either but just since I started my latest project, I'm not sure what settings is responsible for that part anyway (Veturs' HTML > Validate > Scripts apparently is not enough).

This may not be a bug but an issue many others I know struggle with too without seeing through all the available settings/plugins and their effect on the actual outcome.

**Comment by jackkoppa** [comment]
Hi, there was at one point where the feature that you're describing was turned on by default.

Now, while it's still experimental, you have to enable it manually.

Add this to your workspace VS Code settings:
```json
vetur.experimental.templateInterpolationService: true
```

**Comment by jackkoppa** [comment]
Hi @alexeigs - if the above resolves your problem, feel free to mark the issue as closed. Glad it seems to have been the solution!

**Comment by alexeigs** [comment]
Works as expected, thanks!
