### ISSUE TITLE
how can i use optionalChaining?

### ISSUE THREAD

**Issue by wenfangcao** [vuejs/vetur#1438]
let b = a?.b?.c?.s

**Comment by jackkoppa** [comment]
For JavaScript: [the Babel plugin](https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining)

For TypeScript: Soon! November 5th!

[The issue](https://github.com/microsoft/TypeScript/issues/16#issue-37906351)
[TS 3.7](https://github.com/microsoft/TypeScript/issues/33352), target release of 11/5/19

Also, this can probably be closed as an issue not particularly specific to Vetur

**Comment by wenfangcao** [comment]
I've used the Babel plugin, but the vscode shows the Expression expected.Vetur(1109). How to configure vetur ?

**Comment by oliyg** [comment]
TS 3.7, target release of 11/5/19

Vetur is based on vue-language-server. the vue-language-server is current loading bundled typescript@3.6.3.

so you have to wait for the vue-language-server to upgrade this version to 3.7

**Comment by octref** [comment]
As answered by others, you'll need to wait TS 3.7. After which you can install locally to your workspace and use `vetur.useWorkspaceDependencies` to use it.

**Comment by abercrave** [comment]
https://devblogs.microsoft.com/typescript/announcing-typescript-3-7/ 🙂

**Comment by GoldSubmarine** [comment]
It's time.

**Comment by jrt324** [comment]
@octref  Please reopen this issue ,  

> As answered by others, you'll need to wait TS 3.7. After which you can install locally to your workspace and use `vetur.useWorkspaceDependencies` to use it.

This answer not working !

**Comment by BrianHorvat** [comment]
Workaround until Vetur is updated to use TS 3.7:

1. Clone the Vetur repo

Clone the Vetur repo, go to the server directory, install dependencies, update TypeScript to 3.7,

**Comment by BrianHorvat** [comment]
Workaround until Vetur is updated:

1. Clone Vetur
2. Navigate to the "server" directory
3. Install dependencies and update TypeScript to 3.7
4. In VS Code, set "vetur.dev.vlsPath" to the absolute path of the "server" directory
5. Restart VS Code

This got optional chaining and nullish coalescing working for me.

**Comment by octref** [comment]
TS 3.7 might break other functionalities of Vetur, so I can't just upgrade.
You can now use `vetur.useWorkspaceDependencies` with locally installed TS. The point of that setting is you don't have to wait for Vetur to update its TS dependencies for using a newer version.

**Comment by jackkoppa** [comment]
Yup, can confirm that `useWorkspaceDependencies` is working great for us for optional chaining, having TS 3.7 installed for the repo :+1: Love it!

**Comment by Flexicon** [comment]
Is it intended not to work within template tags? Or does typescript only work within script tags?

**Comment by Niekvdm** [comment]
Using TypeScript 3.7 breaks intellisense for me.

**Comment by jcperez-ch** [comment]
Should we reopen? Seems like vetur is not compatible with TS 3.7 fully

**Comment by kbirger** [comment]
> 
> 
> Using TypeScript 3.7 breaks intellisense for me.

What exactly is broken for you?

**Comment by ERENKYI** [comment]
Not using TypeScript but Intellisense is broken to me as well.
![Code_affuFhouZ7](https://user-images.githubusercontent.com/29287377/70827660-c4435d00-1dfa-11ea-8e59-d031723a9d7f.png)

**Comment by kbirger** [comment]
Well, if you're not using TypeScript, then it's a separate issue, I think. useWorkspaceDependencies just allows you to use the TS that is in your package.json rather than the bundled one

**Comment by P4sca1** [comment]
Is there any reason why `vetur.useWorkspaceDependencies` cannot be set in the workspace but only in the user settings?

**Comment by labzy88** [comment]
**For those that have multiple projects in their VS workspace.**

This seems to be the problem for me, I hope that points some of you in the right direction.

I have found two solutions for now:
1. init a package.json in the root workspace folder and install typescript there. Creating a node_modules folder here just to workaround this Vetur warning makes me feel physically sick so I have to resort to...
2. Open the the project folder as a visual studio workspace. This works fine, although not exactly how I want to work.

I'm hoping someone knows how to fix this and can help me?

Ideally I want a way to get Vetur to detect the deepest dependencies and then work from there. I assume this is how Visual Studio itself works, maybe there is a way I can get Vetur to do the same?

**Comment by borie88** [comment]
What is required to get this working within template tags? Is that an issue with eslint-plugin-vue which is used to validate templates?
