### ISSUE TITLE
vue

### ISSUE THREAD

**Issue by mmd123123** [vuejs/vetur#1441]
Issue Type: <b>Feature Request</b>

没有代码提示

Extension version: 0.22.3
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

**Comment by octref** [comment]
Your issue is closed because you did not provide a repro case. Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.
