### ISSUE TITLE
As long as the 'length' attribute is included in the html tag, vetur will clear all attribute.

### ISSUE THREAD

**Issue by CaiLifeng** [vuejs/vetur#1443]
## Info

- Platform: macOS
- Vetur version:0.22.3
- VS Code version:1.38.1

## Problem

1 . vscode format type set to vue
![image](https://user-images.githubusercontent.com/7630913/65868884-caa16b80-e3ab-11e9-9016-dc243ec12502.png)

2. code:
`    <sms-input
      length="8"
    />
    <input maxlength="333" length="555"/>
`

3. Choose "Format Document"

4. Problem
As long as the **length** attribute is included in the html tag, vetur will clear all attribute.
![image](https://user-images.githubusercontent.com/7630913/65869324-cde92700-e3ac-11e9-8db6-770a75f15f55.png)

**Comment by octref** [comment]
You can configure `"vetur.format.defaultFormatter.html": "prettier"` or report an upstream issue to https://github.com/Prettyhtml/prettyhtml.
