### ISSUE TITLE
How to separate Vue SFC to separate files?

### ISSUE THREAD

**Issue by predragnikolic** [vuejs/vetur#1444]
- [x] I have searched through existing issues, 
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: I don't use vetur directly. I use "vue-language-server": "0.0.61"

## Problem
Hello, 
thanks for this amazing language server :)

I was looking for a way to separate Vue SFC to separate files and still get vetur(vls) auto-completion in `.js` files?

For example, if I have `App.vue`:
```
<template>
    ...
</template>
<script>
export default {
    ...
}
</script>
<style>
    ...
</style>
```

And I want to separate it, so `App.vue` would look like this: 
```
<template>
    ...
</template>
<script src="./App.js"></script>
<style src="./App.css"></style>
```

`App.js` would look like this:
```
export default {
    data() {
        return {someData: 1}
    }
}
```

But if I separate my files like this, 
I will lose all vetur functionality in `App.js`. (references, goto definition, auto-completion,...),
nor will I get `someData` completion item in `App.vue` template, 
as I would if I used a SFC vue file.

### Note
But, I found a way around this and just wanted to check if it is ok to do it in this way.

I wrote `App.vue` to look like this: 
```
<template>
    ...
</template>
<script src="./App.script.vue"></script> // note: imported a vue file instead of js
<style src="./App.css"></style>
```

`App.script.vue`:
```
<script>
export default {
    data() {
        return {someData: 1}
    }
}
</script>
```
Because I am importing a `vue` file I will get all vetur functionality :D, almost... 
While I still won't get `someData` completion item in autocompletion in `App.vue` template.
I will get diagnostics, hover information, goto definition and references work also...

![output1](https://user-images.githubusercontent.com/22029477/65921046-584b7e00-e3e1-11e9-97bd-fd21b14a6214.gif)

Is anyone writing components in this way? Is it ok? :)
```
<template></template>
<script src="./App.script.vue"></script>
<style src="./App.css"></style>
```

**Comment by octref** [comment]
This is currently impossible, because JS files are handled by TypeScript Language Server that Vue Language Server cannot interfere, and therefore VLS cannot wrap the object literal in `Vue.extend` calls.
