### ISSUE TITLE
Formating with Prettier: Honor `prettier.requireConfig` (or add equivalent option)

### ISSUE THREAD

**Issue by loilo** [vuejs/vetur#1445]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.22.3
- VS Code version: 1.38.1

## Problem

With my VS Code setup, there's a pretty common problem I regularly run into:

I use the [official Prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) for formatting code with Prettier, but I have enabled its `prettier.requireConfig` option which only runs the Prettier formatter if a `.prettierrc` file is present.

This leads to a pretty annoying inconsistency, because if no `.prettierrc` exists, my JS/CSS/... code stays untouched while Vue code still gets formatted.

I'm aware that Vetur ships with its own instance of the Prettier library and does not generally interact with the Prettier extension, but it would be great if the `prettier.requireConfig` option would be honored by Vetur. Of course this would create a soft dependency on the Prettier extension, but since it's the official extension and the behavior would be a no-op without that extension installed, it should be fine IMO.

Alternatively, there could be an equivalent Vetur option which does the same.

What do you think?

## Reproducible Case

0. Enable "Format on Save" in VS Code
1. Install Vetur and the [Prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)
2. Set the Prettier extension's `prettier.requrieConfig` option to `true`.
3. Create a new project and in it a JS and a Vue file.
4. Fill them with the bare minimum of formattable code (`console.log()` respectively `<script>console.log()</script>` should be sufficient).
5. Save both files.
6. Observation: The JS file will not be formatted while the JS section of the Vue file will.

**Comment by octref** [comment]
Vetur doesn't read any setting from prettier.* scope to avoid confusion (https://vuejs.github.io/vetur/formatting.html). It used to be very confusing whether Vetur is reading config from prettier.* or config files.
If you don't want to format script sections, try having a workspace setting that sets `vetur.format.defaultFormatter.js` to `none`.

**Comment by loilo** [comment]
Alright. Not optimal, but plausible. Thanks for taking care!
