### ISSUE TITLE
Relative import causes Vetur to be confused about filename case

### ISSUE THREAD

**Issue by zmbq** [vuejs/vetur#1447]
## Info

- Platform: Windows
- Vetur version: 0.22.4
- VS Code version: 1.38.1

## Problem

Sometimes when I use relative imports, for instance `import ArtefactCard from './artefact-card.vue';`, Vetur complains about filename casing:

File name 'd:/Chelem/Qumran/ScrollEditor/src/views/edition/components/artefact-card.vue' differs from already included file name 'd:/chelem/Qumran/ScrollEditor/src/views/edition/components/artefact-card.vue' only in casing.,

Note the difference is between d:/chelem and d:/Chelem. The project root is at d:/Chelem/Qumran/ScrollEditor, and is never specified in the code, so this is a problem with the extension - not the source.

This never happens with absolute imports, just with relative ones.

## Reproducible Case
This happens sometimes, in different projects, always with relative imports. I couldn't find a reliable way of reproducing this.

## Suggestion
When checking for filename casing, only check the part that actually appears in the code, not the part that's added.

**Comment by clouds56** [comment]
Same here, if it could not be fixed right now, is there some workaround? (like disable vetur in some folder but I don't know how)

**Comment by gambolputty** [comment]
Having the same issue on macOS Catalina:

`
File name '/Users/gregor/Git/talkative-browser/src/components/Editor/Keymap.js' differs from already included file name '/users/gregor/Git/talkative-browser/src/components/Editor/Keymap.js' only in casing.Vetur(1149)
`

The difference lies in the *Users*-folder at the start: `/Users` vs. `/users`

This https://github.com/Microsoft/TypeScript/issues/25460#issuecomment-526273944 helped:
> So I simply closed the folder is was working in in Visual Studio Code and re-opened it. After everything loaded up, no errors and I didn't have to mess with the tsconfig.json file.

**Comment by octref** [comment]
Thanks @gambolputty. Seems to be an upstream issue w/ TypeScript. If reopening VS Code doesn't fix the issue feel free to reopen.

**Comment by wumaorg** [comment]
I had the same problem on my Mac

**Comment by wunderdaz** [comment]
Any news on this? Quite an annoying IDE bug, especially since compiling the code works correctly.
