### ISSUE TITLE
Extract props / data / methods info from Component to power template IntelliSense

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#145]
- Provide suggestion based on Component attributes for `v-if`, etc
- Provide `v-on` like `@click`, `@click.stop`
- Support built-in components such as `<component>`, `<transition>`, etc

**Comment by M6stafa** [comment]
is this feature work with imported script with `src` attributed in `vue` files?

**Comment by eladcandroid** [comment]
Any news?

**Comment by octref** [comment]
This is already done via #1083 and available in 0.16.0.
