### ISSUE TITLE
Cannot work with flow

### ISSUE THREAD

**Issue by catsigma** [vuejs/vetur#1452]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows 10 remote to Ubuntu 18.04
- Vetur version: 0.22.4
- VS Code version: 1.38.1

## Problem

Whether I disabled `vetur.validation.script` or not, the official plugin of flow `Flow Language Support` cannot be activated for the `script` part.

## Reproducible Case

Create a vue file:
```vue
<template>
  <div>
  </div>
</template>

<script>
// @flow

abc   // should show the error

export default {
  data() {
    return {}
  }  
}
</script>
```
No matter what settings you are using, it just won't activate the flow plugin to display the error (which works fine for .js file in the same project)

**Comment by sploders101** [comment]
This may be for the same reason as #1449. Could you try his case in either downgrading or opening a file, or closing & reopening vscode, and checking it again? That issue may be worth following as well, since typescript is used much more widely than flow lately and is probably the same root issue

**Comment by sploders101** [comment]
Looks like we got a PR #1450, which should fix this as well. Just waiting on merge.

**Comment by octref** [comment]
Vetur uses TypeScript language server, and there's no flow support there.
