### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by rodrigoraraujo** [vuejs/vetur#1453]
- Issue Type: `Bug`
- Extension Name: `vetur`
- Extension Version: `0.22.4`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.38.1`

Server returned 422
node.children is not iterable

**Comment by sploders101** [comment]
Unfortunately, I'm not familiar with developing vscode extensions, but for the sake of the project maintainers, could you elaborate on a few things? It's likely to get your issue addressed quicker.

What exactly is the issue?
Does the extension install?
Does it run/partially work? If so, which part (specifically) doesn't?
Where is the error message coming from (output->vetur, notification, etc.)?
Can you post instructions on how to replicate the issue?
Screenshots may help as well.

It may also help to make your title a bit more descriptive as well.

**Comment by octref** [comment]
Your issue is closed because you did not provide a repro case. Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.
