### ISSUE TITLE
intellisense isn't working as expected with @typedef and @type 

### ISSUE THREAD

**Issue by RyanHavoc** [vuejs/vetur#1454]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 1.38.1
- VS Code version: 0.22.4

## Problem

I'm trying to use `@typedef` and `@type` in my components but Intellisense always shows the prop as `any`:

![image](https://user-images.githubusercontent.com/824169/66563436-adac2b80-eb55-11e9-9120-a89c3ec7db1c.png)

## Reproducible Case

Beyond checking with a colleague if he sees the same behaviour, which he does, I'm not sure how to reproduce this.

**Comment by ktsn** [comment]
We need to annotate `type` option with `PropType` utility type from `vue`´s typing as props are handled by different way from other options.

```vue
<script>
/**
 * @typedef {object} Foo
 * @property {string} bar
 */
export default {
  props: {
    foo: {
      /**
       * @type {import('vue').PropType<Foo>}
       */
      type: Object,
      required: true
    }
  },

  mounted() {
    this.f
  }
}
</script>
```

![image](https://user-images.githubusercontent.com/2194624/66694057-bb46ea00-ecea-11e9-9329-3fa0e8d8761c.png)

**Comment by ktsn** [comment]
We can improve documentation with it I guess.

**Comment by RyanHavoc** [comment]
@ktsn Is there not a cleaner way to do this? I was reading this article which is what confused me as to why it wasn't working: https://blog.usejournal.com/type-vue-without-typescript-b2b49210f0b

This was back from 2018 and seemed to work for him. We do we need `import('vue').PropType<>` now?

**Comment by ktsn** [comment]
@RyanHavoc The article does the exact same thing with my example. `PropType<T>` is a type alias of `{ new (): T }`. You can write it directly if you want. 

The reason that your example does not work is that 1) you are annotating props option object instead of type field and 2) annotate with direct type (`Path`) instead of a constructor of type (`{ new (): Path }`)

**Comment by RyanHavoc** [comment]
@ktsn Ah, there was another reason why this wasn't working for me, we use a "custom" `status` property in our components to keep track of component state, `ready`, `alpha`, `deprecated` etc.

```
<script>
import VulnerablePath from '~/components/elements/VulnerablePath';

/**
 * @typedef {object} Path
 * @property {string} source
 */
export default {
  name: 'VulnerablePaths',
  //status: 'ready',
  components: {
    VulnerablePath,
  },
  props: {
     paths: {
      /**
       * @type {import('vue').PropType<Path[]>}
       */
      type: Object,
      required: true
    }
  },
  mounted() {
    this.paths[0].source;
  },
};
</script>
```

If I comment it out, the intellisense works. If I uncomment it it doesn't.

Can I add this to Vetur somehow so that it doesn't affect the intellisense?

**Comment by ktsn** [comment]
Since Vetur uses TypeScript feature to provide intellisense, we need to declare the extra option type in that case.

```ts
// augment.d.ts
import Vue from 'vue'

declare module 'vue/types/options' {
  interface ComponentOptions<V extends Vue> {
    status?: string
  }
}
```

https://vuejs.org/v2/guide/typescript.html#Augmenting-Types-for-Use-with-Plugins
