### ISSUE TITLE
TypeScript errors not showing after upgrading VSCode to v1.39

### ISSUE THREAD

**Issue by Ky6uk** [vuejs/vetur#1456]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: **macOS 10.15**
- Vetur version: **0.22.4**
- VS Code version: **1.39.1**
- TypeScript version: **3.6.4**

Vue file: TS + SCSS (modules)

## Problem

After a few minutes, VSCode stops displaying errors and hover tooltips for TS part of `.vue` component files. Output logs for vue language server are empty. Window reloading helps but only for 5-10 minutes.

I think it started to happen after upgrading VSCode to `v1.39`. For plain `.ts` files it still works.

**Comment by sixpounder** [comment]
I can confirm the issue under the system specs listed by @Ky6uk. Also happening on Linux.

**Comment by sixpounder** [comment]
Update: VSCode 1.39.1 actually removed the issue 🥳

**Comment by Ky6uk** [comment]
@sixpounder just upgraded today. The issue still exists.

**Comment by NicoAiko** [comment]
> @sixpounder just upgraded today. The issue still exists.

Can confirm.

![Bildschirmfoto 2019-10-11 um 12 03 28](https://user-images.githubusercontent.com/22343587/66643552-3f33a000-ec1f-11e9-9f65-a93feb971564.png)
![Bildschirmfoto 2019-10-11 um 12 03 54](https://user-images.githubusercontent.com/22343587/66643553-3f33a000-ec1f-11e9-934f-3b2355a8cca6.png)

**Comment by sixpounder** [comment]
@NicoAiko @Ky6uk in my case it seems to be working in general, but I get the same behaviour as in 1.39 occasionally. I am not sure about the conditions to reproduce the issue.

**Comment by Ky6uk** [comment]
Possible related to #1449

**Comment by Ky6uk** [comment]
Downgrading to Vetur `v0.22.3` resolves the problem.

<img width="534" alt="Screen Shot 2019-10-11 at 14 21 23" src="https://user-images.githubusercontent.com/46930/66647828-9a22c280-ec32-11e9-8894-baed770a3126.png">

**Comment by ffxsam** [comment]
Just noticed this today. Type awareness has stopped working, and mousing over variables does nothing when it should pop up type info.

**Comment by ktsn** [comment]
Thank you for filing this issue. Let's track it on #1449.
