### ISSUE TITLE
How to stop wrapping things

### ISSUE THREAD

**Issue by hunterInt** [vuejs/vetur#1460]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux 19
- Vetur version: 0.22.4
- VS Code version: 1.39.1

## Problem

I love using Vetur, except I don't know how to disable this weird wrapping. 
This is what I want:
![Screenshot from 2019-10-13 19-25-02](https://user-images.githubusercontent.com/14793417/66719423-c5064580-edef-11e9-934d-c705cc187a53.png)
This is what it does:
![Screenshot from 2019-10-13 19-25-15](https://user-images.githubusercontent.com/14793417/66719424-c59edc00-edef-11e9-88f2-80c4aa8e331d.png)

How can I disabled this? Or better yet, make Vetur auto-fix these back the the first screenshot.

It also does this with the HTML, but only wraps some attributes sometimes:
![Screenshot from 2019-10-13 19-32-20](https://user-images.githubusercontent.com/14793417/66719452-3e059d00-edf0-11e9-9ab2-07a75c1eb145.png)

## Reproducible Case

Open a .vue file and format it.

**Comment by ktsn** [comment]
As docs says, you can disable formatting by setting `vetur.format.enable` for global, `vetur.format.defaultFormatter` for specific language.

https://vuejs.github.io/vetur/formatting.html
