### ISSUE TITLE
Vetur could not parse the decorator in methods block.

### ISSUE THREAD

**Issue by OsterHuang** [vuejs/vetur#1461]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Mac 10.14.6
<img width="202" alt="螢幕快照 2019-10-16 上午10 53 06" src="https://user-images.githubusercontent.com/10231299/66884233-26523280-f003-11e9-8bfb-4b78883fde74.png">

- Vetur version: 0.22.4
<img width="657" alt="螢幕快照 2019-10-16 上午10 54 19" src="https://user-images.githubusercontent.com/10231299/66884301-5c8fb200-f003-11e9-9c2f-40ae15c609e3.png">

- VS Code version: 1.38.1

## Problem

The methods with decorator on the head line in Vue component will displays parsing errors.
But it is still running fine on the browser.

<img width="599" alt="螢幕快照 2019-10-16 上午11 08 26" src="https://user-images.githubusercontent.com/10231299/66885135-ef315080-f005-11e9-9d21-c278a536dff7.png">

![螢幕快照 2019-10-16 上午11 08 50](https://user-images.githubusercontent.com/10231299/66885213-2dc70b00-f006-11e9-9172-e7298ab854f0.png)

## Reproducible Case
https://bitbucket.org/oster_huang/useful-annotation/src/master/

**Comment by yoyo930021** [comment]
You can't use decorator on method.
You only can use decorator on clase method.

**Comment by yoyo930021** [comment]
https://babeljs.io/blog/2018/09/17/decorators#object-decorators

**Comment by yoyo930021** [comment]
The Vue file use Typescript parser to parse script.
This error also exists in common javascript file in Typescript parser.
