### ISSUE TITLE
Import typescript file with alias in path into vue component.

### ISSUE THREAD

**Issue by mstys** [vuejs/vetur#1463]
- [ x ] I have searched through existing issues
- [ x ] I have read through [docs](https://vuejs.github.io/vetur)
- [ x ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.22.4
- VS Code version: 1.32.1 (1.32.1)

## Problem

Error in .vue file during import .ts file with alias in path. File is imported correctly but editor mark line with import.

Relative path without an error

![Zrzut ekranu 2019-10-17 o 11 03 24](https://user-images.githubusercontent.com/11544428/66994787-266b3480-f0ce-11e9-94b9-b1045853587d.png)

Path with alias with an error.

![Zrzut ekranu 2019-10-17 o 11 03 45](https://user-images.githubusercontent.com/11544428/66994798-2b2fe880-f0ce-11e9-8eec-8e92ea8c9923.png)

Please note that other files are imported without any error.

tsconfig.json

```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": ["webpack-env", "types/globalTypes.ts"],
    "paths": {
      "@/*": ["src/*"]
    },
    "lib": ["esnext", "dom", "dom.iterable", "scripthost"]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ],
  "exclude": ["node_modules"]
}

```

**Comment by mstys** [comment]
Update: no idea what was the reason of above issue but reinstalling vscode and setup project again helped. I can't reproduce an issue again.

**Comment by samelie** [comment]
Dang! this one is annoying. The code compiles (custom webpack with the `resolve` :
```
resolve: {
    modules: [constants.NODE_MODULES_DIR, constants.WORKSPACE_NODE_MODULES_DIR],
    extensions: ['.ts', '.js', '.vue', '.json'],
    alias: {
      '@': constants.SRC_DIR,     
      ),
    },
  },
```
of course this has nothing to do with VS Code's path resolver. Will post if I find fix

**Comment by nizulzaim** [comment]
same issue. i know this already closed but get same problem

**Comment by yoyo930021** [comment]
Hello everyone,
Vetur is support this feature now.
Please keep `tsconfig.json` in project root.
Remember set `compilerOption.paths`.
and than restart vue language server or restart VSCode.

**Comment by ishaan-puniani** [comment]
Hello, I am getting the same issue, 
Working fine on my teammate machine but not working on my machine and not working on github actions. 

not sure what I am missing
