### ISSUE TITLE
Typescript: data properties not recognised in computed section

### ISSUE THREAD

**Issue by roblugt** [vuejs/vetur#1466]
- [x ] I have searched through existing issues
- [x ] I have read through [docs](https://vuejs.github.io/vetur)
- [x ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  Win
- Vetur version: 0.22.4
- VS Code version: 1.39.0

## Problem

Modified the Home.vue file generated using the vue cli to create a basic vue project using Typescript but not using the using the class-style vue-property-decorators.  After creating a computed property Vetur complains with message

Property 'name' does not exist on type 'CombinedVueInstance<Vue, unknown, unknown, unknown, Readonly<Record<never, any>>>'.

When running the component it works fine.

Reverting to Vetur version 0.18.1 also seems to fix the problem.

**Comment by roblugt** [comment]
![vetur](https://user-images.githubusercontent.com/23504965/67127010-56125d80-f1f0-11e9-8077-5cf26d2a51cc.JPG)

**Comment by roblugt** [comment]
See screenshot for error message, and notice syntax error in the computed title.

**Comment by ktsn** [comment]
You need a return type annotation of the computed property.

See: https://vuejs.org/v2/guide/typescript.html#Annotating-Return-Types

**Comment by roblugt** [comment]
Thank you @ktsn

Adding a return type to the computed property fixed the problem.

**Comment by bambbt** [comment]
I had the same problem.
Thanks for that tip. Make sense.

**Comment by itomtom** [comment]
Hi @ktsn 

Would you happen to know how to annotate a new variable declared in the created hook?
```typescript
  created() {
    this.commentPadding = 15;
  },
```

I've attempted `this.commentPadding: number` but didn't work.

**Comment by ahmed3oun** [comment]
You just need to specify the return type of this function bcs in ts it's necessary i think!
here u must add title : function() : string {
                return this.name 
}
