### ISSUE TITLE
can't jump to other file from the import statement in vue file

### ISSUE THREAD

**Issue by yuanxiaowa** [vuejs/vetur#1468]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version:0.22.5
- VS Code version:1.39.2

**Comment by Ttou** [comment]
same problem

**Comment by MarvinRudolph** [comment]
Same

**Comment by deankinane** [comment]
I'm having the same problem.
It seems IntelliSense for Vue files is completely broken.

I updated to VS Code 1.39.2 yesterday, not sure if that is related to the problem.

I've tested with both JS and TS and neither are working at the moment.

**Comment by deankinane** [comment]
Issue is related to #1449 

Downgrading to Vetur 0.22.3 fixes the issue.

**Comment by MarvinRudolph** [comment]
@deankinane Thank you, downgraded and works fine. :)

**Comment by YamadaAoi** [comment]
Vetur 0.22.4 is ok

**Comment by YamadaAoi** [comment]
> Vetur 0.22.4 is ok

oh no!!!today Vetur 0.22.4 is broken,Vetur 0.22.3 is ok,may be cache

**Comment by yuanxiaowa** [comment]
> > Vetur 0.22.4 is ok
> 
> oh no!!!today Vetur 0.22.4 is broken,Vetur 0.22.3 is ok,may be cache

Vetur 0.22.4 is ok in my matchine, maybe lower versions work

**Comment by yuanxiaowa** [comment]
Vetur 0.22.4 is ok, thanks~~~

**Comment by deankinane** [comment]
> Vetur 0.22.4 is ok, thanks~~~

In 0.22.4 it works for the first file opened or files open from a previous session.
You can recreate by:

1. Close all files

**Comment by yuanxiaowa** [comment]
> > Vetur 0.22.4 is ok, thanks~~~
> 
> In 0.22.4 it works for the first file opened or files open from a previous session.
> You can recreate by:
> 
> 1. Close all files
> 2. Close VS Code
> 3. Open VS Code
> 4. Open a file
> 5. Confirm IntelliSense is working
> 6. Open a second file
> 7. Confirm IntelliSense is not working

I tried follow your steps just now,but it's ok.
