### ISSUE TITLE
On Vue syntax detection

### ISSUE THREAD

**Issue by y912765390** [vuejs/vetur#1470]
hello ！I'd like to know how you check whether the content in < template > is up to the standard. When it's not up to the standard, you will also give a hint like this  ~~~~~.Red wavy line

**Comment by octref** [comment]
https://vuejs.github.io/vetur/interpolation.html

**Comment by y912765390** [comment]
Thank you very much. I'll read it carefully




------------------ 原始邮件 ------------------
发件人: "Pine"<notifications@github.com>;
发送时间: 2019年10月24日(星期四) 凌晨4:01
收件人: "vuejs/vetur"<vetur@noreply.github.com>;
抄送: "912765390"<912765390@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [vuejs/vetur] On Vue syntax detection (#1470)




https://vuejs.github.io/vetur/interpolation.html

**Comment by octref** [comment]
All code are in this repo. You can just read them.

**Comment by y912765390** [comment]
I'm sorry. Maybe I'm a little stupid. I'm still confused. You can give me more details. I think the end must be to use a function to verify the Vue text. Is that so, please? If so, where is this function? Sorry again. I've disturbed you many times

**Comment by y912765390** [comment]
Maybe I should ask, how do you use eslint-plugin-vue to test Vue text
