### ISSUE TITLE
No Intellisense for new exports

### ISSUE THREAD

**Issue by Soresu** [vuejs/vetur#1471]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win 10
- Vetur version: 0.22.3+
- VS Code version: 1.39.2

## Problem

This issue is not connected to [#1449](https://github.com/vuejs/vetur/issues/1449)
Exports from newly created javascript files are not visible in the intellisense. Now, I have to reload the window whenever I create a new javascript file and I want to use it from a vue file.
Since there are intellisense problems with the current versions of vetur, I couldn't check if any of those fixed this.

## Reproducible Case

1. Open a project
2. Create a new javascript file with a named export, eg a function called "test".
3. Open another javascript file and start typing the function name, intellisense will pop up with the function
4. Open a vue file, start typing the function name. The function is missing from the list.
5. Close and open Visual Studio Code
6. Open a vue file, start typing the function name, it will be visible.

**Comment by paskausks** [comment]
I don't think this is for new files. I think it's for all .vue files.

With the current version of Vetur I don't have any IntelliSense. In neither JavaScript or TypeScript projects. As soon as I downgrade to 0.22.4 IntelliSense does work again.

In my case
* Platform: Win 8.1
* Vetur version 0.22.5 (current)
* VS Code version: 1.39.2

Issue can be reproduced by:
1. Cloning the https://github.com/octref/veturpack repo
2. `yarn`
3. Open VSCode in the cloned folder
4. Go to _Counter.vue_ and try Lodash' autocompletion with `_.`

**Comment by Soresu** [comment]
@paskausks For me, the 0.22.4 update completely broke intellisense, and it doesn't work at all. Check the link I referenced in the first comment.

**Comment by paskausks** [comment]
@Soresu yeah, interesting. I'm currently on 0.22.4 since that's the version that is actually working for me.

**Comment by parox2014** [comment]
@paskausks I have the same problem,please tell me how to downgrade,thank you

**Comment by kcwms** [comment]
@parox2014 from the Extension's page download the VSIX under the ChangeLog tab\
![get_vsix](https://user-images.githubusercontent.com/29052675/67356079-0bae1b00-f527-11e9-81bd-42c7d0c3f784.png)

from VSCode (Ctrl+Shift+P) Extension: Install From VSIX...

**Comment by parox2014** [comment]
@kcwms It works,thank you so much

**Comment by octref** [comment]
Does this repro on 0.22.6?

**Comment by paskausks** [comment]
@octref Just tested it. Seemingly, no issues on 0.22.6.

**Comment by Soresu** [comment]
@octref 0.22.6 still has this issue.

**Comment by rickyruiz** [comment]
@octref 0.22.6 fixed it for me. It's blazing fast now in a big TS project that used to be slow. Nice job man!

Platform: Win 10
VS Code version: 1.39.2

**Comment by istriver** [comment]
**I hava the same problem when I update Vetur to version 0.23.0.** 

Platform: Win 10,VS Code version: 1.41.1
I have tried different VS Code version,but also no IntelliSense .
When I downgrade to  0.22. 6, it works.

**Comment by omidb** [comment]
I have the same problem, Vue files don't support lodash IntelliSence. I get full IntelliSence in JS files.

**Comment by zhuqingguang** [comment]
Exports from newly created typescript files are not visible in the intellisense either. Auto importing don't work either, but in `.ts` file it works fine

**Comment by yoyo930021** [comment]
I will close and lock this issue. It has not been active for a long time.
I don't know if the question exists.
If you have problem, please open a new issue.
