### ISSUE TITLE
vetur0.22.5 snippet for js is not work

### ISSUE THREAD

**Issue by zhuman1993** [vuejs/vetur#1475]
when i upload vetur to 0.22.5 version, the snippet for js is not work, and then i installed the 0.22.4 version, it work again.

please finish the issue

**Comment by peidLuo** [comment]
me too, omg,... (ᵒ̤̑ ₀̑ ᵒ̤̑)

**Comment by steelcg** [comment]
me too

**Comment by ah597568204** [comment]
same issues already change version to 0.22.5 version to 0.22.4

**Comment by croson** [comment]
me too

**Comment by Rizzato95** [comment]
Me too

**Comment by JHanL** [comment]
me too

**Comment by BearAndDoggy** [comment]
me too

**Comment by nik9play** [comment]
me too

**Comment by zangxx66** [comment]
me too

**Comment by octref** [comment]
Duplicate of #1476. Fixed by #1472 and released in 0.22.6.
