### ISSUE TITLE
JavaScript code suggestions in Vue components not working on Vetur 0.22.5

### ISSUE THREAD

**Issue by mishannn** [vuejs/vetur#1476]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows 10 Pro
- Vetur version: 0.22.5
- VS Code version: 1.39.2

## Problem

JavaScript code suggestions in Vue components not working on Vetur 0.22.5, but on 0.22.4 is ok.

#### 0.22.5
![image](https://user-images.githubusercontent.com/15077672/67394343-ac92e980-f5ac-11e9-8a06-bd1a3b90c837.png)

#### 0.22.4
![image](https://user-images.githubusercontent.com/15077672/67394397-caf8e500-f5ac-11e9-9ad1-e0c01d56236f.png)

## Reproducible Case

Open any Vue component and write code in ```<script>``` section.

**Comment by pavel-rakhmanov** [comment]
also reproduced with VS Code version: 1.39.1

**Comment by octref** [comment]
Fixed by #1472 and released in 0.22.6.
