### ISSUE TITLE
use files.associations config, Vetur version >= 0.22.5 has error

### ISSUE THREAD

**Issue by winixt** [vuejs/vetur#1480]
## Info

- Platform:  macOS
- Vetur version: 0.22.5、0.22.6
- VS Code version: 1.39.2

## Problem

vscode config `"files.associations": { "*.fes": "vue" }`

when has javascript code( in <script>)，will has problem below:
![image](https://user-images.githubusercontent.com/20717402/67447815-b4539c00-f647-11e9-8adf-5bd34df77fec.png)

![image](https://user-images.githubusercontent.com/20717402/67447494-a6514b80-f646-11e9-8d7d-fa9e645d74b1.png)

if only `<template> and <style>` is ok.

Vetur version(0.22.4) will not has this problem. `.vue` file too.

**Comment by transtone** [comment]
Vetur version(0.22.5) will not has this problem. .vue file too.

**Comment by weixisheng** [comment]
I met the same problem. So I uses version 0.22.5 again.

**Comment by Dshufeng** [comment]
感谢作者,我也遇到这个问题.希望尽快修复

**Comment by octref** [comment]
You can do `"vetur.experimental.templateInterpolationService": false`. Vetur doesn't support `fes` files.

**Comment by winixt** [comment]
> You can do `"vetur.experimental.templateInterpolationService": false`. Vetur doesn't support `fes` files.

vetur.experimental.templateInterpolationService default value is 'false', not change to it.

vscode config has set "files.associations": { "*.fes": "vue" }, so Vetur will work for ‘fes' as 'vue'

**Comment by mryellow** [comment]
This appears to be an ongoing issue. 

```
    "files.associations": {
        "*.foo": "vue"
    },
    "vetur.grammar.customBlocks": {
        "bar": "js"
    },
```

Working `file.foo`:

```
<bar>
</bar>
```

```
<script lang="js">
</script>
```

Not working `file.foo`:

```
<script>
</script>
```

**Comment by yoyo930021** [comment]
It's a limit.
TypeScript language service can't support.

**Comment by mryellow** [comment]
I had assumed it could be forced by specifying the language as a custom block, but would appear `"script"` is a special case and the following doesn't work:

```
    "vetur.grammar.customBlocks": {
        "script": "js"
    },
```

**Comment by mryellow** [comment]
I'm convinced this is a bug.

In any file type associated with Vue. A `<script>` tag should be interpreted as Javascript unless otherwise specified.

It should not be required to define `lang="js"` on a `<script>` tag.

```
  "files.associations": {
      "*.foo": "vue"
  },
  ```
    
    Should make `*.foo` files behave exactly like `*.vue` files.

**Comment by yoyo930021** [comment]
> I'm convinced this is a bug.
> 
> In any file type associated with Vue. A `<script>` tag should be interpreted as Javascript unless otherwise specified.
> 
> It should not be required to define `lang="js"` on a `<script>` tag.
> 
> ```
>   "files.associations": {
>       "*.foo": "vue"
>   },
> ```
> 
> Should make `*.foo` files behave exactly like `*.vue` files.

The `files.associations` option don't support in Vetur.
It is a limit in TypeScript language service.

**Comment by mryellow** [comment]
> It is a limit in TypeScript language service.

Is this part of Vetur? Which limit are you talking about?

I don't wish to have anything to do with TypeScript. `<script>` should be Javascript until `lang="ts"` says otherwise.

**Comment by yoyo930021** [comment]
> > It is a limit in TypeScript language service.
> 
> Is this part of Vetur? Which limit are you talking about?
> 
> I don't wish to have anything to do with TypeScript. `<script>` should be Javascript until `lang="ts"` says otherwise.

JavaScript feature is from TypeScript language service.

**Comment by mryellow** [comment]
I'm willing to put some time into fixing this bug if you can point me in the right direction.

![Screenshot_20201217_141432](https://user-images.githubusercontent.com/213575/102439356-426fba80-4072-11eb-8a32-7051bbe84ffb.png)

**Comment by yoyo930021** [comment]
> I'm willing to put some time into fixing this bug if you can point me in the right direction.
> 
> ![Screenshot_20201217_141432](https://user-images.githubusercontent.com/213575/102439356-426fba80-4072-11eb-8a32-7051bbe84ffb.png)

Please open a new issue.
