### ISSUE TITLE
Question marks not shown next to optional object properties

### ISSUE THREAD

**Issue by ffxsam** [vuejs/vetur#1482]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.22.6
- VS Code version: 1.39.2

## Problem

In .vue files, optional properties (in an object arg) are not shown with question marks, yet this behavior is present in .ts files.

Example (.ts file):

<img width="678" alt="Screen Shot 2019-10-25 at 3 39 37 PM" src="https://user-images.githubusercontent.com/12532733/67603280-0c6cca00-f73e-11e9-9b82-c1eefd33e8a0.png">

In a .vue file:

<img width="679" alt="Screen Shot 2019-10-25 at 3 38 12 PM" src="https://user-images.githubusercontent.com/12532733/67603297-14c50500-f73e-11e9-98cc-3d66fb009863.png">

## Reproducible Case

1. Open .vue file
2. Import a function that takes an object with optional properties as an argument
3. Trigger autocomplete

**Comment by octref** [comment]
Part of #1510.
