### ISSUE TITLE
Multi-line declarations not recognized by vetur

### ISSUE THREAD

**Issue by mubaidr** [vuejs/vetur#1487]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win 10
- Vetur version: 0.22.6
- VS Code version: 1.40-insiders

## Problem

This is actually a compatibility issue with `prettier` formater. 

If an array in the script is formatted by prettier into multi-line definition, the `vetur` fails to recognize variables on multi-lines used this in template. 

![Capture](https://user-images.githubusercontent.com/2222702/68089840-da224180-fe8e-11e9-82f0-78b4458e9519.PNG)

## Reproducible Case

![Capture2](https://user-images.githubusercontent.com/2222702/68089824-a0e9d180-fe8e-11e9-9f12-771c27b86bce.PNG)

**Comment by ktsn** [comment]
This is not related to prettier but Vuex typings. The problem should not occur on the latest Vuex typings (v3.1.2).
