### ISSUE TITLE
Got "valid-v-for" if I write key in bind attribute

### ISSUE THREAD

**Issue by iigmir** [vuejs/vetur#1493]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS 10.15.1
- Vetur version: 0.22.6
- VS Code version: 1.40.0

## Problem

When I write codes like "Reproducible Case" paragraph, it shows this linting:

```
[vue/valid-v-for]
Custom elements in iteration require 'v-bind:key' directives.eslint-plugin-vue
```

![Screenshot](https://user-images.githubusercontent.com/11061770/68459253-d81a0300-023f-11ea-9474-2fdfc4b2559b.png)

Binding an object of attributes is valid syntax in VueJS. I believe that write the `key` attribute in the `v-bind` binding object should be valid.

## Reproducible Case

Save this code in VS Code as `.vue` format:

```
<template>
    <b-nav-item v-for="(item) in link_binding" v-bind="{ key: item.name.id }" >
        Elements inside
    </b-nav-item>
</template>
```

## Issues might be related
#261

[ Replace require-v-for-key with new rule just for stateful elements #522 ](https://github.com/vuejs/eslint-plugin-vue/issues/522)

**Comment by sqal** [comment]
You should report this issue in the [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue) repository, this is not directly related to Vetur.

**Comment by ktsn** [comment]
Yes, it should be reported on eslint-plugin-vue.

**Comment by iigmir** [comment]
OK, I will. I just thaught that it's just a issue from Vetur.
