### ISSUE TITLE
TypeScript 3.7 features interpreted as errors

### ISSUE THREAD

**Issue by NicoAiko** [vuejs/vetur#1498]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS Catalina
- Vetur version: 0.22.6
- VS Code version: 1.40.0

## Problem

TypeScript v3.7 introduced some new features, like optional chaining and nullish coalesce.
These changes produce errors for Vetur though.

![Bildschirmfoto 2019-11-11 um 15 09 09](https://user-images.githubusercontent.com/22343587/68593300-66d38d80-0495-11ea-92d3-6cea96e29ec6.png)

## Reproducible Case

Just create a `.vue` file with its script being typescript (obviously on v3.7+) and create a function that uses the new features.

**Comment by ktsn** [comment]
Enable `Vetur: Use Workspace Dependencies` to let Vetur use 3.7. See https://github.com/vuejs/vetur/issues/1438#issuecomment-551911880
