### ISSUE TITLE
emmet SuggestionsAsSnippets not working on sass

### ISSUE THREAD

**Issue by yoyoys** [vuejs/vetur#1508]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.22.6
- VS Code version: 1.40.1

## Problem

I'd use emmet setting below:
```json
"emmet.showSuggestionsAsSnippets": true,
"editor.snippetSuggestions": "top"
"emmet.includeLanguages": {
    // "vue-sass": "sass"  // it's no use
    "vue-html": "html"
},
``` 

emmet works fine with other blocks, but not working on sass block. (gif below)

## Reproducible Case
I'd test with stylus and `scss`, works fine.
But `sass` was broken.
(btw, the suggestion was auto close when I enter properties.)

![2019-11-20 06 12 25](https://user-images.githubusercontent.com/22124891/69191168-f0055700-0b5c-11ea-8310-b5891639e34e.gif)

**Comment by octref** [comment]
Vetur only has syntax highlighting and formatting support for SASS.

@TheRealSyler Maybe you would be interested?

**Comment by TheRealSyler** [comment]
ill take a look at it, but im pretty sure that emmet is handled by vscode.

**Comment by TheRealSyler** [comment]
@octref @yoyoys this issue can be closed.
