### ISSUE TITLE
Intellisense not recognizing Vue SFC's component

### ISSUE THREAD

**Issue by BSG-75** [vuejs/vetur#1509]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows
- Vetur version: 0.22.6, installed through VSIX from VSCode in administrator mode
- VS Code version: 1.39.2 (System setup)

## Problem
Looks like VSCode won't recognize my Vue component in the SFC file, but just an ordinary object:
![image](https://user-images.githubusercontent.com/2989995/69278881-749ab880-0be3-11ea-8482-9e8326c04b8c.png)

When I write `this.`, computed properties `predefinedTags`, `computedTags` etc. are suggested as _methods_ because like `mode`, they are all declared as `computed`'s member, but I can't get any intellisense suggestions from `data()`.

Output from Vue Language Server log:
```
Loaded bundled typescript@3.6.3.
Vetur initialized
```

**Comment by Soresu** [comment]
I've just noticed the same thing. I've checked it in the previous verisons, it stopped working after version 0.22.2.

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/74289290-7f954e80-4ce3-11ea-9a92-11cdca8fed05.png)

```vue
<template>
  <div></div>
</template>

<script>
export default {
  data() {
    return {
      tags: ['CMS']
    }
  },
  computed: {
    mode() {
      this.
    }
  }

};
</script>
```

Please provide a minimal reproducible case.

**Comment by Soresu** [comment]
@octref Currently with Vetur 0.23.0 and VSCode 1.42.0 it is working fine. Although in the template tag, the nested properties are not visible. 

![image](https://user-images.githubusercontent.com/9396091/74328382-0dc60f00-4d8e-11ea-8d4d-904d1368755b.png)

It knows that there is an obj variable with test and test2 properties, but there is no intellisense after the dot. Also there is no info about the Vue instance properties, like $router. It is visible in the script tag.

**Comment by octref** [comment]
@Soresu That's a different issue, tracked in #1129.

**Comment by Soresu** [comment]
@octref Ah fine, thanks for the info. 
Meanwhile, the issue happened again. When you define the "props" property on the Vue instance and you return a property from a computed, the intellisense stop working in computed fields. And  in the tooltip, it is labeled as method instead of property.


![image](https://user-images.githubusercontent.com/9396091/74429762-d7ef5c00-4e5b-11ea-9275-0253de59f21e.png)

 Without "props" property (or returning a local variable), it is working, which is interesting.

![image](https://user-images.githubusercontent.com/9396091/74430071-711e7280-4e5c-11ea-9902-23f3e4b8f966.png)

**Comment by octref** [comment]
Can you create a minimal repro by forking https://github.com/octref/veturpack and open a new issue?

![image](https://user-images.githubusercontent.com/4033249/74481975-7ed9f500-4e68-11ea-978c-d7689bc8faf6.png)

**Comment by yoyo930021** [comment]
If `vetur.useWorkspaceDependencies: true`, you will use typescript@2.9.2 in vetur and not have any error.
The error is happened when using typescript@^3.x.x.
It's a type error in Vue lib.
Ref: vuejs/vue#11235

**Comment by octref** [comment]
@yoyo930021 Thanks a lot for finding the issue and providing a fix!
I'll mark this as upstream and close it then.

**Comment by ZhengXiaowei** [comment]
why dosen't it work for me?
