### ISSUE TITLE
HTML angle-bracket matching fails with v-if="foo > 0"

### ISSUE THREAD

**Issue by qgates** [vuejs/vetur#1525]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

- Platform: Win10
- Vetur version: 0.22.6
- VS Code version: 1.40.1

## Problem

A line like `<template v-if="colindex > 0">` breaks vscode angle-bracket matching, which matches the opening < with the > from the v-if condition and not the > at eol.

**Comment by ktsn** [comment]
Can you provide a self-contained reproduction please?
About reproduction: https://new-issue.vuejs.org/?repo=vuejs/vue#why-repro

**Comment by qgates** [comment]
Here's an example snippet. Paste into a file of type 'Vue'
```
<template>
  <div v-if="colindex > 0">
    <p>Some content</p>
  </div>
</template>
```
1. Place the cursor on 'colindex' and see that the greater than angle-bracket is incorrectly matched to the opening angle-bracket of the div.
2. Place the cursor at the end of the line `<template>` and see that the `<p>` angle brackets are incorrectly highlighted, a consequence of (1).
3. Change the v-if condition by replacing `"colindex > 0"` with `"colindex == 0"` and everything's fixed.

**Comment by qgates** [comment]
Closing, it appears that bracket matching is done by editor core and not by syntax definition. Following up with a post to https://github.com/microsoft/vscode/issues/71091#issuecomment-557582765.
