### ISSUE TITLE
Intellisense cannot recognize .vue file imported from JS file.

### ISSUE THREAD

**Issue by fejj182** [vuejs/vetur#1573]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.22.6
- VS Code version: 1.40.2

## Problem

Pretty simply, it seems intellisense is working fine when I'm inside a .vue file, but not inside a .js file. The files are in the same directory.

I've seen that there have been similar issues and some were fixed in 0.22.6 but also none that mention it only not working in JS.

<img width="628" alt="Screenshot 2019-12-01 at 12 31 16" src="https://user-images.githubusercontent.com/9628162/69913334-d0acda80-1436-11ea-9b6a-249d8d0aeccb.png">

<img width="721" alt="Screenshot 2019-12-01 at 12 31 42" src="https://user-images.githubusercontent.com/9628162/69913338-d4406180-1436-11ea-9203-6d2b8e5951a4.png">

I've tried many versions of jsconfig.json file (it's at the root) but with no luck. Also tried to install Path Intellisense/Autocomplete but they can't find the .vue file either.

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "target": "es6",
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "exclude": ["node_modules", "dist"]
}
```

## Reproducible Case

N/A - All cases

**Comment by michaelnwani** [comment]
I would like to add on that in my code, there’s no intellisense for the vuex import in .js files either (but it works when inside .vue files)

**Comment by octref** [comment]
I do special handling inside Vue files. I don't have that access in JS/TS files. You would need to file an issue for VS Code or TypeScript.
