### ISSUE TITLE
<script> region language features fail if using self-closing <template>

### ISSUE THREAD

**Issue by qq326943819** [vuejs/vetur#1577]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win10
- Vetur version:0.22.6
- VS Code version:1.40.2

## Problem
In ".vue" file.If my template tag is self-closing,my IntelliSense will fail,and the code cannot be formatted.
e.g(waiting gif)

![QljXJ1.gif](https://s2.ax1x.com/2019/12/04/QljXJ1.gif)

## Reproducible Case
N/A - All cases

**Comment by gfernandez-me** [comment]
same here
