### ISSUE TITLE
Broken intellisense with typescript 3.7.3 (Vetur 0.23.0)

### ISSUE THREAD

**Issue by Niekvdm** [vuejs/vetur#1589]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windown 10
- Vetur version: 0.23.0
- VS Code version: 1.40.2
- Extensions Enabled: Vetur only

## Problem

Build latest master source and named it for example 0.22.7.
This latest master version will be named 0.23.0 according to the changelog.

The issue is that within SFC .vue files (typescript) intellisense stops working.
![image](https://user-images.githubusercontent.com/3315401/70691872-7293b900-1cba-11ea-9d3a-94632479b5ab.png)

In the image above it showcases the issue, type definition on hover and intellisense (shift+space) are stuck on loading.

This also happened on Vetur 0.22.6 with useWorkspaceDependencies (TS 3.7.x) enabled.
Typescript 3.6.x works properly.

![image](https://user-images.githubusercontent.com/3315401/70692016-c56d7080-1cba-11ea-904d-07447a1efb80.png)

I've mentioned this issue before here:
https://github.com/vuejs/vetur/issues/1510#issuecomment-557410649

This is issue showcases the problem.

## Reproducible Case

Build from master branch including Typescript 3.7.x (3) and try to use intellisense or resolve types on hover.

**Comment by octref** [comment]
Is it slow or is it completely broken?
Any error in Help -> Developer Tools or Output -> Vue Language Server?

**Comment by Niekvdm** [comment]
> Is it slow or is it completely broken?
> Any error in Help -> Developer Tools or Output -> Vue Language Server?

Completely broken, first time you try to resolve something it breaks no errors.
F12 goto to definition breaks aswell and it will keep loading indefinitely.

**Comment by Niekvdm** [comment]
@octref I've tried to captured it in a short video:
[Vetur_0.23.0_Typescript_3.7.3_broken_intellisense.MP4](https://drive.google.com/file/d/1srxNAC-5MmaWFrftWRHlFNGDxLHntvwO/view)

As shown in the video upon a fresh reload of vscode all is wel until you start typing and try to use intellisense everything breaks. unfortunately no errors are show in the console or any of the vscode logs.

**Comment by pellelauritsen** [comment]
Is this the reason why v0.23 is not on VS Marketplace ?

**Comment by Niekvdm** [comment]
Has this been addressed?

**Comment by Niekvdm** [comment]
Double checked it with the latest release, problem still exist as described and shown in the video.

**Comment by Yancy1028** [comment]
0.22.6 is work ok.wating 0.23.x

**Comment by Niekvdm** [comment]
@Yancy1028 Thats correct but the current release is 0.23.0. Which also includes nullish coalescing etc.

**Comment by Niekvdm** [comment]
@octref I've found out that upgrading to Typescript 3.7.5 solves this issue. As in 3.7.5 they resolved an issue with paths on non C drive on windows.

> We've updated our bundled TypeScript version to 3.7.5. This minor update includes some important bugs fixes, including fixing IntelliSense for projects that are not stored on C: drives on Windows.

**Comment by octref** [comment]
@Niekvdm Great. I'll upgrade to TS 3.7.5 for next release.
