### ISSUE TITLE
Html Mirror Cursor does not activate in vue-html template

### ISSUE THREAD

**Issue by davidbernegger** [vuejs/vetur#1590]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.22.6
- VS Code version:

## Problem

vscode 1.41 introduced [html mirror cursors](https://code.visualstudio.com/updates/v1_41#_html-mirror-cursor), but they don't get activated in the template tags

## Reproducible Case

1) Enter cursor in html tag
2) No secondary cursor appears

**Comment by octref** [comment]
#565.
