### ISSUE TITLE
Maybe a typo?

### ISSUE THREAD

**Issue by troy351** [vuejs/vetur#1599]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version:
- VS Code version:

## Problem

https://github.com/vuejs/vetur/blob/975e51018d10503db881c0fad2fd5e99ef9ddb1d/server/src/services/dependencyService.ts#L26

**Comment by octref** [comment]
Thanks, that's embarrassing 😅
