### ISSUE TITLE
stuck in installing

### ISSUE THREAD

**Issue by balta3** [vuejs/vetur#1602]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: 
- VS Code version: 1.41.1

## Problem

If I try to install the plugin, it is stuck in installing without any message in the developer tools log.

**Comment by octref** [comment]
Please try the methods in FAQ: https://github.com/vuejs/vetur/blob/master/docs/FAQ.md
