### ISSUE TITLE
vetur detect *.nvue files with many error

### ISSUE THREAD

**Issue by 15050050972** [vuejs/vetur#1616]
In *.vue file, vetur works fine, but I have some file like `*.nvue`, it is actually  a vue file( but can't change it to .vue).
Vetur can't recgonize *.nvue file, so I set `file association` in vscode setting, like:
```
"files.associations": {
        "*.nvue": "vue"
    },
```
Now the *.nvue file has the vue logo, but vetur dected many errors: 
![K(1N(UY~DNW%6BT(Z1D(55Y](https://user-images.githubusercontent.com/23148429/71629346-fa287400-2c37-11ea-8498-58529712fa48.png)

BTW, the left is my plugin, It seems there is no conflict with `vetur`.
And, when I canged `file association` from `vue` to `html`, it worked.

Could you give me some advice?
Thanks for your time.

**Comment by octref** [comment]
`files.associations` doesn't make a file automatically supported by Vetur. We only support .vue files. Sorry.

**Comment by sowth** [comment]
@octref 如何让 Vetur 支持 .nvue 文件？我很需要这个功能，如果你知道，请告诉我，然后我自行修改本地已安装的Vetur扩展。

**Comment by joye-wang** [comment]
vetur官方回复的是不支持nvue文件后缀，vetur只是提供了一些高亮和增强，感觉不用它也是可以的。再具体的你咨询一下uni app的交流群吧


页面最左下角：https://uniapp.dcloud.io/README
