### ISSUE TITLE
Parsing error: Unexpected token <

### ISSUE THREAD

**Issue by GopherJ** [vuejs/vetur#1624]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: 0.0.65
- VS Code version: N/A

## Problem

I've used vue-language-server for vim along with YCM and Ale, it's reporting unexpected token for `<template`

## Reproducible Case

vim config: https://github.com/GopherJ/cfg/blob/master/vim/.vimrc
installation script: https://github.com/GopherJ/cfg/blob/master/vim/install.sh

## Screenshots
![Peek 2020-01-07 20-54](https://user-images.githubusercontent.com/33961674/71896982-2d1abc80-3190-11ea-889d-3cfddaa2811d.gif)

**Comment by octref** [comment]
I don't know what is `$t` or how I can repro this issue.

Your issue is closed because you did not provide a repro case. Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.
