### ISSUE TITLE
Vetur Error 2769 on Vuex mapState

### ISSUE THREAD

**Issue by ariefsn** [vuejs/vetur#1625]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows
- Vetur version: 0.22.6
- VS Code version: 1.41.1

## Problem

I want to use vuex mapState with modules then show this error.
![image](https://user-images.githubusercontent.com/33569737/71956053-ab24a500-321c-11ea-9f70-8a3eddb86e0c.png)
![image](https://user-images.githubusercontent.com/33569737/71956085-c68fb000-321c-11ea-9921-dec1c6e63c2d.png)

**Comment by ktsn** [comment]
Could you report it on Vuex repo as it is typing issue of Vuex?
