### ISSUE TITLE
identifier expected

### ISSUE THREAD

**Issue by Cipa** [vuejs/vetur#1633]
- [ x] I have searched through existing issues
- [ x] I have read through [docs](https://vuejs.github.io/vetur)
- [ x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Macos
- Vetur version: latest
- VS Code version: latest

## Problem
<img width="1327" alt="Screen Shot 2020-01-10 at 10 13 54 PM" src="https://user-images.githubusercontent.com/293377/72199843-cd721a80-33f6-11ea-80a6-e4852546ce29.png">

VS code reset to default, and only installed Vetur as you can see in the image above

## Reproducible Case
see above

**Comment by ktsn** [comment]
Where `@apply` comes from? Looks like your code is different from [CSS apply rule](https://hospodarets.com/css_apply_rule) which expects css custom properties after `@apply`.

**Comment by Cipa** [comment]
I use tailwind.css.
Maybe I need to add more plugins?

<img width="1440" alt="Screen Shot 2020-01-11 at 10 34 39 AM" src="https://user-images.githubusercontent.com/293377/72208964-3b9df800-345e-11ea-916e-919a500f445f.png">

**Comment by ktsn** [comment]
It looks it should be without `.`.
https://tailwindcss.com/docs/extracting-components/#extracting-css-components-with-apply

"Unknown at rule" comes from VSCode built-in css/scss validator. You should disable it in config. Search `unknown at rule` on VSCode settings pane.

**Comment by Cipa** [comment]
Interesting, the tutorial I followed was using the .
Unfortunately I get different problems without the code on the example page
<img width="1440" alt="Screen Shot 2020-01-11 at 10 49 45 PM" src="https://user-images.githubusercontent.com/293377/72215202-e8ab5b80-34c4-11ea-8257-8df70ccc5679.png">

**Comment by ktsn** [comment]
Looks like you need to specify `lang="postcss"` as tailwind css is using postcss and introducing the customized syntax.

![image](https://user-images.githubusercontent.com/2194624/72215452-07a5fe00-3556-11ea-8412-630571e8f101.png)

**Comment by Cipa** [comment]
That triggers a compile error in my case
<img width="431" alt="Screen Shot 2020-01-12 at 12 00 42 AM" src="https://user-images.githubusercontent.com/293377/72215921-bdc60500-34ce-11ea-96b6-cca949799ccd.png">

**Comment by ktsn** [comment]
You may want to override default highlight to get rid of `lang="postcss"` via config or configure your build for `lang="postcss"`...
https://vuejs.github.io/vetur/highlighting.html#custom-block

```js
  "vetur.grammar.customBlocks": {
    "style": "postcss"
  }
```

**Comment by Cipa** [comment]
still no luck
I tried lang="postcss", css, stylus, sass, scss but I get a compile error

no lang, it compiles but looks like this

<img width="738" alt="Screen Shot 2020-01-12 at 8 40 43 AM" src="https://user-images.githubusercontent.com/293377/72222251-7748c880-3517-11ea-9309-bfe030f5268b.png">

**Comment by ktsn** [comment]
Did you follow the steps stated on docs?
