### ISSUE TITLE
离线扩展包vetur下载不成功，显示失败-网络错误

### ISSUE THREAD

**Issue by lfx1993** [vuejs/vetur#1636]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version:
- VS Code version:

**Comment by octref** [comment]
Your issue is closed because you did not provide a repro case. Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.
