### ISSUE TITLE
Vue 3.0 support

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#1638]
https://github.com/vuejs/vetur/tree/vue3 should support it by wrapping default export in `createComponent`.

@yyx990803 I only see `createComponent` with `3.0.0-alpha.1`. Do you still plan to rename this to `defineComponent`? Is there an issue I can follow?

I see that `createComponent` is already replaced with `defineComponent` in https://github.com/vuejs/vue-next, but these changes aren't published.

**Comment by yyx990803** [comment]
We will be publishing 3.0.0-alpha.2 very soon.

**Comment by yyx990803** [comment]
Alpha 2 is out. However I noticed `defineComponent` was in fact already in alpha 1: https://unpkg.com/browse/@vue/runtime-core@3.0.0-alpha.1/dist/runtime-core.d.ts - maybe there was a version mismatch of some sort?

**Comment by octref** [comment]
@yyx990803 🤦‍♂I pulled the sample code that updated package.json but didn't run `yarn` again.

#1645 should fix this.

**Comment by mika76** [comment]
Is there a vue 3 issue or miletstone that can be tracked maybe? I mean vetur pretty much  works but multiple root nodes currently give errors and there are one or two other things I've hit...

**Comment by Spittal** [comment]
I'm also curious about the state of supporting fragments?
