### ISSUE TITLE
Cannot find name 'document', 'window', ... Do you need to change your target library?

### ISSUE THREAD

**Issue by scriptlessatwork** [vuejs/vetur#1646]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win 10
- Vetur version: 0.23.0
- VS Code version: 1.41.1

## Problem
![](https://i.imgur.com/3gYnsFL.png)

Using Typescript.

What I done:
- added dom to lib in tsconfig.json
- check tsconfig.json for errors
- reinstalled vetur, restarted vscode

Seems like simple dom objects/methods are unknown to Vetur even when DOM is defined in lib.

tsconfig.json:
```js
{
    "compileOnSave": false,
    "buildOnSave": false,
    "atom": {
      "rewriteTsconfig": false
    },
    "compilerOptions": {
      "allowSyntheticDefaultImports": true,
      "allowUnreachableCode": false,
      "allowUnusedLabels": false,
      "alwaysStrict": true,
      "baseUrl": "./",
      "charset": "utf8",
      "declaration": false,
      "diagnostics": false,
      "esModuleInterop": true,
      "experimentalDecorators": true,
      "emitDecoratorMetadata": true,
      "forceConsistentCasingInFileNames": true,
      "importHelpers": true,
      "locale": "en",
      "module": "commonjs",
      "moduleResolution": "node",
      "newLine": "lf",
      "noEmit": false,
      "noEmitHelpers": false,
      "noEmitOnError": false,
      "noFallthroughCasesInSwitch": true,
      "noImplicitAny": true,
      "noImplicitReturns": true,
      "noImplicitThis": false,
      "noImplicitUseStrict": false,
      "noUnusedLocals": true,
      "noUnusedParameters": false,
      "pretty": true,
      "removeComments": true,
      "resolveJsonModule": true,
      "sourceMap": false,
      "strictNullChecks": false,
      "target": "es2016",
      "paths": {
        "@/*": [
          "src/*"
        ]
      },
      "lib": [
        "es2017",
        "es2016",
        "es2015",
        "esnext",
        "dom"
      ],
    },
    "include": [
      "src/*",
    ],
    "exclude": [
      "node_modules"
    ]
  }
  ```

## Reproducible Case

Test application: https://github.com/scriptlessatwork/test-app
For example using document.* or window.* methods in a Vue component method.
Language is Typescript.

**Comment by ktsn** [comment]
Could you provide self-contained reproduction?
See about reproduction: https://new-issue.vuejs.org/?repo=vuejs/vue#why-repro

**Comment by scriptlessatwork** [comment]
> 
> 
> Could you provide self-contained reproduction?
> See about reproduction: https://new-issue.vuejs.org/?repo=vuejs/vue#why-repro

Added

**Comment by ktsn** [comment]
Did you read the link I posted? Text is not a reproduction as we cannot exactly confirm the issue from it. You can provide minimal example project, reproducing the issue, as GitHub repository, for example.

**Comment by scriptlessatwork** [comment]
> 
> 
> Did you read the link I posted? Text is not a reproduction as we cannot exactly confirm the issue from it. You can provide minimal example project, reproducing the issue, as GitHub repository, for example.

Added a minimal test app. The path to the file with the error is src/components/HelloWorld.vue
There is also a screenshot shown the problem in the file.

**Comment by ktsn** [comment]
Is it really reproducible case on your end? I could not see any errors on it. Also it does not have `tsconfig.json` which you stated in the original post.
<img width="418" alt="Screenshot 2020-01-15 at 7 17 00 PM" src="https://user-images.githubusercontent.com/2194624/72425705-a71ff680-37cb-11ea-9697-8ddc5feb241c.png">

**Comment by scriptlessatwork** [comment]
> Is it really reproducible case on your end? I could not see any errors on it. Also it does not have `tsconfig.json` which you stated in the original post.
> <img alt="Screenshot 2020-01-15 at 7 17 00 PM" width="418" src="https://user-images.githubusercontent.com/2194624/72425705-a71ff680-37cb-11ea-9697-8ddc5feb241c.png">

So I found out that the error messages dont exist on my Macbook while on my main computer (Windows 10) it shows those errors. I'm using vscode settings sync, so they should have the same settings. Weird.

**Comment by scriptlessatwork** [comment]
Seems like its actually working now, I didnt found the issue

**Comment by plastic-shurikens** [comment]
Might be a late reply but adding "DOM" to lib in compilerOptions solved it for me 

`{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "lib": ["es6", "DOM"],
    "allowJs": true,
    "outDir": "build",
    "rootDir": "src",
    "strict": true,
    "esModuleInterop": true,
    "types": ["node", "jest"],
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "downlevelIteration": true,
  },`
