### ISSUE TITLE
Vuter 0.23.0 Cannot work

### ISSUE THREAD

**Issue by HuangZhaoPing** [vuejs/vetur#1652]
## Info

- Platform: win10
- Vetur version: 0.23.0
- VS Code version: 1.41.1

## Problem

the 0.23.0 version cannot work in .vue file（no javascript prompt and no css prompt），back to 0.22.6 is ok

**Comment by octref** [comment]
Any error message in Output -> Vue Language Server, or Help -> Toggle Developer Tools?

Also please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue with repro case.

**Comment by abdallla-mosa** [comment]
Ihave the same problam
