### ISSUE TITLE
Stylus is being converted to css on save

### ISSUE THREAD

**Issue by geoidesic** [vuejs/vetur#1670]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS (Mojave)
- Vetur version: 0.23.0
- VS Code version: 1.41.1

## Problem

I have only Vetur plugin, no other plugins enabled.
When I save my Vue SFC, stylus markup is automatically converted to CSS in the editor and saved as CSS instead of stylus.

## Reproducible Case
```
<template lang="pug">
$2
</template>
<style lang="stylus">
textarea
    .wide
        width:100%
</style>
<script>
export default {
  name: "$1",
  props: [],
  data() {
    return {};
  },
  created() {},
  mounted() {},
  computed: {},
  methods: {}
};
</script>
```

I simply paste that in and save it as tmp.vue and it converts immediately to:
```
<template lang="pug">
$2
</template>
<style lang="stylus">
textarea {
  .wide {
    width: 100%;
  }
}
</style>
<script>
export default {
  name: "$1",
  props: [],
  data() {
    return {};
  },
  created() {},
  mounted() {},
  computed: {},
  methods: {}
};
</script>
```

**Comment by octref** [comment]
`"editor.formatOnSave": false` or `vetur.format.defaultFormatter.stylus: "none"`.

**Comment by geoidesic** [comment]
Thanks but where do I put those settings? Presumably some file? If I click on VsCode settings then I get a form... so I'm not sure what do do here.

**Comment by geoidesic** [comment]
Also it sounds like you're suggesting that I switch stylus formatting off.. but I want it on. The problem is that instead of formatting it as stylus, ventur is currently formatting it as CSS.

I think this should be re-opened.

**Comment by octref** [comment]
https://vuejs.github.io/vetur/formatting.html#stylus-supremacy

![image](https://user-images.githubusercontent.com/4033249/75494025-1e6eab80-5970-11ea-8bfe-329023952c39.png)
