### ISSUE TITLE
No CSS completions in `style` attribute inside `<template>` region

### ISSUE THREAD

**Issue by snoopy83101** [vuejs/vetur#1678]
## Info
- Platform: macOS
- Vetur version:
- VS Code version:

## Problem

"files.associations": {
        "*.vue": "vue"
  }
then:
![image](https://user-images.githubusercontent.com/24613784/73130279-5f516880-4030-11ea-96bf-51bf60b673b3.png)

style snippet not work

"files.associations": {
        "*.vue": "html"
  }
then:
![image](https://user-images.githubusercontent.com/24613784/73130358-cd4a5f80-4031-11ea-9669-65d0a49e447d.png)

Vetur does not work

I hope to have code hints for inline styles, and also use Vetur.
Can this be achieved?

![image](https://user-images.githubusercontent.com/24613784/73130338-7e9cc580-4031-11ea-9427-83ee84ae8d70.png)
![image](https://user-images.githubusercontent.com/24613784/73130343-96744980-4031-11ea-866a-a979056febb6.png)

**Comment by snoopy83101** [comment]
1. When tr in a table's header sets the width
2. When setting heigth for some elements
3. When debugging styles temporarily in the development environment

I think this may still be necessary.

**Comment by snoopy83101** [comment]
@octref 
HI! So, is this a feature that will be perfected sooner or later?

**Comment by snoopy83101** [comment]
@octref 
It's been a long time since, unfortunately, I still haven't seen the fix of this bug.

**Comment by snoopy83101** [comment]
@octref  What is the specific version number?

**Comment by octref** [comment]
@snoopy83101 It's not released yet. It'll be released in 0.27.0.

**Comment by snoopy83101** [comment]
@octref 
![image](https://user-images.githubusercontent.com/24613784/92704943-e405b280-f385-11ea-9347-e20acd973c22.png)
Unfortunately, it did not work.

**Comment by cereschen** [comment]
> @octref @cereschen
> ![image](https://user-images.githubusercontent.com/24613784/92704943-e405b280-f385-11ea-9347-e20acd973c22.png)
> Unfortunately, it did not work.

Please refer to the behavior of EMMT in the Style block
![image](https://user-images.githubusercontent.com/52478109/92712527-672a0700-f38c-11ea-9640-37407c98f48f.png)

none:
![image](https://user-images.githubusercontent.com/52478109/92712580-7c9f3100-f38c-11ea-8dd0-6c050b33b2a8.png)

**Comment by snoopy83101** [comment]
Sorry i don't quite understand what you are talking about
The style in the div tag does not enable automatic perception like HTML.

how to  "refer to the behavior of emmet in the Style block"?

**Comment by snoopy83101** [comment]
What I understand is:

Previously, when choosing .vue, IntelliSense could not appear in style.
At present, choose .vue, style can appear and can only be perceived (same as html)

Am I wrong?

**Comment by snoopy83101** [comment]
> > @octref @cereschen
> > ![image](https://user-images.githubusercontent.com/24613784/92704943-e405b280-f385-11ea-9347-e20acd973c22.png)
> > Unfortunately, it did not work.
> 
> Please refer to the behavior of emmet in the Style block
> ![image](https://user-images.githubusercontent.com/52478109/92712527-672a0700-f38c-11ea-9640-37407c98f48f.png)
> 
> none:
> ![image](https://user-images.githubusercontent.com/52478109/92712580-7c9f3100-f38c-11ea-8dd0-6c050b33b2a8.png)

What I understand is:

Previously, when choosing .vue, IntelliSense could not appear in style.
At present, choose .vue, style can appear and can only be perceived (same as html)

Am I wrong?

**Comment by snoopy83101** [comment]
Why can't the html part of .vue be the same as .html?

**Comment by snoopy83101** [comment]
![image](https://user-images.githubusercontent.com/24613784/92716805-e53cdc80-f391-11ea-9a31-31b5422134c7.png)
Are you saying this? In <style></style>?
There is no problem before. The problem is that the style="" in the <div></div> tag has no IntelliSense

**Comment by cereschen** [comment]
> ![image](https://user-images.githubusercontent.com/24613784/92716805-e53cdc80-f391-11ea-9a31-31b5422134c7.png)
> Are you saying this? In <style></style>?
> There is no problem before. The problem is that the style="" in the
> 
> tag has no IntelliSense

I mean that only Emmet IntelliSense is currently provided

![image](https://user-images.githubusercontent.com/52478109/92717188-64321500-f392-11ea-9560-03a676b3f30b.png)

**Comment by cereschen** [comment]
This is how Emmet behaves in <style></style>, you can try it

**Comment by snoopy83101** [comment]
> This is how Emmet behaves in <style></style>, you can try it

I think I understand, thank you very much!

**Comment by cereschen** [comment]
> > This is how Emmet behaves in <style></style>, you can try it
> 
> I think I understand, thank you very much!

If  we want template to behave like HTML, need to add extra dependencies, if only for style.not worth.
So, get used to Emmet, which is short and efficient
