### ISSUE TITLE
[Suggestion]: separate vetur server to a standalone package

### ISSUE THREAD

**Issue by HerringtonDarkholme** [vuejs/vetur#168]
Vetur is a great vscode plugin. And its implementation has already in par with language server protocol.

It would be even greater if server code can be separated into a standalone package so other editor users can share this great language service via language service client.

**Comment by octref** [comment]
Never really took time to move stuff to [vls](https://github.com/octref/vls).

Will look into doing it while doing #145 this weekend.

**Comment by HerringtonDarkholme** [comment]
Hi @octref . I have extracted vetur server into a separate repo. 

https://github.com/HerringtonDarkholme/vue-language-server

Is this fine?

**Comment by octref** [comment]
That's fine, but I'm wondering how you are gonna update it as I update the code for the server.

Now after a while I think I should just close the repo https://github.com/octref/vls and merge it back to vetur, so I can deal with all issues at the same place.
Meanwhile I'll keep all language server in `/server` and find a way to distribute it.

**Comment by octref** [comment]
I deprecated vls and put the code under `/server`.
The main reason is for vetur to do template IntelliSense / type check etc, it's much easier to just put html/js mode together.
I'm thinking the best way to let vetur's LS reused by other editors is to put https://github.com/octref/vetur/blob/master/server/src/htmlServerMain.ts#L148-L254 as a module.

**Comment by HerringtonDarkholme** [comment]
I finally decided to fork out vetur server. Some progress here:

1. enabled `strict` type checking so the code itself is more robust
2. fixed test case and improved test infra, now mocha is with source map support
3. Vue component tag and attribute documentation is added

**Comment by HerringtonDarkholme** [comment]
I have tried to use a local version of vue language server instead of packaged one, after a little change in client.

```ts
    var serverOptions = {
        run: { command: "vls" } // suppose vls starts server
    };
```

It seems to work well. For example, new added tag hover info is displayed seamlessly.
<img width="1038" alt="screen shot 2017-06-07 at 6 01 29 pm" src="https://user-images.githubusercontent.com/2883231/26873132-5f21dace-4bab-11e7-9e31-162c82fbda60.png">

Would it be an option that let user to configure vetur client to use local vue language server?

**Comment by octref** [comment]
I don't think that's a good idea, because then I wouldn't know the where the bugs come from.

But good job on the Stylus IntelliSense! Are you thinking about merging or just keep maintaining your fork?
