### ISSUE TITLE
ability to write prop documentation like JSDocs

### ISSUE THREAD

**Issue by mesqueeb** [vuejs/vetur#1692]
- [v] I have searched through existing issues
- [v] I have read through [docs](https://vuejs.github.io/vetur)
- [v] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

So I often write actual descriptions along with my props, that when I come back in a few months, I easily understand what the props do.

I was just thinking, it would be cool if there could be a standard way to add documentation / an explanation sentence to props, just like JSDocs, and then maybe vetur can show that documentation when the dev typed the prop name or when he hovers over the prop name in a template.

BTW: For now I'm using actual strings for them because I use those to generate actual JSON documentation on each component I make:
<img width="686" alt="image" src="https://user-images.githubusercontent.com/3253920/73577949-c2744c80-44c1-11ea-9991-81ef7225c9f9.png">

**Comment by octref** [comment]
You should follow up in https://github.com/vuejs/vue/issues/7186. Until we have a standardized format, there isn't much I can do. Or you can follow https://github.com/vuejs/vetur/issues/1364, which we use internally for getting descriptions bound to tag completions.
