### ISSUE TITLE
Autocomplete script

### ISSUE THREAD

**Issue by simplenotezy** [vuejs/vetur#1698]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:Mac
- Vetur version:latest
- VS Code version:latest

## Problem

When i type script then hit tab, nothing happens.

## Reproducible Case

Download vetur, go to a .vue file, type script then hit tab. I expect to see:

<script>
 export default {

 }
</script>

**Comment by octref** [comment]
Your issue is closed because you did not provide a repro case. Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.
