### ISSUE TITLE
VTI crashes with exit code 1 without any logs

### ISSUE THREAD

**Issue by ktsn** [vuejs/vetur#1699]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  macOS 10.15.3
- VTI version: 0.0.2
- VS Code version: -

## Problem

`vti diagnostics` crashes without any error logs on a larger project.
- number  of `.vue` -> 134
- number of `.ts` -> 120

<img width="617" alt="Screenshot 2020-02-09 at 4 06 48 PM" src="https://user-images.githubusercontent.com/2194624/74098810-344e3500-4b57-11ea-9a95-62058083e2b0.png">

I couldn't catch any errors even though I set `uncaughtexception` and `unhandledrejection` even in vti source.

## Reproducible Case

It's pretty hard to reproduce as it looks depends on the size of a project (maybe memory allocation related?) and the reproducible project is confidential.
I've got some memory report in the attached zip file.

https://drive.google.com/file/d/1zUKepNdxCH7Imk2zR7bHvArcGQ8MDmwn/view?usp=sharing

- `Timeline.heaptimeline` Memory allocation timeline through `vti diagnostics`
- `Snapshot1.heapsnapshot` Snapshot just after starting `vti diagnostics`
- `Snapshot2.heapsnapshot` Snapshot after 2-3 seconds of starting `vti diagnostics`
- `Snapshot3.heapsnapshot` Snapshot just before `vti diagnostics` crashes

**Comment by jackkoppa** [comment]
Hi @ktsn - I'm having the same exact experience. I adding logging & breakpoints to both `vti > cli.js`, and `vue-language-server > vls.js`, but there are no JS exceptions being thrown before it exits with `1`. In my case, for a small project, it will usually get through the 8 files that it needs to check, but fail right before the validation result is returned to `vti > cli.js` for the final file. Though there's some variation on when exactly the failure occurs, if I try the command 10 different times. And, every once in a while, it gets all the way through without errors

Will create a repro case repo

**Comment by jackkoppa** [comment]
@ktsn, @octref - this repo is a reliable reproduction on my machine. I'm under no illusions that you'll have the exact same experience on your machines, but if you have a few minutes to try, that'd be excellent. Quick repro steps from the README, that are [reliable](https://github.com/jackkoppa/vti-failures-1699/blob/master/logs/detailed_repro_logs(2.17.20).md) on my machine:

```bash
git clone https://github.com/jackkoppa/vti-failures-1699.git
cd vti-failures-1699
npm ci
npm run vti

# fails

# Now, change one of the ComplexComponent files from .vue -> .txt
# thus removing it from vti observation, and run vti again
mv src/components/ComplexComponent4.vue src/components/ComplexComponent4.txt
npm run vti

# succeeds
```

**Comment by dkonchekov** [comment]
Hi, @jackkoppa! I reproduced error on my machine with 2 more ComplexComponents (6 in total).

**Comment by dkonchekov** [comment]
Running vti with `sudo` fixes problem on my machine. @jackkoppa , @ktsn could you try?

**Comment by jackkoppa** [comment]
@dkonchekov - whoa! You're absolutely right!

I can run `sudo npm run vti` on the repo, and it worked without any issue!

Also tried `sudo npm run vti` on one of our private repos, with:
- 48 .vue files
- 32 .ts files

And had no issues, where the command had previously errored out quite quickly. Awesome!

I'm far from a process/memory allocation expert - I wonder what the best way to find the upper bound is that `sudo` is removing?

**Comment by bahek2462774** [comment]
It happens to me as well. Working fine with sudo 
`sudo npm run vti`. Otherwise, it fails.

**Comment by dkonchekov** [comment]
Here output of linux `strace vti diagnostics` in @jackkoppa repo:
1. with sudo: https://vti-1699.s3.amazonaws.com/output-sudo.txt
2. without sudo: https://vti-1699.s3.amazonaws.com/output.txt

**Comment by dkonchekov** [comment]
There is similar project https://github.com/Yuyz0112/vue-type-check that doesn't suffer this problem.

**Comment by ktsn** [comment]
Thanks @jackkoppa and @dkonchekov for providing simple reproduction and work around regarding `sudo`! I can reproduce both behavior as well. I'll take a look on the crash.

**Comment by TheBeastOfCaerbannog** [comment]
Hi! The issue was not the large projects, VTI was killed after 3s timeout on projects of any size because VS Code language server self-terminated.
I've opened a PR with a suggestion how we can fix it and more complete description of the problem. Would appreciated if someone could take a look.
