### ISSUE TITLE
Cannot find module '@/styles/variables.scss' vetur(2307)

### ISSUE THREAD

**Issue by fronterender** [vuejs/vetur#1700]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version:0.23.0
- VS Code version:1.40.1

## Problem

import variable from '@/styles/variables.scss' // the error is 'Cannot find module...... '
console.log(variable) // there is no error in the console 
but, it work normally in some projects ,I want to ignore errors through configuration，no matter how different my version is

## Reproducible Case
...

**Comment by octref** [comment]
Your issue is closed because you did not provide a repro case. Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.
