### ISSUE TITLE
Tags and Attributes descriptions are not being parsed as markdown anymore.

### ISSUE THREAD

**Issue by phiter** [vuejs/vetur#1706]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.23.0
- VS Code version: 1.42.0

## Problem

Tag and attributes auto-completions are not accepting markdown anymore.

This is possibly due to Vetur using [`MarkedString`](https://vshaxe.github.io/vscode-extern/vscode/MarkedString.html) from `vscode-languageserver-types`, in the following line:

https://github.com/vuejs/vetur/blob/73a0854b9eba3311951546a1e82a6832b523acbb/server/src/modes/template/services/htmlHover.ts#L3

This type is deprecated and [`MarkdownString`](https://vshaxe.github.io/vscode-extern/vscode/MarkdownString.html#MarkdownString) should be used instead.

## Reproducible Case

This is reproducible in any repository that has a framework with the tags and attributes provider.
Here's a screenshot of the issue that is happening: 
![image](https://user-images.githubusercontent.com/12252332/74448001-facc4100-4e58-11ea-8fb6-0ac992ad40fd.png)

**Comment by phiter** [comment]
By the way if it was possible to make the description multiline by accepting an array and breaking it into separate items (like vscode snippets) that would be cool.

**Comment by phiter** [comment]
This also fails for onsen ui which uses markdown.

https://github.com/OnsenUI/vue-onsenui-helper-json/blob/d9a293efbd2074b284c1a86a887960987af21590/vue-onsenui-tags.json#L112

![image](https://user-images.githubusercontent.com/12252332/74450815-73cd9780-4e5d-11ea-95ad-ada829e8f2c2.png)

**Comment by ChrisKader** [comment]
I am curious if this is related to the issue with .vue files in general losing intellisense (https://github.com/vuejs/vetur/issues/1509)

**Comment by phiter** [comment]
I don't know. I don't have that issue on my setup.
