### ISSUE TITLE
The Vue Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by maoxiaoquan** [vuejs/vetur#1713]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: w10
- Vetur version: v0.23.0
- VS Code version:v1.42.1
- Version: 1.42.1 (user setup)
- Commit: c47d83b293181d9be64f27ff093689e8e7aed054
- Date: 2020-02-11T14:45:59.656Z
- Electron: 6.1.6
- Chrome: 76.0.3809.146
- Node.js: 12.4.0
- V8: 7.6.303.31-electron.0
- OS: Windows_NT x64 10.0.18362

## Problem

The Vue Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

**Comment by maoxiaoquan** [comment]
Need help, it's very affecting the use

**Comment by Xi-yu** [comment]
![image](https://user-images.githubusercontent.com/35017425/74623782-eea9f180-5180-11ea-80cb-145d30e66556.png)

**Comment by maoxiaoquan** [comment]
没有作用

**Comment by rebolyte** [comment]
Related: #1348

**Comment by octref** [comment]
Please provide a repro case: https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md 
And attach errors in Output -> Vue Language Server and VS Code's Help -> Developer Tools.

**Comment by xianghongai** [comment]
#### 1、问题（示例源码在百度网盘，文后链接）

![Vetur1](https://user-images.githubusercontent.com/2075006/102572432-0cd8d900-4127-11eb-9015-9281336674dd.png)

![Vetur2](https://user-images.githubusercontent.com/2075006/102572435-119d8d00-4127-11eb-847d-05c0c8064861.png)

---

示例:

链接: [https://pan.baidu.com/s/1UHsf1_E29VPK_Ar8ZhfCRA](https://pan.baidu.com/s/1UHsf1_E29VPK_Ar8ZhfCRA)

提取码: 2b62

**Comment by yoyo930021** [comment]
@maoxiaoquan Is the problem solve?

**Comment by maoxiaoquan** [comment]
> @maoxiaoquan Is your problem solved?

I changed my computer, and the reinstalled plug-in does not have this problem. I forgot to close this problem.

**Comment by xianghongai** [comment]
Is that closed? Also 👍?
Re-create another Issue for this issue?
One issue for one developer?
Or is the same Problem an Issue?

![2020-12-22-173036](https://user-images.githubusercontent.com/2075006/102872955-6c165080-447b-11eb-8172-c9bbef7ee804.png)

**Comment by yoyo930021** [comment]
> Is that closed? Also 👍?
> Re-create another Issue for this issue?
> One issue for one developer?
> Or is the same Problem an Issue?
> 
> ![2020-12-22-173036](https://user-images.githubusercontent.com/2075006/102872955-6c165080-447b-11eb-8172-c9bbef7ee804.png)

Open a new issue for your problem,
And your link is 404.

**Comment by maersk96** [comment]
I fixed it like this:

1. Uninstall Vetur
2. Restart (not just reload) VS Code
3. Reinstall Vetur

**Comment by emkis** [comment]
I fixed just changing the Vetur version to `v0.31.3`

**Comment by yoyo930021** [comment]
Vetur crashing have many probably reasons.
Everyone may have different reasons when crashing.
So if anyone's Vetur crash, I suggest to open a new issue for follow.

The computer science is difficult.
We only can fix it case by case.

This issue is locked.
