### ISSUE TITLE
intellisense and auto completion not working when write sfc file with ts class

### ISSUE THREAD

**Issue by xpuliapushi** [vuejs/vetur#1718]
- [ ✔] I have searched through existing issues
- [ ✔] I have read through [docs](https://vuejs.github.io/vetur)
- [ ✔] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:Win10 x64
- Vetur version:-0.23.0
- VS Code version:1.42.1

## Problem

i use sfc component file with script lang="ts" to write my codes
but none of auto completion or intellisense are working, i dont konw whats going on
please help

## Reproducible Case
my extensions : “eslint”, "tslint", "prettier", "vetur"
setting.json : {}

`<script` lang="ts">
import { Component, Vue} from 'vue-property-decorator';

@Component
export default class extends Vue {
}
</script>

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/75491691-309a1b00-596b-11ea-95d7-2fc76da64a07.png)

From what I see, you need to have capital `C`.
