### ISSUE TITLE
Couldn't save code

### ISSUE THREAD

**Issue by XuZhaoTong** [vuejs/vetur#1721]
## Info

- Platform: Win10
- Vetur version:0.23.0
- VS Code version:1.42.1

## Problem

Every time I save, it appears as shown in the figure, which prevents me from saving the code：Running Save Participants for 'xxxx': Quick Fixes
![image](https://user-images.githubusercontent.com/32711995/75009660-292fc900-54b6-11ea-8385-9e78d57b5766.png)

**Comment by MarvinRudolph** [comment]
Same here. I'm using TypeScript 3.7.5 and tried to downgrade but doesn't seem to work. Had to deactivate the extension completely for now. :/

**Comment by XuZhaoTong** [comment]
> Same here. I'm using TypeScript 3.7.5 and tried to downgrade Vetur but doesn't seem to work. Had to deactivate the extension completely for now. :/
I didn't use TypeScript, but it was the same.I'm sure it's a matter of the Veter.

**Comment by vkboo** [comment]
I have exactly the same problem. I don't know if it has something to do with my binding Eslint automatic formatting code. I hope the government will reply earlier.

**Comment by 312307025** [comment]
I have the same problem
I'll try to press F1 and then 'restart extension host'
This can be saved. You can try it

**Comment by XuZhaoTong** [comment]
> I have the same problem
> I'll try to press F1 and then 'restart extension host'
> This can be saved. You can try it

Nice!Such a good idea

**Comment by octref** [comment]
If you disable ESLint extension this shouldn't happen. So it's an ESLint extension issue, not Vetur's issue. Please follow: https://github.com/microsoft/vscode-eslint/issues/904

**Comment by webdevnerdstuff** [comment]
@octref I have disabled all extensions except for Vetur, and the problem is still happening. To be honest I think this is a VSCode bug as many extensions seem to be having this issue. The problematic thing is the stupid @vscodebot bot keeps closing all new issues related to this.
