### ISSUE TITLE
Show ts problems as warnings instead of errors

### ISSUE THREAD

**Issue by chavlji** [vuejs/vetur#1722]
There should be an option to show Vetur's ts errors as less problematic linting warnings.

It's not ok, that typescript error has same color as js parsing error. With the later app will not run, while first is in a lot of cases just a warning something might not be ok...

EsLint warnings are colored (underlined) in yellow for example.

**Comment by octref** [comment]
TS don't support that: https://github.com/Microsoft/TypeScript/issues/13408

**Comment by octref** [comment]
Nevertheless I made a commit so if TS supports it in the future we can benefit automatically.

**Comment by chavlji** [comment]
Could you please explain a bit why TS should support that? I thought this extension works as a bridge between LSP (language server protocol) and VSCode. So that when it gets an error from LSP it tells VSCode where and what warning to show?
I'm considering modifying just my version if it would anyhow be doable...
