### ISSUE TITLE
template lang=pug is being treated like html (pug isn't working)

### ISSUE THREAD

**Issue by mark-hahn** [vuejs/vetur#1723]
- [x ] I have searched through existing issues
- [x ] I have read through [docs](https://vuejs.github.io/vetur)
- [x ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.23.0
- VS Code version: 1.42.1

## Problem

Pug highlighting and commenting don't work in the `<template lang=pug>` section of my SFC files.   It is all black and when I use `ctrl-/` it inserts html comments.

Is there something I need to do to enable it?

## Reproducible Case

Sorry, it just never works for me.

**Comment by octref** [comment]
`<template lang="pug">`.
