### ISSUE TITLE
the css user snippets for emmet in *.vue file not works

### ISSUE THREAD

**Issue by onezhaoyn** [vuejs/vetur#1724]
the css emmet expansion in *.vue file works perfectly!
But the user CSS snippets for emmet in *.vue file not working ( user HTML snippets works fine!)
Could you please have a look?

i define a css snippet:
 ![image1](https://tva1.sinaimg.cn/large/0082zybpgy1gc6p5gxokdj307u02r0sn.jpg)

it works fine in *.styl file:
 ![image1](https://tva1.sinaimg.cn/large/0082zybpgy1gc6p5njcmsj30fh03xdfv.jpg)

but the user snippets now shown in *.vue file:
 ![image1](https://tva1.sinaimg.cn/large/0082zybpgy1gc6p5rnubij308m03fdft.jpg)

_Originally posted by @onezhaoyn in https://github.com/vuejs/vetur/issues/232#issuecomment-590073995_

**Comment by octref** [comment]
CSS snippets aren't used in Vue files. You need to define Stylus snippets.
