### ISSUE TITLE
The Vue language server often suspends

### ISSUE THREAD

**Issue by zhkkjun** [vuejs/vetur#1725]
## Info

- Platform: Win10
- Vetur version: 0.23.0
- VS Code version: 1.42.1 (user setup)

## Problem
There is nothing in  "Vue Language Server"
Poor English, the following is from Google Translate：
The Vue language server often suspends, which occupies a core resource of the CPU when suspended. Once suspended, it can only be resolved by restarting. Guess conflicts with ESLint.
![image](https://user-images.githubusercontent.com/50400973/75127990-f1669280-56fc-11ea-85ce-ed0de21dc0ef.png)

Vue语言服务器会经常挂起，挂起时占满CPU一个核心的资源，一旦挂起只能重启才能解决，猜测和ESLint有冲突。

## Reproducible Case
Usually appears when writing * .vue | * .js files
一般在写*.vue|*.js文件时会出现

**Comment by zhkkjun** [comment]
This problem does not seem to happen in the previous version of Vetur
这个问题似乎不会在Vetur上一个版本出现

**Comment by octref** [comment]
Are you running into ESLint's save participant issue? #1724 
Does disabling ESLint fix the issue for you?

**Comment by zhkkjun** [comment]
I think it has been fixed
