### ISSUE TITLE
Validate ts/js on manually on key shortcut

### ISSUE THREAD

**Issue by chavlji** [vuejs/vetur#1731]
- Vetur version: 0.23.0
- VSCode Version: 1.43.0-insider
- OS Version: Darwin x64 19.3.0 (OsX Catalina 10.15.3)

## Problem

Intellisense popup is a bit slow (2-3 seconds) if i have `vetur.validation.script` on.

It would be nice if I could disable `vetur.validation.script: false` and use key shortcut to manually run js/ts validation.

Could you add an action to manually run js/ts validation?

**Comment by octref** [comment]
I won't likely do that, but if you can include a profile I can look into the slow intellisense. https://github.com/vuejs/vetur/blob/master/.github/PERF_ISSUE.md

**Comment by octref** [comment]
> Could you add an action to manually run js/ts validation?

We won't do that. We'll try to fix by improving the performance. If you have a profile for slowness, please open a new issue.
