### ISSUE TITLE
VTI Error: Cannot find module

### ISSUE THREAD

**Issue by odanado** [vuejs/vetur#1732]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Node: 12.14.0
- vti: 0.0.2

## Problem
I get an error when I run `vti`.
`Error: Cannot find module 'vscode-css-languageservice/lib/umd/data/browsers'`

## Reproducible Case
reproduction repository: https://github.com/odan-sandbox/vti-error-reproduction

**Comment by ApplicationDeveloper** [comment]
try this fix https://github.com/vuejs/vetur/pull/1730

**Comment by patrick-ebot7** [comment]
> try this fix #1730

Tried this fix, but it isn't working for me. I get almost the same error `Error: Cannot find module 'vscode-css-languageservice/lib/umd/data/webCustomData'`

**Comment by odanado** [comment]
Thanks!

I checked a version of `vscode-css-languageservice`. As a result of the version is 4.1.0.

```bash
$ yarn why vscode-css-languageservice
=> Found "vscode-css-languageservice@4.1.0"
info Reasons this module exists
   - "vti#vue-language-server" depends on it
   - Hoisted from "vti#vue-language-server#vscode-css-languageservice"
```

When I fixed to 4.0.2 a version of `vscode-css-languageservice`, `vti` command was succeeded.
https://github.com/odan-sandbox/vti-error-reproduction/pull/1/files

**Comment by selfagency** [comment]
I'm having this issue too.

**Comment by weilbith** [comment]
When is the next release planned to include this fix?

**Comment by selfagency** [comment]
@weilbith I'm no longer having this issue myself so I believe it's been fixed.

**Comment by weilbith** [comment]
Hmm I had. So could only solve it by manually downgrading the vscode... dependency locally.
The linked fix was merged to `master` in march, while the latest npm release was 4 months ago.

**Comment by badbabykosh** [comment]
This is still a problem
