### ISSUE TITLE
最新版有问题

### ISSUE THREAD

**Issue by Alson3364** [vuejs/vetur#1735]
更新到最新版后，在vscode里使用会对vue文件报错，每次报错都会出现错误提示，并且无法保存，需要点击取消才可以，现在已经恢复都上一个版本，就不会有个问题，可以自己去试一下看是怎么回事

**Comment by octref** [comment]
Please use English and include repro case.

Your issue is closed because you did not provide a repro case. Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.
