### ISSUE TITLE
Doesn't recognize new properties in Typescript SFCs.

### ISSUE THREAD

**Issue by alimoabd2127** [vuejs/vetur#1738]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win/Linux
- Vetur version: 0.23.0
- VS Code version: 1.42.1

## Problem
Vetur doesn't recognize new lifecycle hooks from plugins like vue-socket.io, vue-socket.io-extended when using Typescript.

![image](https://user-images.githubusercontent.com/9029695/75619858-4b2ce980-5b4f-11ea-947c-044a930feb10.png)
This code compiles just fine and produces no errors even though Vetur says that it cannot find the overload.
![image](https://user-images.githubusercontent.com/9029695/75619862-5849d880-5b4f-11ea-9e8c-f9c77a0abbe2.png)
![image](https://user-images.githubusercontent.com/9029695/75619882-8c24fe00-5b4f-11ea-8cc2-b46488cb9ec2.png)

## Reproducible Case
Install vue-socket.io/vue-socket.io-extended as well as typescript.
Add vue-socket.io to a plugin file.
Try to use socket: {} property in a SFC with `script lang="ts"`.

**Comment by ktsn** [comment]
This kind of error likely not a vetur issue but library does not provide typings or wrong tsconfig config. If you are sure this is Vetur issue, please provide a minimal and self-contained reproduction as example GitHub repo etc.

**Comment by octref** [comment]
Your issue is closed because you did not provide a repro case. Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.
