### ISSUE TITLE
auto format of a multiline ternary operator with return is broken 

### ISSUE THREAD

**Issue by maratumba** [vuejs/vetur#1739]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOs
- Vetur version: 0.23.0
- VS Code version: 1.42.1

## Problem
when auto formatting, the following statement
```js
avatarStyle() {
      return this.small ?
        {
          width: "5px !important",
          height: "25px !important"
        }
        : {};
    }
```
is transformed into this:
```js
avatarStyle() {
      return this.small
        ? {
            width: "5px !important",
            height: "25px !important"
          }
        : {};
    }
```
which changes the logic (and returns `this.small` in this case instead of the style object)
## Reproducible Case
Apply auto formatting the above code in a vue single component file.

**Comment by ktsn** [comment]
Well, it does not change the logic...?

**Comment by maratumba** [comment]
Umm, it does?

From [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/return):

> ### Automatic Semicolon Insertion
> 
> The return statement is affected by automatic semicolon insertion (ASI). No line terminator is allowed between the return keyword and the expression.
> ```js
> return
> a + b;
> ```
> is transformed by ASI into:
> ```js
> return; 
> a + b;
> ```
> The console will warn "unreachable code after return statement".

**Comment by ktsn** [comment]
Well, it is you have no expression after `return`, in your case you have `this.small`. Did you try to run your code?

**Comment by maratumba** [comment]
Well, now it works either way. I guess it was some other problem. Sorry for bothering.
