### ISSUE TITLE
Duplicate identifier '"keydown"' error when using multiple keydown events

### ISSUE THREAD

**Issue by victorgarciaesgi** [vuejs/vetur#1745]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOs
- Vetur version:10.15.3
- VS Code version: 1.42.1

## Problem

I have this code:

![image](https://user-images.githubusercontent.com/15092120/75684305-d5349980-5c98-11ea-8e24-683d6f957acc.png)

With `vetur.experimental.templateInterpolationService` set to true, the TS virtual file will think that I have duplicate identifiers whereas this code is valid Vue template code

![image](https://user-images.githubusercontent.com/15092120/75684430-162cae00-5c99-11ea-9fa7-c90b83c0518d.png)

To reproduce simply rewrite this code to any template

```vue
<template>
<input
 @keydown.down.up.prevent.stop="updateSelectedResult"
 @keydown.esc.prevent="handleEchap"
 @keydown.enter.prevent="handleEnter"
/>
</template>
```

**Comment by stuffinator** [comment]
Any news on this?

**Comment by DavudSafarli** [comment]
![image](https://user-images.githubusercontent.com/43086951/94394604-cbabdb00-016e-11eb-8fed-9a847bb5a62b.png)
Isn't there any solution yet?
