### ISSUE TITLE
Running Save Participants

### ISSUE THREAD

**Issue by webdevnerdstuff** [vuejs/vetur#1746]
- [x ] I have searched through existing issues
- [x ] I have read through [docs](https://vuejs.github.io/vetur)
- [x ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.23.0
- VS Code version: 1.42.1

## Problem

When saving a vue file, the file either will not save or takes a long time saving and the following message pops up:

``` Running Save Participants for 'File.vue': Quick Fixes ```

I have tested this with all extension disabled globally (not just workspace). I went though each individual extension to test it (which was painful), and Vetur was the only one causing this problem. 

I have also searched the VSCode Issues and it seems a lot of people are having the "Running Save Participants" problem and some are reporting other extensions are having this problem as well, but for me it seems to be this extension specifically.

I then checked with one of my co-worker who also uses the same tools as I do. He does not have this problem. The only difference is the VS Code version he is using. 

My Co-workers info
- Platform: Win & MacOS (same versions on both)
- Vetur version: 0.23.0
- VS Code version: 1.41.1

Then I checked with another co-worker. He's on the same versions as I am, and he hasn't seen the problem. So I have no clue wtf is the problem anymore.

So perhaps an issue with Vetur the latest VS Code version. But again, I have seen others reporting issues with other extensions causing this problem. I will be submitting a ticket to VS Code as well.

## Reproducible Case

1. Open vue file.
2. Save file
3. Notice that the "Running Save Participants" pops up and file takes a long time to save.

**Comment by webdevnerdstuff** [comment]
From my VS Code ticket, VS Code 1.43 endgame should be released in a few days. Hopefully that will resolve whatever the issue might be.

Here is my other ticket just in case you want to follow it as well. https://github.com/microsoft/vscode/issues/91916

**Comment by webdevnerdstuff** [comment]
Also good to note. This next release should help to discover exactly what extensions may be causing the issue.

https://github.com/microsoft/vscode/issues/90851#issuecomment-589681352

**Comment by JoelFeiner** [comment]
That dialog isn't the problem. It's just showing that Vetur is taking a long time to do it's post-save work. I've been having really high CPU usage and long save times as well.

Before the dialog, VSCode would time out on saving (configurable). The dialog made it so that plugins could take as long as they wanted to do their thing. I suspect people are just now seeing that plugins are slow sometimes, when it was hidden before.

**Comment by octref** [comment]
The same participant comes from ESLint, not Vetur. If you disable ESLint extension and this still happens, feel free to reopen. https://github.com/microsoft/vscode-eslint/issues/904

**Comment by webdevnerdstuff** [comment]
@octref I already stated in my initial posting that I had ALL extensions disabled, with only Vetur on and it was still happening. I'm not sure why you closed this.

**Comment by octref** [comment]
Sorry, I didn't realize, I thought it's the same issue as the other one.
Does this make the bug go away temporarily?

```json
  "editor.codeActionsOnSave": {
    "source.fixAll": false,
    "source.organizeImports": false
  }
```

**Comment by webdevnerdstuff** [comment]
Just tried it out. First disabled all extensions and enabled Vetur. Doesn't seem to be happening now. So I turned everything on and it seems to happen less than it was before I think, but still happens occasionally from me saving and changing things like crazy trying to trigger it.

Before I did have `"source.fixAll.eslint": true,` with `"editor.codeActionsOnSave"`, maybe that's conflicting with it a little bit. Not sure. 

But so far so good. I've been messing with things for a bit now and haven't seen the error message. Thank you for the help, I really didn't want to have to live without this extension, even for a few days! lol :)

**Comment by webdevnerdstuff** [comment]
Like clockwork. As soon as I am done screwing around testing things... it started happening again. *facepalm. So, I guess I'll test some more when I have some more time.

**Comment by JoelFeiner** [comment]
I'm still seeing this issue even in 0.24.0. I've disable eslint and tslint vue and I still get high CPU usage after some time. The only plugin that VSCode says it is waiting on is Vetur. Also the Vue language server node process uses a lot of CPU, and no others do.

**Comment by Floriskoch** [comment]
I'm having the same issue. It seems like it happens most often with Vue components close to the root of the app (App.vue, and other near-root level components).

**Comment by JoelFeiner** [comment]
This remains a huge issue. I made a couple line changes in one of my Vue files and it took 3-5 minutes for it to run all the save participants. That's essentially unusable.
