### ISSUE TITLE
import { map, filter, intersection } from 'lodash'`  shows the warning: "node_modules/lodash/lodash.js' is not a module.Vetur(2306)"

### ISSUE THREAD

**Issue by qiulang** [vuejs/vetur#1747]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.23
- VS Code version: 1.42.1

## Problem
`import { map, filter, intersection } from 'lodash'`  shows the warning: "node_modules/lodash/lodash.js' is not a module.Vetur(2306)"

<img width="846" alt="lodash" src="https://user-images.githubusercontent.com/516243/75739612-4d09cf00-5d40-11ea-80b8-05cf37a7183f.png">

This is my jsconfig.json 

```
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "@/*": ["src/*"]
        },
        "checkJs": true
    },
    "include": ["./src/**/*"],
    "exclude": ["node_modules", "**/node_modules/*"]
}

```

How do I fix it ?

Thanks!

**Comment by F0rsaken** [comment]
Try and install `@types/lodash`
Using npm: ```npm install -D @types/lodash```
Using yarn: ```yarn add -D @types/lodash```

**Comment by yoyo930021** [comment]
Try to add `esModuleInterop` in jsconfig.json     compiler options?

**Comment by octref** [comment]
This does not reproduce for me on https://github.com/octref/veturpack/blob/master/client/components/Counter.vue

Please provide a reproducible sample.
