### ISSUE TITLE
Windows Intellisense broken, endless intializing js/ts language features, high cpu

### ISSUE THREAD

**Issue by johannes-z** [vuejs/vetur#1748]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows
- Vetur version: 0.23.0 (8dce2b7b2461c59678a6df41cae07004a934e510)
- VS Code version: 1.42.1

## Problem

I have a yarn monorepo, that can't "Initializing JS/TS language features". Other projects work, and if I disable the vetur extension, it works again. Generally, vetur stopped working since 0.23.0.

You can find the project here: https://github.com/johannes-z/office-fabric

Also, there seems to be some kind of endless loop, because 1 core is at 100% all the time when I have vetur 0.23 installed...

## Reproducible Case

Checkout my project, run `yarn`, open any `.vue` file and test intellisense. Doesn't work on windows (haven't tried other OSs).

**Comment by Niekvdm** [comment]
This is due to an error in Windows path resolving in Typescript 3.7.3. Please enable useWorkspaceDependencies with a higher typescript version or upgrade to Vetur 0.24.0 which includes the proper fixes and upgrades,

**Comment by octref** [comment]
What @Niekvdm said. If you still have this issue in 0.24.0 feel free to reopen.
