### ISSUE TITLE
'require(someDynamicVariable)' can't use webpack ?

### ISSUE THREAD

**Issue by pagnkelly** [vuejs/vetur#1749]
我在尝试把vetur改成webpack，想使包的大小小一些
然而存在很多问题 Critical dependency: the request of a dependency is an expression
我想是因为存在太多动态引用导致的
我尝试externals来解决
但是太多的引用让我崩溃
想知道有什么方法可以让包大小小一些
虽然vetur貌似也没有解决

**Comment by octref** [comment]
Please use English for issues.
