### ISSUE TITLE
$refs of ref... Property '$refs' does not exist on type 'Element'.

### ISSUE THREAD

**Issue by tobiasfeil** [vuejs/vetur#1754]
vscode 1.42.1, vetur 0.24.0, ubuntu 19.10
![image](https://user-images.githubusercontent.com/17533713/75986943-466d8a00-5eef-11ea-97d4-802dd517a72e.png)
![Screenshot from 2020-03-05 14-41-02](https://user-images.githubusercontent.com/17533713/75987035-77e65580-5eef-11ea-9786-be7b41c63d91.png)

But the application works as intended

**Comment by ktsn** [comment]
It is intensional behavior and not related to Vetur as the `$refs` type is just defined like that. As `$refs` items can be anythings (HTMLElement, Vue component...), you need to manually cast it.

```ts
const contact = this.$refs.contact as any
contact.$refs.emailField.focus()
```

**Comment by Dailenis** [comment]
> It is intensional behavior and not related to Vetur as the `$refs` type is just defined like that. As `$refs` items can be anythings (HTMLElement, Vue component...), you need to manually cast it.
> 
> ```ts
> const contact = this.$refs.contact as any
> contact.$refs.emailField.focus()
> ```

Thanks, you save my day
