### ISSUE TITLE
Object possibly undefined

### ISSUE THREAD

**Issue by NicoAiko** [vuejs/vetur#1755]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.24.0
- VS Code version: 1.42.1

## Problem

Error: 2532
Even though I checked in before, if `idx` is undefined or not, Vetur doesn't recognize that.

![Bildschirmfoto 2020-03-06 um 11 15 01](https://user-images.githubusercontent.com/22343587/76074756-234ce400-5f9c-11ea-8f08-fdefafb82a6f.png)

## Reproducible Case

Test this kind of function in a `.ts` file and in a `.vue` file.
In the `.ts` file, there is no error being thrown, in the `.vue` file, there is.
```ts
function test(idx?: number) {
  const idxDefined = idx !== undefined;

  if (idxDefined && idx >= 0) {
    // idx being 'possibly undefined' for Vetur
    // and no error or whatever for regular TS
  }
}
```

![Bildschirmfoto 2020-03-06 um 11 19 27](https://user-images.githubusercontent.com/22343587/76074908-5db68100-5f9c-11ea-9b25-9f65f8fdaa39.png)

**Comment by ktsn** [comment]
It will be an error even in TypeScript.
https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABFApgZygChgEwB4D8AXImCALYBGKATgJSIDeAUIohAhorngCIrAYYFDkQBebvkQBCMRPA4BQkQG5mrbsETZ8-QcNEAyQ5LyIAfBIAMDFmzYB6B6cTUhAc0QByAA5w0aDCUADYAnogKSgZeiMBwNIgAaihQIDQajs4AhmCiYHCItDTxiCUA7gAWWagAbrSxJTQo7iDBWQkAKgDKGgC+zL1AA

**Comment by NicoAiko** [comment]
That's interesting.
Did you try it in VSCode?

**Comment by ktsn** [comment]
Yes I did. The same result.

**Comment by NicoAiko** [comment]
That's even more interesting...
It doesn't error on my machine.

I'm confused...

**Comment by NicoAiko** [comment]
It might be my VSCode being strange here... 
Let's close this.
