### ISSUE TITLE
[Question/FeatureRequest] How is prettier used?

### ISSUE THREAD

**Issue by ThaDaVos** [vuejs/vetur#1756]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version: Latest
- VS Code version: Latest

## Problem

It seems that Vetur is not using prettier completely, my prettier is set to use the `.editorconfig` file, as Vetur doesn't support it, but it still seems to not follow it. A .prettierrc does work, so, does Vetur parse it itself, or does it just call Prettier. If the latter is the case, then I'll have to open an issue on their github.

## Reproducible Case
Place an .editorconfig file in your repo and see it not being followed by Vetur...

**Comment by octref** [comment]
Please read this section:

https://vuejs.github.io/vetur/formatting.html
