### ISSUE TITLE
can i set  vetur follow eslint's rules about vue/html-self-closing ?

### ISSUE THREAD

**Issue by ehnote** [vuejs/vetur#1771]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: win10
- Vetur version: 0.24.0
- VS Code version: 1.42.1

## Problem
vetur's html-self-closing ruler didn't match eslint and eslint-loader , how can i change it to the same as eslint? 

my eslint ruler:
'vue/html-self-closing': ["error",{
      "html": {
        "void": "never",
        "normal": "any",
        "component": "any"
      },
      "svg": "always",
      "math": "always"
    }],

**Comment by octref** [comment]
https://vuejs.github.io/vetur/linting-error.html
