### ISSUE TITLE
Tags attributes not working for PascalCase

### ISSUE THREAD

**Issue by philfontaine** [vuejs/vetur#1773]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version: 0.24.0
- VS Code version: 

## Problem

I have noticed that the [framework support for tags](https://vuejs.github.io/vetur/framework.html#usage) only seems to cover kebab-case . I tried adding adding PascalCase support to quasar (https://github.com/quasarframework/quasar/issues/6600). The tags suggestion is working as expected, but the attributes are not available. 

EDIT: Remove now irrelevant information

**Comment by philfontaine** [comment]
The change was introduced here https://github.com/vuejs/vetur/commit/bded7621ce2ff3c3f10b908ad4032b6e44249382.

When I undo those changes, PascalCase tags are working correctly.

**Comment by philfontaine** [comment]
It looks like it is handled here https://github.com/vuejs/vetur/blob/master/server/src/modes/template/tagProviders/componentInfoTagProvider.ts#L32, but it is not handled for external tags.

**Comment by philfontaine** [comment]
@octref This seems to be fixed now, but this issue was not closed or linked in the change log.

**Comment by yoyo930021** [comment]
Fixed in #2056

**Comment by yoyo930021** [comment]
Thanks for reminding.
