### ISSUE TITLE
Code completion inside <template> does not work

### ISSUE THREAD

**Issue by tobidalhof** [vuejs/vetur#1774]
## Info

Vetur version: 0.24.0

VSCode
Version: 1.43.0 (user setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

## Problem

Code completion inside `<template>` does not work
https://streamable.com/um4fo

**Comment by om26er** [comment]
I confirm the issue, though not really sure if that was ever implemented ?

**Comment by F0rsaken** [comment]
probably @ktsn will know it, but I think it only works if you have set `vetur.experimental.templateInterpolationService` set tu `true` in your settings

**Comment by om26er** [comment]
> probably @ktsn would know it, but I think it only works if you have set `vetur.experimental.templateInterpolationService` set tu `true` in your settings

I tried that, both at workspace and User level and it doesn't seem to do anything. Wonder if that is a new regression or something ?

**Comment by om26er** [comment]
There seems to be something wrong with the <template> tag there.
![code](https://user-images.githubusercontent.com/6350837/76653047-bc29c380-6589-11ea-90b2-260c6245e309.png)

**Comment by om26er** [comment]
```
Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:44:52.965Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-14-generic snap
```

**Comment by tobidalhof** [comment]
> I confirm the issue, though not really sure if that was ever implemented ?

It definently worked a few days ago. Tried VS Code release of January and vetur v0.23.0 but no luck

**Comment by F0rsaken** [comment]
> There seems to be something wrong with the tag there.
> ![code](https://user-images.githubusercontent.com/6350837/76653047-bc29c380-6589-11ea-90b2-260c6245e309.png)

Can you paste script part of code?

**Comment by ktsn** [comment]
@tobidalhof Please provide a reproduction to confirm (e.g. example GitHub project)
See: https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md

@om26er You issue looks different from OP. Please open a new issue with a reproduction.

**Comment by tobidalhof** [comment]
> @tobidalhof Please provide a reproduction to confirm (e.g. example GitHub project)

Created https://github.com/tobidalhof/vetur-issue with vue cli (typescript). Please also see https://github.com/tobidalhof/vetur-issue

**Comment by tobidalhof** [comment]
@F0rsaken THANKS! `vetur.experimental.templateInterpolationService` to `true` actually worked. But not sure why it worked before then
