### ISSUE TITLE
no props completion when child component `export default {}` ends with `;`

### ISSUE THREAD

**Issue by F0rsaken** [vuejs/vetur#1775]
- [ * ] I have searched through existing issues
- [ * ] I have read through [docs](https://vuejs.github.io/vetur)
- [ * ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.24.0
- VS Code version: 1.43.0

## Problem

There is no prop suggestion on child components.
![image](https://user-images.githubusercontent.com/21238469/76652421-dd2ced00-6566-11ea-9e61-037aef3c6bf7.png)

![image](https://user-images.githubusercontent.com/21238469/76652469-ef0e9000-6566-11ea-9dd3-7533814a2ec4.png)

And it happens in every component, it's not just that one.

## Reproducible Case

It happens in every my project, event the newly created ones.

**Comment by yoyo930021** [comment]
Please provide reproducible project.

**Comment by rchl** [comment]
Does vetur even claims to provide such feature?
I admit I'm using vetur in Sublime Text (in JS codebase) so maybe I'm not seeing all functionalities but I never saw it working.

**Comment by yoyo930021** [comment]
![Screen Shot 2020-03-17 at 8 34 30 PM](https://user-images.githubusercontent.com/9126398/76856689-bcc6a080-688e-11ea-8a06-0d5de9983778.png)

https://github.com/vuejs/vetur/blob/master/CHANGELOG.md#child-component-completion

If you set `tsconfig.json` for alias path?

**Comment by rchl** [comment]
Alright, nice :)
Sublime's version is not up to date.

**Comment by F0rsaken** [comment]
@yoyo930021 I made 2 repos: first as a fork from Veturpack: https://github.com/F0rsaken/veturpack

and second using newest `@vue/cli` with JS:  https://github.com/F0rsaken/vue-js-test

In the first, made with Veturpack, props suggestion worked, but in the second one, made with `@vue/cli` not.
If you can download them and check, that would be great!

**Comment by yoyo930021** [comment]
The reason is very easy.
When the child component doesn't end of `export default {}`, Vetur parse error.
Include the end of `;`.

**Comment by F0rsaken** [comment]
wow, in my whole life, I would never guessed it!

But that's only semicolons, syntax like this:
![image](https://user-images.githubusercontent.com/21238469/77041965-28a62780-69bb-11ea-8532-f1c20d8d42b7.png)
actually works

Thanks, @yoyo930021 ! 😅 

Just out of curiosity, is there a code doc's of Vetur to help contributors? Or I just have to go over code and try to understand it?

**Comment by yoyo930021** [comment]
You can refer:
- Vetur:
  - https://github.com/vuejs/vetur/blob/master/.github/CONTRIBUTING.md
- LSP:
  - https://microsoft.github.io/language-server-protocol/
- LSP node implementation:
  - https://github.com/microsoft/vscode-languageserver-node
- Typescript:
  - https://github.com/microsoft/TypeScript/wiki/Architectural-Overview
- Typescript AST:
  - https://ts-ast-viewer.com/

There are no documents in many places, especially typescript.

**Comment by F0rsaken** [comment]
wow, thanks for the materials, gonna read it later

But how you found it the issue?! VSCode Debugger?

**Comment by yoyo930021** [comment]
I researched this part when #1323, so I know the position of the code.
And  I use VSCode debugger to debug this part code.

**Comment by octref** [comment]
I renamed and reopened this issue since I can reproduce it.

**Comment by F0rsaken** [comment]
> I renamed and reopened this issue since I can reproduce it.

Sory for closing it, thought that if there is ready PR I can close it. Sory for problem

**Comment by octref** [comment]
@F0rsaken No need to be sorry. It'll be closed again soon 😉
