### ISSUE TITLE
Highlight broken after Regex

### ISSUE THREAD

**Issue by panjiangyi** [vuejs/vetur#1780]
- [x] I have searched through existing issues

## Info

- Platform: macOS
- Vetur version:V 0.24.2
- VS Code version: 1.43.0

## Problem
Vetur mixed a Regex with a method call and block comment
![image](https://user-images.githubusercontent.com/14845510/76721563-70d70700-677b-11ea-8ed8-1cd52a8daa07.png)

## Reproducible Case
```js
/someReg\//.test()
```
Vetur treat "//." in a Regex method call as a start mark of a block comment

**Comment by IWANABETHATGUY** [comment]
![image](https://user-images.githubusercontent.com/17974631/80472512-65305000-8977-11ea-891e-6adc9b323033.png)
can't reproduce at 
```
version: 1.44.2
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

**Comment by octref** [comment]
I also cannot reproduce with `/someReg\//.test()`.
