### ISSUE TITLE
Array get error type in v-for

### ISSUE THREAD

**Issue by yoyo930021** [vuejs/vetur#1790]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.24.0 (master)
- VS Code version: 1.43.0

## Problem
Wrong: `readonly never[]`
Correct: `readonly {
    id: number;
    text: string;
    list: never[];
}[]`

![Screen Shot 2020-03-17 at 2 58 44 PM](https://user-images.githubusercontent.com/9126398/76830265-ddc3cd00-685f-11ea-8a6e-2307f3d700bb.png)
![Screen Shot 2020-03-17 at 2 58 56 PM](https://user-images.githubusercontent.com/9126398/76830277-e0bebd80-685f-11ea-829b-e980de5b6897.png)

PS. show virtual file is correct.

## Reproducible Case
https://github.com/yoyo930021/vetur-int-bug/blob/master/src/components/HelloWorld.vue

**Comment by ktsn** [comment]
Hmm, that's weird. If I copy and paste the virtual code into the script block, it infers correct type.

**Comment by yoyo930021** [comment]
Really weird.

I also check about virtual code in project.
https://github.com/yoyo930021/vetur-int-bug/blob/master/src/components/Test.vue

**Comment by ktsn** [comment]
If it is with explicit interface annotation, the type will be correct:

```ts
import { defineComponent, computed } from '@vue/composition-api'

interface Group {
  id: number
  text: string
  list: string[]
}

export default defineComponent({
  setup() {
    const groups = computed<Group[]>(() => {
      const result = []
      result.push({
        id: 1,
        text: '',
        list: []
      })
      return result
    })
    return {
      groups
    }
  }
})
```

**Comment by yoyo930021** [comment]
This is also correct.
I think problem when typescript automatically infer types.

```typescript
import { defineComponent, computed } from "@vue/composition-api";

export default defineComponent({
  setup() {
    const groups = computed(() => {
      const result: { id: number, text: string, list: string[]}[] = []
      result.push({
        id: 1,
        text: '',
        list: []
      })

      return result;
    });

    return {
      groups
    };
  }
});
```

**Comment by yoyo930021** [comment]
I found the problem.
https://github.com/vuejs/vetur/blob/dcf66c49bbeb59f6485f4fa97748bbb8f8d4ca81/server/src/services/typescriptService/serviceHost.ts#L401
When `noImplicitAny: true` or remove this line, array will get correct type.

**Comment by ktsn** [comment]
Hmm, I see. I set `noImplictAny` for template service because user can write a function in template. e.g.:

```vue
<template>
  <button @click="(event) => onClick(event)">Click</button>
</template>
```

I guess we could just remove this option and filter implicit any errors out if it comes from template region.
