### ISSUE TITLE
Typescipt:Alias is not working and the location of workspace  is wrong

### ISSUE THREAD

**Issue by xingxinglieo** [vuejs/vetur#1793]
## Info

- Platform: win10
- Vetur version: 0.24.0
- VS Code version: latest

## Problems
fisrt,this workspace is clone from a vue-ts-tempalte,but it is wrong here.All imports are wrong exclude node_modules.
![image-20200320132913625](https://user-images.githubusercontent.com/48762792/77140741-84ed7200-6ab5-11ea-8ef0-d33753d29429.png)
and location of workspace  is wrong
![image-20200320135645014](https://user-images.githubusercontent.com/48762792/77140770-9b93c900-6ab5-11ea-882e-f84cc8b8257f.png)
` c:/Users/星星/Desktop/前端学习/学习node/koa/src'.  `  This path is the tsconfig-path in other workspace. It is so strange. 

I think,maybe the `ts-config` doesn't has an effect in `.vue` file.

**Comment by ktsn** [comment]
Thank you for filing the issue.
Please provide a minimal and self-contained reproduction to confirm the issue.

See: 
https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by stgogm** [comment]
Same thing happening to me but I manage to narrow the issue to particular case that is if I add the project folder to an existing Workspace then it doesn't resolves any alias and shows "cannot find module @/...". If I create a new Workspace or open the folder directly, it works as expected.

**Comment by octref** [comment]
Please provide a minimal repro case in a new issue.
