### ISSUE TITLE
Incompatible with Prettier 2.0 because of parser option babylon which has been removed (replaced by babel)

### ISSUE THREAD

**Issue by philfontaine** [vuejs/vetur#1794]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.24.0
- VS Code version:

## Problem

The parser option `babylon` has been removed in [Prettier 2.0](https://prettier.io/blog/2020/03/21/2.0.0.html#remove-deprecated-options-and-option-values-6993httpsgithubcomprettierprettierpull6993-7511httpsgithubcomprettierprettierpull7511-7533httpsgithubcomprettierprettierpull7533-7535httpsgithubcomprettierprettierpull7535-7536httpsgithubcomprettierprettierpull7536-by-fiskerhttpsgithubcomfisker)

Error message:

Prettier format failed
[Error - 10:52:04 p.m.] Couldn't resolve parser "babylon"

The fix: https://github.com/vuejs/vetur/blob/master/server/src/modes/script/javascript.ts#L484
Replace `babylon` with `babel`

## Reproducible Case

Format a Vue File using prettier 2.0

**Comment by rnenjoy** [comment]
Anyone news?

**Comment by Janther** [comment]
@rnenjoy 
This is the setting I have in my `.vscode/settings.json`
```Javascript
{
  "[vue]": {
    // Vetur uses an old version of prettier
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
}
```
This is specific enough that it doesn't mess with my other formatting options and fixes the problem with `vue` files.

**Comment by dubonzi** [comment]
> @rnenjoy
> This is the setting I have in my `.vscode/settings.json`
> 
> ```js
> {
>   "[vue]": {
>     // Vetur uses an old version of prettier
>     "editor.defaultFormatter": "esbenp.prettier-vscode"
>   }
> }
> ```
> 
> This is specific enough that it doesn't mess with my other formatting options and fixes the problem with `vue` files.

Not an option for me since that option affects the whole .vue file and I don't use prettier to format my template, only the script tag.

**Comment by rnenjoy** [comment]
For now i went into the extension code, and changed babylon to babel manually. Tell me if you guys need help which file to edit.

**Comment by Mirakurun** [comment]
@rnenjoy how do you do that?

**Comment by rnenjoy** [comment]
> @rnenjoy how do you do that?

Sorry for the delay:
Goto %USERPROFILE%\.vscode\extensions\octref.vetur-0.24.0\server\dist\modes\script\javascript.js


Change 398
const parser = scriptDoc.languageId === 'javascript' ? 'babylon' : 'typescript';
to 
const parser = scriptDoc.languageId === 'javascript' ? 'babel' : 'typescript';

**Comment by Makapashev** [comment]
@rnenjoy just add this line to your .vscode/settings.json file `"vetur.format.defaultFormatter.html": "none"` it should help you.
