### ISSUE TITLE
Object property with quotes will not show in auto complete hints

### ISSUE THREAD

**Issue by littlee** [vuejs/vetur#1804]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.24.0
- VS Code version: 1.43.1

## Problem

Object property with quotes will not show in auto complete hints

![WX20200324-173222](https://user-images.githubusercontent.com/7534668/77410551-fc910900-6df5-11ea-823d-7878f1bdf883.png)

## Reproducible Case

create a `.vue` file and a `.js` file
a.vue
```html
<template>
</template>
<script>
import a from './a';
a.
</script>
```

a.js
```
export default {
  中文: 1,
  pp: 1,
  'pp-1': 1,
  '中文-1': 1
};
```

**Comment by yoyo930021** [comment]
It's a TypeScript feature.
https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=9&pc=1#code/MYewdgzgLgBCCGIYF4YG8BQNswOSFo5QcNNcAuGARgBosdyyAmanGCAU2DIGYmcDCBaeqRgAWDAF8MGBCAB0RDEA

`-` is not a valid property name.
You can't input `a.中文-1`.

**Comment by littlee** [comment]
but it works fine inside `.js` files

<img width="707" alt="截屏2020-03-26上午12 58 48" src="https://user-images.githubusercontent.com/7534668/77564168-3d277a00-6efd-11ea-9cca-229ce260bc1d.png">

**Comment by yoyo930021** [comment]
This problem exists in almost all online editors.
XD

**Comment by kdlslyv** [comment]
Awesome @yoyo930021  - I just stumbled across the same issue in *.vue files.
In *.ts files the autocomplete of props with hyphen works too.
Thank you!
