### ISSUE TITLE
error 2551 depending on indent (and it shouldn't even occur here)

### ISSUE THREAD

**Issue by schl3ck** [vuejs/vetur#1809]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows 10 Enterprise ((1803) 64-bit
- Vetur version: 0.24.0
- VS Code version: 1.43.2

## Problem

Vetur reports the error 2551 at a position where no error is. Also this depends on the indentation of the line. The error says

```
Property 'houldError' does not exist on type 'CombinedVueInstance<{ tasks: any[]; } & { shouldError(task: any): void; errorsToo(id: any): void; noError(): void; } & Record<never, any> & Vue, object, object, object, Record<never, any>>'. Did you mean 'shouldError'? Vetur(2551)
```

![vetur-error-2551](https://user-images.githubusercontent.com/42554556/77757784-2171c000-7032-11ea-9a4b-00ad89d176b3.png)
![vetur-error-2551-2](https://user-images.githubusercontent.com/42554556/77757977-7e6d7600-7032-11ea-8b74-d91730b79447.png)

## Reproducible Case

I've created a repo that reproduces this error: https://github.com/schl3ck/vetur-error-on-different-indent

The steps are outlined in the readme of the linked repo, but are the same as these:

1. Clone the repo
2. Run `npm i`
3. Open the folder with VSCode and open the file `src/Errors.vue`
4. Wait until everything is loaded
5. Observe the error Veture(2551) on line 8 & 9 but not on line 10
6. Indent line 8 or 9 once => error still there
7. Indent same line again => error vanishes
8. Remove `(...)` from the function call on the other line => error vanishes
9. Add `()` to the function call on line 10 => error appears

**Comment by DarkLite1** [comment]
I have the exact same issue:

![image](https://user-images.githubusercontent.com/10828570/81493265-4f882800-929f-11ea-9bdb-bee0beec9291.png)

**Comment by dastrong** [comment]
having the same issue with inline functions. Happens across multiple computers

**Comment by octref** [comment]
https://github.com/vuejs/vetur/issues/1319

Please change line ending to LF to see if it goes away.
Upstream PR is https://github.com/mysticatea/vue-eslint-parser/pull/74
