### ISSUE TITLE
OUTLINE fails after VS update 1.43

### ISSUE THREAD

**Issue by ErikVerheul** [vuejs/vetur#1810]
Since Visual Studio Code version 1.43 do not show any methods etc. of my component .js files.
A file with:
**import ...
export default {
   data() {...},
   methods: {
       my methods
   }
}**
stops interpreting everything in the default object.

Before VS version all was fine. Sounds like a compatibility problem.
Hope for a fix.

Thanks, Erik

**Comment by IWANABETHATGUY** [comment]
this is not a issue related to vetur, actually it's a typescript issue

**Comment by IWANABETHATGUY** [comment]
https://github.com/vuejs/vetur/issues/1849

**Comment by IWANABETHATGUY** [comment]
you could see this issue, i think would be fixed next release

**Comment by octref** [comment]
OK, thank you. You can close your own issue as well.
