### ISSUE TITLE
False error "Type 'null' is not assignable" for Typescript code

### ISSUE THREAD

**Issue by rajinder-yadav** [vuejs/vetur#1818]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

-  Platform: Linux
-  Vetur version: 0.24.0
-  VS Code version: 1.43.0-insider

## Problem

Incorrect error for Typescript, Class properties should be 'null' assignable!

The following are valid in Typescript;

```ts
export default class App extends Vue {
  obj:object = null;
  str:string = null;
  num:number = null;
}
```

Vetur reports as error, "Type 'null' is not assignable to type X"

![e1](https://user-images.githubusercontent.com/439226/78017916-01384e80-731b-11ea-885f-92fa3923f3a7.png)

**Comment by ktsn** [comment]
It's typescript error. 
https://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBAE2AMwIYFcA28DGnUDOBcAgmGHAN4CwAUHHBAEYBWAXMy8DvALxwA7LJgDcdBgRhQ2kqAEsBAczj8hmUeMHoAtmyHamwKCq3qxtAL5A

You may want to disable `--strictNullChecks` compiler options.
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#--strictnullchecks

**Comment by rajinder-yadav** [comment]
Yes I already have strichNullChecks set to false in __tsconfig.json__, see line 6 in left pane.

Why is Vetur still reporting this as an erro? Is there some place else I need to disable strictNullChecks?

![null-check](https://user-images.githubusercontent.com/439226/78109650-9f81ee00-73c7-11ea-8475-bd328c0ef8cb.png)

**Comment by rajinder-yadav** [comment]
These seem to be a bug with VSCode, I had to close it down and re-open and the null check error is gone.
