### ISSUE TITLE
Property 'video' has no initializer and is not definitely assigned in the constructor.

### ISSUE THREAD

**Issue by rajinder-yadav** [vuejs/vetur#1819]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: 0.20.0
- VS Code version:  1.43.0-insider

## Problem

In a Typescript project, the following code reports an error, but builds and runs correctly.

```ts
  @Prop() private video: object;
```

Since a property should not be assigned a value, the above code is correct and should not report the error:

__Property 'video' has no initializer and is not definitely assigned in the constructor.__

To fix this error, I am forced to write code like this:

```ts
  @Prop() private video: object | undefined;
```

![e2](https://user-images.githubusercontent.com/439226/78021799-d7cef100-7321-11ea-887d-c610c94d1469.png)

**Comment by ktsn** [comment]
It's not Vetur issue. Please use definite assignment assertion.
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#strict-class-initialization

**Comment by rajinder-yadav** [comment]
1. TypeScript is not reporting the same error, only Vetur!
1. Also the project builds with TypeScript with no error, your link shows this to be an error.

See output below, please fix or provide configure setting to disable this check in Vetur.

![noerror](https://user-images.githubusercontent.com/439226/78108793-128a6500-73c6-11ea-97c9-356a24693ffa.png)

**Comment by rajinder-yadav** [comment]
Updated rule is tsconfig, had to shut down vscode to see that this is no longer reported by Vetur.

Thank you!

**Comment by rajinder-yadav** [comment]
FYI for anyone looking for the fix, just disable  "__strictNullChecks__" inside "__tsconfig.json__".

```json
{
  "compilerOptions": {
    "strictNullChecks": false,
```

**Comment by klesun** [comment]
But... but disabling `strictNullChecks` has so many other implications besides fixing the Vue property initialization errors... So I assume the official solution suggested by the @ktsn is to use explicit `!` exclamation mark construct on every mandatory property:
```
  @Prop({ required: true }) private video!: object;
```
