### ISSUE TITLE
Publish to Open-VSX registry

### ISSUE THREAD

**Issue by sh7dm** [vuejs/vetur#1823]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: any
- Vetur version: any
- VS Code version: any, including Theia and other compatible software

## Problem
Vetur is only present in Visual Studio marketplace, but it'll be great if it'll be published to [Open-VSX](https://open-vsx.org/), an vendor-independent extension registry for any product compatible with VS Code extensions.

**Comment by octref** [comment]
I'm not sure what that involves, but I currently don't have time to investigate this.
It seems someone else is already publishing the latest versions.

**Comment by Glandos** [comment]
I also would like to see it published to open-vsx.org, but I understand your position.

Anyway, there are two solutions:
1. Open a PR like https://github.com/open-vsx/publish-extensions/pull/166/files
2. Create your account and namespace, following https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

The second way is recommended for security reasons. But of course, the first path is working well for distributing code.

Thank you anyway for Vetur.
