### ISSUE TITLE
Intellisense highlight vue file in template section broken.

### ISSUE THREAD

**Issue by ufhy** [vuejs/vetur#1835]
- [ x ] I have searched through existing issues
- [ x ] I have read through [docs](https://vuejs.github.io/vetur)
- [ x ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  Windows 10
- Vetur version: 0.24.0
- VS Code version: 1.44.0 (system setup)
- Node.js: 12.8.1

## Problem
this is just simple component i've create
![image](https://user-images.githubusercontent.com/5884467/78977617-f9628080-7b4a-11ea-859b-0286d7a673b8.png)

![image](https://user-images.githubusercontent.com/5884467/78977758-3cbcef00-7b4b-11ea-8f68-8365d410b222.png)

**Comment by ufhy** [comment]
this is none broken code
![image](https://user-images.githubusercontent.com/5884467/78978529-82c68280-7b4c-11ea-9fb2-abc0eb0ee441.png)

**Comment by octref** [comment]
Your issue is closed because you did not provide a repro case. Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.
