### ISSUE TITLE
When will a new version of vls be published

### ISSUE THREAD

**Issue by bimbiltu** [vuejs/vetur#1840]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: WSL
- vls version: 0.2.0
- Using emacs and lsp-mode

## Problem
I'm trying to use a fresh install of vls 0.2.0 however when starting the server I see the following error:
```
Error: Failed to load plugin 'vue' declared in 'CLIOptions': Cannot find module 'eslint-plugin-vue'
```

Upon further investigation, I see this has been fixed over a month ago in https://github.com/vuejs/vetur/commit/40571f96bbe07963f5f8a2b9f2f0e08587a15ff1 but has not yet been published (see [htmlValidation.js on unpkg](https://unpkg.com/vls@0.2.0/dist/modes/template/services/htmlValidation.js). Do you have a timeline for when a new version of vls will be published? For now I just applied that change locally and everything is working fine again.

**Comment by jardakotesovec** [comment]
Also ran into month old bug which seems to fixed in master..  more frequent releases would help with these cases. Vetur is great :-).

**Comment by rchl** [comment]
@ktsn sorry for pinging but would really appreciate new release to be able to use new version in SublimeText.

**Comment by JoelFeiner** [comment]
It's been almost two months without an update, while bugs continue to pile up. Is there a fork of Vetur that is actually maintained?

**Comment by mustaqimM** [comment]
In the meantime, `yarn add eslint eslint-plugin-vue@next -D` works for me on emacs

**Comment by kapitanluffy** [comment]
Is there a way to install the master branch of vls? I tried `vuejs/vls#master` but it does not work

**Comment by yoyo930021** [comment]
The Vetur author will back when May.

**Comment by JoelFeiner** [comment]
It is now May and no updates. I'm growing concerned.

**Comment by octref** [comment]
I published a new version.
