### ISSUE TITLE
Code outline: exportDefaultExpression outline could not show properly

### ISSUE THREAD

**Issue by IWANABETHATGUY** [vuejs/vetur#1849]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
but i am pretty sure you can reproduce this in other platform
- Vetur version: 0.24.0
- VS Code version: 1.44

## Problem
this is not a bug for now , but may  happen in next release

- VSCode Version:1.44.0
- Electron: 7.1.11
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Darwin x64 18.7.0

Steps to Reproduce:

1. use vscode inter typescript version which is 3.8.3
2. open a test.js file , and input code as below
```js
export default {
  a: 'string',
  b: 2,
  c () {
    
  }
}
```
3. a exportExpression outline is looks like
![image](https://user-images.githubusercontent.com/17974631/79105445-3e80ef80-7da3-11ea-855d-041b849de004.png)

when i change  the typescript version to `3.7.5`
the outline show below, i think this may be better, but i am not sure if this is a typescript bug or vscode's.
![image](https://user-images.githubusercontent.com/17974631/79105368-185b4f80-7da3-11ea-98fb-027222312055.png)
`大纲` is outline

Does this issue occur when all extensions are disabled?: Yes

**Comment by IWANABETHATGUY** [comment]
i make a issue to vscode, but there are thousands of issue in list, i am not sure they could notice me. 

I contribute this repo yesterday, i clone the repo and install dependencies,  the typescript version in  **directory server** is `^3.7.5` but actually install `3.8.3`, so when i vsce package it , i found that exportDefaultExpression outline gone, the same result as the first picture. 

The exportDefaultExpression outline is import for `.vue`, because we can quickly jump to the component option like `method`, `data` with powerful symbol, but this change may destroy this experience. This may be a upstream bug of typescript , but i am not sure i can explain clearly about that, so i hope you could notice about this breaking change (not sure a bug or something else)

**Comment by IWANABETHATGUY** [comment]
@ktsn  sorry to bother you again.

**Comment by IWANABETHATGUY** [comment]
upstream tracked here : https://github.com/microsoft/TypeScript/issues/37877

**Comment by IWANABETHATGUY** [comment]
fixed by https://github.com/microsoft/TypeScript/pull/38255

**Comment by octref** [comment]
Fixed when updating TS to 4.0.2:

![image](https://user-images.githubusercontent.com/4033249/91128793-667e4900-e6db-11ea-958a-a932ec678f5a.png)

**Comment by rathboma** [comment]
Do I need to manually install this version of typescript, or does the latest vscode install it?

If manual, how do I do that?

Sorry for dumb questions.

**Comment by rchl** [comment]
- Enable `vetur.useWorkspaceDependencies` and install the latest version of typescript in your project
or
 - Wait for the next release of Vetur.

**Comment by rraihansaputra** [comment]
This seems to not work for TypeScript enabled SFC with `export default Vue.extend({options});`. Is this a bug or am I doing something wrong with my SFC?

![without-vue-extend](https://user-images.githubusercontent.com/8604926/95670187-73cf9400-0bb2-11eb-9c97-ef1bc41c027c.png)
![with-vue-extend](https://user-images.githubusercontent.com/8604926/95670188-7500c100-0bb2-11eb-9e01-9d73a6be6d2b.png)

**Comment by yoyo930021** [comment]
> This seems to not work for TypeScript enabled SFC with `export default Vue.extend({options});`. Is this a bug or am I doing something wrong with my SFC?
> 
> Vetur version: 0.28.0
> Project TypeScript: 4.0.3
> "vetur.useWorkspaceDependencies": true
> 
> ![without-vue-extend](https://user-images.githubusercontent.com/8604926/95670187-73cf9400-0bb2-11eb-9c97-ef1bc41c027c.png)
> ![with-vue-extend](https://user-images.githubusercontent.com/8604926/95670188-7500c100-0bb2-11eb-9e01-9d73a6be6d2b.png)

If you have some problem, please open a new issue with template.

**Comment by rraihansaputra** [comment]
Thanks @yoyo930021, will open up a new issue.
