### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by jhemmmm** [vuejs/vetur#1851]
- [ Y ] I have searched through existing issues
- [ Y ] I have read through [docs](https://vuejs.github.io/vetur)
- [ Y ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows 10
- Vetur version: 0.24
- VS Code version: 1.43.2

## Problem

![image](https://user-images.githubusercontent.com/14343151/79314090-e299a080-7f33-11ea-80a9-c74de633d244.png)

https://i.imgur.com/jIqLxZt.gifv

**Comment by octref** [comment]
You are using nickeylean.veturing, so please report to that extension.
