### ISSUE TITLE
Syntax highlighting is broken for .ts.vue files

### ISSUE THREAD

**Issue by AbdelrahmanElqusiry-VG** [vuejs/vetur#1855]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows WSL2
- Vetur version: 0.24.0
- VS Code version: 1.44.2

## Problem

Syntax highlighting does not work for the script tag in .ts.vue files. It works everywhere else. Other extensions don't have that issue so it must be related to Vetur. I have tried reinstalling with Admin privileges and uninstalled every other extension but Vetur. A screenshot is attached.

![Screenshot (45)](https://user-images.githubusercontent.com/59791045/79679501-d26d1400-8206-11ea-9a65-49fb66bcab6c.jpg)

**Comment by AlexRuppert** [comment]
It might be related to the `></template>` line. I just had a similar issue, where I had a space before `</template>` on the same line and it broke syntax highlighting for my style section.

Having `</template>` alone on it's own line fixed the syntax highlighting for me. I hope this helps in locating the error cause.

**Comment by AbdelrahmanElqusiry-VG** [comment]
> It might be related to the `></template>` line. I just had a similar issue, where I had a space before `</template>` on the same line and it broke syntax highlighting for my style section.
> 
> Having `</template>` alone on it's own line fixed the syntax highlighting for me. I hope this helps in locating the error cause.

That actually was the issue! 

I would have never thought of that. Thank you very much!
