### ISSUE TITLE
if you capitalize the V in your .vue/.Vue file extension in the file name linter breaks

### ISSUE THREAD

**Issue by rwp140** [vuejs/vetur#1863]
as far as i can tell, i was looking in vetur settings and came back to "Cannot find name 'template'.Vetur(2304)" eventually fixed by uncapitalizing the V in the file name for the .vue file extension. I'm not sure why it was suddenly a problem or exactly why that fixed anything. I had capitalized it simply from OCD. sorry for being brief on information, i was not quite out of the state of panic long enough or fast enough to record everything like i should of.

**Comment by octref** [comment]
Sorry but we don't support custom extensions yet. Only `.vue` is supported.
