### ISSUE TITLE
Syntax Highlighting Broken 

### ISSUE THREAD

**Issue by goudine** [vuejs/vetur#1864]
## Info

- Platform: MacOS 10.15.4
- Vetur version: 0.24.0
- VS Code version: 1.44.2
- VueCLI version: 4.3.1

## Problem

No syntax highlighting in `*.vue` files. Colour appears if file extension switched to `*.js`

## Reproducible Case

1. Download [VS Code](https://code.visualstudio.com/)
2. Install [Vetur](https://vuejs.github.io/vetur)
3. Open file with `.vue` extension

`*.vue`
<img width="608" alt="vue_extension" src="https://user-images.githubusercontent.com/17364268/79916125-0b5ee180-83dd-11ea-94fd-83f3f083477a.png">

`*.js`
<img width="653" alt="js_extension" src="https://user-images.githubusercontent.com/17364268/79916167-1e71b180-83dd-11ea-84c6-96381d4f2696.png">

**Comment by goudine** [comment]
Could not reproduce on different machine. Something else causing the issue.

**Comment by sdaitzman** [comment]
I am also experiencing this issue, but only for JS code blocks.

**Comment by octref** [comment]
In FAQ I mentioned: Usually this is caused by corrupt installation. Force reinstall should work.
