### ISSUE TITLE
Restrict js-beautify version to maintain support for older Nodejs versions

### ISSUE THREAD

**Issue by janlazo** [vuejs/vetur#1865]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win 
- Vetur version: 0.2.0 (vls)
- VS Code version: N/A
- Node version: 8.17.0

## Problem

js-beautify [v1.11.0](https://github.com/beautify-web/js-beautify/blob/master/CHANGELOG.md#v1110) dropped support for Node versions older than v10 because of mkdirp and clarified that js-beautify will not revert the upgrade in .https://github.com/beautify-web/js-beautify/issues/1783.  https://github.com/vuejs/vetur/pull/1826 has a build failure when upgrading from v1.10.3 to v1.11.0. `vls` v0.2.0 supports Node versions up to v6, https://github.com/vuejs/vetur/commit/e028890d30cf32c0dbc208bba06c2e04dbdd0804.

Can js-beautify version be restricted to versions older than v1.11.0
to maintain support for existing Node versions?

## Reproducible Case

1. Install Node version 8 or older.
2. `npm install -g vls`

Expected error message:

```
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for mkdirp@1.0.4: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm ERR! notsup Not compatible with your version of node/npm: mkdirp@1.0.4
npm ERR! notsup Not compatible with your version of node/npm: mkdirp@1.0.4
npm ERR! notsup Required: {"node":">=10"}
npm ERR! notsup Actual:   {"npm":"6.13.4","node":"8.17.0"}
```

**Comment by octref** [comment]
But then that means I won't get any bug fixes since v1.11.0.
One thing to do might be to depend on locally installed versions of formatters, and I don't bundle formatters in Vetur at all.

**Comment by janlazo** [comment]
Can vetur use peer or optional dependencies for formatters and let the user install the formatters if needed for autofixing?

**Comment by octref** [comment]
> Can vetur use peer or optional dependencies for formatters and let the user install the formatters if needed for autofixing?

That's hard — and I just realized upgrading to prettier 2.0 (#1925) will need Node 10.0 as well, so I'll just make VLS supporting Node 10.0+. Sorry.
