### ISSUE TITLE
Object is of type 'unknown' according to Vetur but TypeScript is able to infer the correct type + vue-cli-service build fails.

### ISSUE THREAD

**Issue by cerino-ligutom** [vuejs/vetur#1868]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows 10 64bit Pro
- Vetur version: 0.24.0
- VS Code version: 1.44.2

## Problem

Vetur is reporting the parameter is of type `unknown` even though TypeScript is able to derive the type `GetLoggedInUserQuery`.

![image](https://user-images.githubusercontent.com/6721822/80160708-d92dc980-8600-11ea-855a-a5f4ee7019e1.png)

Edit:
Cannot build the app because of this.

## Reproducible Case

1. Setup `@vue/composition-api` for Vue 2
2. Setup `@vue/apollo-composable` 
3. Use the `useResult()` helper of `@vue/apollo-composable` on your GraphQL query.
4. Use the parameter (`data` from the screenshot) of the function from the third argument of the `useResult()` function.
5. Vetur will report:

> Object is of type "unknown".

Even though TypeScript is able to derive the correct type.

**Comment by octref** [comment]
Can you push a minimal repro sample to GitHub so I can clone and find the issue?

**Comment by cerino-ligutom** [comment]
@octref Sure, [here](https://github.com/cerino-ligutom/vetur-issue-1868)

**Comment by VincentJonathan** [comment]
Any temporary workaround for this?

**Comment by yoyo930021** [comment]
> @octref Sure, [here](https://github.com/cerino-ligutom/vetur-issue-1868)

I can't reproduce it.
![截圖 2020-08-05 下午1 49 53](https://user-images.githubusercontent.com/9126398/89376537-8fd23780-d722-11ea-9510-b706fe4497b6.png)
You can give me information when you hover `useResult`?

**Comment by yoyo930021** [comment]
The vue-cli-service isn't this project problem,
but I also study about it.

1. You're missing two libraries (`apollo-client` `graphql`) in this repos.
2. `useGetLoggedInUserQuery` have a type error.
3. The `@vue/apollo-composable` library have a type error.

Maybe third problem is type problem in `@vue/apollo-composable` library,
You can `skipLibCheck: true` in `tsconfig.json` for ignore it.
