### ISSUE TITLE
Unable to use "Go To Definition" inside <script> for single file components

### ISSUE THREAD

**Issue by edward01** [vuejs/vetur#1873]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info
- Platform: macOS
- Vetur version: 0.24.0
- VS Code version: 

> Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

## Problem

- I'm unable to use "Go to Definition" on one of vue methods (example: inside the mounted())

- VS Code Notification
> Unable to open 'vue-editor-bridge.ts': Unable to read file '/vue-temp/vue-editor-bridge.ts' (Error: Unable to resolve non-existing file '/vue-temp/vue-editor-bridge.ts').
![image](https://user-images.githubusercontent.com/3353300/80282668-5f532880-8745-11ea-8daf-04f3ad160500.png)

- Log (Window) output
> [2020-04-25 22:30:57.576] [renderer1] [error] Unable to read file '/vue-temp/vue-editor-bridge.ts' (Error: Unable to resolve non-existing file '/vue-temp/vue-editor-bridge.ts'): Error: Unable to read file '/vue-temp/vue-editor-bridge.ts' (Error: Unable to resolve non-existing file '/vue-temp/vue-editor-bridge.ts')
    at e.doReadAsFileStream (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1635:7)
![image](https://user-images.githubusercontent.com/3353300/80282680-7a259d00-8745-11ea-8812-bc66a72f2755.png)

## Reproducible Case

Sample Code, then use "Go to Definition" on the this.fetchDatabase() under mounted()
```javascript
<template>
  <div id="app">
    <router-view />
  </div>
</template>

<script>
export default {
  mounted() {
    this.fetchDatabase()
  },
  methods: {
    fetchDatabase() {
      console.log('action here')
    }
  },
}
</script>
```
![ezgifcom-video-to-gif](https://user-images.githubusercontent.com/3353300/80282439-1353b400-8744-11ea-8f0d-0929a6cc797b.gif)

**Comment by janhaa** [comment]
Solution to this?

**Comment by san-taunk** [comment]
I am facing same issue,
what was the solution to this problem?

**Comment by svdmitrij** [comment]
Same problem, why the issue closed?

**Comment by edward01** [comment]
> Same problem, why the issue is closed?

Sorry mate, i thought I'm the only one facing this issue so I gave up for the mean time. It was now reopened. 

No, it is still not fixed. Just tried ST3 for the meantime 😅

**Comment by octref** [comment]
@edward01 I cannot reproduce this. Can you follow this guide to collect LSP log?
https://github.com/vuejs/vetur/wiki/Collecting-LSP-log

**Comment by edward01** [comment]
Per retest today, I no longer encountered my issue on my vue project compared last time. Thanks for the fix.

Closing this issue now

**Comment by dtboy1995** [comment]
the same issue. when i ctrl+click `this.someFunc()`

**Comment by ndunn219** [comment]
I get the same when I control-click `this.someFunc()`. It gives me the option to create the file. I tried that and it creates the file in C:\vue-temp\vue-editor-brige.ts. Then the next ctrl+click opens that file, which is empty.

![vue-editor-bridge](https://user-images.githubusercontent.com/1577669/97106876-8231ab80-169a-11eb-8244-bf9affad13db.png)

**Comment by dariosalvi78** [comment]
same here

**Comment by marcius** [comment]
same as sdunn219, but after clicking on "create file" I got this:

![image](https://user-images.githubusercontent.com/180110/100520797-1615fc00-31a0-11eb-96ca-c0c14f3dd92d.png)

**Comment by leolafon** [comment]
Same on Ubuntu 20.04, the problem seems to only happen when trying to go to definition of a method from inside a life cycle hook (`created` in my case). It works fine when doing so from another method.

**Comment by EarthmanWeb** [comment]
I have the same problem.  That makes 8 of us,  why is this issue closed, without a solution?

**Comment by fabis94** [comment]
Same issue

**Comment by yoyo930021** [comment]
I will look this issue.
Please open a new issue when you have a problem.

Actually everyone’s problems may have different causes.
Continuous response in a closed issue is not helpful.
