### ISSUE TITLE
Symbol detection not working for Vue component .js files

### ISSUE THREAD

**Issue by carestad** [vuejs/vetur#1886]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux (pop os! 20.04)
- Vetur version: 0.24.0
- VS Code version: 1.45.1

## Problem

When "splitting" out the JS to a separate file, named the same as the .vue file (lets say `example.vue` and `example.js`), the intellisense symbols in VS Code aren't resolved. This used to work at some point, but I recently noticed it doesn't anymore. You could use `CTRL+SHIFT+O` and search in the defined methods, computed etc., like you still can in `.vue` files.

The JS file has a  `// @vue/component` declaration right above the `export default {}` section.

## Reproducible Case

`example.vue`
```vue
<template>
  <div />
</template>
<script src="./example.js"></script>
```

`example.js`:
```js
// @vue/component
export default {
  name: 'Example component',
  computed: {
    myComputed() { return "hello"; },
  },
  methods: {
    fooMethod() { return false; },
  },
};
```

Check out the breadcrumbs in VS Code + opening the "symbol" search with CTRL+SHIFT+O and see that it only lists `default` in there.

Are there any tricks to make these separate .js files (partially) work with vetur, so some of these integrations will work in VS Code?

(The `// @vue/component` comment is added to get `eslint-plugin-vue` working in these .js files)

**Comment by yoyo930021** [comment]
#1775

**Comment by carestad** [comment]
@yoyo930021 Does it mean that if I remove the `;` in the end of my export statement, it should be working again? Because I just tried that and it did not work :confused:

**Comment by yoyo930021** [comment]
> @yoyo930021 Does it mean that if I remove the `;` in the end of my export statement, it should be working again? Because I just tried that and it did not work 😕

I made a mistake. =_=
It's a new feature.

**Comment by carestad** [comment]
Alright. Is there any known workaround for this though? I believe it _has_ worked at some point, just not sure when, unfortunately :confused: 

Also noticed I had forgotten to input my vetur version, so I updated the metadata for the issue now.

**Comment by yoyo930021** [comment]
> Alright. Is there any known workaround for this though? I believe it _has_ worked at some point, just not sure when, unfortunately 😕
> 
> Also noticed I had forgotten to input my vetur version, so I updated the metadata for the issue now.

Maybe you can try to install the old version in vscode.
https://github.com/microsoft/vscode/issues/12764#issuecomment-442370545

**Comment by octref** [comment]
> the intellisense symbols in VS Code aren't resolved.

Then this is either:
- An issue with VS Code's TS support
- An issue with your Vue typing
