### ISSUE TITLE
Formatting failed: "Error: [1,124]: Unexpected character )."

### ISSUE THREAD

**Issue by lennycode** [vuejs/vetur#1887]
- [X ] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
 

## Info

- Platform:  Win
- Vetur version:  0.24.0
- VS Code version: 1.43.2

## Problem

 I have a large .vue file and it fails to format with the message in the title.  No details in output. App runs with no errors.

**Comment by octref** [comment]
Your issue is closed because you did not provide a repro case. Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.
