### ISSUE TITLE
Vetur and *.vue.html single component files

### ISSUE THREAD

**Issue by p3k** [vuejs/vetur#1888]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

Not sure if this is a duplicate of #81 or related to it…?

## Info

- Platform: Linux x64 4.15.0-96-generic
- Vetur version: 0.24.0
- VS Code version: 1.44.2

## Problem

We are currently using `*.vue.html` files with the following mapping in `.vscode/settings.json` but the syntax highlighting differs from files ending with `*.vue` only so fundamentally one might consider it broken.

```json
{
	"files.associations": {
		"*.vue.html": "vue"
	}
}
```

Here is a screenshot of a `*.vue.html` file using this mapping:

![image](https://user-images.githubusercontent.com/16631/80565595-2939d100-89f1-11ea-844e-646b0a051726.png)

## Reproducible Case

I guess I just provide the source code from the screenshot. If opened with the file extension `*.vue.html` and the correct file association in VS Code it should give a similar display as in the screenshot.

```html
<template>
	<div>
		<input type='text' :value='value' @change='onChange'/>
	</div>
</template>

<script>
	export default {
		props: { value: String },

		setup(props, context) {
			function onChange(event) {
				context.emit('input', event.target.value);
			}

			return {
				onChange
			};
		}
	}
</script>
```

**Comment by octref** [comment]
> syntax highlighting

The red lines are not syntax highlighting. They are errors. We don't support .vue.html files yet.
