### ISSUE TITLE
Default formatting is too opinionated

### ISSUE THREAD

**Issue by TheGuywithTheHat** [vuejs/vetur#1893]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.24.0
- VS Code version: 1.43.2

## Problem

In my opinion (no pun intended), the default formatting with prettier is too opinionated. It removes trailing commas, adds semicolons, changes single quotes to double, changes all indentation to two spaces, etc. Others also disagree with the defaults, for example: #679, #1460, #1320, #1311, and #984. In addition, the defaults _can even break people's code_, e.g. #719 and #1398. I understand that most/all of those issues have fixes or workarounds, but those types of issues will continue to occur simply because it's too opinionated.

I know that it can be valuable to have opinionated formatters. I know that I can configure prettier and prettyhtml. However, I do not think that it should be the way it is _by default_.

**If I wanted an opinionated formatter, I would have enabled an opinionated formatter.**

I understand that much of this is subjective; I'm just throwing my subjective perspective out here for you to consider.

---

Side question: I currently format my files by changing the file type to HTML, doing the formatting, and changing it back to Vue. Is there any way to make Alt+Shift+F format Vue files with vscode's default HTML formatter, which respects my global vscode settings and doesn't change anything other than whitespace?

**Comment by doyle-mark** [comment]
I use this for formatting https://marketplace.visualstudio.com/items?itemName=febean.vue-format

works great, I forked it and included my own eslint configuration however

**Comment by octref** [comment]
I don't see any other high quality formatters that continue to get developed and maintained.
In the past, js-beautify was the default, which is what VS Code HTML formatter uses. It caused bugs and wasn't actively maintained so I changed the default.
If you have a good suggestion feel free to reopen.
