### ISSUE TITLE
Failed to load typescript from workspace. Using bundled typescript@3.7.5.

### ISSUE THREAD

**Issue by DarkLite1** [vuejs/vetur#1898]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.24.0
- VS Code version:
```
Version: 1.45.0 (system setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:18:48.860Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.14393
```

## Problem

Error message from Panel -> Output -> Vue Language Server:
```
Failed to load typescript from workspace. Using bundled typescript@3.7.5.
Vetur initialized
```

I have installed TypeScript version `3.8.3` which is correctly used within vscode but Vetur can't load it. Even though I've set Vetur to `Use Workspace Dependencies: true`. Am I doing something wrong?

Added TS globally:
```
yarn global add typescript
```

Added TS to my package json of my project:
```
yarn add typescript@latest --dev
```

![image](https://user-images.githubusercontent.com/10828570/81496707-e2ce5700-92b9-11ea-8084-ea87feb1723e.png)

**Comment by DarkLite1** [comment]
Fixed this one thanks to the help of Callo, a Quasar Framework dev.  

Apparently I didn't set up vscode correctly. Even though vscode shows the correct TS version at the bottom right, this is not enough for Vetur to be able to use it. To fix this, one needs to update the vscode user `settings.json`:

```
"typescript.tsdk": "node_modules/typescript/lib"
```
This points to the globally installed TypeScript version and makes sure Vetur can use.

**Comment by IlCallo** [comment]
This actually points to the *locally* TS version ;)
