### ISSUE TITLE
Bring in stylelint and stylefmt for style

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#190]
They seem to have best support for linting / formatting css/scss/sass/less/postcss.

**Comment by cannap** [comment]
look at this https://github.com/morishitter/scssfmt :D

**Comment by glen-84** [comment]
@octref In order to support [sass-lint](https://marketplace.visualstudio.com/items?itemName=glen-84.sass-lint) (I'm the author), does something have to be added to Vetur, or do you know of a way to add support via existing APIs?

**Comment by octref** [comment]
@glen-84 Take a look at https://github.com/vuejs/vetur/tree/master/server/src for `modes/style/stylus/index`. Basically each language is called a `mode` in Vetur and it's easy to add a default template mode for sass (currently we don't have one yet), and only implement its `doValidation` method which is for reporting lint errors.

Integrating sass should be pretty similar to integrating stylus.

**Comment by octref** [comment]
Seems `sass-lint` also has support for `scss` files. Maybe you can start form there.

**Comment by octref** [comment]
@glen-84 Seems `sass-lint` also supports `scss` files. Maybe you can start from there since Vetur already has support for scss. See https://github.com/vuejs/vetur/blob/master/server/src/modes/style/index.ts

**Comment by octref** [comment]
There is nothing to do for this issue so closing.

`stylefmt` is included in `prettier` and we'll include it.
For linting I'll open a new issue.

**Comment by glen-84** [comment]
@octref Apologies for the late reply. I would prefer to do something that doesn't rely directly on your extension, but instead is more generic to the framework (in this case Vue.js) in use.

I will investigate this more at a later date.

Thanks.
