### ISSUE TITLE
Vetur does not work at all ! I have tried everything from vetur/docs/FAQ !

### ISSUE THREAD

**Issue by GeorgeFlorian** [vuejs/vetur#1922]
Issue Type: <b>Bug</b>

After VSCode updated itself to the latest version: 1.45.1 (user setup), Vetur alongside Vue VSCode Snippets and Vue Inline Template stopped working.

I don't have any autocomplete for Vue nor does the HTML inside js files get highlighted.

![Capture](https://user-images.githubusercontent.com/39895513/82358453-34d85080-9a0f-11ea-8308-9c3ac1ba6b8a.PNG)

OS: Windows 10 Pro 1836.836

Extension version: 0.24.0
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (8.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Mister-Hope** [comment]
1.45.1 works for me, and I am on Win10 pro too with a build number of `19041.264`. maybe checking again with your settings?

**Comment by GeorgeFlorian** [comment]
> 1.45.1 works for me, and I am on Win10 pro too with a build number of `19041.264`. maybe checking again with your settings?

Can you please specify what settings ?

This is a fresh install of Windows 10 and VSC.
I have disabled all the other extensions except Vetur and it still doesn't work.

**Comment by GeorgeFlorian** [comment]
I have tried the following:

- Run command: Developer: Reinstall Extension for Vetur.
- Remove Vetur in your extensions folder and do a clean reinstall.
- (Windows): Try removing & reinstall Vetur with admin privilege.
- If nothing above works, download the latest pre-packaged vsix file and install through vsix.

Nothing works !!!
What is happening ? I really need this extension.

**Comment by Mister-Hope** [comment]
```json
  // vetur 设置
  "vetur.format.defaultFormatterOptions": {
    "js-beautify-html": {
      "wrap_attributes": "auto"
    },
    "prettyhtml": {
      "printWidth": 100,
      "singleQuote": false,
      "wrapAttributes": false,
      "sortAttributes": false
    },
    "prettier": {
      "printWidth": 80,
      "singleQuote": false,
      "tabWidth": 2,
      "useTabs": false,
      "semi": true,
      "trailingComma": "es5",
      "bracketSpacing": true,
      "parser": "babel"
    }
  },
  "vetur.format.defaultFormatter.html": "prettyhtml",
  "vetur.format.defaultFormatter.js": "prettier",
  "vetur.format.defaultFormatter.ts": "prettier",
  "vetur.useWorkspaceDependencies": true,
```

**Comment by GeorgeFlorian** [comment]
What do I do with that ?

I know that you are trying to help me, but please be more specific because I don't know what can I do with the above code.

**Comment by Mister-Hope** [comment]
Above is my vscode settings, and I just delete them and restart vscode, everything still works fine.

**Comment by Mister-Hope** [comment]
Oop, I just got a clear look at your sceenshot, vetur works for `.vue` files, I don't think it hightlighted the template string in the previous version. Also, I don't think vetur is providing autocomplete for js files.

**Comment by GeorgeFlorian** [comment]
> Above is my vscode settings, and I just delete them and restart vscode, everything still works fine.

I have just deleted all the extensions from `username/.vscode/extensions`. I have reinstalled VSCode.

I ran it as Admin, installed Vetur and some syntax gets highlighted, but he HTML inside template still doesn't gets highlighted, just like the picture from the first post.

Is Vetur supposed to have this functionality or not ?

**Comment by GeorgeFlorian** [comment]
Soooo... Vetur turned out to be working properly. The extension that I was looking for was `Vue Inline Template`

It looks nice now. I hope that it keeps working.

![Capture](https://user-images.githubusercontent.com/39895513/82443311-f6dc3a80-9aa9-11ea-8d03-90e87d0ebd1c.PNG)
