### ISSUE TITLE
at-rule or selector expectedcss(css-ruleorselectorexpected) validation error display for styles beginning ">>>"

### ISSUE THREAD

**Issue by simonbrent** [vuejs/vetur#1924]
## Info

- Platform: Windows 10
- Vetur version: 0.24.0
- VS Code version: 1.45.1

## Problem

at-rule or selector expectedcss(css-ruleorselectorexpected) validation error display for styles beginning ">>>"

## Reproducible Case

Create a .vue file with the following style block:

```
<style scoped>
  >>> .foo { display: block; }
</style>
```

Open the file in VS Code - you will see the error "at-rule or selector expectedcss(css-ruleorselectorexpected)"

Disable the Veture > Validation: Style setting and reload VS Code - the error will no longer be present.

**Comment by octref** [comment]
There's no support for non-standard CSS features.

**Comment by simonbrent** [comment]
But this is the documented way to do deep selectors for scoped style:
https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors

Should I be doing `* >>> .foo { display: block; }` instead?

**Comment by octref** [comment]
From what I see you need to have a selector before and after `>>>`. What's the grammar for `>>>`?

**Comment by simonbrent** [comment]
https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors is the only place I've seen it officially documented, which doesn't define whether you must have a selector before and after. However, I know that not having a selector before does work, since my code behaves as expected.

**Comment by octref** [comment]
You can try your luck by opening an issue here: https://github.com/microsoft/vscode-css-languageservice, but I doubt they'd make the change to accommodate non-standard CSS. Vetur uses it and it parses standard CSS/SCSS/Less.

**Comment by rchl** [comment]
You can use `/deep/` instead.

**Comment by frederikheld** [comment]
Same issue with /deep/.

**Comment by simonbrent** [comment]
FYI `::v-deep` appears to work without an error (for now...)

**Comment by DMOAbove** [comment]
I am getting this error with this:

```
:deep(.select-input) {
    .dropdown-container {
      @apply bg-dark-stone #{!important};
      .dropdown-menu {
        .dropdown-input-select-item {
          &:hover {
            @apply text-white #{!important};
          }
        }
      }
    } <- gives error here
```

Seems related with interpolating the important from tailwind. If I remove both importants the error doesn't happen.

**Comment by dcvermeer** [comment]
@keyframes slideFromLeft7 {
    0% {
        width: 0;
    }
    100% {
        width: <?php echo ($Value / 195) * 100; ?>%;
    }
} <---- gives a "at-rule or selector expectedcss(css-ruleorselectorexpected)" 
i have no clue how to fix it ?
