### ISSUE TITLE
Update to prettier 2.0 please

### ISSUE THREAD

**Issue by Mister-Hope** [vuejs/vetur#1925]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

**Comment by octref** [comment]
Duplicate of #1794.

**Comment by Mister-Hope** [comment]
I notice #1794 before opening this issue.#1794  is talking about Vetur issues when using prettier 2.0 in workspace, and some of the users already gave a workaround. While I am talking about update prettier in Vetur to 2.0

**Comment by octref** [comment]
OK then

**Comment by mesqueeb** [comment]
@octref Thanks a lot for closing this ! When will this be live in VSCode? Much thanks!
