### ISSUE TITLE
Cannot open user scaffold snippet folder on WSL

### ISSUE THREAD

**Issue by ewen-lbh** [vuejs/vetur#1927]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Ubuntu 18.04.4 LTS on Windows 10 x86_64 
- Vetur version: `0.24.0`
- VS Code version: `1.45.1`

## Problem

Upon selecting "Vetur: Open user scaffold snippet folder" from the Command Palette, I received the following error message:

```
Command 'Vetur: Open user scaffold snippet folder' resulted in an error (ENOENT: no such file or directory, mkdir '/home/ewen/.config/Code/User/snippets/vetur')
```

(My WSL username is `ewen`)

Nothing outputs on the `Vue Language Server` output panel, but that's to be expected I guess.

## Reproducible Case

1. Open Visual Studio Code, hosted on WSL, Ubuntu 18.04
2. <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>
3. Execute `Vetur: Open user scaffold snippet folder`
4. See the error message

**Comment by octref** [comment]
I'm not familiar with WSL. Are all your configs stored in `/home/ewen/.config`?

If you run the command `Preferences: Configure User Snippets` and choose `JavaScript`, where is it located? You can find it in breadcrumb or sidebar.

![image](https://user-images.githubusercontent.com/4033249/83988307-735d8d00-a975-11ea-92ee-0c04df422de5.png)

**Comment by ewen-lbh** [comment]
@octref hi, sorry but I didn't remember that the issue fixed itself, I don't remember how, I think that I just restarted vscode a few times. I forgot to close the issue, sorry again
