### ISSUE TITLE
Symlink node_modules will take up very high memory and cpu

### ISSUE THREAD

**Issue by Moerj** [vuejs/vetur#193]
![qq20170509-171414](https://cloud.githubusercontent.com/assets/13795438/25844439/133bd3e2-34dd-11e7-8f5e-3058912dbc62.jpg)
![qq20170509-172658](https://cloud.githubusercontent.com/assets/13795438/25844449/1a0de8c2-34dd-11e7-9db3-a9c34ad6888c.jpg)

It take my very high memory and cpu.😱
This is not the case before.

And when I disable it...

![qq20170509-172512](https://cloud.githubusercontent.com/assets/13795438/25844477/2e4ccc0e-34dd-11e7-8a2c-51f7c1ffab30.jpg)

**Comment by octref** [comment]
Dup of #164.

**Comment by Moerj** [comment]
@octref 
In other words, wait for the new version to solve this problem?

**Comment by octref** [comment]
Yeah, it will take some time. I haven't got a good repro case though, so it'd be great if you have a project that causes this problem and that you don't mind sharing.

**Comment by Moerj** [comment]
oh. Thanks. I will help you as much as possible.🤡

I know how this problem is actually caused.

I tell you the details later.

**Comment by Moerj** [comment]
@octref 
I find the problem!

The bug is using link node_modules for project.

If install node_modules by current project folder.It is normal

![qq20170509-185122 2x](https://cloud.githubusercontent.com/assets/13795438/25847741/ee4b830e-34e9-11e7-8ec9-af3d8937e9a3.jpg)

![qq20170509-185439 2x](https://cloud.githubusercontent.com/assets/13795438/25847746/f2c22046-34e9-11e7-94c0-b2a2f6636f31.jpg)

**Comment by Moerj** [comment]
should I submit a new issues or you reopen this issues?😝

**Comment by octref** [comment]
...Why would you do that. Is that considered normal practice?

**Comment by Moerj** [comment]
Link node_modules Is for reuse.Similar projects do not install again.

**Comment by octref** [comment]
Does this still happen in latest version? If so does it happen if you add a jsconfig/tsconfig that excludes `node_modules` manually?

I'm seeing some bugs on TS repo complaining about symlinks not working properly. This might be hard to fix...
What's stopping you from using yarn so you don't have to download `node_modules` again anyway?

**Comment by octref** [comment]
Feel free to reopen if this still happens.
