### ISSUE TITLE
Is eslint vs code extension required or not?

### ISSUE THREAD

**Issue by Dealerpriest** [vuejs/vetur#1941]
- [x ] I have searched through existing issues
- [x ] I have read through [docs](https://vuejs.github.io/vetur)
- [ x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Problem

It's unclear from vetur web documentation whether eslint extension is required or not.

In the [setup](https://vuejs.github.io/vetur/setup.html) part of the documentation it's stated that eslint extension should be installed for **linting**. 

> Install ESLint extension for linting vue and js files.

What does this actually mean? Is it reccomended to also install eslint because it provides nice linting functionality, **or**, does vetur somehow depend on the user installing eslint extension for some of it's internal functionality?

In the part of the documentation that discusses [formatting](https://vuejs.github.io/vetur/formatting.html) the following is stated:

> Vetur bundles all the above formatters. When Vetur observes a local install of the formatter, it'll prefer to use the local version.

This implies that eslint is bundled in the vetur install, so that the user can get `prettier-eslint` as formatter by making that change in the extension settings. Is that the case? **Or**, does this setting rely on eslint being installed manually by the user? 

Some further clarification would be much appreciated

**Comment by yoyo930021** [comment]
The ESLint extension can lint your file.
The Vetur can format with ESLint fix.

The Vetur doesn't depend on ESLint extension.
The `ESLint`  libaray is bundled in the Vetur for validate vue template.
The `prettier-eslint` libaray is bundled in the Vetur for format Vue file.
If you install `prettier-eslint` in your project, the Vetur will use`prettier-eslint` in your project.

**Comment by octref** [comment]
As @yoyo930021 answered.
