### ISSUE TITLE
vetur error on "import type" statements

### ISSUE THREAD

**Issue by rfox12** [vuejs/vetur#1943]
For Typescript users who want to import a type (and signal that they aren't going to instantiate any objects from the module), it's nice to be able to **`import type`** like this:

```
...
<script lang="ts">
import type { AxiosError } from 'axios';
...
```
right now this results in: `Cannot find name 'AxiosError'.Vetur(2304)`

**Comment by yoyo930021** [comment]
Have you open `Use Workspace Dependencies` option?
https://vuejs.github.io/vetur/FAQ.html#vetur-uses-different-version-of-typescript-in-vue-files-to-what-i-installed-in-node-modules

**Comment by rfox12** [comment]
That does the trick.  Thank you.

**Comment by noook** [comment]
I am using the `import type` syntax to prevent circular dependencies

And by doing this, Vetur is not able to find my interface in my own project.

```ts
// components/Radio/index.ts
interface Props {
  name: string;
  value: unknown;
  disabled: boolean;
  getValue: (value: unknown) => string;
}

export type {
  Props,
};
```

```vue
<script lang="ts">
// components/Radio/Radio.vue
import { defineComponent, PropType, ref } from 'vue-demi';
import type { Props } from '.';

export default defineComponent({
  name: 'GRadio',
  props: {
    name: {
      type: String as PropType<Props['name']>,
      required: true,
    },
    value: {
      // null omits type validation made by Vue at runtime. Value can be of any type
      type: null as unknown as PropType<Props['value']>,
      required: true,
    },
    disabled: {
      type: Boolean as PropType<Props['disabled']>,
      default: false,
    },
    getValue: {
      type: Function as PropType<Props['getValue']>,
      default: (value: unknown) => value as string,
    },
  },
});
</script>
```

```vue
<template>
  <!-- Cannot find name 'Props'. -->
  <div class="app">
    <h1>App</h1>
    <form class="flex flex-col">
      <GRadio name="test" :value="2">
        2
      </GRadio>
    </form>
  </div>
</template>

<script lang="ts">
// App.vue
import { defineComponent } from 'vue-demi';
import GRadio from '@/components/Radio';

export default defineComponent({
  name: 'App',
  components: { GRadio },
});
</script>
```

**Comment by yoyo930021** [comment]
> I am using the `import type` syntax to prevent circular dependencies
> 
> And by doing this, Vetur is not able to find my interface in my own project.
> 
> Use workspace dependencies option is enabled
> 
> ```ts
> // components/Radio/index.ts
> interface Props {
>   name: string;
>   value: unknown;
>   disabled: boolean;
>   getValue: (value: unknown) => string;
> }
> 
> export type {
>   Props,
> };
> ```
> 
> ```
> <script lang="ts">
> // components/Radio/Radio.vue
> import { defineComponent, PropType, ref } from 'vue-demi';
> import type { Props } from '.';
> 
> export default defineComponent({
>   name: 'GRadio',
>   props: {
>     name: {
>       type: String as PropType<Props['name']>,
>       required: true,
>     },
>     value: {
>       // null omits type validation made by Vue at runtime. Value can be of any type
>       type: null as unknown as PropType<Props['value']>,
>       required: true,
>     },
>     disabled: {
>       type: Boolean as PropType<Props['disabled']>,
>       default: false,
>     },
>     getValue: {
>       type: Function as PropType<Props['getValue']>,
>       default: (value: unknown) => value as string,
>     },
>   },
> });
> </script>
> ```
> 
> ```
> <template>
>   
>   <div class="app">
>     <h1>App</h1>
>     <form class="flex flex-col">
>       <GRadio name="test" :value="2">
>         2
>       </GRadio>
>     </form>
>   </div>
> </template>
> 
> <script lang="ts">
> // App.vue
> import { defineComponent } from 'vue-demi';
> import GRadio from '@/components/Radio';
> 
> export default defineComponent({
>   name: 'App',
>   components: { GRadio },
> });
> </script>
> ```

Do you use correct syntax?
The `index.ts` is wrong in my thoughts.

**Comment by noook** [comment]
What do you mean, _correct_ syntax ? This is valid, it compiles and runs correctly.

I just omitted the import and export of the Vue component because it is not pertinent in this issue

**Comment by yoyo930021** [comment]
> What do you mean, _correct_ syntax ? This is valid, it compiles and runs correctly.
> 
> I just omitted the import and export of the Vue component because it is not pertinent in this issue

Oh, sorry. Can you open a new issue? I will take a look.
