### ISSUE TITLE
How do you pronounce "vetur"?

### ISSUE THREAD

**Issue by rdhelms** [vuejs/vetur#1957]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

"vee-ter"?
"veh-toor"?
🤷🏼‍♂️

**Comment by hikerpig** [comment]
I seems like vetur is *winter* in icelantic, pronounces `/ˈvɛːtʏr/`

According to https://glosbe.com/is/en/vetur

**Comment by octref** [comment]
[`/ˈvɛːtʏr/`](https://en.wiktionary.org/wiki/vetur)

I wanted to find a unique word that starts with V, so I chose `Vetur` from this Icelandic song:

https://www.youtube.com/watch?v=lfksYyxGRJw
