### ISSUE TITLE
Conditional is ignored in 'Object is possibly null'

### ISSUE THREAD

**Issue by HunderlineK** [vuejs/vetur#1958]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS 10.14.6
- Vetur version: 1.45.1
- VS Code version: 0.24.0

## Problem
I have a conditional statement that only be reached if the object exists; however, I am still getting 'Object is possibly null' error; I suspect it is because in the 'data' I have set its initial value to 'null'

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/12711237/83697467-148ec100-a5cd-11ea-833d-893ba0b83da9.png">

## Reproducible Case

```
      return this.selectedEvent && this.profile && this.profile.uploads
        ? this.profile.uploads.find((/** @type {any} */ { result: { public_id: publicId } }) => this.selectedEvent.publicId === publicId)
        : null
```

**Comment by mdbetancourt** [comment]
that's an expected behavior and has nothing to do with vetur, it's a typescript behavior. you get that error because a function sometimes is not called syncronous so typescript cant ensure that var will keep as an object (could be changed before running that function).
a good one could be
```ts
const { p
return this.profile?.uploads?.find(({

**Comment by HunderlineK** [comment]
@mdbetancourt Thanks for the clarification and the pattern. I'm closing the issue since it's TS related.

Just for my understanding, since the `this.profile.uploads.find((/** @type {any} */ { result: { public_id: publicId } }) => this.selectedEvent.publicId === publicId)` shouldn't all of it be evaluated in the same tick as the condition `this.selectedEvent && this.profile && this.profile.uploads`?

Maybe I'm misunderstanding something about how JS evaluates the expression.
