### ISSUE TITLE
[feature request] add autocompletion for props in <template> for imported components

### ISSUE THREAD

**Issue by Hulkmaster** [vuejs/vetur#1960]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

Would be nice to have autocompletion feature for props for imported components and add required props by default

`some-component.vue`
```
export default {
  props: {
    red: {
      type: Boolean,
      required: true,
    }
  },
}
```

`another-component.vue`
```
<some-component />
```
here would be nice to have suggestion about possible props, or even better - add required props by default

**Comment by yoyo930021** [comment]
It's available now.

**Comment by octref** [comment]
If you setup your imports correctly you should get this feature:

![image](https://user-images.githubusercontent.com/4033249/83989985-af472100-a97a-11ea-828f-1fcaed989849.png)

**Comment by Hulkmaster** [comment]
Yeah, sorry, seems like wrong import configuration from my side

**Comment by Hulkmaster** [comment]
But then i would still leave second part of my suggestion as a feature request

to mark if component is missing some required properties @octref

**Comment by octref** [comment]
If that's your cause you should follow https://github.com/vuejs/vetur/issues/1288.
For the other one see #1571. @ktsn Is it that you looked into this and with Vue 2 typing it's impossible?

**Comment by doraeric** [comment]
I need some help, I want to get the autocomplete like the picture above, but I can only see `:red` like this. What should I do to get `red`?
I am using nuxt with typescript

```
// TestComponent.vue
<template>
  <div></div>
</template>

<script lang="ts">
import Vue from 'vue'
export default Vue.extend({
  props: {
    red: Boolean,
  },
})
</script>
```

![crop](https://user-images.githubusercontent.com/16789570/103152906-698f6000-47c7-11eb-8cb6-bd81292b80ba.png)
