### ISSUE TITLE
3rd party client support: CodeActions should return "edit" instead of "command" or the server should implement workspace/executeCommands

### ISSUE THREAD

**Issue by Narretz** [vuejs/vetur#1962]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: master
- VS Code version: None
- Sublime Text 3

## Problem

The Vetur client currently has a custom implementation to execute CodeAction text edits. The server returns the following:
https://github.com/vuejs/vetur/blob/139bc1b0e11acd0eef3212012bbd624e6a3ab73b/server/src/modes/script/javascript.ts#L603-L613
and the client handles it by calling a vscode command:
https://github.com/vuejs/vetur/blob/139bc1b0e11acd0eef3212012bbd624e6a3ab73b/client/vueMain.ts#L41-L45

However, the spec says about the CodeAction command:

> When the command is selected the server should be contacted again (via the workspace/executeCommand) request to execute the command.

https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_codeAction

Or better yet, return the text changes directly via the edit property:

>  Since version 3.8.0: support for CodeAction literals to enable the following scenarios:
> 
>  the ability to directly return a workspace edit from the code action request. This avoids having another server roundtrip to execute an actual code action. However server providers should be aware that if the code action is expensive to compute or the edits are huge it might still be 

The current implementation kills the CodeAction feature for 3rd party clients such as Sublime-LSP.

**Comment by Narretz** [comment]
LSP-vue issue: https://github.com/sublimelsp/LSP-vue/issues/4

**Comment by rchl** [comment]
Fixed by https://github.com/vuejs/vetur/pull/1704

**Comment by octref** [comment]
@rchl Thanks for linking it 👍
