### ISSUE TITLE
Vue components don't get highlighted like React

### ISSUE THREAD

**Issue by max-programming** [vuejs/vetur#1963]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows
- Vetur version: 0.24.0
- VS Code version: 1.45.1

## Problem
I love using Vetur. It is very fast and great. But when I do a React project, and in the highlighting, I saw that the components had a different colour (**That is by VS Code**)  than the normal tags: 

![image](https://user-images.githubusercontent.com/51731966/83972739-7f0e6c80-a8ff-11ea-9f2f-047f1e460d89.png)

I noticed that Vue files did not have that thing: 

![image](https://user-images.githubusercontent.com/51731966/83972752-951c2d00-a8ff-11ea-9978-9008c86aa644.png)

## Reproducible Case

It would be nice if the Vue components also have different colour highlighting

**Comment by max-programming** [comment]
Will this feature be added? so should I close this issue

**Comment by ThatNUB** [comment]
Would be great to have it!

**Comment by AmrBinBashir** [comment]
@max-programming don't close it, otherwise they will forget about it. We have to be patient and let them do their work.

**Comment by max-programming** [comment]
okay. Thanks to support!

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/89272537-e54e0c00-d670-11ea-8ce8-8640d1a1931d.png)

![image](https://user-images.githubusercontent.com/4033249/89273229-d9167e80-d671-11ea-8f92-22b4291ac455.png)

**Comment by max-programming** [comment]
@octref I can't see it on mine. Do I have to change some settings?

**Comment by AmrBinBashir** [comment]
@max-programming works for me, It only works for <PascalCase> like <MyButton>.

**Comment by octref** [comment]
It only works for `<PascalCase>`, which is consistent with React.

**Comment by max-programming** [comment]
> It only works for `<PascalCase>`, which is consistent with React.

This is what happens here:
I think there is some setting to change
![image](https://user-images.githubusercontent.com/51731966/89702288-67824d00-d95d-11ea-8215-64565d413e2c.png)

**Comment by octref** [comment]
#2136

**Comment by max-programming** [comment]
@octref Very happy to see the dedication and work towards this extension. Thanks a lot 😊
This is the other issue. It didn't get highlighted when expanded or if we write something between it
![image](https://user-images.githubusercontent.com/51731966/89726501-d7193a80-da38-11ea-8911-a7fa16fcfb54.png)

**Comment by octref** [comment]
@max-programming Thanks for catching the cases 👍 #2146
I'd prefer opening new issues than appending to old issues though. It's easier to track.

**Comment by max-programming** [comment]
This issue is finally solved. Sorry I checked it now

**Comment by jstiers** [comment]
What is the correct scope to change the color in a custom theme?

Thank you

**Comment by octref** [comment]
`support.class.component.html`.

**Comment by Kolobok12309** [comment]
How disable this feature?)

**Comment by octref** [comment]
`editor.tokenColorCustomizations`

**Comment by mathewcst** [comment]
Is there some setting that I should check? Or some specific theme? For me, it isn't working.

I'm using Vue 3 with Typescript, Community Material Theme and that's it. No highlights. But React highlights works.

**Comment by mathewcst** [comment]
Found the issue (for me). I use WSL 2. When I open a project through WSL it doesn't get highlighted but when I open it through Windows it works perfectly.

![image](https://user-images.githubusercontent.com/5620645/97915055-9aa36500-1d2f-11eb-9e23-2127d13d2df7.png)

**Comment by octref** [comment]
@mathewcst You might want to file an issue for them: https://github.com/Microsoft/vscode-remote-release
