### ISSUE TITLE
valid-template-root  root requires exactly one element;vue3使用多根节点

### ISSUE THREAD

**Issue by Perfumere** [vuejs/vetur#1976]
## Info

- Platform: Win & Mac
- Vetur version:0.24.0
- VS Code version:April 2020 (version 1.45.1)

## Problem
When I use vue-next,I got an error
What should I do to not see it
在模板使用多根节点，报错如下
```vue
// app.vue
<template>
    <demo-layout />
    <demo-container />
    <demo-menu />
    <demo-button />
</template>
```
[vue/valid-template-root]
The template root requires exactly one element.

**Comment by q788799660** [comment]
不影响正常使用，但是报错

**Comment by octref** [comment]
https://vuejs.github.io/vetur/linting-error.html#linting-for-template

`vetur.validation.template: false`

**Comment by fightingcat** [comment]
Sorry for trolling this, but would it not be better if the plugin can discover the .eslintrc file?

**Comment by octref** [comment]
Tracked in #2015. Now you can turn it off with `"vetur.validation.template": false`.

**Comment by gk-shi** [comment]
Have all of you solved this error prompt？Why do I still have this error prompt `valid-template-root`？
 I use the latest vscode (v1.48.1) and the latest vetur (0.26.1).😹
![image](https://user-images.githubusercontent.com/27017919/90858374-a7631e80-e3b8-11ea-8dbe-f14642c818c2.png)

**Comment by Perfumere** [comment]
yeah,I had solved this error.  just create dir named  .vscode in the rootDir and then create file named settings.json in .vscode
![image](https://user-images.githubusercontent.com/42104643/90858872-9ebf1800-e3b9-11ea-922a-a956e67e3698.png)
@gk-shi

**Comment by Perfumere** [comment]
but now, the lasted vetur had no problem as I see.
Maybe you could update the plugin and restart VsCode
@gk-shi

**Comment by gk-shi** [comment]
the latest `vetur` is ok.

I found the reason of my problem.

I installed other plugin work for Wechat miniprogram, and it will check `template` block in the `.vue` files....￣□￣｜｜

after turn off thems the `vetur` working correctly.

Thanks!😁
@Perfumere

**Comment by web2033** [comment]
Disable the whole template validation for the sake of fixing one warning? Is that a suggestion?

**Comment by yoyo930021** [comment]
> Disable the whole template validation for the sake of fixing one warning? Is that a suggestion?

The Vue 3 rules are now automatically used when Vue3.
You don't need disable it.

**Comment by septe01** [comment]
> https://vuejs.github.io/vetur/linting-error.html#linting-for-template
> 
> `vetur.validation.template: false`

tks its solved for me

**Comment by ahm750** [comment]
Disabling the template validation defeats the whole purpose of having Vetur. 

I resolved the issue by moving the project to the root of the workspace. So if you're project is in a subfolder (e.g workspace > sub > project), Vetur looks for the package.json file in the subfolder and not in your project folder, hence the reason why it doesn't work properly.

**Comment by yoyo930021** [comment]
> Disabling the template validation defeats the whole purpose of having Vetur.
> 
> I resolved the issue by moving the project to the root of the workspace. So if you're project is in a subfolder (e.g workspace > subfolder > project), Vetur looks for the package.json file in the subfolder and not in your project folder, hence the reason why it doesn't work properly.

If you use subfolder and monorepo, you can use `vetur.config.js`.

**Comment by ahm750** [comment]
> > Disabling the template validation defeats the whole purpose of having Vetur.
> > I resolved the issue by moving the project to the root of the workspace. So if you're project is in a subfolder (e.g workspace > subfolder > project), Vetur looks for the package.json file in the subfolder and not in your project folder, hence the reason why it doesn't work properly.
> 
> If you use subfolder and monorepo, you can use `vetur.config.js`.

This worked too, thanks!

**Comment by lijing666** [comment]
> Disabling the template validation defeats the whole purpose of having Vetur.
> 
> I resolved the issue by moving the project to the root of the workspace. So if you're project is in a subfolder (e.g workspace > subfolder > project), Vetur looks for the package.json file in the subfolder and not in your project folder, hence the reason why it doesn't work properly.

When my project is in a subfolder , node_modules modules with package.json has vetur tags or attributes config also not  work

**Comment by yoyo930021** [comment]
> > Disabling the template validation defeats the whole purpose of having Vetur.
> > I resolved the issue by moving the project to the root of the workspace. So if you're project is in a subfolder (e.g workspace > subfolder > project), Vetur looks for the package.json file in the subfolder and not in your project folder, hence the reason why it doesn't work properly.
> 
> When my project is in a subfolder , node_modules modules with package.json has vetur tags or attributes config also not work

Please use `vetur.config.js`.
https://vuejs.github.io/vetur/guide/setup.html#advanced

**Comment by lijing666** [comment]
> > > Disabling the template validation defeats the whole purpose of having Vetur.
> > > I resolved the issue by moving the project to the root of the workspace. So if you're project is in a subfolder (e.g workspace > subfolder > project), Vetur looks for the package.json file in the subfolder and not in your project folder, hence the reason why it doesn't work properly.
> > 
> > 
> > When my project is in a subfolder , node_modules modules with package.json has vetur tags or attributes config also not work
> 
> Please use `vetur.config.js`.
> https://vuejs.github.io/vetur/guide/setup.html#advanced

Thanks a lot, It works
