### ISSUE TITLE
vue-language-server package

### ISSUE THREAD

**Issue by ennmichael** [vuejs/vetur#1977]
Today I tried to install the Vue language server using the following command:
```
npm i -g vue-language-server
```
I got errors when trying to run vls. Eventually I found out that the `vue-language-server` package is deprecated, and now the name is simply `vls`.

Is there a reason why the `vue-language-server` package still exists? Could you please add a note to the README file explaining that it is deprecated so that users know right away?

If there is some detail that I am perhaps missing, please excuse my ignorance.

**Comment by octref** [comment]
@ennmichael It's my fault. I got the `vls` package name and I like it being short.
I forgot to deprecate `vue-language-server` and just did so https://www.npmjs.com/package/vue-language-server.

Do you have issue installing `vls`?

**Comment by octref** [comment]
Feel free to continue discussion, just closing since I just need to deprecate `vue-language-server`.

**Comment by ennmichael** [comment]
I had no issue installing `vls` and getting it to work. Thank you very much for your efforts.

**Comment by rchl** [comment]
Although latest release of vls has a bug that makes it crash on Windows if there is no local eslint dependency. It's already fixed on master so new release would be appreciated.

**Comment by octref** [comment]
OK, I'll try to make a release this week.
