### ISSUE TITLE
Some problems caused by importing Vue file without suffix(导入vue文件不加后缀带来的一些问题)

### ISSUE THREAD

**Issue by mcc-stack** [vuejs/vetur#1978]
When I use vetur, by default, when I import a vue file, there is no suffix. When I write a component, there is no prompt. It's too troublesome to add the. vue suffix manually every time. How can I solve this problem?
我在使用vetur的时候,导入vue文件默认是没有后缀名,写组件的时候就没有提示了,每次手动去加.vue后缀太麻烦了,我该怎么解决?
![10b30b282087c74b53bb465016f1732](https://user-images.githubusercontent.com/54461051/84219072-4f7b8200-ab02-11ea-8c7a-7614b1b1c012.png)
![b378703f0f8732f93e784b1686f1e19](https://user-images.githubusercontent.com/54461051/84219087-54d8cc80-ab02-11ea-8674-e7da2fef444c.png)

**Comment by octref** [comment]
There's no way around that limitation yet, sorry.
