### ISSUE TITLE
If possible, keep html tags on the same line

### ISSUE THREAD

**Issue by pattrickrice** [vuejs/vetur#1980]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.24.0
- VS Code version: 1.45.1

## Problem
The problem area is highlight here. new lines should be inserted after the `>` character, not in the middle of the tag.
```html
            </v-btn></v-col
          ><v-col>
            <v-btn @click="$emit('close')" depressed color="primary" outlined>
              Close
            </v-btn></v-col
          >
        </v-row></v-container
      >
```
full template

```html
<template>
  <v-card>
    <v-form v-model="valid" class="pa-2">
      <v-container>
        <v-card-title class="headline">
          Add Item
        </v-card-title>

        <v-row no-gutters>
          <v-col>
            <v-text-field required v-model="name" label="Name"> </v-text-field>
          </v-col> </v-row
        ><v-row>
          <v-col>
            <v-btn
              @click="add"
              depressed
              color="primary"
            >
              <span class="white--text">Add Item</span>
            </v-btn></v-col
          ><v-col>
            <v-btn @click="$emit('close')" depressed color="primary" outlined>
              Close
            </v-btn></v-col
          >
        </v-row></v-container
      >
    </v-form>
  </v-card>
</template>
```

## Reproducible Case

The above template. If you paste it into vs-code, there's no linting warning. I can manually sift through each tag and correct them, but i feel like this is something that could be an optional rule like `avoid-breaking-tags`. I didn't break them myself, they were broken up by auto-formatting, so i feel like the auto-formatting should be just a bit smarter.

**Comment by octref** [comment]
With `"vetur.format.defaultFormatter.html": "prettyhtml"`, or `prettier` or `js-beautify` this does not happen to me.

What's your formatter? Does running the template as HTMl through that formatter directly cause this bug as well?

**Comment by sapphi-red** [comment]
I think this prettier issue (https://github.com/prettier/prettier/issues/8302) is related.

**Comment by pattrickrice** [comment]
Actually, yes I use `'plugin:prettier-vue/recommended',` and it looks like that issue _is_ the issue I'm describing. I will close this as it seems like an upstream problem.
