### ISSUE TITLE
How to set @this in jsdoc to infer the component instance type?

### ISSUE THREAD

**Issue by predragnikolic** [vuejs/vetur#1981]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

- Vetur version: "vue-language-server": "0.0.67"
- VS Code version: None, I use Sublime Text. 

## Problem
Hello,

I am trying to set the type of `this` for functions that are defined outside of the component. 
by using the jsdoc [@this](https://jsdoc.app/tags-this.html). Using @this we can set the value of this, so the typescript language server can infer the type. 

I created a `example.js` file, with the following content:
```javascript
import Vue from "vue";

const HelloComponent = Vue.extend({
	data() {
		return {
			message: ""
		};
	},
	methods: {
		setMessage,
		notify
	}
});

/** @this {typeof HelloComponent} */
function setMessage(message) {
	this.message = message;
        //   ^^^^^^^ error - Property 'message' does not exist on type 'ExtendedVue<Vue, { message: string; }, { setMessage: typeof setMessage; notify: () => void; }, any, Record<never, any>>'.
}


/** @this {typeof HelloComponent} */
function notify() {
	alert(this.message);
        //         ^^^^^^^ error - Property 'message' does not exist on type 'ExtendedVue<Vue, { message: string; }, { setMessage: typeof setMessage; notify: () => void; }, any, Record<never, any>>'.
}

export default HelloComponent;
```

Does anyone know how to properly infer the type of the component and assign the value to @this? 

That would allow me to type `this.` and get autocompletions for `message, setMessage, notify, $forceUpdate and other vue methods`, diagnostics, symbol rename, references and much more, in functions that are defined outside of the component.

I know that is is more of a question than an issue,
but any answer would be appreciated. 

:)

**Comment by octref** [comment]
You might need a newer version of typescript. Ask your language client library how to enable `"vetur.useWorkspaceDependencies": true`, so Vetur can load a newer version of TS.

**Comment by predragnikolic** [comment]
I concluded that this is more of a typescript question that a vetur one.

So far I know that all component defined with `Vue.extend` have these two signatures:
 
```typescript
  extend<Data, Methods, Computed, PropNames extends string = never>(options?: ThisTypedComponentOptionsWithArrayProps<V, Data, Methods, Computed, PropNames>): ExtendedVue<V, Data, Methods, Computed, Record<PropNames, any>>;
  extend<Data, Methods, Computed, Props>(options?: ThisTypedComponentOptionsWithRecordProps<V, Data, Methods, Computed, Props>): ExtendedVue<V, Data, Methods, Computed, Props>;
```

All I need to do is unpack the Data, Methods, Computed and Props from the `VueExtended` type.
So I _partially_ solved my problem by creating a `unpack.d.ts` file with the following content:

```typescript
type Unpack<T> = T extends import("vue/types/vue").ExtendedVue<infer Vue, infer Data, infer Methods, infer Computed, infer Params> ? Vue & Data & Methods & Computed & Params : T;
```
> note: the generic type T represents any ExtendedVue type.

And this all works great, but **only** in case when I define `data`, `computed` and `methods` within Vue.extend(**object**) (the object must have at least `data`, `computed` and `methods` for the Unpack type to work) If eater one is missing, typescript will later treat `this` as `any` the type `any`.

Here is a working example:

![Screenshot from 2020-06-15 20-51-03](https://user-images.githubusercontent.com/22029477/84694762-fd938b80-af49-11ea-93b8-4f607a90ec35.png)

<details>
  <summary>here is how the main.js file looks</summary>

```javascript
import Vue from "vue";

const HelloComponent = Vue.extend({
    data() {
        return {
            message: 'hello'
        }
    },

    methods: {
        setMessage,
        notify
    },

    computed: {
        // trying to return this.message will break type inference
        greet() { return "hello" }
    },
});

/** @this  {Unpack<HelloComponent>}
 *
 * Sets the message.
 *
 * @param {string}  message  The message
 */
function setMessage(message) {
    this.message = message
    this.notify()
}

/** @this  {Unpack<HelloComponent>}
 *
 */
function notify() {
    alert(this.message)
}


export default HelloComponent;

```
</details>


Even if I just type this.message(type `string`) instead of string "hello" will break type inference...
```diff
    computed: {
        // trying to return this.message will break type inference
-       greet() { return "hello" }
+       greet() { return this.message }
    },
```

also deleting the `computed` or `data` or `methods` section will break type inference. 
Well at least now I know that this is a typescript question/issue.

**Comment by predragnikolic** [comment]
is there a way to check if:
- a type is `any`, 
- or a key ('data', 'computed', 'methods') is missing or doesn't exist in object? 

// this sadly doesn't work
`... infer Methods, Computed extends unknown? never : infer Computed, infer Params`

// this also doesn't work as any type is the `any` type
`... infer Methods, Computed extends any? never : infer Computed, infer Params`

I also tried:
`... infer Methods, Computed extends null ? never : infer Computed, infer Params`
`... infer Methods, Computed extends undefined ? never : infer Computed, infer Params`

but without any good result.

The goal of this question is to detect if data, computed, methods are missing, and if so assign the type never to a particular key that is missing.
This will not treat `this` as `any` and the type inference will work correctly.

**Comment by predragnikolic** [comment]
I created a small repo with the same working example as in the image I posted above:
https://github.com/predragnikolic/jsdoc-typehint-this

@octref, I concluded that this issue is not related to vetur, should I move the issue to a different place?

**Comment by predragnikolic** [comment]
I will close this. This is more of a TypeScript and Vue question.

**Comment by octref** [comment]
@predragnikolic Sorry for my late response. I suggest that you move this issue to vuejs/vue since it's related to TS+Vue typing.
