### ISSUE TITLE
Show error on window.addEventListener()

### ISSUE THREAD

**Issue by AllanOricil** [vuejs/vetur#1985]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.24.0
- VS Code version: 1.46.0

## Problem
![image](https://user-images.githubusercontent.com/55927613/84578688-f4fe5200-ad9d-11ea-9591-8f92bcff53bc.png)

This is the error message
```
Property 'addEventListener' does not exist on type 'typeof window'.Vetur(2339)
```

**Comment by yoyo930021** [comment]
Please provide reproducible case.

Use Vue CLI project or Vuepack.

**Comment by octref** [comment]
Your issue is closed because you did not provide a repro case. Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.
