### ISSUE TITLE
Use typescript.tsdk setting for TypeScript version (instead of useWorkspaceDependencies)

### ISSUE THREAD

**Issue by glen-84** [vuejs/vetur#1996]
- [x] I have searched through existing issues

## Feature Request

Consider using the `typescript.tsdk` setting to load TypeScript, so that the same version is used in both `*.ts` files _and_ `*.vue` files.

The current behaviour is quite confusing by default (setting `useWorkspaceDependencies` works, but it's not immediately obvious that this is necessary).

As far as I know, the `typescript.tsdk` setting is opt-in, so the user should already trust this directory.

**Comment by octref** [comment]
Fixed in #1737.
