### ISSUE TITLE
The Vue Language Server Crashed

### ISSUE THREAD

**Issue by ThaDaVos** [vuejs/vetur#1998]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows 10 2004 - WSL 2 Ubuntu 
- Vetur version: 0.24.0
- VS Code version: 1.46.0

## Problem

Related issues; 
https://github.com/vuejs/vetur/issues/1348
https://github.com/vuejs/vetur/issues/1713

### Why a new issue? 
Simple, I cannot produce a reproducable example (which the others are tagged with) as I don't know **yet** what is causing it, but I've got my local environment set up to work directly with the latest master branch code so I think together we can debug this and figure out an issue as it seems to be a project specific issue (probably something with packages used or something) as it seems to only happen in a few of my projects (Most are Laravel + Vue and only some have issues).

### Whats happening:

The Vue Language Server crashes like 30 to 60 seconds after invoking a format of the document.
It will spew out the following logs from that moment on: https://pastebin.com/erC5DjY9

## Reproducible Case

I cannot reproduce it in the veturpack installation, I'll keep trying, later on I may update the issue if I find what's causing it, until I didn't have any luck

**Comment by ThaDaVos** [comment]
For other people ending up here (probably because of the notification on the other issues), please submit the following as I would like to gather stats about the projects and maybe we can find something in common:

1. Development setup: OS (for example: Windows 10 with WSL 2 running Ubuntu 16.04)
2. Development setup: VSCode Version
3. Development setup: Vetur Version
4. Development setup: VSCode installed extensions
5. Project setup: Frameworks? (for example: Laravel 6.x with Laravel Mix 5.0.4, using VueJs 2.6.11)
6. Project setup: Installed dependecies
7. Project setup: Installed dev-dependecies
8. Project setup: Base layout of folder, where are you .vue files? (For example, `{ROOT}/resources/js/components`)
9. When does it happend? After invoking a format?
10. Include the log out from that moment forward and sanatize it where needed

**Comment by ThaDaVos** [comment]
1. `Development Setup:` Windows 10, using WSL 2 running Ubuntu 18.04.4 LTS
2. `Development Setup:` VsCode 1.46.0
3. `Development Setup:` Vetur 0.24.0
4. `Development Setup:` Extension list: https://termbin.com/mrq2
5. `Project Setup:` Laravel 6.x with Laravel Mix 5.0.4, using VueJs 2.6.11
6. `Project Setup:` Installed dependecies, see #package.json
7. `Project Setup:` Installed dev-dependecies, see #package.json
8. `Project Setup:` Project layout is a mono-repo with two VueJs + Laravel projects in there, both have the same structure from the root on: `{ROOT}/{PROJECT}/resources/components/*`
9. `When:` Happens after invoking a format on a .vue file
10. `Log:` https://pastebin.com/erC5DjY9

#package.json:
#### Project 1:
https://termbin.com/rvuty
#### Project 2:
https://termbin.com/0ttd

**Comment by noayanez20** [comment]
Same problem here, previously I could fix it temporaly restarting vscode, but now it's crashing when starting. I have looked many  trends of this, but not found a solution yet.

**Comment by yoyo930021** [comment]
Related: #1348

**Comment by Swader** [comment]
Reproducible example: run [this](https://github.com/swader/polkadash) in WSL2 (Ubuntu 20.04). Always does it for me.

- `Development setup`: OS (for example: Windows_NT x64 10.0.19042 with WSL 2 running Ubuntu 20.04)
- `Development setup`: VSCode Version 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
- `Development setup`: Vetur Version 0.24.0
- `Development setup`: VSCode installed extensions (See: details below)
- `Project setup`: https://github.com/swader/polkadash
- `Project setup`: Installed dependecies and dev deps (see package.json in repo)
- `Project setup`: Components are in src/components, pages are in src/pages. Some plugins and config files in src/.
- `When it happens`: Happens immediately on VS Code start.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (13.49GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.4.1
laravel-goto-view|cod|1.3.3
vscode-eslint|dba|2.1.6
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.3
php-debug|fel|1.13.0
auto-close-tag|for|0.5.8
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.4
discord-vscode|icr|3.15.0
copy-markdown-as-html|jer|1.1.0
php-namespace-resolver|Meh|1.1.8
dotenv|mik|1.0.1
python|ms-|2020.6.91350
remote-wsl|ms-|0.44.4
vetur|oct|0.24.0
laravel-blade|one|1.22.1
laravel5-snippets|one|1.9.0
laravel-artisan|rya|0.0.27
vue-vscode-snippets|sdr|1.9.0
vscode-status-bar-format-toggle|tom|2.0.0
JavaScriptSnippets|xab|1.8.0


</details>

**Comment by octref** [comment]
Merging to #1944 since it contains a profile. If you are still running into this, please try to record a profile. Thanks: https://github.com/vuejs/vetur/blob/master/.github/PERF_ISSUE.md

**Comment by yogithesymbian** [comment]
The Vue Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.
```
Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T11:00:52.911Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin arm64 20.3.0
```


and


```
Version: 1.55.0-insider (Universal)
Commit: d06d2f1d6245ce00b1c36a9cd81a9087d225173e
Date: 2021-03-26T13:57:45.993Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin arm64 20.3.0
```

**Comment by yoyo930021** [comment]
> The Vue Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.
> 
> ```
> Version: 1.54.3
> Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
> Date: 2021-03-15T11:00:52.911Z
> Electron: 11.3.0
> Chrome: 87.0.4280.141
> Node.js: 12.18.3
> V8: 8.7.220.31-electron.0
> OS: Darwin arm64 20.3.0
> ```
> 
> and
> 
> ```
> Version: 1.55.0-insider (Universal)
> Commit: d06d2f1d6245ce00b1c36a9cd81a9087d225173e
> Date: 2021-03-26T13:57:45.993Z
> Electron: 11.3.0
> Chrome: 87.0.4280.141
> Node.js: 12.18.3
> V8: 8.7.220.31-electron.0
> OS: Darwin arm64 20.3.0
> ```

https://github.com/vuejs/vetur/issues/2724#issuecomment-804893788
