### ISSUE TITLE
Override Getter/Setter in typescript throws an error 

### ISSUE THREAD

**Issue by finnscho** [vuejs/vetur#1999]
Hi,
I have a base component that has a getter and setter called "value" of type "string | MyModel" I override this getter/setter in a derived class.  Veture is showing an error :"
Property 'Value' in type 'DerivedComponent' is not assignable to the same property in base type 'BaseComponent '.
 Type 'string | MyModel' is not assignable to type 'string'.
 Type 'MyModel' is not assignable to type 'string'.Vetur(2416)

I don't get any compilation errors.
Best regards,

finnscho

**Comment by yoyo930021** [comment]
Please provide a repro case: https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md

**Comment by octref** [comment]
Your issue is closed because you did not provide a repro case. Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.
