### ISSUE TITLE
Formating for dynamic scoped slot is broken

### ISSUE THREAD

**Issue by PadreSVK** [vuejs/vetur#2000]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: v0.24.0
- VS Code version: 1.46.0

## Problem

Dynamic scoped slots is formatted from this 
```vue
 <template  v-slot:[`header.${h.value}`]="{ header }" v-for="h in headers">
```
to this
```vue
 <template v-slot:[&#x60;header.${h.value}&#x60;]="{ header }" v-for="h in headers">
```

![formatting-bug](https://user-images.githubusercontent.com/8254631/85234612-e4d61a80-b40e-11ea-8680-b807806cd670.gif)

## Reproducible Case

https://github.com/PadreSVK/vetur/tree/bug/formatting-dynamic-slot

**Comment by yoyo930021** [comment]
What formatter do you used?
You can find `vetur.format.defaultFormatter.html` config in VSCode setting.

**Comment by PadreSVK** [comment]
I dont have any settings for `vetur.format.defaultFormatter.html`. I just have these settings:
```json
"vetur.format.defaultFormatter.js": "vscode-typescript",
"vetur.format.options.tabSize": 4,
"[vue]": {
    "editor.defaultFormatter": "octref.vetur"
},
```

**Comment by octref** [comment]
It's an upstream issue as I can confirm in https://prettyhtml.netlify.com/. Please file against them.
You can change the formatter with `vetur.format.defaultFormatter.html: "prettier"`

**Comment by joweste** [comment]
Hi, why this post was closed? 
Is there some solution?
I have the same problem.

**Comment by yoyo930021** [comment]
> Hi, why this post was closed?
> Is there some solution?
> I have the same problem.

It's `prettier-html` lib problem.
It's out of our scope.

Please open issue in this link.
https://github.com/Prettyhtml/prettyhtml/issues

**Comment by mainslotonlinemudahmenang** [comment]
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

https://github.com/github/hub/issues/3088
--
https://github.com/xtekky/gpt4free/issues/294
https://github.com/AIGC-Audio/AudioGPT/issues/34
https://github.com/NVIDIA/NeMo-Guardrails/issues/12
https://github.com/orchidsoftware/platform/issues/2596
https://github.com/metabase/metabase/issues/30453
https://github.com/TeamNewPipe/NewPipe/issues/10057
https://github.com/github/codespaces-jupyter/issues/367
https://github.com/github/codespaces-jupyter/issues/368
https://github.com/xtekky/gpt4free/issues/297


</body>
</html>
