### ISSUE TITLE
view-design / iview X does not exist in MessageConfig 

### ISSUE THREAD

**Issue by antonelepfl** [vuejs/vetur#2001]
## Info

- Platform: macOS
- Vetur version: v0.24.0
- VS Code version: 1.46.0

## Problem

I'm using a library called `view-design` version: 4.2.0 and I'm trying to use the Message feature

![Screenshot 2020-06-22 at 09 37 59](https://user-images.githubusercontent.com/24406041/85261244-2943d380-b46c-11ea-956e-848d6875965b.png)

And I get this error message
![Screenshot 2020-06-22 at 09 38 09](https://user-images.githubusercontent.com/24406041/85261307-3eb8fd80-b46c-11ea-8e25-e752a3afabfd.png)

From the documentation this was implemented in version 4: https://www.iviewui.com/components/message-en#With_Background

**Comment by yoyo930021** [comment]
It's a typescript definition question in `view-design`.
[Code Link](https://github.com/view-design/ViewUI/blob/master/types/message.d.ts#L44)
You can pay back `view-design` project. [link](https://github.com/view-design/ViewUI/issues).
