### ISSUE TITLE
Extension 'Vetur' cannot format 'test.vue'

### ISSUE THREAD

**Issue by timsayshey** [vuejs/vetur#2009]
## Info

- Platform: macOS
- Vetur version: 0.24.0
- VS Code version: 1.47.0-insider

## Problem

After setting Vetur as the default formatter for Vue files I get a generic error when trying to format a vue component:
Extension 'Vetur' cannot format 'test.vue'

![2020-06-24 09 07 20](https://user-images.githubusercontent.com/1148940/85571933-3098e780-b5fa-11ea-802a-1e8ec11887e6.gif)

## Reproducible Case

Install Vetur and set it as the default formatter. Create a new Vue component:

```
<template lang="pug">
div
  div.my-class Test
</template>
```

Then right click and click 'Format Document'.

**Comment by octref** [comment]
Output -> Vue Language Server, any output?

**Comment by guigagb** [comment]
In any project quasar have a some problem

**Comment by guigagb** [comment]
> In any project quasar have a some problem

I removed the prettier from vscode and it worked.
I had to use eslint formatting

**Comment by octref** [comment]
No follow-up from OP -> closing.

**Comment by mesqueeb** [comment]
same issue here, no output in Vue Language Server
![2020-09-01 16 22 28](https://user-images.githubusercontent.com/3253920/91814671-7532a600-ec6f-11ea-9d53-e90587865a9f.gif)

**Comment by octref** [comment]
@mesqueeb Please open new issue with a reproducible case: https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md

I cannot get the source of the file you are formatting by just looking at a gif.

**Comment by joel-wenzel** [comment]
What worked for me was changing:
` "vetur.format.enable": false`
to 
`"vetur.format.enable": true `

I think quasar might disable this by default when creating through the cli

**Comment by yulafezmesi** [comment]
Ups, In my case, totally forgot added working path to `eslint.workingDirectories` object.

![image](https://user-images.githubusercontent.com/45617686/118442082-c6e26a00-b6f2-11eb-920c-8714942fa428.png)

**Comment by oscarm3l1n** [comment]
For my Vetur works fine whenever i start VScode. Then it can stop working at completely random. When i restart VScode it works again...
