### ISSUE TITLE
Vue 2/3 Eslint rules

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#2015]
Currently, if you start a project with Vue 3 and is using multi-root elements:

![image](https://user-images.githubusercontent.com/4033249/86525096-34a7ed80-beb5-11ea-8265-38b46fb3c49b.png)

I'm planning to turn automatic template validation based on eslint off, so this wouldn't mislead users.

In the long term, I hope there could be 2 eslint rulesets, one for Vue 2 and one for Vue 3. Depending on the `vue` dependency version in `package.json`, choose which one to load.

@ota-meshi it seems you are doing a lot of work for the eslint-vue plugin. Would you be able to help creating the rulesets, or tell me which rules I should/shouldn't load for Vue 3?

**Comment by ota-meshi** [comment]
Hi @octref.

`eslint-plugin-vue@v7.0.0-alpha.x` has started support for Vue.js 3.x.
This version adds three rulesets for Vue.js 3.x.

- ["plugin:vue/vue3-essential"](https://eslint.vuejs.org/rules/#priority-a-essential-error-prevention-for-vue-js-3-x)
- ["plugin:vue/vue3-strongly-recommended"](https://eslint.vuejs.org/rules/#priority-b-strongly-recommended-improving-readability-for-vue-js-3-x)
- ["plugin:vue/vue3-recommended"](https://eslint.vuejs.org/rules/#priority-c-recommended-minimizing-arbitrary-choices-and-cognitive-overhead-for-vue-js-3-x)

The following existing rulesets have been changed for use with Vue.js 2.x for compatibility.

- ["plugin:vue/essential"](https://eslint.vuejs.org/rules/#priority-a-essential-error-prevention-for-vue-js-2-x)
- ["plugin:vue/strongly-recommended"](https://eslint.vuejs.org/rules/#priority-b-strongly-recommended-improving-readability-for-vue-js-2-x)
- ["plugin:vue/recommended"](https://eslint.vuejs.org/rules/#priority-c-recommended-minimizing-arbitrary-choices-and-cognitive-overhead-for-vue-js-2-x)

Every ruleset contains `vue/valid-template-root`, but it has been changed to not report on multiple roots.
https://github.com/vuejs/eslint-plugin-vue/pull/1038

Let me know if you have any other help.

**Comment by FrankFang** [comment]
@ota-meshi  How can I make vetur use `eslint-plugin-vue@v7.0.0-alpha.x`?

**Comment by octref** [comment]
@ota-meshi Great work. I have made the bundled eslint engine to load different rulesets depending on Vue version.

@FrankFang Detailed steps are in https://vuejs.github.io/vetur/linting-error.html
