### ISSUE TITLE
extend Nuxt asyncData new $config in context

### ISSUE THREAD

**Issue by reslear** [vuejs/vetur#2019]
## Feature Request
add support extend Nuxt.js asyncData new $config in context
<img width="620" alt="Снимок экрана 2020-07-06 в 11 51 42" src="https://user-images.githubusercontent.com/12596485/86574806-11e20b80-bf7f-11ea-87d2-82f13703510c.png">

nuxt docs: https://nuxtjs.org/blog/moving-from-nuxtjs-dotenv-to-runtime-config

**Comment by yoyo930021** [comment]
It's a typescript definition question in `Nuxt.js`.
Maybe you can try to upgrade Nuxt.js to latest version?
Or open issue to Nuxt.js?

**Comment by reslear** [comment]
yes this bug in @nuxt/types
