### ISSUE TITLE
Compatibility With FP-TS

### ISSUE THREAD

**Issue by louisreingold** [vuejs/vetur#2026]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.24.0
- VS Code version: 1.46.1

## Problem

First, npm install fp-ts

Then, put the following in a .Vue file

`
import { pipe } from "fp-ts/lib/function";
`

Vetur says: Module '"../../../node_modules/fp-ts/lib/function"' has no exported member 'pipe'. Vetur(2305)

Putting the same in a normal .ts file works fine.

**Comment by louisreingold** [comment]
$1,000 to first person who can give me a real solution to this (I'm not moving my VS Code project root): email louis@soflyy.com or Skype louis.soflyy. Offer expires in a week.

**Comment by F0rsaken** [comment]
![image](https://user-images.githubusercontent.com/21238469/87543068-574fb880-c6a4-11ea-9a77-b26ed4476617.png)
works fine in my project, I installed newest version of a package.

Can you show me your VS Code settings? Also how project is structured (for example a screen of sidebar with files or something like that)

**Comment by yoyo930021** [comment]
Please provide a repro case: https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md

**Comment by octref** [comment]
@louisbourque I cannot reproduce this:

- Clone https://github.com/octref/veturpack
- `yarn add fp-ts`

![image](https://user-images.githubusercontent.com/4033249/88166167-6f49ae00-cc49-11ea-8a75-5ee6b515db18.png)
