### ISSUE TITLE
new release please

### ISSUE THREAD

**Issue by IWANABETHATGUY** [vuejs/vetur#2027]
- [x] I have searched through existing issues

## Feature Request

Vetur has no new release since Mar, should we release a new version?

**Comment by F0rsaken** [comment]
yes, please, there are many PR's that solves issues, that even small release would be great! ❤️

**Comment by mesqueeb** [comment]
My use case is:
https://github.com/vuejs/vetur/issues/1925

I'd love to start using Prettier 2.0, which is pending this already fixed & merged issue.

Now just the release on VSCode! 🎉

**Comment by octref** [comment]
I released Vetur 0.25.0, `vls@0.3.0` and `vti@0.0.4`: https://github.com/vuejs/vetur/releases/tag/v0.25.0
