### ISSUE TITLE
[ERROR WHEN add PROPS to COMPONENT] Property 'xyz' does not exist on type 'CombinedVueInstance<Vue,

### ISSUE THREAD

**Issue by mamedun** [vuejs/vetur#2028]
- [*] I have searched through existing issues
- [*] I have read through [docs](https://vuejs.github.io/vetur)
- [*] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  macOS
- Vetur version: 0.24.0
- VS Code version: 1.4.7 stable and insider

## Problem

my problem related with #1834 

if i set the props inside component, it throws lot of error

![Screen Shot 2020-07-10 at 17 16 03](https://user-images.githubusercontent.com/18057021/87144308-be025a00-c2d1-11ea-8fa5-ac7dfa1009d3.png)

![Screen Shot 2020-07-10 at 17 16 11](https://user-images.githubusercontent.com/18057021/87144356-d07c9380-c2d1-11ea-80a6-98faf9effb29.png)

## Reproducible Case
just add props inside component and it all broken

im sorry my english is not so well. thanks for this awesome project before!!

**Comment by mamedun** [comment]
### UPDATED

spend lot of hour to figure it out about this problem, and finally post this issue. when suddenly **i tried to restart my laptop**. voila the **problem solved** :(

sorry for my 'noobiness'

![Screen Shot 2020-07-10 at 17 32 22](https://user-images.githubusercontent.com/18057021/87145343-5ea54980-c2d3-11ea-8be4-b2068bafbc1d.png)

**Comment by JoelFeiner** [comment]
You shouldn't need to restart your whole computer for an issue in VSCode. I suspect what worked was restarting VSCode and that resulted in Vetur/TS re-reading project information. It should be able to do it in realtime, though. So IMHO this is still actually a bug if it can be reproduced.
