### ISSUE TITLE
Compressed

### ISSUE THREAD

**Issue by pagnkelly** [vuejs/vetur#2029]
I executed the "vsce package" command and found that it has a size of more than 50 m. Why don't you release it after compression

**Comment by yoyo930021** [comment]
If you try to use `yarn prepare-publish` ?

**Comment by pagnkelly** [comment]
It's still large.I hope it's smaller.but I took it.so, don't care about it

**Comment by octref** [comment]
The latest release is 37M. Most of it comes from the server's dependencies. If you find a low-hanging fruit to reduce the size please let us know.
