### ISSUE TITLE
Multiline comments in Stlyes move on every save

### ISSUE THREAD

**Issue by mubaidr** [vuejs/vetur#203]
I have tried searching but could not find this bug reported, except this one, https://github.com/octref/vetur/issues/99, which is very close but related for script tag (and not commented code). Behaviour is very similar but happens to comments in style tags.

Steps to reproduce:
-Create vue single file component
-Add multi-line comment to styles tag
-Save file multiple times.

A new Tab indent will be added to multi-line comments (from 2nd line) with every save action.

**Comment by octref** [comment]
This is a bug for js-beautify...
I'll see what I can do.

**Comment by mubaidr** [comment]
Ohh... Wrong place for the bug/issue then. You can close this one.

**Comment by octref** [comment]
No worries, I'll file a bug on js-beautify side. And there is a way I can avoid this bug on my side too.

**Comment by mubaidr** [comment]
Ok Great! Thanks

**Comment by liamwang** [comment]
![2017-06-08_14-39-10](https://user-images.githubusercontent.com/5000396/26915511-e0bb3ece-4c58-11e7-8e7f-9fe225e719dd.gif)

**Comment by ericcirone** [comment]
Not sure if it is a js-beautify bug. When i turn off Vetur and format my document with Beautify, which uses js-beautify, this does not happen.

**Comment by octref** [comment]
Now css/scss/less regions use prettier and does not move multiline comments around.

js-beautify for html is disabled by default and is deprecated. I'll eventually remove it in the future. Report all bugs to js-beautify. Changelog here: https://github.com/vuejs/vetur/blob/master/CHANGELOG.md#vetur-formatting-changes
