### ISSUE TITLE
Standalone Vetur service for pre-commit and CI pipelines

### ISSUE THREAD

**Issue by vegerot** [vuejs/vetur#2036]
- [x] I have searched through existing issues

## Feature Request

Vetur is great, and can do things other services (like `vue/eslint`) can't.  I was hoping there could be a way to integrate some of Vetur's features into our CI workflow.  For example, I would like for there to be a way **outside of VSCode** to get warnings like
```ts
Object is possibly 'null'.Vetur(2531)
```

So either if Vetur made an eslint rule to identify this, or if there were a standalone vetur executable so that I could run `vetur src/**/*.vue` in my CI flow in addition to ESlint to print these warnings.

**Comment by rchl** [comment]
Haven't tried it myself but see https://vuejs.github.io/vetur/vti.html

**Comment by yoyo930021** [comment]
You can try to use `vti`,
and follow #1635 and new release for #1805.

**Comment by vegerot** [comment]
@yoyo930021 I made a comment in that first thread about how it does not do what I thought it would do.  Not sure if this is a bug or what

**Comment by yoyo930021** [comment]
> @yoyo930021 I made a comment in that first thread about how it does not do what I thought it would do. Not sure if this is a bug or what

You can add a issue and provide a reproducible case.
Let's debug about this problem.
