### ISSUE TITLE
vetur 支持 <script type='text/x-template'>的语法提示和格式化吗？

### ISSUE THREAD

**Issue by LFDCC** [vuejs/vetur#2039]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: win
- Vetur/VLS version:v0.24.0
- VS Code (or other LSP client) version:1.47.1

## Problem

<script type='text/x-template'>这种模板内代码无法语法提示和格式化吗？我试过了没什么效果

**Comment by yoyo930021** [comment]
I think it's not supported.

**Comment by octref** [comment]
We only support blocks specified here: https://vuejs.github.io/vetur/highlighting.html
