### ISSUE TITLE
Component props auto-completion doesn't work when using PascalCase

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vetur#2049]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.25.0
- VS Code version: 1.47.2

## Problem

Props auto completion works when using `<kebab-case/>` components:

<img width="632" alt="Screen Shot 2020-07-22 at 12 32 13 PM" src="https://user-images.githubusercontent.com/499550/88202927-8cfe1f80-cc17-11ea-9fea-78f2d081f060.png">

...but not with `<PascalCase/>`:

<img width="654" alt="Screen Shot 2020-07-22 at 12 32 26 PM" src="https://user-images.githubusercontent.com/499550/88202966-97201e00-cc17-11ea-98b7-0019d629e06f.png">

Also, component name completion is currently also `<kebab-case/>` only:

<img width="791" alt="Screen Shot 2020-07-22 at 12 34 42 PM" src="https://user-images.githubusercontent.com/499550/88203068-bd45be00-cc17-11ea-9285-ab20dd740da0.png">

Would be nice to have the component name auto-completion to be based on the exact registered name.

**Comment by octref** [comment]
> Also, component name completion is currently also <kebab-case/> only:

Actually, after configuring `"vetur.completion.tagCasing": "initial"`, this works as expected.
