### ISSUE TITLE
[vti] handle component with async setup

### ISSUE THREAD

**Issue by cexbrayat** [vuejs/vetur#2050]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- VTI version: v0.0.4

## Problem

When a component uses an async setup, then `vti` thinks the returned variable in `setup` are not available.

## Reproducible Case

Repo: https://github.com/cexbrayat/vti-async

```
yarn
yarn dev
npx vti@0.0.4 diagnostics
```

Basic component:

```vue
<template>
  <div>{{ users }}</div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'App',

  async setup() {
    const users = ref<Array<string>>(await Promise.resolve(['Cédric']);
    return { users };
  }
});
</script>
```

Error thrown:
```
File : /Users/ced-pro/Code/vue/vti-async/src/components/HelloWorld.vue
Error: Property 'users' does not exist on type 'ComponentPublicInstance<{}, Promise<{ users: Ref<string[]>; }>, {}, {}, {}, Record<string, any>, VNodeProps & AllowedComponentProps & ComponentCustomProps, ComponentOptionsBase<...>>'.
```

**Comment by yoyo930021** [comment]
@ktsn
I think we need to unwrap `Promise` type,
Or modify upstream type definition?

**Comment by ktsn** [comment]
It looks like an upstream type declaration issue.

**Comment by cexbrayat** [comment]
The issue is till here with latest Vue 3.0.0-rc.10 and latest vti 0.0.10
@ktsn when you refer to an upstream issue, do you mean a core `vue-next` issue? Should we open an issue there?

**Comment by yoyo930021** [comment]
> The issue is till here with latest Vue 3.0.0-rc.10 and latest vti 0.0.10
> @ktsn when you refer to an upstream issue, do you mean a core `vue-next` issue? Should we open an issue there?

I open a issue in `vue-next`.

**Comment by cexbrayat** [comment]
Closing, as this has been fixed upstream

**Comment by IlyaSemenov** [comment]
Any chance for this to be backported to vue2?
