### ISSUE TITLE
Use Vetur-bundled prettier for .js files

### ISSUE THREAD

**Issue by tobiasfeil** [vuejs/vetur#2054]
- [ x] I have searched through existing issues
- [ x] I have read through [docs](https://vuejs.github.io/vetur)
- [ x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

Vetur is formatting my .vue files and properly keeping the rules I set in my vscode settings under `"vetur.format.defaultFormatterOptions.prettier"` for Javascript formatting. However, plain `.js` files (like mixins) aren't formatted accordingly. Is this possible?

**Comment by yoyo930021** [comment]
You can use `.prettierrc` file ?

**Comment by tobiasfeil** [comment]
Yes, I put a .prettierrc with the contents of 
```
{
    "semi": false,
    "singleQuote": true,
    "trailingComma": "none",
    "arrowParens": "avoid"
}
``` at the project root, but still nothing is happening

**Comment by yoyo930021** [comment]
Use prettier CLI or prettier VSCode extension?

**Comment by tobiasfeil** [comment]
None of the above, Vetur-bundled prettier (which is formatting scripts in .vue files perfectly)

**Comment by yoyo930021** [comment]
We can do this, but It out of range for this extension.
Vetur bundled prettier is same as CLI or prettier extension.

**Comment by tobiasfeil** [comment]
OK thx!
