### ISSUE TITLE
Make vue-html syntax highlighter support script and style tag content

### ISSUE THREAD

**Issue by IcyFoxe** [vuejs/vetur#2055]
- [x] I have searched through existing issues

## Feature Request

Would it be possible to add **support for JavaScript and Style tags** within vue-html syntax highlighter?
I think it would be pretty useful.

Here's a preview of regular **html** highlighter compared to **vue-html** one:
https://i.imgur.com/h1PcWxB.jpg

**Comment by yoyo930021** [comment]
I think you can use `vue` syntax highlighter.
