### ISSUE TITLE
Highlight partially working

### ISSUE THREAD

**Issue by vandelpavel** [vuejs/vetur#2059]
- [* ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [* ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows
- Vetur version: 0.25
- VS Code version: Version: 1.47.2 (user setup)

## Problem

Suddenly vetur highlight on .vue files stopped working. Now some key-words are not colored like normal.
https://user-images.githubusercontent.com/61196133/88411115-abab1480-cdd7-11ea-8ef3-e984802b1f60.png

## Reproducible Case
Open vsc and a random .vue file.

##ALSO

I unistalled all my extension and re installed them.
I use:
-Babel js
-ESLint
-gitflow
-GitLens
-Prettier
-TODO highlights
-obviously vetur

**Comment by yoyo930021** [comment]
If you use any theme?
Probably about this link.
https://code.visualstudio.com/api/extension-guides/color-theme#semantic-colors

**Comment by octref** [comment]
Also, you need to paste the original code here so we can repro it.

**Comment by vandelpavel** [comment]
Yeah i changed the theme to a darker one but i think that's not the point. Later i changed it to the normal after that issue and nothing happened.

@octref wich code did you refer to? The one that i'm trying to highlight?

**Comment by octref** [comment]
> wich code did you refer to? The one that i'm trying to highlight?

Yes

> Also this morning started to normally highlight the text again. I don't know why.

If you can find a reproducible case, feel free to open another issue with a repro case: https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md
