### ISSUE TITLE
vuter  高亮显示不起作用

### ISSUE THREAD

**Issue by zblossom** [vuejs/vetur#2060]
vue 里面的代码还是没有高亮显示

**Comment by yoyo930021** [comment]
1. Please provide a repro case: https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md
2. Please use issue template for information.

**Comment by octref** [comment]
https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md
