### ISSUE TITLE
Turn off dependabot

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#2068]
Some issues that I encountered:

- Too many useless notifications (still managable, just annoying)
- Push some changes -> Dependabot re-runs all PRs and takes up all resources on CI. I have to go to Azure DevOps to cancel/delete all dependabot builds so PR builds can run

@ktsn Do you know a good solution to those issues?

**Comment by ktsn** [comment]
As for the second issue, we may be able to avoid Dependabot rebasing PRs by switching off the option `Automatically rebase Dependabot PRs when they have conflicts`. It's organization-level configuration, though.

![Screen Shot 2020-07-29 at 8 56 50 PM](https://user-images.githubusercontent.com/2194624/88802849-375ce080-d1de-11ea-869a-e4447ad03650.png)

**Comment by octref** [comment]
> Automatically rebase Dependabot PRs when they have conflicts

Would that solve the issue? Because if I push a change to master, that means all dependabot PRs will rebase -> trigger new builds...

**Comment by octref** [comment]
Updated the config and should be better now. Thanks for chiming in @ktsn.
