### ISSUE TITLE
Cannot find name slotVariable when using v-slot in component, in multiple lines

### ISSUE THREAD

**Issue by amoshydra** [vuejs/vetur#2094]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.25.0
- VS Code version: 1.47.3 & 1.48.0-insider

### Output > Vue Language Server
No error

### Problems
```json
{
	"resource": "retracted:/test-vetur/componentA.vue",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'slotVariable'.",
	"source": "Vetur",
}
```

#### Description

Error with detecting slot's variables with when:
1. v-slot syntax is written directly on the component
2. v-slot syntax is written on the next line

See ComponentA in the screenshot below

![image](https://user-images.githubusercontent.com/8733840/89128863-23411800-d52b-11ea-8738-d04d1f17c5cc.png)

#### `ComponentA`

```vue
<template>
  <Parent
    v-slot="{ slotVariable }"
  >
    {{ slotVariable }}
  </Parent>
</template>
```

##### Virtual content

```js
import __vlsComponent from "./ComponentA.vue";
import {
    __vlsRenderHelper,
    __vlsComponentHelper,
    __vlsIterationHelper
} from "vue-editor-bridge";
__vlsRenderHelper(__vlsComponent, function() {
    () => __vlsComponentHelper(this, "parent", {
        props: {},
        on: {},
        directives: []
    }, [slotVariable]);
});
```

#### `ComponentB`

```vue
<template>
  <Parent v-slot="{ slotVariable }">
    {{ slotVariable }}
  </Parent>
</template>
```

##### Virtual content

```js
import __vlsComponent from "./ComponentA.vue";
import {
    __vlsRenderHelper,
    __vlsComponentHelper,
    __vlsIterationHelper
} from "vue-editor-bridge";
__vlsRenderHelper(__vlsComponent, function() {
    ({
        slotVariable
    }) => __vlsComponentHelper(this, "parent", {
        props: {},
        on: {},
        directives: []
    }, [slotVariable]);
});
```

#### `ComponentC`

```vue
<template>
  <Parent>
    <template v-slot="{ slotVariable }">
      {{ slotVariable }}
    <template>
  </Parent>
</template>
```

**Comment by amoshydra** [comment]
I found out that this issue only appear when the file is using CRLF.

And the error occurs in here:
https://github.com/vuejs/vetur/blob/271dbfcd9b1be62f847e6edf0041ee0775ee2f91/server/src/services/typescriptService/transformTemplate.ts#L588-L592

Using example for ComponentA

### CRLF
```ts
{
  start: 36,
  end: 52,
  code = "<template>\r\n  <Parent\r\n    v-slot=\"{ slotVariable }\"\r\n  >\r\n    {{ slotVariable }}\r\n  </Parent>\r\n            \n</template>",
  paramsStr: " slotVariable }\""
}
```

### LF
```ts
{
  start: 33,
  end: 49,
  code = "<template>\n  <Parent\n    v-slot=\"{ slotVariable }\"\n  >\n    {{ slotVariable }}\n  </Parent>\n           \n</template>",
  paramsStr: "{ slotVariable }"
}
```

**Comment by amoshydra** [comment]
I think this should be related to `vue-eslint-parser`
- https://github.com/vuejs/vetur/issues/1319#issuecomment-586124875
    - https://github.com/mysticatea/vue-eslint-parser/pull/74

I guess we will need to wait for https://github.com/mysticatea/vue-eslint-parser/pull/74

**Comment by yoyo930021** [comment]
Fixed in https://github.com/vuejs/vetur/commit/062d747d0c7584e38e4df2f3570d96638cfcbbe0.
But it is not released.
