### ISSUE TITLE
Latest plugin isn't allow eslint override

### ISSUE THREAD

**Issue by wonbyte** [vuejs/vetur#2113]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS 10.15.6
- Vetur version: 0.26.0
- VS Code version: 1.47.3

## Problem

After updating the vetur plugin to the latest version today, I am now seeing eslint errors for 
`[vue/valid-v-slot]'v-slot' directive doesn't support any modifier.`. When I try to turn this rule off following the docs here: https://vuejs.github.io/vetur/linting-error.html#linting it is not working.

<img width="1628" alt="Screen Shot 2020-08-04 at 5 05 37 PM" src="https://user-images.githubusercontent.com/681965/89349955-ba65b700-d674-11ea-9b66-b1aeec3776a8.png">

```
[vue/valid-v-slot]
'v-slot' directive doesn't support any modifier.
```

## Reproducible Case
1. Update to the latest vetur plugin.
2. Open a file with a template slot that uses the dot modifier.

**Comment by octref** [comment]
Are you using vue2 or vue3?
When you turn off Vetur's linting, you should set `vetur.validation.template: false`. Did you do that?

**Comment by wonbyte** [comment]
I'm on a standard Vue 2 app with the default eslintrc generated by the Vue cli. After updating vetur the error started so are you suggestion I turn off template validation to get rid of it?

**Comment by wonbyte** [comment]
Turning off the `vetur` template validation does allow me to suppress the error. Any idea why it started after upgrading to the latest `vetur` plugin version? Did something change in the bundled `eslint` setup?

**Comment by yoyo930021** [comment]
> Vue 2. Turning off the `vetur` template validation does allow me to suppress the error. Any idea why it started after upgrading to the latest `vetur` plugin version? Did something change in the bundled `eslint` setup?

Follow up #2015. 
We upgrade `eslint-plugin-vue` version to `7.0.0-beta.0` for vue 3 support.

**Comment by yoyo930021** [comment]
We will provide vue template validation with `eslint-plugin-vue`.
So it is not related to eslint config.

**Comment by wonbyte** [comment]
@yoyo930021 yep, I was able to turn off the `vetur` linting and use the `eslint` for now so that I can turn that error off. I assume once vue 3 is released that error should no longer appear when using `vetur`?

**Comment by yoyo930021** [comment]
> @yoyo930021 yep, I was able to turn off the `vetur` linting and use the `eslint` plugin for now. I assume once vue 3 is released that error should no longer appear when using `vetur`?

Can we add modifier in `v-slot` when vue 3?
I can't find related rfcs.

**Comment by mentAl-maZe** [comment]
@octref 
> Are you using vue2 or vue3?
> When you turn off Vetur's linting, you should set `vetur.validation.template: false`. Did you do that?

If I turn off `vetur.validation.template` i get linting by eslint but i loose linting on interpolated js... is there a way to circumvent this?

**Comment by wonbyte** [comment]
> > @yoyo930021 yep, I was able to turn off the `vetur` linting and use the `eslint` plugin for now. I assume once vue 3 is released that error should no longer appear when using `vetur`?
> 
> 
> 
> Can we add modifier in `v-slot` when vue 3?
> 
> I can't find related rfcs.

Good question. Closest thing I've found is https://github.com/vuejs/vue-next/issues/1241 but I'm not sure what they finalized on....

**Comment by octref** [comment]
@mentAl-maZe #1293. I'll fix that for the next release.

**Comment by haiarha** [comment]
For now, I disable latest extension and install `v0.24.1`:
https://marketplace.visualstudio.com/items?itemName=hikerpig.vetur

**Comment by yoyo930021** [comment]
> For now, I disable `latest` extension and install `v0.24.1`:
> https://marketplace.visualstudio.com/items?itemName=hikerpig.vetur

You can set `vetur.validation.template: false`.

**Comment by haiarha** [comment]
@yoyo930021 But i need validation in the file 😭

**Comment by haiarha** [comment]
> If I turn off vetur.validation.template i get linting by eslint but i loose linting on interpolated typescript... is there a way to circumvent this?

@mentAl-maZe For me this fork fits perfectly:
> I disable latest extension and install v0.24.1:
> https://marketplace.visualstudio.com/items?itemName=hikerpig.vetur

**Comment by mentAl-maZe** [comment]
@octref Thx :+1: 

@haiarha I'll wait for the next release to drop, in the meantime I'll just have to be a bit more careful about my variables :sweat_smile:

**Comment by yoyo930021** [comment]
The v0.26.1 is release.

**Comment by benwinding** [comment]
Well I can confirm that this is still an issue in vetur `0.31.3`.
- `vetur.validation.template: false` in settings works, but you lose a lot of other error checking too
- It would be great to support this option here: https://eslint.vuejs.org/rules/valid-v-slot.html#options
- This fork of the extension works as expected https://marketplace.visualstudio.com/items?itemName=hikerpig.vetur

**Comment by yoyo930021** [comment]
> Well I can confirm that this is still an issue in vetur `0.31.3`.
> 
>     * `vetur.validation.template: false` in settings works, but you lose a lot of other error checking too
> 
>     * It would be great to support this option here: https://eslint.vuejs.org/rules/valid-v-slot.html#options
> 
>     * This fork of the extension works as expected https://marketplace.visualstudio.com/items?itemName=hikerpig.vetur

The `vetur.validation.template: false` option is only disable eslint built-in rule and template prop.
You don't lose a lot of other error checking.
https://vuejs.github.io/vetur/linting-error.html#linting

This built-in feature is only design in basic project.
The strong use of ESLint to replace this feature.

**Comment by garyo** [comment]
Newbie question: where to set `vetur.validation.template: false`? I'm using emacs with vls on Linux (WSL). I have a `.eslintrc.js` but no vetur config files in my project. I tried creating `vetur.config.js` per https://vuejs.github.io/vetur/reference/#example but it seemed to have no effect on this error.
