### ISSUE TITLE
Assertion Failed error on server stop

### ISSUE THREAD

**Issue by wonbyte** [vuejs/vetur#2114]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS 10.15.6
- Vetur version: 26.0
- VS Code version: 1.47.3

## Problem
When starting my vue application via the vscode terminal when I use `Ctrl + c` to stop it I am getting the following error:

```
 DONE  Compiled successfully in 270ms                                                                                                                                       4:59:49 PM

  App running at:
  - Local:   http://localhost:8080/ 
  - Network: http://192.168.86.57:8080/

^CAssertion failed: (0), function uv_close, file ../deps/uv/src/unix/core.c, line 174.
[1]    15803 abort      npm run serve
```

<img width="1316" alt="Screen Shot 2020-08-04 at 5 13 17 PM" src="https://user-images.githubusercontent.com/681965/89350515-cd2cbb80-d675-11ea-83e7-ddae8a64c688.png">

## Reproducible Case

1. Use latest vetur plugin
2. start a vue app via the `vscode` terminal.
3. use `ctrl + c` to stop the server.

**Comment by octref** [comment]
That's an issue for vue-cli, not Vetur.
