### ISSUE TITLE
Formatting not working with version 0.26.0

### ISSUE THREAD

**Issue by csicky** [vuejs/vetur#2116]
## Problem
After update to 0.26.0 format does not work anymore. I have reverted using vsix package to 0.25.0 and the format works again. I have a lot of extensions, might be a conflict. Please let me know if you need to export some config and how to do it. With so many settings and extensions configs I can't tell why it was working and why it is not with latest version. Might be Prettier or eslint not working well with latest version of Vetur.

![image](https://user-images.githubusercontent.com/3931907/89388312-8342e480-d70c-11ea-98b3-21bcf24e3714.png)

**Comment by yoyo930021** [comment]
Please give your `vetur` formatting setting.
https://vuejs.github.io/vetur/formatting.html#formatters

You can see [CHANGELOG](https://github.com/vuejs/vetur/blob/master/CHANGELOG.md) and commit.

**Comment by csicky** [comment]
THX for help, one more question please :)

What formatting config to give to vetur to make it work like is in version 0.25.0? I would have preferred that this is migrated automatically and I don't have to come here asking questions as I don't have that much time, but now that we are here, the page you linked doesn't tell me which one to choose.

Now looking there and I have formatters selected. For some reason 0.26.0 doesn't pick them up?

![image](https://user-images.githubusercontent.com/3931907/89391503-fb130e00-d710-11ea-93ef-c8be8554dfc5.png)

**Comment by yoyo930021** [comment]
> THX for help, one more question please :)
> 
> What formatting config to give to vetur to make it work like is in version 0.25.0? I would have preferred that this is migrated automatically and I don't have to come here asking questions as I don't have that much time, but now that we are here, the page you linked doesn't tell me which one to choose.
> 
> Now looking there and I have formatters selected. For some reason 0.26.0 doesn't pick them up?
> 
> ![image](https://user-images.githubusercontent.com/3931907/89391503-fb130e00-d710-11ea-93ef-c8be8554dfc5.png)

I need to know what are you used for formatting.

**Comment by yoyo930021** [comment]
I guess it's a bug for `prettier-eslint` and `vetur`.
Short term:
1. install `prettier-eslint` in your project, and notice https://github.com/prettier/prettier-eslint/pull/359.
2. Not use `prettier-eslint`.


@octref I think we need to downgrade `prettier-eslint` version.
https://github.com/vuejs/vetur/commit/56df0f3fa4e445629819fc84181f8a2dfd770efb

**Comment by csicky** [comment]
So, for now I can keep using 0.25.0. Thank you for your help.

**Comment by yoyo930021** [comment]
The v0.26.1 is release.

**Comment by csicky** [comment]
I am sorry to report that the problem was not resolved. I have upgraded to 0.26.1 and the format is not working. If you need some debugging info, please let me know what to do to export it. It is very well possible that I have some old config which might conflict. In the meantime I go back to 0.25.0 so I can work.

**Comment by yoyo930021** [comment]
> I am sorry to report that the problem was not resolved. I have upgraded to 0.26.1 and the format is not working. If you need some debugging info, please let me know what to do to export it. It is very well possible that I have some old config which might conflict. In the meantime I go back to 0.25.0 so I can work.

Please provide reproducible case.
https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md

**Comment by csicky** [comment]
It seems I will stay on 0.25.0 as I don't have time to do that repro thing.
