### ISSUE TITLE
Test tag in SFC

### ISSUE THREAD

**Issue by Thomas-git** [vuejs/vetur#2119]
- [x] I have searched through existing issues

## Feature Request

It would be great to have syntax highlight in <test> tag for SFC vue file.
It should be as easy as highlighting the script tag.
It would be even better if using "lang" attribute for better completion.
`<test lang="jest">
</test>`

`<test lang="ava">
</test>`

**Comment by octref** [comment]
You can use `"vetur.grammar.customBlocks"`.
