### ISSUE TITLE
Component Data - `type: 'boolean'` should trigger completion without `=""`

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#2127]
For example, now installing `element-ui` and completing `<el-tree expand-on-click-node=""></el-tree>`. `expand-on-click-node` has type boolean and should trigger a completion like `expand-on-click-node`, not `expand-on-click-node=""`.

**Comment by rchl** [comment]
I must just add a note that it's a bit of a preference thing too.

Some projects I work with prefer to use `:expand-on-click-node="true"`, to be explicit.
`expand-on-click-node=""` is wrong for sure as it doesn't start with the colon but I wonder if it would be possible to support both options (`expand-on-click-node` and `:expand-on-click-node="true"`).

If not then I can live with it I guess. Maybe will consider switching to `expand-on-click-node` variant.

**Comment by rchl** [comment]
Thinking more about it, the `:expand-on-click-node=""` variant would be more universal so the default value is not always `false` so you might actually want to write `:expand-on-click-node="false"`. Having the short form by default would require more work to then switching to the long form.

**Comment by octref** [comment]
> the default value is not always false

I'd say that's a minority case. That's not consistent with HTML5's boolean attributes.

When user attempts to type a boolean attribute, I think they are way more likely to use it for the truthy value, so I should make that easier for them.

In majority case, having to `delete` twice is worse than in the minority case, having to type `="`.

**Comment by rchl** [comment]
Yeah, OK.

**Comment by octref** [comment]
Associated with wrong commit...
