### ISSUE TITLE
Property 'xxx' does not exist on type 'CombinedVueInstance<Record<never, any> & Vue, object, object, object, Record<never, any>>'

### ISSUE THREAD

**Issue by mateonunez** [vuejs/vetur#2131]
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)

## Info

- Platform: Windows x64 
- Vetur version: 0.26.1
- VS Code version: 1.47.3

## Problem

Updating Vetur into the last release I get an error in each property in `html component`, `computed`, `methods`, `events`, etc.

```
Property 'styleRow' does not exist on type 'CombinedVueInstance<Record<never, any> & Vue, object, object, object, Record<never, any>>'
```
This is my method:
```js
styleRow(row) {
   return `background-color: ${
     row.order && row.order.category ? row.order.category.color : '#ffffff'
   }`
}
```

## Reproducible Case

Not reproducible by a project.

**Comment by jtsom** [comment]
Same here. Big problem...

**Comment by yoyo930021** [comment]
Please provide reproducible case.
https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md

**Comment by jtsom** [comment]
Unfortunately, for me, I can't send along the project that is having this issue. I am trying to recreate it in a small, sample application, but the error is not showing. This error is showing for some props, some computed items and some methods. Not all, which is making it hard to track down. I would suggest, if you have several Vue apps, as I'm sure you do, open each one and see if the error appears.

**Comment by yoyo930021** [comment]
> Unfortunately, for me, I can't send along the project that is having this issue. I am trying to recreate it in a small, sample application, but the error is not showing. This error is showing for some props, some computed items and some methods. Not all, which is making it hard to track down. I would suggest, if you have several Vue apps, as I'm sure you do, open each one and see if the error appears.
> 
> A sample of the error:
> ![image](https://user-images.githubusercontent.com/13488/89650844-08ef9d00-d891-11ea-838c-ab35296f6047.png)
> 
> The item it claims does not exist, clearly does:
> ![image](https://user-images.githubusercontent.com/13488/89650901-1c026d00-d891-11ea-938f-72c6ec2db58c.png)
> 
> BTW, this is in a Javascript application - NO Typescript is being used.

If I don't have case, debugging is too hard.
Can you reproduce the same code every time?

If yes, I think #1707 or vuejs/vue#8721 ?

**Comment by jtsom** [comment]
> > Unfortunately, for me, I can't send along the project that is having this issue. I am trying to recreate it in a small, sample application, but the error is not showing. This error is showing for some props, some computed items and some methods. Not all, which is making it hard to track down. I would suggest, if you have several Vue apps, as I'm sure you do, open each one and see if the error appears.
> > A sample of the error:
> > ![image](https://user-images.githubusercontent.com/13488/89650844-08ef9d00-d891-11ea-838c-ab35296f6047.png)
> > The item it claims does not exist, clearly does:
> > ![image](https://user-images.githubusercontent.com/13488/89650901-1c026d00-d891-11ea-938f-72c6ec2db58c.png)
> > BTW, this is in a Javascript application - NO Typescript is being used.
> 
> If I don't have case, debugging is too hard.
> Can you reproduce the same code every time?
> 
> If yes, I think #1707 or [vuejs/vue#8721](https://github.com/vuejs/vue/issues/8721) ?

Yes in one project, no in another. Both of those issues relate to Typescript projects. Again, this is not Typescript, straight Javascript, so I cannot add type annotations.

**Comment by rchl** [comment]
@jtsom you **need** to add annotations in JS code too. Vetur will only be able to automatically infer types for trivial things like literals and others. Anything more complicated **needs** annotations. And yes, you can annotate stuff in JS - use JSDoc for that. if you are not doing that then don't expect things to work flawlessly.

**Comment by rchl** [comment]
I just found this blog post that should explain it more: https://blog.usejournal.com/type-vue-without-typescript-b2b49210f0b

Any non-trivial props, data options, computed values, methods, etc. need to be annotated.

**Comment by jtsom** [comment]
That document says "We have to provide @type annotations for properties which are impossible infer statically." Except, my data properties are all simple strings, so should not need types (see above). Also, in another small application, I am not seeing this error, and the data properties are also simple types:

![image](https://user-images.githubusercontent.com/13488/89659080-5d991500-d89d-11ea-8980-d59c7e85afa9.png)

Not to mention, what changed in a .1 update that would cause this big change in functionality.

**Comment by rchl** [comment]
You need to know that if you are missing some annotations in other places in the Vue file, that can break type checking in that file in general.

So add all annotations where needed or simplify your file until it doesn't reproduce.

If nothing helps then create a repro as we can't be guessing forever here.

**Comment by jtsom** [comment]
How would you annotate Vuex getters? on the getter itself in the store? on the ...mapGetters( .. ) call?
Again, I have to ask, what changed in the latest update to cause all of these issues? To go through my javascript and add @type is going to be a huge task.

**Comment by yoyo930021** [comment]
It's a bug on upsteam.
The temporary solution is used JSDoc.

**Comment by jtsom** [comment]
Well, for me, temporary solution is to downgrade to the previous version until this is fixed.

**Comment by mateonunez** [comment]
I've downgraded too to the `0.26.0` version.

**Comment by yoyo930021** [comment]
> Well, for me, temporary solution is to downgrade to the previous version until this is fixed.

You can't downgrade to fix it.
The only possible way is to install TypeScript 2.9 in project,
And set `"vetur.useWorkspaceDependencies": true`

**Comment by yoyo930021** [comment]
> I've downgraded too to the `0.26.0` version.
If this work in v0.26.0?

**Comment by jtsom** [comment]
I downgraded to v0.26.0 and all of those errors went away.

**Comment by mateonunez** [comment]
Yes, it is working on `v0.26.0`.

**Comment by yoyo930021** [comment]
I think the problem is not what I think.
@mateonunez @jtsom 
Please try to provide reproducible case.
Otherwise it’s really hard to debug.

**Comment by jtsom** [comment]
Believe me, I am trying to. A simple app that is structured the same as my more complicated app won't show the error. Simple components in my large app has several errors, but a more complicated component has none. They have the same data, methods, computed sections, and make heavy use of Vuex getters.

**Comment by jtsom** [comment]
Here is a reproducible component. If you change the computed to return a string, the error will go away. As it is, it shows these errors:

![image](https://user-images.githubusercontent.com/13488/89663666-df8c3c80-d8a3-11ea-90fc-1f4c5ba46d3b.png)

```
<template>
<div class='hello'>
  {{ title }} {{ testing }}
    <div v-for="item in items">{{ item }}</div>
    <button @click="clickMe">Click me</button>
</div>
</template>

<script>

export default {

  props: {
    testing: { type: String }
  },
  computed: {
    title() {      
      return this.testing === 'hello'; // ** change to just return a string to remove error
    }
  },
  methods: {
    clickMe() {
      console.log('click');
    }
  },
  data() {
    return {
      items: ['item1', 'item2', 'item3', 'item4', 'item5'],

      items2: []
    };
  }
};
</script>
```

**Comment by yoyo930021** [comment]
> Here is a reproducible component. If you change the computed to return a string, the error will go away. As it is, it shows these errors:
> 
> ![image](https://user-images.githubusercontent.com/13488/89663666-df8c3c80-d8a3-11ea-90fc-1f4c5ba46d3b.png)
> 
> ```
> <template>
> <div class='hello'>
>   {{ title }} {{ testing }}
>     <div v-for="item in items">{{ item }}</div>
>     <button @click="clickMe">Click me</button>
> </div>
> </template>
> 
> <script>
> 
> export default {
> 
>   props: {
>     testing: { type: String }
>   },
>   computed: {
>     title() {      
>       return this.testing === 'hello'; // ** change to just return a string to remove error
>     }
>   },
>   methods: {
>     clickMe() {
>       console.log('click');
>     }
>   },
>   data() {
>     return {
>       items: ['item1', 'item2', 'item3', 'item4', 'item5'],
> 
>       items2: []
>     };
>   }
> };
> </script>
> ```

This problem is #1707 and vuejs/vue#8721 
It's upstream problem and v0.26.0 also have error.
The v0.26.1 is only change can use template  interpolation when `vetur.validation.template: false`.
If you no need template interpolation, please set `vetur.experimental.templateInterpolationService: false`

**Comment by jtsom** [comment]
Weird. Because v0.26.0 did not have that error, as as far as I know I did not have that option turned on.

Either way, turning that option off did eliminate the error using v.0.26.1

Hopefully this will get fixed soon.

(I assume by "template interpolation service" you mean like: <span>{{ card.label }}</span> ? or is that something else? )

**Comment by yoyo930021** [comment]
Template interpolation service 
https://vuejs.github.io/vetur/interpolation.html#generic-language-features

**Comment by yoyo930021** [comment]
Maybe this option have a problem.

**Comment by jtsom** [comment]
> Template interpolation service
> https://vuejs.github.io/vetur/interpolation.html#generic-language-features

Hm. Ok. I do remember reading that article and I did turn that option on. Up until v0.26.1 I had no issues. Having that option on using v0.26.1, results in the reported errors. Turning it off remove the errors. So something in 0.26.1 triggered the problem.

**Comment by yoyo930021** [comment]
> Here is a reproducible component. If you change the computed to return a string, the error will go away. As it is, it shows these errors:
> 
> ![image](https://user-images.githubusercontent.com/13488/89663666-df8c3c80-d8a3-11ea-90fc-1f4c5ba46d3b.png)
> 
> ```
> <template>
> <div class='hello'>
>   {{ title }} {{ testing }}
>     <div v-for="item in items">{{ item }}</div>
>     <button @click="clickMe">Click me</button>
> </div>
> </template>
> 
> <script>
> 
> export default {
> 
>   props: {
>     testing: { type: String }
>   },
>   computed: {
>     title() {      
>       return this.testing === 'hello'; // ** change to just return a string to remove error
>     }
>   },
>   methods: {
>     clickMe() {
>       console.log('click');
>     }
>   },
>   data() {
>     return {
>       items: ['item1', 'item2', 'item3', 'item4', 'item5']
>     };
>   }
> };
> </script>
> ```
> 
> Adding type annotations (assuming I'm doing it correct) does not help:
> 
> ![image](https://user-images.githubusercontent.com/13488/89663892-49a4e180-d8a4-11ea-9386-18ea0cfe0692.png)

@jtsom 
If this code is work in v0.26.0?

**Comment by rchl** [comment]
> Adding type annotations (assuming I'm doing it correct) does not help:
> 
> ![image](https://user-images.githubusercontent.com/13488/89663892-49a4e180-d8a4-11ea-9386-18ea0cfe0692.png)

Those annotations are not correct.
Computed property should have
```js
/** @returns {boolean} */
```
and data should have
```js
/** @returns {{ items: string[] }} **/
```
(although personally I haven't tried annotating whole data like that. I usually annotate individual properties of returned object with `/** @type {foo} */`.

I guess there is a regression in typescript that makes it fail to infer data that it should be able to infer but even without the regression, sometimes you just need to annotate stuff as it won't be able to infer automatically.

**Comment by jtsom** [comment]
> @jtsom
> Is this code work in v0.26.0?

Yup. No errors with v0.26.0:

![image](https://user-images.githubusercontent.com/13488/89666674-c639bf00-d8a8-11ea-9f00-dec103de00ea.png)

**Comment by rchl** [comment]
No errors but are types correct in the template? Is template actually type checked?

**Comment by yoyo930021** [comment]
> > @jtsom
> > Is this code work in v0.26.0?
> 
> Yup. No errors with v0.26.0:
> 
> ![image](https://user-images.githubusercontent.com/13488/89666674-c639bf00-d8a8-11ea-9f00-dec103de00ea.png)

You have `vetur.validation.template: false` in your screenshot........................
In v0.26.0, it will disable template interpolation service.
In v0.26.1, it will not.

**Comment by jtsom** [comment]
> You have `vetur.validation.template: false` config in your screenshot with line 15.
> In v0.26.0, it will disable template interpolation service.
> In v0.26.1, it will not disable.

Ah, yes. setting 'Vetur.validation.template: true' does now show the errors in v0.26.0:

![image](https://user-images.githubusercontent.com/13488/89667528-47458600-d8aa-11ea-8e2b-476820c5e72c.png)

Fixing up the type annotations also makes the errors go away.

**Comment by octref** [comment]
I think the solution is to have a config that controls `templateInterpolationDiagnostics`.

For completion/definition/reference/hover, people should still be able to use them without having to fully type their components.

I think it's time we move interpolation service out of experimental status and fix all remaining issues.

How about adding `vetur.validation.interpolation`, defaulted to false?
Completion/definition/reference/hover powered by template interpolation service can be turned on by default.

**Comment by yoyo930021** [comment]
I think I need to promote this PR on upsteam.
https://github.com/vuejs/vue/pull/11235

**Comment by jtsom** [comment]
If either of those solutions will help eliminate those errors, especially if there aren't any type declarations, then I'm all for it. Adding type information to my existing project would be difficult to impossible - type declarations for Vuex store items (...mapGetters, etc.) is no simple task! Until then, I will keep this option turned off. (Vue / Vetur / VSCode / JS have never been the easiest environment to work with, I've come to deal with the quirks / difficulties, so...)

**Comment by yuchenliu15** [comment]
> I've downgraded too to the `0.26.0` version.

same, this worked for me

**Comment by DeannaBonds** [comment]
I downgraded too.   Only solution I could find.   It seemed to want types in javascript and I can't change 1000's of lines of code just for this.

**Comment by Pedroprt** [comment]
I found in .vscode folder a file settings.json

{
"vetur.validation.template": false,

"eslint.validate": ["javascript", "javascriptreact", "typescript", "vue"],

"vetur.experimental.templateInterpolationService": true (change this to false. It worked for me)
}

**Comment by nicong622** [comment]
I found that this error is related to the _computed block_ . If i remove the computed block , i will not get this error. Once i have any computed properties, however, i get this error again. Below is an example:

has computed properties:
![image](https://user-images.githubusercontent.com/5938867/90715036-a9a37b00-e2db-11ea-95e3-cbb50bbc5687.png)

no computed properties:
![image](https://user-images.githubusercontent.com/5938867/90715113-e66f7200-e2db-11ea-9a2d-0b37e6fa12ef.png)

**Comment by yoyo930021** [comment]
> I found that this error is related to the _computed block_ . If i remove the computed block , i will not get this error. Once i have any computed properties, however, i get this error again. Below is an example:
> 
> has computed properties:
> ![image](https://user-images.githubusercontent.com/5938867/90715036-a9a37b00-e2db-11ea-95e3-cbb50bbc5687.png)
> 
> no computed properties:
> ![image](https://user-images.githubusercontent.com/5938867/90715113-e66f7200-e2db-11ea-9a2d-0b37e6fa12ef.png)

Known Issues about #1707 or vuejs/vue#8721 
And have a PR to fix it vuejs/vue#11235

**Comment by jtsom** [comment]
And that PR has been sitting there for 5 months... what's holding it up???

**Comment by octref** [comment]
vuejs/vue#11235 does not seem to fix this case for me:

```vue
<template>
  <div>
    {{ fo }}
  </div>
</template>

<script>
import * as _ from 'lodash'

export default {
  props: ['foo', 'bar'],
  
  data() {
    return {
      fo: 1
    }
  },
  
  computed: {
    a() {
      return this.fo + 1
    }
  }
}
</script>
```

**Comment by octref** [comment]
I added `vetur.validation.interpolation`. Default to true.

**Comment by yoyo930021** [comment]
> [vuejs/vue#11235](https://github.com/vuejs/vue/pull/11235) does not seem to fix this case for me:
> 
> ```
> <template>
>   <div>
>     {{ fo }}
>   </div>
> </template>
> 
> <script>
> import * as _ from 'lodash'
> 
> export default {
>   props: ['foo', 'bar'],
>   
>   data() {
>     return {
>       fo: 1
>     }
>   },
>   
>   computed: {
>     a() {
>       return this.fo + 1
>     }
>   }
> }
> </script>
> ```

I study this case.
I find the only way when typescript 3.9. =_=
https://github.com/yoyo930021/vue/tree/fix-type-when-computed-return-this-3.9

**Comment by dyllandry** [comment]
In case others arrive, here's a summary of the current problem, the minimal reproducible example, and what you can do to try and fix it: https://github.com/vuejs/vetur/issues/1707#issuecomment-686851677

**Comment by krushndayshmookh** [comment]
> I've downgraded to the `0.26.0` version and it works.

this worked for me

**Comment by yoyo930021** [comment]
> > I've downgraded to the `0.26.0` version and it works.
> 
> this worked for me

set `vetur.validation.interpolation` false in latest version.

**Comment by krushndayshmookh** [comment]
> > > I've downgraded to the `0.26.0` version and it works.
> > 
> > 
> > this worked for me
> 
> set `vetur.validation.interpolation` false in latest version.

this solves everything. thanks

**Comment by anubhavkamath** [comment]
> > > > I've downgraded to the `0.26.0` version and it works.
> > > 
> > > 
> > > this worked for me
> > 
> > 
> > set `vetur.validation.interpolation` false in latest version.
> 
> this solves everything. thanks

Where is this set?

**Comment by krushndayshmookh** [comment]
> vetur.validation.interpolation

![image](https://user-images.githubusercontent.com/10362528/94824524-c2e32f80-0422-11eb-9957-a74942bae443.png)

**Comment by panamacheng** [comment]
Well, I am not sure, it does work for JS validations.

**Comment by janvorisek** [comment]
Vetur still works well while using class-style components. Because of a smoother transition to Vue 3, we wanted to migrate to options/composition API and having the above mentioned issues.

Interestingly - computed is fine, but adding `components: { AppSidebar, AppFooter },` leads to the same error.

**Comment by yoyo930021** [comment]
> Vetur still works well while using class-style components. Because of a smoother transition to Vue 3, we wanted to migrate to options/composition API and having the above mentioned issues.
> 
> Interestingly - computed is fine, but adding `components: { AppSidebar, AppFooter },` leads to the same error.

If you use Vue3, there's no problem.
Because it is a type defined problem in vue2.
If you use composition API in vue2, almost no problem.
Just remember not to use computed in option API.

**Comment by thefoxie** [comment]
I don't use TS. I'd love to have completion in templates. JSDoc doesn't seem to do anything.

**Comment by yoyo930021** [comment]
> I don't use TS. I'd love to have completion in templates. JSDoc doesn't seem to do anything.

JSDoc can help you.
We can't do anything in this project.
We have discussed this problem with core library maintainers.

**Comment by thefoxie** [comment]
@yoyo930021 can you guide me with the JSDoc? None of the annotations work and I still get the error.
```js
/** @returns { {filteredTags: object} } **/
    data() {
        return {
            /** @type {object} **/
            filteredTags: {
                categories: new filterProperty(),
                media: new filterProperty(),
                orientation: new filterProperty(),
                camera: new filterProperty(),
            },
    }
```

**Comment by thefoxie** [comment]
Doesn't work on simple components with properly defined props.
![obrázok](https://user-images.githubusercontent.com/15309350/100114748-08940580-2e72-11eb-8270-ada87e2773bb.png)

**Comment by thefoxie** [comment]
@yoyo930021 @octref Cloned veturpack to get better idea what's going on and to fiddle around. The repo worked even when I copied parts of the code like props and template but not when I copied all of it. Seems like it works when I get rid of `emits: ["click"]`. Does Vetur support emits option as it produces this bug?

**Comment by thefoxie** [comment]
It appears even when I use `beforeUnmount()`. After a while, I figured out it's because I haven't updated to vue3 on this particular project yet but started to use newer eslint and hooks/options. Everything seems to work with vue3.

**Comment by yoyo930021** [comment]
> @yoyo930021 @octref Cloned veturpack to get better idea what's going on and to fiddle around. The repo worked even when I copied parts of the code like props and template but not when I copied all of it. Seems like it works when I get rid of `emits: ["click"]`. Does Vetur support emits option as it produces this bug?

https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#property-xxx-does-not-exist-on-type-combinedvueinstance

https://github.com/vuejs/vetur/issues/2392

**Comment by dawidstefaniak** [comment]
Setting return types for all functions inside computed solved it for me.

**Comment by thefoxie** [comment]
I get the error even when I set return types sometimes. Disappears after I comment out props.

**Comment by serkon** [comment]
`Property 'doThisInput' does not exist on type 'CombinedVueInstance<Vue, unknown, unknown, unknown, Readonly<Record<never, any>>>'.` 

Also `doThisClick`gave same error.

***Solution:***
I get above error then i have added declaration to component. I solved error using below definitions:

```vue
<script lang="ts">
  import Vue from 'vue';

  declare module 'vue/types/vue' {
    interface Vue {
      fields: Field[];
      doThisClick: () => void;
      doThisInput: () => void;
    }
  }

  export default Vue.extend({
    name: 'form-builder',
    data() {
      return {
        fields: [
          {
            name: 'name',
            events: { click: this.doThisClick, input: this.doThisInput },
          },
        ],
      };
    },
    methods: {
      submit(): void {
        console.log('form will be post');
      },
      forDemo(): void {
        console.log('potato');
      },
      doThisClick(field: Field): void {
        console.log('click', field, event);
      },
      doThisInput(field: Field): void {
        console.log('Input', field, event);
      },
    },
  });
</script>

```

**Comment by caybokotze** [comment]
For *anyone* encountering this issue. I have seen it creep up a few times when using typescript. I'm not sure if it's an issue with `vue-tsc` or something else, but this is the solution to get around the linter warnings/errors.

Normally the issue would look something like this...

```txt
TS2339: Property 'title' does not exist on type 'CombinedVueInstance<Vue, unknown, unknown, unknown, Readonly<Record<never, any>>>'.
```

The solution is to define some types so that Vue is aware of what is trying to be defined in the component. 

*** Example:

```ts
interface IData {
  title: string;
}
interface IProps {

}
interface IComputed {

}
interface IMethods {
 
}
```

*** Define the component

```ts
export default Vue.extend<IData, IMethods, IComputed, IProps>({
   data() {
      title: "Some title"
   }
});
```

Please also note that the order in which you pass your type parameters is important. The order follows DSMC (Data, Methods, Computed, Props).

Hope this helps. If anyone has any other specific questions, please email me. My email is on my Github profile.

**Comment by yoyo930021** [comment]
Please refer https://vuejs.github.io/vetur/guide/FAQ.html#property-xxx-does-not-exist-on-type-combinedvueinstance

I will lock this issue. If you have a problem, please open a new issue with template.
