### ISSUE TITLE
Prop with `required: false` or default value should not trigger prop validation error when not provided

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#2141]
From https://github.com/vuejs/vetur/issues/2135#issuecomment-670841767

**Comment by octref** [comment]
- Use `DiagnosticSeverity.Error` for passing an undeclared prop
- When not passing a required prop
  - If in array form, show a warning with `DiagnosticSeverity.Warning` (as all props are optional)
  - If in object form, only show error if required props are not passed. For example, if a component requires `foo` and takes an `optional` bar, not passing `bar` should not generate an error.

**Comment by yoyo930021** [comment]
When no prop:
```
// case 1 -> warning
props: [foo, bar]
// case 2 -> warning
props: {
  foo: String,
  bar: String,
}
// case 3 -> error
props: {
  foo: {
    type: String,
    required: true
  }
}
// case 4 -> No any errors or warning
props: {
  foo: {
    type: String,
    required: false
  },
  bar: {
    type: String,
    default: ''
  }
}
```

**Comment by madarame-haruto20-fixer** [comment]
Hi,

When using `v-bind="<Prop Object>"`, this will show `misses props` warning.

![image](https://user-images.githubusercontent.com/64626169/92189855-a6db8500-ee9a-11ea-8776-bbcbf1199024.png)

Is there any solution to fix it?
