### ISSUE TITLE
Vuetify  v-slot:item.foo. 'v-slot' directive doesn't support any modifier.

### ISSUE THREAD

**Issue by forever84721** [vuejs/vetur#2147]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.26.1
- VS Code version: 1.47.3

## Problem
After version 0.26.0, this error appears when using v-slot:item.foo.
![image](https://user-images.githubusercontent.com/22338037/89746508-8cf19100-daec-11ea-89dc-a9c4b4d82827.png)
![image](https://user-images.githubusercontent.com/22338037/89746516-9d097080-daec-11ea-9e32-ee4eee690889.png)
This is the usage of Vuetify teaching (https://vuetifyjs.com/en/components/data-tables/), this error will not occur in the version before 0.26.0

## Reproducible Case
https://vuetifyjs.com/en/components/data-tables/#customizing-default-rows

**Comment by octref** [comment]
Please report to https://github.com/vuejs/eslint-plugin-vue.
