### ISSUE TITLE
vls 0.4.2 doesn't ship with built-in snippets

### ISSUE THREAD

**Issue by rchl** [vuejs/vetur#2148]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- VLS version: 0.4.2

## Problem

In an empty file, the built-in vetur snippet completions are missing.

## Reproducible Case

1. Open empty vue file
2. Type `template`

Should be provided with built-in snippet completions.

Here is a proof that snippets are missing: https://diff.intrinsic.com/vls/0.4.0/0.4.2

**Comment by rchl** [comment]
I have looked into it a bit before myself but I didn't see any issue. It could be that maybe some specific workflow we not followed the last time.

I hope it will work out for the next release at least.

**Comment by octref** [comment]
Sorry about that. Probably a mishap for me.

**Comment by octref** [comment]
Published vls 0.5.0
