### ISSUE TITLE
Tag autocompletion inside of template does not seem right (different from regular HTML files)

### ISSUE THREAD

**Issue by bassneck** [vuejs/vetur#2152]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: MacOS
- Vetur version: v0.26.1
- VS Code version: 1.47.3
- VSCode settings have been completely reset
- No other extensions installed

## Problem

Hi. The title might be a bit confusing, apologies for that.

When I type out a new opening tag, I expect a matching closing tag to be added. This does not happen. 

In addition, when adding a tag inside of a tag of the same name (i.e. div inside of div), the only suggestion provided converts my new tag into a closing tag for the parent and I end up with
```
<div>
</div>
</div>
```
instead of 
```
<div>
  <div></div>
</div>
```

So far I've tried setting html formatter to none but that had no affect. I couldn't find any other relevant options.
Editing regular html files works quite differently - gif below.

### Case 1
1. Inside of the template, type `<div`
2. Type the `>`

Expected: it should create `<div></div>` and put the cursor between the tags
Actual: suggestions disappear and nothing happens

![vetur-case-1](https://user-images.githubusercontent.com/505411/90117798-7593fb80-ddab-11ea-8a5e-e18d0626e6fc.gif)

### Case 2: Nested divs
1. Create a div and put the cursor inside of it:
2. Add a new opening `<div>`

Expected: The top suggestion should be to create a new `<div></div>` pair
Actual: The only suggestion is to close the parent tag. Need to press escape to dismiss suggestions.

![vetur-case-2](https://user-images.githubusercontent.com/505411/90117826-83498100-ddab-11ea-9ad2-c8ba45488c71.gif)

For comparison, this is how it works in an html file:

![vetur-html-comparison](https://user-images.githubusercontent.com/505411/90118169-f3580700-ddab-11ea-9006-41da933fc060.gif)

**Comment by octref** [comment]
Part of #565.
