### ISSUE TITLE
Intellisense in latest Vetur is painfully slow

### ISSUE THREAD

**Issue by kjeksfjes** [vuejs/vetur#2163]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.26.1
- VS Code version: 1.48.0

## Problem

Intellisense, e.g. when typing `import whatever from './'` i takes around 10 seconds for suggestion to pop up.

I've tried downgrading VS Code to no avail. The only thing that seems to work is downgrading Vetur to 0.25.0.

## Reproducible Case

- Use latest Vetur on latest VS Code. Use something like Path Intellisense (doesn't matter) and try to import something by typing `import whatever from './'`.
- Expected result: Intellisense suggestion pops up right away.
- Actual result: After 10 seconds or so intellisense suggestion pops up.

**Comment by yoyo930021** [comment]
Can you profile it?
https://github.com/vuejs/vetur/blob/master/.github/PERF_ISSUE.md

**Comment by 3nuc** [comment]
Having similar issue but with TypeScript intellisense of instance properties in <script> or <template> tags.

What I did:
1. Open https://github.com/tokyo-metropolitan-gov/covid19/blob/development/components/PositiveRateMixedChart.vue (in vscode after cloning repo and npm install, not on web)
1. Go to <template>
2. Write down `v-text="displayOptionHeader."` (notice dot at end) in some random tag
3. **Pressed start CPU profiling in Chrome**
4. Return to vscode after '.' and press ctrl+space
5. Wait for intellisense box to appear with suggestions based on TS interface
6. **Stop CPU profiling*
[covid-19-ctrl-space-in-template.zip](https://github.com/vuejs/vetur/files/5075780/covid-19-ctrl-space-in-template.zip)

I mainly experience it at work in a vue-property-decorator TS project but I don't wanna share the profile from there

**Comment by IWANABETHATGUY** [comment]
Actually , most language feature of vetur come from `typescript`, so the bottleneck also came from typescript, i am not sure if vetur using the typescript incremental parsing.

**Comment by 3nuc** [comment]
The difference between editing a `.ts` file and `.vue` lang="ts" file in the same workspace is very noticeable. IntelliSense in `.ts` is much faster, though I use the TS nightly extension. Not sure if others share the same experience

**Comment by octref** [comment]
From @3nuc's profile, seems `recreateVueTempalteSourceFile` is slow.
Does turning off `"vetur.experimental.templateInterpolationService": false` help?

@kjeksfjes If you don't provide a profile, there's nothing I can do. Your issue is likely unrelated to @3nuc's.

**Comment by IWANABETHATGUY** [comment]
> "vetur.experimental.templateInterpolationService": false
Is it possible to turn our parser into incremental？so that  we don't need to reparse our `.vue` file every edit.
I found that here is a incremental parser generator framework [tree-sitter](https://github.com/tree-sitter/tree-sitter),

**Comment by IWANABETHATGUY** [comment]
one more,  i already found one incremental vue parser generate by `tree-sitter`,which is available , https://github.com/ikatyang/tree-sitter-vue,
[demo link](https://ikatyang.github.io/tree-sitter-vue/)

**Comment by ZhangPuXi** [comment]
Also met the same issue, it seems that it also slows the emmet suggestion.

**Comment by Stevenje** [comment]
Same issue here.

**Comment by castrix** [comment]
I had the same issue, I'm using this boilerplate for my project with compositon api https://github.com/sapphi-red/vite-boilerplate-plus. on my other project I use vue class component and not experiencing any issue
