### ISSUE TITLE
Prop diagnostics not displayed for PascalCase components in templates

### ISSUE THREAD

**Issue by triforcely** [vuejs/vetur#2168]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: latest origin/master (833c3743543744f9c3466f3dcd88b6a596a9d2f1)
- VS Code version: 1.47.3

## Problem

Prop diagnostics are shown only for components written with 'kebab-case'.
![image](https://user-images.githubusercontent.com/12202969/90310855-bbf57180-def5-11ea-9867-c1ebe309da44.png)

## Reproducible Case

1) Create component with some property.
2) Try using it in other component with both 'kebab-case' and 'PascalCase' syntax.

**Comment by octref** [comment]
Fixed by #2170.
