### ISSUE TITLE
No snippet for TypeScript class-based syntax in .vue files

### ISSUE THREAD

**Issue by Mikilll94** [vuejs/vetur#2171]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.26.1
- VS Code version: 1.48

## Problem

In VS Code there is no scaffold snippet for TypeScript class-based syntax in .vue files

![image](https://user-images.githubusercontent.com/17653648/90323271-6c4b9000-df5f-11ea-9847-24b8c4a9cde6.png)

As you can there is only one scaffold snippet for TypeScript in .vue but it is for non-class-based syntax.

## Reproducible Case

1. Create a new file.
2. Type Ctrl + Enter
3. As you can see, there is no scaffold snippet for TypeScript class-based syntax in .vue files

**Comment by yoyo930021** [comment]
https://vuejs.github.io/vetur/snippet.html#customizable-scaffold-snippets

**Comment by Mikilll94** [comment]
@yoyo930021 
Thanks. But in my case the `vue-class-component.vue` snippet is not available. Is it a bug of Vetur? What should I do to make it available?

**Comment by yoyo930021** [comment]
> @yoyo930021
> Thanks. But in my case the `vue-class-component.vue` snippet is not available. Is it a bug of Vetur? What should I do to make it available?

The Vetur don't contain `vue-class-component.vue` snippet.
So this issue is a feature request.
The link can help you add custom snippet for temporary.

**Comment by Mikilll94** [comment]
@yoyo930021 
Thanks, I have successfully added my custom snippet.
