### ISSUE TITLE
Auto complete of curly parentheses didn't work in inline elements 

### ISSUE THREAD

**Issue by pixieaka** [vuejs/vetur#2172]
When i write `{{` in inline object like `<p></p>` it converted to :
```
<p>{{</p>
```
but when new line inserted it's the auto complete work fine
```
<p>
{{  }}
</p>
```

**Comment by yoyo930021** [comment]
Please use bug report for issue.
This info can't help us to resolve problem.

**Comment by pixieaka** [comment]
@yoyo930021 This problem in new Vue JS project from CLI | In HelloWorld.vue inside src/components directory

**Comment by yoyo930021** [comment]
You can use this link to open issue.
https://github.com/vuejs/vetur/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by octref** [comment]
Because there is no whitespace after you type `{`, Vetur doesn't autoclose it.
If that's your desired behavior, set `"editor.autoClosingBrackets": "always"`.
