### ISSUE TITLE
Default format delete spaces in elements

### ISSUE THREAD

**Issue by pixieaka** [vuejs/vetur#2174]
When i format document like
```
<p> space before and after this text </p>
```
spaces deleted automatically but this not right behavior, because in some cases the user want this spaces like separation
```
<span> | </span>
``` 
this automatically removes any spaces and converted to
```
<span>|</span>
```

**Comment by triforcely** [comment]
I don't think that these spaces will mean anything (according to https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace). I find it strange to use whitespace for spacing things (instead of css) but shouldn't '& nbsp;' be used instead?

**Comment by yoyo930021** [comment]
It is a upstream problem for default format library.
