### ISSUE TITLE
Auto complete of curly parentheses didn't work in inline elements

### ISSUE THREAD

**Issue by pixieaka** [vuejs/vetur#2175]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows 10 Build 19041.264
- Vetur version: 0.26.1
- VS Code version: 1.48.0

## Problem
Auto complete of curly parentheses didn't work in inline elements

## Reproducible Case
1- new project with Vue JS CLI With router
2- in ` src/components/HelloWorld.vue` in `<template>` tag this the problem

When i write `{{` in inline object like `<p></p>` auto complete didn't work :
```
<p>{{</p>
```
but when new line inserted auto complete work fine :
```
<p>
{{  }}
</p>
```

---
### HelloWorld.vue | File
```
<template>
    <div class="hello">
        <h1>{{ msg }}</h1>
        <p>{{</p> <!-- HERE THE PROBLEM -->
    </div>
</template>

<script>
export default {
    name: "HelloWorld",
    props: {
        msg: String,
    },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">
h3 {
    margin: 40px 0 0;
}
ul {
    list-style-type: none;
    padding: 0;
}
li {
    display: inline-block;
    margin: 0 10px;
}
a {
    color: #42b983;
}
</style>
```

**Comment by cereschen** [comment]
This is also the case in HTML files, not vetur itself

**Comment by octref** [comment]
That's same as HTML. If you want to change the behavior, use `"editor.autoClosingBrackets": "always"`.
