### ISSUE TITLE
Show quick outline in vue component file

### ISSUE THREAD

**Issue by ppasieka** [vuejs/vetur#218]
In larger files it would be nice to use "Show the quick outline (CTRL-SHIFT-O, ⌘-SHIFT-O)". especially to navigate between event handlers.

Currently quick outline only show html tags

![image](https://cloud.githubusercontent.com/assets/2170707/26621189/27b21a38-45e6-11e7-8f7e-782540b870ec.png)

I would love to see behavior like in js file

![image](https://cloud.githubusercontent.com/assets/2170707/26621244/673ed4ca-45e6-11e7-9b03-33f97e0424ad.png)

**Comment by octref** [comment]
We can do that by implementing a js/ts `symbolProvider`.

**Comment by HerringtonDarkholme** [comment]
I think this issue has already been implemented.

<img width="991" alt="screen shot 2017-08-14 at 11 28 50 am" src="https://user-images.githubusercontent.com/2883231/29257334-c5d6b4a2-80e3-11e7-9e47-55486538b5c5.png">

Now vetur includes all symbols from template, script and styles.
