### ISSUE TITLE
No suggestion on hover in TypeScript part only in Linux (not in macOS)

### ISSUE THREAD

**Issue by patarapolw** [vuejs/vetur#2190]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux Mint 20 (also not working in Elementary Linux). Works OK in macOS.
- Vetur version: 0.26.1
- VS Code version: VSCodium 1.48.0

## Problem

- No suggestion for TypeScript
- No dialog on hover (No IntelliSense)
- Syntax highlighting is OK. Autofix is OK (Prettier + ESLint). No complain on variable typos.
- Nothing in output panel

## Reproducible Case

- Install VSCodium
- Install Vetur extension
- Open a `*.vue` file.

**Comment by octref** [comment]
Your issue is closed because you did not provide a repro case. Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.

And BTW, vscodium modifies VS Code source and I don't have time to fix issues caused by it.

**Comment by patarapolw** [comment]
It appears to work OK in VSCode, but not in VSCodium on the same platform (Linux). Thanks anyway.
