### ISSUE TITLE
Different JSDoc Intellisense Behaviour on Script Block and on JavaScript File

### ISSUE THREAD

**Issue by jefrydco** [vuejs/vetur#2193]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: MacOS
- Vetur version: 0.26.1
- VS Code version: 1.48.1

## Problem

This is intellisense in JavaScript file:

![JavaScript Intellisense](https://user-images.githubusercontent.com/20434351/91004856-89d3c600-e5ff-11ea-9ceb-2d5bcfe59034.png)

It shows description and example.

And this is intellisense in `<script>` block on Vue SFC:

![Vue JavaScript Intellisense](https://user-images.githubusercontent.com/20434351/91004956-c3a4cc80-e5ff-11ea-9449-b5e4005f7bfc.png)

It doesn't show description and example.

This is also occurrs on `<script lang="ts">` block on Vue SFC:

![Vue TypeScript Intellisense](https://user-images.githubusercontent.com/20434351/91005056-0d8db280-e600-11ea-8538-51e6e05fcc1d.png)

## Reproducible Case

- Create a index.js and export named function that has JSDoc description and example.
- Try to import it on JavaScript
- Try to import it on `<script>` block on Vue SFC

Minimal Reproduction: https://github.com/jefrydco/vue-intellisense-behaviour

**Comment by octref** [comment]
This is a special pre-processing recently added in VS Code: https://github.com/microsoft/vscode/blob/8ba70d8bdc3a10e3143cc4a131f333263bc48eef/extensions/typescript-language-features/src/utils/previewer.ts

I copied it over:

![image](https://user-images.githubusercontent.com/4033249/91124896-ee138a00-e6d2-11ea-9088-4afc3b392e0e.png)

**Comment by octref** [comment]
While at it I fixed hover/completion as well:

![image](https://user-images.githubusercontent.com/4033249/91127213-63358e00-e6d8-11ea-99cd-bf5c54f643f5.png)
