### ISSUE TITLE
Fit in monaco-editor@0.20

### ISSUE THREAD

**Issue by y912765390** [vuejs/vetur#2194]
I know we have mono Vue which can support Vue in Monaco editor. But it doesn't have ESM package, so I don't know how to adapt to the version above 0.10 of Monaco. For example, how can I use the monaco-editor@0.20 Vue is supported in

**Comment by octref** [comment]
https://github.com/rebornix/monaco-vue

**Comment by y912765390** [comment]
I know the library and I'm using it, but I don't fit it moanco-editor@0.20 Can you give me more accurate guidance. How to monaco-editor@0.20 Use this library in

**Comment by y912765390** [comment]
Monaco editor seems to need the ESM package to be able to enter, while moaco-vue can only be packaged into the Min version

**Comment by octref** [comment]
I don't have time to investigate integrations. You can reach our to the author of monaco-vue.

**Comment by y912765390** [comment]
I tried again. Others have ESM package, dev package, but monaco-vue only has min package. If you join Monaco editor, there will be an error.How can I contact him? I didn't get a reply to my question in monaco-vue. Thank you for your reply

**Comment by octref** [comment]
Make the changes to build ESM yourself, or wait for his response.
