### ISSUE TITLE
Formatting of *.ts files?

### ISSUE THREAD

**Issue by pootzko** [vuejs/vetur#2197]
- [X] I have searched through existing issues

## Feature Request

Hi, sorry for perhaps a silly mistake on my end, but unless I'm understanding something wrong, formatting of plain .ts files is not supported at the moment (model / service .ts files)? The only way I've managed to make it work was to install the prettier vscode plugin, but that would then mess up the html formatting in .vue files. TS code inside .vue files which is inside `<script lang="ts">` tag does get formatted without any issues.

Here's my .vscode/settings.json

```json
{
  "editor.insertSpaces": true,
  "editor.formatOnSave": true,
  "vetur.format.defaultFormatter.html": "js-beautify-html",
  "vetur.format.defaultFormatter.ts": "prettier",
  "vetur.format.defaultFormatterOptions": {
    "js-beautify-html": {
      "wrap_attributes": "force-aligned",
      "wrap_line_length": 120,
      "indent_handlebars": true
    },
    "cSpell.words": [
      "validatable"
    ],
    "editor.tabSize": 2
  },
  "search.exclude": {
    "package-lock.json": true
  }
}
```

.prettierrc
```
{
  "trailingComma": "all",
  "jsxBracketSameLine": true,
  "printWidth": 120,
  "arrowParens": "avoid"
}
```

.prettierignore
```
.vscode/*
settings.json
tsconfig.*
tslint.json
.eslintrc.json
```

.editorconfig
```
root = true

[*]
charset = utf-8
indent_style = space
indent_size = 2
insert_final_newline = true
trim_trailing_whitespace = true

[*.ts]
quote_type = double

[*.md]
max_line_length = off
trim_trailing_whitespace = false
```

tslint.json
```json
{
  "defaultSeverity": "warning",
  "extends": [
    "tslint:recommended"
  ],
  "linterOptions": {
    "exclude": [
      "node_modules/**",
      ".vscode/**"
    ]
  },
  "rules": {
    "no-empty": false,
    "quotemark": [
      true,
      "double"
    ],
    "indent": [
      true,
      "spaces",
      2
    ],
    "interface-name": false,
    "ordered-imports": false,
    "object-literal-sort-keys": false,
    "no-consecutive-blank-lines": true,
    "eofline": false,
    "member-access": [
      true,
      "no-public"
    ],
    "max-classes-per-file": false,
    "arrow-parens": [
      true,
      "ban-single-arg-parens"
    ]
  }
}
```

Thank you!

**Comment by rchl** [comment]
This extension is not set up to run on plan *.ts files so it's out of scope. You need to look into other available solutions for handling what you want.

**Comment by pootzko** [comment]
Ok thanks, I guess I'll close this then. However if someone has a setup they're willing to share on how to make .vue and .ts play nice together, please leave a comment. My main issue with prettier on is that as soon as I install it, I don't know how to turn it off for html inside .vue files. Perhaps there's a way, but after a few hours of messing with this, I haven't been able to do it. 

It feels like vetur and prettier are fighting over it. Vetur can't do .ts files, but can handle html nicely through prettyhtml / js-beutify-html, but and on the other hand, prettier can handle .ts files, but then doesn't let Vetur handle html...

**Comment by octref** [comment]
> I don't know how to turn it off for html inside .vue files.

F1, run this command to open settings.json:

![image](https://user-images.githubusercontent.com/4033249/91320598-51470e80-e7f0-11ea-9ca1-b693a2ad0970.png)


```json
{
  "[vue]": {
    "editor.defaultFormatter": "octref.vetur"
  },
  "vetur.format.defaultFormatter.html": "<YOUR_CHOICE>",
  "vetur.format.defaultFormatter.css": "prettier",
  "vetur.format.defaultFormatter.js": "prettier"
}
```

Open settings UI, then

**Comment by pootzko** [comment]
That's it! Perfect, thanks a lot!

This bit did it:

```json
"[vue]": {
    "editor.defaultFormatter": "octref.vetur"
  },
```

**Comment by scscgit** [comment]
Does this mean that everyone has to install Prettier into their IDE despite its functionality being included in Vetur, only for the sole reason that you've decided to exclude types like .ts from the formatter? Please, can someone document the plugin intentions in the Readme together with the list of other extensions that should or shouldn't be installed together with it when following common developer use-cases?
