### ISSUE TITLE
Type 'void' is not assignable to type 'object'

### ISSUE THREAD

**Issue by DarkLite1** [vuejs/vetur#2199]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows Server 2016
- Vetur version:  0.26.1
- VS Code version: 1.48.2

## Problem

We're using a graphql backend server and use the Apollo client to get results. 

Type safety in the `<script>` section works fine but in the  `<template>` section we get the Vetur warning below:
> Type 'void' is not assignable to type 'object'.Vetur(2769)

```typescript
.// no issues here:
const { result, loading, error } = useAllAccountsQuery()
const allAccounts = useResult(result)

if (allAccounts.value) {
   allAccounts.value.accounts
   allAccounts.value.accounts[0].accountIdentifier
}
```
![image](https://user-images.githubusercontent.com/10828570/91443553-c60f5c80-e873-11ea-9bec-3ee2e59b406f.png)

Panel -> Output -> Vue Language Server: No messages

## Additional info

I've opened a similar [issue here](https://github.com/vuejs/vue-apollo/issues/1051). [GitHub repo](https://github.com/DarkLite1/hip/blob/master/src/pages/Index.vue) with all code.

**Comment by rchl** [comment]
It's a type that can be Void so not sure why would you expect it to work in a template without null-checking first.

Just wrap that code in a `v-if`.

Your code in the script tag is not equivalent to the template code. Something like this would also show the problem:

```js
    for (const account in allAccounts.value) {
      // account
    }
```

**Comment by DarkLite1** [comment]
Thank you for getting back to me. I tried your suggestion but it still comaplains:

![image](https://user-images.githubusercontent.com/10828570/91449285-38376f80-e87b-11ea-9c16-35209412c3ea.png)

**Comment by rchl** [comment]
`allAccounts` is an `AllAccountsQuery` type which is an object (dictionary) with a `accounts` property:

```ts
export type AllAccountsQuery = { __typename?: 'Query' } & {
  accounts: Array<
    { __typename?: 'Account' } & Pick<Account, 'accountIdentifier' | 'name'>
  >
}
```

so this code is wrong. Try `v-for="account in allAccounts.accounts"` instead.

**Comment by DarkLite1** [comment]
I've been playing a long time with this and can't seem to pin point my error. Your suggestion also did not work:

![image](https://user-images.githubusercontent.com/10828570/91450616-c52ef880-e87c-11ea-9e37-e6bafe3252c0.png)


This does remove the error but then I get no result back from my query on the webpage:
```typescript
      <div v-if="allAccounts">
        <div
          v-for="account in allAccounts.accounts"
          :key="account.accountIdentifier"
        >
          {{ account.name }}
        </div>
      </div>
```

**Comment by rchl** [comment]
I'm sorry but I can't provide support for the usage of that graphql library. Your last code snippets is correct types wise. The fact that you don't get data is unrelated to your initial problem and you should look for help with that in forums or chat specific to that library.

**Comment by DarkLite1** [comment]
I understand, thank you anyway for the help. I do find it strange that the code is typescript correct in the `<script>` section but not in the `<template>` section. Hmmm... So I think the library, graphql-codegen, is working correctly but the `<template>` part is not reading/interpreting the typescript part correctly. That's why I thought the issue was within Vetur. F

eel free to share your thoughts, because I don't know where to go from here.

**Comment by rchl** [comment]
IMO this has nothing to do with TS and you would have exactly the same problem if the project would be fully in JS.
Maybe the query is just failing and the accounts array is empty.
In any case, please search for help in more specific forums/chats.

**Comment by octref** [comment]
Changing it to `allAccounts!` have fixed it for me.

> the code is typescript correct in the <script> section but not in the <template> section

You are returning an object that can be null. Returning that object from `setup` is correct. Iterating on that nullable object is not.

**Comment by DarkLite1** [comment]
Thank you, but the code below does remove the error but defines `account` as type `any` so there's no type checking and it brakes the webpage:
```html
<template>
      <div v-if="allAccounts">
        <div
          v-for="account in allAccounts!"
          :key="account.accountIdentifier"
        >
          {{ account.name }}
        </div>
      </div>
</template>
```

I probably misunderstood you. Could you maybe provide an example for a noob like me?
