### ISSUE TITLE
Support for labels on tuple elements in TypeScript

### ISSUE THREAD

**Issue by MT224244** [vuejs/vetur#2212]
- [x] I have searched through existing issues

## Feature Request

Support labeling of Tuple elements in TypeScript in .vue files.  
It is already supported in .ts files.

For .ts files
![image](https://user-images.githubusercontent.com/25514849/91517992-1fd25e00-e92a-11ea-8eb9-b04fa8f48101.png)

For .vue files
![image](https://user-images.githubusercontent.com/25514849/91518099-560fdd80-e92a-11ea-954f-c8c106a54745.png)

**Comment by yoyo930021** [comment]
Please use this config and install support this feature typescript version in project.
https://vuejs.github.io/vetur/FAQ.html#vetur-uses-different-version-of-typescript-in-vue-files-to-what-i-installed-in-node-modules

**Comment by MT224244** [comment]
Oh! sorry, I see it was in the FAQ.
It's resolved, thank you!
