### ISSUE TITLE
Add vue.config.js > css.loaderOptions.sass.prependData scss to the autocomplete suggestions

### ISSUE THREAD

**Issue by UltraCakeBakery** [vuejs/vetur#2213]
- [x] I have searched through existing issues

## Feature Request

I pasted our vue.config.js below. 
The imports are not added to our autocomplete suggestions.
```
module.exports = {
    configureWebpack: {
        plugins: [ new BundleAnalyzerPlugin() ]
    },
    css: {
        loaderOptions: {
            sass: {
                prependData: `
                    @import "~bootstrap/scss/functions";
                    @import "~bootstrap/scss/variables";
                    @import "~bootstrap/scss/mixins";
                    @import "@/scss/_variables.scss";
                `
            }
        }
    }
}
```

**Comment by octref** [comment]
Duplciate of #130.

**Comment by UltraCakeBakery** [comment]
@octref I don't really understand how this is a duplicate? That issue is very broad and not specifically about the feature I'm requesting.

**Comment by octref** [comment]
There are many bundlers, we cannot support scss compilation settings for each of them.
https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-scss supports Vue SFC as well. You can give it a try.
