### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by Uninen** [vuejs/vetur#2215]
We should add a code of conduct document to the project. I can do a PR to the docs if we find a suitable template.

**Comment by triforcely** [comment]
There is a resource regarding [contributing](https://github.com/vuejs/vetur/wiki#contribution-guide). What additional code of conduct will solve?

**Comment by Uninen** [comment]
Here's a ready template that Vue also uses: https://www.contributor-covenant.org
