### ISSUE TITLE
Vetur › Validation: Interpolation Validate interpolations in <template> region using TypeScript language service

### ISSUE THREAD

**Issue by wuxinzhe097** [vuejs/vetur#2231]
- [ ] I have searched through existing issues

## Feature Request

It should be turned off by default

**Comment by ink6** [comment]
I think so

**Comment by octref** [comment]
Fixed in https://github.com/vuejs/vetur/commit/6b1c0eb3f52875636a22664a8b1cc0cb9e0080ed
