### ISSUE TITLE
Can't collapse template HTML

### ISSUE THREAD

**Issue by dvvdev** [vuejs/vetur#2234]
- [X ] I have searched through existing issues
- [ X] I have read through [docs](https://vuejs.github.io/vetur)
- [ X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS - latest update
- Vetur version: 2.7.1
- VS Code version: 1.48.2

## Problem
 
Can't collapse code. The triangles disappear when trying to interact with them.

## Reproducible Case

Create code with Vetur 2.7.1. Try to collapse it. Does not work.

Disable Vetur. Collapse code as expected.

Revert to Vetur 2.4 version, code collapses as expected  .

**Comment by 18781698365** [comment]
me too,hope to solve it as soon as possible.

**Comment by yoyo930021** [comment]
I can't reproducible this, but It's not have collapse in template region.
Are you referring to this?

**Comment by 18781698365** [comment]
yes, I mean this. Thank you for your reply!

**Comment by artnova-david** [comment]
same problem. In my case reverting to an older version solves the problem only for .vue files created prior 2.4 version of Vetur.

**Comment by antoinematyja** [comment]
On my side this seems to be related with linters. When I open a .vue file, folding works, then one second later unusual linter issues appear and folding disappears.

**Comment by yoyo930021** [comment]
> On my side this seems to be related with linters. When I open a .vue file, folding works, then one second later unusual linter issues appear and folding disappears.

It's not what you think.
Provide folding have three ways.
The basic two is Folding Markers and Indentation.
Ths full one is LSP.

We try to use LSP for #899 in v0.27.0,
but we forget to add HTML folding in LSP.
We have a PR to fix it now.  #2244 

PS. The lint error is another problem, but thanks you.

**Comment by olearycrew** [comment]
> Can't collapse code in template region

This is the correct description of the issue - @dvvdev could you update the title?

**Comment by nicovrg** [comment]
does someone know when the html folding will be supported again?

**Comment by mika76** [comment]
@nicovrg seems to be working for me... are you on the latest version?

**Comment by nicovrg** [comment]
i'm on 0.27.0

**Comment by CharlesOkwuagwu** [comment]
still not working on version 0.31.3

**Comment by yoyo930021** [comment]
> still not working on version 0.31.3

Please open a new issue and provide more information.

**Comment by davevasquez** [comment]
In case this helps some of you, I was having a similar issue with code folding disappearing a second or two after loading a .vue file.  In my case, I had changed the name of the folder where my .vue files were and forgot to update my vetur.config.js file to point to the new directory name.  This resulted in disabling my code folding (but as far as I could tell everything else continued to work - which made it hard to pinpoint this as the issue).  

Hope this helps someone!
