### ISSUE TITLE
The props validator can't handle about `v-bind`, `:[key]` and `v-model`

### ISSUE THREAD

**Issue by yoyo930021** [vuejs/vetur#2236]
- [x] I have searched through existing issues

## Feature Request
The `v-bind` is hard to handle.
Maybe we can ignore it.

The `:[key]` is also hard to handle.

The `v-model` can read AST to handle.

**Comment by bbugh** [comment]
@octref #2241 does not appear to address custom model names. The model prop can be customized, but if I'm reading the source correctly, the model prop in that change set seems to be hard-codes to `value`. From the docs: https://vuejs.org/v2/api/#model

**Comment by yoyo930021** [comment]
> @octref #2241 does not appear to address custom model names. The model prop can be customized, but if I'm reading the source correctly, the model prop in that change set seems to be hard-codes to `value`. From the docs: https://vuejs.org/v2/api/#model

No, #2241 has thought about it.
Please see https://github.com/vuejs/vetur/blob/master/server/src/modes/script/componentInfo.ts#L117
