### ISSUE TITLE
Missing props warning when using .sync modifier

### ISSUE THREAD

**Issue by victorgarciaesgi** [vuejs/vetur#2237]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.27.1
- VS Code version: 1.48.2

## Problem

![image](https://user-images.githubusercontent.com/15092120/92218366-4bf55e00-ee99-11ea-8b87-1c98866390ca.png)

**Comment by lastlink** [comment]
I'm also having this issue, I'm assuming it's from a recent update.

**Comment by bestickley** [comment]
I'm also having this issue

**Comment by masoudelahi** [comment]
I'm also having this issue
