### ISSUE TITLE
Make <PascalCase> component highlight is optional

### ISSUE THREAD

**Issue by neyasbltb88** [vuejs/vetur#2239]
Please make this highlight as an option in the settings. It was convenient for me when all components were highlighted like html tags.
![image](https://user-images.githubusercontent.com/28704903/92224174-1e64e080-eeaa-11ea-80c3-3ed98f307548.png)

**Comment by ShevRuslan** [comment]
I agree completely

**Comment by victorgarciaesgi** [comment]
@neyasbltb88 You can overwrite it using VsCode `Developer: Inspect Editor Tokens and Scope`.

![image](https://user-images.githubusercontent.com/15092120/92227186-32a6de80-eea6-11ea-800f-6c25a73c1a41.png)

Then in your settings.json you can customize it

```json
"editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": "support.class.component.html",
        "settings": {
          "foreground": "#aeaf55 (the color you want here)"
        }
      }
    ]
  },
  },
```

**Comment by neyasbltb88** [comment]
@victorgarciaesgi Thank you, it works

**Comment by gerasimvol** [comment]
it should be highlighted with color of other tags

**Comment by octref** [comment]
As @victorgarciaesgi said this is configurable.
I won't offer an option since VS Code doesn't allow dynamic language grammar, and this is consistent with JSX/TSX highlighting.
