### ISSUE TITLE
Vue SFC: HTML folding broken - Wrong lint warning

### ISSUE THREAD

**Issue by antoinematyja** [vuejs/vetur#2242]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.27.1
- VS Code version: 1.48.2

## Problem

When I launched VSCode this morning I wasn't able to fold the HTML in my .vue SFC file. Also weird lint warnings appeared.
I quickly identified this was coming from Vetur. I tried to downgrade to 0.26 and it works fine.

<img width="446" alt="image" src="https://user-images.githubusercontent.com/9961462/92236154-2413f380-eeb5-11ea-91f0-77eab3236c1f.png">

As you can see I can fold `<template>` but nothing inside. Also there is a lint warning which should not happen:
```
[vue/no-multiple-template-root]
The template root requires exactly one element.
```

## Reproducible Case

The issue happens with any vue SFC file, for instance:
```
<template>
  <p>
    <div>{{ greeting }} World!</div>
  </p>
</template>

<script>
module.exports = {
  data: function() {
    return {
      greeting: "Hello"
    }
  }
}
</script>

<style scoped>
p {
  font-size: 2em;
  text-align: center;
}
</style>
```

Thanks!

Edit: here is my `.eslintrc.js` if this helps:

```
module.exports = {
  env: {
    browser: true,
    es2020: true
  },
  extends: [
    'plugin:vue/essential',
    'standard'
  ],
  parserOptions: {
    ecmaVersion: 11,
    sourceType: 'module'
  },
  plugins: [
    'vue'
  ],
  rules: {
    'space-before-function-paren': [
      'error',
      {
        anonymous: 'never',
        named: 'never'
      }
    ]
  }
}
```

**Comment by yoyo930021** [comment]
Can you split to two issues?
The HTML folding is same to #2234

**Comment by antoinematyja** [comment]
My bad, I searched for "fold" in opened issues and this did not showed.
