### ISSUE TITLE
[Feature request] Reference globally registered component to Vetur

### ISSUE THREAD

**Issue by victorgarciaesgi** [vuejs/vetur#2243]
- [x] I have searched through existing issues

## Feature Request

First off all, thanks for this great update! Having props check and component signature is so useful, you are catching up fast with TSX.

I wondered if you though of a way of referencing globally registered components?

For exemple in Nuxt, I have a plugin that register a bunch of components, but the path can be different for all every project. Maybe a config file like `vetur.config.js` to indicate a path to the file?

```ts
Vue.component('SvgIcon', SvgIcon);
Vue.component('Spinner', Spinner);
Vue.component('Popin', Popin);
```

**Comment by yoyo930021** [comment]
Hi everyone,
 If you interested this issue, 
you can go to #2377 and #2378.
View and post your ideas.

**Comment by yoyo930021** [comment]
> Why mixing global components and multiple-roots in the same issue? If it's because it is supposed to depend on the new configuration file then I would still keep it separate with it being dependant on the other.

It is only a message for guide users to discuss RFCs.
I won't discuss multiple-roots in this issue.

**Comment by rchl** [comment]
My comment was about the RFC itself. It IMO shouldn't mix global components into it.

**Comment by yoyo930021** [comment]
Fixed in v0.31.0

**Comment by yoyo930021** [comment]
> My comment was about the RFC itself. It IMO shouldn't mix global components into it.

I loss your comment. 😅
I think your problem solved in RFC.

**Comment by rchl** [comment]
> > My comment was about the RFC itself. It IMO shouldn't mix global components into it.
> 
> I loss your comment. 😅
> I think your problem solved in RFC.

I might have been confused initially anyway so probably all good.
