### ISSUE TITLE
Too bad, my html tags cannot be retracted and expanded after 0.27.1

### ISSUE THREAD

**Issue by TuiMao233** [vuejs/vetur#2245]
0.26.1：
![image](https://user-images.githubusercontent.com/49724027/92239595-e1224200-eeed-11ea-9d44-675730788ccb.png)
0.27.1：
![image](https://user-images.githubusercontent.com/49724027/92239741-1595fe00-eeee-11ea-82a1-13a64ae13c0b.png)

**Comment by yoyo930021** [comment]
Duplicate of #2234
