### ISSUE TITLE
Auto import does not respect "trailingComma": "all" after upgrading to v0.27+

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/vetur#2246]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  Win
- Vetur version: 0.27.1
- VS Code version: 1.48.2

## Problem
Auto import does not respect prettier `"trailingComma": "all"`, added redundant comma.

## Reproducible Case
0.27.1
![image](https://user-images.githubusercontent.com/28700378/92242867-0c5b6000-eef3-11ea-900b-df1bcbcefe07.png)

0.26.1
![image](https://user-images.githubusercontent.com/28700378/92242904-1b421280-eef3-11ea-8ea3-94e3c3cae0f4.png)

**Comment by octref** [comment]
Your issue is closed because you did not provide a repro case. Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.

Autoimport is a TS feature and has nothing to do with prettier.
