### ISSUE TITLE
Add a setting for enabling/disabling prop validation

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#2249]

**Comment by Killea** [comment]
Currently, the prop validation is not working properly.

**Comment by tobidalhof** [comment]
Warnings for missing optional props should be disabled by default

**Comment by yoyo930021** [comment]
> Currently, the prop validation is not working properly.

Have any question in v0.27.2?
The #2241 is fixed known problems.

**Comment by ilyakamens** [comment]
Thank you, @octref!
