### ISSUE TITLE
The Vue Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by gengxuelei** [vuejs/vetur#225]
os: win10 x64
vscode: 1.12.2
vetur: 0.7.0

![image](https://cloud.githubusercontent.com/assets/11707936/26810096/141491c6-4a9c-11e7-805c-5fef4e1b1aba.png)
![image](https://cloud.githubusercontent.com/assets/11707936/26810114/256f4146-4a9c-11e7-8a28-e4e4eaa24801.png)

**Comment by octref** [comment]
![image](https://cloud.githubusercontent.com/assets/4033249/26810141/bb9aa170-4a37-11e7-9070-7a0e44a76b83.png)

Try creating a tsconfig/jsconfig that only includes your source code.

**Comment by gengxuelei** [comment]
![image](https://user-images.githubusercontent.com/11707936/27025904-a5772402-4f8e-11e7-81c4-99a8f7438b42.png)
扩展主机意外终止。请重新加载窗口以恢复。（extension host crashed，reload to restore）
重新加载窗口（reload windows）

CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

I didn't have time to check the cpu & memory。
But I think it is the same reason that lead to this crashed
similar to https://github.com/octref/vetur/issues/229

**Comment by jiangxianboy** [comment]
I have the same problem...

**Comment by kevinongko** [comment]
also run into this problem.

OS: macOS Sierra 10.12.5
VScode: 1.13.1
vetur: 0.7.0

**Comment by octref** [comment]
Is there any project where you could share with me as a repro case?

**Comment by gengxuelei** [comment]
It's a company project, Is any one can supply one?
Wish can be solved as possible

**Comment by octref** [comment]
Like I said, create a jsconfig.json / tsconfig.json at the root of the repo and only `includes` your frontend code (vue / js files).

**Comment by gengxuelei** [comment]
I created a jsconfig.json at the root of the repo , is that right?

![image](https://user-images.githubusercontent.com/11707936/27170159-79e71e5c-51df-11e7-8d9d-bea1966e461a.png)

I am not sure if this file will solve this problem .
if it's ok , I'll close this issue.

**Comment by octref** [comment]
@gengxuelei Did it work for you?

**Comment by gengxuelei** [comment]
It seems ok

**Comment by biliydog** [comment]
@gengxuelei i've got same problem as you even i already got jsconfig file in my project, until i add  complierOptions and exclude option like you , thanks

**Comment by Wifsimster** [comment]
Same problem, since last update :-1:

**Comment by gengxuelei** [comment]
vetur0.9.3，vscode1.14.2 error again

**Comment by octref** [comment]
Then please open a new issue **with reproduction steps** otherwise I can't help you.
