### ISSUE TITLE
HTML folding Problem in .vue file

### ISSUE THREAD

**Issue by Suraiya-Aysha** [vuejs/vetur#2256]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version:
- VS Code version:

**Comment by Suraiya-Aysha** [comment]
Hey, I can't fold any HTML tag in .vue file. If I uninstall Vetur extension from VS code editor then I can fold the HTML tag. But vetur is an important extension for Vue js. Please fix the bug. I am facing truble.
Please fix HTML folding issue. We are some developers suffering more from the day before evening.

**Comment by jmteow** [comment]
@Suraiya-Aysha I am facing this issue as well. it was still working two days ago

**Comment by octref** [comment]
> [ ] I have searched through existing issues

If you search existing issues you'll find duplicates and that this issue has been fixed.
