### ISSUE TITLE
Syntax higlight not working on Vetur 0.27.2

### ISSUE THREAD

**Issue by leandromatos-hotmart** [vuejs/vetur#2257]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.27.2
- VS Code version: 1.48.2

## Problem

Syntax highlight not working on single file components.

## Reproducible Case

Just open an SFC on VSCode and you saw a one-color syntax.

**Comment by octref** [comment]
https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#no-syntax-highlighting--no-language-features-working

**Comment by leandromatos-hotmart** [comment]
Thank's. Remove the plugin folder and install again solved my problem.
