### ISSUE TITLE
v-slot with { } accept slot data has type any error in typescript project when update to 0.27.2

### ISSUE THREAD

**Issue by Eurkidu** [vuejs/vetur#2258]
#  Info

- Platform: macOS
- Vetur version: 0.27.2
- VS Code version: 1.48.2

## Problem
when update to 0.27.2
use v-slot with { } to accept data has this error tip，but I don‘t know how to definition this type
and when use 0.27.1 version has no this error tip

![图片](https://user-images.githubusercontent.com/13271070/92462794-85adc800-f1fd-11ea-9688-b4d5298dbdd2.png)

## Reproducible Case
```vue
// mc-ossfile-view.vue
<template>
  <div class="mc-ossfile-view">
    <div class="mc-ossfile-view__file-item"
      v-for="(item, idx) in fileList" :key="idx">
      <slot :item="item" :idx="idx"></slot>
      <div class="info-button"></div>
      <slot name="after" :item="item" :idx="idx"></slot>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Vue, Prop } from 'vue-property-decorator'

@Component
export default class McOssfileView extends Vue {
  @Prop({ type: Array, default: () => [] }) readonly fileList!: mcLib.TDataObject[]
}
</script>
```

```vue
// use vue file
<mcOssfileView
  :fileList="fileList">
  <template v-slot="{item}">{{item.name}}</template>
  <template v-slot:after="{item}">
    <div class="info-bar">
      <div class="text">{{item.name}}</div>
    </div>
  </template>
</mcOssfileView>
```

**Comment by JW9506** [comment]
In 0.28.0, I don't see it being reported as error, but it is still unable to infer the type from the child component. Is this expected?

**Comment by yoyo930021** [comment]
> In 0.28.0, I don't see it being reported as error, but it is still unable to infer the type from the child component. Is this expected?

Yes, we can't infer type from slot.
If you want this, please open a issue,
but maybe have related issue.

**Comment by JW9506** [comment]
> Yes, we can't infer type from slot.
> If you want this, please open a issue,
> but maybe have related issue.

It definitely enhances the Typescript development experience if we have this feature. It should be one of the reasons why people would rather use Typescript over Javascript when using VueJs. Hope to see this implemented in the future (not just avoiding this).

**Comment by yoyo930021** [comment]
> > Yes, we can't infer type from slot.
> > If you want this, please open a issue,
> > but maybe have related issue.
> 
> It definitely enhances the Typescript development experience if we have this feature. It should be one of the reasons why people would rather use Typescript over Javascript when using VueJs. Hope to see this implemented in the future (not just avoiding this).

It's a lot of work.
It will take a lot of time.

**Comment by JW9506** [comment]
> It's a lot of work.
> It will take a lot of time.

If you know ahead of time something takes a lot of work, then you just implied you know the direction towards the end goal, just think about how to achieve it while your Typescript skill gets better.

**Comment by yoyo930021** [comment]
> > It's a lot of work.
> > It will take a lot of time.
> 
> If you know ahead of time something takes a lot of work, then you just implied you know the direction towards the end goal, just think about how to achieve it while your Typescript skill gets better.

https://github.com/vuejs/rfcs/pull/192

**Comment by johnsoncodehk** [comment]
> > Yes, we can't infer type from slot.
> > If you want this, please open a issue,
> > but maybe have related issue.
> 
> It definitely enhances the Typescript development experience if we have this feature. It should be one of the reasons why people would rather use Typescript over Javascript when using VueJs. Hope to see this implemented in the future (not just avoiding this).

I have implemented this feature :)
https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar
![121576572_10216014201542719_6124167373920226918_o](https://user-images.githubusercontent.com/16279759/96086149-65f07a80-0ef4-11eb-9317-17a79b8577a6.jpg)

**Comment by sebastian0x62** [comment]
@yoyo930021 I see there is work in progress regarding this issue. I'm using Vuetify and have the slot type issue with its virtual scroller. Is there any workaround to manually type hint the correct slot type from "any"? I didn't find a way for that. Wondering if it's currently even possible (just manual hinting).

**Comment by vlbn** [comment]
i think i'm having the same problem.. any idea how to work around this? thank you in advance.

![image](https://user-images.githubusercontent.com/54779348/148662379-6e30db38-afcb-4b37-a40e-f8cc6f74385e.png)

**Comment by lukas-pierce** [comment]
I use small life hack for it in my TypeScript + Vue3 + ESLint components:


```vue
<template>
  <Modal>
    <template #footer="{footerMessage, close}: SlotProps">
      <p>{{ footerMessage }} <a href="#" @click.prevent="close">Dismiss</a></p>
    </template>
  </Modal>
</template>

<script setup lang="ts">
import Modal from './Modal.vue'

// close function signature
type VoidCallback = () => void

// it used for typing slot props
// eslint-disable-next-line no-unused-vars
interface SlotProps {
  footerMessage: string
  close: VoidCallback
}
</script>
```

The main idea to define interface for typing slot props.
IDE understands it, but ESLint thinks is unused, because it does not see this type usage in `#footer`

**Comment by tvld** [comment]
Did not help for me. I managed with:
```js
  <template #expansion-row="props: any">
    <span> More about {{ props.item.username }} </span>
  </template>
```

**Comment by yoyo930021** [comment]
Please use volar instead of vetur for vue setup support.
