### ISSUE TITLE
insertSpaceBeforeFunctionParenthesis setting is not working for standard function

### ISSUE THREAD

**Issue by thaiat** [vuejs/vetur#226]
- Platform: macOS
- Vetur version: 0.7.0
- VSCode version: 1.12.2

I have the following config setting:
```json
"vetur.format.js.InsertSpaceBeforeFunctionParenthesis": false
```

when formatting the following code:
```js
<script>
var add = function (a, b) {
  return a + b;
};

export default {
  name: 'hello',
  methods: {
    login(event) {
      console.log(event);
    }
  },
  data() {
    return {
      msg: 'Welcome to Your Vue.js App!!!' + add(12, 14)
    };
  }
};
</script>
```

It removes correctly the spaces in `login` or `data`, but it adds a space before parenthesis in the standard `add` function.

PS: When `vetur.format.js.InsertSpaceBeforeFunctionParenthesis` is true everything is consistent

**Comment by octref** [comment]
Thanks. I can confirm it's working as expected in ts file but not vue file.

**Comment by octref** [comment]
That space is controlled by `InsertSpaceAfterFunctionKeywordForAnonymousFunctions` in TS formatter setting, not `InsertSpaceBeforeFunctionParenthesis`.

I've made it so that `InsertSpaceBeforeFunctionParenthesis` would control both, so now Vetur should be consistent for space before function. Will be available in 0.9.5.

**Comment by BruceHem** [comment]
Hi i'm on Vetur 0.10.1 and I don't see InsertSpaceBeforeFunctionParenthesis in config options

**Comment by StrangeTown** [comment]
@BruceHem 

- set vetur's default formatter to "vscode-typescript"
- and then set "javascript.format.insertSpaceBeforeFunctionParenthesis" to "true"

```js
"vetur.format.defaultFormatter.js": "vscode-typescript",
"javascript.format.insertSpaceBeforeFunctionParenthesis": true
```
