### ISSUE TITLE
Implement features faster

### ISSUE THREAD

**Issue by oswaldofreitas** [vuejs/vetur#2263]
Issue Type: <b>Feature Request</b>

Hello,

I'm waiting for a long time for some features to be implemented, specially:

- code inferring in the template (with intellisense)
- monorepo support (I want to have as many tsconfig files I want in different folders)

Vue is a framework extensively used today by milions? of devs, and Vetur is what allow us to have a nice experience when working with Vue on VSCode.

A new dev just started working in my team and he uses WebStorm and I just loved some features they have there like well handling javascript in the Vue Single File Component template.

Should Microsoft invest resources to help on this extension due to the enourmous Vue community that's using VSCode?

Extension version: 0.27.2
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:56:10.074Z)
OS version: Linux x64 5.7.4-050704-generic snap

**Comment by octref** [comment]
> code inferring

What do you mean by code inferring? Autocompletion?

> monorepo support

I'll do it next.

> A new dev just started working in my team and he uses WebStorm and I just loved some features they have there like well handling javascript in the Vue Single File Component template.

https://vuejs.github.io/vetur/interpolation.html
If there are features you want specifcially, please open specific feature request issues.

> Should Microsoft invest resources to help on this extension due to the enourmous Vue community that's using VSCode?

I no longer work at Microsoft & I'd be greatful if that could happen. You could open an issue in https://github.com/microsoft/vscode.

**Comment by oswaldofreitas** [comment]
code inferring: yes, I meant Autocompletion.

monorepo: cool that you're moving to this next, thank you.

javascript in templates: I meant this "Vetur now offers completion, diagnostics, hover, jump to definition, find references for these JavaScript snippets." from your link, but I don't get `jump to definition` working for example, maybe I'm missing something.

Microsoft's support: I opened an issue there and they closed it :(

* thank you for your amazing work

**Comment by oswaldofreitas** [comment]
what about code completion (intellisense) in the template using Typescript enums for example?

**Comment by octref** [comment]
@oswaldofreitas You can open a new issue for that. That'd be easier for me to track it. Thanks.

**Comment by yoyo930021** [comment]
> what about code completion (intellisense) in the template using Typescript enums for example?

When `vetur.experimental.templateInterpolationService: true`,
You can use it.
```vue
<template>
  <div>{{ Color.red }}</div>
</template>

<script lang="ts">
import Color './enums/color'

export default {
  data () {
    return {
       Color
    }
  }
}
</script>
```
If you use composition api, you can return it in setup function.

**Comment by oswaldofreitas** [comment]
> `vetur.experimental.templateInterpolationService: true`,

that's exactly what I wanted @yoyo930021 ! Thank you so much
