### ISSUE TITLE
PUG and javascript different formatting options

### ISSUE THREAD

**Issue by grofzero** [vuejs/vetur#2279]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: 0.27.3
- VS Code version: 1.49.0

## Problem

I would like to format the javascript part to have single quote, but the pug part to have double quote for html attributes.
Is there a way to configure vetur this way? 

## Reproducible Case
{
	"printWidth": 160,
	"singleQuote": true,
	"semi": true,
	"useTabs": true,
	"tabWidth": 4
}

<template lang="pug">
   div
      div(tabindex="0")
</template>
<script>
export default {
   data: ()=>({
      test: ''
   })
}
</script>

**Comment by Shinigami92** [comment]
https://github.com/prettier/plugin-pug/pull/106
https://github.com/prettier/plugin-pug/issues/105

**Comment by yoyo930021** [comment]
We need to upgrade `@prettier/plugin-pug` version to v1.6.1
