### ISSUE TITLE
intellisense does not work properly with apollo-vue

### ISSUE THREAD

**Issue by code-is-art** [vuejs/vetur#2280]
- [* ] I have searched through existing issues
- [*] I have read through [docs](https://vuejs.github.io/vetur)
- [*] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info
- Platform: macOS
- Vetur version: 0.27.3
- VS Code version: 1.49

## Problem
I am opening this new issue because this exact issue has been closed in the past with no resolution for my situation. Intellisense does not work correctly in .vue files if using custom properties, like vue-apollo. [This issue](https://github.com/vuejs/vetur/issues/481) is still a problem for javascript code since the common fix of adding types to the jsconfig.json is not working for javascript projects. While adding a vue-apollo-fix.d.ts file in the root of the project with the following code does indeed solve the issue I believe it is still worthy of a revisit.
```javascript
import Vue from 'vue'

declare module "vue/types/options" {
    interface ComponentOptions<V extends Vue> {
      apollo?: {}
    }
  }
```
If you want me to close this issue and discuss here [here](https://github.com/vuejs/vetur/issues/481) let me know.

## Reproducible Case
  - Generate a project from https://github.com/octref/veturpack/generate
  - npm install vue-apollo
  - Add the following code to Test.vue
```vue
<template>
  <div>
    {{ test }}
  </div>
</template>

<script>
import * as _ from 'lodash'

export default {
  apollo: {
  },
  data() {
    return {
      test:1
    }
  },
  methods: {
    test() {
      this.te
    }
  }
}
</script> 
```
![with apollo](https://user-images.githubusercontent.com/50637029/93285146-2d00a100-f7a2-11ea-8925-da64b96b661f.png)

![without apollo](https://user-images.githubusercontent.com/50637029/93285125-1eb28500-f7a2-11ea-8c2d-6e74cfa9741d.png)

**Comment by rchl** [comment]
You can use `tsconfig.json` in your javascript project too. If that fixes your issue then go for it. But I'm not sure if that is really the issue. I think you might need to annotate that anyway (either through JSDoc or with external type definition like you did).

**Comment by code-is-art** [comment]
Ok , thanks. I guess what I don't understand is that since apollo-vue has its own type definition shouldn't it not cause problems with intellisense and vetur? I don't understand why I would have to re-annotate it in the root of my project. Also, if this is a repeatable issue shouldn't the work around be posted in the FAQ somewhere?
![apollo-vue](https://user-images.githubusercontent.com/50637029/93338866-e12d1680-f7f8-11ea-8103-64e557688c5f.png)

**Comment by rchl** [comment]
I think this FAQ answer covers it: https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#template-errors-in-components-written-in-javascript

**Comment by code-is-art** [comment]
Yes, I guess it does. I'm still confused by it since the types are annotated within the module itself but I guess its a vscode-vue issue at this point and not vetur. Thanks.

**Comment by rchl** [comment]
I believe it's a Typescript issue or rather limitation. It doesn't help how Vue Options API is designed. The composition API will make some of those issues obsolete.

**Comment by rchl** [comment]
@code-is-art BTW. It doesn't seem like extra annotations are actually needed as long as you register types in `types` array in `tsconfig.json`.

Here is a project where types work for me without any extra annotations: https://github.com/rchl/test-apollo-types

**Comment by code-is-art** [comment]
Yes, you are correct. I had neglected to close and reopen the project on vscode for the tsconfig to take effect.

**Comment by code-is-art** [comment]
for some reason it is still not working in my project without including the .d.ts file but I am sure is something particular to me as the test with the veturpack project has shown

**Comment by code-is-art** [comment]
I'm going to leave this closed but I just teated your https://github.com/rchl/test-apollo-types repo and as soon as you add a main.js file and try to import the vue package it all goes south.
```javascript
import Vue from "vue";
import Test from "./Test.vue";

Vue.config.productionTip = false;

new Vue({
  render: h => h(Test)
}).$mount("#app");
```
I know this is more of a vscode-vue-typescript situation but adding a tsconfig.json **doesn't work** for me.

**Comment by rchl** [comment]
I've added main.js to my project and I don't see the issue.

Also, I don't see the issue with `tsconfig.json`.

It looks like for you it's reading some global tsconfig settings from somewhere that cause the conflict Vue.
The `include` is **NOT** `**/*` by default so that must be coming from somewhere else.
