### ISSUE TITLE
Error: this.$store does not exist on type class. (Vue 3 + TypeScript)

### ISSUE THREAD

**Issue by dannysmc95** [vuejs/vetur#2292]
- [ x ] I have searched through existing issues
- [ x ] I have read through [docs](https://vuejs.github.io/vetur)
- [ x ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Ubuntu 20.04 (WSL2, Ubuntu Budgie)
- Vetur version: 0.27.3
- VS Code version: 1.49.1

## Problem

![Screenshot](https://i.imgur.com/flRWQ8s.png)

## Reproducible Case

1. Use the Vue CLI to create a Vue 3 project with TypeScript using class component style syntax.
2. Go into the store and create any state object.
3. In your class (happens in methods, computed, anything), call `this.$store`,
4. See vetur complain that `this.$store` does not exist on the class.

I followed this link: [https://discordapp.com/channels/325477692906536972/568037134968160256/756604272484941856](https://discordapp.com/channels/325477692906536972/568037134968160256/756604272484941856) after speaking with some people on the Vue discord, and added the `vuex-shim.d.ts` file which did fix it but it stopped working again, I swapped it to use `Store<any>` instead.

See my shim:

```typescipt
import { ComponentCustomProperties } from 'vue'
import { Store } from 'vuex'

declare module '@vue/runtime-core' {
	// Declare your own store states.
	interface State {
		count: number
	}

	interface ComponentCustomProperties {
		$store: Store<any>
	}
}
```

**Comment by dannysmc95** [comment]
Please note, this DOES still work, it's just vetur showing a problem.

**Comment by octref** [comment]
> Use the Vue CLI to create a Vue 3 project with TypeScript using class component style syntax.
> Go into the store and create any state object.
> In your class (happens in methods, computed, anything), call this.$store,
> See vetur complain that this.$store does not exist on the class.

Can you push the result of that to a repo?

**Comment by dannysmc95** [comment]
Hi @octref , repo here: https://github.com/dannysmc95/vetur-issue1

Looks like the issue is specific to Linux (not tested on Windows).

Issue seems to appear on Windows WSL2 - Ubuntu 20.04 and Ubuntu Budgie 20.04

**Comment by dannysmc95** [comment]
@octref I apologise for the delay was trying to narrow the error down.

**Comment by octref** [comment]
Your issue is related to vue-class-component typing so please open issue there. If you pass the same code from your `script` into a TS file it shows error as well.

**Comment by slowaways** [comment]
The same error here using Quasar Framework, after update from Quasar v1 (Vue 2) to Quasar v2 (Vue 3)

**Comment by ngekoding** [comment]
Same problem here

**Comment by luucaskenji** [comment]
@ngekoding or anyone looking for a solution to this. I spent hours looking for a solution and the following code worked for me:
First, when mounting the app, create a global property for `$store`:
```ts
// main.ts

import { createApp } from 'vue';
import App from './App.vue';
import router from './router';
import store from './store';

const app = createApp(App);
app.config.globalProperties.$store = store;
app.use(router).mount('#app');
```

then I created this file in src folder:
```ts
// shims-vuex.d.ts

import { Store } from 'vuex';

declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $store: Store<T>;
  }
}
```
More info [here](https://v3.vuejs.org/guide/typescript-support.html#augmenting-types-for-globalproperties)

**Comment by BroJenuel** [comment]
> @ngekoding or anyone else looking for a solution to this. I spent hours looking for a solution and the following code worked for me:
> First, when mounting the app, create a global property for `$store`:
> 
> ```ts
> // main.ts
> 
> import { createApp } from 'vue';
> import App from './App.vue';
> import router from './router';
> import store from './store';
> 
> const app = createApp(App);
> app.config.globalProperties.$store = store;
> app.use(router).mount('#app');
> ```
> 
> then I created this file in src folder:
> 
> ```ts
> // shims-vuex.d.ts
> 
> import { Store } from 'vuex';
> 
> declare module '@vue/runtime-core' {
>   interface ComponentCustomProperties {
>     $store: Store<T>;
>   }
> }
> ```
> 
> I don't know if it could help, but I stopped and ran the project again (`yarn serve`)
> More info [here](https://v3.vuejs.org/guide/typescript-support.html#augmenting-types-for-globalproperties)

did not work for me

**Comment by veritymedia** [comment]
What fixed it for me was a vuex related package (vuexfire) I stupidly missed, which was breaking my whole store. After trying all of the proposed solutions around, it was one of the most rudimentary ones that fixed it 😂  😅
