### ISSUE TITLE
Shims not working for Vue 3 + TypeScript

### ISSUE THREAD

**Issue by dannysmc95** [vuejs/vetur#2293]
- [ x ] I have searched through existing issues
- [ x ] I have read through [docs](https://vuejs.github.io/vetur)
- [ x ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: All (I am using Linux - Ubuntu 20.04 Budgie)
- Vetur version: 0.27.3
- VS Code version: 1.49.1

## Problem

So this is the issue:
![Screenshot Issue](https://i.imgur.com/Ml1Ut1a.png)

This is my shim for .jpeg images:
![Screenshot Shim](https://i.imgur.com/b5zIlEG.png)

## Reproducible Case

1. Create a new vue project from the CLI with Vue 3 and TypeScript,
2. Add a jpeg image (happens, with all image formats),
3. Then add the screenshot'd shim in `shims-jpeg.d.ts`,
4. Try and image that image into a Vue project.

**Comment by dannysmc95** [comment]
Since using typescript with Vue 3, I have to admit it does look like Vetur is not managing typescript properly within .vue files, and is not aware of the tsconfig or the shims.

**Comment by chanlito** [comment]
@dannysmc95 do you have a repo, which we can look into? I'm using Vetur in my project. It seems fine.

**Comment by dannysmc95** [comment]
@chanlito what package versions are you using? I can see the issue with linux but not mac, it's weird, I haven't got an available repo to use no, but I can try and make one?

**Comment by chanlito** [comment]
I use macOS with Vue 2 atm. Yeah, I repo would really help the team.

**Comment by dannysmc95** [comment]
Hmm @chanlito well the issue is specifically with the Vue 3 preview & TypeScript, I shall create a repo now though, but it definitely looks like Vetur is not playing nicely with TypeScript, I have had more issues than development.

**Comment by 3nuc** [comment]
Shouldn't you just do `export default string`?

**Comment by octref** [comment]
> screenshot'd shim

Screenshot is not a repro case: https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md#how-to-create-a-repro-case

And I cannot reproduce this issue:
![image](https://user-images.githubusercontent.com/4033249/93730262-744fbd00-fbfa-11ea-9416-6511210d1e49.png)

**Comment by dannysmc95** [comment]
I have made a new repo, and tried this again on Ubuntu and it seems fine over WSL2 now, (it wasn't yesterday) so I am not sure, but I am unable to reproduce, if I see the issue again I shall push the repo up and re-open this project.
