### ISSUE TITLE
Bad highlighting tags using CamelCase

### ISSUE THREAD

**Issue by wanxe** [vuejs/vetur#2295]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win/macOS
- Vetur version: 0.27.3
- VS Code version: 1.49.1

## Problem
Highlighting tags aren't working well using CamelCase names on Vue2 and Vue3 SFC's.

![image](https://user-images.githubusercontent.com/10264065/93715177-9e07d600-fb5f-11ea-9bc5-bb70ee67c1c5.png)

## Reproducible Case

Just create a component and declare it between the <template></template> tags in a SFC.

**Comment by octref** [comment]
The highlighting is not semantic. Uppercase components receive special highlight. This is consistent with JSX.
