### ISSUE TITLE
Literal String Union Autocomplete now working inside .vue file

### ISSUE THREAD

**Issue by Shen123456789** [vuejs/vetur#2300]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win10 Home
- Vetur version: 0.27.3
- VS Code version: 1.49.1

## Problem
Autocomplete for string literal union type not working inside **.vue** file (with `<script lang="ts">` ). But working just fine inside **.ts** file.

Working nice in **test.ts**
![working](https://user-images.githubusercontent.com/39094317/93777913-8740ac80-fc4f-11ea-8850-498b85cf62d4.png)

No autocomplete, only information in **test.vue**
![not_working](https://user-images.githubusercontent.com/39094317/93777939-8c056080-fc4f-11ea-8795-63122d8fdfa8.png)

## Reproducible Case
**Declare any kind of type with string literal union type.**
Expected: Give autocomplete just as in a .ts file.
Reality: No autocomplete in **.vue** file

**Note**: I'm not really sure where to post this: vue, vetur or vscode. And i also not really sure whether this should be a bug report or feature request. But since in the vetur doc they said that 

> The IntelliSense should be almost the same to the IntelliSense in js/ts files 
So maybe this is the right place to post this.

**Comment by octref** [comment]
https://github.com/vuejs/vetur/commit/aaff6be212d24ef25ba0156b825504fb1c250521

I cannot recall why I made this change. I'll revert it for now. If I do encounter the bug I'll fix it again...

**Comment by octref** [comment]
I remember the reason now...

If I do make `'` a trigger character, when I type over `'black'|`, I get unwanted completion.

![image](https://user-images.githubusercontent.com/4033249/93794750-160ef280-fc6b-11ea-96fc-8d64f8099219.png)

I'll have to find another fix.

**Comment by Shen123456789** [comment]
@octref Have you been able to fix it without giving unwanted completion ? 
How about make `'` and `"` only if they are immediately after a `(`  ?

**Comment by octref** [comment]
I forgot to reopen.

**Comment by tuan-lm** [comment]
@octref  any news on this ?
In the meantime i think i would rather has that unwanted completion than not auto-complete at all.
Literal String Union is a great way to restraint option, I use them alot and auto-complete will help alot in vue file. 
Unwanted completion can be cancel with a simple `Esc`. The benefit outweight the uncomfortable IMO
