### ISSUE TITLE
collapse code missing end mark

### ISSUE THREAD

**Issue by Ltyi** [vuejs/vetur#2303]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win10
- Vetur version: 0.27.3
- VS Code version: 1.49.1

## Problem

collapse code missing end mark
this issue since version 0.27.0

## Reproducible Case

![Image 8](https://user-images.githubusercontent.com/32029674/93839041-3ddb7600-fcbe-11ea-8f0c-0e1bedb9f0f8.png)

**Comment by octref** [comment]
What's the expected behavior?

**Comment by Ltyi** [comment]
> What's the expected behavior?

![Image 11](https://user-images.githubusercontent.com/32029674/93840685-d6c0c000-fcc3-11ea-9291-791ad7f41f69.png)

---

If you collapse the <script>, missing end tag too

![Image 13](https://user-images.githubusercontent.com/32029674/93840842-5ea6ca00-fcc4-11ea-8a49-ff6569a937e5.png)

**Comment by octref** [comment]
Isn't that same as JS/TS file?

**Comment by Ltyi** [comment]
> Isn't that same as JS/TS file?

.js file

![Image 14](https://user-images.githubusercontent.com/32029674/93842099-4a64cc00-fcc8-11ea-8df5-981605d7720d.png)

.vue file

![Image 15](https://user-images.githubusercontent.com/32029674/93842125-5cdf0580-fcc8-11ea-9e4a-f207f0445cb6.png)

**Comment by yoyo930021** [comment]
VSCode team use a hack for this problem.
https://github.com/microsoft/vscode/issues/47240
https://github.com/microsoft/vscode/blob/f74e473238aca7b79c08be761d99a0232838ca4c/extensions/typescript-language-features/src/languageFeatures/folding.ts#L57
