### ISSUE TITLE
Custom attributes should be shown before other attributes

### ISSUE THREAD

**Issue by akbarnafisa** [vuejs/vetur#2309]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: v0.27.3
- VS Code version: 1.49.0

## Problem

Custom attributes not showing fully on the top if the tag is in the same line and closed

## Reproducible Case

Custom attributes on `f-btn` are showing fully on top, in this case, the `f-btn` does not have closing tag yet

![image](https://user-images.githubusercontent.com/16829122/93873110-5918a680-fcfb-11ea-93e9-a17e465a0319.png)

Custom attributes on `f-btn` are not showing fully on top, in this case, `f-btn` has a closing tag and the same line

![image](https://user-images.githubusercontent.com/16829122/93873266-a268f600-fcfb-11ea-8424-3d7ea0f8f29c.png)

Custom attributes on `f-btn`  are showing again but in a new line and have closing tag

![image](https://user-images.githubusercontent.com/16829122/93873454-ee1b9f80-fcfb-11ea-9c97-fdb5155a55b3.png)

**Comment by octref** [comment]
In the second case, if you scroll up do you see all attributes?
This has something todo with how VS Code chooses completion items. Don't think there's much I can do.

**Comment by akbarnafisa** [comment]
All the attributes can be found below, it's just not showing at the top, so it's kinda hard to know what custom attributes the component has

**Comment by rchl** [comment]
Completion items have a `sortText` property in [LSP spec](https://microsoft.github.io/language-server-protocol/specification#textDocument_completion) so I think you could force the order by generating appropriate `sortText` values @octref .

**Comment by octref** [comment]
Good suggestion, I should probably also use a different `CompletionItem.Kind` so it has a different icon.

**Comment by yoyo930021** [comment]
Fixed #2557
