### ISSUE TITLE
Incorrect html syntax highlighting for kabob case elements.

### ISSUE THREAD

**Issue by jeremy-addy** [vuejs/vetur#231]
- Platform: Win
- Vetur version: 0.7.0
- VSCode version: 1.12.2

Some kabob case custom html elements do not have correct syntax highlighting.

![image](https://user-images.githubusercontent.com/16001179/26982770-0fb3ef36-4cff-11e7-81f9-0490873b1adc.png)

**Comment by codeams** [comment]
I'm having the same issue on Mac OS Sierra. Works fine for two words like "menu-bar" but when you type the second dash the highlight gets messed up.

![screen shot 2017-06-24 at 17 11 51](https://user-images.githubusercontent.com/5368213/27512254-3e5c3afc-5900-11e7-908d-b0e3f94fc1ee.png)
![screen shot 2017-06-24 at 17 11 31](https://user-images.githubusercontent.com/5368213/27512255-3e6fda30-5900-11e7-88ec-935d62422ce2.png)

**Comment by octref** [comment]
Fixed by #332.
