### ISSUE TITLE
Collapse/expand blocks bug in template section

### ISSUE THREAD

**Issue by nicovrg** [vuejs/vetur#2310]
Issue Type: Bug

Collapse/expand blocks (code between <div>...</div>) is not working inside <template>...</template> section. 
The "triangle" icon only appears in the editor at the left side of the <template> tag. 
The "triangle" icon is missing at the other blocks inside <template></template> section, and therefore you can not collapse/expand those blocks.
It was working fine two weeks ago, i've try everything that came in my mind and search for a week now

Extension version: 0.27.1
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:56:10.074Z)
OS version: Linux Mint x64

- I have searched through existing issues, found others people having the same problem but no answer worked for me

**Comment by octref** [comment]
Your issue is closed because you did not provide a repro case. Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.
