### ISSUE TITLE
performance question

### ISSUE THREAD

**Issue by gregveres** [vuejs/vetur#2311]
This is more of a question to every one... 
Is Vuter with eslint very slow? 
I have eslint configured to do the prettying and linting and on TS files it is very fast. But when I am working in a vue file (using composition  API), the linting and formatting is very, very slow. It takes minutes for intellisense to come up and every time I save, I get the popup in the lower corner saying that vuter and eslint are working. More often than not I kill the process so that the save can happen.

What I think is happening is that as I am typing, linting tasks are being queued and executed and they get further and further behind - as if the task is not debounced. If I try something that requires intellisense, it just puts the task on the end of the queue. If I stop typing and leave the editor for a couple of minutes, I get fast intellisense when I go back to the editor. But then as I type again, the editor gets further and further behind.

I also find that if I do leave the save operation to finish and there were prettier formatting issues in the TS code, then the formatting process that finally runs completely messes up the code by creating copies of certain lines, or merging certain lines in an incoherent way.

I am not trying to point the finger anywhere, I am just looking to see if anybody else is having similar issues. I think I will try to make a copy of my project and strip all my code out of it to see if I can get a bare minimum reproduction case.

**Comment by octref** [comment]
Duplicates of #2150. You can try disabling `vetur.languageFeatures.codeActions` in the next verison.
