### ISSUE TITLE
[Template validation props] Error when optional camel-cased props are missing

### ISSUE THREAD

**Issue by victorgarciaesgi** [vuejs/vetur#2314]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.28.0
- VS Code version: 1.49.1

## Problem

Vetur warn me that the props `true-value?` and `false-value?` are not provided, whereas those props are optional in the definition component.

![image](https://user-images.githubusercontent.com/15092120/93994909-b3177b80-fd90-11ea-82e3-dfdb7359e39b.png)

**Toogle.vue**
![image](https://user-images.githubusercontent.com/15092120/93995105-e0fcc000-fd90-11ea-8b51-53b313bff506.png)

**Comment by tup1tsa** [comment]
Definitions are generated with an error.
It should be `'true-value'?` instead of `'true-value?'`. The question mark is placed in the wrong spot

**Comment by yoyo930021** [comment]
> Definitions are generated with an error.
> It should be `'true-value'?` instead of `'true-value?'`. The question mark is placed in the wrong spot

#2342
