### ISSUE TITLE
0.28.0 - Failed to install 'octref.vetur' Windows 10 VS Code user version

### ISSUE THREAD

**Issue by emveeoh** [vuejs/vetur#2316]
- [ x] I have searched through existing issues
- [x ] I have read through [docs](https://vuejs.github.io/vetur)
- [ x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win 10
- Vetur version: 0.28.0
- VS Code version: 
- - Version: 1.49.1 (user setup)
- - Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
- - Date: 2020-09-16T23:27:51.792Z
- - Electron: 9.2.1
- - Chrome: 83.0.4103.122
- - Node.js: 12.14.1
- - V8: 8.3.110.13-electron.0
- - OS: Windows_NT x64 10.0.16299

## Problem
Failed to install 'octref.vetur'.

Unable to install VS Code extension via extensions marketplace interface within VS Code.

![image](https://user-images.githubusercontent.com/16849690/94150509-38f5fe00-fe47-11ea-9e0b-83314d6f3b48.png)

## Reproducible Case
Click 'install' button within Extensions Marketplace panel within VS Code.

**Comment by JW9506** [comment]
Try to find all `octref.vetur` folders inside `~/.vscode/extensions` and install again.

**Comment by yoyo930021** [comment]
I can't reproduce it.

**Comment by emveeoh** [comment]
24-hours later and I am now able to install it. No changes to my system at all. 
Okay to close this issue.  Thank you for your help!
