### ISSUE TITLE
[VTI] VTI should return exit code 1 and display more useful errors on unknown errors

### ISSUE THREAD

**Issue by andrewisaburden** [vuejs/vetur#2324]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Problem

If VTI hits an error not already accounted for with the existing exception handlers, it just prints `VTI operation failed` with no further information. It also exits with error code 0.

## Proposed solution
     console.log(`VTI operation failed with error: ${_err}`);
     process.exit(1);

## Potential Problem

I'm less sure about this one, but also if there are no files it exits with error code 0 (success). I think ESLint does the same, but arguably it should be treated as a failure so that if, say, a CI pipeline tried to run VTI on the wrong directory with no found Vue files it should return a failure so that the mistake can be picked up.

I'm happy to fix these if the solutions are OK.

**Comment by andrewisaburden** [comment]
@yoyo930021 do you have an opinion on exiting with error code 1 (failure) when no files are found?

**Comment by yoyo930021** [comment]
> @yoyo930021 do you have an opinion on exiting with error code 1 (failure) when no files are found?

No, I commit it when I rebase branch.
