### ISSUE TITLE
Bug with optional chaining autocompletion with strictNullCheck enabled

### ISSUE THREAD

**Issue by victorgarciaesgi** [vuejs/vetur#2326]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.28.0
- VS Code version: 1.49

## Problem

Normally since TS 3.7 with `strictNullCheck: true`, VSCode would behave like this when autocompleting a property of a maybe undefined object (in a TS file), and activated by the setting `typescript.suggest.includeAutomaticOptionalChainCompletions`

![Like here](https://code.visualstudio.com/assets/updates/1_41/ts-chain-completion.gif)

However in a `.vue` file, this behaviour is happening

`post` is of type `Post | undefined`, so it would normally add the `?.`, but it even removes the `.`

![Bug vetur](https://user-images.githubusercontent.com/15092120/94248046-3914fd00-ff1e-11ea-9d6f-36fbfa33dc02.gif)

**Comment by johnsoncodehk** [comment]
This may have reference value for fixed:
https://github.com/johnsoncodehk/volar/blob/ad86aafd3c7c6ea99c072daa6204b366e3f2c73a/packages/vscode-typescript-languageservice/src/languageFeatures/completions.ts#L60-L126
