### ISSUE TITLE
When attribute content wrap without square brackets or curly bracket, the highlight is not correct.

### ISSUE THREAD

**Issue by lcysgsg** [vuejs/vetur#2327]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.28.0
- VS Code version: 1.49.2

## Problem

![image](https://user-images.githubusercontent.com/19550000/94250024-41d3f600-ff53-11ea-9034-39e8dd2c7c23.png)

**Comment by yoyo930021** [comment]
The grammar is hard to cross lines.
We need to add `semanticHighlighting` in LSP to fix it.

**Comment by lcysgsg** [comment]
I am now use the vetur 0.31.3 and vscode 1.52.1, hightlight is correct.
![image](https://user-images.githubusercontent.com/19550000/103326414-31b83f00-4a8b-11eb-927c-1cd7256b386b.png)

**Comment by yoyo930021** [comment]
That could be an upstream bug.

You can close issue when problem isn't exist.
