### ISSUE TITLE
Can not import external Vue files

### ISSUE THREAD

**Issue by corsen2000** [vuejs/vetur#233]
- Platform:  Win
- Vetur version: 0.7.0
- VSCode version: 1.13.0

I'm getting a `cannot find module` error in my editor when trying to import external `.vue` files.

```ts
import Grid from ../components/grid.vue';  // This does not have an editor error
import Icon from '@foo/vue-components/icon/icon.vue'; // This has an editor error
```

My projects build successfully imports each type of `.vue` file, so this is an editor only problem.

Will try to create a reproducing repository, but will take some time. If anyone has any ideas in the interim, it would be appreciated.

**Comment by octref** [comment]
Yeah, they probably wouldn't work yet because Vetur doesn't have the setup for such module resolution yet.

It would be great if you can provide a reproducing repo, so I can test and try to support it.

**Comment by HerringtonDarkholme** [comment]
Sorry, importing vue file from node_modules is probably too heavy for TypeScript compiler, which is the underlying engine that powers vetur. 

You can add `declare "*.vue"` to import vue from node_modules.

**Comment by corsen2000** [comment]
@HerringtonDarkholme thanks for the suggestion, I'll try that out and expect it will work. I don't understand the comment though. What does "too heavy" mean. This is an editor only problem. I can compile my TypeScript project without issue and it is fairly quick to do so.

**Comment by HerringtonDarkholme** [comment]
Importing vue requires analyzes script part in files, which requires to analyzes all dependencies in the imported vue. Thus it is very easy to analyze too many files
