### ISSUE TITLE
Workspace Component Data doesn't work

### ISSUE THREAD

**Issue by TonyXiang** [vuejs/vetur#2333]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur/VLS version: 0.28.0
- VS Code (or other LSP client) version: 1.49.2

## Problem

File attributes.json is necessary to make workspace Component Data work but the documentation says all we need to do is  create a file tags.json

## Reproducible Case

I follow the documentation create a file tags.json with:
```json
{ "foo-bar": { "description": "A foo tag", "attributes": ["foo-attr"] } }
```
And add this line to package.json:
```json
{
  "vetur": { "tags": "./tags.json" }
}
```

But it doesn't work.

I additionally create file attributes.json and add to package.json , it works.

**Comment by yoyo930021** [comment]
ref: #2278
