### ISSUE TITLE
Does vetur have plans to support vite?

### ISSUE THREAD

**Issue by akirarika** [vuejs/vetur#2336]
- [x] I have searched through existing issues

## Feature Request

![Snipaste_2020-09-27_17-54-05](https://user-images.githubusercontent.com/33272184/94361952-82b24300-00ea-11eb-8058-1639415d6d65.png)

**Comment by yoyo930021** [comment]
Vetur is editor extension.
Normally it has nothing to do with vite.
In this case, it is a wrong path or wrong tsconfig.json.
You can try to use `./src/store` or set path in tsconfgi.json

**Comment by yoyo930021** [comment]
#2338
