### ISSUE TITLE
use vite path mapping path tips 

### ISSUE THREAD

**Issue by auto-p** [vuejs/vetur#2338]
I use vite, whose root path is the webserver root

IDE vscode prompts me that '/ "is my Linux system root, not my web server root

Can you open the configuration option to set the path mapping

**Comment by yoyo930021** [comment]
https://vuejs.github.io/vetur/setup.html#project-setup

**Comment by auto-p** [comment]
It has no effect on me
i set config options paths .... but 
tsconfig.json

`

{
  "compilerOptions": {
    /* Visit https://aka.ms/tsconfig.json to read more about this file */

    /* Basic Options */
    "target": "es2020",                        
    "module": "commonjs",             
    "strict": true,                        
    "baseUrl": ".",                       
    "paths": {
      "/*":["./"]
    },                       
    "typeRoots": ["./src/types"],                    
    // "types": [],                       
    // "allowSyntheticDefaultImports": true, 
    "esModuleInterop": true,                 
    "skipLibCheck": true,                     
    "forceConsistentCasingInFileNames": true 
  },
  "include": [
    "./src/**/*"
  ]
}

`

**Comment by auto-p** [comment]
thank

**Comment by auto-p** [comment]
tsconfig.json
`
"paths": {
      "/*":["./*"]
    }, 
`
The correct path prompt is obtained in the. TS file

Does not appear to work in the. Vue file
`
<script lang="ts">
import {Block} from "/src/components/Elem/Block.vue";
import setupGameMain from "./setupGameMain";
</script>
`

**Comment by yoyo930021** [comment]
> tsconfig.json
> `"paths": { "/*":["./*"] }, `
> The correct path prompt is obtained in the. TS file
> 
> Does not appear to work in the. Vue file
> `<script lang="ts"> import {Block} from "/src/components/Elem/Block.vue"; import setupGameMain from "./setupGameMain"; </script>`

If you restart vscode when `tsconfig.json` change?
Vetur is not listen `tsconfig.json` change now.

**Comment by auto-p** [comment]
thank , reboot vscode  create vue-shim.d.ts file  content is
`declare module "*.vue" {
  import Vue from 'vue'
  export default Vue
}`
, he run success !
