### ISSUE TITLE
Code folding stopped working from 0.27.x when template lang set to html

### ISSUE THREAD

**Issue by zfeher** [vuejs/vetur#2340]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows 10
- Vetur version: 0.28.0
- VS Code version: 1.49.2

## Problem

Code folding in tempates stopped working when the `lang` attribute is set to `html`. If I omit the `lang` attribute from the template, code folding starts working immediatelly. If the `lang="html"` attribute is there not even the code folding markers are shown. (We need to specify the `lang` attribute cause extract-loader/html-loader won't process the template part otherwise.)

This happens since 0.27.0 release. It worked just fine in 0.26.x version of Vetur.

## Reproducible Case

Open a .vue file which has a template with some foldable content. Set `<template lang="html">` and try folding.

**Comment by yoyo930021** [comment]
Temporary Solution:
```json
// vscode settings.json
{ "editor.foldingStrategy": "indentation" }
```

**Comment by zfeher** [comment]
@yoyo930021 thanks for the tip. until this we had revert back to Vetur 0.26.1.

**Comment by octref** [comment]
We don't support `<template lang="html>`, neither do we support `<style lang="css">` or `<script lang="js">` or `<script lang="babel">`. You can open an issue for the webpack libraries you are using. We'll only follow SFC spec: https://vue-loader.vuejs.org/spec.html#src-imports and the supported blocks are here: https://vuejs.github.io/vetur/highlighting.html
