### ISSUE TITLE
TypeScript Ternary Operator Problem

### ISSUE THREAD

**Issue by bestickley** [vuejs/vetur#2346]
- [x] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.28.0
- VS Code version: 1.49.2

## Problem

![image](https://user-images.githubusercontent.com/35735118/94580489-fe75d200-0247-11eb-8934-275c87b79e7a.png)

## Reproducible Case

Use the ternary operator in TS. I'd expect vetur to ensure `r.completionDate` type is not null

**Comment by yoyo930021** [comment]
Please provide a reproducible project.
https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md

I can't repro it.
![截圖 2020-09-30 下午8 06 33](https://user-images.githubusercontent.com/9126398/94683060-79c6a900-0358-11eb-9417-639ad1c8eb11.png)

**Comment by bestickley** [comment]
The issue is resolved now. Must of been a bad intelligence cache.
