### ISSUE TITLE
When workspace contains prettier/plugin-pug of different version than bundled version, formatting fails

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#2354]
From https://github.com/vuejs/vetur/issues/2347#issuecomment-704664572

https://github.com/prettier/prettier/issues/9342
https://github.com/octref/prettier-double-plugin-load

**Comment by yoyo930021** [comment]
I resolve this problem when refactor dependencyService in #2301 
https://github.com/yoyo930021/vuter/blob/8738eb55957d17bdcc37b0e06e4815e7cc7c7a90/server/src/services/dependencyService.ts#L183
https://github.com/yoyo930021/vuter/blob/8738eb55957d17bdcc37b0e06e4815e7cc7c7a90/server/src/utils/prettier/index.ts#L112
