### ISSUE TITLE
Code actions unavailable with Emacs' lsp-mode

### ISSUE THREAD

**Issue by consoleaf** [vuejs/vetur#2355]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version:
- VS Code version: 1.49.1
- Editor: Emacs

## Problem

When using Emacs with lsp-mode, I try to call code actions, but it spams error messages like:
```
LSP :: Error from the Language Server: Request textDocument/codeAction failed with message: Cannot read property 'codeActions' of undefined (Internal Error)
```

Found in lsp-mode logs:
```
[Trace - 10:36:52 AM] Received response 'textDocument/codeAction - (48)' in 61ms.
Result: null
```

When using VSCode, this or a similar error message doesn't appear, but code actions are still unavailable, including when opening the veturpack sample project

**Comment by adispring** [comment]
I hit this error too.

**Comment by Niedzwiedzw** [comment]
same

**Comment by yoyo930021** [comment]
if anyone try to add `vetur.languageFeatures.codeActions: true` in config?
I don't know much about emacs, and I'm not sure what to do about it.

**Comment by consoleaf** [comment]
emacs-lsp/lsp-mode@46d1a7e4029fb141d41504095e0e10741c7fb624 seems to fix it. Gonna check and report back.
