### ISSUE TITLE
Already included file name

### ISSUE THREAD

**Issue by mmdsb** [vuejs/vetur#2372]
Already included file name 'c:/Users/x/Desktop/vue-typescript-admin-template-master/src/views/tab/components/TabPane.vue' differs from file name 'c:/Users/x/Desktop/vue-typescript-admin-template-master/src/views/tab/components/tabPane.vue' only in casing.Vetur(1261)

## Info

- Platform: Win
- Vetur/VLS version:1261
- VS Code (or other LSP client) version:1.50.0

## Problem
比如先
import TabPane from './components/TabPane.vue'
然后修改引入的名称，文件本身名称不变，只是引入的名称
import TabPane from './components/tabPane.vue'   (T变为小写)
再将t变为大写后出现错误提示，无法消除

**Comment by yoyo930021** [comment]
If you use official extension?
https://marketplace.visualstudio.com/items?itemName=octref.vetur

**Comment by mmdsb** [comment]
> If you use official extension?
> https://marketplace.visualstudio.com/items?itemName=octref.vetur

是的啊

**Comment by yoyo930021** [comment]
> > If you use official extension?
> > https://marketplace.visualstudio.com/items?itemName=octref.vetur
> 
> 是的啊

https://github.com/microsoft/TypeScript/issues/25460
Try this issue.

**Comment by mmdsb** [comment]
> > > If you use official extension?
> > > https://marketplace.visualstudio.com/items?itemName=octref.vetur
> > 
> > 
> > 是的啊
> 
> [microsoft/TypeScript#25460](https://github.com/microsoft/TypeScript/issues/25460)
> Try this issue.

thanks

**Comment by yoyo930021** [comment]
> > > > If you use official extension?
> > > > https://marketplace.visualstudio.com/items?itemName=octref.vetur
> > > 
> > > 
> > > 是的啊
> > 
> > 
> > [microsoft/TypeScript#25460](https://github.com/microsoft/TypeScript/issues/25460)
> > Try this issue.
> 
> thanks

If no problem, you can close this issue. ^_^

**Comment by hellorayza** [comment]
> Already included file name 'c:/Users/x/Desktop/vue-typescript-admin-template-master/src/views/tab/components/TabPane.vue' differs from file name 'c:/Users/x/Desktop/vue-typescript-admin-template-master/src/views/tab/components/tabPane.vue' only in casing.Vetur(1261)
> 
> ## Info
> * Platform: Win
> * Vetur/VLS version:1261
> * VS Code (or other LSP client) version:1.50.0
> 
> ## Problem
> 比如先
> import TabPane from './components/TabPane.vue'
> 然后修改引入的名称，文件本身名称不变，只是引入的名称
> import TabPane from './components/tabPane.vue' (T变为小写)
> 再将t变为大写后出现错误提示，无法消除
> 
> ## Reproducible Case

Refer to:
https://github.com/microsoft/TypeScript/issues/25460#issuecomment-531068391
