### ISSUE TITLE
Vue 3 and Typescript "Property does not exist on type" error with augmented ComponentCustomProperties and data key on component.

### ISSUE THREAD

**Issue by nrgnrg** [vuejs/vetur#2373]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: v0.28.0
- VS Code version: 1.50.0

## Problem

This is my vue-shims.d.ts where I add the type for a global property I've added.

```
import { ComponentCustomProperties } from "vue";
import { CONSTANTS } from "@constants";

declare module "@vue/runtime-core" {
  interface ComponentCustomProperties {
    $const: typeof CONSTANTS;
  }
}
```

This works fine until I add a data option to my component, see screen shots of with and without:

<img width="667" alt="Screenshot 2020-10-10 at 20 57 31" src="https://user-images.githubusercontent.com/25795402/95664020-f2d5b580-0b3b-11eb-8402-c0afca2bcc73.png">

<img width="502" alt="Screenshot 2020-10-10 at 20 57 44" src="https://user-images.githubusercontent.com/25795402/95664033-1862bf00-0b3c-11eb-826a-016952bd02b6.png">

When I add the data option, Vetur thinks $const does not exist on "this", as if what's in data overwrites my augmented ComponentCustomProperties.

Typescript is still getting the type inference as you can see from the cropped off bit of the image with the error so I think this is just a vetur issue.

**Comment by yoyo930021** [comment]
If you can repro in typescript file?

**Comment by nrgnrg** [comment]
Sure I'll do that asap.

I've found a workaround for now, annotating return type of the computed property removed the error but threw a line 0 "cannot read property 'map' of undefined" in eslint. Upgraded `@typescript-eslint/eslint-plugin` and `@typescript-eslint/parser` to the latest version but I had to disable the `@typescript-eslint/camelcase` rule. It seems to have fixed the issue.

**Comment by holwech** [comment]
@yoyo930021 

I have made a repro that I believe should work (but doesn't). You can find the [repro here](https://github.com/holwech/vue-vetur-global-prop-repro).

Relevant code:
```typescript
// src/main.ts
import { createApp } from 'vue'
import App from './App.vue'

interface Constants {
    test1: number;
    test2: number;
}

const CONSTANTS: Constants = {
    "test1": 1,
    "test2": 2
} 

let app = createApp(App)

app.config.globalProperties.$const = CONSTANTS;

declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $const: Constants;
  }
}

app.mount('#app')
```

```typescript
// src/components/HelloWorld.vue

import { defineComponent } from "vue";

export default defineComponent({
  name: "HelloWorld",

  setup() {
    let constants = this.$const; // Error: Property '$const' does not exist on type 'void'
  }
});
```

**Comment by yoyo930021** [comment]
@holwech @nrgnrg 
I think it is a bug in vue 3 typescript type def.
You can open a issue to `vue-next` project.

**Comment by KaelWD** [comment]
https://vuejs.org/v2/guide/typescript.html#Annotating-Return-Types

> Error: Property '$const' does not exist on type 'void'

`setup` doesn't have `this`, use provides instead.

**Comment by yoyo930021** [comment]
@KaelWD you're right.

**Comment by holwech** [comment]
Makes sense, I found a [SO post with some potential solutions](https://stackoverflow.com/questions/64040286/access-this-root-in-vue-js-3-setup) for anyone who finds this issue via Google.

**Comment by nrgnrg** [comment]
The original issue has nothing to do with using setup so I think this is still a bug.

**Comment by yoyo930021** [comment]
> The original issue has nothing to do with using setup so I think this is still a bug.

It is same as https://vuejs.org/v2/guide/typescript.html#Annotating-Return-Types

**Comment by catherineluse** [comment]
in my case I needed this in my `tsconfig.json`:

```
"noImplicitThis": false,
```

**Comment by Inspirateur** [comment]
> https://vuejs.org/v2/guide/typescript.html#Annotating-Return-Types
> 
> > Error: Property '$const' does not exist on type 'void'
> 
> `setup` doesn't have `this`, use provides instead.

I'm having the same issue and I don't understand what "provides" refers to here, the link is broken, could you elaborate ?

**Comment by KaelWD** [comment]
@Inspirateur I've updated my comment, there was two separate answers.
