### ISSUE TITLE
vetur intelliSense doesn't work in project created by @vue/cli

### ISSUE THREAD

**Issue by inkyMountain** [vuejs/vetur#2376]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.28.0
- VS Code version: 1.50.0

## Problem

The data returned in data function of Vue component doesn't appear in intelliSense when typing in template tag within a double braces. 
For example, if i defined data like this:
```javascript
<script>
export default {
  data() {
    return {
      foo: 'foo'
    }
  }
}
</script>
```

The "foo" property should appear in intelliSense list when I try to type foo in double braces
```html
<template>
  <div>
   <!-- When typing f, "foo" should appear in the intelliSense list-->
    {{ f }}
  </div>
</template>
```
What confuses me is that project cloned from https://github.com/octref/veturpack gives proper intelliSense list, but failed when in vue cli scaffolded project.

## Reproducible Case

1. Clone the following repo.
```sh
git clone https://github.com/inkyMountain/vetur-bug.git
cd vetur-bug
yarn install
```

2. Try type one of the returned data in template tag of file "src/App.vue"(line 6)

PS: The following commit shows the changes I make to the project after running Vue cli.
https://github.com/inkyMountain/vetur-bug/commit/484d6127cbc49967708aa9d9f30cfbb85ad798c8

**Comment by yoyo930021** [comment]
Try this
https://vuejs.github.io/vetur/setup.html#project-setup

**Comment by inkyMountain** [comment]
> Try this
> https://vuejs.github.io/vetur/setup.html#project-setup

The url you provide give the following instructions:
1. Install Sass, language-stylus, ESLint VS Code extensions.
2. Configure VS Code config "eslint.validate".
3. Add jsconfig.json with `"include": ["./src/**/*"]`
4. configure path mapping in jsconfig.json.

I tried these but no luck. Could you please clone the repo I provide above to see if there's something wrong? Or it's an issue with vetur's logic?

**Comment by yoyo930021** [comment]
> > Try this
> > https://vuejs.github.io/vetur/setup.html#project-setup
> 
> The url you provide give the following instructions:
> 
> 1. Install Sass, language-stylus, ESLint VS Code extensions.
> 2. Configure VS Code config "eslint.validate".
> 3. Add jsconfig.json with `"include": ["./src/**/*"]`
> 4. configure path mapping in jsconfig.json.
> 
> I tried these but no luck. Could you please clone the repo I provide above to see if there's something wrong? Or it's an issue with vetur's logic?

When you add `jsconfig.json` in project, restart VSCode?
If not, you can try `tsconfig.json`. It can use in javascript project.

**Comment by inkyMountain** [comment]
I finnaly solve the problem by turn on the `vetur.experimental.templateInterpolationService ` option in VS Code GUI settings.
Thanks for your patience !
@yoyo930021
