### ISSUE TITLE
VETUR doesnt work with vue files

### ISSUE THREAD

**Issue by ioma8** [vuejs/vetur#2387]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows
- Vetur version: 0.28.0
- VS Code version: 1.50.0

## Problem

I installed Vetur, opened *.vue file, wanted to do formatting, but VSCODE just says Vue formatter not found :( 

![image](https://user-images.githubusercontent.com/6624752/96233968-1617bf00-0f99-11eb-8d13-df0acfa23d9b.png)

[Error - 10:11:06] No workspace path found. Vetur initialization failed.
Vetur initialized
[Error - 10:11:06] Request textDocument/documentSymbol failed.
  Message: Unhandled method textDocument/documentSymbol
  Code: -32601 
[Error - 10:11:06] Request textDocument/codeAction failed.
  Message: Unhandled method textDocument/codeAction
  Code: -32601 
[Error - 10:11:06] Request textDocument/documentLink failed.
  Message: Unhandled method textDocument/documentLink
  Code: -32601 
[Error - 10:11:06] Request textDocument/colorPresentation failed.
  Message: Unhandled method textDocument/documentColor
  Code: -32601 
[Error - 10:11:06] Request textDocument/foldingRange failed.
  Message: Unhandled method textDocument/foldingRange
  Code: -32601 
[Error - 10:11:07] Request textDocument/codeAction failed.
  Message: Unhandled method textDocument/codeAction
  Code: -32601 
[Error - 10:11:09] Request textDocument/codeAction failed.
  Message: Unhandled method textDocument/codeAction
  Code: -32601 
[Error - 10:11:09] Request textDocument/foldingRange failed.
  Message: Unhandled method textDocument/foldingRange
  Code: -32601 
[Error - 10:11:10] Request textDocument/documentSymbol failed.
  Message: Unhandled method textDocument/documentSymbol
  Code: -32601 
[Error - 10:11:10] Request textDocument/codeAction failed.
  Message: Unhandled method textDocument/codeAction
  Code: -32601 
[Error - 10:11:10] Request textDocument/documentLink failed.
  Message: Unhandled method textDocument/documentLink
  Code: -32601 
[Error - 10:11:10] Request textDocument/colorPresentation failed.
  Message: Unhandled method textDocument/documentColor
  Code: -32601 
[Error - 10:11:10] Request textDocument/codeAction failed.
  Message: Unhandled method textDocument/codeAction
  Code: -32601 
[Error - 10:11:11] Request textDocument/foldingRange failed.
  Message: Unhandled method textDocument/foldingRange
  Code: -32601 
[Error - 10:11:11] Request textDocument/codeAction failed.
  Message: Unhandled method textDocument/codeAction
  Code: -32601 
[Error - 10:11:11] Request textDocument/documentSymbol failed.
  Message: Unhandled method textDocument/documentSymbol
  Code: -32601 
[Error - 10:11:12] Request textDocument/documentLink failed.
  Message: Unhandled method textDocument/documentLink
  Code: -32601 
[Error - 10:11:12] Request textDocument/colorPresentation failed.
  Message: Unhandled method textDocument/documentColor
  Code: -32601 
[Error - 10:11:13] Request textDocument/definition failed.
  Message: Unhandled method textDocument/definition
  Code: -32601 
[Error - 10:11:13] Request textDocument/definition failed.
  Message: Unhandled method textDocument/definition
  Code: -32601 
[Error - 10:11:56] Request textDocument/hover failed.
  Message: Unhandled method textDocument/hover
  Code: -32601 
[Error - 10:11:58] Request textDocument/hover failed.
  Message: Unhandled method textDocument/hover
  Code: -32601 
[Error - 10:12:31] Request textDocument/codeAction failed.
  Message: Unhandled method textDocument/codeAction
  Code: -32601

**Comment by yoyo930021** [comment]
How are you use Vetur?
This project only support a project.
And no support mutli roots and subfolder.

**Comment by octref** [comment]
Your issue is closed because you did not provide a repro case. Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.

**Comment by aminya** [comment]
> How are you use Vetur?
> Vetur only support a project.
> and no support mutli roots and subfolder.

Hi! I am the maintainer of atom-ide-vue for Atom. I have hit the same error. 

How can we fix this? 
https://github.com/atom-ide-community/atom-ide-vue/issues/35

**Comment by yoyo930021** [comment]
https://github.com/vuejs/vetur/issues/2561

**Comment by yoyo930021** [comment]
> > How are you use Vetur?
> > Vetur only support a project.
> > and no support mutli roots and subfolder.
> 
> Hi! I am the maintainer of atom-ide-vue for Atom. I have hit a similar error. 
> 
> How can we fix this? 
> https://github.com/atom-ide-community/atom-ide-vue/issues/35
> 
> @yoyo930021 

https://github.com/vuejs/vetur/issues/2561
