### ISSUE TITLE
jsconfig for vue-project in subfolder

### ISSUE THREAD

**Issue by bunower** [vuejs/vetur#2393]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: WSL2
- Vetur version: 0.28
- VS Code version: 1.50.1

## Problem
I have laravel-project and inside this project is a folder frontend, where i have a vue project.
This vue project is generated by vue-cli.

```
 Laravel
 - app
 - bootstrap
 ...
 - frontend <!-- vue-cli generated -->
 -- src
 - public
 - resources
 ...
 - jsconfig.json
```
I am opening the whole project. 
So i created at top level jsconfig file with:

```
{
    "include": ["./frontend/src/**/*"],
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "@/*": ["frontend/src/*"]
        }
    },
    "exclude": ["./frontendnode_modules"]
}
```
But i didnt get intellisense to work.

**Comment by yoyo930021** [comment]
You need to create `jsconfig.json` and `package.json` in `frontend/src/`.
After that open `frontend/src` folder in VSCode.

**Comment by yoyo930021** [comment]
More advanced support will need to wait for this [RFC](https://github.com/vuejs/vetur/pull/2378) and [RFC](https://github.com/vuejs/vetur/pull/2377).

**Comment by bunower** [comment]
> You need to create `jsconfig.json` and `package.json` in `frontend/src/`.
> After that open `frontend/src` folder in VSCode.

Ok, thanks.
