### ISSUE TITLE
Intellisense Works For Data Props in Computed, And Also It Doesn't Work

### ISSUE THREAD

**Issue by XiNiHa** [vuejs/vetur#2394]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: v0.28.0
- VS Code version: 1.50.1

- Nuxt 2.14.6
- TypeScript 4.0.3

## Problem
<img width="1194" alt="스크린샷 2020-10-22 오전 11 11 42" src="https://user-images.githubusercontent.com/8155259/96816658-a7cf7280-1458-11eb-8781-45226934f27e.png">

The first section shows that the type of the data property is being inferred correctly. However, in the second section, an error occurs. While I've faced that type error for a while, I was bypassing the check by using `$data`. However, I just realized that the type inference was working correctly in the other side.

I've found some similar issues about type inference in computed properties, but not the exact same one - so I decided to submit a new one.

**Comment by XiNiHa** [comment]
<img width="1194" alt="스크린샷 2020-10-22 오전 11 11 42" src="https://user-images.githubusercontent.com/8155259/96817175-c2eeb200-1459-11eb-8547-8d3b60e00710.png">
Okay this looks much weirder... both `events` and `viewDate` are defined in `data()` and only one of them is not getting type inference.

**Comment by XiNiHa** [comment]
Seems to be not related to Vetur

**Comment by yoyo930021** [comment]
Duplicate of #2131

**Comment by yoyo930021** [comment]
Issues: vuejs/vetur#1707, vuejs/vetur#1509, #8721, #9873
