### ISSUE TITLE
Import failded

### ISSUE THREAD

**Issue by timsofteng** [vuejs/vetur#2405]
Hello. I got this error when i tried to import file into vue file.
![image](https://user-images.githubusercontent.com/51912173/97334649-a8676f00-1885-11eb-9f80-db7047a717d2.png)

**Comment by yoyo930021** [comment]
Please use the issue template to open the issue.

**Comment by octref** [comment]
Your issue is closed because you did not provide a repro case. Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.
