### ISSUE TITLE
Support CSS modules: Property '$style' does not exist on type

### ISSUE THREAD

**Issue by tomitrescak** [vuejs/vetur#2407]
- [x] I have searched through existing issues

## Feature Request

It would be amazing if Vetur would support CSS modules using following syntax:

```vue
<template>
  <div :class="[$style.button]">
   Hello
  </div>
</template>

<style module>
.button {
  color: green;
}
</style>

```

**Comment by yoyo930021** [comment]
Add a new file in your project.

```typescript
// shims-css-module-vue.d.ts
import Vue from 'vue'

declare module 'vue/types/vue' {
  interface Vue {
    $style: Record<string, string>
  }
}

```

**Comment by yoyo930021** [comment]
Advanced Support:
Please follow #1372

**Comment by octref** [comment]
You can follow the shim suggestion above to make Vetur recognize `$style`. For more advanced features follow #1372.

**Comment by totkeks** [comment]
> Add a new file in your project.
> You can get basic support.
> 
> ```ts
> // shims-css-module-vue.d.ts
> import Vue from 'vue'
> 
> declare module 'vue/types/vue' {
>   interface Vue {
>     $style: Record<string, string>
>   }
> }
> ```

Unfortunately, this doesn't work anymore with vue3 since the component type is the return type of the `defineComponent` function and you can't augment a type with a new property like you can with an interface.
Any ideas?

**Comment by iqingting** [comment]
> > Add a new file in your project.
> > You can get basic support.
> > ```ts
> > // shims-css-module-vue.d.ts
> > import Vue from 'vue'
> > 
> > declare module 'vue/types/vue' {
> >   interface Vue {
> >     $style: Record<string, string>
> >   }
> > }
> > ```
> 
> Unfortunately, this doesn't work anymore with vue3 since the component type is the return type of the `defineComponent` function and you can't augment a type with a new property like you can with an interface.
> Any ideas?

this worked to me

``` ts
import { ComponentCustomProperties } from 'vue'

declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $style: {
      [key: string]: string
    }
  }
}
```
