### ISSUE TITLE
Optional Chaning does not work on template

### ISSUE THREAD

**Issue by nunonux** [vuejs/vetur#2423]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Windows 10
- Vetur version: 0.28.0
- VS Code version: 1.50.1

## Problem
I'm using Vue 3 and when I use optional chaning in template it shows a error saying "object is possibly 'null' or 'udefined' ". I think it should not show the error because when I use null coalescing operator, no error is shown.

**Error Message**:  "Object is possibly 'null' or 'undefined'.Vetur(2533)"

![image](https://user-images.githubusercontent.com/17728684/97820493-02a96b00-1c9e-11eb-9421-014620db0755.png)

**Comment by octref** [comment]
Your issue is closed because you did not provide a repro case. Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue or reopen this one.

**Comment by yoyo930021** [comment]
Although you didn't provide enough information.
It just so happens that I've had the same problem.
But in the past, Vue2 didn't allow it.
So I choose to ignore it, that's all.

I create a PR to fix it.
Please provide a repro case for the next issue.
