### ISSUE TITLE
Jump to definition from Vue single file components

### ISSUE THREAD

**Issue by AdamBD** [vuejs/vetur#2427]
- [x] I have searched through existing issues

## Feature Request

Hello, 

I have searched and dont see if this has been requested or is an existing feature of the tool, but I would like to suggest a 'jump to definition' feature for this tool. It would be great to jump to the function declaration of functions used inside of vue components, either those imported or being used from vueX store modules etc.

Would something like this be possible?

**Comment by octref** [comment]
Jump to definition is available. Please follow https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md#how-to-create-a-repro-case to create a repro case, illustrate what's not working and open a new isuse. Thank you.
