### ISSUE TITLE
Latest version of Vetur for VSCode doesn't recognize defineComponent from vue

### ISSUE THREAD

**Issue by akessner** [vuejs/vetur#2428]
- [x] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: 
- Vetur version:
- VS Code version:

## Problem
![image](https://user-images.githubusercontent.com/2528305/97919432-714efd00-1d60-11eb-803a-4303ee0e1ff8.png)

VS Code updated the Vetur plugin to 0.29.0 and I had to roll back to 0.28.0 to remove this issue.

**Comment by akessner** [comment]
It took a while, but the problem showed up in the older version as well, it must be something else.

**Comment by octref** [comment]
`defineComponent` is for Vue 3. You might have installed Vue 2. Try `yarn add vue@next`.

**Comment by akessner** [comment]
Thanks, but I was using vue3 for the past few weeks without this error. The code compiles fine and works.

**Comment by yoyo930021** [comment]
Try to delete node_modules folder and reinstall it.
