### ISSUE TITLE
Getting "File name X differs from already included file name Y only in casing" on Windows

### ISSUE THREAD

**Issue by rchl** [vuejs/vetur#2433]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Win
- Vetur version: 0.28.0
- VS Code version: none, using Sublime Text LSP 1.0.18

## Problem

After opening a Vue file, getting a diagnostic error like:

```
File name 'c:/Projekt/temp/lsp-vue-repro/src/App.vue' differs from already included file name 'C:/Projekt/temp/lsp-vue-repro/src/App.vue' only in casing.
```

The issue happens only on Windows and with editors other than VSCode (at least with Sublime Text). The problem is that vetur does some path normalization but not consistent enough to avoid this problem.

Here are differences between the folders passed through initialize request in ST and Vscode:

ST:
```
  "rootPath": "C:\\workspace\\project",
  "rootUri": "file:///C:/workspace/project",
  "workspaceFolders": [
    {
      "name": "project",
      "uri": "file:///C:/workspace/project"
    }
  ]
```

VSCode:
```
    "rootPath": "c:\\workspace\\project",
    "rootUri": "file:///c%3A/workspace/project",
    "workspaceFolders": [
        {
            "uri": "file:///c%3A/workspace/project",
            "name": "project"
        }
    ]
```

As you can see VSCode normalizes drive letter to lower-case which is why there is no issue there. While it would be possible for ST to do the same, it's not really required per LSP spec, and also the issue is really in vetur as I'll demonstrate in next comment.

A related issue in ST: https://github.com/sublimelsp/LSP-vue/issues/83

## Reproducible Case

This issue doesn't reproduce on VSCode as it's doing normalization of passed in paths but it happens in Sublime Text with LSP plugin and possibly on other clients.

**Comment by rchl** [comment]
Vetur generally uses its `getFileFsPath` utility function to get a normalized file system path from the document URI. It does that before validating the document from different notification handlers like `didOpen` or `didChange`.

The one (and the main) problem I found is that it doesn't do any normalization in the `VLS.init()` function. It passes whatever it has gotten from the client to the `dependencyService.init` call which initializes typescript service with non-nomalized filesystem path which can have upper-case drive letter.  That is problematic because that will create a list of project files in `parsedConfig.fileNames` with upper-case drive letter and that list will be later compared with the URIs passed through `didOpen` and other notifications.

**Comment by goodtong** [comment]
![7C%8LQD%%QHF0NISJ9YLEGF](https://user-images.githubusercontent.com/27069899/106440978-74b76900-64b4-11eb-8faf-2d13ff6de0d8.png)

Platform: Win10
Vetur version: 0.32.0

Is this fixed?

**Comment by yinfoyuan** [comment]
Can this prompt be ignored in version 0.32.0

**Comment by rchl** [comment]
Please post a server log somewhere (on gist for example).
https://github.com/vuejs/vetur/wiki/Collecting-LSP-log

(I would suggest restarting VSCode and clear the log manually before reproducing but instead provide a full log since starting VSCode)

**Comment by wangxdmm** [comment]
@rchl 
win10
vetur v0.35.0
```
[Trace - 下午5:20:47] Sending request 'textDocument/codeAction - (17)'.
Params: {
    "textDocument": {
        "uri": "file:///d%3A/web-app/vue3/element-plus/packages/components/button/src/button.vue"
    },
    "range": {
        "start": {
            "line": 39,
            "character": 41
        },
        "end": {
            "line": 39,
            "character": 51
        }
    },
    "context": {
        "diagnostics": [
            {
                "range": {
                    "start": {
                        "line": 39,
                        "character": 41
                    },
                    "end": {
                        "line": 39,
                        "character": 51
                    }
                },
                "message": "File name 'd:/web-app/vue3/element-plus/packages/components/button/src/button.ts' differs from already included file name 'D:/web-app/vue3/element-plus/packages/components/button/src/button.ts' only in casing.\n  The file is in the program because:\n    Imported via './button' from file 'D:/web-app/vue3/element-plus/packages/components/button/src/button.vue'\n    Imported via './button' from file 'D:/web-app/vue3/element-plus/packages/components/button/src/button-group.ts'\n    Imported via './src/button' from file 'D:/web-app/vue3/element-plus/packages/components/button/index.ts'\n    Imported via './button' from file 'd:/web-app/vue3/element-plus/packages/components/button/src/button.vue'",
                "code": 1149,
                "severity": 1,
                "source": "Vetur"
            }
        ],
        "only": [
            "quickfix"
        ]
    }
}
```
![image](https://user-images.githubusercontent.com/18161150/140488407-36ba5d7a-f3a0-428d-8012-73f041ee5709.png)
