### ISSUE TITLE
vue-html not working for SFC

### ISSUE THREAD

**Issue by tbhaxor** [vuejs/vetur#2446]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Linux
- Vetur version: 0.29.0
- VS Code version: 1.50.1

## Problem

I have a vue-typescript project. I only want to disable the formatting (formatter: prettier) for `<template>...</template>` in the .vue SFC files and format the typescript and SCSS.

Content of settings.json in my working directory
```json
{
  "editor.quickSuggestions": {
    "strings": true
  },
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.detectIndentation": true,
  "editor.tabSize": 2,
  "editor.insertSpaces": true,
  "vetur.format.enable": false,
  "css.validate": false,
  "less.validate": false,
  "scss.validate": false,
  "[vue-html]": {
    "editor.formatOnSave": false
  }
}
```

Content of .prettierrc
```json
{
  "endOfLine": "lf",
  "semi": true,
  "useTabs": false,
  "tabWidth": 2,
  "singleQuote": true,
  "trailingComma": "none",
  "bracketSpacing": true
}
```

## Reproducible Case
1. Create a Vue Project `vue create test-project`
2. Install Prettier `yarn add -D prettier`
3. Paste the contents of settings.json (from above) in `**/.vscode/settings.json`
4. Paste the content of prettier configuration (from above) in `**/.prettierrc`
5. Reload editor &rArr; Open any *.vue file (say App.vue) &rArr; Press CTRL+S

**Comment by rchl** [comment]
Please try with `0.29.1` once it shows up.

**Comment by tbhaxor** [comment]
@rchl Any idea when it will be published?

**Comment by rchl** [comment]
It seems to be now.

**Comment by yoyo930021** [comment]
Did this work before old version?

**Comment by tbhaxor** [comment]
Nope it was not working, so eventually i had to use `[vue]` and that would forbid prettier to format entire vue SFC file

**Comment by yoyo930021** [comment]
This setting is only work in one file. It is a limit in VSCode.
You can set `vetur.format.defaultFormatter.html: none` to do it.

**Comment by tbhaxor** [comment]
> `vetur.format.defaultFormatter.html: none` to do it.

@yoyo930021 this config has no effect. It seems to be ignored like `[vue-html]`

**Comment by yoyo930021** [comment]
> > `vetur.format.defaultFormatter.html: none` to do it.
> 
> @yoyo930021 this config has no effect. It seems to be ignored like `[vue-html]`

The `vue-html` is not working in Vue SFC.
Because it is working when vue-html file.
The `vue-html` is a lang id in VSCode.
The lang id is based on a file in VSCode.
So, Vue SFC lang id is `vue` not `vue-html`. VSCode can't allow have multiple lang id in a file.

**Comment by yoyo930021** [comment]
> > `vetur.format.defaultFormatter.html: none` to do it.
> 
> @yoyo930021 this config has no effect. It seems to be ignored like `[vue-html]`

Or do you mean it still formats the template?

**Comment by tbhaxor** [comment]
> Or do you mean it still formats the template?

@yoyo930021 Yes. It still formats the template data

**Comment by yoyo930021** [comment]
> > Or do you mean it still formats the template?
> 
> @yoyo930021 Yes. It still formats the template data

![Nov-10-2020 14-16-44](https://user-images.githubusercontent.com/9126398/98635168-719e5800-235f-11eb-9c5b-a813786e6fda.gif)
It is working for me.

**Comment by tbhaxor** [comment]
![Peek 2020-11-11 06-20](https://user-imag.githubusercontent.com/28386721/98751442-1fece080-23e6-11eb-9b3c-97be1ddcdb44.gif)
@yoyo930021 Not working in my case

**Comment by yoyo930021** [comment]
> ![Peek 2020-11-11 06-20](https://user-images.githubusercontent.com/28386721/98751541-4c086180-23e6-11eb-90f9-23c3bb973f83.gif)
> 
> @yoyo930021 Not working in my case

Disable all other extension?
Prettier extension can format for Vue SFC.

**Comment by tbhaxor** [comment]
> > ![Peek 2020-11-11 06-20](https://user-images.githubusercontent.com/28386721/98751541-4c086180-23e6-11eb-90f9-23c3bb973f83.gif)
> > @yoyo930021 Not working in my case
> 
> Disable all other extension?
> Prettier extension can format for Vue SFC.

Yeah disabling extensions work. Not all just disabling prettier works but thats not the solution to this problem as i have express js code withinn same workspace and there i need formatting....

**Comment by yoyo930021** [comment]
> > > ![Peek 2020-11-11 06-20](https://user-images.githubusercontent.com/28386721/98751541-4c086180-23e6-11eb-90f9-23c3bb973f83.gif)
> > > @yoyo930021 Not working in my case
> > 
> > Disable all other extension?
> > Prettier extension can format for Vue SFC.
> 
> Yeah disabling extensions work. Not all just disabling prettier works but thats not the solution to this problem as i have express js code withinn same workspace and there i need formatting....

You can set VSCode setting.
```json
{
  [vue]: {
    "editor.defaultFormatter": "octref.vetur"
  }
}
```

**Comment by tbhaxor** [comment]
@yoyo930021 thanks man. it solved my problem for now. waiting for the fix for `[vue-html]` (original issue)

**Comment by yoyo930021** [comment]
> @yoyo930021 thanks man. it solved my problem for now. waiting for the fix for `[vue-html]` (original issue)

Ha, we can't save original problem.
It is a limit in VSCode. 😂
