### ISSUE TITLE
更新到0.29.1后vue文件高亮失效了，回退到0.29.0有可以

### ISSUE THREAD

**Issue by ybchen292** [vuejs/vetur#2447]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [ ] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: 
- Vetur version:
- VS Code version:

**Comment by yoyo930021** [comment]
Please provide information in issue.
Alternatively, try to reinstall vetur.
We have found probability of installation failure.

**Comment by ybchen292** [comment]
尝试卸载重装vscode已解决
