### ISSUE TITLE
Display code frame in VTI

### ISSUE THREAD

**Issue by yoyo930021** [vuejs/vetur#2449]
- [x] I have searched through existing issues

## Feature Request
Display code frame, Like: lines, code.

https://github.com/vuejs/vetur/issues/1635#issuecomment-724118122

**Comment by lzxb** [comment]
Do you have an update plan?

**Comment by yoyo930021** [comment]
> Do you have an update plan?

If you can open a PR, I'll handle it.
Otherwise I need time to make it happen.

**Comment by lzxb** [comment]
I don't know much about it and can't help

**Comment by lzxb** [comment]
Thank you for your contribution to the community
