### ISSUE TITLE
Refactor VTI with modern cli library

### ISSUE THREAD

**Issue by yoyo930021** [vuejs/vetur#2451]
- [x] I have searched through existing issues

## Feature Request

Refactor VTI with modern cli library:
Like: commander, yargs

**Comment by andrewisaburden** [comment]
@yoyo930021 do you intend to implement this?

**Comment by yoyo930021** [comment]
> @yoyo930021 do you intend to implement this?

I plan to deal with monorepo first.
If you have time, you can send a PR!

**Comment by Monchi** [comment]
I will work on this

**Comment by yoyo930021** [comment]
> I will work on this

Welcome, Thanks your help.
