### ISSUE TITLE
Extension Vetur cannot format MyComponent.Vue

### ISSUE THREAD

**Issue by mesqueeb** [vuejs/vetur#2452]
Heya! I'm not sure why but Vetur doesn't run on some of my projects.
I have made one of them easily clonable so you can try reproduce it. Vetur won't run at all for me but not sure why.  : )
I think I did the setup correctly though!!

- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: macOS Catalina
- Vetur version: v0.29.1
- VS Code version: Version: 1.51.0

## Problem

<img width="476" alt="image" src="https://user-images.githubusercontent.com/3253920/98641121-9d750a00-236e-11eb-9fe9-1d14e8ebe859.png">

<img width="347" alt="image" src="https://user-images.githubusercontent.com/3253920/98641094-8e8e5780-236e-11eb-9516-61bebe0e55b4.png">

## Reproducible Case

```
git clone https://github.com/fergusmeiklejohn/cycraft
git checkout vetur-issue
yarn
code .
```
Then navigate to any vue file and press `⌘S`

**Comment by rchl** [comment]
You have `"vetur.format.enable": true,` in your local `.vscode/settings.json`.

**Comment by mesqueeb** [comment]
@rchl thanks so much!!! I can't believe I spent so long trying to figure it out, when it's a simple stupid oversight! :P 

@yoyo930021 is it maybe possible to change the error message from
> Extension 'Vetur' cannot format 'src/App.vue'

to something like:
> Extension 'Vetur' did not format because it is disabled

**Comment by yoyo930021** [comment]
> @rchl thanks so much!!! I can't believe I spent so long trying to figure it out, when it's a simple stupid oversight! :P
> 
> @yoyo930021 is it maybe possible to change the error message from
> 
> > Extension 'Vetur' cannot format 'src/App.vue'
> 
> to something like:
> 
> > Extension 'Vetur' did not format because it is disabled

I can't actually do in LSP.

**Comment by mesqueeb** [comment]
Ok, thanks anyway! : )
cya around!!

**Comment by sebastianjung** [comment]
for anyone else having this problem. I had to remove something like this from my settings.json for it to format again:
```
...,
 "[vue]": {
        "editor.tabSize": 2,
        "editor.defaultFormatter": "..."
 },
 ...
```

**Comment by Lietsaki** [comment]
@sebastianjung Thank you very much! That solved it for me.
