### ISSUE TITLE
There is an error when I input ' this. '

### ISSUE THREAD

**Issue by dgburn** [vuejs/vetur#246]
vetur initialized
[Error - 下午5:25:20] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'parameters' of undefined
  Code: -32603

**Comment by dgburn** [comment]
When there is  the components Object will appear this error

**Comment by octref** [comment]
Code? Screenshot? Platform? Version?

**Comment by HerringtonDarkholme** [comment]
Probably a duplicate of #296 .

**Comment by octref** [comment]
Closed due to inactivity. Feel free to reopen if you can provide more info.
