### ISSUE TITLE
When formatting the vue file, the `template lang='pug'` node will be cleared.

### ISSUE THREAD

**Issue by richex-cn** [vuejs/vetur#2460]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Windows 10 2004
- Vetur version: 0.30.0
- VS Code version: 1.51.1

## Problem

![a](https://user-images.githubusercontent.com/25103518/98911195-2c189100-24ff-11eb-9186-3e36faa74251.gif)

No output from the Vue Language Server output panel.
After falling back to 0.29.1, the problem no longer occurs.

**Comment by richex-cn** [comment]
@yoyo930021 I installed version 0.30.1, but this problem still exists.

**Comment by yoyo930021** [comment]
> @yoyo930021 I installed version 0.30.1, but this problem still exists.

If you restart?

**Comment by richex-cn** [comment]
@yoyo930021 

This problem still exists in my workspace :

![a](https://user-images.githubusercontent.com/25103518/99031654-963e3e00-25b2-11eb-93c6-9c474825cd3c.gif)

But formatting after creating a new directory to test it, is normal :

![b](https://user-images.githubusercontent.com/25103518/99031819-0056e300-25b3-11eb-93d5-3a3a02831af5.gif)

**Comment by yoyo930021** [comment]
> @yoyo930021
> 
> This problem still exists in my workspace :
> 
> ![a](https://user-images.githubusercontent.com/25103518/99031654-963e3e00-25b2-11eb-93c6-9c474825cd3c.gif)
> 
> But formatting after creating a new directory to test it, is normal :
> 
> ![b](https://user-images.githubusercontent.com/25103518/99031819-0056e300-25b3-11eb-93d5-3a3a02831af5.gif)

What is your .prettierrc file content?

**Comment by richex-cn** [comment]
The `vetur.useWorkspaceDependencies` is `true`, and the `.prettierrc.js` file of the current workspace is as follows:

```
module.exports = {
  tabWidth: 2,
  printWidth: 80,
  semi: false,
  singleQuote: true,
  proseWrap: 'preserve',
  requirePragma: false,
  bracketSpacing: true,
  arrowParens: 'avoid',
  trailingComma: 'none'
}
```

@yoyo930021

**Comment by yoyo930021** [comment]
Can you try to use this vsix?
[vetur-0.30.1.vsix.zip](https://github.com/vuejs/vetur/files/5535778/vetur-0.30.1.vsix.zip)
https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#install-an-old-version-of-vetur

**Comment by richex-cn** [comment]
@yoyo930021 Before installation, I uninstalled this extension and deleted the `%USERPROFILE%\.vscode\extensions\octref.vetur-0.30.1\` directory. Then run `code.exe --install-extension vetur-0.30.1.vsix` through the command line to open VSCode, and I don't see the Vetur extension in the plug-in list, the same is true for restarting VSCode.

![20201113_173416](https://user-images.githubusercontent.com/25103518/99058264-ed0a3e80-25d7-11eb-8e6a-0a929fc9a499.png)

So I using the Install from VSIX command in the Extensions view command drop-down, And completed the installation of the Vetur extension. But this problem still exists.

**Comment by yoyo930021** [comment]
Can you provide your project or any repro project?
https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md
If you don't want to go public, you can send me an email.

If none of these,
https://github.com/vuejs/vetur/issues/2468#issuecomment-726561376

**Comment by richex-cn** [comment]
I tried to clone the project on another device, but this problem did not occur. After trying for a while, I found that setting `vetur.useWorkspaceDependencies` to true will cause the problem to appear, so it should be the library introduced by the plugin or I introduced The library is caused by a problem.

This is a minimal repro case:

https://github.com/richex-cn/repro-vetur-formatting-bug-issue-2460

**Comment by IvanCaceres** [comment]
I just started experiencing this issue after  all formatting was working correctly all day.

Suddenly on save now it's deleting the contents of <template lang="pug">. Very frustrating for this issue to randomly appear.

**Comment by richex-cn** [comment]
@IvanCaceres You can try the way I mentioned above, if you still can't solve it, you can communicate with @yoyo930021 .

**Comment by yoyo930021** [comment]
Reason: https://github.com/vuejs/vetur/issues/2347#issuecomment-704664572
I will close searching plugin feature and use found lib from vetur.

**Comment by yoyo930021** [comment]
Ha, I found the problem.
In your project, it have a `prettier` lib but version is `1.x.x`.
This version don't support plugin.
