### ISSUE TITLE
Unexpected error at end of git diffs

### ISSUE THREAD

**Issue by jods4** [vuejs/vetur#2470]
- [x] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Win
- Vetur version: 0.30.1
- VS Code version: 1.51.1

## Problem
When I look at a commit diff, inside a .vue file, there's always an error added at the end of the file for `vue/comment-directive`.
This error is only there in the diff view, it doesn't appear in the same file opened normally.

Git Diff:
![image](https://user-images.githubusercontent.com/3832820/99079271-02736e80-25c0-11eb-82e4-ff326b6b1c17.png)

Editor:
![image](https://user-images.githubusercontent.com/3832820/99079352-2040d380-25c0-11eb-8fb9-be4c8c35ef8c.png)

## Reproducible Case
Happens in any .vue file.

**Comment by yoyo930021** [comment]
What kind of extension did you use for git diff ?

**Comment by jods4** [comment]
Isn't it the built-in VS Code diff view?

For example just go to the SOURCE CONTROL panel and view the currently staged changed by double-clicking.
![image](https://user-images.githubusercontent.com/3832820/99100124-a9193880-25db-11eb-9bd7-15ac19e45ab1.png)

The nice red line with error text is provided by **Error Lens** extension, but if you look closely you'll notice there's a red squiggle there, which is the default error widget.

I also have **GitLens** and **Git Graph** installed but I'm pretty sure they are unrelated to this behavior.

**Comment by yoyo930021** [comment]
I want to close diagnostic to fix it in git diff view.
Ref: https://github.com/microsoft/vscode-eslint/issues/216
