### ISSUE TITLE
Vue Language Server not able to startup on fresh WSL installation.

### ISSUE THREAD

**Issue by johannboehme** [vuejs/vetur#2475]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [X] I have tried reinstalling the WSL instance several times.

## Info

- Platform: WSL2 Debian + latest vim + coc.nvim + coc-vetur
- Vetur version: 1.2.2
- VS Code version: vim 8.2 latest

## Related (came from):
https://github.com/neoclide/coc-vetur/issues/57

## Problem

Language server stays in state "starting":
![image](https://user-images.githubusercontent.com/58803954/99244883-004d2200-2803-11eb-847b-82cb7454fa9e.png)

coc.nvim is unable to provide syntax suggestions:
![image](https://user-images.githubusercontent.com/58803954/99245029-3a1e2880-2803-11eb-9751-073a74a47942.png)

LSP inspector shows, that only one initialization message is sent between components:
![image](https://user-images.githubusercontent.com/58803954/99245125-5f129b80-2803-11eb-9a0a-9685f0a78320.png)
![image](https://user-images.githubusercontent.com/58803954/99245260-9719de80-2803-11eb-90ef-3d4b1419bea4.png)

I also tried to install and use the vls directly as described here:
https://github.com/vuejs/vetur/tree/master/server

It didn't report any errors but also resulted in same behavior:
![image](https://user-images.githubusercontent.com/58803954/99246253-486d4400-2805-11eb-88f1-f210c6b0791c.png)

## Reproducible Case

- Install WSL Debian on Win10
- wsl.exe --set-version Debian 2
- install nvm / nodejs / vue  / vim / coc.nvim
- CocInstall coc-vetur

I reproduced this behavior on several newly installed instances.
Other coc language server implementations (e.g. coc-html, coc-java) work as intended.

Any input how to analyze this further would be very appreciated.

BR,
J.Boehme

**Comment by yoyo930021** [comment]
There are actually a lot of related issues in WSL.
But we haven't had the environment or the time to deal with it.
It would be great if someone could help with that.

**Comment by yoyo930021** [comment]
The problem may be solve in new version.
https://twitter.com/kazuyukimiyake/status/1336950473765470208?s=20

**Comment by johannboehme** [comment]
Verified!
