### ISSUE TITLE
Vetur format vue with prettier-eslint failed: "Prettier-Eslint format failed: Cannot find module 'prettier'"

### ISSUE THREAD

**Issue by Alieckxie** [vuejs/vetur#2477]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Win
- Vetur version: v0.30.2
- VS Code version: 1.51.1

## Problem

format with "prettier-eslint" failed_(:з」∠)_
Vue Language Server output is: 
```
[INFO ] Loaded bundled typescript@4.0.5.
[INFO ] Loaded bundled prettier.
[INFO ] Loaded bundled @starptech/prettyhtml.
[INFO ] Loaded bundled prettier-eslint.
[INFO ] Loaded bundled prettier-tslint.
[INFO ] Loaded bundled stylus-supremacy.
[INFO ] Loaded bundled @prettier/plugin-pug.
Vetur initialized
Prettier-Eslint format failed
[Error - time] Cannot find module 'prettier'
Require stack:
- c:\Users\Administrator\.vscode\extensions\octref.vetur-0.30.2\server\dist\vls.js
- c:\Users\Administrator\.vscode\extensions\octref.vetur-0.30.2\server\dist\vueServerMain.js
```

## Reproducible Case

just install vetur and set config `"vetur.format.defaultFormatter.js": "prettier-eslint",` and create a simple vue project by vue/cli and then open a vue file and then `alt + shift + f` then Vue Language Server output appear message show above.

**Comment by Vorror** [comment]
I'm also using "prettier-eslint" and receiving the same error:


```js
Prettier-Eslint format failed
[Error - 3:08:29 PM] Cannot find module 'prettier'
```

**Comment by Tirro** [comment]
Platform: Win
Vetur version: v0.30.2
VS Code version: 1.51.1

I'm using "prettier-tslint" and i've the same problem:

```
[Error - 11:03:49] Cannot find module 'prettier'
Require stack:
- c:\Users\...\.vscode\extensions\octref.vetur-0.30.2\server\dist\vls.js
- c:\Users\...\.vscode\extensions\octref.vetur-0.30.2\server\dist\vueServerMain.js
Prettier-Tslint format failed
```

**Comment by an-tho-ny** [comment]
I have the same issue. The only thing I have done recently is update VS Code to version **1.51.1**.

I'm not sure if that has anything to do with it but it looks like most of us have the same version of VS Code.

**Comment by yoyo930021** [comment]
Fixed in https://github.com/vuejs/vetur/commit/a6022bfa0c8bbfdb26bab684a1839d19cc6fefd0.

**Comment by cdoneshot** [comment]
When will the new version be released? @yoyo930021

**Comment by yoyo930021** [comment]
> When will the new version be released? @yoyo930021

Released v0.30.3

**Comment by Vorror** [comment]
@yoyo930021 v0.30.3 is still partially broken for me. 

The `Format Document` command works again, but it gives different results than `prettier + eslint --fix` commands?

**Comment by yoyo930021** [comment]
> @yoyo930021 v0.30.3 is still partially broken for me.
> 
> The `Format Document` command works again, but it gives different results than `prettier + eslint --fix` commands?

If you use `vetur.useWorkspaceDependencies: true`?
Please open a new issue.
