### ISSUE TITLE
V 0.30.2 Is currently broken

### ISSUE THREAD

**Issue by BladeBoles** [vuejs/vetur#2479]
- [x ] I have searched through existing issues
- [x ] I have read through [docs](https://vuejs.github.io/vetur)
- [ x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [ x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Linux
- Vetur version: 0.30.2
- VS Code version: 1.51.1

## Problem

Vue template syntax highlighting does not work.  If you look at your NodeCI check for 0.30.2, you'll see that it failed.  Rolling back to the previous v0.30.1 works.

**Comment by BladeBoles** [comment]
I'm sorry, my steps to reproduce didn't save.  Simply open a .vue file and observe the template region of the file.  There will be no syntax highlighting.

**Comment by yoyo930021** [comment]
If you try to reinstall?
We get some feedback.
When install new version, syntax highlighting is broken sometimes.
The problem is solved when reinstall.

**Comment by BladeBoles** [comment]
> If you try to reinstall?

Reinstalling then restarting vs code did fix it.  Sorry, didn't think to try this after rolling it back!
