### ISSUE TITLE
Add option to disable formatting

### ISSUE THREAD

**Issue by denious** [vuejs/vetur#248]
- Platform: Win
- Vetur version: 0.7.0
- VSCode version: 1.13.1

I am using Vetur is conjunction with Beautify, and prefer Beautify's full formatting options which work just fine in Vue files when added as an HTML format to **beautify.languages**.

However I am worried that 2 extensions doing the same thing underneath might present unexpected behaviour. It would be great to just set **vetur.format.enabled = false** and not worry about it!

This is the kind of configuration that one would expect with this feature:

```
        "vetur.format.enabled": false,
        "beautify.language": {
            "js": {
                "type": [
                    "javascript",
                    "json"
                ],
                "filename": [
                    ".jshintrc",
                    ".jsbeautify"
                ]
            },
            "css": [
                "css",
                "scss"
            ],
            "html": [
                "htm",
                "html",
                "vue"
            ]
        }
```

Thanks,
Denis

**Comment by ericcirone** [comment]
I would like this as well. We have a .jsbeautifyrc which we use and would like to use Beautify to format. Thanks!

**Comment by ericcirone** [comment]
Any update on this?

**Comment by octref** [comment]
I suggest you having "HookyQR.beautifyFile` bound to a shortcut and use it.

We'll move away from `js-beautify` soon. This option sounds confusing.

**Comment by denious** [comment]
Do you mean you'll be getting rid of auto-formatting?
"This option" that I suggested is just a flag to disable Vetur auto-formatting and let your users decide on the formatting tool of their choice.

**Comment by chrisvfritz** [comment]
@octref I think this should possibly be reconsidered. The extension already allows validation for each language to be disabled, because users may want to use external validation. Similarly, it seems to make sense that users may also want to handle formatting outside of Vetur.

For example, I'm working on a project that's using Stylelint and Prettier in single-file components and we just tried enabling `editor.formatOnSave`. It was working great, except for Vetur's formatting, which has subtle bugs that misformat most of our templates. It's a significant enough problem that the team is now talking about removing Vetur completely, which would be a shame.

What do you think? Could it be possible to introduce a setting to disable formatting?

**Comment by octref** [comment]
@chrisvfritz Literally doing that as I'm talking. https://github.com/vuejs/vetur/issues/221#issuecomment-335319050

You should be able to set `vetur.format.defaultFormatter.html` as `none` in 0.10.0 and disable formatter depending on language.

**Comment by chrisvfritz** [comment]
Beautiful! 😄

**Comment by octref** [comment]
On the other hand, try changing `"vetur.format.html.wrap_attributes"` to see if that fixes any js-beautify issues. But in the long term I plan to contribute to prettier-html and remove js-beautify https://github.com/prettier/prettier/issues/1882

However I'm curious, how are you using Stylint and Prettier in SFC now? Would be interested in learn about your setup so I can build support for it (and use it myself :p).

**Comment by ericcirone** [comment]
@octref great to hear! I am using prettier for all JS now except .vue files. @chrisvfritz I would love to hear as well how you are using prettier for .vue files. Thanks.

**Comment by chrisvfritz** [comment]
> Try changing "vetur.format.html.wrap_attributes" to see if that fixes any js-beautify issues.

The problem does seem to be related to that setting. Here's [what I'm seeing happen](http://g.recordit.co/x6UQbnDSRz.gif) with the value `"force-expand-multiline"`, which is unfortunately the only option that doesn't interfere with the style guide [alignment of eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue/pull/205).

> How are you using Stylint and Prettier in SFC now?

I will probably write a blog post once everything is a little more stable, but here's [what I have](https://gist.github.com/chrisvfritz/747a4b702cd603221d3127cbdcd7b589) so far. 

Some features:

- Format on save for HTML in `.vue` files (with Vetur)
- Lint and fix on save for HTML in `.vue` files (with ESLint)
- Format on save for JS in `.js` files (with Prettier) and `.vue` files (with Prettier and Vetur)
- Lint and fix on save for JS in `.js`  and `.vue` files (with ESLint)
- Format on save for SCSS + CSS Modules in both `.scss` and `.vue` files
- Lint on type for SCSS + CSS Modules in both `.scss` and `.vue` files

Limitations:

- Some parts of this are a little hacky until I've made a few improvements to various packages used here
- Stylelint still doesn't seem to understand CSS module exports very well, so I just turn it off for that block.
- If you try to use Stylelint to _fix_ SCSS in `.vue` files, it will erase everything except your styles. 😢  
- That one formatting rule of Vetur breaks a lot of HTML, especially if it includes any multi-line comments or attribute values.

@octref @ericcirone I hope that's helpful!
