### ISSUE TITLE
Unexpected errors occur when using decorators

### ISSUE THREAD

**Issue by Xooone47** [vuejs/vetur#2481]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform:  macOS
- Vetur version: 0.30.2
- VS Code version: 1.48.1

## Problem

Some unexpected errors occur when using decorators in vue component methods. 

Babel and eslint configs are good and compiling done without any error. And the program runs rightly.

Vue component:
![image](https://user-images.githubusercontent.com/7253061/99344278-a57efd80-28ca-11eb-957f-16295149b419.png)

Terminal:
![image](https://user-images.githubusercontent.com/7253061/99344564-58e7f200-28cb-11eb-8fb6-0f3cc367bd0a.png)

Any way to resolve this problem?

**Comment by yoyo930021** [comment]
Open https://www.typescriptlang.org/tsconfig#experimentalDecorators in your `tsconfig.json` or `jsconfig.json`.
and restart VSCode.

**Comment by Xooone47** [comment]
> Open https://www.typescriptlang.org/tsconfig#experimentalDecorators in your `tsconfig.json` or `jsconfig.json`.
> and restart VSCode.

**Comment by Xooone47** [comment]
> Open https://www.typescriptlang.org/tsconfig#experimentalDecorators in your `tsconfig.json` or `jsconfig.json`.
> and restart VSCode.

I enabled this option already,  it resolves the decorator warns in a .js file. But warns still occur in .vue files.

It looks like a vetur problem instead of a vscode problem... 

![image](https://user-images.githubusercontent.com/7253061/99352801-38756300-28de-11eb-9275-9fe3eca6f3e3.png)

**Comment by yoyo930021** [comment]
It is not valid code.

https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVwCbABGEqawcAFALYDOAXHCklYcFAJRwDeAUHHFGAwkUXBRgBDKAHMhDCSgCeAGjhgoEMGxiKA0sEUMaMKJhTTVBGmlNgY0BgAUNW2IoAiwa7fsc4AXgA+bj5+ASERXF4wsLQcBExpEQlCABtgBhMkYGVQmOAmKjYU9IYrG0w7aAA6AuZitJy8sNl4CnZ5JRCYmIB5QgArYAxqggSUYGdNbUVxAAtMGlV1abd9FW6emLiUBKSoEoy4LKat-MKG0vwvCqqoWouDxtyzsIA3CVTsspufGo+vsBqoQzHh5ot2M0YgBfSFQsKCYSiSgwBY0OASdEKRTsADaK1cOnWAF14dDmuT+OTyTweKBILBrggJEhUvBoowJEUGAByACCYDAPJecDiVEgExQMHo3GhIqKqIgeBlHP4AAECMRSMAKABmAAM+shMTmCjw6QAwqbzOR2iEKaFqbS0KlMei+ZsNUQSOgdQajaFrebgFaFLJKJxeI6eOSgA

**Comment by yoyo930021** [comment]
https://github.com/vuejs/vetur/issues/1461
https://babeljs.io/blog/2018/09/17/decorators#object-decorators

**Comment by vw331** [comment]
does anyone fix this?

**Comment by Xooone47** [comment]
> does anyone fix this?

ES doesn't support decorator syntax in object，you can write vue class component then use the decorator

**Comment by vw331** [comment]
> > does anyone fix this?
> 
> ES doesn't support decorator syntax in object，you can write vue class component then use the decorator

but the code is work when i disable vetur。can i use decorator in .vue file without typescript?

**Comment by Xooone47** [comment]
> > > does anyone fix this?
> > 
> > 
> > ES doesn't support decorator syntax in object，you can write vue class component then use the decorator
> 
> but the code is work when i disable vetur。can i use decorator in .vue file without typescript?

https://babeljs.io/blog/2018/09/17/decorators#object-decorators  , object decorator proposal is deprecated，you can write decorator in component with [vue-property-decorator](https://github.com/kaorun343/vue-property-decorator)
