### ISSUE TITLE
Pug: Support Ctrl+Click (Go to Definition)

### ISSUE THREAD

**Issue by Shifu462** [vuejs/vetur#2482]
- [x] I have searched through existing issues

## Feature Request

![image](https://user-images.githubusercontent.com/17011936/99400149-ad08cb80-28f7-11eb-9102-e1dc3ddf0201.png)

Here on the image, the template is in HTML and the same template in pug.

The `ProgressBar` tag in the HTML template is ctrl-clickable and it is highlighted with green text color.
By ctrl-clicking on it I can open the file, in which the ProgressBar component is defined.

The same tag in the pug template is not ctrl-clickable and has a blue color.

**Comment by yoyo930021** [comment]
Our support for pug is basic.
The PR is welcome.

**Comment by Wxh16144** [comment]
[Vue Peek](https://github.com/fuzinato/vscode-vue-peek) should suit you perfectly, and meet your needs.

**Comment by Shifu462** [comment]
Hello @yoyo930021, I've created a PR implementing this feature.
