### ISSUE TITLE
auto suggestion become slowly when typing after installing vetur

### ISSUE THREAD

**Issue by derekzuo-github** [vuejs/vetur#249]
- Platform: macOS
- Vetur version: 0.7.0 | 2017-06-01
- VSCode version: 版本 1.13.1 (1.13.1)

Hi,

Thanks, it's a great tool, but I have come into some problems here: 

DESC:
auto suggestion become slowly when typing after installing vetur,
it takes at least 20 seconds to display.

any suggestions?

<img width="543" alt="2017-06-22 10 48 04" src="https://user-images.githubusercontent.com/10721564/27415256-a0bfbe68-5738-11e7-9ce4-aa5733231a85.png">

**Comment by HerringtonDarkholme** [comment]
Please consider providing an example repo for this issue.

Currently I cannot see this problem even in a medium app like https://github.com/Moerj/GOPIGGY

**Comment by HerringtonDarkholme** [comment]
Close due to inactivity.
