### ISSUE TITLE
How can i close the template type error tips on the Vue 2.x

### ISSUE THREAD

**Issue by 1ncounter** [vuejs/vetur#2492]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: macOS
- Vetur version: 0.30.2
- VS Code version:  1.51.1

## Problem

![image](https://user-images.githubusercontent.com/19562558/99751261-d191bd00-2b1c-11eb-9f6e-21bb354b728a.png)

**Comment by johnsoncodehk** [comment]
This error is come from [Volar](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar), you can disable Volar or install `@vue/runtime-dom` to remove this error. See: https://github.com/johnsoncodehk/volar#work-with-vue-2
