### ISSUE TITLE
Tooltip won't display type information, instead shows "ts" in vscode insider

### ISSUE THREAD

**Issue by vainamov** [vuejs/vetur#2497]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Win
- Vetur version: 0.30.3
- VS Code version: 1.52.0-insider (system setup)
  Commit: 0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d
  Date: 2020-11-26T07:36:22.965Z
  Electron: 11.0.2
  Chrome: 87.0.4280.63
  Node.js: 12.18.3
  V8: 8.7.220.24-electron.0
  OS: Windows_NT x64 10.0.19041

- VS Code stable version: Version: 1.51.1 (user setup)
  Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
  Date: 2020-11-10T23:34:32.027Z
  Electron: 9.3.3
  Chrome: 83.0.4103.122
  Node.js: 12.14.1
  V8: 8.3.110.13-electron.0
  OS: Windows_NT x64 10.0.19041

## Problem

In the latest version of VS Code Insiders Vetur can't show type information in TypeScript Vue projects but instead just shows "ts". I've restarted the TypeScript Language Server and the VLS several times, tried updating both VS Code and Vetur and also removed and reinstalled Vetur completely, without any difference. The problem isn't bound to a specific project, it happened in every file I tried. I can open the same project and file in the stable version of VS Code and it will work fine as expected (see screenshots below).

#### Expected behaviour working as of VS Code 1.51.1
![grafik](https://user-images.githubusercontent.com/11841072/100353703-36528900-2fef-11eb-8d4d-1c54ac420372.png)

```
[INFO ] Loaded bundled typescript@4.0.5.
[INFO ] Loaded bundled prettier.
[INFO ] Loaded bundled @starptech/prettyhtml.
[INFO ] Loaded bundled prettier-eslint.
[INFO ] Loaded bundled prettier-tslint.
[INFO ] Loaded bundled stylus-supremacy.
[INFO ] Loaded bundled @prettier/plugin-pug.
Vetur initialized
```

#### Actual behaviour as of VS Code 1.52.0-insiders
![grafik](https://user-images.githubusercontent.com/11841072/100353745-48342c00-2fef-11eb-9e01-02d811414b04.png)

```
[1126/135948.678:ERROR:registration_protocol_win.cc(102)] CreateFile: Das System kann die angegebene Datei nicht finden. (0x2)
[INFO ] Loaded bundled typescript@4.1.2.
[INFO ] Loaded bundled prettier.
[INFO ] Loaded bundled @starptech/prettyhtml.
[INFO ] Loaded bundled prettier-eslint.
[INFO ] Loaded bundled prettier-tslint.
[INFO ] Loaded bundled stylus-supremacy.
[INFO ] Loaded bundled @prettier/plugin-pug.
Vetur initialized
```

## Reproducible Case

1. Create a Vue 2 project with vue-cli and enable TypeScript support.
2. Open the project in VS Code insiders.
3. Paste the following code in any component:
```ts
<script lang="ts">
    import { Component, Vue } from "vue-property-decorator";

    @Component({ })
    export default class TestView extends Vue {
        field: string;
    }
</script>
```
4. Hover over `field`.

**Comment by yoyo930021** [comment]
I believe it's a VSCode problem.

**Comment by kaskar2008** [comment]
@yoyo930021 There is a big chance those updates will be delivered to VSCode stable as well, so I think it is better for Vetur to be prepared :)

**Comment by yoyo930021** [comment]
I don't find any related change in vscode log.
I need more information and time for the survey.

**Comment by rs3d** [comment]
Same issue here with vue-files:
![image](https://user-images.githubusercontent.com/1399149/100736427-06cac480-33d3-11eb-8e3f-2a44469ade71.png)

TS-Files still work.

VS-Code-Version:
```
Version: 1.52.0-insider (user setup)
Commit: bf21395291146c014220eb70b54fdfc0a15956b5
Date: 2020-12-01T09:19:32.000Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by rs3d** [comment]
@vainamov It looks like the most recent insiders version is working again:
![image](https://user-images.githubusercontent.com/1399149/100999314-e9296680-355c-11eb-81bd-b104d409a411.png)

Tested with 
```
Version: 1.52.0-insider (user setup)
Commit: 92192baf760315ac47fb2caaf3ce6d0778962352
Date: 2020-12-03T05:43:59.635Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by vainamov** [comment]
@rs3d Can confirm!

**Comment by bangjelkoski** [comment]
@rs3d thanks for this, I was struggling to make it work. Upgrading VSCode worked just fine!
