### ISSUE TITLE
Is it possible for more powerful typing when deconstructing a composition API return value.

### ISSUE THREAD

**Issue by ShenQingchuan** [vuejs/vetur#2498]
- [ ☑️ ] I have searched through existing issues

## Feature Request

it will look like this:
```html
<template>
    <div class="my-form" @submit="handleSubmit">
       ...
    </div>
</template>

<script lang="ts">
import { useLoginForm } from '@/composition-api/useLoginForm.ts'
export default {
    setup() {
        // ...
        return {
             ...useLoginForm(),
             // ...
        }
    }
}
</script>
```

```ts
export function useLoginForm() {
     const form = reactive({
         userName: "",
         password: ""
     })

    const handleSubmit = () => { ... }

     // ...

    return {
        form,
        handleSubmit,
        ...
    }
}
```

## Discuss for why
besides `<script setup>`, a better but a little magic way, we'll still use traditional, simply raw TypeScript (or even more like JavaScript) syntax in many cases, but under this situation, the return statement would be very long.
I am still wondering a BEST PRACTICE for that kind of syntax.

But we can move our logics into several composition API (`useXXX` functions), in separated files. I believe Vue 3.0 is recommending this way.
Because in larger projects, programmers don't like a huge SFC with 600+ lines of code, it is difficult to maintain and modify, but a single TypeScript file is fine.

Now when I try the demo above in VS Code, I can't use my `Cmd + click` on the SFC's template to seek for the `handleSubmitForm` function implementation in `useLoginForm.ts`.

**Comment by yoyo930021** [comment]
I can't repro it.
![Nov-30-2020 21-23-33](https://user-images.githubusercontent.com/9126398/100615271-5321f000-3352-11eb-9f00-84aaf45fcba3.gif)

Please provide a repro case.
https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md

**Comment by ShenQingchuan** [comment]
maybe my vetur isn't the latest version?
What's your vetur version ? thanks a lot.
