### ISSUE TITLE
Global virtual methods and properties

### ISSUE THREAD

**Issue by MichaelGitArt** [vuejs/vetur#2502]
## Global virtual methods

How can i describe global virtual methods like $t for i18n? I didn't see insgructions in the documentation. You don't have the feature or I can't find solution?

I use only JsDoc and simple JS. Without typescript

![image](https://user-images.githubusercontent.com/34610289/100735862-94f67900-33da-11eb-8f31-ee859fce5b4b.png)

Error: Property '$t' does not exist on type 'CombinedVueInstance<{ openedSubMenuId: any; } & { openSub(id: any): void; closeSub(): void; } & { nav: NavItem[]; value: boolean; } & Vue, object, object, object, Record<never, any>>'

![image](https://user-images.githubusercontent.com/34610289/100514536-38971d80-317e-11eb-8ffe-6a1bb8ab6e05.png)

**Comment by rchl** [comment]
You fix this the same way as with any other package that provides types. You add the package name to the `types` array in `tsconfig.json`.

```js
{
    "compilerOptions": {
        // ...
        "types": [
            "vue-i18n",
        ],
    },
}
```

**Comment by MichaelGitArt** [comment]
> You fix this the same way as with any other package that provides types. You add the package name to the `types` array in `tsconfig.json`.
> 
> ```js
> {
>     "compilerOptions": {
>         // ...
>         "types": [
>             "vue-i18n",
>         ],
>     },
> }
> ```

I forgot to say. I don't use typescript. I setup types by JsDoc
![image](https://user-images.githubusercontent.com/34610289/100735818-80b27c00-33da-11eb-8f2f-0c12e9a1a518.png)

**Comment by rchl** [comment]
The same answer applies.

**Comment by MichaelGitArt** [comment]
> The same answer applies.

It doesn't work.

And I have to add empty ts file to avoid this error in tsconfig
![image](https://user-images.githubusercontent.com/34610289/101245566-7663eb00-3716-11eb-9ed0-30001cfaa258.png)

**Comment by rchl** [comment]
Why would it be empty if I told you to add this to fix it: https://github.com/vuejs/vetur/issues/2502#issuecomment-735225830
?

**Comment by MichaelGitArt** [comment]
> Why would it be empty if I told you to add this to fix it: [#2502 (comment)](https://github.com/vuejs/vetur/issues/2502#issuecomment-735225830)
> ?

You told me add tsconfig. I did it. Read my comment closely. "I have to add empty ts file to avoid this error in tsconfig" - wihout any ts file in the project I have the problem in the tsconfig

**Comment by rchl** [comment]
Well, you should also have the usual boilerplate. Not only the extra part that I've written before. For example something like:

```js
{
    "compilerOptions": {
        "baseUrl": ".",
        "target": "esnext",
        "module": "esnext",
        "moduleResolution": "node",
        "esModuleInterop": true,
        "allowJs": true,
        "checkJs": true,
        "allowSyntheticDefaultImports": true,
        "lib": ["dom", "esnext"],
        "noEmit": true,
        "resolveJsonModule": true,
        "strict": true,
        "types": [
            "vue-i18n",
        ],
    },
}
```

And if you have further problems then create a repro as we can't be guessing your problem from vague comments forever.

**Comment by MichaelGitArt** [comment]
> Well, you should also have the usual boilerplate. Not only the extra part that I've written before. For example something like:
> 
> ```js
> {
>     "compilerOptions": {
>         "baseUrl": ".",
>         "target": "esnext",
>         "module": "esnext",
>         "moduleResolution": "node",
>         "esModuleInterop": true,
>         "allowJs": true,
>         "checkJs": true,
>         "allowSyntheticDefaultImports": true,
>         "lib": ["dom", "esnext"],
>         "noEmit": true,
>         "resolveJsonModule": true,
>         "strict": true,
>         "types": [
>             "vue-i18n",
>         ],
>     },
> }
> ```
> 
> And if you have further problems then create a repro as we can't be guessing your problem from vague comments forever.

Thank you! It's my fault. I use nuxt and I need add this types
```js
{
  "compilerOptions": {
    "types": ["@nuxt/types", "nuxt-i18n"]
  }
}
```

**Comment by rchl** [comment]
Yes. And it's explained in the docs also: https://i18n.nuxtjs.org/setup#typescript :)

(`nuxt-i18n` maintainer here ;))
