### ISSUE TITLE
how can i resolve this problem 

### ISSUE THREAD

**Issue by QPvicus** [vuejs/vetur#2503]
## Info

- Platform: 
- Vetur version:
- VS Code version:

## Problem

![11](https://user-images.githubusercontent.com/57519939/100528834-03410d00-321c-11eb-9100-d5037129b9ed.png)

**Comment by yoyo930021** [comment]
https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#property-xxx-does-not-exist-on-type-combinedvueinstance
