### ISSUE TITLE
Vetur breaks long v-if="" statements

### ISSUE THREAD

**Issue by telion2** [vuejs/vetur#2506]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: 
- Vetur version:v0.30.3
- VS Code version: 1.51.1

## Problem
``` 
<template>
  <div>
    <div>
      <v-row>
        <v-col>   
          <v-form >
           <div
                class="form-input-set"
                v-if="(((someConfig || {}).fieldsToEdit || {})['someName'] || {})[ 'readable' ]"
            >
            ...
           </div>
         </v-form>
       </v-col>
     </v-row>
    </div>
 </div>
</template>
``` 
Becomes: 
``` 
  <div>
    <div>
      <v-row>
        <v-col>   
          <v-form >
            <div
                class="form-input-set"
                v-if="
                   (((someConfig || {}).fieldsToEdit || {})['someName'] || {})[
                        'readable'
                   ]
               "
            >
           </div>
         </v-form>
       </v-col>
     </v-row>
    </div>
 </div>
</template>
``` 
Which can prevent the code from working in certain cases. 
I had the problem a few times now with new code, which I was ok with adapting. 
But now if I touch code that was already written months ago and was fine, this bug happens. 

Any Ideas, besides that it is a long line admittedly.  
## Reproducible Case

Dont know how I gonna reproduce this. Im not well versed with formatters in vs-studio.

**Comment by yoyo930021** [comment]
You can try to toggle formatter in template.

If you're not satisfied with the result of the format, you can go to the formatter project and open an issue.
