### ISSUE TITLE
Argument of type '{ name: string; }' is not assignable to parameter of type 'new (...args: any[]) => any'.

### ISSUE THREAD

**Issue by vahost** [vuejs/vetur#2507]
- [ x] I have searched through existing issues
- [x ] I have read through [docs](https://vuejs.github.io/vetur)
- [x ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows
- Vetur/VLS version: 0.30.0
- VS Code (or other LSP client) version: 1.52.0-insidier

## Problem
I'm getting this error in VS Code:
Argument of type '{ name: string; }' is not assignable to parameter of type 'new (...args: any[]) => any'.
  Type '{ name: string; }' provides no match for the signature 'new (...args: any[]): any'.

It's appearing when I view the code from my Quasar App.vue file, which looks like this:

<template>
  <div id="q-app">
    <router-view />
  </div>
</template>

```
<script>
import Vue from 'vue'
import VuePlyr from 'vue-plyr'
// The second argument is optional and sets the default config values for every player.
Vue.use(VuePlyr, {
  plyr: {
    fullscreen: { enabled: false }
  },
  options: {
    controls: [
      'play',
      'progress',
      'current-time',
      'mute',
      'volume',
      'settings'
    ]
  },
  emit: ['ended']
})
export default {
  name: 'App'
}
</script>

<style>
video::-webkit-media-controls {
  display: none;
}
</style>

```

I just want to understand what the error is telling me about the code, because I don't see anything in my code that matches what the error is reporting.

**Comment by yoyo930021** [comment]
Please provide a repro case.
https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md

**Comment by Nuuou** [comment]
@vahost, I also had this issue when I had the `vetur.experimental.templateInterpolationService` configuration set to `true`.
Disabling this (which is the default) fixed this issue for me.

Hope that helps!

**Comment by yoyo930021** [comment]
Your issue is closed because you did not provide a repro case.
Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.
