### ISSUE TITLE
javascript formatting issue

### ISSUE THREAD

**Issue by jasonbronson** [vuejs/vetur#2508]
- Platform: Macos
- Vetur version: 0.30.3
- VS Code version: 1.51.1

## Problem

On save of a vue file it's doing some weird formatting on the files. See here https://gyazo.com/b0ad16d34e7fdfd7d7325b61dd6682e1

Rolling back to previous version works

**Comment by koflist** [comment]
I had the same problem

**Comment by yoyo930021** [comment]
Please provide provide a repro case.
Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.

and what is your setting?

**Comment by yoyo930021** [comment]
Your issue is closed because you did not provide a repro case.
Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.
