### ISSUE TITLE
Global Filter argument - Property x does not exist on type ComponentX

### ISSUE THREAD

**Issue by pasteusernamehere** [vuejs/vetur#2509]
## Info

- Platform: Windows
- Vetur version: v0.30.3
- VS Code version: 1.51.1

## Problem

Property 'precisio' does not exist on type 'ComponentX'. Did you mean 'precision'?

## Reproducible Case

I apologize in advance if this is already a known issue but I cannot find anything on it. 

I have a filter that is globally registered:

`
function numberFilter(value: number, precision?: number) {...}
`

From within my component I reference the filter and pass the appropriate argument.

`
<span class="profileValue" v-else-if="isNumber(value)">{{
        value | numberFilter(precision)
}}</span>
`

The argument is defined like so:

`
get precision(): number | undefined {
    return this.rowInfo.precision ?? 2;
}
`

The code works as expected but Vetur throws a warning:
Property 'precisio' does not exist on type 'TheStandardCardColumn'. Did you mean 'precision'?

This is not a show stopper issue by any stretch of the imagination. I am more curious if I am doing something wrong to cause this. :-)

Cheers

**Comment by yoyo930021** [comment]
Please provide a repro case.
https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md

**Comment by pasteusernamehere** [comment]
I really wish I could create a repro case.  I have been trying all morning with no luck. I have discovered that the warning is only produced when "Experimental: Template Interpolation Service" is enabled.  Furthermore the warning is not produced if the text is on a single line. Only after prettier kicks in does the warning get emitted.

This code emits no warning:
```
      <span class="profileValue" v-else-if="isNumber(value)">{{ value | numberFilter(precision) }}</span>
```

This code does:
```
      <span class="profileValue" v-else-if="isNumber(value)">{{
        value | numberFilter(precision)
      }}</span>
```

Please let me know if any further information can help reveal the underlying problem.

**Comment by yoyo930021** [comment]
> I really wish I could create a repro case. I have been trying all morning with no luck. I have discovered that the warning is only produced when "Experimental: Template Interpolation Service" is enabled. Furthermore the warning is not produced if the text is on a single line. Only after prettier kicks in does the warning get emitted.
> 
> This code emits no warning:
> 
> ```
>       <span class="profileValue" v-else-if="isNumber(value)">{{ value | numberFilter(precision) }}</span>
> ```
> 
> This code does:
> 
> ```
>       <span class="profileValue" v-else-if="isNumber(value)">{{
>         value | numberFilter(precision)
>       }}</span>
> ```
> 
> Please let me know if any further information can help reveal the underlying problem.

You can add repro code in a project, and give project link in this issue.
This will give us a way to debug.

If you want to help us, you can try to use `Vetur: Show corresponding virtual file and sourcemap` command.

**Comment by pasteusernamehere** [comment]
Sorry I cannot publish the repo as it is private :-(

Below is the output from `Vetur: Show corresponding virtual file and sourcemap`.

```
====================
Virtual content of c:\Branches\Prism\src\components\TheStandardCardField.vue.template
Hover, semantic diagnostics, jump to definition and find references are run on this file.
====================

import __vlsComponent from "./TheStandardCardField.vue";
import { __vlsRenderHelper, __vlsComponentHelper, __vlsIterationHelper, __vlsComponentData } from "vue-editor-bridge";
__vlsRenderHelper(__vlsComponent, function () { this.rowInfo ? __vlsComponentHelper(this, "v-col", { props: {}, on: {}, directives: [] }, [this.rowInfo.cardColumnFormat === undefined || this.rowInfo.cardColumnFormat === this.cardColumnFormat.Text || this.rowInfo.cardColumnFormat === this.cardColumnFormat.TextArea ? __vlsComponentHelper(this, "div", { props: {}, on: {}, directives: [] }, [__vlsComponentHelper(this, "label", { props: {}, on: {}, directives: [] }, [this.isBoolean(this.value) ? this.nbsp : `${this.label}:`]), this.isBoolean(this.value) ? __vlsComponentHelper(this, "span", { props: {}, on: {}, directives: [] }, [__vlsComponentHelper(this, "v-icon", { props: { "color": "black" }, on: {}, directives: [] }, ["$check"]), this.label]) : this.isNumber(this.value) ? __vlsComponentHelper(this, "span", { props: {}, on: {}, directives: [] }, [[[(this.precisio)]] || this.value]) : this.isIdentity(this.value) ? __vlsComponentHelper(this, "span", { props: {}, on: {}, directives: [] }, [this.value.name]) : this.isDate(this.value) ? __vlsComponentHelper(this, "span", { props: {}, on: {}, directives: [] }, [[[]] || this.value]) : true ? __vlsComponentHelper(this, "span", { props: {}, on: {}, directives: [] }, [this.value]) : true]) : true]) : true; });


====================
SourceMap
from: c:\Branches\Prism\src\components\TheStandardCardField.vue
to  : c:\Branches\Prism\src\components\TheStandardCardField.vue.template
[VueFileStart, VueFileEnd, VueFileText] => [TSVirtualFileStart, TSVirtualFileEnd, TSVirtualFileText]
====================

[27, 34, rowInfo] => [226, 238, this.rowInfo]
[15, 20, v-col] => [279, 284, props]
[70, 242, rowInfo.cardColumnFormat === undefined ||
          rowInfo.cardColumnFormat === cardColumnFormat.Text ||
          rowInfo.cardColumnFormat === cardColumnFormat.TextArea] => [317, 492, this.rowInfo.cardColumnFormat === undefined || this.rowInfo.cardColumnFormat === this.cardColumnFormat.Text || this.rowInfo.cardColumnFormat === this.cardColumnFormat.TextArea]
[43, 46, div] => [531, 536, props]
[267, 272, label] => [607, 612, props]
[304, 341, isBoolean(value) ? nbsp : `${label}:`] => [645, 702, this.isBoolean(this.value) ? this.nbsp : `${this.label}:`]
[400, 416, isBoolean(value)] => [706, 732, this.isBoolean(this.value)]
[368, 372, span] => [772, 777, props]
[429, 435, v-icon] => [849, 854, props]
[482, 487, label] => [917, 927, this.label]
[551, 566, isNumber(value)] => [932, 957, this.isNumber(this.value)]
[514, 518, span] => [997, 1002, props]
[600, 610, (precision] => [1037, 1052, (this.precisio)]
[580, 585, value] => [1058, 1068, this.value]
[674, 691, isIdentity(value)] => [1073, 1100, this.isIdentity(this.value)]
[637, 641, span] => [1140, 1145, props]
[705, 715, value.name] => [1178, 1193, this.value.name]
[778, 791, isDate(value)] => [1198, 1221, this.isDate(this.value)]
[741, 745, span] => [1261, 1266, props]
[805, 810, value] => [1307, 1317, this.value]
[854, 858, span] => [1366, 1371, props]
[890, 895, value] => [1404, 1414, this.value]


```

**Comment by pasteusernamehere** [comment]
I have refactored my component and the error has gone away. If I run into this again I will see if I can get a repro for you.
