### ISSUE TITLE
Ctrl+left Buttom (Go to Definition)

### ISSUE THREAD

**Issue by zengchulin** [vuejs/vetur#2521]
![image](https://user-images.githubusercontent.com/56253585/101238246-ddcf6a00-3719-11eb-9480-00c03e25f609.png)

It is recommended to add Ctrl + left click on the component label and path to jump to the definition

**Comment by yoyo930021** [comment]
Please provide a repro case.
Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md

**Comment by zengchulin** [comment]
The .vue file cannot jump to the component definition by ctrl + left button or f12 click on the component label

**Comment by zengchulin** [comment]
The component label for the VUE file cannot jump to the definition through F12

**Comment by zengchulin** [comment]
Integration of VUe-peek is recommended

**Comment by zengchulin** [comment]
Integration of vue-peek is recommended

**Comment by zengchulin** [comment]
Go to definition" doesn't work in .vue files

**Comment by yoyo930021** [comment]
Vetur support it.
Please provide a repro case.
Otherwise we can do nothing.

**Comment by zengchulin** [comment]
The recommended jump to the definition ignores index.vue or.vue that does not write the incoming path

**Comment by yoyo930021** [comment]
Oh, please use `.vue` file extensions.
https://github.com/vuejs/vetur/issues/423#issuecomment-340235722

**Comment by zengchulin** [comment]
WebStorm omits the file extensions by default (new project with Vue CLI). I can't find an IDE option to enforce extensions for .vue files and omit it for .js files. There is option to require to always add an extension
So to have code completion for all developers in my project I have to add .js extensions everywhere? Is that Vetur way of solving the problem for projects that use different editors?
I've tried to switch from WebStorm to VSCode (4 times by now) and these are the kind of issues that always bring me back to WebStorm.

**Comment by yoyo930021** [comment]
> WebStorm omits the file extensions by default (new project with Vue CLI). I can't find an IDE option to enforce extensions for .vue files and omit it for .js files. There is option to require to always add an extension
> So to have code completion for all developers in my project I have to add .js extensions everywhere? Is that Vetur way of solving the problem for projects that use different editors?
> I've tried to switch from WebStorm to VSCode (4 times by now) and these are the kind of issues that always bring me back to WebStorm.

https://github.com/vitejs/vite/issues/178#issuecomment-630138450
https://github.com/vuejs/vue-cli/issues/6064
https://github.com/vuejs/vue-cli/issues/5307

Vue CLI will drop this support in v5.

**Comment by yoyo930021** [comment]
> WebStorm omits the file extensions by default (new project with Vue CLI). I can't find an IDE option to enforce extensions for .vue files and omit it for .js files. There is option to require to always add an extension
> So to have code completion for all developers in my project I have to add .js extensions everywhere? Is that Vetur way of solving the problem for projects that use different editors?
> I've tried to switch from WebStorm to VSCode (4 times by now) and these are the kind of issues that always bring me back to WebStorm.

You can open issues what missing feature or bug back to WebStorm.
Take time to process slowly, Development time is limited. We can only improve slowly.
