### ISSUE TITLE
SCSS Autocompletion broken

### ISSUE THREAD

**Issue by sglancer** [vuejs/vetur#2522]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Windows 10
- Vetur version: 0.30.3
- VS Code version: 1.51.1

## Problem
Autocompletion inside a **style** tag is broken in Vetur version 0.30.3, as shown in the following screenshot.
![image](https://user-images.githubusercontent.com/990356/101236985-19225800-368a-11eb-812f-3d81d2c0d86b.png)

Pressing tab obviously autocompletes to "marginright: ;", instead of "margin-right". This problem occurs with any CSS property: first option would be exactly what you type.
Reinstalling Vetur/VSC doesn't work. Rolling back to a previous Vetur version (0.30.2) solves this problem.

## Reproducible Case
- Open a .vue file
- In the **<style>** tag, try to autocomplete any CSS property.

**Comment by XiongAmao** [comment]
I have the same problem.  v_0.30.2 does not have this problem.
Compare v_0.30.3 and v_0.30.2,  it seems that the `vscode-emmet-helper` (2.0.9 -> 2.1.2) update is causing the problem.
https://github.com/vuejs/vetur/compare/v0.30.2...v0.30.3
