### ISSUE TITLE
"Extension 'Vetur' cannot format" when Template interpolation service is enabled

### ISSUE THREAD

**Issue by Yakimych** [vuejs/vetur#2532]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: macOS
- Vetur version: 0.31.0
- VS Code version: 1.51.1

## Problem

Similarly to https://github.com/vuejs/vetur/issues/2009, formatting does not work, but kicks in if I disable and re-enable "Template interpolation service". It stops working again after restarting VSCode though, so I currently need to toggle the "Template interpolation service" off and on after every VSCode restart.

## Reproducible Case
- Create a new Vue app, e.g. via the CLI (doesn't seem to matter how it's created)
- Enable the "Template interpolation service" in Vetur settings
- Restart VSCode
- Open a vue file and call "Format document"

Actual: "Extension 'Vetur' cannot format ..." appears in the bottom panel. Note that no errors are logged in "Vue Language Server" output.
Expected: The document is formatted

### Workaround
- Go to Vetur settings
- Toggle the "Template interpolation service" off and on again
- Formatting works as expected until next VSCode restart

**Comment by Vout** [comment]
I'm experiencing the exact same issue since today.

**Comment by kody-abe** [comment]
Same issue today

**Comment by Vout** [comment]
Beside above i'm experiencing some other issues also, for example this piece of code, 

```<h1>{{ product.title }}</h1>```

It underlines the `product` and gives the following error,

```Property 'product' does not exist on type 'CombinedVueInstance<Record<never, any> & Vue, object, object, object, Record<never, any>>'.Vetur(2339)```

NuxtJS doesn't throw an error, everything is working fine so i'm not sure why Vetur thinks it's a problem since today.

**Comment by yoyo930021** [comment]
> Beside above i'm experiencing some other issues also, for example this piece of code,
> 
> `<h1>{{ product.title }}</h1>`
> 
> It underlines the `product` and gives the following error,
> 
> `Property 'product' does not exist on type 'CombinedVueInstance<Record<never, any> & Vue, object, object, object, Record<never, any>>'.Vetur(2339)`
> 
> NuxtJS doesn't throw an error, everything is working fine so i'm not sure why Vetur thinks it's a problem since today.

https://vuejs.github.io/vetur/guide/FAQ.html#property-xxx-does-not-exist-on-type-combinedvueinstance

**Comment by yoyo930021** [comment]
Fixed in 7af21d7

**Comment by fardolieri** [comment]
Is there a rough estimation on when this fix is released in the vscode marketplace?
In the meantime, I installed version [0.30.3](https://github.com/vuejs/vetur/releases) manually. That fixes the format problem for me.

**Comment by yoyo930021** [comment]
> Is there a rough estimation on when this fix is released in the vscode marketplace?
> In the meantime, I installed version [0.30.3](https://github.com/vuejs/vetur/releases) manually. That fixes the format problem for me.

Release in v0.31.1
