### ISSUE TITLE
[Typescript] Not getting proper type check/IntelliSense

### ISSUE THREAD

**Issue by darthmeme** [vuejs/vetur#2534]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform:  macOS
- Vetur version: 0.31.0
- VS Code version: 1.51.1

## Problem

When importing a method from a `.ts` file that returns `null` or `undefined` into a Vue component, it seems to lose the `null` or `undefined` type when invoked.

When hovering over the import:
![image](https://user-images.githubusercontent.com/42481527/101567389-d31c1a00-3a24-11eb-9003-d76839a78cd8.png)
It correctly shows that the method returns a `string` or `null`

When invoking the function and hovering over it:
![image](https://user-images.githubusercontent.com/42481527/101567414-df07dc00-3a24-11eb-9b04-735deb4dbcf7.png)
It only shows that the method returns a `string`

Also, this might be related to [this issue](https://github.com/vuejs/vetur/issues/1820), but I don't have any type checks against null. This line of code should complain that I'm assigning `null` to a string, but it doesn't.
![image](https://user-images.githubusercontent.com/42481527/101567550-1f675a00-3a25-11eb-940c-9fadebb9ab7c.png)

## Reproducible Case
https://github.com/darthmeme/veturpack-repro

**Comment by yoyo930021** [comment]
Please use `compilerOptions.strict: true` in your `tsconfig.json`.

**Comment by darthmeme** [comment]
@yoyo930021 hey, thanks for the quick reply! That totally worked for the repo I pushed to show the issue!

On other projects I work on, this was already set in `tsconfig.json` and still didn't work. But there seems to have been an update pushed yesterday and Vetur threw some issues with not finding certain files (`tsconfig` and `package.json`) - was able to fix those from the [FAQ link](https://vuejs.github.io/vetur/guide/FAQ.html#vetur-find-xxx-but-they-aren-t-in-the-project-root) and now everything works flawlessly!

**Comment by nuochong** [comment]
me to
