### ISSUE TITLE
can't format ".vue" file in version 0.31

### ISSUE THREAD

**Issue by ZhengXiaowei** [vuejs/vetur#2535]
- [x ] I have searched through existing issues
- [x ] I have read through [docs](https://vuejs.github.io/vetur)
- [ x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x ] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: macOS
- Vetur version: 0.31
- VS Code version: 1.51.1

**Comment by yoyo930021** [comment]
https://github.com/vuejs/vetur/issues/2531#issuecomment-741492935

**Comment by wilsunson** [comment]
![image](https://user-images.githubusercontent.com/40852123/101603005-e1286580-3a39-11eb-8a07-61544322f9d6.png)
roll back to v0.30.3 is ok

**Comment by ZhengXiaowei** [comment]
> ![image](https://user-images.githubusercontent.com/40852123/101603005-e1286580-3a39-11eb-8a07-61544322f9d6.png)
> roll back to v0.30.3 is ok

yes, rolled

**Comment by tony-mo** [comment]
thx!

**Comment by vipsunwei** [comment]
切换到30  ，好使了。

**Comment by yoyo930021** [comment]
Fixed in v0.31.1
