### ISSUE TITLE
Fear upgrading

### ISSUE THREAD

**Issue by csicky** [vuejs/vetur#2539]
Whenever I dare clicking the update button for this extension, or Prettier or Eslint, something for sure will break. So good the vsix file is there.
I didn't want a jsconfig.json file, don't need it, but I added it just for Vetur. Still formatting is not working anymore. I get error in status bar Extension Vetur cannot format... file name. Was working just fine in previous version.

I just wish when publishing an update you would deal with backward compatibility and migrate settings automatically.

**Comment by sdzbzjh** [comment]
I didn't want a jsconfig.json file,too

**Comment by yoyo930021** [comment]
The format problem is fixed.
I will release new version tonight.

The `jsconfig.json` is only a warning.
If you don't need to talk vetur any speical option, you can ignore it.
You can use vetur.ignoreProjectWarning: false in vscode setting to close this warning.

**Comment by sdzbzjh** [comment]
> The format problem is fixed.
> I will release new version tonight.
> 
> The `jsconfig.json` is only a warning.
> If you don't need to talk vetur any speical option, you can ignore it.
> You can use vetur.ignoreProjectWarning: false in vscode setting to close this warning.

`vetur.ignoreProjectWarning: true`

**Comment by yoyo930021** [comment]
All instructions are here.
https://vuejs.github.io/vetur/guide/FAQ.html#vetur-can-t-find-tsconfig-json-jsconfig-json-in-xxxx-xxxxxx

**Comment by csicky** [comment]
thank you

**Comment by yoyo930021** [comment]
I have no intention of changing people's habits.
But we get too many questions about the config file.
These warnings are intended to alert users to possible problems.

**Comment by bkarlson** [comment]
so much this... Everything works fine, they suddenly breaks (usually it's because Vetur was silently updated). Long  chain of package upgrades till some meaningul googleable error message appears and then it's another round of messing with configs. An hour later equilibrium restored and everything works **just like before**. Until next Vetur update I suppose..
