### ISSUE TITLE
Template type checking appears in the wrong place.

### ISSUE THREAD

**Issue by ForBurning** [vuejs/vetur#2540]
![QQ截图20201209182234](https://user-images.githubusercontent.com/28643492/101617515-aa5b4b00-3a4b-11eb-900b-11197c59c389.png)

**Comment by yoyo930021** [comment]
Please open new issue with template.

Your issue is closed because you did not provide a repro case.
Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.
