### ISSUE TITLE
After installing the extension, load project is always displayed in the status bar

### ISSUE THREAD

**Issue by Uomfan** [vuejs/vetur#2554]
Issue Type: <b>Bug</b>

After installing the extension, load project is always displayed in the status bar

Extension version: 0.31.1
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

> 

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (10.88GB free)|
|Process Argv|--crash-reporter-id 04a8e1df-e442-4b88-bfb4-8ec54bee657a|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by yoyo930021** [comment]
Where is your `vetur.config.js`?
Or what is folder path opened in VSCode?

**Comment by willhoyle** [comment]
I'm getting the same issue. The project loads forever. How can I debug this? I tried uninstalling/reinstalling but no luck.

**Comment by yoyo930021** [comment]
> I'm getting the same issue. The project loads forever. How can I debug this? I tried uninstalling/reinstalling but no luck.


Try to use `Vetur: show doctor info` command in vscode and post message in this issue.

**Comment by vostokwork** [comment]
Same problem.

Infinite loading project from C:\, but my project not in root of C disk.

**Comment by yoyo930021** [comment]
> Same problem.
> 
> Infinite loading project from C:, but my project not in root of C disk.
> 
> ![image](https://user-images.githubusercontent.com/37534401/101885966-e7d6ea00-3bab-11eb-9787-49b2cb458018.png)
> ![image](https://user-images.githubusercontent.com/37534401/101886263-4c924480-3bac-11eb-9841-bc1120117ca8.png)


If you have `vetur.config.js`?

**Comment by vostokwork** [comment]
@yoyo930021 

Output channel

![image](https://user-images.githubusercontent.com/37534401/101886676-e1953d80-3bac-11eb-8655-9d07fd396316.png)

Vetur: show doctor shows nothing.

vetur.config.js is default, I have not changed it

**Comment by yoyo930021** [comment]
> @yoyo930021
> 
> Output channel
> 
> ![image](https://user-images.githubusercontent.com/37534401/101886676-e1953d80-3bac-11eb-8655-9d07fd396316.png)
> 
> Vetur: show doctor shows nothing.
> 
> vetur.config.js is default, I have not changed it

What is content in `vetur.config.js`?

**Comment by vostokwork** [comment]
@yoyo930021 

> And what is folder path for opened ?

`C:\Users\wokalek\work\projects\volochanka\`
`C:\Users\wokalek\work\projects\optimize-village-images\`

But I remove `optimize-village-images` and got this errors, which were not there before

![image](https://user-images.githubusercontent.com/37534401/101887940-9714c080-3bae-11eb-9041-b465ab405e0d.png)

**Comment by vostokwork** [comment]
@yoyo930021 

I do not have any vetur.config.js

**Comment by yoyo930021** [comment]
> @yoyo930021
> 
> > And what is folder path for opened ?
> 
> `C:\Users\wokalek\work\projects\volochanka\`
> `C:\Users\wokalek\work\projects\optimize-village-images\`
> 
> But I remove `optimize-village-images` and got this errors, which were not there before
> 
> ![image](https://user-images.githubusercontent.com/37534401/101887940-9714c080-3bae-11eb-9041-b465ab405e0d.png)
Is this warning correct?

I think we have some bug in windows.

**Comment by vostokwork** [comment]
@yoyo930021 yes, I think, nuxt.js project (with node_modules) placed in `volochanka/nuxt`, not in root of project folder. 

![image](https://user-images.githubusercontent.com/37534401/101891204-c5949a80-3bb2-11eb-8ac1-55d171515079.png)

**Comment by yoyo930021** [comment]
> @yoyo930021 yes, I think, nuxt.js project (with node_modules) placed in `volochanka/nuxt`, not in root of project folder.
> 
> ![image](https://user-images.githubusercontent.com/37534401/101891204-c5949a80-3bb2-11eb-8ac1-55d171515079.png)
> 
> But I do not want to see this errors...

In your case, please keep `package.json` in opened project root.
Or add `vetur.config.js` in this project.
```javascript
module.exports = {
  projects: ['./nuxt']
}
```

**Comment by vostokwork** [comment]
@yoyo930021 thanks a lot!

Apparently this is not a problem from this issue, sorry

**Comment by yoyo930021** [comment]
> @yoyo930021 thanks a lot!
> 
> Apparently this is not a problem from this issue, sorry

No problem.
Our documentation and warnings need to be improved. 😅
I also find some bug about this case. Thanks your help.

In fact, this kind of project was also problematic before.
It's just that Vetur doesn't give any errors or warnings.

**Comment by yoyo930021** [comment]
Fixed in 1f444d3

**Comment by willhoyle** [comment]
Ok I've narrowed it down a bit. 
rolling back to v0.30.3 works so it must be a changed introduced in v0.31.0. 

By the way, I've never had a vetur.config.js file and it has always worked, not sure if that is undefined behaviour to omit this file.

v0.31.0 (and v0.31.1) outputs an error:

````Error: EACCES: permission denied, scandir '/home/will/projects/dashboard/data/postgres'
    at Object.readdirSync (fs.js:854:3)
    at Object.fs.readdirSync (electron/js2c/asar.js:621:39)
    at readdirWithFileTypes (/home/will/.vscode/extensions/octref.vetur-0.31.1/server/dist/vls.js:34:39846)
    at Object.read (/home/will/.vscode/extensions/octref.vetur-0.31.1/server/dist/vls.js:34:39776)
    at JL.scandirSync [as _scandir] (/home/will/.vscode/extensions/octref.vetur-0.31.1/server/dist/vls.js:34:41945)
    at JL._handleDirectory (/home/will/.vscode/extensions/octref.vetur-0.31.1/server/dist/vls.js:34:47863)
    at JL._handleQueue (/home/will/.vscode/extensions/octref.vetur-0.31.1/server/dist/vls.js:34:47789)
    at JL.read (/home/will/.vscode/extensions/octref.vetur-0.31.1/server/dist/vls.js:34:47645)
    at QL.read (/home/will/.vscode/extensions/octref.vetur-0.31.1/server/dist/vls.js:34:48639)
    at AM.walkSync [as _walkSync] (/home/will/.vscode/extensions/octref.vetur-0.31.1/server/dist/vls.js:34:49920)
````
which makes sense because the folder permissions are as follows:

`drwx------ 19 guest-lhspf4 will 4096 Dec 11 09:41 postgres` (no group read access for will).

Should vetur catch this error and just ignore it? (or log it but continue scanning the directories?). By the way, this folder is in my .gitignore, should vetur ignore folders/files in .gitignore?

Happy to help in any other way, let me know!

**Comment by joaopauloufal** [comment]
> Ok I've narrowed it down a bit.
> rolling back to v0.30.3 works so it must be a changed introduced in v0.31.0.
> 
> By the way, I've never had a vetur.config.js file and it has always worked, not sure if that is undefined behaviour to omit this file.
> 
> v0.31.0 (and v0.31.1) outputs an error:
> 
> ```
> Error: EACCES: permission denied, scandir '/home/will/projects/dashboard/data/postgres'
>     at Object.readdirSync (fs.js:854:3)
>     at Object.fs.readdirSync (electron/js2c/asar.js:621:39)
>     at readdirWithFileTypes (/home/will/.vscode/extensions/octref.vetur-0.31.1/server/dist/vls.js:34:39846)
>     at Object.read (/home/will/.vscode/extensions/octref.vetur-0.31.1/server/dist/vls.js:34:39776)
>     at JL.scandirSync [as _scandir] (/home/will/.vscode/extensions/octref.vetur-0.31.1/server/dist/vls.js:34:41945)
>     at JL._handleDirectory (/home/will/.vscode/extensions/octref.vetur-0.31.1/server/dist/vls.js:34:47863)
>     at JL._handleQueue (/home/will/.vscode/extensions/octref.vetur-0.31.1/server/dist/vls.js:34:47789)
>     at JL.read (/home/will/.vscode/extensions/octref.vetur-0.31.1/server/dist/vls.js:34:47645)
>     at QL.read (/home/will/.vscode/extensions/octref.vetur-0.31.1/server/dist/vls.js:34:48639)
>     at AM.walkSync [as _walkSync] (/home/will/.vscode/extensions/octref.vetur-0.31.1/server/dist/vls.js:34:49920)
> ```
> 
> which makes sense because the folder permissions are as follows:
> 
> `drwx------ 19 guest-lhspf4 will 4096 Dec 11 09:41 postgres` (no group read access for will).
> 
> Should vetur catch this error and just ignore it? (or log it but continue scanning the directories?). By the way, this folder is in my .gitignore, should vetur ignore folders/files in .gitignore?
> 
> Happy to help in any other way, let me know!

I also have this same problem. A suggestion for improvement would be that the vetur has some configuration to ignore certain folders.

**Comment by yoyo930021** [comment]
Fix and release in v0.31.2

**Comment by yoyo930021** [comment]
@joaopauloufal @willhoyle 
It could be other problems.
If you still have same error in v0.31.2, you can open a new issue.

**Comment by willhoyle** [comment]
Ok will do. It might be something else because v0.31.2 doesn't fix it. Thanks

**Comment by maisen20** [comment]
hello, unfortunately i also have this problem. for some time now it has been loading the project continuously as soon as i open the first vue file. this takes up quite a bit of my macbook's power and it also gets warmer than it should.

**Comment by yoyo930021** [comment]
Please open a new issue.
Use issue template and provide more information like https://github.com/vuejs/vetur/issues/2554#issuecomment-743245625
