### ISSUE TITLE
Option to make Vetur stop warning me that it can't find jsconfig.json

### ISSUE THREAD

**Issue by mastazi** [vuejs/vetur#2560]
## Feature Request

I would like an option so that Vetur will not warn me that it can't find jsconfig.json. It does that every single time I open one of my Vue projects. I'm not planning to add a jsconfig.json. I'm the only person in the team using VS Code and I don't want to pollute the repo with a file that no one else uses.

**Comment by yoyo930021** [comment]
We have this option 
https://vuejs.github.io/vetur/guide/FAQ.html#vetur-can-t-find-tsconfig-json-jsconfig-json-in-xxxx-xxxxxx
