### ISSUE TITLE
In version 0.31.3, the path completion recommendation becomes slower

### ISSUE THREAD

**Issue by sijianian** [vuejs/vetur#2566]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: 
macOS
- Vetur version:
0.31.3
- VS Code version:
1.52.0
## Problem

In version 0.31.3, the path completion recommendation becomes slower

This is normal in version 0.31.1

In 0.31.3
![Dec-14-2020 10-45-06](https://user-images.githubusercontent.com/17903414/102034663-90c65480-3df9-11eb-96dc-dddb8ba8806e.gif)

In 0.31.1
![Dec-14-2020 10-44-50](https://user-images.githubusercontent.com/17903414/102034672-97ed6280-3df9-11eb-9399-026161b37115.gif)

If more information is needed, I can provide it on my end

**Comment by yoyo930021** [comment]
Please provide more information in this link.
https://github.com/vuejs/vetur/blob/master/.github/PERF_ISSUE.md

Or provide a reproducible case.
https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md
