### ISSUE TITLE
nuxt-property-decorator + typescript 

### ISSUE THREAD

**Issue by Zenthae** [vuejs/vetur#2567]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md) (lol there is no FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform:  Win
- Vetur version: latest 😉 (0.31.3)
- VS Code version: latest 😉  (1.52)

## Problem

there is no auto-completion / IntelliSense for props and data on custom component using `nuxt-property-decorator` and typescript

**Comment by yoyo930021** [comment]
I can't repro it.
![Dec-16-2020 21-57-59](https://user-images.githubusercontent.com/9126398/102357912-d184c000-3fe9-11eb-8cf5-7eaaccf0cf72.gif)

**Comment by yoyo930021** [comment]
Please provide a repro case.
Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md.

**Comment by Zenthae** [comment]
i solved the case, it's because i wasn't importing my components since nuxt is doing it by default, so it probably wasn't able to find the definition. but it's sad since it mean that we cannot take advantage of this functionality.

**Comment by yoyo930021** [comment]
> i solved the case, it's because i wasn't importing my components since nuxt is doing it by default, so it probably wasn't able to find the definition. but it's sad since it mean that we cannot take advantage of this functionality. is it possible to tell `Vetur` to look for components directly in a folder ? and not only specifically imported ones ?

I am not familiar with nuxt.
but I think you need this feature.
https://vuejs.github.io/vetur/guide/global-components.html

**Comment by Zenthae** [comment]
you're my savior ^^
if anyone need it :
```js
module.exports = {
  projects: [
    {
      root: './',
      globalComponents: [
        // Nuxt components folder
        './components/**/*.vue',
      ],
    },
  ],
};
```
in `vetur.config.js` and you need to restart the language server or you editor ^^

**Comment by yoyo930021** [comment]
I think your problem is solved.
I close this issue.

**Comment by 99linesofcode** [comment]
While it may seem that the globalComponents setting solves this issue (it might when you don't nest your components in subdirectories) it doesn't correctly solve the issue here. `@nuxt/components` allows you to dynamically import components from the `components/` directory and any subdirectory there in. As is documented here:

https://nuxtjs.org/docs/directory-structure/components/#nested-directories

I believe this is actually a bug, possibly a very simple one to resolve for anyone familiar with the vetur code base relating to the nuxt external tag loader not being loaded correctly. See my issue for more info #3370

**Comment by SimplyCorey** [comment]
Facing the same issue with the next directories and I have not been able to find a solution.  

Essentially, we have the following folder setup:

```
Ui/
     Button.vue
```

We use @nuxt/components for autoloading (per https://nuxtjs.org/docs/directory-structure/components/#nested-directories )and reference the component in our files as <UiButton>. 

The file that vetur generates when viewing vetur doctor has these lines which does not allow vetur to pick up the UiButton component correctly.

```
{
  "name": "Button",
  "path": "/resources/nuxt/components/block/settings/Button.vue"
},
```

**Comment by jameskid007** [comment]
I've made a plugin to help jump to the corresponding component file. And nested files are supported. The name of the component is “Nuxt 2 goto".  You can go to the vscode store to find it
