### ISSUE TITLE
High CPU usage and crashloop with Typescript 4.x.x

### ISSUE THREAD

**Issue by fdaugs** [vuejs/vetur#2569]
## Info

- Platform: macOS Big Sur 11.0.1
- Vetur version: 0.31.3
- VS Code version: 1.52.0

## Problem

The vueServerMain.js process causes very high cpu and memory usage. The memory consumption rises slowly to about 4.1-4.2GB, then the process seems to crash and starts all over again, leading to an infinite crash loop.

## Reproducible Case

I testet different typescript versions by adding them to my project dependencies and using:
`"vetur.useWorkspaceDependencies": true`

If I use Version 3.9 or lower the memory consumption is just 3.1 GB and there is no high cpu usage. 
But when using 4.0 or higher the problem occurs.

**Comment by yoyo930021** [comment]
Can you provide more information with this link?
https://github.com/vuejs/vetur/blob/master/.github/PERF_ISSUE.md

It would be better if you can provide repro project.

**Comment by fdaugs** [comment]
Profiling is currently not possible with Chrome v87+ (https://bugs.chromium.org/p/chromium/issues/detail?id=1151855). I will look into it, as soon as v88 is released.

**Comment by sapphi-red** [comment]
This occured when I was using TS 4.1.2 and I did not occur when I changed to TS 4.1.3.
This issue may be related? https://github.com/microsoft/TypeScript/issues/41124

**Comment by yoyo930021** [comment]
I think problem solved.
