### ISSUE TITLE
Nuxt js Suggestions not appear

### ISSUE THREAD

**Issue by engmagdy87** [vuejs/vetur#2570]
- [ x] I have searched through existing issues
- [ x] I have read through [docs](https://vuejs.github.io/vetur)
- [ x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [ x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Linux
- Vetur version: 0.31.3
- VS Code version:1.52.0

## Problem

concerning nuxt js, in vue component, press on `CTRL+SPACE` show the menu without any suggestions for nuxt properties like `head` function

I uninstalled `vetur` and reinstall it but still not working

**Comment by yoyo930021** [comment]
I can't repro it.
![Uploading 截圖 2020-12-16 下午10.20.01.png…]()

Please provide a repro case.
https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md

**Comment by engmagdy87** [comment]
@yoyo930021 so if the `nuxt` and the other options related to nuxt appear in the suggestions, so vetur works without any issue?

**Comment by yoyo930021** [comment]
> @yoyo930021 but in the following screenshot (i.e. from a video), the `hid` appears as a suggestion, is this vetur related issue when it does not appear?
> ![Screenshot-20201216163834-499x323](https://user-images.githubusercontent.com/8473421/102362560-3675f100-3fbd-11eb-8fee-78c6cfd9d833.png)
> 

https://typescript.nuxtjs.org/guide/setup#configuration
Please add `tsconfig.json` in your project.
If you don't use TypeScript, add `jsconfig.json`.

**Comment by engmagdy87** [comment]
I already added it with the following config
```js
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "~/*": ["./*"],
      "@/*": ["./*"],
      "~~/*": ["./*"],
      "@@/*": ["./*"]
    },
  },
  "exclude": ["node_modules", ".nuxt", "dist"]
}

```

**Comment by engmagdy87** [comment]
`jsconfig.json` is already created
```js
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "~/*": ["./*"],
      "@/*": ["./*"],
      "~~/*": ["./*"],
      "@@/*": ["./*"]
    }
  },
  "exclude": ["node_modules", ".nuxt", "dist"]
}

```

**Comment by yoyo930021** [comment]
> `jsconfig.json` is already created
> 
> ```js
> {
>   "compilerOptions": {
>     "baseUrl": ".",
>     "paths": {
>       "~/*": ["./*"],
>       "@/*": ["./*"],
>       "~~/*": ["./*"],
>       "@@/*": ["./*"]
>     }
>   },
>   "exclude": ["node_modules", ".nuxt", "dist"]
> }
> ```
Install `@nuxt/types` package.
Add this in `compilerOptions`
```
  "types": [
      "@types/node",
      "@nuxt/types"
    ]
```
