### ISSUE TITLE
Vetur command(s) not found

### ISSUE THREAD

**Issue by franciscolourenco** [vuejs/vetur#2571]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: macOS
- Vetur version: v0.31.3
- VS Code version: 1.52.0
## Problem

Vetur commands are not found. All of them show a similar error
![image](https://user-images.githubusercontent.com/208149/102345455-b8eeb880-3f9d-11eb-91d7-d531458486bf.png)

Panel -> Output -> **Vue Language Server** is not available

## Reproducible Case

N/A

**Comment by yoyo930021** [comment]
Please open a vue file in VSCode.

**Comment by franciscolourenco** [comment]
@yoyo930021 thanks, solved.
