### ISSUE TITLE
Pug full support

### ISSUE THREAD

**Issue by pedro-gilmora** [vuejs/vetur#2572]
- [ x] I have searched through existing issues

## Feature Request

I think it would be a good feature to have same support like HTML support for Intellisense, auto-completion, Emmet, folding, linting and all designed services to make Vue + Pug a nice dev environment

**Comment by yoyo930021** [comment]
https://github.com/vuejs/vetur/issues?q=is%3Aissue+is%3Aopen+pug

We don't have enough time to develop or maintenance pug part.
The PR is welcome. If anyone can help, There will be a lot of improvement.

**Comment by johnsoncodehk** [comment]
I have a plan for `vscode-pug-languageservice` and it may helpful, I will do it after finishing the accumulation works, so it will not happen soon.

**Comment by qnp** [comment]
@yoyo930021 @octref I can work on it.

**Comment by jdheeter** [comment]
I use PUG+Vue everyday and it would be great to have full Pug support in Vetur. Especially the ability to Intellisense component variables in single file components would be a nice productivity boost.

**Comment by johnsoncodehk** [comment]
Done: https://www.npmjs.com/package/vscode-pug-languageservice

**Comment by ionuttibi** [comment]
> Done: https://www.npmjs.com/package/vscode-pug-languageservice

How do i make this work?

**Comment by kissu** [comment]
Hi, do you plan to have the auto-import at some point? 😄

**Comment by pedro-gilmora** [comment]
I jumped to Rider, sorry I'll close this issue

**Comment by kissu** [comment]
@pedro-gilmora what is Rider ?

**Comment by IgorKurkov** [comment]
JetBrains Rider isn't so good solution for Vscode users :) VScode is the most usable editor so have no idea why auto-import in Vue doesn't work in Vscode. PLease who solved this issue, drop here addon or something...

**Comment by yoyo930021** [comment]
Please try to use Volar instead.
https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar

**Comment by IgorKurkov** [comment]
@yoyo930021 thank you, already use it, but auto imports doesn't work unfortunately

**Comment by qnp** [comment]
I switched to Volar and it's perfect. What issue are you facing @IgorKurkov ?
