### ISSUE TITLE
Seemingly arbitrary code suggestions using Emacs + LSP.

### ISSUE THREAD

**Issue by mikejholly** [vuejs/vetur#2574]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Linux
- Vetur version: 0.6.4
- VS Code version: N/A

## Problem

Seemingly arbitrary suggestions using Emacs + LSP.

When I open a `.vue` file using `web-mode` and `lsp-mode` with `vls` support, I see suggestions that don't seem to be accurate or relevant to the actual code. Actual errors seem to be working fine (underlined with correct messages).

The project was generated using the Vue CLI.

Apologies if this is the wrong place to report the issue. Perhaps you can point me in the right direction, if so.

![image](https://user-images.githubusercontent.com/332408/102522980-ccf0f380-404b-11eb-9e0a-ff9e8b6905e8.png)

## Reproducible Case

Note: Veturpack doesn't seem relevant here since the problem is related to Emacs.

1. Check out https://github.com/mikejholly/vetur-issue.
2. Open in Emacs 28. Start web-mode & LSP (latest).
3. Navigate cursor to `<script>` tags.
4. Suggestions should appear.

**Comment by dirodriguezm** [comment]
How did you solve this ?

**Comment by yoyo930021** [comment]
> How did you solve this ?

This line
https://github.com/vuejs/vetur/blob/304e7567f11a709171a0ae987b115e9054907047/server/src/modes/script/javascript.ts#L802
