### ISSUE TITLE
how to avoid to redirect to the shim-vue.d.ts file after clicking the import path of .vue

### ISSUE THREAD

**Issue by HomyeeKing** [vuejs/vetur#2591]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: 
- Vetur version:
- VS Code version:

## Problem

In vue+ts project, we have a shim file to let ts recognize the .vue file, but at the mean time, we are not able to  jump to the exact .vue file after clicking the import path , it always redirect to the vue-shilm.d.ts,  how to avoid it ?

**Comment by yoyo930021** [comment]
Where do you jump?
In the `.ts` file, This is a known issue and requires the help of ts plugin.
In the `.vue` file, When the corresponding file is not found, it will jump to that file.

**Comment by HomyeeKing** [comment]
@yoyo930021  yeah you are right ,`.vue` can find `.vue` correctly,  
but in `tsx` file, it always redirect the `shim-vue.d.ts`,
so  which plugin can avoid it

**Comment by yoyo930021** [comment]
> @yoyo930021 yeah you are right ,`.vue` can find `.vue` correctly,
> but in `tsx` file, it always redirect the `shim-vue.d.ts`,
> so which plugin can avoid it

Follow https://github.com/vuejs/vetur/issues/2016
