### ISSUE TITLE
Experimental Interpolation Service wrong type inference with if-conditions

### ISSUE THREAD

**Issue by ivansieder** [vuejs/vetur#2604]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Ubuntu 20.04.1 LTS
- Vetur version: v0.31.3 locally and unknown on CodeSandbox, but happens on both systems
- VS Code version: 1.52.1 locally and unknown on CodeSandbox, but happens on both systems

## Problem

When checking with v-if for a property, the (experimental) interpolation service complains about the element being possibly null. This also happens when moving the if-condition to a parent wrapper element:
![Screenshot from 2020-12-28 09-24-17](https://user-images.githubusercontent.com/35377072/103201777-07327e80-48f1-11eb-865c-3d06908c0205.png)

![interpolation-service-error](https://user-images.githubusercontent.com/35377072/103201755-f71a9f00-48f0-11eb-8c03-433817899436.png)

## Reproducible Case

- Enable "Vetur > Experimental: Template Interpolation Service"
- Reproduction link (already includes the above settings, therefor not using the below generate URL): https://codesandbox.io/s/proud-cloud-f40x5?file=/src/App.vue
- Wait some time and the errors should pop up on the "element" property inside the `template` tags

**Comment by yoyo930021** [comment]
If I understand correctly, JavaScript is too flexible.
We need to talk more type with `@JSdoc` or TypeScript to get the correct judgment result.

This PR may be the final solution.
https://github.com/vuejs/vetur/pull/1824

**Comment by ivansieder** [comment]
@yoyo930021 out of curiosity: were you able to eventually fix this or do you need any additional information?

**Comment by yoyo930021** [comment]
> @yoyo930021 out of curiosity: were you able to eventually fix this or do you need any additional information?

JavaScript doesn't have enough information to check in the first place.
So we don't do anything, without close check in JS.

**Comment by ivansieder** [comment]
@yoyo930021 but does this actually relate to JS itself? Because if I use for example `{{ element !== null ? element.id : 0 }}`, it interpolates properly. To me it seems more likely to be related to how Vetur infers types, could that be?

**Comment by yoyo930021** [comment]
> @yoyo930021 but does this actually relate to JS itself? Because if I use for example `{{ element !== null ? element.id : 0 }}`, it interpolates properly. To me it seems more likely to be related to how Vetur infers types, could that be?

Template interpolates service is based on typescript template service.

In your codesandbox:
<img width="383" alt="截圖 2021-03-09 下午3 29 06" src="https://user-images.githubusercontent.com/9126398/110433994-31bc6700-80ec-11eb-8f58-8e498350ca5d.png">
