### ISSUE TITLE
How to remove unused warnings for variables that are already used in the template

### ISSUE THREAD

**Issue by zhenzhenChange** [vuejs/vetur#2606]
- [ ] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  Win x64
- Vetur/VLS version: 0.31.3
- VS Code (or other LSP client) version: 1.52.1

## Problem

Except for adding // @ts-nocheck at the top

What else can be done without reporting this warning?

Although I don't use it in the `script`, I do use it in the `template`

![unused](https://ftp.bmp.ovh/imgs/2020/12/789f5452da1a87d0.png)

**Comment by yoyo930021** [comment]
We don't support <script setup> now.
https://github.com/vuejs/vetur/issues/2296#issuecomment-734345448

**Comment by zhenzhenChange** [comment]
Ok，Thanks，Still in development, right?

**Comment by yoyo930021** [comment]
> Ok，Thanks，Still in development, right?

We expect to wait for the RFC to be finalized before developing.

**Comment by zhenzhenChange** [comment]
Okay, okay, good job and happy new year in advance.
