### ISSUE TITLE
Error in v-bind property when props and computed setter are defined

### ISSUE THREAD

**Issue by edwillys** [vuejs/vetur#2610]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Linux
- Vetur version: 0.31.3
- VS Code version: 1.52.1

## Problem

Vetur throws a wrong error message in v-bind property if props and computed setter are present. When I delete either the props or the setter, the error is gone. 

Following is the error message:
_Property 'options' does not exist on type 'CombinedVueInstance<Vue, object, object, object, Record<never, any>>'. Did you mean '$options'?Vetur(2551)_

This is the output of the Vue Language Server (no error here)
```
Vetur initialized
[INFO ] Find node_modules paths in /home/edlub/proj/quasar-culturaltraces - 330ms
[INFO ] Loaded bundled typescript@4.1.2.
[INFO ] Loaded bundled prettier.
[INFO ] Loaded bundled @starptech/prettyhtml.
[INFO ] Loaded bundled prettier-eslint.
[INFO ] Loaded bundled prettier-tslint.
[INFO ] Loaded bundled stylus-supremacy.
[INFO ] Loaded bundled @prettier/plugin-pug.
```

Here is a screenshot:
![image](https://user-images.githubusercontent.com/1780037/103443966-69c6aa00-4c64-11eb-830a-ac1fb85cfa54.png)

## Reproducible Case

Simply create a test.vue file with the following minimal content:
PS: I'm actually using Quasar's ```q-select``` (which accepts _options_ as a prop) but I replaced it with a ```div``` for the sake of simplicity.

```
<template>
  <div :options="options" >
  </div>
</template>

<script>
export default {
  name: "Test",
  data() {
      return {
          options: [],
    }
  },
  props: {
  },
  computed: {
    test: {
      get: function() {
        return 0
      },
      set: function(newValue) {
      }
    }
  },
}
</script>
```

**Comment by vittorio-c** [comment]
Same problem here. Using coc-vetur on nvim. 

As soon as I remove the v-bind directives, the error is gone.

**Comment by yoyo930021** [comment]
It's a limit.
https://vuejs.github.io/vetur/guide/FAQ.html#property-xxx-does-not-exist-on-type-combinedvueinstance

**Comment by edwillys** [comment]
Not sure if I quite get why it doesn't work. The explanation on the link above is rather vague: _"If you are getting a lot of Property 'xxx' does not exist on type 'CombinedVueInstance' errors, it's an issue with Vue's typing and TypeScript"_

Can you suggest a workaround on the codepen above, which is not very intrusive and that won't disable all of the other Vetur functionalities? The ones mentioned are rather too drastic (completely disabling checks or change to Composition API) or don't work (Annotating return type)

**Comment by yoyo930021** [comment]
> Not sure if I quite get why it doesn't work. The explanation on the link above is rather vague: _"If you are getting a lot of Property 'xxx' does not exist on type 'CombinedVueInstance' errors, it's an issue with Vue's typing and TypeScript"_
> 
> Can you suggest a workaround on the codepen above, which is not very intrusive and that won't disable all of the other Vetur functionalities? The ones mentioned are rather too drastic (completely disabling checks or change to Composition API) or don't work (Annotating return type)

It is a complex problem with Vue and TypeScript.
It currently has no simple solution.
We would like to solve the problem, but we need more time.
