### ISSUE TITLE
$store not define/exist in Vue 3 typescript project.

### ISSUE THREAD

**Issue by vutran6853** [vuejs/vetur#2629]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [ ] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Win
- Vetur version: 0.31.3
- VS Code version: 1.52

## Problem
When access vuex by `this.$store` anywhere in my component. I get error and it won't compile on save. Not sure if Vetur, Vuex, Vue issue. I do not have no eslint/lint plugin in this project. Let me know. Thank

![Imgur](https://imgur.com/K21tY7B.png)

## Reproducible Case
1) create new vue cli project
2) pick default Vue 3 with typescript and Vuex
3) sample code: 
```
<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'HelloWorld',
  mounted() {
    console.log('this.$store', this.$store)
  }
})
</script>
```

**Comment by yoyo930021** [comment]
https://next.vuex.vuejs.org/guide/migrating-to-4-0-from-3-x.html#typescript-support

**Comment by C-alcium** [comment]
How are you meant to pack the above recommendation with the pre-generated shims-vue.d.ts?
