### ISSUE TITLE
"Cannot read property 'vue' of undefined" when there's no "dependencies" in package.json

### ISSUE THREAD

**Issue by scrollbar-ww** [vuejs/vetur#2632]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [ ] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: 
- Vetur version: 0.31.3
- VS Code version: 1.52.1

## Source
"vueVersion.ts":
``` typescript
export function inferVueVersion(packagePath: string | undefined): VueVersion {
  const packageJSONPath = packagePath;
  try {
    if (!packageJSONPath) {
      throw new Error(`Can't find package.json in project`);
    }
    const packageJSON = packageJSONPath && JSON.parse(readFileSync(packageJSONPath, { encoding: 'utf-8' }));
    const vueDependencyVersion = packageJSON.dependencies.vue || packageJSON.devDependencies.vue;
`

**Comment by yoyo930021** [comment]
We need to infer vue version for some features.

**Comment by scrollbar-ww** [comment]
some component lib doesn't have "dependencies", all external dependencies are in "devDependencies"。
so，it's a little earlier to throw the error.
you should wrote like this:
`
  const vueDependencyVersion = packageJSON.dependencies?.vue || packageJSON.devDependencies?.vue;
`
if got undefined, throw error.

**Comment by yoyo930021** [comment]
> some component lib doesn't have "dependencies", all external dependencies are in "devDependencies"。
> so，it's a little earlier to throw the error.
> you should wrote like this:
> `const vueDependencyVersion = packageJSON.dependencies?.vue || packageJSON.devDependencies?.vue;`
> if got undefined, throw error.

No any error about this case.
![截圖 2021-01-11 下午6 45 10](https://user-images.githubusercontent.com/9126398/104171145-2f67c480-543d-11eb-8e26-81cfff4a8794.png)
![截圖 2021-01-11 下午6 45 18](https://user-images.githubusercontent.com/9126398/104171151-3262b500-543d-11eb-83ce-5380a6a0a714.png)

**Comment by yoyo930021** [comment]
Thanks @scrollbar-ww.
Nice catch.
