### ISSUE TITLE
Auto completion without auto import

### ISSUE THREAD

**Issue by aurelienbobenrieth** [vuejs/vetur#2633]
Not sure If should have posted this as a bug or a feature request.

I would like to know if in "Preferences" you could add the possibility to enable _auto completion_, **without** auto import.

The auto import is always messed up in my project, it does not manage to use the aliases set up in webpack, it auto import the file as many time as I auto complete tags, and above all it places the component name quite randomly, sometimes it is placed in "props" or "data" and makes the compilation crash.
For now I disabled it, however I would really like the auto completion to work, I don't mind having to import my component manually as long as the auto completion is fine.

Thank you very much for your time

**Comment by yoyo930021** [comment]
> The auto import is always messed up in my project, it does not manage to use the aliases set up in webpack

You can use `tsconfig.json`/`jsconfig.json` to set path alias.
The `javascript/typescript.preferences.importModuleSpecifier` option can set auto-import path policy.

> it auto import the file as many time as I auto complete tags, and above all it places the component name quite randomly, sometimes it is placed in "props" or "data" and makes the compilation crash.

Please open a issue and provide a repro project. I can study this bug.

> I would like to know if in "Preferences" you could add the possibility to enable auto completion, without auto import.

Temporary solution: `vetur.completion.autoImport` can close it.
