### ISSUE TITLE
Vetur should honor .eslintrc from workspace

### ISSUE THREAD

**Issue by some-user123** [vuejs/vetur#2636]
- [x] I have searched through existing issues

## Feature Request

I'm using yarn workspace and followed the documentation: https://vuejs.github.io/vetur/guide/setup.html#project-setup

This works great, with one exception. My configuration of `eslint-plugin-vue` rules in .eslintrc is not picked up from my workspace I.e. non-root folder). Would be cool, if this could be added as a feature.

Please let me know, if you need more information/input.

**Comment by yoyo930021** [comment]
If you have custom ESLint rules for vue, we will suggest close template validation and use ESLint extension.
https://vuejs.github.io/vetur/guide/linting-error.html#linting
