### ISSUE TITLE
Custom component in `template` won't get it's attributes suggestions?

### ISSUE THREAD

**Issue by yaquawa** [vuejs/vetur#2649]
## Info

- Platform: macOS
- Vetur version: 0.32.0
- VS Code version: 1.52.1

## Problem
Custom component in `template` won't get it's attributes suggestions.

## Reproducible Case

```vue
<template>
    <Foo ppp="xxx" />
</template>

<script lang="ts">
import { Foo } from 'foo'

export default defineComponent({
    components: { Foo }
})
</script>
```

`ppp="xxx"` won't get any warning even if the `Foo` component doesn't have such a prop. Also it won't get any auto suggestions of attributes that `Foo` provides.

**Comment by yoyo930021** [comment]
Please provide a repro case.
Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md

And we don't support no file extension for import Vue SFC.
