### ISSUE TITLE
Vetur won't recognize props with a default value function

### ISSUE THREAD

**Issue by bux** [vuejs/vetur#2669]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [-] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md) Link doesn't work
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Win
- Vetur version: 0.32.0
- VS Code version: 1.52.1

## Problem

Using vue 3 and typescript

Error with default value
![image](https://user-images.githubusercontent.com/1235520/106728866-2cf82500-660d-11eb-9ebf-045791ddf3f4.png)

No Error when omitting the default value
![image](https://user-images.githubusercontent.com/1235520/106728905-3aadaa80-660d-11eb-94a4-62b9ec811bbe.png)

**Comment by yoyo930021** [comment]
You can try to define define a return type on your default.
Ref: https://github.com/vuejs/vue/issues/8679

We believe the same happens in vue 3.

**Comment by bux** [comment]
Thank you.

Using both `PropType` and an arrow function resolves the error message.

```
props: {
    elements: {
        type: Array as PropType<Element[]>,
        default: () => {
            return []
        },
    },
},
```
