### ISSUE TITLE
Vue Language Server crashed in VS Code Insiders 1.14.0

### ISSUE THREAD

**Issue by ppasieka** [vuejs/vetur#268]
- Platform: Win
- Vetur version: 0.8.5
- VSCode version:  1.14.0-insider

## Problem
```
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Piotr\.vscode-insiders\extensions\octref.vetur-0.8.5\client\node_modules\vue-language-server\dist\vueServerMain.js:8:9)
    at Object.<anonymous> (C:\Users\Piotr\.vscode-insiders\extensions\octref.vetur-0.8.5\client\node_modules\vue-language-server\dist\vueServerMain.js:225:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
[Info  - 15:14:08] Connection to server got closed. Server will restart.
module.js:472
    throw err;

```

## Reproducible Case

Open vue file

In Stable VSCode plugin works.

**Comment by octref** [comment]
Do you have lodash in `C:\Users\Piotr\.vscode-insiders\extensions\octref.vetur-0.8.5\client\node_modules\`?

**Comment by ppasieka** [comment]
I had to run 
`npm install` in
`C:\Users\Piotr\.vscode-insiders\extensions\octref.vetur-0.8.5\client\`

**Comment by LukeLin** [comment]
I got this error too after vscode auto updating vetur plugin.

**Comment by octref** [comment]
@LukeLin https://octref.github.io/vetur/setup.html#overall

**Comment by LukeLin** [comment]
@octref Problem resolved after upgrading to newest version!

**Comment by Moerj** [comment]
![qq20170709-010319 2x](https://user-images.githubusercontent.com/13795438/27987581-51897e1c-6442-11e7-9736-d6f86ae8a461.jpg)


@octref I have same problem when I upgrading vetur version 0.8.6 to 0.9.0
But in 0.8.6 it is ok.

**Comment by Moerj** [comment]
![qq20170709-010855 2x](https://user-images.githubusercontent.com/13795438/27987659-a7e840b2-6443-11e7-9353-93bc72236f10.jpg)


@octref When I add a jsconfig.json. Bug solved.
So jsconfig.json is necessary? 😅

**Comment by doommm** [comment]
i have the same issue , and add jsconfig or tsconfig file don't work for me.
vscode for windows, version 1.13.1. vetur 0.9.0.

**Comment by BruceLpc** [comment]
![qq 20170710140504](https://user-images.githubusercontent.com/17290663/28004621-792a3380-6578-11e7-9061-240b37ba9d08.png)

I have the same issue ，vscode for windows, version 1.13.1. vetur 0.9.0.

**Comment by octref** [comment]
@BruceLpc Your issue is #321

**Comment by octref** [comment]
This seems to be an issue with VSCode having incomplete `node_modules` when installing extensions.

Uninstall / Reinstall seems to work. See #323.
