### ISSUE TITLE
The syntax highlighting of lang="ts" is inconsistent with the syntax highlighting of the .ts file

### ISSUE THREAD

**Issue by luwanquan** [vuejs/vetur#2687]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.32.0
- VS Code version: 1.53.0
- VS Code theme: One Dark Pro
- VS Code formatter: Prettier

## Problem

![image](https://user-images.githubusercontent.com/17645984/107109247-a1cf9700-6879-11eb-8d2c-05ac7c91083d.png)

This is an irrelevant question, but I have always been curious about what caused the inconsistency of the highlighting on both sides🤔 .
Prior to this, I have searched a lot of information and did not find the specific reason.

**Comment by jasonlyu123** [comment]
I think it's because the typescript extension has the [semantic-highlighting](https://code.visualstudio.com/updates/v1_43#_typescript-semantic-highlighting) feature. It provides highlights with type analysis.

**Comment by luwanquan** [comment]
@jasonlyu123 You are correct, when I set `"editor.semanticHighlighting.enabled": false`, the display of the .ts file is the same as the display of lang="ts".

**Comment by zhuqingguang** [comment]
楼主，我想问下在VSCode 中，你在vue3 的工程中使用 `lang="ts”`, 会有类型检查吗？ 我用vue-cli 初始化 vue3 的项目，不会报类型检查。。
![Uploading image.png…]()
