### ISSUE TITLE
Property does not exist on type 'unknown'.Vetur(2339)

### ISSUE THREAD

**Issue by franfrLor** [vuejs/vetur#2690]
When I do a v-for, I have errors on the object used:
```
<template v-for="option in options" v-slot:[option.slot]>
      <div :key="option.slot">
        <q-img
          :src="urlImage(option.image)"
          style="height: 30px; width: 30px"
        />
      </div>
</template>
```

I have this error on the properties of the object used via the v-for :
options has type Array in props
Property 'slot' does not exist on type 'unknown'.Vetur(2339)

How can I fix this error?

**Comment by yoyo930021** [comment]
If your code is correct, you may have this problem.
https://vuejs.github.io/vetur/guide/FAQ.html#property-xxx-does-not-exist-on-type-combinedvueinstance

**Comment by geoidesic** [comment]
I am getting this same error in every vue file. I am not using TypeScript. This is new behaviour... didn't used to have this error in these same files. It happens in every template, whenever there is a reference to the vm.
