### ISSUE TITLE
'event' is deprecated vetur6385

### ISSUE THREAD

**Issue by Fanna1119** [vuejs/vetur#2705]
As the title says.
How do I deal with this warning? I am uncertain if this is vue side or vetur side.
How does one deal with the event otherwise?

```js

<template>
  <p @mousewheel.passive="check()">test</p>
  {{ count }}
  <p @mousewheel.passive="test()">test</p>
</template>

<script>
import { ref } from "vue";
export default {
  setup() {
    const count = ref(0);

    const check = () => {
      const direction = event.deltaY < 0 ? count.value++ : count.value--;
      console.log(direction);
    };

    const test = () => {
      console.log(event);
    };
    return {
      check,
      count,
      test,
    };
  },
};
</script>


```
![Screenshot_20210214_193153](https://user-images.githubusercontent.com/4569097/107884134-c7a10f80-6efb-11eb-9164-959b7947a4c9.png)

**Comment by LinusBorg** [comment]
This is not related to Vetur.

https://developer.mozilla.org/en-US/docs/Web/API/Window/event

**Comment by yoyo930021** [comment]
Same as @LinusBorg 
Maybe you need to use native event?
```typescript
const check = (event: Event) => {
  console.log(event)
}
```
