### ISSUE TITLE
Vetur claims that FileList is not iterable

### ISSUE THREAD

**Issue by Fuzzyma** [vuejs/vetur#2706]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: win10
- Vetur version: 0.32
- VS Code version: 1.53.2

## Problem

```
Type 'FileList' must have a '[Symbol.iterator]()' method that returns an iterator.Vetur(2488)
```

![vetur error](https://user-images.githubusercontent.com/3540542/108194349-3f707380-7162-11eb-9eb2-571113b4feb8.PNG)

## Reproducible Case

```typescript
    const onDrop = (ev: DragEvent) => {
      ev.preventDefault()

      if (!ev.dataTransfer) return

      const files = ev.dataTransfer.files

      const filtered = [ ...files ].filter(s => s.type.includes('image'))
    }
```

**Comment by yoyo930021** [comment]
Please provide a repro project.

![截圖 2021-02-17 下午7 00 59](https://user-images.githubusercontent.com/9126398/108195253-7a6aab00-7152-11eb-8e10-fe078fe8e5f5.png)

**Comment by yoyo930021** [comment]
Your issue is closed because you did not provide a repro case.
Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.

**Comment by jasonlyu123** [comment]
Did you include `DOM.Iterable` in your `tsconfig`?
