### ISSUE TITLE
No definition found for computed property

### ISSUE THREAD

**Issue by chrissyast** [vuejs/vetur#2718]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Win 10
- Vetur version: 0.32
- VS Code version: 1.53

## Problem

![image](https://user-images.githubusercontent.com/31564153/108627589-5ce95a00-744e-11eb-9cb5-9d7f78fb43c7.png)

## Reproducible Case
`pages/index.vue` within https://github.com/chrissyast/teaching

Open in VS Code, click on {{ welcomeText }} on line 5, press F12 to go to the definition of welcomeText.

Expected behaviour is to jump to declaration of `welcomeText` within `computed`

**Comment by yoyo930021** [comment]
https://vuejs.github.io/vetur/guide/FAQ.html#property-xxx-does-not-exist-on-type-combinedvueinstance
