### ISSUE TITLE
Not able to Disable autoformatting the code

### ISSUE THREAD

**Issue by dhara15101991** [vuejs/vetur#2720]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [ ] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Linux
- Vetur version: v0.32.0
- VS Code version: 1.53.2

I have been finding a solution for not able to disable the formatting. But nothing works at all. I did the following things but it seems that not working.
I opened a file from myproject -> .vscode -> settings.json. Added following line but it is not working at all

"editor.formatOnSave": false

Then I opened F1-> Preferences: Open Settings (JSON). There I add 

`"editor.formatOnSave": false,` and `"[vue]": { "editor.formatOnSave": false },` 

But it is also not working at all. 

Also, there is no proper documentation which says that where to add the below the line.

`"vetur.format.enable": false` 

I go through the following [https://github.com/vuejs/vetur/issues/1056](Issue) but not working for me.

I am new to VS Code. I don't know where to add all vetur configurations?  Which file? Where is located? If anyone guides me to add vetur configuration it will be very helpful

Can anyone please help me?

**Comment by yoyo930021** [comment]
Can you provide some video?
I don't understand what happened about your problem

**Comment by dhara15101991** [comment]
Hello @yoyo930021 ,

Please check below video. 

https://user-images.githubusercontent.com/14217908/108949179-f05a9f00-7689-11eb-947d-d92461863a70.mp4

**Comment by yoyo930021** [comment]
> Hello @yoyo930021 ,
> 
> Please check below video. 
> 
> https://user-images.githubusercontent.com/14217908/108949179-f05a9f00-7689-11eb-947d-d92461863a70.mp4
> 
> 

Can you disable other extensions and try again?

**Comment by dhara15101991** [comment]
![image](https://user-images.githubusercontent.com/14217908/108951183-8a701680-768d-11eb-9f22-ddddc2c2d7a7.png)
These extensions are installed. Let me check by disabling it.

**Comment by dhara15101991** [comment]
I disabled it but it is still formatting the code. FYI I am using the Nuxt framework of vue.

**Comment by yoyo930021** [comment]
> I disabled it but it is still formatting the code. FYI I am using the Nuxt framework of vue. Can you guide me where to add
> `"vetur.format.enable": false` code? All configuration starts from **vetur**

I think that format is not made by VSCode.
Can you provide your `package.json` content?

**Comment by dhara15101991** [comment]
![image](https://user-images.githubusercontent.com/14217908/108973470-5e16c300-76aa-11eb-9ec3-4ae25fa68625.png)

**Comment by yoyo930021** [comment]
Set `eslint.autoFixOnSave": false` ?

**Comment by dhara15101991** [comment]
In which config file this need to save?

**Comment by yoyo930021** [comment]
> ![image](https://user-images.githubusercontent.com/14217908/108951183-8a701680-768d-11eb-9f22-ddddc2c2d7a7.png)
> These extensions are installed. Let me check by disabling it.

Use this option, active vetur and test
![截圖 2021-02-24 下午4 49 41](https://user-images.githubusercontent.com/9126398/108974306-4b0eed80-76c0-11eb-8c1d-35a9736a83b9.png)

**Comment by dhara15101991** [comment]
I did it. But I find something else. When I don't run the build from the console, it doesn't format the code. but as soon as I run `npm run dev` it formats my code. I think this is something else.

https://www.awesomescreenshot.com/video/2856786?key=fb7f2ca8b1cf0f662cacedc545ba493f

See above video

**Comment by yoyo930021** [comment]
Your problem isn't in the vetur.
