### ISSUE TITLE
Prop TagCasing is not used for global Components

### ISSUE THREAD

**Issue by Seuthes** [vuejs/vetur#2721]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Win
- Vetur version: 0.32.0
- VS Code version: 1.53.2

## Problem

If you configugure global components (which is an awesome feature), they will be always suggested in kebab-case, although I setted `"vetur.completion.tagCasing": "initial"`. 

I have also PascalCase for my other components, but not the global ones.

I looked into the source code of the method `getGlobalComponents` and noted that it has alredy everything to support PascalCase, but unfortnatly the prop `tagCasing` is not passed in the `componentInfo.ts` on line 67:

`const globalComponents = getGlobalComponents(tsModule, service, globalComponentInfos);`

If you could fix this, it would be great!

Just replace it with:
`const globalComponents = getGlobalComponents(tsModule, service, globalComponentInfos, config.vetur.completion.tagCasing);`

**Comment by yoyo930021** [comment]
Fixed in https://github.com/vuejs/vetur/commit/07f816d953d12c130e0ca7f77e96f642d6418bd2
