### ISSUE TITLE
Composition API snippets

### ISSUE THREAD

**Issue by Namchee** [vuejs/vetur#2741]
- [x] I have searched through existing issues

## Feature Request

Composition API is a new way to write your Vue components. However, currently Vetur only provides quick snippets for Options API for the `script` tag. It would be awesome if Vetur provides snippets to quickly scaffold Composition API-based components, both with and without TypeScript.

For example, we can type `composition-ts` to quickly write

```vue
<script lang="ts">
import { defineComponent } from '@vue/composition-api';

export default defineComponent({
  setup() {
  
  },
});
</script>
```

And `composition-js` to write

```vue
<script>
export default {
  setup() {
  
  },
};
</script>
```

**Comment by yoyo930021** [comment]
Fixed #2761
