### ISSUE TITLE
style error in vue file

### ISSUE THREAD

**Issue by murphysking** [vuejs/vetur#2742]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [ ] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: macOS
- Vetur version: 0.32.0
- VS Code version: 1.53.2

## Problem

![2021-03-02 10 03 05](https://user-images.githubusercontent.com/22335334/109587494-1ed0f200-7b42-11eb-9483-c4a90fa159df.gif)

If i disable vetur,there' no emmet abbreviation and the problem disappear.Maybe it's a vetur problem.Does anyone knows how to resolve.

**Comment by yoyo930021** [comment]
Fixed in #2847

**Comment by murphysking** [comment]
thanks
