### ISSUE TITLE
编辑vue文件时的MDN Reference提示

### ISSUE THREAD

**Issue by ches1y** [vuejs/vetur#2744]
VSCode 1.52以上版本可以通过在settings.json里添加"html.hover.references": false等设置项来关闭html/CSS里的MDN Reference提示，参见https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_54.md#hovers-in-csslessscss-and-html

设置后在编辑.html/.css等后缀的文件时，MDN Reference的提示确实关闭了，但是在编辑.vue文件时仍存在，请问该如何设置vetur？或者在settings.json里如何设置？

谢谢！

**Comment by jasonlyu123** [comment]
This needs to be implemented in vetur. But it probably isn't hard. Just add some new config and pass them to the vscode-html/css-language-service library.

**Comment by yoyo930021** [comment]
You can also use `css.hover.documentation` and `css.hover.references` in vetur.
But we don't support `html.hover.documentation` and `html.hover.references`

**Comment by ches1y** [comment]
> You can also use `css.hover.documentation` and `css.hover.references` in vetur.

THX for the information.
But how to use them in vetur?

**Comment by yoyo930021** [comment]
> > You can also use `css.hover.documentation` and `css.hover.references` in vetur.
> 
> THX for the information.
> But how to use them in vetur?

Same key set in vscode setting, vetur will read it.

**Comment by katerlouis** [comment]
When the translation from Chinese works properly, @ches1y also wants to disable css and html documentation and references on hover in vue files. Unfortunately the settings

`css.hover.documentation: false` 
`css.hover.references: false`
`html.hover.documentation: false`
`html.hover.references: false`

seem to be ingored by vetur. 


> Same key set in vscode setting, vetur will read it.
or where exactly should I set this settings? I cannot find a vetur specific settings file or so.
