### ISSUE TITLE
An import path cannot end with a '.ts' extension. Consider importing 'xx.js' instead.

### ISSUE THREAD

**Issue by cn3lfs** [vuejs/vetur#2750]
- [ x] I have searched through existing issues
- [ x] I have read through [docs](https://vuejs.github.io/vetur)
- [ x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [ x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Win10
- Vetur version:0.33.0
- VS Code version:1.53.2

```json
// tsconfig.json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "allowJs": true,
    "importHelpers": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": ["webpack-env", "jest"],
    "paths": {
      "@/*": ["src/*"]
    },
    "lib": ["esnext", "dom", "dom.iterable", "scripthost"]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ],
  "exclude": ["node_modules", "public"]
}
```

```js
//.eslintrc.js

module.exports = {
  root: true,
  env: {
    node: true
  },
  extends: [
    'plugin:vue/essential',
    'eslint:recommended',
    '@vue/typescript/recommended',
    '@vue/prettier',
    '@vue/prettier/@typescript-eslint'
  ],
  parserOptions: {
    ecmaVersion: 2018
  },
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    '@typescript-eslint/no-explicit-any': 'off',
    '@typescript-eslint/no-unused-vars': 'warn',
    '@typescript-eslint/no-non-null-assertion': 'off',
    '@typescript-eslint/no-use-before-define': 'off',
    '@typescript-eslint/no-empty-function': 'off',
    '@typescript-eslint/no-this-alias': 'off',
    '@typescript-eslint/interface-name-prefix': 'off',
    '@typescript-eslint/camelcase': 'off',
    '@typescript-eslint/no-var-requires': 'off',
    'vue/require-component-is': 'off'
  },
  overrides: [
    {
      files: [
        '**/__tests__/*.{j,t}s?(x)',
        '**/tests/unit/**/*.spec.{j,t}s?(x)'
      ],
      env: {
        jest: true
      }
    }
  ]
}

```

```js
// webpack
  resolve: {
    alias: {
      '@': 'src',
      vue$: 'vue/dist/vue.runtime.esm.js'
    },
    extensions: [
      '.tsx',
      '.ts',
      '.mjs',
      '.js',
      '.jsx',
      '.vue',
      '.json',
      '.wasm'
    ],
}
```

## Problem

An import path cannot end with a '.ts' extension. Consider importing '@/utils/eventBus.js' instead.
![image](https://user-images.githubusercontent.com/31005019/109744306-037ee900-7c0d-11eb-910d-d6fdd0cc41bb.png)

It works right in  v0.32.0, so i back to 0.32.0 for now.

## Reproducible Case

[see this git](https://github.com/cn3lfs/vue-typescript-admin-template)

i modify a file.  in src\views\zip\index.vue

![image](https://user-images.githubusercontent.com/31005019/109746930-362ae080-7c11-11eb-97f2-16fbdbfb6363.png)

**Comment by yoyo930021** [comment]
Please provide a repro case.
https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md

I can't repro it.

**Comment by cn3lfs** [comment]
already add a repo. because import {} from 'a'. import {} from 'a.ts' are use in many place. I can not modify it all.

**Comment by yoyo930021** [comment]
It's a breaking change in typescript 4.2.
https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/#d-ts-extensions-cannot-be-used-in-import-paths

You can change your code or use old version typescript.

**Comment by yoyo930021** [comment]
Use replaced with regex can help you refactor your project.

**Comment by cn3lfs** [comment]
> Use replaced with regex can help you refactor your project.

it is company's project, i don't want to make lots of changes to code, it will takes some unnecessary troubles.

**Comment by drengr** [comment]
> It's a breaking change in typescript 4.2.
> https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/#d-ts-extensions-cannot-be-used-in-import-paths
> 
> You can change your code or use old version typescript with `vetur.useWorkspaceDependencies`.

Excuse me, but as far as I can see from cn3lfs repo - they try to import .ts flile, not a .d.ts file. So it looks like Vetur issue.
I have the same issue in my project with Vetur v0.34.1

**Comment by yoyo930021** [comment]
> > It's a breaking change in typescript 4.2.
> > https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/#d-ts-extensions-cannot-be-used-in-import-paths
> > You can change your code or use old version typescript with `vetur.useWorkspaceDependencies`.
> 
> Excuse me, but as far as I can see from cn3lfs repo - they try to import .ts flile, not a .d.ts file. So it looks like Vetur issue. I have the same issue in my project with Vetur v0.34.1. I'm trying to import some .ts file with helper functions.

It is a typescript behavior.
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzlApgMzgXzmqERwDkAAgG4CuKA9FOQHYygoC0AxtNQM5StXB0ATFAA8AdDE6EAUDKlA

**Comment by drengr** [comment]
> It is a typescript behavior. https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzlApgMzgXzmqERwDkAAgG4CuKA9FOQHYygoC0AxtNQM5StXB0ATFAA8AdDE6EAUDKlA

Yes, you're right. Sorry for bothering you.
