### ISSUE TITLE
Typescript + vue 3 setting props via variable gets optional properties of props that has required attributes

### ISSUE THREAD

**Issue by Lilja** [vuejs/vetur#2754]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: N/A
- Vetur version: "vls": "^0.7.1"
- VS Code version: N/A (coc-vetur: 1.2.3)

## Problem
I don’t know if this is a problem with the tooling/vetur or a vue-next problem.

I have a few components that share props, so naturally I’d thought to use a variable that is importable. By doing this, the language server/vetur tells me the props are optional.

By using props directly:
![image](https://user-images.githubusercontent.com/6134511/110017006-00c3e700-7d26-11eb-98d0-f6a672d98dcb.png)

Expected. msg is not-optional.

When using a variable:

![image](https://user-images.githubusercontent.com/6134511/110017068-12a58a00-7d26-11eb-8906-78d5bf975a14.png)

As you can see the msg prop is now optional? Even though it has required: true.

Is this an error with Vue-next or vetur?
Are there any workarounds that are not using `as unknown as ...`?

## Reproducible Case

```vue
<template>
  <div class="hello"> {{props}} </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue';

const ComponentProps = {
    msg: {
        type: String as PropType<string>,
        required: true
    }
}
export default defineComponent({
  props: {
    msg: {
        type: String as PropType<string>,
        required: true
    }
  }, /* ComponentProps, */
  setup(props) {

  }
});
</script>

```

**Comment by yoyo930021** [comment]
It's a problem in `vue-next` project.
