### ISSUE TITLE
Vetur can't find tsconfig.json or jsconfig.json

### ISSUE THREAD

**Issue by jacrosby** [vuejs/vetur#2765]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Win
- Vetur version: v0.33.1
- VS Code version: 1.54.1

## Problem

I have a VS Code workspace with many projects, one is the Vue frontend and all the others are backend services running .Net Core. On loading VS Code, I get dozens of messages about Vetur not being able to find tsconfig.json or jsconfig.json relating to the .Net Core services which obviously won't have those files. How can I stop Vetur showing these messages without adding any Vetur config files to those projects? They are not frontend projects so shouldn't be littered with frontend related config files. Thanks in advance!

![image](https://user-images.githubusercontent.com/40349956/110440524-b8287700-80f3-11eb-86f6-776295f39fe7.png)

## Reproducible Case

- Create a new workspace file in VS Code
- Add a Vue project to workspace
- Add a .Net Core project to workspace
- Open VS Code and you should see those messages

**Comment by jacrosby** [comment]
Thanks, I had seen that but missed the crucial line about the VS Code setting!

**Comment by caiqichang** [comment]
@yoyo930021 
https://vuejs.github.io/vetur/docs/guide/setup.html#project-setup
https://vuejs.github.io/vetur/docs/guide/setup.html#advanced
retuen 404

**Comment by danger89** [comment]
> https://vuejs.github.io/vetur/guide/FAQ.html#vetur-can-t-find-tsconfig-json-jsconfig-json-in-xxxx-xxxxxx

Is this file still required for V3? I could not find anything on: https://v3.vuejs.org/. Sorry..

**Comment by yoyo930021** [comment]
> @yoyo930021 https://vuejs.github.io/vetur/docs/guide/setup.html#project-setup https://vuejs.github.io/vetur/docs/guide/setup.html#advanced retuen 404

https://vuejs.github.io/vetur/guide/setup.html#project-setup
https://vuejs.github.io/vetur/guide/setup.html#advanced

**Comment by yoyo930021** [comment]
> > https://vuejs.github.io/vetur/guide/FAQ.html#vetur-can-t-find-tsconfig-json-jsconfig-json-in-xxxx-xxxxxx
> 
> Is this file still required for V3? I could not find anything on: https://v3.vuejs.org/. Sorry..

It is also needed in vue3. Not related to the Vue version.

**Comment by artnikbrothers** [comment]
spent some time to find the line in docs about disabling it. For those like me will just post a screenshot 

![image](https://user-images.githubusercontent.com/9512270/142448334-dca81c93-6098-4e0d-b6d7-3b60beb19e23.png)

**Comment by Felixbug23** [comment]
thanks👍

**Comment by madlife12327** [comment]
vetur only scan your project root folder , please restart vscode and make sure the root folder include `jsconfig.json` or `tsconfig.json`.

**Comment by mfoman** [comment]
And what about projects that don't have the frontend in the root but is a big monorepo.
