### ISSUE TITLE
@Component({ data }) object not getting recognized in template

### ISSUE THREAD

**Issue by ndresx** [vuejs/vetur#2766]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: macOS
- Vetur version: `0.33.1`
- VS Code version: `1.54.0`

## Problem

The via `vue-property-decorator` defined `@Component` decorator's `data` object is not getting recognized in the template. I'm not sure if that's a bug or intended, but it would be nice to support it.

![image](https://user-images.githubusercontent.com/27507295/110714368-87376780-8203-11eb-92f0-d2bde35b9718.png)

**Comment by yoyo930021** [comment]
It is a limit in typescript.
Decorator can't effect any type information in typescript.
So there is no solution to this problem.

We have some issue for solve this problem in `vue-class-component`.
https://github.com/vuejs/vue-class-component/issues/465
https://github.com/vuejs/vue-class-component/issues/416
https://github.com/vuejs/vue-class-component/issues/416
