### ISSUE TITLE
Interpolation when component extends from defineComponent

### ISSUE THREAD

**Issue by mercs600** [vuejs/vetur#2767]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: macOS
- Vetur version: 0.33.1
- VS Code version: Version: 1.54.1

## Problem

We're using https://github.com/vuejs/composition-api to define components. 
```vue
<script lang="ts">
import { defineComponent } from '@vue/composition-api'
export default defineComponent({
  name: 'CeHeader'
})
</script>
```

Then we have component which extends previous one and also use defineComponent ( but can be also defined by Vue.extend) 
```ts
export default defineComponent({
  extends: CeHeader,
})
```

In extended components interpolation doesn't work

### BaseComponent:
```vue
<template>
  <div>
    {{ headerTag }}
  </div>
</template>

<script lang="ts">
import { computed, defineComponent } from '@vue/composition-api'
import useSharedProps from '../../composables/useSharedProps'

export default defineComponent({
  name: 'CeHeader',
  props: {
    ...useSharedProps()
  },
  setup (props) {
    const headerTag = computed((): string => {
      return `h${props.headerLayout || 1}`
    })

    return {
      headerTag
    }
  }
})
</script>
```
<img width="720" alt="Zrzut ekranu 2021-03-11 o 15 52 01" src="https://user-images.githubusercontent.com/7935392/110805817-bab8d700-8281-11eb-9a81-632ee25864a0.png">

###  Extended components:
```vue
<template>
  <div>
    {{ headerTag }}
  </div>
</template>
<script lang="ts">
import { defineComponent } from '@vue/composition-api'
import CeHeader from './CeHeader.vue'
export default defineComponent({
  extends: CeHeader,
  computed: {
    iShouldGetTagAddnotation (): string {
      return this.headerTag
    }
  }
})
</script>
```
<img width="664" alt="Zrzut ekranu 2021-03-11 o 15 53 33" src="https://user-images.githubusercontent.com/7935392/110806007-f0f65680-8281-11eb-852c-9bb7532becd5.png">

## Solution
Any ideas how can I resolve it ? 

#### edit
I can use as separator, but then I can't extend my new components with new props/methods etc.
<img width="952" alt="Zrzut ekranu 2021-03-11 o 17 35 13" src="https://user-images.githubusercontent.com/7935392/110821732-a6300b00-8290-11eb-8163-b2034edcd5f3.png">

**Comment by yoyo930021** [comment]
It is a typescript limit or a type information bug or feature in the upstream library.
You can open a issue to `@vue/composition-api` project.

**Comment by mercs600** [comment]
I'll try, thanks @yoyo930021
