### ISSUE TITLE
When to support variable name syntax highlighting in <script setup> please?

### ISSUE THREAD

**Issue by microkof** [vuejs/vetur#2780]
The version of vetur in my PC is 0.33.1. VS Code theme is Monokai.

Now vetur doesn't support syntax highlighting in <script setup>. For example:

![image](https://wx4.sinaimg.cn/mw1024/3e2cf89cly1goh7zgsi8kj20bi05daaa.jpg)

**Comment by microkof** [comment]
And, since the variables is not needed to return, can you add a marker to the variable to indicate that it will be implicitly returned.

**Comment by yoyo930021** [comment]
Duplicate of https://github.com/vuejs/vetur/issues/2296
