### ISSUE TITLE
Add Vue3 support for vim and neovim 

### ISSUE THREAD

**Issue by wgxh** [vuejs/vetur#2782]
### Feature request

I use coc extension 'coc-vetur', But 'coc-vetur' does not seem to support Vue3.
I have posted a feature request on coc-vetur, but its author says, 'Send your feature request to https://www.npmjs.com/package/vls.', See [this](https://github.com/neoclide/coc-vetur/issues/69).
I think This language server should include these support for Vue3 feature:
1. Support `<script setup>`.
2. Auto completion CSS `v-bind()`.
3. Auto completion variable names in html interpolation expression.(Variables is define in `setup function`)

I hope this language server can add vue3 support for vim/neovim, Thanks!

**Comment by yoyo930021** [comment]
Vetur and vls support vue3.
but they don't support `<script setup>`. Please follow https://github.com/vuejs/vetur/issues/2296.

> Auto completion CSS v-bind().

Please open a new issue about this.

**Comment by wgxh** [comment]
> Vetur and vls support vue3.
> but they don't support `<script setup>`. Please follow #2296.
> 
> > Auto completion CSS v-bind().
> Please open a new issue about this.

Oh, Thanks! I hope this language server support `<script setup>` feature very soon!
