### ISSUE TITLE
Better intellisense 

### ISSUE THREAD

**Issue by Thaval** [vuejs/vetur#2794]
## Feature Request

IntelliSense is a crucial feature for developers, especially if you reference members of another file. Is saves time navigating around, creating typos and let foreign developers quickly see a kind of API live while coding. 

Currently intellisense seems not to be working in multi file components. It would be great if you could add this feature and provide better intellisense in general (slot names, scoped slots, custom events, custom components, filters, etc)

**Comment by yoyo930021** [comment]
You propose too scattered.
Please make practical suggestions and open issues.
In fact, there are many features that may already have issues.
