### ISSUE TITLE
The TypeScript language service died unexpectedly

### ISSUE THREAD

**Issue by yogithesymbian** [vuejs/vetur#2820]
Issue Type: <b>Bug</b>

The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

Extension version: 0.33.1
VS Code version: Code - Insiders 1.55.0-insider (6ebe2a14f3722bc2582ecd8108d0a71dfdd46036, 2021-03-25T16:25:42.996Z)
OS version: Darwin arm64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (2.32GB free)|
|Process Argv|--crash-reporter-id 2c5ea852-5c71-40ae-b5b6-8e23957d70ab|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
pythonvspyt943:30277000
openwslfolder:30278404
vspre833cf:30267465
vsdfh931cf:30280410
vscnewfilebutton:30280634
vshan820cf:30276953

```

</details>

**Comment by yoyo930021** [comment]
What does TypeScript language service die?
In vue language server? In vscode?
Please provide some information or screenshot or repro case.

**Comment by yogithesymbian** [comment]
> What does TypeScript language service die?
> In vue language server? In vscode?
> Please provide some information or screenshot or repro case.

hmm , vscode.
<img width="468" alt="vetur" src="https://user-images.githubusercontent.com/28316296/112711877-b4279200-8f06-11eb-8d43-fc8c39958663.png">

**Comment by yoyo930021** [comment]
> > What does TypeScript language service die?
> > In vue language server? In vscode?
> > Please provide some information or screenshot or repro case.
> 
> hmm , vscode.
> <img alt="vetur" width="468" src="https://user-images.githubusercontent.com/28316296/112711877-b4279200-8f06-11eb-8d43-fc8c39958663.png">

Vetur doesn't effect with TypeScript language service now.
You can report issue to TypeScript project.

Please follow https://github.com/vuejs/vetur/issues/2724#issuecomment-804893788 with vue language server crash
