### ISSUE TITLE
Moving Vetur to vuejs organization

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#284]
Since Vetur has changed its mission from being a VSCode extension to providing a Language Server Protocol compliant `vue-language-server` that could help users using any editor supporting LSP, I think it's time to move Vetur to vuejs organization.

Me, @HerringtonDarkholme and @ktsn will work together to improve `vue-language-server`.
I'm also open to using `vue-language-server` for possibly Atom / Neovim / Sublime, which has partial LSP client. But due to my lack of knowledge of Atom / Neovim / Sublime (and lack of time), I will just focus on developing the VSCode client. However, contributions are welcome!

For end users there should be no change. But if possible I'd like to move the doc to https://vetur.vuejs.org.

@yyx990803

**Comment by yyx990803** [comment]
This is great news. Transferring individual repos into org can be tricky because you need full admin rights in the receiving org. Instead you can first transfer it to my personal account, and I'll then move it into the `vuejs` org.

**Comment by octref** [comment]
OK, submitted request.

**Comment by yyx990803** [comment]
Done!
