### ISSUE TITLE
Prettier-eslint formatting doesn't work

### ISSUE THREAD

**Issue by Vorror** [vuejs/vetur#2840]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [X] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: MacOs (intel)
- Vetur version: 0.33.1
- VS Code version: 1.55.0
- Node version: 12.18.3

## Problem

The `"vetur.format.defaultFormatter.js": "prettier-eslint"` setting does not work. I've tried this setting at _both_ the workspace level and at the user level.

With a fairly basic eslint config:
```js
module.exports = {
  extends: ['eslint:recommended', 'plugin:vue/recommended'],
  rules: {
    'quote-props': ['error', 'consistent-as-needed']
  },
  parser: 'vue-eslint-parser'
}
```

This:
```js
const test = {
  'hello-world': 'foo',
  foo: 'bar'
}
```

Should transform into below when eslint is run:
```js
const test = {
  'hello-world': 'foo',
  "foo": 'bar' // "foo" is now quoted
}
```

Eslint works correctly when run directly using: `./node_modules/.bin/eslint --fix ./src/Test.vue` or using the `ESlint: Fix all auto-fixable issues` option in VSCode.

The user setting `"vetur.useWorkspaceDependencies": true` does not affect this issue. I've tried with both this setting on _and_ off.

VLS Logs
```
[DEBUG] Using prettier. Options
{"singleQuote":true,"semi":false,"trailingComma":"none","printWidth":80,"tabWidth":2,"useTabs":false,"parser":"vue"}
[DEBUG] Using prettier-eslint. Options
{"singleQuote":true,"semi":false,"trailingComma":"none","printWidth":80,"tabWidth":2,"useTabs":false,"parser":"babel"}
```

As an aside, with `"vetur.format.defaultFormatter.js": "prettier-eslint"` prettier no longer respects `.prettierrc.json` file(tested by turning `semi:false` on and off).

Also, there's nothing special with the `quote-props` eslint rule. I simply picked a rule that I knew demonstrated the issue.

## Reproducible Case

I've created a sample repo [here](https://github.com/Vorror/vetur-prettier-eslint) that demonstrates the issue.

**Comment by Vorror** [comment]
After a lot of testing, here's what I found.

The last working version of Vetur is `29.1` w/ `prettier-eslint@10.0.0`
![image](https://user-images.githubusercontent.com/3613230/113465357-5bbe2c00-9401-11eb-80d6-fa9f0fa26bbe.png)

![image](https://user-images.githubusercontent.com/3613230/113465362-68db1b00-9401-11eb-8916-e2f40198922d.png)


If you use a version of either, then everything stops working. Here's a work branch of repo: https://github.com/Vorror/vetur-prettier-eslint/tree/work-branch

**Comment by arpowers** [comment]
I can confirm that recently I haven't had formatting in component HTML templates working ... this may be the cause.
