### ISSUE TITLE
Parsing error: Invalid first character of tag name on comparison with less-than operator (<)

### ISSUE THREAD

**Issue by heimer16** [vuejs/vetur#2858]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Linux
- Vetur version:  0.33.1
- VS Code version: 1.54.3

## Problem

[vue/no-parsing-error]
Parsing error: invalid-first-character-of-tag-name.eslint-plugin-vue

![2021-04-11-035935_793x131_scrot](https://user-images.githubusercontent.com/890855/114299895-e1ce1880-9a7a-11eb-8cda-fd49ed3ed84d.png)

## Reproducible Case
Install vscode
install vetur
create new .vue file.  insert a conditional statement with ternary operator including < (less than)

```
<template>
    <p>{{ min < max ? 'yep' : 'nope' }}</p>
</template>

**Comment by yoyo930021** [comment]
Ref: https://github.com/vuejs/eslint-plugin-vue/issues/370
