### ISSUE TITLE
Incorrect syntax highlighting when using nullish coalescing in template

### ISSUE THREAD

**Issue by CLDXiang** [vuejs/vetur#2861]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Win10
- Vetur version: 0.33.1
- VS Code version: 1.55.1

## Problem

When using nullish coalescing（`??`） in template, syntax highlighting behaves unexpectedly:

![image](https://user-images.githubusercontent.com/23160486/114444153-1d92ea80-9c01-11eb-9f54-0b3383a6475f.png)

While using `||` the highlighing is correct:

![image](https://user-images.githubusercontent.com/23160486/114444338-54690080-9c01-11eb-93d2-feee10d19903.png)

**I don't know why but this problem doesn't happen on my macOS (with same VSCode extensions and settings).**

## Reproducible Case

Create a new `.vue` file:

```vue
<template>
  <div>
    <span>
      {{ aVariable ?? 3 }}
    </span>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  props: {
    aVariable: { type: Number, required: true },
  },
});
</script>
```

**Comment by simaodiascosta** [comment]
Similar happens when using typeof operator in a v-if condition

Using typeof
![image](https://user-images.githubusercontent.com/46888903/114537256-e7c62400-9c49-11eb-97ab-0738eca6a762.png)

No typeof
![image](https://user-images.githubusercontent.com/46888903/114537091-b188a480-9c49-11eb-911e-aa785829cd2c.png)

**Comment by Dassderdie** [comment]
A possible workaround for the `typeof` could be to add brackets:
![image](https://user-images.githubusercontent.com/18506183/116094792-1f9c8500-a6a8-11eb-8a74-ecb678fc1ed8.png)

![image](https://user-images.githubusercontent.com/18506183/116094737-14e1f000-a6a8-11eb-94d9-1ed6c70681db.png)

**Comment by yoyo930021** [comment]
I work well when VSCode 1.56.2 in windows.
<img width="335" alt="截圖 2021-06-02" src="https://user-images.githubusercontent.com/9126398/120435386-3c675f00-c3b0-11eb-8884-b7c5e195855b.png">

**Comment by CLDXiang** [comment]
@yoyo930021 I tried to disable my VS Code plugins one by one and found this problem was caused by a deprecated plugin _Sublime Babel_ (joshpeng.sublime-babel-vscode), I'm sorry for the wrong report, **this is not a Vetur's bug**. But the _typeof_ case in the comments seems to be a reproducible problem.

**Comment by yoyo930021** [comment]
I will close this issue. Thanks for your report.
The `typeof` problem ☞ https://github.com/vuejs/vetur/issues/2709
