### ISSUE TITLE
Template Interpolation issue with data() when using Object Spread Operator

### ISSUE THREAD

**Issue by Wacheee** [vuejs/vetur#2864]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform:  Win
- Vetur version: 0.33.1
- VS Code version: 1.55.1
- Vue version: v2

## Problem
When i use the Object Spread Operator (...) to use mapState and mapGetters inside computed properties, then the properties from data() is no longer recognized by interpolation, even if i add differents objects to data, still the same. When i start the server Vue doesnt give me warnings or error and the page run normally (v-model and methods using this prop works ok)

![image](https://user-images.githubusercontent.com/77031418/114640029-4799ea80-9c9d-11eb-8c78-0447d3306773.png)
![image](https://user-images.githubusercontent.com/77031418/114640216-99db0b80-9c9d-11eb-9947-c62eb6687da4.png)
![image](https://user-images.githubusercontent.com/77031418/114640227-9f385600-9c9d-11eb-8cb3-eaa10f4aa066.png)

But if i dont use Object Spread Operator, and only use mapState or mapGetters then no issue:

![image](https://user-images.githubusercontent.com/77031418/114640311-d4dd3f00-9c9d-11eb-95d6-5192fa462b7b.png) 
![image](https://user-images.githubusercontent.com/77031418/114640648-9005d800-9c9e-11eb-9581-9fe099272401.png)
![image](https://user-images.githubusercontent.com/77031418/114640316-d9a1f300-9c9d-11eb-8ba4-6ad7087b3ffb.png)

I'm not sure if im doing something wrong, im new to vue and vetur, but i didn't found this issue here or in the Internet.

Greets

**Comment by yoyo930021** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord](https://vue-land.js.org/) server or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by Wacheee** [comment]
Hello, but this is a bug from vetur, because Vue functions normally, its vetur Interpolations tthat has problem
