### ISSUE TITLE
Cannot find module '/@/xxx' or its corresponding type declarations.Vetur(2307)

### ISSUE THREAD

**Issue by xingyesh** [vuejs/vetur#2875]
-  [x] I have searched through existing issues
-  [x] I have read through [docs](https://vuejs.github.io/vetur)
-  [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
-  [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform:  macos
- Vetur version: v.0.33.1 
- VS Code version: 1.55.2
- vue version: 3.0.0

## Reproducible Case

![image](https://user-images.githubusercontent.com/16128175/115180779-fe1c2600-a108-11eb-8f6e-4554f4c1163c.png)
![image](https://user-images.githubusercontent.com/16128175/115180778-fe1c2600-a108-11eb-8b43-a2ab3e276150.png)

cannot find module /@/xx on vite2 app.
```
// vitejs config
alias: {
        '/@': path.resolve(__dirname, 'src') 
      }
```
base on issue https://github.com/vuejs/vetur/issues/1896 and mr https://github.com/vuejs/vetur/pull/2525, but the error is still having

**Comment by yoyo930021** [comment]
https://vuejs.github.io/vetur/guide/FAQ.html#vetur-can-t-recognize-components-imported-using-webpack-s-alias

**Comment by xingyesh** [comment]
em... thanks。 use @ instead of /@ is ok!  /@ still occur error

**Comment by wdlhao** [comment]
问题解决了吗？我也遇到了这个问题；
![image](https://user-images.githubusercontent.com/11900691/115491788-32bbe900-a293-11eb-9995-33f9c9b3219c.png)

**Comment by 17biubiu** [comment]
同问

**Comment by zptime** [comment]
通过vscode将文件夹加入到工作区时，必须单独加载，并且放在第一个

![alias](https://user-images.githubusercontent.com/21326338/121645198-7e865400-cac6-11eb-9bcc-edee22cccbe4.jpg)

**Comment by drewlsvern** [comment]
> （1）tsconfig.json配置
> 
> ```json
> {
>   "compilerOptions": {
>     "baseUrl": "./",
>     "paths": {
>       "@": ["src/*"],
>       "store/*": ["src/store/*"]
>     }
>   }
> }
> ```
> 
> （2）通过vscode将文件夹加入到工作区时，必须单独加载，并且放在第一个
> 
> ![alias](https://user-images.githubusercontent.com/21326338/121645198-7e865400-cac6-11eb-9bcc-edee22cccbe4.jpg)

I can confirm this worked for me. 
Visual studio code v1.64.2
Vetur v0.35.0
Vue 3.2.29

**Comment by twknab** [comment]
Just wanted to add that in addition to updating `tsconfig.json` as described here, I also had to create a `shims-vue.d.ts` file (per [StackOverflow thread](https://stackoverflow.com/a/64213710/6685623)) and place it in my root Vue directory.

Here's the contents of the file:

```typescript
declare module "*.vue" {
  import type { DefineComponent } from "vue";
  const component: DefineComponent<
    Record<string, unknown>,
    Record<string, unknown>,
    unknown
  >;
  export default component;
}
```
🥲
