### ISSUE TITLE
Using VScode, workspace mode only can recognized the first project' s tsconfig.json

### ISSUE THREAD

**Issue by CALMorACT** [vuejs/vetur#2888]
- [√] I have searched through existing issues
- [√] I have read through [docs](https://vuejs.github.io/vetur)
- [√] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [√] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: 
- Vetur version: 0.33.1
- VS Code version: 1.55.2

## Problem

![image](https://user-images.githubusercontent.com/46255829/116037384-97fc4980-a69a-11eb-8a75-1d0c163db1d2.png)
![image](https://user-images.githubusercontent.com/46255829/116037578-dd207b80-a69a-11eb-9d95-b40079763b24.png)

## Reproducible Case

When use WorkSpace mode and the project is not first in left files list

**Comment by yoyo930021** [comment]
Please use monorepo settings.
https://vuejs.github.io/vetur/guide/setup.html#advanced
