### ISSUE TITLE
Ability to sort: data, components & methods properties

### ISSUE THREAD

**Issue by RanjeetEppa18** [vuejs/vetur#2896]
## Feature Request
This is a feature request for: Sorting `data` `methods` and `components`  properties;

**Comment by IWANABETHATGUY** [comment]
this feature should processed by `vue-eslint-plugin` or prettier

**Comment by yoyo930021** [comment]
https://eslint.vuejs.org/rules/order-in-components.html#vue-order-in-components
https://eslint.vuejs.org/rules/sort-keys.html#vue-sort-keys

**Comment by RanjeetEppa18** [comment]
Thanks for the information! @yoyo930021
