### ISSUE TITLE
[Vue 3] Support nullable Function props

### ISSUE THREAD

**Issue by AverageHelper** [vuejs/vetur#2898]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: macOS
- Vetur version: 0.33.1
- VS Code version: 1.55.2

## Problem

> Conversion of type '`FunctionConstructor`' to type '`PropType<OnSelectCallback | null>`' may be a mistake because neither type sufficiently overlaps with the other.

![Screen Shot 2021-04-28 at 8 35 58 AM](https://user-images.githubusercontent.com/1500092/116422217-c42fdb80-a7fc-11eb-9098-2fb8ddf680ef.png)

## Reproducible Case

https://github.com/AverageHelper/prop-type-function-or-null

* Set `"strict": true` in the tsconfig that manages the vue file in question.
* Create a function callback signature type to use as a prop type
* Add a prop whose type is `Function` and default is `null`
* Augment the function type with a `PropType` that includes your custom callback signature and `null`
* Observe error

**Comment by AverageHelper** [comment]
This issue only occurs when the `PropType` annotation contains `null`. Vetur takes a normal function signature there just fine.

Since other prop types allow being augmented with `null`, and Vue has supported adding function signatures to props since [#9692](https://github.com/vuejs/vue/issues/9692#issue-420446580), I'm fairly certain this syntax _should_ work.

Nullable function props are useful over events in the case where a component should behave differently based on the existence of a callback function. For example, a component may in some contexts be interactive, perhaps indicating in its UI that it is interactive, and calling a callback function passed by its parent component. In other contexts, the same component may only display data, but formatted in the same manner as the interactive version. I don't know a way to have a component check that its parent component handles an event, so function props have been a good way for us to make that check.

**Comment by yoyo930021** [comment]
It's problem in vue 3 TypeScript type information.
Please report to vue-next project

**Comment by AverageHelper** [comment]
Issue been reported at [vue-next#3760](https://github.com/vuejs/vue-next/issues/3760).
