### ISSUE TITLE
Vetur cannot recongize semantic highlight

### ISSUE THREAD

**Issue by libgcc** [vuejs/vetur#2899]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: 
- Vetur version:v0.31.3
- VS Code version:1.49

## Problem
I setup my semantic highlight like this: 
   
```
 "editor.semanticHighlighting.enabled": true,
    // Overrides editor semantic token color and styles from the currently selected color theme.
    "editor.semanticTokenColorCustomizations": {
        "enabled": true,
        "rules": {
            "parameter": {
                "foreground": "#BC8AFF"
            },

        }
    },
```
for the purple paramter highlight. Both js and ts file accept the setting and show as expect: 
![js](https://user-images.githubusercontent.com/2680469/116435442-ed448080-a87d-11eb-9f6c-6ea1244b67ae.jpg)
![ts](https://user-images.githubusercontent.com/2680469/116435457-f2093480-a87d-11eb-8c65-8745f8cf2fcc.jpg)

But the vue file dosen't take it. With inspection no semantic  token type is detected:
![vue](https://user-images.githubusercontent.com/2680469/116435630-267cf080-a87e-11eb-9ebf-5abb3fb5cd3b.jpg)

Reinstall Vetur extension cannot fix this problem, I've tried several time. Any ideas?

**Comment by yoyo930021** [comment]
Fixed in #2802
