### ISSUE TITLE
Eslint autofix not working after upgrading 0.7.0 -> 0.8.6

### ISSUE THREAD

**Issue by ugros** [vuejs/vetur#290]
After upgrading from eslint 0.7.0 to 0.8.6, eslint autofix has stopped working.

- Platform: Win64
- Vetur version: 0.8.6
- VSCode version: 1.13.1

I'm using latest eslint plugin extension. Here's my eslint config (that was working perfectly before):

```
{
  "parser": "babel-eslint",
  "env": {
    "browser": true
  },
  "plugins": ["html"],
  "settings": {
    "import/resolver": {
      "webpack": {
        "config": "./webpack.config.js"
      }
    }
  },
  "globals": {
    "module": true,
    "require": true
  },
  "extends": "airbnb-base"
}
```

(showing only parts that might be relevant).

My eslint extension is properly set (vue added to eslint validate).

I do see eslint errors, but I can't autofix them (either using eslint extension autofix on save or a keybinding).

Even tho I like newest features a lot, this is a huge regression for me and eslint autofix is a killer feature that I can't live with.

Please look into it. Thanks a lot!

**Comment by WalterZou** [comment]
config as this may help:
```
"eslint.validate": [
    "javascript",
    "javascriptreact",
    {
      "language": "vue",
      "autoFix": true
    },
    {
      "language": "html",
      "autoFix": true
    }
  ],
```

**Comment by WalterZou** [comment]
But, `emmet` not work with the latest `Vetur:0.8.6` , even if i disabled `userNewEmmet`

**Comment by octref** [comment]
@WalterZou The old emmet is working for me in 0.8.6. If you can't get it to work consider open an issue with repro steps.

**Comment by octref** [comment]
@ugros It's still working for me in https://github.com/vuejs-templates/webpack. Can you try if it works for you? If not try modifying the webpack template so it reproduces the error, and put that project on GitHub.

**Comment by ugros** [comment]
Hello,

This issue no longer appears in latest version.
Anyway, I had everything setup up properly (including eslint autofix option for vue/html files).

I guess we can close this issue.
