### ISSUE TITLE
lang="javascript" on an editor component

### ISSUE THREAD

**Issue by vvpvvp** [vuejs/vetur#293]
## Info

- Platform: macOS
- Vetur version: 0.8.6
- VSCode version: 1.13.1

## Problem
when I add ` lang="javascript"` on `<editor>` component,  and there is many confusion errors .

<img width="818" alt="2017-06-27 15 56 32" src="https://user-images.githubusercontent.com/7303371/27576923-52fc40d0-5b51-11e7-83b6-c747c1d938b7.png">

**Comment by HerringtonDarkholme** [comment]
Hi, I cannot reproduce this if I add `lang="javascript"` to `script` block.

I guess you are adding it to `template` block. So html tags are parsed as JSX, which are invalid of course.

**Comment by octref** [comment]
@HerringtonDarkholme Think he meant the `lang="javascript"` on the `<editor>` component.
