### ISSUE TITLE
Property 'token' does not exist on type '{ token: { readonly value: string; } }‘

### ISSUE THREAD

**Issue by mashirozx** [vuejs/vetur#2951]
- [x] I have searched through existing issues
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Linux
- Vetur version: v0.33.1
- VS Code version: 1.56.2

## Problem

![image](https://user-images.githubusercontent.com/16148054/119246150-c5f97e80-bbb1-11eb-85cd-9422ee0d5264.png)

## Reproducible Case
A normal Typescript function, I just don't know what's wrong on that...
![image](https://user-images.githubusercontent.com/16148054/119246189-0fe26480-bbb2-11eb-9f46-8174af51b007.png)

**Comment by yoyo930021** [comment]
Please provide a repro case.
Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md.
