### ISSUE TITLE
Vue3 + Vite:  Syntax highlighting

### ISSUE THREAD

**Issue by Marimax01** [vuejs/vetur#2960]
- [x] I have searched through existing issues

## Feature Request

Hello,

I use vue3 with Vite, I added [vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages) which allows me to generate my router automatically, however the following feature [sfc-custom-block-for-route-data](https://github.com/hannoeru/vite-plugin-pages#sfc-custom-block-for-route-data) has no syntax highlighting.

Would it be possible to add it?

**Comment by yoyo930021** [comment]
Use it.
https://vuejs.github.io/vetur/guide/highlighting.html#custom-block

**Comment by Marimax01** [comment]
Thanks, I didn't know this feature.
