### ISSUE TITLE
Highlight problem on the latest version

### ISSUE THREAD

**Issue by owalid** [vuejs/vetur#2989]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: macOS
- Vetur version: 0.34.1
- VS Code version: 1.56.2

## Problem

Hello !

My vetur on my vscode doesn't color the code of my javascript part as it should.
This since the last version.
When I switch to version 0.33.1 I have no problem but with the current version I lose the usual javascrip colorization.

I use the theme "Material Theme Ocean High Contrast".
I put you an example:
![0 34 1](https://user-images.githubusercontent.com/28403617/121208891-b39e6680-c87a-11eb-8fd1-57d4bb955a18.png)
![0 33 1](https://user-images.githubusercontent.com/28403617/121208907-b600c080-c87a-11eb-9cf0-92d0fd5965f7.png)

## Reproducible Case

Download [Material theme]( https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme)
Switch between version 0.33.1 and version 0.34.1

**Comment by jasonlyu123** [comment]
This is probably because of the new semantic highlights feature. If you don't like it, you can disable it with the `vetur.languageFeatures.semanticTokens` config
