### ISSUE TITLE
What‘s wrong？

### ISSUE THREAD

**Issue by Myluckygirl** [vuejs/vetur#2991]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [ ] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: 
- Vetur version:
- VS Code version:

## Reproducible Case

![image](https://user-images.githubusercontent.com/22091749/121328720-2543e680-c947-11eb-875e-35c0e157b2d2.png)
![image](https://user-images.githubusercontent.com/22091749/121328738-2bd25e00-c947-11eb-9f3a-cd6020ab3a27.png)

Why?

**Comment by leopiccionia** [comment]
Are you using `jsconfig.json`/`tsconfig.json`, as documented [here](https://vuejs.github.io/vetur/guide/setup.html#path-mapping)?

**Comment by triforcely** [comment]
@Myluckygirl If you configure paths mappings set in tsconfig.json should be correctly understood by the extension. Try (of course alongside your configuration).
```json
{
    "compilerOptions": {
        "paths": {
            "@/*": ["src/*"]
        }
    }
}
```

**Comment by yoyo930021** [comment]
Just answer from @travisboss @leopiccionia .
