### ISSUE TITLE
Don't require key with v-for on template tags

### ISSUE THREAD

**Issue by Smith-Curise** [vuejs/vetur#300]
- [X] I searched through existing issues.
- [X] I have looked through docs at https://octref.github.io/vetur/

## Info

- Platform: Win
- Vetur version:  0.8.6
- VSCode version: 1.13.1

## Problem

![image](https://user-images.githubusercontent.com/18729228/27642353-1f7d3f4c-5c51-11e7-9fb9-64d8ace61bf3.png)

**According to vue document, `template` tags don't need key, but `vetur` still need to add key.**

![image](https://user-images.githubusercontent.com/18729228/27642260-ceda0f7a-5c50-11e7-8cff-20a57d931ebf.png)

**Comment by octref** [comment]
>  I searched through existing issues.

Have you?

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/27652978-edcffcae-5c3d-11e7-9b68-bfc7da033b8f.png)
