### ISSUE TITLE
when using vue3 and use v-model to bind to component: vetur show misses props: model-value

### ISSUE THREAD

**Issue by blesstosam** [vuejs/vetur#3007]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform:  macOs
- Vetur version: 0.34.1
- VS Code version: 1.57.0

## Problem

 {componentName} misses props: model-value

<img width="706" alt="WX20210615-090429@2x" src="https://user-images.githubusercontent.com/26403700/121977517-c8b65080-cdb8-11eb-9ee4-d7b4722541e5.png">

**Comment by yoyo930021** [comment]
Please check https://vuejs.github.io/vetur/guide/FAQ.html#vetur-can-t-find-package-json-in-xxxx-xxxxxx

If Vetur read correct `package.json` file in project, Vetur will use `model-value` in vue3 project.

**Comment by blesstosam** [comment]
@yoyo930021 thanks!
