### ISSUE TITLE
How to disabled line for VTI or VLS

### ISSUE THREAD

**Issue by IndexXuan** [vuejs/vetur#3010]
- [x] I have searched through existing issues

## Feature Request

Vue 2.x does not support v-slot types, It means when we use VTI or VLS with scale real-world project, it is results lots of errors which is mostly not errors.

for example: in CI, we cannot check it one-by-one, in [vite-plugin-checker](https://github.com/fi3ework/vite-plugin-checker/issues/1), it will always showup in browser overlay.

Recommended syntax: something like @ts-ignore or @ts-expect-error for vue, also like volar supported(or not) vue-ignore ? especially in vue template.

Thanks very much.

**Comment by hexf00** [comment]
I also want to know the answer, the type of scope parameter is deduced as ` vnode [] | undefined`, this makes volar unable to work in vue2.

https://github.com/johnsoncodehk/volar/pull/750#issuecomment-1023947885
