### ISSUE TITLE
Organize Imports works error

### ISSUE THREAD

**Issue by qq326943819** [vuejs/vetur#3020]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Win
- Vetur version:0.34.1
- VS Code version:1.57.1

## Problem
The imports will move to the first line by use it , e.g.

![](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-e76a802d-e9c2-4118-983e-0bb881f11e09/f00d7d15-db74-4825-a949-141a241993cf.gif)

**Comment by chrisreedio** [comment]
I'm running into the same thing.

**Comment by JUST-Limbo** [comment]
running into the same problem...
