### ISSUE TITLE
got an error in terminal  with provider FAILED  , Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by IOLOII** [vuejs/vetur#3047]
- [ x ] I have searched through existing issues
- [ x ] I have read through [docs](https://vuejs.github.io/vetur)
- [ x ] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [ x ] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: windows 10
- Vetur version: 0.34.1
- VS Code version: 1.57.0   system setup

## Problem
```sh
[2021-07-04 21:49:51.482] [exthost] [error] [octref.vetur] provider FAILED
[2021-07-04 21:49:51.482] [exthost] [error] Error: Request textDocument/semanticTokens/full failed with message: Cannot read property 'flags' of undefined
    at c:\Users\yuey\.vscode\extensions\octref.vetur-0.34.1\dist\vueMain.js:1:64858
    at c:\Users\yuey\.vscode\extensions\octref.vetur-0.34.1\dist\vueMain.js:1:65153
    at Immediate.<anonymous> (c:\Users\yuey\.vscode\extensions\octref.vetur-0.34.1\dist\vueMain.js:1:65518)
    at processImmediate (internal/timers.js:461:21)
```
## Reproducible Case

i dont know how to reappeared in this error , just install and use it long time,recently go some error with vscode  is could't  paste txt in vscode  ,It takes a long time  , then i open extensions terminal ,see error with "Vetur can't find package.json in /xxxx/xxxxxx."  I solved the problem according to the solution, but I still have this problem. I can't solve it, so let's ask a Issue.

thanks

**Comment by nyancodeid** [comment]
I have the same problem, and I try to figure out what's make Vetur error. I scroll up and down, the error message keeps going out on Output Extension. I think there is a problem with my code or having invalid syntax on it (no error showed up on VS Code / Linting).

And I found the problem is coming from `optional chaining` syntax. And then I remove it. Voila, the Vetur error message does not show up again. And now it's working normally.

**Comment by yoyo930021** [comment]
@IOLOII Which typescript version is in your project?

**Comment by yoyo930021** [comment]
> i got this output in my current version vscode
> 
> ```
> Vetur initialized
> [INFO ] Find node_modules paths in d:\program\workspace\Dado\trip_user_ui _cj_branch - 3198ms
> [INFO ] Loaded bundled typescript@4.3.2.
> [INFO ] Loaded bundled prettier.
> [INFO ] Loaded bundled @starptech/prettyhtml.
> [INFO ] Loaded bundled prettier-eslint.
> [INFO ] Loaded bundled prettier-tslint.
> [INFO ] Loaded bundled stylus-supremacy.
> [INFO ] Loaded bundled @prettier/plugin-pug.
> [Error - 下午3:32:38] Request textDocument/semanticTokens/full failed.
>   Message: Request textDocument/semanticTokens/full failed with message: Cannot read property 'flags' of undefined
>   Code: -32603 
> [INFO ] update d:\program***\src\plugins\api\index.js in ts language service.
> ```
> 
> vscode version: ![image](https://user-images.githubusercontent.com/34856171/136520337-0df652d2-4d87-487f-8c4b-bb4770c3f865.png)
> 
> plugin version: ![image](https://user-images.githubusercontent.com/34856171/136520475-bce2e23d-7743-4b62-ad61-241632d98857.png)
> 
> this problem has long time no see, i don't know how to reappear，so if it happend , i will tell you , thanks for your reply

Please test v0.35.0 version.

**Comment by IOLOII** [comment]
> > i got this output in my current version vscode
> 
> > 
> 
> > ```
> 
> > Vetur initialized
> 
> > [INFO ] Find node_modules paths in d:\program\workspace\Dado\trip_user_ui _cj_branch - 3198ms
> 
> > [INFO ] Loaded bundled typescript@4.3.2.
> 
> > [INFO ] Loaded bundled prettier.
> 
> > [INFO ] Loaded bundled @starptech/prettyhtml.
> 
> > [INFO ] Loaded bundled prettier-eslint.
> 
> > [INFO ] Loaded bundled prettier-tslint.
> 
> > [INFO ] Loaded bundled stylus-supremacy.
> 
> > [INFO ] Loaded bundled @prettier/plugin-pug.
> 
> > [Error - 下午3:32:38] Request textDocument/semanticTokens/full failed.
> 
> >   Message: Request textDocument/semanticTokens/full failed with message: Cannot read property 'flags' of undefined
> 
> >   Code: -32603 
> 
> > [INFO ] update d:\program***\src\plugins\api\index.js in ts language service.
> 
> > ```
> 
> > 
> 
> > vscode version: ![image](https://user-images.githubusercontent.com/34856171/136520337-0df652d2-4d87-487f-8c4b-bb4770c3f865.png)
> 
> > 
> 
> > plugin version: ![image](https://user-images.githubusercontent.com/34856171/136520475-bce2e23d-7743-4b62-ad61-241632d98857.png)
> 
> > 
> 
> > this problem has long time no see, i don't know how to reappear，so if it happend , i will tell you , thanks for your reply
> 
> 
> 
> Please test v0.35.0 version.

OK

**Comment by zsmithjc** [comment]
Hi, I'm still getting this error in Vetur 0.35.0.
TypeScript 4.4.

![Screen Shot 2021-12-29 at 3 27 31 PM](https://user-images.githubusercontent.com/96127382/147700927-09576b00-fc34-484f-a5e8-c62c535ba3a9.png)

**Comment by zsmithjc** [comment]
Hi, I'm still getting this error when starting up Vetur.
Vetur version 0.35.0
TS version 4.4
![image](https://user-images.githubusercontent.com/96127382/147701115-2f52da58-c816-422e-a5df-1eb98abd3a00.png)

**Comment by BrightTan** [comment]
> Hi, I'm still getting this error when starting up Vetur. Vetur version 0.35.0 TS version 4.4 Is this something breaking or anything I need to be worrying about? ![image](https://user-images.githubusercontent.com/96127382/147701115-2f52da58-c816-422e-a5df-1eb98abd3a00.png)
me too.

**Comment by IOLOII** [comment]
> > Hi, I'm still getting this error when starting up Vetur. Vetur version 0.35.0 TS version 4.4 Is this something breaking or anything I need to be worrying about? ![image](https://user-images.githubusercontent.com/96127382/147701115-2f52da58-c816-422e-a5df-1eb98abd3a00.png)
> > me too.

In my experience，it affect your your coding, so just type code , do not pay attention to this error report.
If you try to format code , but not formated, you can see this logs, may be some tags has no ending tag, jsut this
