### ISSUE TITLE
Vetur does not recognize "import type" as different from "import"

### ISSUE THREAD

**Issue by dospunk** [vuejs/vetur#3059]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Windows 10
- Vetur version: v0.34.1
- VS Code version: 1.58.1

## Problem

line 8 shows `'storeType' is declared but its value is never read.Vetur(6133)` when hovered over and line 13 shows ` 'storeType' refers to a value, but is being used as a type here. Did you mean 'typeof storeType'?Vetur(2749)` when "storeType" is hovered over
![vetur error](https://user-images.githubusercontent.com/7871432/125665007-1735b764-19e3-49e5-8eab-f04fe7586cb4.PNG)

store.ts contains
```ts
export const store = {
	thing: 1,
	otherThing: 2,
	yabadaba: 'doo'
}
```

I have set vetur.useWorkspaceDependencies to true but this hasn't made a difference 

## Reproducible Case

https://github.com/dospunk/vetur-import-type-error

**Comment by yoyo930021** [comment]
What is your `vetur.format.defaultFormatter.html` option value?
https://vuejs.github.io/vetur/guide/formatting.html#formatters

**Comment by yoyo930021** [comment]
I think you have some misunderstand for `import type`.

It isn't work in typescript file too.
<img width="257" alt="截圖 2021-08-06 下午9 35 26" src="https://user-images.githubusercontent.com/9126398/128518679-ef2e5b8b-921f-42d8-8f9b-2fcf7d6f3018.png">
<img width="719" alt="截圖 2021-08-06 下午9 35 22" src="https://user-images.githubusercontent.com/9126398/128518666-1fdf3a74-64bd-4a09-9906-4e12d1dd23bd.png">

**Comment by dospunk** [comment]
Yup, you're right. Sorry for that!
