### ISSUE TITLE
Template interpolation not recognizing Vue prototype properties from external file

### ISSUE THREAD

**Issue by elias123tre** [vuejs/vetur#3068]
- [x] I have searched through existing issues

## Info

- Platform: Win
- Vetur version: 0.34.1
- VS Code version: 1.58.2
- Edit: This is on a fresh installation of VS Code, Vetur and node/npm

## Problem

![image](https://user-images.githubusercontent.com/18127101/126042133-3b0ea261-c2e2-4a73-a6cd-587adebc10a4.png)

Output panel -> Vue Language Server does not contain any errors

## Reproducible Case

In VS Code with template interpolation enabled:

1. Create blank project with Vue CLI 4.5.13 (Use vue 2 with defaults): `vue create my-app`
2. Change line 2 in `src/App.vue` to `<div id="app" :title="$test">`
3. Add `Vue.prototype.$test = "Lorem ipsum"` after line 4 in `src/main.js`
4. Error squiggly appears: `Property '$test' does not exist on type 'CombinedVueInstance<Record<never, any> & Vue, object, object, object, Record<never, any>>'.`

**Comment by rchl** [comment]
This can't be done automatically. You need to extend the types: https://vuejs.org/v2/guide/typescript.html#Augmenting-Types-for-Use-with-Plugins

**Comment by elias123tre** [comment]
Okay. I found a similar answer when searching telling the same thing and I got it working. Is there any way, however, to do it in pure JavaScript with a jsdoc comment for example? I had a similar issue with computed and a jsdoc comment solved, maybe it can be done here too. I prefer keeping typescript out of the project if the whole thing isn't written in ts.

**Comment by rchl** [comment]
You need to use typescript type definition files for this.
