### ISSUE TITLE
VS Code cannot go to definition.

### ISSUE THREAD

**Issue by tazaraz** [vuejs/vetur#3070]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: macOS 10.13.6
- Vetur version: v0.34.1
- VS Code version: 
```
Version: 1.58.2 (Universal)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:09:06.581Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 17.7.0
```

## Problem
Issue also exists in [#1873](https://github.com/vuejs/vetur/issues/1873), but I cannot reply to it as it is locked.

VS Code is unable to go to definitions of user created functions or components. This however does work when using plain Vue, leading me to believe it is a Nuxt specific problem. 

The error is as follows: Unable to open 'vue-editor-bridge.ts': Unable to read file '/vue-temp/vue-editor-bridge.ts' (Error: Unable to resolve non-existing file '/vue-temp/vue-editor-bridge.ts').

Noteworthy is that clicking the closing part of a component (when it consists of an `<Tag>` and `</Tag>`), the cmd+click does nothing, and the right-click -> "Go to definition" results in a popup saying "No definition found for 'Tag'", while on the opening tag the error above occurs, whether it be by cmd+click or right-click.

## Reproducible Case
  - Use `npx create-nuxt-app` with TypeScript
  - Add `"vetur.experimental.templateInterpolationService": true` in your `settings.json`
  - Go to the 'pages/index.vue' and (in my case) cmd+click  `<Tutorial/>`
  - Error will pop up in the lower right corner

## Remarks and a possible but dirty solution
The problem seems to be that Vetur does not know Nuxt will include them automatically, and thus does not include the components necessary for autocompletion. This is odd, considering that typing `Tag`, will show a dropdown menu containing `tag` as suggestion together with the description containing the abolute path to the according `Tag.vue` file, but hitting "enter" does not import the definitions of `Tag`.

When adding them manually with a `import Tag from '@/components/Tag.vue'` and specifying it as a component, this definition error is resolved (for me that is) and cmd+click works once again. It might be a quick but dirty way to resolve the problem by automating this. It does defeat the whole "Nuxt automatically includes your components for you", while having your autocompletion importing it anyways. 

It also is a hassle to implement, as I can already think of two different implementation of components:
```typescript
import Tag from '@/components/Tag.vue';
export default Vue.extend({
    components:{
        Tag
    }
})
```
OR
```typescript
import Tag from '@/components/Tag.vue';
@Component({
    components:{
        Tag
    }
})
export default class Tag extends Vue {...}
```

**Comment by devilstars** [comment]
Same issue, vetur simply does not work with nuxt. In my case it's a "no typescript" installation.

![2021-07-22_090821](https://user-images.githubusercontent.com/12907959/126596345-276a9959-0b7b-4ffc-9ab5-892abfdeee06.jpg)

**Comment by Ledvis** [comment]
The same happens in a **quasar** framework (not `typescript`). Although it works great in projects created from **vue-cli**

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/24472685/136645835-bb6adfc5-a14e-4d7e-bb78-fd337a4e1bf7.png">

**Comment by yoyo930021** [comment]
Vetur doesn't know what components are global ?
Please talk to vetur in config. Doc: https://vuejs.github.io/vetur/guide/global-components.html#example
Example by create-nuxt-app:
```vetur.config.js
module.exports = {
  projects: [
    { root: './', globalComponents: ['./components/**/*.vue'] }
  ]
};
```
Welcome to contribute document for nuxt.

**Comment by tazaraz** [comment]
> Vetur doesn't know what components are global ? Please talk to vetur in config. Doc: https://vuejs.github.io/vetur/guide/global-components.html#example Example by create-nuxt-app:
> 
> ```js
> module.exports = {
>   projects: [
>     { root: './', globalComponents: ['./components/**/*.vue'] }
>   ]
> };
> ```
> 
> Welcome to contribute document for nuxt.

That does fix the issue. It would however be usefull if the error indicated that one is supposed to do this.
