### ISSUE TITLE
go to definition don't work in 0.34.1

### ISSUE THREAD

**Issue by chaosforfun** [vuejs/vetur#3083]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: macOS
- Vetur version: v0.34.1
- VS Code version:1.58.2

## Problem

go to definition don't work, and report a error:
![image](https://user-images.githubusercontent.com/2226267/128115042-ecdd1c7d-32b1-456a-a7b8-7c180ee7cd79.png)
![image](https://user-images.githubusercontent.com/2226267/128115055-9fc311a8-23e7-4760-a83c-aecd2bd6012d.png)

here is some log:
    
    [Trace - 10:47:14 AM] Received response 'textDocument/definition - (359)' in 3ms.
    Result: [
        {
            "uri": "file:///file%3A///Volumes/work/AQProject/Monitor/src/pub/receiver/receiver.vue",
            "range": {
                "start": {
                    "line": 5,
                    "character": 30
                },
                "end": {
                    "line": 5,
                    "character": 34
                }
            }
        }
    ]

**Comment by yoyo930021** [comment]
Please provide a repro case.
https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md
