### ISSUE TITLE
Question: Is it possible to show warning if I forgot to add lang="ts" to script tag in some vue file?

### ISSUE THREAD

**Issue by ppasieka** [vuejs/vetur#309]
Is it possible to show warning if I forgot to add lang="ts" to script tag in some vue file? For example in project where all vue files should be compiled by Typescript.

Maybe as a setting for workspace?

I'm asking because I just spent 3h trying to find what is a cause of
```
Object literal may only specify known properties, and 'components' does not exist in type 'AsyncComponent'.
```

and I found that after scaffolding vue file (with scaffold snippet) I forgot to add lang="ts" to script tag

**Comment by octref** [comment]
Not really. I was thinking maybe adding a `vetur.scaffold.templateLang` etc for scaffolding but feel that's a bit unnecessary, and I don't like having too much options.

**Comment by ppasieka** [comment]
Ok. I understand
