### ISSUE TITLE
Support Vue 3.2 - <script setup>

### ISSUE THREAD

**Issue by jzs11** [vuejs/vetur#3105]
## Feature Request

In Vue 3.2, we could use <script setup> as a compile-time syntactic sugar - https://v3.vuejs.org/api/sfc-script-setup.html#basic-syntax

In the following screenshot, LeftPanel, Breadcrumb and onClick are all consumed by the template, could we manage to support this feature? 
![image](https://user-images.githubusercontent.com/2770401/128975637-4fffffcc-79db-4233-b997-ea1e21d9008a.png)

**Comment by wangz-code** [comment]
支持了吗?
