### ISSUE TITLE
Support the <script setup> syntax in SFCs

### ISSUE THREAD

**Issue by dsine-de** [vuejs/vetur#3108]
## Feature Request

See https://v3.vuejs.org/api/sfc-script-setup.html

Currently there are no errors with the new `<script setup>` syntax, but variables defined in the script are displayed (e.g. component imports, computed etc.) as dimmed when they are never read in the script itself, because you don't have to `return` them with this syntax and there is a tooltip `<variable> is declared but its value is never read. Vetur(6133)`.

**Comment by zs-g** [comment]
I also encountered the same problem

**Comment by Gumper-x** [comment]
I have the same problem

**Comment by Azema4ka** [comment]
I also encountered the same problem

**Comment by lupas** [comment]
see also https://github.com/vuejs/vetur/issues/2296

**Comment by SKFrozenCloud** [comment]
I also get ```Module '"mycomponent.vue"' has no default export.```

**Comment by yoyo930021** [comment]
Duplicate of #2296
