### ISSUE TITLE
No default export while using setup sugar

### ISSUE THREAD

**Issue by wiketool** [vuejs/vetur#3116]
- [x] I have searched through existing issues
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Windows 10 Professional Edition 20H2 x64
- Vetur version:v0.34.1
- VS Code version:1.59.0
- Node.js version:14.16.0

## Problem

I used `setup sugar` in my code,then `Vetur` report error `Module xxx has no default export`

## Reproducible Case

**HelloWorld.vue**
```javascript
...
<script lang="ts" setup>
import { ref } from 'vue'

defineProps({
  msg: {
    type: String,
    required: true,
  },
})

const count = ref(0)
</script>
...
```

**Home.vue**
```javascript
...
<script lang="ts">
...

/*The following line is where error report*/
import HelloWorld from '@/components/HelloWorld.vue' 

...
</script>
...
```

**Comment by coderlfm** [comment]
I had the same problem

**Comment by nevermore1000** [comment]
I had the same problem

**Comment by nopeless** [comment]
same problem here as well

**Comment by ZangYuSong** [comment]
I had the same problem

**Comment by yoyo930021** [comment]
Duplicate of #2296
