### ISSUE TITLE
Vetur with external html

### ISSUE THREAD

**Issue by askeet** [vuejs/vetur#3118]
- [x ] I have searched through existing issues
- [ x] I have read through [docs](https://vuejs.github.io/vetur)
- [ x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [ x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: 
 Windows 10
- Vetur version:
0.34.1
- VS Code version:
1.59.0
## Problem
Vetur works fine with SPA file, however when I am trying to split files on vue, html and scss  it doesn't any see variables in the .html 

settings.json 
```
{
  "editor.formatOnSaveMode": "file",
  "editor.formatOnSave": true,
  "htmlhint.options": {
    "doctype-first": false
  },
  "prettier.disableLanguages": ["html"],
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "[html]": {
    "editor.defaultFormatter": "HookyQR.beautify"
  },
  "eslint.alwaysShowStatus": true,
  "typescript.tsdk": "node_modules\\typescript\\lib",
  "vetur.experimental.templateInterpolationService": true,
  "emmet.includeLanguages": {
    "vue-html": "html"
  },
  "[vue]": {
    "gitlens.codeLens.scopes": ["document"]
  },
  "vue3snippets.vueIndentScriptAndStyle": true
}
```

Vue file 

```
<style scoped lang="scss" src=".\myfile.scss"></style>
<template src=".\myfile.html"></template>
<script>
export default {
  name: 'myfile',
  data() {
    return {
      test: { str1: 'Hello world' }
    };
  }
};

<script>
```

HTML 

```
<div >
 {{ test.str1  }}
</div>
```

**Comment by yoyo930021** [comment]
You can refer https://github.com/vuejs/vetur/issues/2471

**Comment by yoyo930021** [comment]
Duplicate of #2471
