### ISSUE TITLE
Support code folding in custom block if lang is defined on the block

### ISSUE THREAD

**Issue by mrleblanc101** [vuejs/vetur#3119]
- [x] I have searched through existing issues

## Feature Request

I use vue-i18n-loading which create a `<i18n></i18n>` custom block in the SFC.
Currently I cannot use code folding inside this block even if it's just regular JSON.
The lang is defined on the block just like for `<script>` and `<style>` but the default is JSON.
`<i18n lang="json">` or `<i18n lang="yaml">` are both valid. 
<img width="388" alt="Capture d’écran, le 2021-08-18 à 17 33 58" src="https://user-images.githubusercontent.com/17392251/129975252-0d618298-5dc2-4610-9f2c-0528d2f1985e.png">
<img width="378" alt="Capture d’écran, le 2021-08-18 à 17 34 53" src="https://user-images.githubusercontent.com/17392251/129975376-103cb995-0e46-411a-8287-28badb9873ad.png">

**Comment by mrleblanc101** [comment]
Maybe the issue come from somewhere else as code folding seem to work when I do `> Developper: Reload windows` but disappear after a few seconds.

**Comment by yoyo930021** [comment]
We can't support this feature in other language for vetur.
If you want traditional behavior, https://github.com/vuejs/vetur/issues/2308#issuecomment-760721567

**Comment by mrleblanc101** [comment]
I dont understand why it work for SCSS then.

**Comment by yoyo930021** [comment]
> I dont understand why it work for SCSS then.

We have built-in SCSS feature in vetur for Vue SFC.

**Comment by mrleblanc101** [comment]
But why not for JSON, pug, stylus and less ? All of these are supported by Vue.
Why only SCSS ?

**Comment by yoyo930021** [comment]
> But why not for JSON, pug, stylus and LESS ? All of these are supported by Vue. Why only SCSS ? These other language are also very common

We only support languages in doc.
https://vuejs.github.io/vetur/guide/intellisense.html#template

We don't have any time to maintaining other languages.
In fact, we don't even have good support for existing languages.
I'm welcome any PR for this.

**Comment by mrleblanc101** [comment]
I'm not sure I understand, the code folding is natively supported by VS Code, don't you just provide the scope so VS Code know how to handle the folding ?
Since the `lang` is provided in my exemple, can't you just provide it for all custom block so VS Code can handle it correctly ? 
VS Code already does code folding for `json` and `yaml`

**Comment by mrleblanc101** [comment]
From what I can see, Vetur already expose `<i18n>` custom block as `json` and the syntax highlighting is already working.
Why would code folding for JSON explicitly not be supported ? Can't we reopen as a feature request ? Why was this closed ?

**Comment by yoyo930021** [comment]
> I'm not sure I understand. The code folding is handled natively by VS Code, don't you just provide the scope so VS Code know which language server to use ? Since the `lang` attribute is provided in my exemple, can't you just provide it for all custom block so VS Code can handle it correctly ? VS Code already does code folding for `json` and `yaml`

You can refer this.
https://github.com/vuejs/vetur/issues/2234#issuecomment-687123329

**Comment by mrleblanc101** [comment]
I'm not sure I understand. This issue has a PR that seem would fix this issue, but it seem like it got reverted.
I see no resolution in the ticket.

**Comment by mrleblanc101** [comment]
Wait 🤔 It work on my personal machine but not on my work marchine...
Which is weird because I use setting sync so they are identica
![2021-10-04 22 56 34](https://user-images.githubusercontent.com/17392251/135953027-2527d724-76c9-41c5-b214-290d4d17dcff.gif)
l.

**Comment by yoyo930021** [comment]
In the past, the code folding is from vscode built-in for indentation.
but we need advanced code folding, so we use code folding from LSP folding. https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_foldingRange

When using LSP folding, vscode built-in will disable.
You only can `"editor.foldingStrategy": "indentation"` for toggle to vscode built-in folding.

Otherwise, you will have to add the language LSP folding. Like HTML `<template>`.
We can't add LSP folding for any language from the custom block.
We will not have enough time to be able to maintain.

Otherwise, you have to use the proxy mechanism, but this is beyond the scope of this plugin.

**Comment by mrleblanc101** [comment]
Weird that it work on my personal machine right now tho 🤔
