### ISSUE TITLE
Links in README pointing to wrong directory

### ISSUE THREAD

**Issue by gekkedev** [vuejs/vetur#3128]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
 - no, not necessary
- [ ] I have tried restarting VS Code or running `Vetur: Restart VLS`
 - no, not necessary

## Problem
Most links in the documentation's [quick start guide](https://github.com/vuejs/vetur/blob/master/docs/guide/Readme.md) seem to point to the wrong directory. If they point to somewhere like `/guide`, they become `/docs/guide`. I.e.
`https://vuejs.github.io/vetur/guide/setup.html#advanced` (correct)
turns into
`https://vuejs.github.io/vetur/docs/guide/setup.html#advanced` (incorrect; 404)
I would have submitted a PR removing the beginning slash but wasn't sure if that would help - in preview mode it just seemed to make the paths relative although they were meant to be absolute.

**Comment by yoyo930021** [comment]
Fixed in https://github.com/vuejs/vetur/pull/3117
