### ISSUE TITLE
"Wi" emmet abbreviation complete "widows"

### ISSUE THREAD

**Issue by samedkucuk** [vuejs/vetur#3143]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Win 
- Vetur version: 0.34.1
- VS Code version: 1.60.0

## Problem
 While writing css of my project always "wi" and "wid" emmet abbreviation complete "widows: |;". I try to fix from Configure user snippet css.json but its not work. Same problem happens in Webstorm to.

![a9JJZ](https://user-images.githubusercontent.com/71490803/132195510-ac005d9a-abc8-446f-9815-aaf99d577c36.jpg)

**Comment by yoyo930021** [comment]
You can try to issue in https://github.com/microsoft/vscode-emmet-helper/issues 
We based on it.
