### ISSUE TITLE
Question: Where I can find 0.8.7 version of a plugin?

### ISSUE THREAD

**Issue by ppasieka** [vuejs/vetur#316]
In this repo ChangeLog has information about changes in 0.8.7 but in marketplace you can find only 0.8.6 version.

![image](https://user-images.githubusercontent.com/2170707/27906211-ea656a30-6242-11e7-83a7-8fd3b45db6aa.png)

**Comment by octref** [comment]
I thought I published it while I went for a coffee -- but apparently it failed. I'm sorry. I'll publish 0.8.8 soon with some more fixes & features.
