### ISSUE TITLE
Look into adopting lerna

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#317]
@HerringtonDarkholme We mentioned this before. Now we have kinda like 3 packages that's becoming messy to maintain.

I've never used lerna before but I'm open to it. Heard it just released 2.0.
What's your opinion?

**Comment by HerringtonDarkholme** [comment]
lerna seems to require all sub-projects listed under `packages`. 

The benefit seems to be

1) reduce duplicate package installation
2) synchronize all cross-dependent packages
3) publish all packages at once

I don't know how much the benefit will be in this repo...

**Comment by octref** [comment]
Let's leave it simple then.
