### ISSUE TITLE
Emmet doesn't work inside <template> tag.

### ISSUE THREAD

**Issue by hajarrashidi** [vuejs/vetur#320]
- [ ] I searched through existing issues.
- [ ] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: 
- Vetur version:
- VSCode version:

## Problem
Emmet is not supported inside <template> tag.
For example:
```
<template>
    <div class="test">
        ul>li*5
    </div>
</template>
```

I am using:
Os: win 10
Editor: VSC: 1.13.1
Vetur 0.9.0
`

**Comment by octref** [comment]
Do you have this setting?

https://vuejs.github.io/vetur/emmet.html

New emmet is not available yet. https://github.com/vuejs/vetur/issues/232

**Comment by hajarrashidi** [comment]
@octref  Thanks for the help. 
So went to **File  > Preference > Settings** and then in the **settings.json** - user settings i added 
```
  "emmet.syntaxProfiles": {
    "vue-html": "html",
    "vue": "html"
  }

```
