### ISSUE TITLE
Vetur stopped working - Unable to pinpoint root cause

### ISSUE THREAD

**Issue by pasteusernamehere** [vuejs/vetur#3226]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Windows (21H1)
- Vetur version: 0.35.0
- VS Code version: 1.62.1

## Problem

Vetur has completely stopped working for me. 

The following commands all result in command not found errors:
 
Vetur: Show Output Channel
Vetur: Restart VLS (Vue Language Server)
Vetur: Show Doctor info

I have tried uninstalling both via the UI and manually wiping the extension folder and the error persists when I reinstall.
I have disabled all extensions except for Vetur and the problem persists.

## Reproducible Case

I can reproduce this on two machines thus far. Both machines have been updated to Windows 21H1. I am going to try to get my hands on a different machine to try before upgrading Windows and see what the before and after looks like. I am putting this out there to see if anyone has seen such issues and if any resolutions are known.

**Comment by pasteusernamehere** [comment]
I tried this on a Windows machine that is running 20H2 and I am getting the same results. I am at a total loss why this started happening. Vetur is essential to my workflow.

**Comment by yoyo930021** [comment]
Can you try to collect LSP log?
https://github.com/vuejs/vetur/wiki/Collecting-LSP-log

**Comment by pasteusernamehere** [comment]
Unfortunately I cannot even get this far, the Vue Language Server does not even appear anymore in the list of output options as it did before.

**Comment by pasteusernamehere** [comment]
I inspected the extension logs and found an issue with my SonarLint extension. I uninstalled SonarLint and Vetur started working again. I reinstalled SonarLint and Vetur continues to work.  Very odd. Issue thankfully resolved. BTW disabling SonarLint didn't help. I had to remove it and add it back.
