### ISSUE TITLE
JSX does not work with lang=ts

### ISSUE THREAD

**Issue by rhyek** [vuejs/vetur#325]
- [x] I searched through existing issues.
- [x] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: Windows 10
- Vetur version: 0.9.0
- VSCode version: 1.13.1

## Problem

JSX does not work with `<script lang="ts">`.

![image](https://user-images.githubusercontent.com/702922/28047432-297c76a2-65a7-11e7-9183-0ef13659181e.png)

**Comment by HerringtonDarkholme** [comment]
One question, how you compile Vue's SFC in tsx format?

As far as I know "appendSuffixTo" option treats script in SFC as  `ts` not `tsx`.

**Comment by HerringtonDarkholme** [comment]
After several investigation, I think there is no much chance that we will support this.

1) There is no known method to use SFC with tsx with tsloader/atl. I wonder how you compile your project.

2) in JS code, TSC simply suppress the error. In fact, no `JSX` namespace is provided unless you manually installed React typing or  Vue-tsx typing.

3) We need new TypeScript definition for `ElementAttributesProperty`. This require Vue2.4 release.  Other libraries only have insufficient experiments.

4) Even if Vue2.4 is released, vue's jsx is different from React JSX. Type checking is not available for event listeners.

To sum, I don't think vetur will support JSX/TSX in short term.

**Comment by rhyek** [comment]
@HerringtonDarkholme This was actually a new boilerplate I was starting to work on and this was the first bump I ran into. I didn't actually get to the compilation step.

I greatly appreciate your investigations and will probably look into other options (such as not using SFC when wanting to use `render()` and also using css-in-js).

**Comment by HerringtonDarkholme** [comment]
Reopen due to this https://github.com/TypeStrong/ts-loader/pull/581
