### ISSUE TITLE
Rename file bug？

### ISSUE THREAD

**Issue by MichaelPorter0** [vuejs/vetur#3254]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [ ] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: 
- Vetur version:
- VS Code version:

## Problem

I create a vue file named TodoList.vue  but  typed wrong（Todolist.vue）.
I changed my file name to TodoList.vue  ,but vetur go run with:
![image](https://user-images.githubusercontent.com/38281116/143556838-1f67c71f-b075-4e68-9e7c-3b04a5108c6f.png)

Is that reasonable?
![image](https://user-images.githubusercontent.com/38281116/143557489-fbfd1667-7e28-4c44-ae4a-7c8a2366cee5.png)
## Reproducible Case

see above

**Comment by LinusBorg** [comment]
Have you tried  restarting VS Code or running `Vetur: Restart VLS`?

Seems like a caching issue that needs a restart of the Vetur Language Server

**Comment by MichaelPorter0** [comment]
> Have you tried restarting VS Code or running `Vetur: Restart VLS`?
> 
> Seems like a caching issue that needs a restart of the Vetur Language Server

It's solved. Thank you very much！I always thought there was something wrong with my code...
