### ISSUE TITLE
[Question] which version of prettier does Vetur use?

### ISSUE THREAD

**Issue by kingyue737** [vuejs/vetur#3264]
Does Vetur use locally installed prettier of a project or prettier with a specific version? I installed prettier v2.5.0. But it seemed that Vetur formats the project with rules from ~2.4.0

**Comment by JTravis76** [comment]
I was wondering the same thing. I believe you're right on the version. After reviewing the package.json, line 621 showing:
> "prettier": "^2.4.1",

**Comment by kingyue737** [comment]
close as vetur is dead
