### ISSUE TITLE
Promise.allSettled does not appear in IntelliSense

### ISSUE THREAD

**Issue by jzymx50** [vuejs/vetur#3265]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform:  Win
- Vetur version: v0.35.0
- VS Code version: 1.62.3

## Problem

Promise.allSettled does not appear in vue <script> section
![image](https://user-images.githubusercontent.com/54551206/144568683-4cfb1705-ee3c-4a53-bcac-b212cfd0bac5.png)

But it displays normally in .js file.
![image](https://user-images.githubusercontent.com/54551206/144569253-aa95d45b-1db5-4fd1-bcdc-bcfa5067a25c.png)

**Comment by yoyo930021** [comment]
Do you set correct `lib` option in your tsconfig.json/jsconfig.json?

**Comment by jzymx50** [comment]
> Do you set correct `lib` option in your tsconfig.json/jsconfig.json?

Sorry, no environment for testing. Haven't used Vetur for a long time.
But I guess you are right, if the Vetur IntelliSense depends on the lib option.

**Comment by yoyo930021** [comment]
Vetur is also based on typescript language service.
The reason is different default tsconfig.
