### ISSUE TITLE
Set subfolder as vue project folder

### ISSUE THREAD

**Issue by Sccotliu** [vuejs/vetur#3275]
- [x] I have searched through existing issues

## Feature Request

Vetur is the wonderful plugin for vscode, but maybe I'd like put frontend and backend folder into same vscode workspace, then vetur will  tell me cannot find package.json or other config files, can we just set vue project folder as a subfolder instead of toplevel folder of vscode workspace?

**Comment by rchl** [comment]
This is supported - https://vuejs.github.io/vetur/guide/setup.html#advanced

**Comment by Sccotliu** [comment]
> This is supported - https://vuejs.github.io/vetur/guide/setup.html#advanced

It works, Thanks
