### ISSUE TITLE
Support VeeValidate in Component Data

### ISSUE THREAD

**Issue by KareemDa** [vuejs/vetur#3287]
- [x] I have searched through existing issues

## Feature Request
[](url)

Kindly add VeeValidate package into [Supported Frameworks ](https://vuejs.github.io/vetur/guide/component-data.html#supported-frameworks) as it's the most use package for form validation

**Comment by yoyo930021** [comment]
Please open new issue to VeeValidate project.
https://vuejs.github.io/vetur/guide/component-data.html#adding-a-framework
