### ISSUE TITLE
Intellisense inside lifecicle methods (created, mounted, etc)

### ISSUE THREAD

**Issue by victorwpbastos** [vuejs/vetur#330]
- [X] I searched through existing issues.
- [X] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: Win
- Vetur version: 0.9.1
- VSCode version: 1.14

## Problem

The intellisense is not working as expected inside `lifecicle methods`.

Inside `lifecicle methods (created, mounted, etc)`:
![image](https://user-images.githubusercontent.com/1017515/28184568-405acc08-67ea-11e7-8469-3585244f88de.png)

Inside `methods`:
![image](https://user-images.githubusercontent.com/1017515/28185069-52c94aa2-67ec-11e7-9434-c4b2c73454b1.png)

**Comment by HerringtonDarkholme** [comment]
I cannot reproduce it. Please provide a reproduction file.

![screen shot 2017-07-14 at 11 52 18 am](https://user-images.githubusercontent.com/2883231/28197662-f7a11d86-688a-11e7-9d51-eff568ed3479.png)

**Comment by HerringtonDarkholme** [comment]
Close due to inactivity. Feel free to reopen it if you have more info.
