### ISSUE TITLE
IntelliSense not working on extended components

### ISSUE THREAD

**Issue by KareemDa** [vuejs/vetur#3303]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Win 
- Vetur version: 0.35
- VS Code version: LTS

## Problem
when extending a vue component, all intelliSense is gone. 

I'm trying to extend a Vuetify component as described in their docs: [extend vuetify component](https://vuetifyjs.com/en/getting-started/frequently-asked-questions/#extend-components)

the extended component is working but i have not hints, autocomplete, intelliSense in the props:

vuetify component: 
![image](https://user-images.githubusercontent.com/42810389/148555230-9aa31730-1a70-44b7-bdb7-d159ef13f973.png)

after extending: 
![image](https://user-images.githubusercontent.com/42810389/148555288-05235d56-ed81-44d8-8a0e-a94b540a7c9d.png)

**Comment by OACDesigns** [comment]
I have a similar case, where I am extending `VBtn` and registering it as a global component. 

I have managed to get Vetur to detect the component and provide intellisense prompts for my custom defined props.   
This was achieved by registering it as a global component in `vetur.config.js` (as per the docs: https://vuejs.github.io/vetur/guide/global-components.html).

Now all that's missing is the intellisense for the props that are inherited from VBtn.

I think this is related to https://github.com/vuejs/vetur/issues/2261

**Comment by yoyo930021** [comment]
Vetur have two methods to get component info (include props).

1. From TypeScript compiler:
Vetur will parse your code with typescript API, it doesn't support `extends`.

2. From component data:
Vetur will read a format json data to get component info.
When you try to extends it, we will lost it.
Ref: https://vuejs.github.io/vetur/guide/component-data.html#supported-frameworks

In this case, the vuetify framework provide component date.
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/package.json#L112

**Comment by KareemDa** [comment]
> Vetur have two methods to get component info (include props).
> 
> 1. From TypeScript compiler:
>    Vetur will parse your code with typescript API, it doesn't support `extends`.
> 2. From component data:
>    Vetur will read a format json data to get component info.
>    When you try to extends it, we will lost it.
>    Ref: https://vuejs.github.io/vetur/guide/component-data.html#supported-frameworks
> 
> In this case, the vuetify framework provide component date. https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/package.json#L112

So There is now way to detect the props in extended compoenent, right ?

**Comment by yoyo930021** [comment]
If component data from TypeScript compiler, it is possible.
But this feature is hard to implement. It's out of vetur target. Maybe volar can try it.
