### ISSUE TITLE
emmet doesn't work on vscode 1.15.0

### ISSUE THREAD

**Issue by deangoku** [vuejs/vetur#331]
- [x] I searched through existing issues.
- [x] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: Win
- Vetur version:0.9.1
- VSCode version:1.15.0

## Problem

![image](https://user-images.githubusercontent.com/6375486/28185978-060df40a-684c-11e7-9f62-29950541862a.png)
With emmet.syntaxProfiles setting, emmet doesn't work at all, works fine in previous version of vscode. With emmet.includeLanguages setting,  clicking menu or entering command can expand abbreviation but pressing tab.

**Comment by octref** [comment]
https://github.com/vuejs/vetur/issues/232

For now only `emmet.useNewEmmet: false` will work fine.

**Comment by Hanruis** [comment]
in vscode 1.50,  it ues emmet2.0 by default , and setting `emmet.useNewEmmet` has been removed .
![image](https://user-images.githubusercontent.com/5762991/29203104-c8fff34a-7ea0-11e7-861c-3fd7926efc6d.png)

**Comment by octref** [comment]
OK I'll look into integrating new emmet. But I don't quite like the decision on removing the old emmet.
