### ISSUE TITLE
Autocomplete `ceil($number)` instead of `center`

### ISSUE THREAD

**Issue by mrleblanc101** [vuejs/vetur#3311]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: macOS 12.1
- Vetur version: 0.35.0
- VS Code version: 1.63.2

## Problem

When I type `text-align: ce`, vetur suggest `ceil($number)` inside a `<style lang="scss" scoped>` which is not valid SCSS.
The only reference I found is in Vetur `.vscode/extensions/octref.vetur-0.35.0/server/dist/vls.js`

**Comment by yoyo930021** [comment]
It's a feature in scss.
https://sass-lang.com/documentation/modules/math#bounding-functions
