### ISSUE TITLE
Use own attribute snippets

### ISSUE THREAD

**Issue by bogdankorshunov** [vuejs/vetur#3320]
Is it possible to use custom attributes for vetur? I would like to use my snippet like "for" which will output:

`v-for="${1} in ${2}'" :key="${1}"`
`v-for="item in items" :key="item"`

Here is a hint of the standard directive
![image](https://user-images.githubusercontent.com/49434029/150638794-0fe67dea-8dff-4910-861d-bb2c37445f93.png)

**Comment by yoyo930021** [comment]
Please see https://vuejs.github.io/vetur/guide/snippet.html#customizable-scaffold-snippets.
