### ISSUE TITLE
Shows errors for modifiers on vue/valid-v-slot when allowModifiers is true

### ISSUE THREAD

**Issue by douglasg14b** [vuejs/vetur#3321]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Windows
- Vetur version: v0.35.0
- VS Code version: 1.63.2

## Problem

With the following rule:

```
    'vue/valid-v-slot': ['error', {
      allowModifiers: true
    }],
```

And the following code:

```
<template v-slot:name.modifier="props"></template>
```

![image](https://user-images.githubusercontent.com/1400380/150889393-26d8a483-ffc3-46b7-979e-f0a268cbd0c2.png)

This seems to have been the focus of the following, now closed, issues who's comments indicate this is a continued problem:

* https://github.com/vuejs/vetur/issues/2113
* https://github.com/vuejs/vetur/issues/2118

**Comment by yoyo930021** [comment]
If you try to use custom eslint rule, please disable `vetur.validation.template` in your vscode setting.
Ref: https://vuejs.github.io/vetur/guide/linting-error.html#linting
