### ISSUE TITLE
Property 'X' does not exist on type with injected

### ISSUE THREAD

**Issue by thexeos** [vuejs/vetur#3322]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Win
- Vetur version: 0.35.0
- VS Code version: 1.63.2

## Problem

> Property 'XXX' does not exist on type 'CreateComponentPublicInstance<{ [x: string & `on${string}`]: ((...args: any[]) => any) | undefined; } | { [x: string & `on${string}`]: undefined; }, {}, { typedData: DataType[]; typedFlag: boolean; }, {}, ... 13 more ..., {}>'.
>  Property 'XXX' does not exist on type '{ $: ComponentInternalInstance; $data: { typedData: DataType[]; typedFlag: boolean; }; $props: { [x: string & `on${string}`]: ((...args: any[]) => any) | undefined; } | { ...; }; ... 10 more ...; $watch(source: string | Function, cb: Function, options?: WatchOptions<...> | undefined): WatchStopHandle; } & ... ...'.

When I do this in SFC file:

```
  inject: ['XXX']
```

I've seen issues and possible solutions for props, but `PropType` won't work with `inject`.
Also this is an SFC, so I can't use `import { inject } from 'vue'` with type hint.

**Comment by thexeos** [comment]
Oh, and the current workaround I am using is:

```ts
declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    XXX: boolean
  }
}
```

But obviously that's not good, as if I forget to use `inject: ['XXX']` in a component, Vetur would not report any errors.

**Comment by yoyo930021** [comment]
This is a limit from 'typescript' type system.
Please use vue composition API with inject.
