### ISSUE TITLE
Display error suggestions when import modules

### ISSUE THREAD

**Issue by Ttou** [vuejs/vetur#333]
- [x] I searched through existing issues.
- [x] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: macOS
- Vetur version: 0.9.1
- VSCode version: 1.14.1

## Problem
![test1-fs8](https://user-images.githubusercontent.com/4298437/28203368-0e21774c-68ac-11e7-8902-2811725e7831.png)

**Comment by octref** [comment]
There is no suggestion for import modules and unlikely to have it soon.

**Comment by Ttou** [comment]
I have found the reason, because of enable `emmet.useNewEmmet`
