### ISSUE TITLE
Feature request: Add scaffold snippets for `<style>`

### ISSUE THREAD

**Issue by g-plane** [vuejs/vetur#334]
- [x] I searched through existing issues.
- [x] I have looked through docs at https://vuejs.github.io/vetur/

- Platform:  Win
- Vetur version: 0.9.1
- VSCode version: 1.14.1

In the current version, scaffold snippets for `style` tag doesn't not with `scoped` property. How about adding a feature like: Vetur still provides `style` scaffold snippets without `scoped` property, also provides snippets with `scoped` property.

**Comment by HerringtonDarkholme** [comment]
Contribution welcome!

**Comment by HerringtonDarkholme** [comment]
Contribution welcome!
