### ISSUE TITLE
`javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces` is not working for .vue file

### ISSUE THREAD

**Issue by leaves4j** [vuejs/vetur#336]
- Platform: macOS
- Vetur version: 0.9.1
- VSCode version:1.14.1

**Comment by octref** [comment]
We don't read format options from `javascript.*`. https://vuejs.github.io/vetur/formatting.html

**Comment by leaves4j** [comment]
@octref is there a plan to expose format option `insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces` ?

**Comment by octref** [comment]
No, and it seems to have some inconsistencies too: https://github.com/Microsoft/TypeScript/issues/9613

I'm looking forward to add prettier support and get rid of TS formatter.
