### ISSUE TITLE
Vetur + auto import components using @nuxt/components broken

### ISSUE THREAD

**Issue by 99linesofcode** [vuejs/vetur#3370]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: WSL2
- Vetur version: v0.35.0
- VS Code version: 1.65.0

## Problem

When attempting to `Go to Definition` by CTRL + clicking on a component (which is automatically imported by Nuxt from a sub directory of `components/`) inside a Vue template, the following error is displayed:

![image](https://user-images.githubusercontent.com/3071062/156864834-a631c4c3-e599-4ac1-b94f-5868a7acf843.png)

Support for automatically generating a `tags.json` file has been added to `@nuxt/components` since version [0.2.4](https://github.com/nuxt/components/blob/main/CHANGELOG.md#024-2020-05-20). The team also introduced the necessary changes to Vetur [in this PR](https://github.com/vuejs/vetur/pull/1921).

From what I could gather, it looks like this externalTagProvider is simply not loaded. That, or I'm missing something from the documentation on how to enable support for it. Can anyone see what is going wrong here?

## Reproducible Case

1. Set up a basic Nuxt.js project. Automatically importing components from the `components/` directory is already enabled by default;
2. Create a nested directory and component structure [as per the documentation](https://nuxtjs.org/docs/directory-structure/components/#nested-directories);
3. Add the component to a template and attempt to `Go to definition`.
4. 💥

**Comment by 99linesofcode** [comment]
I believe auto importing components is already enabled by default.

![image](https://user-images.githubusercontent.com/3071062/156907914-4dd13e1e-8b92-4e28-8e33-9081f5f1c442.png)

**Comment by JorgeVV** [comment]
[#2567 ](https://github.com/vuejs/vetur/issues/2567#issuecomment-747286928) helped me with this issue

**Comment by 99linesofcode** [comment]
@JorgeVV thanks, that does actually provide me with a temporary workaround. But as I just commented in #2567 it doesn't correctly solve the issue.

**Comment by 99linesofcode** [comment]
While it may seem that the globalComponents setting solves this issue (it might when you don't nest your components in subdirectories) it doesn't correctly solve the issue here. `@nuxt/components` allows you to dynamically import components from the `components/` directory and any subdirectory there in. As is documented here:

https://nuxtjs.org/docs/directory-structure/components/#nested-directories

I believe this is actually a bug, possibly a very simple one to resolve for anyone familiar with the vetur code base relating to the nuxt external tag loader not being loaded correctly.

Anyone with a better understanding of the inner workings of Vetur or VSCode plugin development that could take a stab at this?

**Comment by 99linesofcode** [comment]
Apologies, I tagged you guys in the wrong PR. Meant to draw your attention to this one instead:

> @pi0 I realize this isn't your primary focus but perhaps you could take a stab at this since you also worked on the initial PR? cc: @octref

**Comment by giancarllorojas** [comment]
I'm facing the same issue. Would be nice if the "Go to definition" feature worked for nested directories when using Nuxt Components.

**Comment by pi0** [comment]
Hi @99linesofcode. I've no ideas about `vue-editor-bridge.ts`. We didn't make any noticeable change for Nuxt 2 and `@nuxt/components` but it _might_ need some for latest version compatibility. @octref any hints are more than welcome would be happy to help 🙏🏼

**Comment by yoyo930021** [comment]
You mix two problems in this issue.

## Do we support nuxt built-in components?
Yes, we support it. The `tags.json` `externalTagProvider` will provide it.

## Do we support nuxt auto import components?
No, we did not support him directly. You can use global component feature to support it.
Ref: https://github.com/vuejs/vetur/issues/2567#issuecomment-747286928
We don't have any method to detect auto component in project. Except we write nuxt need it.

In this case, I think it's a good idea to use the config method.
