### ISSUE TITLE
Can we have vue attribute intellisense?

### ISSUE THREAD

**Issue by Thaina** [vuejs/vetur#338]
When writing html file I wish I would have intellisense for `v-for` / `v-on` and so on with vetur installed. Is this project will support that?

**Comment by HerringtonDarkholme** [comment]
Planned but not in recent release.

**Comment by octref** [comment]
How could Vetur know if your html file is template for component, or a html file containing the whole bundled app, or just a random html file in your doc?

**Comment by Thaina** [comment]
@octref For simplicity I have seen all extension in vscode, even vscode itself, never care about that. If it has intellisense for angular (`ng-for` for example) it will exist in attribute autocomplete every times I try to add attribute to html

So if I install and enable vetur. `v-for` should exist alongside `ng-for` even I don't add vue into that html file

**Comment by octref** [comment]
I'll think about it. Maybe the best way is to provide it if `vue` is in the package.json dependency, same as the check we do for Element and Onsen UI.

**Comment by Thaina** [comment]
Normally I use cdn script tag. That approach won't work

**Comment by octref** [comment]
This is tracked in #81.
