### ISSUE TITLE
'v-on' directives require event names

### ISSUE THREAD

**Issue by zhanziyang** [vuejs/vetur#339]
- [x] I searched through existing issues.
- [x] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: Win/macOS
- Vetur version: 0.9.1
- VSCode version: 1.14.1

## Problem
<img src="http://i.imgur.com/z1KgyRL.png" title="source: imgur.com" />

**The newly released [vue@2.4.0](https://github.com/vuejs/vue/releases/tag/v2.4.0) supports `v-on` without a event name now. So I think this linting rule should be disabled.**

**Comment by octref** [comment]
https://github.com/vuejs/eslint-plugin-vue/issues/89

**Comment by zhanziyang** [comment]
Got it. Thanks.

**Comment by octref** [comment]
We can keep it open to track progress once it lands upstream. Thanks!

**Comment by nickmessing** [comment]
@octref, we just need for vuejs/eslint-plugin-vue#90 to get merged, right?

**Comment by octref** [comment]
@nickmessing 
Oh didn't see it. Yep when vuejs/eslint-plugin-vue#90 lands in a release we can update Vetur's dependency on `esling-plugin-vue`.

**Comment by armano2** [comment]
`esling-plugin-vue@3.7.0` relesed with fix

**Comment by octref** [comment]
I'll look into integrating it soon.

**Comment by octref** [comment]
We are already on `eslint-plugin-vue@3.8.0` and I don't see this issue anymore.
