### ISSUE TITLE
vls can only work on singel .vue file?

### ISSUE THREAD

**Issue by weidehai** [vuejs/vetur#3394]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: 
- Vetur version:0.35
- VS Code version:1.66.0

## Problem
i use vetur in one a.vue file,the vls work,but when i create a new b.vue file end import a.vue file as a component,the vls not work
![image](https://user-images.githubusercontent.com/25458528/161554191-47747ea3-d6df-4a9b-92a7-16395f114fd7.png)
![image](https://user-images.githubusercontent.com/25458528/161554230-41a5e897-3f25-46dc-916d-36f5ad0af63c.png)
As shown above，the Test component accept foo prop with number type,but i pass a string,the vls not show error for me
so i guess vls just work on a Independent file，it not consider the import component from outside,right?

**Comment by yoyo930021** [comment]
Vetur doesn't support single file.
Please use a project.
