### ISSUE TITLE
style lang="sass" issue

### ISSUE THREAD

**Issue by prui** [vuejs/vetur#340]
- [ ] I searched through existing issues.
- [ ] I have looked through docs at https://vuejs.github.io/vetur/

## Info

<style lang="sass">
scss code

</style>

## Problem

in vue file when use <style lang="sass">, then css formatted doesn't work

**Comment by VitorLuizC** [comment]
I think VSCode don't support SASS Syntax, only SCSS. And `<style lang="sass">` refers to SASS Syntax instead of SCSS (`<style lang="scss">`). You could try this [extension](https://marketplace.visualstudio.com/items?itemName=robinbentley.sass-indented) that provide SASS Syntax highlight.

**Comment by octref** [comment]
Ues `lang="scss"` for scss code.
