### ISSUE TITLE
code .Extension issue

### ISSUE THREAD

**Issue by rs517** [vuejs/vetur#3407]
- Issue Type: `Bug`
- Extension Name: `vetur`
- Extension Version: `0.35.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.66.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by yoyo930021** [comment]
Your issue is closed because you did not provide a repro case.
Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.
