### ISSUE TITLE
when I provide $store in vue Component, CombinedVueInstance cannot find correct type

### ISSUE THREAD

**Issue by Yubiao-Li** [vuejs/vetur#3409]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: 
- Vetur version: v0.35.0
- VS Code version: 1.66.2

## Problem
when I provide $store in vue Component, CombinedVueInstance cannot find correct type

<img width="647" alt="image" src="https://user-images.githubusercontent.com/39786286/164386076-21c5c2d2-a8e0-47a9-83ce-86b075460b51.png">

## Reproducible Case

```vue
<template>
  <div></div>
</template>

<script lang="ts">
export default {
  provide() {
    return {
      store: this.$store,
    };
  },
  data() {
    return {
      curPage: 0,
    };
  },
  methods: {
    test() {
      this.curPage = 1;
    },
  },
};
</script>

<style></style>

```

**Comment by yoyo930021** [comment]
Please check
https://vuejs.github.io/vetur/guide/FAQ.html#property-xxx-does-not-exist-on-type-combinedvueinstance
