### ISSUE TITLE
script syntax highlight issue

### ISSUE THREAD

**Issue by fourcels** [vuejs/vetur#341]
- [x] I searched through existing issues.
- [x] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: Linux 
- Vetur version: 0.9.1
- VSCode version: 1.14.1

## Reproducible Case
![screenshot_2017-07-18_10-44-53](https://user-images.githubusercontent.com/1042568/28298494-2ddd3c5e-6ba6-11e7-86f0-d73f68d1cc8f.png)

```js
export default {
  obj: {
    "a": "<"  // the '<' will produce syntax issue
  }
}
```

**Comment by octref** [comment]
Thanks I can repro it.

**Comment by nalply** [comment]
There's a similar problem if you omit attribute quotes (which is allowed in HTML):

Example with quotes (working fine):

![image](https://user-images.githubusercontent.com/172290/29416723-51004504-8367-11e7-9fb7-1d6c7bc59840.png)

Example without quotes (bad syntax highlighting):

![image](https://user-images.githubusercontent.com/172290/29416856-b1ec0eb6-8367-11e7-8710-2ec3c4043f01.png)

**Comment by octref** [comment]
OK it's a new syntax in HTML5. https://mathiasbynens.be/notes/unquoted-attribute-values

I don't think there is any support for it in any HTML grammar yet...

**Comment by nalply** [comment]
It works in the HTML editor of vscode:

![image](https://user-images.githubusercontent.com/172290/29417639-2d513c0a-836a-11e7-9a09-aae7c2e1dc59.png)

**Comment by octref** [comment]
OK, seems VSCode pulls in the latest HTML grammar from here: https://github.com/textmate/html.tmbundle

I'll try to merge it with the current vue-html grammar.

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/30190901-3488fcc2-93f2-11e7-89a7-e0cfbe07ac71.png)
