### ISSUE TITLE
When will VUE3 be supported

### ISSUE THREAD

**Issue by zhuangwei-8256** [vuejs/vetur#3416]
When will VUE3 be supported?
For example, verify the root nodes of vue3 and vue2

**Comment by lehni** [comment]
It seems like Volar is the way forward for Vue 3: https://github.com/johnsoncodehk/volar/discussions/583

**Comment by yoyo930021** [comment]
This project only has limited vue 3 support.
The volar extension is recommend in vue 3 project.
https://github.com/vuejs/vetur#project-status

PS. https://github.com/vuejs/vetur/issues/3476
