### ISSUE TITLE
Mention in the docs that the file association for .vue needs to be configured as Vue-html

### ISSUE THREAD

**Issue by asifm** [vuejs/vetur#342]
- [x] I searched through existing issues.
- [x] I have looked through docs at https://vuejs.github.io/vetur/

I don't see anywhere in the docs mentioned that the file association for `.vue` needs to be configured as `Vue-html`. Maybe it's obvious to most people. Or maybe it's done automatically by the extension. For me, neither was the case. I had `.vue` configured as `html` at the time I installed vetur. Obviously vetur didn't work and I wasted a lot of time looking at the wrong places trying to figure out why it wasn't working.

**Comment by octref** [comment]
`vue-html` refers to only the `<template>` part of a Vue SFC.

You only need to set it up for emmet: https://vuejs.github.io/vetur/emmet.html
Otherwise, vue files are automatically associated to `vue` file type.
