### ISSUE TITLE
`references` in tsconfig.json are not expanded

### ISSUE THREAD

**Issue by FichteFoll** [vuejs/vetur#3422]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Arch Linux
- Vetur version: vls 0.7.6
- VS Code version: Sublime Text 4

## Problem

Specifying `baseUrl` and `paths` mappings in `tsconfig.json`'s `compilerOptions` only works if used in the main `tsconfig.json`, not if they are specified in a different sub-project file which is referenced using `references`. 

Related: #890

## Reproducible Case

1. Start with any project that uses path mappings (such as the default project). Example:
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    },
  }
}
```
2. Rename `tsconfig.json` to `tsconfig.app.json`
3. Create a  new `tsconfig.json` with 
```json
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    }
  ]
}
```

Any imports from `@/` cannot be resolved, just like in #890.

The feature works as expected when I mirror the relevant `compilerOptions` into this file.

**Comment by yoyo930021** [comment]
In your case, the `extends` option is correct one.
https://www.typescriptlang.org/tsconfig#extends

**Comment by towry** [comment]
So `references` is not supported by vetur ???

**Comment by yoyo930021** [comment]
> So `references` is not supported by vetur ???

Yes, not supported. The `references` isn't work well when no pure typescript project.
