### ISSUE TITLE
Style IntelliSense not working when I use postcss.

### ISSUE THREAD

**Issue by leenin** [vuejs/vetur#344]
## Info

- Platform: macOS
- Vetur version: 0.9.1
- VSCode version: 1.14.1

## Problem

When I use postcss
<img width="255" alt="wx20170719-143604 2x" src="https://user-images.githubusercontent.com/15712232/28353905-5d7dbe80-6c90-11e7-962d-b82f14f73344.png">

When I use css
![wx20170719-144652 2x](https://user-images.githubusercontent.com/15712232/28354146-3130af9e-6c91-11e7-8acf-6a61df3b806a.png)
**I want this!!!!!!!!**

**Comment by MaxMilton** [comment]
Amazing, thanks @octref !!

**Comment by leenin** [comment]
Wow, thanks @HerringtonDarkholme @octref
