### ISSUE TITLE
请问，还有人维护么

### ISSUE THREAD

**Issue by Topthinking** [vuejs/vetur#3443]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: 
- Vetur version:
- VS Code version:

**Comment by YFengFly** [comment]
只是前来做个提醒。根据目前置顶的公告，短期内会有维护，长期来说弃坑，生命周期会随着 Vue 2.7 的结束而结束，请尽可能迁移至 Volar ：
https://github.com/vuejs/vetur/issues/3476
