### ISSUE TITLE
Path Intellisense not working in .vue file

### ISSUE THREAD

**Issue by LukeLin** [vuejs/vetur#346]
- [x] I searched through existing issues.
- [x] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform:  Windows && OSX
- Vetur version:0.9.1
- VSCode version:1.14.1 && 1.15.0

**Comment by octref** [comment]
Open an issue on their side. I don't think we'll ever include it in Vetur by default.

**Comment by Ttou** [comment]
not only [Path Intellisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense) but also [Path Autocomplete](https://marketplace.visualstudio.com/items?itemName=ionutvmi.path-autocomplete) has the same problem

**Comment by ccqgithub** [comment]
+1
