### ISSUE TITLE
There is no problem with the path, but an error will be reported

### ISSUE THREAD

**Issue by tumeo** [vuejs/vetur#3462]
![image](https://user-images.githubusercontent.com/104367546/173183447-fdc0f40d-ffd5-4472-bfba-be0439433409.png)

**Comment by yoyo930021** [comment]
Please provide a repro case.
https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md
Your issue is closed because you did not provide a repro case.
Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.
