### ISSUE TITLE
npm autocomplete?

### ISSUE THREAD

**Issue by thearabbit** [vuejs/vetur#347]
`npm` autocomplete don't work
```js
<script>
    import _ from 'lodash';

    export default {
        name: 'Message',
        data() {
               _.sort ....... // don't autocomplete
```
Please help me.

**Comment by octref** [comment]
`npm i -D @types/lodash`.

**Comment by thearabbit** [comment]
I install via `npm i -S lodash`, what differance?

**Comment by octref** [comment]
This is not a Q/A place for basic npm question. You can find it on Google or StackOverflow.
