### ISSUE TITLE
High CPU usage and high read IO usage

### ISSUE THREAD

**Issue by ChiHoc** [vuejs/vetur#348]
## Info

- Platform: OSX 10.12.5
- Vetur version: 0.9.1
- VSCode version: 1.14.2 

## Problem

I got a high cpu usage and high read IO usage vetur process. 

process
![image](https://user-images.githubusercontent.com/4478983/28456947-bb25db4c-6e36-11e7-90a7-fadb0370def9.png)

high read IO usage
![image](https://user-images.githubusercontent.com/4478983/28456985-e0357a32-6e36-11e7-8c97-0237e1411280.png)

high cpu usage
![image](https://user-images.githubusercontent.com/4478983/28456932-b02c8588-6e36-11e7-96df-70ee7ed25513.png)

## Reproducible Case

1. Open a vue project.  (224M, 24,110 files)
2. Use "workbench.action.files.showOpenedFileInNewWindow" key and open a new window.
3. Watch "Activity Monitor"

**Comment by eronaeon** [comment]
#216

**Comment by octref** [comment]
https://github.com/vuejs/vetur/issues/216#issuecomment-305576562
https://vuejs.github.io/vetur/setup.html

**Comment by ChiHoc** [comment]
It works and feel sorry to open a duplicate issue. Thank you. @eronaeon @octref

**Comment by ChiHoc** [comment]
Um, it still seems happening when I **open file in new window**, even if exclude "dist" and include "src". ("src" is my vue project source dir)

![image](https://user-images.githubusercontent.com/4478983/28508041-570a6a66-706a-11e7-95e4-bba20154f797.png)

![image](https://user-images.githubusercontent.com/4478983/28508039-4e0d694a-706a-11e7-862e-9d7b94d77d87.png)

**Comment by octref** [comment]
Does that happen with Vetur disabled?

**Comment by ChiHoc** [comment]
It works well with Vetur disabled.

**Comment by ChiHoc** [comment]
The key point that I open file in a new **window**, not a new **tab**.

**Comment by octref** [comment]
If there is no repro case I can't help you.

Does Vetur work well for other projects like egoist/vuepack or the webpack template?
Can you try to modify them to cause this error? Or is the error just because of you having too much files in your workspace?

**Comment by ChiHoc** [comment]
Here is the repro case.

Clone this demo project: https://github.com/bailicangdu/vue2-happyfri.  ( 6.6 MB, 72 files)
![image](https://user-images.githubusercontent.com/4478983/28654296-b72f5e4e-72c5-11e7-98c2-7bbc903b2d85.png)

Add jsconfig.json.
![image](https://user-images.githubusercontent.com/4478983/28654584-07437a6c-72c8-11e7-8c20-8912ba24fe7d.png)

Open project in VSCode, and open a new window.
![2017-07-27 12 36 20](https://user-images.githubusercontent.com/4478983/28654675-c3553e8e-72c8-11e7-87b9-2476b2ca150e.gif)

**Comment by octref** [comment]
I don't think it has anything to do with "Opening New Window". The problem is you are opening **single vue file** using a VSCode instance / window, without a workspace.

People have reported this issue before. Vetur cannot determine your tsconfig without a workspace.
Now we recommend always work on Vue project by opening the whole project as a workspace. But with the upcoming VSCode support for Multi-Folder workspace, I plan to look deeper into workspace and have better support for the two scenarios:

- opening single vue file
- opening multiple vue projects using Multi-Folder workspace
