### ISSUE TITLE
Version v0.36.0 not available on VisualStudio Marketplace

### ISSUE THREAD

**Issue by josephdpurcell** [vuejs/vetur#3481]
## Problem

The fix for typescript >= 4.5 is here! See https://github.com/vuejs/vetur/blob/7a60fa2ebffb9a8c02285e9e8184d943eb5f374b/CHANGELOG.md#0360--2022-07-11--vsix, which is version 0.36.0.

However, the vsix link for 0.36.0 fails: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/octref/vsextensions/vetur/0.36.0/vspackage

I presume this is also why VSCode's extension page shows v0.35.0 as the latest too: https://marketplace.visualstudio.com/items?itemName=octref.vetur

## Reproducible Case

* Go to the CHANGELOG.md
* Click the VSIX link next to 0.36.0
* Notice the VSIX file does not download and instead shows an error

**Comment by rchl** [comment]
See https://github.com/vuejs/vetur/issues/3323#issuecomment-1180114561

> The VSCode extension will update when I get permission again.
> My token is expired.....

**Comment by yoyo930021** [comment]
You can download it in this link.
https://github.com/vuejs/vetur/releases/tag/v0.36.0

**Comment by yoyo930021** [comment]
The extension is published!
