### ISSUE TITLE
Unclear Vetur Setup Instruction

### ISSUE THREAD

**Issue by rogadev** [vuejs/vetur#3485]
## Problem

See docs here for reference: [Setup > Extensions > Vetur](https://github.com/vuejs/vetur/blob/master/docs/guide/setup.md)

It's not immediately clear what you're instructing users to do when reading the "VS Code Config" section on this page. "Add vue to your eslint.validate setting", with example, doesn't clearly indicate where to post this snippet or how to access the required location. Is it in VS Code settings? Inside an eslintrc.js file? Inside the package.json where the rest of this work is taking place?

A short blurb about how to do this would be immensely helpful for beginners who haven't done anything like this before.

![image](https://user-images.githubusercontent.com/61405141/180270766-c371ea20-5b08-47b8-bf66-b691c5b31051.png)

**Comment by oezkancodes** [comment]
It's in your VS Code settings. See also https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint#version-2.0.4

**Comment by yoyo930021** [comment]
Please set it in your vscode setting.

**Comment by alexander-gekov** [comment]
Created a small PR to add clarification #3536
