### ISSUE TITLE
postcss errors with new version of postcss

### ISSUE THREAD

**Issue by lamartire** [vuejs/vetur#350]
- [x] I searched through existing issues.
- [x] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: Linux
- Vetur version: 0.9.2
- VSCode version: 1.14.2

## Problem

![](http://i.imgur.com/roIyzst.png)

When I updated postcss to last version (6.0.2, also, it includes in new version of vue-loader) I take a lot of errors like this (nested syntax and other features provided by postcss-pliguns).
When I switch to 5.x.x version of postcss and 11.x.x of vue-loader that problems disappears.

## Reproducible Case

Install veteur and open project with last version of postcss/vue-loader. Create postcss styles and write nested styles or styles in sugarss syntax.

**Comment by HerringtonDarkholme** [comment]
Nested syntax isn't supported. And probably will not be supported until CSS spec accepts it. 

You can turn off style linting by setting `vetur.validation.style: false`

**Comment by lamartire** [comment]
@HerringtonDarkholme, but early version works fine.

![image](https://user-images.githubusercontent.com/13414205/28501035-00b0a2cc-6fdc-11e7-9c77-7c62a6abde51.png)

Also, I tryed to disable validation -- doesn't help.

**Comment by octref** [comment]
`vetur.validation.style` will apply to postcss since next version.

**Comment by lamartire** [comment]
@octref thank you! I can't wait :smiley:
