### ISSUE TITLE
Cannot find name '...'

### ISSUE THREAD

**Issue by Ic3m4n34** [vuejs/vetur#3502]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: macOS
- Vetur version: v0.36.0
- VS Code version: 1.70.1

## Problem
I want to include an external script in my Vue component. I'm doing this in the onMounted hook:

```
onMounted(() => {
      const trusted = document.createElement('script')
      trusted.src =
        '//widgets.trustedshops.com/reviews/tsSticker/tsProductStickerSummary.js'
      const summaryBadge = new productStickerSummary() // eslint-disable-line

      summaryBadge.showSummary({
        tsId: $currentShop.trustedShopKey,
        sku: [id],
        element: '.product-rating-stars',
        starColor: '#FFDC0F',
        starSize: '14px',
        fontSize: '12px',
        showRating: 'false',
        scrollToReviews: 'false',
        enablePlaceholder: 'false',
      })
    })
```

But as you see, Vetur complains about `Cannot find name 'productStickerSummary'.`. How do I type this correctly? Or is this a Vetur bug?
<img width="640" alt="Bildschirmfoto 2022-08-15 um 07 59 21" src="https://user-images.githubusercontent.com/11556486/184584198-c7eaaba9-d560-4b1f-9770-5a9b11b4583e.png">

**Comment by yoyo930021** [comment]
Vetur can't know this code.
Please learn more about javascript and typescript.

PS. this code isn't work well in browser.
