### ISSUE TITLE
validation style issue in lang="postcss"

### ISSUE THREAD

**Issue by leenin** [vuejs/vetur#351]
## Info

- Platform: macOS
- Vetur version: 0.9.2
- VSCode version: 1.14.2

## Problem
when I set `"vetur.validation.style": false`
<img width="347" alt="wx20170724-214946 2x" src="https://user-images.githubusercontent.com/15712232/28526400-06e5555a-70ba-11e7-850a-634afa4bb803.png">

But it don't working in postcss
<img width="484" alt="wx20170724-214742 2x" src="https://user-images.githubusercontent.com/15712232/28526307-bf2d235a-70b9-11e7-917d-4f319cc69c5c.png">

How to fix it, or have any mode to do it.
I don't want to the problems lint.

**Comment by octref** [comment]
#350
