### ISSUE TITLE
On save it formats the file, although disabled "editor.formatOnSave" to false

### ISSUE THREAD

**Issue by BroJenuel** [vuejs/vetur#3514]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: 
- Vetur version: v0.36.0
- VS Code version: 1.70.2

## Problem
It seems that theirs a problem, I don't like to format the file on save but still formatting on save, but still theirs something interfering on my prettier RC. So I installed prettier on VS Code to auto format files. by pressing `SHIFT + ALT` it formats good, but when I 'CTR + S' to save, it formats and save, the problem is the format is not the same as the prettier which the `SHIFT + alt` made..

## Reproducible Case
So I disable every possible setting:
```json
// settings.json
{
  "vetur.format.enable": false,
  "editor.formatOnSave": false,
  "[vue]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": false
  },
....
}
```
But problem still persist.

**Comment by yoyo930021** [comment]
Vetur don't auto save any file.
Please check about your other extensions or setting.

**Comment by BroJenuel** [comment]
oops, this is old, I forgot to close it. But for those who have this problem, do not auto format when saving a vue file. turn off here.
![image](https://user-images.githubusercontent.com/31676163/194347617-0db67f18-9a90-4c8d-af6f-7bd45bb31365.png)
