### ISSUE TITLE
Pug support (eslint, autocompletition, better coloring)

### ISSUE THREAD

**Issue by ugros** [vuejs/vetur#353]
## Info

- Platform: Both Win10 and Ubuntu 17.0.4
- Vetur version: 0.9.3
- VSCode version: 1.14.2
## Problem

No features (except for element coloring) work inside pug template.
(No eslint-vue, no autocompletition, nothing..)

Is this just not implemented, or is it broken? Couldn't figure it out from issues/docs.
If it's not implemented, do you have this in your roadmap?
Without this, pug is basically unusable for me. But I really don't like writing
`<my-component></my-component>` and all that html(xml) ugly syntax

Thanks!

PS. (just a quick question: Is html-snippets plugin supposed to work inside normal html-template? It needs me to set file association vue->html, but this disables vetur in .vue files. Is there some workaround?)
PS2. Great work with the project! This extension basically ended the React vs Vue war in my head :)

**Comment by octref** [comment]
Pug is not supported yet and our recent focus isn't on it. PR is always welcome though.

I don't know about other plugins. For Vetur the template region uses snippets under lang `vue-html`.
