### ISSUE TITLE
formatter option 'space_in_paren'

### ISSUE THREAD

**Issue by Ryuurock** [vuejs/vetur#354]
- [x] I searched through existing issues.
- [x] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: win10
- Vetur version: 0.9.3
- VSCode version: 1.14.2

## Problem
We need a format parameter called `space_in_paren`, can we add it in the next release

**Comment by octref** [comment]
No if you don't have any use case or explanation of the option.
