### ISSUE TITLE
vue-i18n single-file-component support [feature-request]

### ISSUE THREAD

**Issue by mcongy** [vuejs/vetur#357]
Hello,

The most popular Vue i18n library does provide a convenient way for local, component-based localization.
http://kazupon.github.io/vue-i18n/en/sfc.html

What we need to support this:
1. Proper coloring for `<i18n></i18n>` tags
2. Treat `<i18n></i18n>` tag contents as JSON
3. Add  `<i18n></i18n>` snippet inside .vue files

I hope it won't be too hard.

Thanks so much!

**Comment by octref** [comment]
So it seems <i18n> content can be either json or yaml. I don't think it's that easy to support it.

**Comment by HerringtonDarkholme** [comment]
Hi, for custom block features, I recommend this separate plugin.

https://github.com/nicolo-ribaudo/vetur-custom-blocks-demo

And file feedback in this issue https://github.com/vuejs/vetur/issues/210.
