### ISSUE TITLE
Vetur should use default/allow custom js-beautify unformatted option

### ISSUE THREAD

**Issue by sindrepm** [vuejs/vetur#358]
## Info

- Platform: Win 10
- Vetur version: 0.9.3
- VSCode version: 1.14.2

## Problem

Vetur does a good job at formatting my code, however, I am a bit annoyed with how it adds a new line before every tag. It makes my markup hard to read, and in some cases can even change the visual output.

Main concerns:
- I prefer to have my `<br>` tags at the end of the line
- `<span>` tags are automatically pushed to new line, which unintentionally leaves a white space in the output if it placed next to some text.

Example:

```
<template>
  <div>
    Some text before a break<br>
    test/<span>test2</span>
  </div>
</template>
```
is converted to:
```
<template>
  <div>
    Some text before a break
    <br> test/
    <span>test2</span>
  </div>
</template>
```
In the output this results in "test/ test2" instead of "test/test2". Maybe not a huge deal, but I feel that the formatting rules are a bit too aggressive.

I have disabled basically all my other extensions which could interfere, so I am pretty sure it is caused by Vetur. After disabling Vetur it does not happen.

Is there some format option I am missing to disable new line before tags? Ideally I would like to disable new line for inline elements.

**Comment by sindrepm** [comment]
After some more digging, it seems that this happens because Vetur sets the js-beautify option `unformatted` to an empty array by default [here](https://github.com/vuejs/vetur/blob/master/server/src/modes/template/services/formatterOptions.ts#L12).

https://github.com/beautify-web/js-beautify#css--html
> -U, --unformatted                  List of tags (defaults to inline) that should not be reformatted

The js-beautify [default](https://github.com/beautify-web/js-beautify/blob/895a45d95b36d8e37a2b8ad4dda488c0e1a8f272/js/src/html/beautifier.js#L93) is to not format inline elements which I think is a more sensible default.

I figured out that I can actually specifyi a custom list of tags in "vetur.format.html.unformatted" and it will work, but this option is not in the list of officially supported settings.

I suggest using the js-beautify defaults and also allow the user to override the `unformatted` option through vetur settings. This way we can e.g. add custom components like `router-link` to the list, which I prefer not to format.

On second thought, maybe even an option to **append** to the list of unformatted elements could be useful as in most situations we want the defaults + any custom tags.

What do you think?

**Comment by octref** [comment]
I don't know if "phrasing elements" ([js-beautify source](https://github.com/beautify-web/js-beautify/blob/895a45d95b36d8e37a2b8ad4dda488c0e1a8f272/js/src/html/beautifier.js#L94)) would be too much. Having `span` in it would cause the following code to be unformatted:

```html
<span>
  test
  </span>
```

same goes for `select` and other non self-closing tags.

Think maybe a better subset of it would be [void element](https://www.w3.org/TR/html51/syntax.html#void-elements), see https://stackoverflow.com/questions/3558119/are-non-void-self-closing-tags-valid-in-html5

**Comment by sindrepm** [comment]
@octref is it possible to make the formatting conditional, so if the markup initially has a new line after the opening tag, it is formatted like a block element and otherwise it is kept inline?

So the following remains unformatted:
```
Some  <span>inline</span> text.
```
While this:
```
<span>
    some text
   </span>
```
is formatted like a block element and becomes:
```
<span>
  some text
</span>
```
Not sure if this is even possible with `js-beautify`, just a suggestion.

Regardless I still think Vetur should just stick to the default unformatted tags set by `js-beautify`. If a user choose to type a span  tag like a block element I think it should just remain as is if my suggestion above is not possible. I mainly use span to change color, e.g. of small junks of inline text and it is really annoying that vetur formats these on a new line.

However, with already being able to override the `unformatted` option my only big issue now is #361.
