### ISSUE TITLE
Migration from TSLint to ESLint

### ISSUE THREAD

**Issue by bhomaidan1990** [vuejs/vetur#3604]
Can you please update the `package.json` file to use `ESLint` instead of `TSLint`, as I get the following warning from `npm`:
```
npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. 
Please see https://github.com/palantir/tslint/issues/4534 for more information.
```
due to this [line](https://github.com/vuejs/vetur/blob/master/package.json#L629) in your `package.json`. thanks in advance.

**Comment by ashutosh887** [comment]
Do you need some help? @bhomaidan1990
