### ISSUE TITLE
Content of unformatted elements are indented indefinitely

### ISSUE THREAD

**Issue by sindrepm** [vuejs/vetur#361]
## Info

- Platform: Win
- Vetur version: 0.9.3
- VSCode version: 1.14.2

## Problem

I am using the js-beautify option `unformatted` to specify a list of elements that should not be formatted, e.g. inline tags like `<br>` and `<span>` so the formatter doesn't put them on a new line ([see](https://github.com/vuejs/vetur/issues/358#issuecomment-318902207)). 

The issue is that whenever I format the document, anything inside the "unformatted" element plus the closing tag is indented, so with `formatOnSave` enabled it keeps indenting the content every time I save the file.

```
<span>
  test
</span>
```
after formatting a few times end up looking like this:
```
<span>
          test
        </span>
```
Which obviously doesn't look good. I am not sure if this is a bug in js-beautify, or if Vetur does some additional indentation in such cases.

## Reproducible Case

1. Add this setting to vscode workspace settings:

```
"vetur.format.html.unformatted": ["span"]
```

2. Add this markup to the `<template></template>` section of a .vue single-file component:

```
<span>
  test
</span>
```

3. Format the document a few times and see what happens.

**Comment by HerringtonDarkholme** [comment]
Thanks for reporting! This is a valid bug.

**Comment by octref** [comment]
Yeah, I made the `unformatted` setting empty to avoid this bug from `js-beautify`.

Looked into `js-beautify` but it wasn't gonna be easy to fix.
So I'm waiting for prettier to have html support and drop `js-beautify` completely.

I didn't really filter out the unsupported settings from `vetur.format.*`, but I wouldn't want to support bugs introduced through setting unspecified settings.

**Comment by octref** [comment]
And similarly #203.

**Comment by HerringtonDarkholme** [comment]
I haven't dig deeper, but I guess https://github.com/vuejs/vetur/blob/master/server/src/modes/template/services/formatters.ts#L20 might be the culprit.

**Comment by my9074** [comment]
@HerringtonDarkholme @octref 
I have the same problem when the label contains multiple rows
![8 -03-2017 11-47-34](https://user-images.githubusercontent.com/4555635/28993615-74d3ddde-79ed-11e7-8410-b62004f5b730.gif)
