### ISSUE TITLE
Formatting doesn't work

### ISSUE THREAD

**Issue by adi518** [vuejs/vetur#364]
- [x ] I searched through existing issues.
- [x ] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: Win
- Vetur version: 0.9.3
- VSCode version: 1.14.2

## Problem
It just won't format. I disabled all other extensions to no avail.

**Comment by octref** [comment]
Any error? What happens when you do "Format Document"?

**Comment by adi518** [comment]
No error, it just does nothing.

**Comment by octref** [comment]
Can you record a gif with LICEcap or provide some screenshots?

**Comment by adi518** [comment]
It seems to have sorted itself out. I'll re-open if it comes back. Thanks.
