### ISSUE TITLE
Format error (multi-word-component names) after upgrading v0.37.1

### ISSUE THREAD

**Issue by meguoe** [vuejs/vetur#3649]
Info
Platform: Mac
Vetur version: v0.37.1
VS Code version: 1.75.1

Problem
After upgrading v0.37.1, there was a format error (multi-word-component names). I tried to disable it in. eslntrc.js, but it had no effect.
<img width="565" alt="image" src="https://user-images.githubusercontent.com/45955794/220048558-fcaa886b-91c9-4512-a7a9-fd1dc2a5b8d3.png">

**Comment by mena234** [comment]
Same issue here.

**Comment by meguoe** [comment]
> 

Yes, I also solved this problem through demotion

**Comment by meguoe** [comment]
> Same issue here, the issue is fixed only when I downgrade the extension to v0.36.1

Yes, I also solved this problem through demotion

**Comment by es5es5** [comment]
Same issue here.
I also changed to 0.36.1

**Comment by Davidbadasyan** [comment]
Like you, I also used demotion to solve this problem.

**Comment by yoyo930021** [comment]
Please set `vetur.validation.template: false` when your project have custom eslint config.

**Comment by yoyo930021** [comment]
Fixed in 891ca72eb3baaa5263709dd2402e99c690a426a0 and v0.37.2
