### ISSUE TITLE
Downgrade in v0.37.2

### ISSUE THREAD

**Issue by Skriptach** [vuejs/vetur#3652]
## Info

- Platform: Win 7 x64
- Vetur version: v0.37.2
- VS Code version: 1.70.3

## Problem

1. Autocomplete stop working
2. Alt + click on a component use in a template stop open that component in a new tab

If install 0.37.0 from vsix than works fine

**Comment by yoyo930021** [comment]
Please provide a repro case.
https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md

**Comment by hxj9102** [comment]
same problem

**Comment by hxj9102** [comment]
same problem in vue2

**Comment by yoyo930021** [comment]
Duplicate of #3657 and fix in v0.37.3
