### ISSUE TITLE
格式化文件特别慢，要很长时间才能保存文件。

### ISSUE THREAD

**Issue by ma-x-x** [vuejs/vetur#3655]
<img width="396" alt="image" src="https://user-images.githubusercontent.com/20221017/220502032-33941376-2974-4035-993a-c9c46077b6c3.png">
## Info

- Platform:  MacBook Pro m1 
- Vetur version: 0.37.2/0.37.1
- VS Code version:   1.75.1
- vue version:  2.x

## Problem

use vetur 0.37.x， save vue file is slow, use low 0.37.x is fast。

**Comment by yoyo930021** [comment]
Please provide a repro case.
https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md

**Comment by ma-x-x** [comment]
您好，我已经收到您的来件，我会尽快处理的。祝您工作生活愉快。                                              ——BastogneYu

**Comment by wei2019-destiny** [comment]
i meet the same problem;
i degraded the plugin to solve the problem

**Comment by elianacc** [comment]
我也有同样的问题，项目是vue2项目，撤回0.36.1可以解决，0.37.1 0.37.2如上图所示一直无法保存

**Comment by DavidJiangLee** [comment]
我也有同样的问题，项目是vue2项目，撤回0.36.1可以解决，0.37.1 0.37.2如上图所示一直无法保存

**Comment by DavidJiangLee** [comment]
![image](https://user-images.githubusercontent.com/48940393/220550011-7b601dc0-3425-4bcc-aaa1-f94bf8c1e61c.png)

**Comment by yoyo930021** [comment]
Duplicate of #3657 and fix in v0.37.3
