### ISSUE TITLE
Add slm template syntax

### ISSUE THREAD

**Issue by anfinil** [vuejs/vetur#366]
Thanks for the great tool! Is it possible to add `slm` template syntax (https://github.com/slm-lang/slm) to `Vetur`. It has already implemented .vscode syntax file in https://github.com/mrmlnc/vscode-slm/blob/master/syntaxes/slm.json.

Or can you give me a key what steps should I do to add it to Vetur and make PR. Thanks.

**Comment by octref** [comment]
That's possible. I'll look into it soon.
