### ISSUE TITLE
Auto-complete <template> tag

### ISSUE THREAD

**Issue by rhyek** [vuejs/vetur#367]
- [x] I searched through existing issues.
- [x] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: Win/Linux
- Vetur version: 0.9.3
- VSCode version: 1.14.2

## Problem
This problem has three parts:

1. When you start typing the opening `<template>`, the suggestions for `<` are `scaffold` + others. If you select `scaffold`, you end up with `<<template>...` (double less-than character). The suggestions for `<t` are `template with html` + others. If you select that one, the same happens:
![1](https://user-images.githubusercontent.com/702922/29044664-b90fb694-7b7d-11e7-982b-95cb7d8baab3.gif)

2. When you have a root or nested `<template>` with both opening and closing tags or just the opening tag, the autocomplete after the first element inside it will not be to close that element, but to scaffold the entire `.vue` file, or just the `<template>` depending on how much you wrote:
![2](https://user-images.githubusercontent.com/702922/29044735-feea689e-7b7d-11e7-8d25-7fe50088742e.gif)
![4](https://user-images.githubusercontent.com/702922/29045123-97b85da0-7b7f-11e7-9b0b-1091e15b964c.gif)

3. Autocomplete for any nested `<template>` tags also tries to scaffold the entire `.vue` file or `<template>`:
![3](https://user-images.githubusercontent.com/702922/29044790-32ebef8c-7b7e-11e7-94a6-cb0f41c47d41.gif)

**Comment by HerringtonDarkholme** [comment]
Thanks for the report.

We will fix nested template issue. However, I cannot reproduce the second GIF. Can you provide more info?

@octref do you have any idea about repeated brackets?

**Comment by rhyek** [comment]
@HerringtonDarkholme, what additional info would you need? In your case, does it actually suggest the closing tag `</div>`?

**Comment by octref** [comment]
I cannot repro 2 or 3 either.

@HerringtonDarkholme I'm sure there is an option in CompletionItem that let's you configure that. I'll have time to look into it this weekend.

**Comment by HerringtonDarkholme** [comment]
@octref I also have investigated the completion error.

The problem is we don't set `textEdit` properly in completionItem. When textEdit is absent, vscode will fallback to `wordPattern` option to compute completion start position.

Sadly, vscode cannot handle embedded langauge's wordPattern.   https://github.com/vuejs/vetur/issues/369 is an example. `$hyphenate-variable` is a word in stylus, but vscode does not recognize. So completion is bad.

So we might need to provide `textEdit` for every completion item. But note, some client does not support `textEdit`, ike vim. A best solution is quite hard to find.

**Comment by rhyek** [comment]
Only the extra bracket issue is addressed, correct?

**Comment by HerringtonDarkholme** [comment]
Nope. Nested template is fixed. 

Extra bracket requires more refactoring.

**Comment by rhyek** [comment]
Great! I will test whenever you make the next release. Thanks.

**Comment by justid** [comment]
I can repro this problem when nested template,it always generate something like
<<template>
  
</template>

**Comment by justid** [comment]
vscode version 1.19.1,should I open a new issues? or it's just some setting problem?

**Comment by HerringtonDarkholme** [comment]
We haven't released a new version, please wait patiently.

**Comment by tetreault** [comment]
+1
