### ISSUE TITLE
Autocomplete bug : string not replaced completely

### ISSUE THREAD

**Issue by devistar** [vuejs/vetur#369]
- [x] I searched through existing issues.
- [ ] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: 
- Vetur version: 0.9.3
- VSCode version: 1.14.1

## Problem

Editing stylus in a .vue file.
It uses word based suggestion.

![bug-vscode-autocomplete](https://user-images.githubusercontent.com/11228594/29110725-fc12937e-7ce7-11e7-8028-a8a6eb1f5cdc.gif)

**Comment by HerringtonDarkholme** [comment]
Sadly, this works as intended. 

Stylus compiler isn't well crafted to support variable completion. So our completion is limited to properties and value.

I suggest you can make a voice under this issue. https://github.com/stylus/stylus/issues/2307
