### ISSUE TITLE
`module` as alias in `v-for` breaks code highlighting

### ISSUE THREAD

**Issue by alex3683** [vuejs/vetur#370]
- [x] I searched through existing issues.
- [x] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: macOS 10.12.6
- Vetur version: 0.9.3
- VSCode version: 1.14.2

## Problem

If the string `module` is used as alias in `v-for`, code highlighting is broken starting from the point of usage.

This is what highlighting looks like normally:
<img width="497" alt="bildschirmfoto 2017-08-10 um 09 18 00" src="https://user-images.githubusercontent.com/768322/29158995-62a94b94-7dad-11e7-9c61-42d58aaf0bc0.png">

This is when using `module` as alias for items:
<img width="517" alt="bildschirmfoto 2017-08-10 um 09 18 22" src="https://user-images.githubusercontent.com/768322/29158997-62b04a34-7dad-11e7-83ec-8a33da9c4e63.png">

The issue seems to vanish when adding the index alias explicitly:
<img width="563" alt="bildschirmfoto 2017-08-10 um 09 18 41" src="https://user-images.githubusercontent.com/768322/29158996-62aac41a-7dad-11e7-907d-cc3cac032b64.png">

## Reproducible Case

This is the code I used for a simple reproduction from the screenshots above:

```
<template>
   <ul>
      <li v-for="module in modules" :key="module">{{module}}</li>
   </ul>
</template>

<script>
export default {
   data: () => ({
      modules: [ 'A', 'B' ]
   }),
   created() {}
};
</script>

```

**Comment by octref** [comment]
https://github.com/vuejs/vetur/issues/259#issuecomment-310450891

> `type` is a reserved word for TS. We are using TS grammar for JS and this isn't easily fixable. I recommend avoid naming parameters as `type`.

The same for `module`. This isn't easy to fix since VSCode uses TS grammar for both JS and TS, so Vetur follows that decision.

**Comment by alex3683** [comment]
I understand, although it isn't a good thing that this bleeds through into code, because of one code highlighter of one IDE.
@octref Perhaps it would at least be good to document this issue and list the reserved words in the documentation. Then I wouldn't have bothered you ;-)
