### ISSUE TITLE
Allow template/script/style tags to be collapsed in vue components

### ISSUE THREAD

**Issue by sdarnell** [vuejs/vetur#371]
- [x] I searched through existing issues.
- [x] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: macOS
- Vetur version: 0.9.3
- VSCode version: 1.14.2

## Problem

When developing components I'm often either working on the template (and styles), or mostly on the code behind the component (i.e. the script).

It would be really nice if the `<template>`, `<style>`, and `<script>` tags themselves could be collapsed. So that I could focus on just the bit I'm interested in.  Usually I'd like to collapse the styles, but currently I have to collapse every top level style individually.

<img width="288" alt="screen shot 2017-08-10 at 13 57 57" src="https://user-images.githubusercontent.com/3684334/29171336-2842f62c-7dd4-11e7-8999-ce4881d71974.png">

**Comment by octref** [comment]
Well, it's not available even upstream: https://github.com/Microsoft/vscode/issues/3422

So there isn't anything I can do on Vetur side.

**Comment by sdarnell** [comment]
ok, thanks
