### ISSUE TITLE
The JS/TS language service immediately crashed 5 times. The service will not be restarted

### ISSUE THREAD

**Issue by yerassylnurlanov** [vuejs/vetur#3718]
Type: <b>Bug</b>

The JS/TS language service immediately crashed 5 times. The service will not be restarted

Extension version: 0.37.3
VS Code version: Code 1.89.0 (Universal) (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:10:10.196Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id ef06d714-569c-4918-8a25-47895150715c --inspect-extensions=33789 --crash-reporter-id ef06d714-569c-4918-8a25-47895150715c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:30973076
chatpanelc:31048052
dsvsc021:30996838
bdiig495:31013172
pythoncenvptcf:31049071
a69g1124:31058053
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by BrightTan** [comment]
i got the same problem

**Comment by opensino** [comment]
extremely slow

**Comment by yerassylnurlanov** [comment]
its bug from vscode, u need to upgrade or downgrade your version of vscode.
