### ISSUE TITLE
How to active Color Picker in the vscode new version 1.15

### ISSUE THREAD

**Issue by Moerj** [vuejs/vetur#374]
![qq20170811-092609](https://user-images.githubusercontent.com/13795438/29198740-4ecbeeb6-7e79-11e7-9dc6-0d612b75cba0.jpg)
In .scss file

![qq20170811-092652](https://user-images.githubusercontent.com/13795438/29198743-56cdba7c-7e79-11e7-856b-b45b46282722.jpg)
In .vue file

Vscode introduced a color picker for color customizations in 1.15 version.
I want to use it in .vue file. But it not work.

Vetur@0.9.3
Vscode@1.15

**Comment by Moerj** [comment]
In Issues #28. Vetur not support color indicator. So not support color picker?

**Comment by HerringtonDarkholme** [comment]
@octref It seems like quite many people want this feature. I think we can add it and also add an option to disable color picker.

**Comment by Moerj** [comment]
I update Vetur@0.9.5 . It has color decorators.  But the color picker can not open. Is that so?

**Comment by octref** [comment]
Yes, see #396.

**Comment by Moerj** [comment]
![image](https://user-images.githubusercontent.com/13795438/30193702-56feb136-9481-11e7-93ec-f44138c3904b.png)


https://code.visualstudio.com/updates/v1_16#_color-picker-in-html

**Comment by HerringtonDarkholme** [comment]
Wow, I will look at it later.

**Comment by yamnikov-oleg** [comment]
VS Code 1.16.1

Color indicator is displayed, but neither hovering, nor clicking opens up the color picker: it just shows css property hint.

**Comment by vberlier** [comment]
Also experiencing this issue, hovering over colors in .vue files doesn't open the color picker in VS Code 1.17.0.

**Comment by llKreator** [comment]
we still need a color picker)

**Comment by nsxz945** [comment]
the problem seem to be unsolved in VS Code 1.18.1

**Comment by HerringtonDarkholme** [comment]
Sadly, color picker is still in proposed stage. We will await its official adoption in vscode.

**Comment by HerringtonDarkholme** [comment]
Actually the new proposed API is better than our implementation now. Migrating to it might be better choice.

**Comment by fynnay** [comment]
Color picker still not opening on hover in Version 1.20.1
(Windows 10)

**Comment by valiumdev** [comment]
Just want to open this issue, since there is still no color picker support for vue files in VS Code.

**Comment by HerringtonDarkholme** [comment]
It works fine for me. If you want to reopen an issue, please provide a concrete reproduction.

<img width="503" alt="screen shot 2018-05-07 at 10 05 26 am" src="https://user-images.githubusercontent.com/2883231/39681656-3a966b7c-51de-11e8-8a03-9416c21d27a3.png">

**Comment by sam-lex** [comment]
I'm not sure about the vue files. But I used to hover (or click) on the color square preview to open the color picker. But doing that now, will only show you the property hints.

Try hovering on the values instead.

If you hover on the color square first, and then on the values, it won't work. Move away and hover on the value directly again.

**Comment by SergioSuarezDev** [comment]
Color picker not work with .asp files at this moment :(

**Comment by jarruda** [comment]
I'd like to make a feature request that a menu option is added to open the color picker.

It appears that a picker is exclusively available when editing certain HTML styles files, but there exists a desire to use it on arbitrary files.  It appears there is sufficient desire present being added to this closed issue to warrant either a new issue, or re-opening this one.

**Comment by luisDanielRoviraContreras** [comment]
It does not work with style `lang = "stylus"` :-1:

**Comment by Nutznieser** [comment]
It also doesn't work for python files (*.py). It seems the color picker only works on some specific files (*.css; ...?).

But it would be very desirable to have this feature also for all kind of languages. But maybe this would require to make it configurable for specific languages, because of the recognition of the different color formats/representations in these languages.
