### ISSUE TITLE
Emment not working anymore with VS Code update

### ISSUE THREAD

**Issue by DevoidCoding** [vuejs/vetur#377]
## Info

- Platform: Win
- Vetur version: 0.9.3
- VSCode version: 1.15.0

## Problem

With the last update of VS Code (updated yesterday), the emmet aren't working anymore on vue-html.
Here's my settings :
```json
"emmet.useNewEmmet": false,
"emmet.syntaxProfiles": {
    "vue-html": "html",
    "vue": "html"
}
```

Now, the "emmet.useNewEmmet" is an unknow configuration setting

## Reproducible Case

Just create a new file or use older .vue file

**Comment by DevoidCoding** [comment]
Replacing it by
```json
"emmet.includeLanguages": {
            "vue-html": "html",
            "vue": "html"
    }
```
will fix the problem

**Comment by octref** [comment]
`"vue": "html"` only fixes it for html. It doesn't limit it to the `<template>` region or has CSS support.
I'm working on integrating emmet directly and will make a release soon. You can subscribe to #232.
