### ISSUE TITLE
autocomplete  suggest appear too slow

### ISSUE THREAD

**Issue by wYuanHpp** [vuejs/vetur#378]
## Info

- Platform:  macOS
- Vetur version: 0.9.3
- VSCode version: 1.14

## Problem

autocomplete  suggest appear too slow when I coding，about spend 10seconds ,  but when I  edit .js file, autocomplete is worked well. I try to adding jsconfig.json but it's not helpful。

**Comment by octref** [comment]
Can you record a gif with https://www.cockos.com/licecap/ and put it here?

**Comment by wYuanHpp** [comment]
![text](https://user-images.githubusercontent.com/20528803/29245659-ff7dc086-8013-11e7-853b-f829a91cc477.gif)
it look like this. I need wait few seconds

**Comment by octref** [comment]
Do you have a very large project?
Does this happen to all vue project, like https://github.com/vuejs-templates/webpack or just one of your project?

**Comment by wYuanHpp** [comment]
As you said , my project is very large. when I try to open a simple vue project, autocomplete's preformance is pertty good . But why ,and how can I config my vscode to fit my this large project ?thank you very much!

**Comment by octref** [comment]
Write a jsconfig / tsconfig at the root of your project / workspace, and only include front end code. Otherwise Vetur would try to analyze your full project.

**Comment by ccqgithub** [comment]
+1， very slow

**Comment by ccqgithub** [comment]
It will to compile whole the code when every suggestion ? 

Maybe, can let the features  `load separately` ?   for example， let `emmet` or `path auto Completion` appear first.

Or, use compied caches ?

**Comment by octref** [comment]
I can help if you can provide me a medium / large size Vue project where this is happening.

**Comment by ccqgithub** [comment]
Thanks, i can't provide my project, my project has 500  vue component and other js files,  i has come back to use atom ...

Just now，i test it on the new version of vscode,  it's faster than before, but aslo very slow ...

**Comment by Akryum** [comment]
See #547
