### ISSUE TITLE
v-on directives don't support modifier x

### ISSUE THREAD

**Issue by p-adams** [vuejs/vetur#379]
When using custom defined keyCodes, for example:
     `Vue.config.keyCodes = {
       "meow": 86
     }`
 I get the following warning in VS Code when using this modifier on an input field:
      `<input type="text" @keyup.meow="someMethod"/>`

      [vue-language-server] 'v-on' directives don't support the modifier 'meow'.

Although this modifier works as expected, what needs to be done for the `vue-language-server` to recognize custom modifiers?

**Comment by octref** [comment]
Disable this rule https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/valid-v-on.md in your eslint setup.
