### ISSUE TITLE
Add framework support for Vuetify

### ISSUE THREAD

**Issue by ram-you** [vuejs/vetur#380]

**Comment by octref** [comment]
PR welcome.

**Comment by ram-you** [comment]
@johnleider 
@nekosaur

**Comment by nekosaur** [comment]
Is there anything that needs to be done from Vuetify's side?

**Comment by ram-you** [comment]
Simply needs contributors from Vuetify's community to help for a PR.

**Comment by nekosaur** [comment]
And I'm asking exactly what needs to be done.

**Comment by octref** [comment]
https://vuejs.github.io/vetur/framework.html

In short, take a look at these two PR. #234 and #308.

**Comment by jmichaliga** [comment]
Willing and able to add support for this ticket. Documentation in your IDE FTW.

**Comment by johnleider** [comment]
I'm going to automatically export the information and square it away @jmichaliga

**Comment by octref** [comment]
@alexsasharegan recently added support for bootstrap-vue. This doesn't seem so hard -- just creating two json files and you are done.

@johnleider I'm also interested in auto-generating that json so framework authors don't have to manually update it. However, it seems hard to find a common way to put component documentation in the component code itself so the docs can be automatically generated.

**Comment by octref** [comment]
@johnleider Did you have any luck at auto-generating it?

**Comment by johnleider** [comment]
Yes

**Comment by octref** [comment]
I just found out https://github.com/vuetifyjs/vuetify-helper-json, but it seems you aren't generating descriptions for the attributes / tags, because you don't have the descriptions for them in the code...

I'm looking into finding a standard way to write component description in Vue SFC.

**Comment by johnleider** [comment]
That would be because it's not done.

**Comment by octref** [comment]
@johnleider Just opened https://github.com/vuejs/vue/issues/7186, would love to hear your opinion.

**Comment by johnleider** [comment]
I don't think I'm qualified enough to be of any relevant conversation in that.
