### ISSUE TITLE
What is the prefix for snippets?

### ISSUE THREAD

**Issue by danielo515** [vuejs/vetur#384]
- [x] I searched through existing issues.
- [x] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: MacOsx
- Vetur version: 0.9.3
- VSCode version: 1.14.2

## Problem

I don't know how can I trigger snippets. They usually have some kind of prefix, but here there is no mention to any kind of prefix, neither snippets.
Are there snippets for vuex by the way?

Thanks and regards

**Comment by octref** [comment]
There is no pre-defined snippets for Vetur.

https://vuejs.github.io/vetur/snippet.html
