### ISSUE TITLE
Support sub folders and multiple tsconfig files in one window

### ISSUE THREAD

**Issue by ubershmekel** [vuejs/vetur#385]
- [x] I searched through existing issues.
- [x] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: macOS
- Vetur version: 0.9.3
- VSCode version: 1.15.0

## Problem

`tsconfig.json` is ignored if it isn't in the root of the vs code window.

For example:

```
file: 'file:///Users/yuval/rylo/nuxtsc/a/pages/index.vue'
severity: 'Error'
message: 'Cannot find module '~plugins/nuxt-class-component'.'
at: '17,23'
source: ''

file: 'file:///Users/yuval/rylo/nuxtsc/a/pages/index.vue'
severity: 'Error'
message: 'Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.'
at: '21,1'
source: ''
```

![Errors in vs code](http://i.imgur.com/ApMnjzi.png)

## Reproducible Case

```
git clone https://github.com/johnlindquist/nuxt-typescript a
git clone https://github.com/johnlindquist/nuxt-typescript b
code .
# now open pages/index.js and see the errors
```

Based on this code it seems to me there is no support to do this currently

https://github.com/vuejs/vetur/blob/446976091acff5258f2e8badc6cd27d0a178ac83/server/src/modes/script/serviceHost.ts#L69

https://github.com/Microsoft/TypeScript/blob/37b20ee670e9a89307b0e69960a2cbce104f93e5/src/compiler/program.ts#L8

**Comment by octref** [comment]
After thinking through it, it's impossible to do this.
For a workspace, I can't look at each `tsconfig.json` and create a language service based on it. In TypeScript, you do `tsconfig.json` per project, and `tsconfig.json` has to be located in the root of the proejct.
Instead, the way you should work on two Vue codebases together is to use the new multi-root https://code.visualstudio.com/updates/v1_18#_support-for-multi-root-workspaces feature.
I'll implement #424, where I spawn one Vue language service for a `workspaceFolder` if it contains a `package.json` with vue in it.

**Comment by WolfspiritM** [comment]
I stumbled over this issue as well as I was wondering why I kept getting experimentalDecorators warning over and over even so I added that to my tsconfig.json. Creating a "*.ts" file beside the vue file with the same code handled it correctly.

I also found https://github.com/Microsoft/vscode/issues/3772 which explains the "same" issue on the "official TS" side and a comment from egamma from Microsoft stated that it is explicitly supported by vscode and should work. If that is vscode behaviour then I think vetur should also support it in the same way.

However I can understand if there are technical reasons why this can't be implemented.

**Comment by Stupidism** [comment]
@octref I'm using `yarn workspaces` with `lerna`, and one of my repo is `next`.

Before add the folder: 
![image](https://user-images.githubusercontent.com/5801015/61173596-048e7d00-a5c8-11e9-9579-cdf50757a593.png)

Your solution works perfect for me!

**Comment by robodude666** [comment]
@octref Are your views from 2017 still the same? "won't fix" ? You mentioned here https://github.com/microsoft/vscode/issues/68343#issuecomment-463091232 that you need to revive this issue.

@Minigugus provided a PR: https://github.com/vuejs/vetur/pull/1734 that seems to address this issue.
