### ISSUE TITLE
Maximum call stack size exceeded. On vscode1.15.1

### ISSUE THREAD

**Issue by Moerj** [vuejs/vetur#390]
Today Vetur was good before I updated vscode.
But when I upgreade vscode from 1.15 to 1.15.1. Vetur has a problem.
```
vetur initialized
/Users/apple/.vscode/extensions/octref.vetur-0.9.3/client/node_modules/typescript/lib/typescript.js:15973
    function forEachChild(node, cbNode, cbNodeArray) {
                         ^

RangeError: Maximum call stack size exceeded
    at Object.forEachChild (/Users/apple/.vscode/extensions/octref.vetur-0.9.3/client/node_modules/typescript/lib/typescript.js:15973:26)
    at bindEachChild (/Users/apple/.vscode/extensions/octref.vetur-0.9.3/client/node_modules/typescript/lib/typescript.js:23091:16)
    at bindBinaryExpressionFlow (/Users/apple/.vscode/extensions/octref.vetur-0.9.3/client/node_modules/typescript/lib/typescript.js:23748:17)
    at bindChildrenWorker (/Users/apple/.vscode/extensions/octref.vetur-0.9.3/client/node_modules/typescript/lib/typescript.js:23162:21)
    at bindChildren (/Users/apple/.vscode/extensions/octref.vetur-0.9.3/client/node_modules/typescript/lib/typescript.js:23066:17)
    at bind (/Users/apple/.vscode/extensions/octref.vetur-0.9.3/client/node_modules/typescript/lib/typescript.js:24319:21)
    at visitNode (/Users/apple/.vscode/extensions/octref.vetur-0.9.3/client/node_modules/typescript/lib/typescript.js:15944:20)
    at Object.forEachChild (/Users/apple/.vscode/extensions/octref.vetur-0.9.3/client/node_modules/typescript/lib/typescript.js:16114:24)
    at bindEachChild (/Users/apple/.vscode/extensions/octref.vetur-0.9.3/client/node_modules/typescript/lib/typescript.js:23091:16)
    at bindBinaryExpressionFlow (/Users/apple/.vscode/extensions/octref.vetur-0.9.3/client/node_modules/typescript/lib/typescript.js:23748:17)
[Info  - 7:48:31 PM] Connection to server got closed. Server will restart.
```

vscode @1.15.1
vetur @0.9.3

**Comment by octref** [comment]
Can you provide a repro?

**Comment by Moerj** [comment]
https://github.com/Moerj/monkey-pc-coupon
This is my project.

**Comment by eric-burel** [comment]
Hi,
I did not have this problem, however I lost Emmet after update, the "Expand abbrevation command" won't work anymore, even when manually triggering using the menu instead of pressing tab (which is understandable since there seems to have been breaking changes about Emmet in this version).

**Comment by Moerj** [comment]
Yes.I lose Emmet after update too.

**Comment by Moerj** [comment]
@eric-burel 
see https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0#_other-changes
Use emmet.includeLanguages instead of emmet.syntaxProfiles setting.
Now emmet is work.

**Comment by eric-burel** [comment]
@Moerj Much thanks, VS Code devs seems to be fond of changing obscure config names so that each new version breaks everything...

**Comment by octref** [comment]
Remove all settings in `includeLanguages` and upgrade to 0.9.4 for new Emmet support.

@Moerj Your project doesn't crash for me though. Are you still using symlinks?

**Comment by Moerj** [comment]
@octref No. I do npm install all dependencies.

**Comment by Moerj** [comment]
@octref
If you don't npm install dependencies.Has no node_modules. This error will happen? I will.

**Comment by Moerj** [comment]
I try to reinstall node_modules and Vetur. Will still crash. 😰

**Comment by Moerj** [comment]
node@8.3.0
npm@5.3.0

**Comment by Moerj** [comment]
@octref 
I know how this bug happened!

When I do npm run build. The vue-cli will build the project and create dist/ files.
![image](https://user-images.githubusercontent.com/13795438/29484879-cc537fb6-84fa-11e7-93f2-c11b442b10cb.png)

In the dist folder. vendor.**.js . There is such a code: forEachChild.

So. Need a jsconfig.json to exclude dist folder ?

![image](https://user-images.githubusercontent.com/13795438/29484905-55b36172-84fb-11e7-8344-37a5ce6f0b17.png)

**Comment by Moerj** [comment]
I mean. If I create a jsconfig.json like this https://vuejs.github.io/vetur/setup.html
Vetur Language server will not work.

![image](https://user-images.githubusercontent.com/13795438/29485014-2e32d748-84fd-11e7-8984-c4cda5c21d10.png)

**Comment by octref** [comment]
If you just exclude `dist/**/*`, does it work?

**Comment by Moerj** [comment]
![image](https://user-images.githubusercontent.com/13795438/29487552-8ae0caba-852d-11e7-89d6-f89a6d88ba81.png)

Not work.

**Comment by octref** [comment]
Remove your `emmet.includeLanguages`.

**Comment by Moerj** [comment]
Yes! already removed.

**Comment by octref** [comment]
So with jsconfig.json, you are not getting crashes?
With jsconfig, I get `this.$` completions in `src/components` but not `src/views`. I'll take a look at this later.

**Comment by Moerj** [comment]
Yeah. Not crashes with jsconfig.json.

**Comment by HerringtonDarkholme** [comment]
Hi @Moerj , I think this issue has been solved. So let's close this issue first.

Feel free to reopen it if you still have problems.

**Comment by Moerj** [comment]
@HerringtonDarkholme js.config can not completely solve this problem.
I think vetur can add a config to control which folder will be ignore .

**Comment by HerringtonDarkholme** [comment]
@Moerj Would you mind give me more explanation? 

Note, You need to configure jsconfig.json's `include` field to include all files you want to compile.

`exclude` only affects files in `included` options. That is, using `exclude` alone won't work.

Could you try this out?

**Comment by HerringtonDarkholme** [comment]
Sorry, I just note issue closed by other person cannot be reopened by OP. Reopen.

**Comment by HerringtonDarkholme** [comment]
I think this should be fixed by https://github.com/Microsoft/TypeScript/pull/18246

**Comment by octref** [comment]
We should upgrade to TS 2.5.3 as https://github.com/Microsoft/TypeScript/pull/18246 seems to be included in it.
