### ISSUE TITLE
Sass Language Type Support

### ISSUE THREAD

**Issue by MarkSky** [vuejs/vetur#395]
- [ ] I searched through existing issues.
- [ ] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: WIndows 10
- Vetur version: 0.9.4
- VSCode version: 1.15.1

## Problem
After installed it, there is one more sass type select in VS Code.
![vsc1](https://user-images.githubusercontent.com/4032734/29505250-c1d33184-8677-11e7-87f0-66603ff490d9.jpg)

And I selected it, it showed an error:
![vsc2](https://user-images.githubusercontent.com/4032734/29505266-d956d216-8677-11e7-980d-b877cb53f4b6.jpg)

**Comment by HerringtonDarkholme** [comment]
@octref should we include css dialect syntax in vetur? If we remove it the issue above will be solved.

**Comment by octref** [comment]
Yeah we should remove sass and ask people to install https://marketplace.visualstudio.com/items?itemName=robinbentley.sass-indented instead, same as we do for stylus.
