### ISSUE TITLE
a problem with Emmet & element UI

### ISSUE THREAD

**Issue by leeziiAtCn** [vuejs/vetur#398]
when 
1 el-button    ----> touch Tab
2 el-input -----> touch Tab

result 
1 \<el-button:d\></el-button:d>
2 \<el-input:b\></el-input:b>

problem
what is :b & :d?

vesion
vscode 1.15.1
vetur 0.9.4

![image 2](https://user-images.githubusercontent.com/22995117/29547743-8a838276-872e-11e7-8c08-24fb0558fd75.png)

**Comment by HerringtonDarkholme** [comment]
Thanks for reporting!

**Comment by octref** [comment]
`button:d` maps to <button disabled="disabled"></button>`.

My guess is we need to update our wordPatterns so emmet takes el-button as one word.

**Comment by HerringtonDarkholme** [comment]
https://github.com/vuejs/vetur/issues/232#issuecomment-324699509

Should be fixed in insider.

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/29698392-1bf9ce0e-8923-11e7-8bea-b8d4b5557351.png)

Not really, he was using `emmet.includeLanguages` and marking `vue` as `html`.

**Comment by HerringtonDarkholme** [comment]
If I read Emmet code correct, Emmet uses whole line as input. We might need to bump version of vscode emmet helper.
