### ISSUE TITLE
Multiline comments in `style` add newline on every save

### ISSUE THREAD

**Issue by iGarym** [vuejs/vetur#404]
## Info

- Platform: Win 10
- Vetur version: 0.9.5
- VSCode version: 1.15.1

## Problem

Newline add between multiline **ROOT** comments and rules on every save.

![201708251503627789599f8a0da26db](https://user-images.githubusercontent.com/19269027/29697152-f74b0336-897f-11e7-80ff-fd3da4638119.gif)

It is disappearance when i set `"vetur.format.css.preserve_newlines": false`

**Comment by HerringtonDarkholme** [comment]
https://github.com/beautify-web/js-beautify/issues/1185

Migrating to prettier seems to be a better fix.

**Comment by octref** [comment]
Now css/scss/less regions use prettier and does not move multiline comments around.

js-beautify for html is disabled by default and is deprecated. I'll eventually remove it in the future. Report all bugs to js-beautify. Changelog here: https://github.com/vuejs/vetur/blob/master/CHANGELOG.md#vetur-formatting-changes
