### ISSUE TITLE
Expected 'v-bind:key' directive to use the variables which are defined by the 'v-for' directive

### ISSUE THREAD

**Issue by lllllllll1** [vuejs/vetur#407]
- [v] I searched through existing issues.
- [v] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: Win
- Vetur version: 0.9.5
- VSCode version: 1.15.1

## Problem

![2017-08-26_00-31-14](https://user-images.githubusercontent.com/7571432/29733470-e815d38e-89f5-11e7-9dcf-76b498a98330.png)
When loop in the loop i have an error.

**Comment by HerringtonDarkholme** [comment]
https://github.com/vuejs/vetur/issues/400

**Comment by iBehzod** [comment]
Is somebdoy find the solution for it?!

**Comment by yoyo930021** [comment]
> Is somebdoy find the solution for it?!

If you find something and no any open exist issue,
Please open issue with bug report template.
