### ISSUE TITLE
Emmet abbreviation always show up regardless of setting

### ISSUE THREAD

**Issue by leonbec** [vuejs/vetur#412]
- [ *] I searched through existing issues.
- [ *] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: Win 10
- Vetur version: 0.9.5
- VSCode version: 1.5.1

## Problem
![image](https://user-images.githubusercontent.com/28700378/29949928-5aedbf14-8f0c-11e7-8490-3cc835671dc8.png)
Since I'm using emmet 2.0, so I set **"emmet.showExpandedAbbreviation": "never"**,  and used custom emmet shortcut , it works fine in normal html file, but not working in vue file. The emmet abbreviation always showed up.

## Reproducible Case
1. In user setting, set
  "emmet.showExpandedAbbreviation": "never",
2. In vue file, inside template tag, type **div**, press tab

**Comment by HerringtonDarkholme** [comment]
@octref We need add an option to disable emmet. Is that fine?

**Comment by LeonCv** [comment]
I think the user setting  **"emmet.includeLanguages": { "vue-html": "html" }** would be enough

**Comment by octref** [comment]
I'll add an option under Vetur to enable / disable it.

**Comment by octref** [comment]
Actually to provide this we need to add another shortcut in Vetur for expanding emmet abbreviations. Together with other emmet settings this would be confusing.
I'm leaving it as it is. If `emmet.includeLanguages` works fine for you that's great.

**Comment by AmazeCPK** [comment]
I don't understand octref. Are you saying this is fixed, or it will be fixed?
Right now I'm having a problem, where everytime I am working on the component's styling, and I use a 'auto' value for a CSS rule, I am greated with this monstrocity:
[http://prntscr.com/gixw60](http://prntscr.com/gixw60)

I can't hit enter without
creating this mess:
[http://prntscr.com/gixws7](http://prntscr.com/gixws7)

Just a small, but important anoyance, thank you.

**Comment by octref** [comment]
Sorry for the problem. But you should open that as an issue for https://github.com/Microsoft/vscode-emmet-helper

**Comment by AmazeCPK** [comment]
Sorry, I wasn't sure if this was a Vetur or VSC Emmet problem. I guessed it was Vetur because the issue disapears when I disable Vetur.

**Comment by octref** [comment]
Reopen since we are still not reading emmet settings from user setting.
