### ISSUE TITLE
emmet 的部分缩略词不起作用

### ISSUE THREAD

**Issue by G-Veigar** [vuejs/vetur#417]
- [ ] I searched through existing issues.
- [ ] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: macOs
- Vetur version: 0.9.5
- VSCode version: 1.15.1

## Problem

例如我在style中（lang="less"）使用css缩略词，w100p，然后按下tab键，并没有向我预料到的一样获得width: 100%; 而是简简单单的缩进了单元格。

**Comment by octref** [comment]
Alright fixed in master by using newest vscode-emmet-helper.
