### ISSUE TITLE
Add support for TS Cast Feature

### ISSUE THREAD

**Issue by joma74** [vuejs/vetur#419]
- [X] I searched through existing issues.
- [X] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: Ubuntu
- Vetur version: 0.9.5
- VSCode version: 1.16.0

## Problem
Support new TS Cast via JSDoc feature inside *.vue script for lang javascript

Example usage
```
<script>
...
methods: {
        triggerFileUpload() {
            // TS Feature: Cast via JSDoc https://github.com/Microsoft/TypeScript/pull/17251
            let photoUploadLement = /** @type {HTMLButtonElement} */ (this.$refs.photoUpload); 
            photoUploadLement.click();
        }
...
</script>
```
Actually gives quiggles `Property 'click' does not exist on type 'AnyVue | Element | AnyVue[] | Element[]'.` for ` photoUploadLement.click()`.

Same code as in example usage is casted properly in a non-*.vue t.i. pure js component. Just to mention that the TS feature works as advertised.

Would be great if you can give it a look.

## Reproducible Case

Anywhere inside a vue script tag where applicable using ts language service support for pure js
```
let varCastedToType = /** @type {TypeAfterCast} */ (varToBeCasted)
```

**Comment by HerringtonDarkholme** [comment]
Sure, we will upgrade TypeScript version in our plugin :)
