### ISSUE TITLE
Format Document appears be broken in 0.9.6?

### ISSUE THREAD

**Issue by teledemic** [vuejs/vetur#421]
- [x] I searched through existing issues.
- [x] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: Win10
- Vetur version: 0.9.6
- VSCode version: 1.16.0

## Problem

Autoformat/indent of HTML / CSS / JS in single-file vue components has stopped working after upgrading to vetur 0.9.6. The "Format Document" command is available in plain js or html files, but not in vue files (language mode is "Vue")

**Comment by octref** [comment]
Thanks, seems things have changed in languageservice API. I'll push a hotfix soon.

**Comment by octref** [comment]
Published 0.9.7
