### ISSUE TITLE
Can fix Intellisense and go to definition for absolute path

### ISSUE THREAD

**Issue by kinanson** [vuejs/vetur#423]
## Info

- Platform:  Win7
- Vetur version:0.9.7
- VSCode version:1.16.0

## Problem

I know had go to definition for component and js file and 0.9.6 also had intellisense for component and props.But if i use absolute path that is not working.see below that is i mean.
`import test from '@components/test.vue`

I think that is possible.If I install Vue Peek.That can help me to definition even if i import absolute path.

I don't know what is "Find Definition for Vue components in <template>".If you want to imporve document thanks.

**Comment by HerringtonDarkholme** [comment]
Do you have jsconfig.json or tsconfig.json in your project?

Have you configured path mapping in it? 

https://www.typescriptlang.org/docs/handbook/module-resolution.html

**Comment by HerringtonDarkholme** [comment]
Vue peek does awful guessing. https://github.com/fussinatto/vscode-vue-peek/blob/master/src/PeekFileDefinitionProvider.ts#L32

I don't like adding it.

**Comment by kinanson** [comment]
Yes.You are right.I tested is ok.Thanks a lot

**Comment by HerringtonDarkholme** [comment]
Thanks.

We also welcome PR to add configuration example / instructions to doc.

**Comment by kinanson** [comment]
Sorry.I am wrong.I was success.But i don't know why doesn't working now.My computer is windows 10.I will test windows 7 tomorrow.But I want to give you some details.
my jsconfig.json is below
`{
  "include": [
    "src/**/*"
  ],
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "components": [
        "*",
        "components/*"
      ]
    }
  }
}
`

below is my test example of gif 
![1](https://user-images.githubusercontent.com/5998113/30279095-d1f6a06e-973e-11e7-931a-17bfef8e448e.gif)

**Comment by HerringtonDarkholme** [comment]
Can you change the lang to ts? It will show error if component isn't resolved. In case your mapping configuration is wrong.

**Comment by kinanson** [comment]
Can you give me some example?I use resolve of alias and i follow typescript Module Resolution description below
![default](https://user-images.githubusercontent.com/5998113/30301893-092b322e-9790-11e7-8bb1-3a5dba9401b4.png)

Even if I can't resolve at vs code but i can run on website.Maybe we have some misunderstanding?

**Comment by kinanson** [comment]
I had solve this problem.Sorry for wasted your time.Below is my final config.That is work very well for windows 10.
`
{
  "include": [
    "src/**/*"
  ],
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": [
        "src/*"
      ]
    }
  }
}
`

**Comment by chocopowwwa** [comment]
H @HerringtonDarkholme  @kinanson ,

 i still experiencing some issue in `.vue` file not `.ts` file

Here some  details

Diretory:
```
└── src
    ├── dir1
    │   ├── a.vue
    │   └── b.ts
    ├── dir2
    │   ├── a.vue
    │   └── b.vue
    ├── index.js
    ├── index.vue
    └── jsconfig.json
```

jsconfig.json
```
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "baseUrl": ".",
        "paths": {
            "Dirone/*": [
                "./dir1/*"
            ],
            "Dirtwo/*": [
                "./dir2/*"
            ]
        }
    }
}
```

**Comment by kinanson** [comment]
@chocopowwwa 
try below:

{
    "compilerOptions": {
        "experimentalDecorators": true,
        "baseUrl": ".",
        "paths": {
            "Dirone/*": [
                "src/dir1/*"
            ],
            "Dirtwo/*": [
                "src/dir2/*"
            ]
        }
    }
}

**Comment by chocopowwwa** [comment]
thanks for your reply @kinanson 

nope, that one doesn't work, either

**Comment by edDimensi** [comment]
Hi, i have some problem.
```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "baseUrl": ".",
    "paths": {
      "src/*": ["./*"]
    }
  }
}
```
```
  import childApi from 'src/api/child';
  import { mapperApi } from '../../utils/api';
  import PageContainer from 'src/elements/PageContainer';
```

PageContainer vue-peek found, mapperApi found, childApi not found.
In .js childApi found.

**Comment by HerringtonDarkholme** [comment]
@edDimensi 

Vetur doesn't support eliding `.vue` extension. (and probably will not support)

**Comment by cr0cK** [comment]
Why Vetur could not handle .vue file out of the box? It seems to be a main feature for an extension that aims to support Vue.

@edDimensi you can workaround by adding a definition for Vue files: https://alexjoverm.github.io/2017/06/28/Integrate-TypeScript-in-your-Vue-project/#Troubleshooting

But "going to definition" shortcut still won't work because it is now going to Vue internals!

**Comment by HerringtonDarkholme** [comment]
I don't like it. I don't think one should omit the extension. VSCode can use path completion so it even doesn't matter whether it requires four more key strokes. It also confuse users between plain script file and vue file. Also, you won't import a json/css file without extension. The same logic applies to vue, too.

On the other hand, resolving file type without extension requires much more code and syscall on both editor plugin and webpack loader. ts-loader requires file extension to `appendSuffixTo` certain file.

Unless one can list some objective advantages of omitting extension, I don't think vetur will support it.

**Comment by cr0cK** [comment]
@HerringtonDarkholme I'm agree with you :) I prefer to let vue extensions too.

I was talking about the need to add a definition to handle .vue files to avoid to have import errors in VS Code. If Vetur could handle this out of the box and could be able to link Vue files in script tags (like vue-peek does), it'd be great.

**Comment by HerringtonDarkholme** [comment]
Sadly vetur cannot change the behavior of TypeScript side. The only workaround is to add a declaration in type definition file.

**Comment by HerringtonDarkholme** [comment]
@cr0cK  you can try this TypeScript langauge service plugin.

 https://github.com/HerringtonDarkholme/vue-ts-plugin

You still need to configure TypeScipt, however.

**Comment by KokoDoko** [comment]
@HerringtonDarkholme I have this same problem, but cannot fix it with any of the solutions in the FAQs or here. As soon as I include the typings.d.ts file, Vetur won't recognise paths to modules in `.vue` files anymore, and changes in vue files are not picked up anymore by intellisense. Removing the .d.ts file fixes everything, but then I cannot have an index.ts file that kickstarts `app.vue`.

**The culprit**
```
declare module "*.vue" {
    import Vue from 'vue'
    export default Vue
}
```

**Comment by HerringtonDarkholme** [comment]
@KokoDoko have you tried the vue ts plugin?

**Comment by alexsasharegan** [comment]
Looking for the best place to file my issue with path mapping in a pseudo multi-root workspace—this issue looks like a relevant place.

I have a project setup as a mono-repo with client and server subdirectories. Those two subdirs have their own `tsconfig.json` and `package.json` files. Here is some basic workspace layout:

```
.
├── client
│   ├── jsconfig.json
│   ├── node_modules
│   ├── package-lock.json
│   ├── package.json
│   ├── src
│   ├── styles
│   └── tsconfig.json
├── project-memory.code-workspace
└── server
    ├── node_modules
    ├── package-lock.json
    ├── package.json
    ├── src
    └── tsconfig.json
```

I have path aliases configured only for the `client` subdir. Webpack resolves `@` to the `src` dir in client and `@styles` to the `styles` dir in client. I also have entered path mappings for my `jsconfig.json` and `tsconfig.json` to support this.

```json
{
	"compilerOptions": {
		"baseUrl": ".",
		"paths": {
			"@styles/*": ["styles/*"],
			"@/*": ["src/*"]
		}
	},
	"include": ["src/**/*"],
	"exclude": ["node_modules"]
}
```

Path resolution is working great in my `.ts` files, but it's failing in my `.vue` files with `lang="ts"`. If I open a new vscode window scoped just to the `client` directory, things do work though.

Am I missing something? Or is vetur not resolving the mapping relative to the correct directory?

![image](https://user-images.githubusercontent.com/16269252/36751978-f73d9e5e-1bbe-11e8-93b0-e0e55c9ce26c.png)
![image](https://user-images.githubusercontent.com/16269252/36752027-11826ab0-1bbf-11e8-9b85-8f6f6a2cae04.png)

**Comment by HerringtonDarkholme** [comment]
@alexsasharegan We haven't supported multi-root projects.

**Comment by evenfrost** [comment]
Faced the very same issue as @alexsasharegan, workaround as for now is to create tsconfig.json in the root of your workspace and make it extend your base tsconfig.json. So, your **root tsconfig.json** should include one configuration line:
```json
{
  "extends": "./path/to/your/real/tsconfig.json"
}
```
After it, all the issues with missing aliased modules like https://github.com/vuejs/vetur/issues/762 or https://github.com/vuejs/vetur/issues/545 are gone, and TS type-checking and intellisense are working well in .vue files.

Should work well for multi-root projects as well following the same logic.

**Comment by neodon** [comment]
To expand on @evenfrost's post (thank you; it saved me a lot of time), the **root** of the workspace corresponds to the first folder in the workspace folder list in VSCode.

So an alternate solution is to rearrange your workspace so your web project folder comes first in the list.  

Vetur then seems to pick up the tsconfig.json file in that folder correctly.

**Comment by danielschmitz** [comment]
Thanks @evenfrost, save my day

**Comment by francoishill** [comment]
Set VS Code user setting `path-intellisense.extensionOnImpor` to `true`.

**Comment by blocka** [comment]
for those using vscode's multi root workspace feature:

make sure the first workspace root is your vue project, otherwise vetur won't pick up on your tsconfig

**Comment by jawa-the-hutt** [comment]
@HerringtonDarkholme 

I might have a use case that addressing the original issue might be worth looking into. It's related to a  [Vue CLI plugin](https://github.com/jawa-the-hutt/vue-cli-plugin-nativescript-vue/tree/dev) for Nativescript-Vue that will allow code sharing between Web and Native platforms in a single project.   It does use [Webpack Resolve Extensions](https://webpack.js.org/configuration/resolve#resolveextensions) to do the heavy lifting from the build side of things.  

I can open a new issue and reference this one if that would be better or I can continue in this issue with more details of the situation if you'd like.

**Comment by artfabrique** [comment]
I use regular js (not ts) and I have this jsconfig.json and tsconfig.json in the root
```
{
    "compilerOptions": {
        "target": "ES6",
        "baseUrl": "./src",
        "paths": {
			"@styles/*": ["styles/*"],
			"@/*": ["src/*"]
		}
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```
When I type imports nothing comes out while path input
![](https://service.crazypanda.ru/v/monosnap/2019-04-17-05-13-47-hR2cb.png)

**Comment by Cyclodex** [comment]
Hey @artfabrique , what I see is the _baseUrl_ seems strange, why is this `./src/` ? Or why do you add src/ again to the `@/*` ?
This will probably look for something like `./src/src/*`
I have this working for me:
```
"baseUrl": ".",
"paths": {
    "@/*": ["src/*"]
},
```

Maybe this helps! Cheers

**Comment by artfabrique** [comment]
> Hey @artfabrique , what I see is the _baseUrl_ seems strange, why is this `./src/` ? Or why do you add src/ again to the `@/*` ?
> This will probably look for something like `./src/src/*`
> I have this working for me:
> 
> ```
> "baseUrl": ".",
> "paths": {
>     "@/*": ["src/*"]
> },
> ```
> Maybe this helps! Cheers

I'm on Windows10 and are you too?

**Comment by Cyclodex** [comment]
Nope, on mac.
Maybe you need backslash instead of slash? Not sure how windows is handling this...

**Comment by NeilRShah** [comment]
I'm having the same issue. I have a multi project workspace: with a `client/` directory where my Vue project lives. 

I've put this in the client folder, and then also tried adding the "extends" jsconfig file at the root directory, like @evenfrost recommended.

`{
  "include": ["src/**/*"],
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    }
  },
  "exclude": ["node_modules"]
}
`

Intellisense works perfectly without the '@/', so if I do something like `import Service from ../blah/service', that works, but `@/blah/service` does not. 

Any suggestions? Would love Intellisense to work, and I feel like I'm so close!

**Comment by VaultDeveloper** [comment]
Also have this problem.

There are some time, VScode detects are error with `experimentalDecorators` and gave me a fast correction. This correction creates a `jsconfig.json`. I don't know why but since the create of this file, VSCode ignore `tsconfig.json`. I juste remove the `jsconfig.json` and reload window and everything works fine.

**Comment by speyou** [comment]
For anyone interested, I just spent 2h on making my specific use case work with this issue of going to definition (+ autcompletion of methods and properties).

My monorepo project:
```
.
├─ node_modules
├─ packages                
│   ├─ @configs
│   │     └─ tsconfig.base.json
│   ├─ core (JS)
│   ├─ app1 (VueJS)
│   ├─ app2 (VueJS)
│   └─ ...
└─ tsconfig.json
```

As you can see I have several VueJS apps (independant from each others but everyone is dependant of core) and I wanted to ctrl+click into my imports in order to peek inside.

My solutions is as follow:

./tsconfig.json
```
{
  "extends": "./packages/@configs/tsconfig.base.json"
}
```

./packages/@configs/tsconfig.base.json
```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true, 
    "experimentalDecorators": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["*", "src/*", "../app1/src/*", "../app2/src/*"], // this is the secret ingredient, add all of your projects here
      "@core/*": ["../core/src/*"]
    }
  }
}
```

Everything is not perfect tho, sometimes it works, sometime it doesn't. I didn't make sense of that yet but I finally have 80% of my files I can open through ctrl+click so it's a win.

Hope it will help someone. :)

**Comment by JoePassanante** [comment]
@speyou Thanks the 
`"allowSyntheticDefaultImports": true`
Worked for me in .jsconfig.json file

**Comment by hiniko** [comment]
I don't know if it helps but under the FAQ for setting up `[js|ts]config.json` and `webpack` it does say that you need the `.vue` extension if you're importing a SFC. Added this to a couple of `import` statements and the errors go away. 

https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#vetur-cannot-recognize-my-vue-component-import-such-as-import-comp-from-comp

I hope that is something that get changed / fixed as that is painful to go and fix everywhere.

**Comment by segidev** [comment]
> Faced the very same issue as @alexsasharegan, workaround as for now is to create tsconfig.json in the root of your workspace and make it extend your base tsconfig.json. So, your **root tsconfig.json** should include one configuration line:
> 
> ```json
> {
>   "extends": "./path/to/your/real/tsconfig.json"
> }
> ```
> 
> After it, all the issues with missing aliased modules like #762 or #545 are gone, and TS type-checking and intellisense are working well in .vue files.
> 
> Should work well for multi-root projects as well following the same logic.

Genius!

**Comment by exarus** [comment]
> css

WebStorm omits the file extensions by default (new project with Vue CLI). I can't find an IDE option to enforce extensions for `.vue` files and omit it for `.js` files. There is option to require to always add an extension
So to have code completion for all developers in my project I have to add `.js` extensions everywhere? Is that Vetur way of solving the problem for projects that use different editors?
I've tried to switch from WebStorm to VSCode (4 times by now) and these are the kind of issues that always bring me back to WebStorm.

**Comment by kjo1** [comment]
> Faced the very same issue as @alexsasharegan, workaround as for now is to create tsconfig.json in the root of your workspace and make it extend your base tsconfig.json. So, your **root tsconfig.json** should include one configuration line:
> 
> ```json
> {
>   "extends": "./path/to/your/real/tsconfig.json"
> }
> ```
> 
> After it, all the issues with missing aliased modules like #762 or #545 are gone, and TS type-checking and IntelliSense are working well in .vue files.
> 
> Should work well for multi-root projects as well following the same logic.

Thank you, you saved my time.

Deserve thumbs up!

**Comment by awefeng** [comment]
> I don't like it. I don't think one should omit the extension. VSCode can use path completion so it even doesn't matter whether it requires four more key strokes. It also confuse users between plain script file and vue file. Also, you won't import a json/css file without extension. The same logic applies to vue, too.
> 
> On the other hand, resolving file type without extension requires much more code and syscall on both editor plugin and webpack loader. ts-loader requires file extension to `appendSuffixTo` certain file.
> 
> Unless one can list some objective advantages of omitting extension, I don't think vetur will support it.

Vetur: Vue tooling for VS Code, but don't support this

**Comment by SomeoneIsWorking** [comment]
> I don't like it

What does that have anything to do with how Vue works?
I'm included in a project which was started in WebStorm long ago and WebStorm imported everything without the file extensions
But it was decided to not renew the licenses so we're now moving to VS Code
How does "I don't like it" help us in any way?

**Comment by yoyo930021** [comment]
This issue is a mixture of many questions, so I will lock this issue.
If you have any question, or feature request, please open a new issue.
