### ISSUE TITLE
Emmet Bem is not working in vue files

### ISSUE THREAD

**Issue by ramya-rao-a** [vuejs/vetur#426]
_From @edDimensi on September 12, 2017 9:38_

- VSCode Version: 1.16
- OS Version: Arch Linux Manjaro i3

Steps to Reproduce:

1. `.vzr-st__content>.__left+.__right`
2. press tab

Reproduces without extensions: No

I see https://github.com/Microsoft/vscode/issues/33631 and wait for it, but now i get this problems.

![peek 2017-09-12 12-33](https://user-images.githubusercontent.com/11390039/30318834-e0207ac0-97b6-11e7-8203-7dd6bd84f67c.gif)
Vue template
![peek 2017-09-12 12-34](https://user-images.githubusercontent.com/11390039/30318835-e03dc256-97b6-11e7-86b4-5836f6e19438.gif)
in SCSS
![peek 2017-09-12 12-35](https://user-images.githubusercontent.com/11390039/30318836-e0470154-97b6-11e7-8eac-6c518c9a8498.gif)
How stop adding a class attribute permanently?

I have that settings
```
  "emmet.syntaxProfiles": {
    "javascript": "jsx",
    "vue": "html",
    "vue-html": "html",
    "html": {
      "filters": "html, bem"
    }
  },
  "emmet.triggerExpansionOnTab": true,
  "emmet.includeLanguages": {
    "vue": "html",
    "vue-html": "html"
  },
```

_Copied from original issue: Microsoft/vscode#34213_

**Comment by ramya-rao-a** [comment]
1. For html file: Am not sure what the problem here is. I need some time to look into it. Until then avoid using the bem filter to remove the `class` attribute
2. For the vue file: I can repro it and @octref should be able to help
3. For the scss file: I am not able to repro this. Why is there html in a scss file?

**Comment by ramya-rao-a** [comment]
_From @edDimensi on September 13, 2017 0:44_

All bugs in vue file.

**Comment by ramya-rao-a** [comment]
Remove the below from both `emmet.syntaxProfiles` and `emmet.includeLanguages`
```
"vue": "html",
"vue-html": "html"
```

The vetur extension now provides emmet support without you needing to add the above to get emmet support in due from VS Code core.

**Comment by ramya-rao-a** [comment]
Also, what is your expected expansion for `.vzr-st__content>.__left+.__right` ?

**Comment by edDimensi** [comment]
If i remove config for emmet.incldueLanguages, emmet stop work.
And yes. I gave wrong example. For  `.vzr-st>.__content` emmet anyway not work

**Comment by ramya-rao-a** [comment]
@edDimensi What is your expected output for `.vzr-st>.__content` ?

Do you have the latest vetur extension?

**Comment by edDimensi** [comment]
![image](https://user-images.githubusercontent.com/11390039/30394418-adb0b256-98cb-11e7-9bd7-e0823995ed5c.png)
i have latest vetur

On `.vzr-st>.__content`, i await 
```
<div class="vzr-st">
            <div class="vzr-st__content"></div>
          </div>
```

**Comment by ramya-rao-a** [comment]
The bem related issue is an upstream one. I have logged https://github.com/emmetio/expand-abbreviation/issues/6 for it. Hopefully we will get a fix soon.

In `emmet.includeLanguages`, try removing the mapping for `vue` and retain the one for `vue-html`. Does that help?

**Comment by sergeche** [comment]
In case of BEM formatter, Emmet uses simplified prefix for elements and modifiers. `-` is used for elements, `_` for modifier and each prefix character is used for getting block name of Nth parent. E.g. `_` means ”take block name of parent element” and `__` means ”take block name of parent’s parent element” and so on.

Thus, `.a>.b>._m` would produce

```html
<div class="a">
	<div class="b">
		<div class="b_m"></div>
	</div>
</div>
```

...and `.a>.b>._m` produces

```html
<div class="a">
	<div class="b">
		<div class="a_m"></div>
	</div>
</div>
```

**Comment by edDimensi** [comment]
@ramya-rao-a remove vue from includeLang help.
Need still wait for implement emmet.preferences for bem?

**Comment by edDimensi** [comment]
How to off adding class to expanded tag?
`ct-header -> <ct-header class=""></ct-header>`

**Comment by sergeche** [comment]
Oops, my bad, fixed in `@emmetio/html-transform@0.3.5`

**Comment by edDimensi** [comment]
And
`.ct-target>(.-wrapper-img>.-img+.-title)`
convert into
```
<div class="ct-target">
    <div class="ct-target__wrapper">
      <div class="ct-target__img"></div>
      <div class="ct-target__title"></div>
    </div>
</div>
```

wrapper-img transforom into wrapper.

**Comment by sergeche** [comment]
Could you create a separate issue for all BEM problems here: https://github.com/emmetio/html-transform ?
So I can keep track of them

**Comment by edDimensi** [comment]
Create
