### ISSUE TITLE
formatOnType

### ISSUE THREAD

**Issue by marrkitos** [vuejs/vetur#427]
With `"editor.formatOnType: true"` in settings, when I press "Enter" key (new line) the code is not formatted, this does not happen in a normal **.js** file.
In other words, I want this to happen:
![bug](https://user-images.githubusercontent.com/8661538/30408529-0f66dc34-98c5-11e7-8d9a-ff3a11a7902f.gif)

but this does not happen in a **".vue"** file, it's a bug or I'm forgetting some settings?

## Info

- Platform: Windows
- Vetur version: 0.9.7
- VSCode version: 1.16.0

**Comment by HerringtonDarkholme** [comment]
We need add 

```js
    documentOnTypeFormattingProvider?: {
        /**
         * A character on which formatting should be triggered, like `}`.
         */
        firstTriggerCharacter: string;
        /**
         * More trigger characters.
         */
        moreTriggerCharacter?: string[];
    };

```

**Comment by marrkitos** [comment]
I'm a little confused, where should I put that configuration?

**Comment by marrkitos** [comment]
I understand, thanks @octref, so, the update will happen soon? I hope so

**Comment by marrkitos** [comment]
I'm sorry if I'm breaking any rule, but I've noticed that the **formatOnType** option no longer works.
Is it my configuration problem or has there been any change in the extension that I have not noticed?

**Comment by HerringtonDarkholme** [comment]
Please see https://github.com/vuejs/vetur/issues/477
