### ISSUE TITLE
vscode 安装插件 vetur 报错 ：The Vue Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by lhb11** [vuejs/vetur#432]
The Vue Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

这个错误在vscode中如何解决

**Comment by HerringtonDarkholme** [comment]
https://github.com/vuejs/vetur/wiki/%EF%BC%A6%EF%BC%A1Q
