### ISSUE TITLE
Emmet HTML slow to recognize

### ISSUE THREAD

**Issue by rjoo** [vuejs/vetur#436]
- [x] I searched through existing issues and FAQ https://github.com/vuejs/vetur/wiki/FAQ
- [x] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: Win
- Vetur version: 0.9.7
- VSCode version: 1.16.1 (both 32/64 bit versions)

## Problem
Emmet is taking an incredibly long time to recognize html abbreviations in .vue files. The issue is not so bad when there is only a `<template>` in the file, but when `<script>` and `<style>` are present it's practically unusable.

With Emmet CSS abbrs, there's only a slight inconsiderable delay.

I've reinstalled vetur, disabled all other extensions, and also reinstalled VS Code (to test differences between 32/64 bit versions).

## Reproducible Case
![](http://g.recordit.co/esN7NfMCv6.gif)

**Comment by octref** [comment]
Do you have a repro case? If not does this happen to [Veturpack](https://github.com/octref/veturpack) or any vue-cli templates?

**Comment by rjoo** [comment]
This project was created with vue-cli's `webpack` template. I just tested it with a bare `webpack-simple` template and saw the same thing happening.

However, I noticed that if I open a new VS Code window that's not tied to any folder, and open a .vue file directly, it is **much** faster.

**Comment by HerringtonDarkholme** [comment]
You probably need to provide a production project for this issue.

I cannot reproduce it on webpack-simple.

**Comment by HerringtonDarkholme** [comment]
I guess this is caused by resolving component options in completion method.

**Comment by rjoo** [comment]
After restarting the laptop today, I got a new error about the 'js-beautify' module not being found. Reinstalling veture again then fixed that problem and the speed problems went away.

I'm not sure what exactly changed from yesterday, other than the restart which would imply the issue was local to my machine's state prior. Will close this issue and sorry for any time wasted.

Thanks for this awesome extension!

**Comment by octref** [comment]
Yeah, that's in the FAQ. Sometimes VSCode messes up `node_modules` while updating. Glad you solved it.

**Comment by qpenta** [comment]
with me its works unistall and disable vetur and use vue - official (volax). Vetur is useless today
