### ISSUE TITLE
Syntax Highlighting: CSS Grid support?

### ISSUE THREAD

**Issue by codeofsumit** [vuejs/vetur#437]
![image](https://user-images.githubusercontent.com/2399810/30659189-6a96aabc-9e3d-11e7-98be-211ba711596d.png)

Is css grid supported?

**Comment by HerringtonDarkholme** [comment]
No.

It is not supported in VSCode either. 

You can file an issue in VSCode, vetur will benefit from it too.

**Comment by codeofsumit** [comment]
will do! THanks for the info

**Comment by codeofsumit** [comment]
this is the bug at vscode
https://github.com/Microsoft/vscode/issues/32309
