### ISSUE TITLE
Question about JSX in render function.

### ISSUE THREAD

**Issue by ethanli83** [vuejs/vetur#438]
- [X] I searched through existing issues and FAQ https://github.com/vuejs/vetur/wiki/FAQ
- [X] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: Win 10
- Vetur version: 0.1.2
- VSCode version: 1.7.2

## Problem

I am just wondering if the JSX in render function is fully supported. When I use ```@click``` in JSX, it highlights the whole line in red.

![image](https://user-images.githubusercontent.com/4969207/30677478-3d3b9bf8-9ecf-11e7-9a17-431671d43863.png)

**Comment by octref** [comment]
https://github.com/vuejs/babel-plugin-transform-vue-jsx#difference-from-react-jsx

![image](https://user-images.githubusercontent.com/4033249/30679257-2ce1c020-9e4d-11e7-8762-1de6420966c1.png)

**Comment by ethanli83** [comment]
@octref Thanks, I assumed the syntax for template would be the same to JSX in render function.
