### ISSUE TITLE
0.9.8 syntax highlighting BUG

### ISSUE THREAD

**Issue by qianzhangsheng** [vuejs/vetur#439]
- [x] I searched through existing issues and FAQ https://github.com/vuejs/vetur/wiki/FAQ
- [x] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: Win/macOS
- Vetur version:0.9.8
- VSCode version:1.16.1 

## Problem

Hello, author

After you encounter the template tag, there is no syntax highlighting

![Image1](https://raw.githubusercontent.com/qianzhangsheng/qianzhangsheng.github.io/master/QQ20170921-164339%402x.png)
![Image2](https://raw.githubusercontent.com/qianzhangsheng/qianzhangsheng.github.io/master/AA89FECB-BB18-4BE0-8180-192BE4DF95FC.png)

**Comment by HerringtonDarkholme** [comment]
This is caused by `"channelMoreComputed > 2"`. 

As a workaround, you can wrap it in a computed property.

**Comment by HerringtonDarkholme** [comment]
Fix in bound! Please wait for the next release.
