### ISSUE TITLE
syntax broken after destructuring scoped props

### ISSUE THREAD

**Issue by VitorLuizC** [vuejs/vetur#443]
- [x] I searched through existing issues and FAQ https://github.com/vuejs/vetur/wiki/FAQ
- [x] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: Darwin x64 16.7.0
- Vetur version: 0.9.8
- VSCode version: Code 1.16.1 ([27492b6][0], 2017-09-14T16:24:39.530Z)

## Problem

Syntax highlight broke on SFC templates.

<img width="549" alt="captura de tela 2017-09-21 as 13 59 06" src="https://user-images.githubusercontent.com/9027363/30708572-bc6a36b8-9ed5-11e7-9d93-694e74a1a832.png">

## Reproducible Case

1. Write a template and try to destructure scoped props.
2. The code that causes this issue:
  ```vue
  <template>
    <c-card
      class="team-vacations-history-card"
      icon="sun"
      title="Histórico de Férias Aprovadas"
      :size="5">
      <employee-list :employees="employees">
        <template scope="{ employee }">
          <p class="line">
            Férias: <span class="value">{{ employee | toInterval }}</span>
          </p>
          <p class="line">
            Total: <span class="value">{{ employee.balance | toDays }}</span>
          </p>
          <p class="line">
            Abono: <span class="value">{{ employee.allowance | toDays }}</span>
          </p>
        </template>
      </employee-list>
    </c-card>
  </template>
  ```

[0]: https://github.com/Microsoft/vscode/commit/27492b6bf3acb0775d82d2f87b25a93490673c6d

**Comment by octref** [comment]
> I searched through existing issues and FAQ

Have you?
