### ISSUE TITLE
Highlighting have some problem

### ISSUE THREAD

**Issue by chenyeah** [vuejs/vetur#444]
- [ ] I searched through existing issues and FAQ https://github.com/vuejs/vetur/wiki/FAQ
- [ ] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: 
- Vetur version:0.9.8
- VSCode version: 1.16.1

## Problem

![image](https://user-images.githubusercontent.com/22478003/30726332-bff4d868-9f7c-11e7-8088-de538007db7e.png)

**Comment by octref** [comment]
Please check these two marks before posting new issues.
Otherwise your issues will be closed automatically.

- [ ] I searched through existing issues and FAQ https://github.com/vuejs/vetur/wiki/FAQ
- [ ] I have looked through docs at https://vuejs.github.io/vetur/

**Comment by chenyeah** [comment]
yes
