### ISSUE TITLE
Implemention go to definition inside vue file

### ISSUE THREAD

**Issue by kinanson** [vuejs/vetur#446]
## Info

- Platform: Win
- Vetur version: 0.9.9
- VSCode version:1.16.1

## Problem

Do you have any plan to support go to definition in the .vue file.That is mean I can click F12 in the template then go to script or style that for only same a vue file?

**Comment by HerringtonDarkholme** [comment]
We should have already shipped that feature.

Can you give a more detailed example where goto definition fails?

**Comment by kinanson** [comment]
Ok.Below is demo gif.

![1](https://user-images.githubusercontent.com/5998113/30771574-4e09d3aa-a07d-11e7-9ef3-1387639d3a23.gif)

**Comment by HerringtonDarkholme** [comment]
Expression in template is not supported.

**Comment by mudin** [comment]
@HerringtonDarkholme will it be supported in the future?

**Comment by CjoyHome** [comment]
I also have this problem. Have I solved it?
