### ISSUE TITLE
Syntax highlight inside `div` and `template` tags are different.

### ISSUE THREAD

**Issue by tatyshev** [vuejs/vetur#449]
- [x] I searched through existing issues and FAQ https://github.com/vuejs/vetur/wiki/FAQ
- [x] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: macOS
- Vetur version: 0.9.8
- VSCode version: 1.16.1

## Problem

Syntax highlight inside `div` and `template` tags are different. Is it bug or feature?

<img width="298" alt="screen shot 2017-09-22 at 12 00 36" src="https://user-images.githubusercontent.com/2528926/30737010-b16b3f42-9f8d-11e7-9d1e-6632b7d2c1fc.png">

With default vscode dark theme:

<img width="284" alt="screen shot 2017-09-22 at 12 03 40" src="https://user-images.githubusercontent.com/2528926/30737130-248a5d6e-9f8e-11e7-97f6-6d0ff7dfddb8.png">

**Comment by HerringtonDarkholme** [comment]
This has been fixed in 0.9.9. Upgrade!
