### ISSUE TITLE
v-for in <template> tag shouldn't require key

### ISSUE THREAD

**Issue by pdcmoreira** [vuejs/vetur#451]
- [x ] I searched through existing issues and FAQ https://github.com/vuejs/vetur/wiki/FAQ
- [x ] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: Windows
- Vetur version: 0.9.7
- VSCode version: 1.15.1

## Problem

A `:key` binding should not be required in a `v-for` when used in a `<template>` tag.

This is supposedly fixed in eslint-plugin-vue:
https://github.com/armano2/eslint-plugin-vue/commit/8dcc275803eb1a4b53202a6ed4ff019e74711223

## Reproducible Case

```html
<template
    v-for="item in items">

    <div class="list-group-item list-group-item-header">
        {{ item.description }}
    </div>

    <div class="list-group-item"
        v-for="subitem in item.subitems">
        {{ subitem.description }}
    </div>
</template>
```

"[vue-language-server] Elements in iteration expect to have 'v-bind:key' directives."

**Comment by pdcmoreira** [comment]
Can you please link the duplicated issue? Can't find it.

**Comment by HerringtonDarkholme** [comment]
https://github.com/vuejs/vetur/issues/300#issuecomment-311742327
