### ISSUE TITLE
Incorrect html formatting for this in .vue files

### ISSUE THREAD

**Issue by amritk** [vuejs/vetur#452]
- [x] I searched through existing issues and FAQ https://github.com/vuejs/vetur/wiki/FAQ
- [ ] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: Ubuntu 16.04
- Vetur version: 0.99
- VSCode version: 1.61.1

## Problem

the the template section of my .vue file I have this line
`{{ (n <= details.rating) ? 'star' : 'star_border' }}`
with vs code's setting "editor.formatOnSave": true, it formats to this:
```
{{ (n
<=d etails.rating) ? 'star' : 'star_border' }}
```
However, in an html file set to type vue-html, it works fine
 
## Reproducible Case
Paste this line into a .vue file in the template section with the "editor.formatOnSave" set to true on your vscode settings
`{{ (n <= details.rating) ? 'star' : 'star_border' }}`

**Comment by octref** [comment]
We don't support html formatting. Open an issue for VSCode instead. Thank.s

**Comment by amritk** [comment]
Ah yes I wasn't sure where to put it. I figured they might send me here. I'll throw it over there thanks.

**Comment by octref** [comment]
We are moving to prettier on css/less/scss/js/ts and js-beautify is deprecated. js-beautify is now disabled by default for html. See https://github.com/vuejs/vetur/blob/master/CHANGELOG.md#vetur-formatting-changes
