### ISSUE TITLE
vetur的问题

### ISSUE THREAD

**Issue by lz535** [vuejs/vetur#453]
在.vue模板文件中，回车会自动多一行空格，输入分号结束也会自动换行，并且会打乱代码格式。

**Comment by octref** [comment]
Please check these two marks before posting new issues.
Otherwise your issues will be closed automatically.

- [ ] I searched through existing issues and FAQ https://github.com/vuejs/vetur/wiki/FAQ
- [ ] I have looked through docs at https://vuejs.github.io/vetur/
