### ISSUE TITLE
How to active javescript snippets in .Vue files

### ISSUE THREAD

**Issue by Moerj** [vuejs/vetur#454]
When open vscode first. If no .js files opend. The javascript snippets not work in Vue file.

But when I open a .js file. It work.

So. How can I active snippets in vue but not open a js file first ?

vscode @1.16.1
vetur @0.9.10

![image](https://user-images.githubusercontent.com/13795438/30772294-80c1a968-a08b-11e7-9538-25b5e0de03b9.png)

![image](https://user-images.githubusercontent.com/13795438/30772329-98597f4c-a08b-11e7-86d4-10db0d18cc2f.png)

**Comment by octref** [comment]
Upstream issue, https://github.com/Microsoft/vscode/issues/33158

Should already be fixed in 1.17.

**Comment by Moerj** [comment]
thanks !😘
