### ISSUE TITLE
REQUEST: Format Stylus content in Vue template

### ISSUE THREAD

**Issue by ThisIsManta** [vuejs/vetur#456]
- [x] I searched through existing issues and FAQ https://github.com/vuejs/vetur/wiki/FAQ
- [x] I have looked through docs at https://vuejs.github.io/vetur/

## Problem

**Vetur** does not support formatting **Stylus** content in `<style>` tags.

I'm the initiator of [**Stylus Supremacy**](https://thisismanta.github.io/stylus-supremacy/) -- a code formatting tool for Stylus language, available in Node.js, VSCode and Atom. I would like to contribute to **Vetur** by adding the ability to format **Stylus** content.

This issue ticket is for tracking purpose. Moved from https://github.com/ThisIsManta/vscode-stylus-supremacy/issues/16

**Comment by octref** [comment]
Oh hey, thanks for your interest in contributing 🌟 

Take a look at this file: https://github.com/vuejs/vetur/blob/master/server/src/modes/style/stylus/index.ts.
All you need to do is to make a `format` function, similar to the css `format`: https://github.com/vuejs/vetur/blob/master/server/src/modes/style/index.ts#L118-L120

**Comment by ThisIsManta** [comment]
@octref, would you enlighten me how I can read VSCode settings? I tried adding `configure(config) {...}` method to *vetur\server\src\modes\style\stylus\index.ts*, but I got nothing. Also I could not be able to debug or print out anything inside `configure` method.

**Comment by ThisIsManta** [comment]
PR opened https://github.com/vuejs/vetur/pull/457
@octref, please advise.

**Comment by HerringtonDarkholme** [comment]
This should be solved by #457 ! Thanks @ThisIsManta !

**Comment by mubaidr** [comment]
I am using latest version for both, but stylus is not being formatted inside `vue` components. `.styl` files works fine. Is there any way i can debug this issue?
