### ISSUE TITLE
:  case no Highlighted

### ISSUE THREAD

**Issue by songxing10000** [vuejs/vetur#458]
## Info

- Platform: 
- Vetur version:0.9.10
- VSCode version:macOS

## Problem
when has : it no Highlighted
![snip20170930_2](https://user-images.githubusercontent.com/10040131/31042858-f1042f12-a576-11e7-9755-57eaeedb745b.png)
when I remove : it Highlighted,but the pic not show
![snip20170930_3](https://user-images.githubusercontent.com/10040131/31042863-0474e0f0-a577-11e7-82c5-a8e94c82d31e.png)

the same code has : in webstorm Highlighted

**Comment by HerringtonDarkholme** [comment]
You need add quote to `dist.src`
