### ISSUE TITLE
better ts support

### ISSUE THREAD

**Issue by Jack85** [vuejs/vetur#460]
Would be cool to have ts Intellisense in .vue files to deeper levels (3+) like typescript language switch is doing.. 
something like 
```

<script lang="ts">
...
//inside coponent class
this.db.dataclass.method(parameters with types...  )
```

**Comment by octref** [comment]
IntelliSense is dependent on your specific setup. Without a repro I can't help you.

**Comment by Jack85** [comment]
What do you mean, what setup i need? 
I have ts project, with ts.config, structure in src like official templates have. 
If I switch language from vue to ts on that particular file, ts I get full intelisense.

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/31290855-d9040eda-aa82-11e7-89bb-f9fdeb9a70da.png)

**Comment by HerringtonDarkholme** [comment]
We have the same TypeScript intellisense underhood. The most probable explanation for this issue is that `this.db` is typed `any`

**Comment by Jack85** [comment]
But your re right, its complex case. Killimanjaro
It gets synthesized most likely by regular ts. 
![image](https://user-images.githubusercontent.com/16955647/31445519-7e4f3e54-ae9e-11e7-83e6-aea8b0a9ca0a.png)
