### ISSUE TITLE
Import path does not show .vue files

### ISSUE THREAD

**Issue by felixgogo** [vuejs/vetur#462]
- [v] I searched through existing issues and FAQ https://github.com/vuejs/vetur/wiki/FAQ
- [v ] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: Win10 Professional
- Vetur version: 0.9.10
- VSCode version: 1.16.1

## Problem
When enable Vetur while disable all other extensions,
import path does not show .vue files. (see screenshot below)

![image](https://user-images.githubusercontent.com/795347/31307171-c91f022c-ab90-11e7-8b87-b27af5a7d3da.png)

## Reproducible Case
1. Disable all extensions except Vetur
2. Type import DangerAlert from './' (the cursor location is between / and ')
3. The drop down menu only shows assets and main (all vue files are not shown) see attached screenshot
4. Install and enable Path Intellisense does not show .vue files
5. Disable Vetur and keep Path Intellisense enabled will show .vue files
6. Disable Path Intellisense and Remove & reinstall Vetur.
7. Vetur still only show assets and main in the drop down menu

**Comment by octref** [comment]
That requires some work from both TS and our side.

**Comment by VSDekar** [comment]
Vetur & Path Intellisense at the same time is working for me...

![image](https://user-images.githubusercontent.com/8400490/31369226-444f7ee2-ad83-11e7-9c07-da7a516d35ea.png)

**Comment by octref** [comment]
Yeah, I guess you should just use Path IntelliSense in combination with Vue. TypeScript language server has limitation on using non js/ts files: https://github.com/Microsoft/TypeScript/issues/19018
