### ISSUE TITLE
Vetur `postcss` doesn't support nesting syntax

### ISSUE THREAD

**Issue by devhbh** [vuejs/vetur#465]
- [x] I have searched through existing issues
- [x] I have read through docs at https://vuejs.github.io/vetur/
- [x] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

## Info

- Platform: OSX
- Vetur version: 0.9.11
- VSCode version: 1.17

## Problem

<img width="248" alt="2017-10-11 4 08 13" src="https://user-images.githubusercontent.com/28704427/31426558-cc46bb00-ae9e-11e7-975b-df0dd727d696.png">

## Reproducible Case

Writing nesting codes, it produces above errors.

**Comment by HerringtonDarkholme** [comment]
We don't support nested css as VSCode doesn't as well.

**Comment by octref** [comment]
I disabled CSS diagnostics for PostCSS.
