### ISSUE TITLE
less 错误提示

### ISSUE THREAD

**Issue by skcary** [vuejs/vetur#466]
- [1 ] I have searched through existing issues
- [1 ] I have read through docs at https://vuejs.github.io/vetur/
- [1] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

## Info

- Platform: macOS
- Vetur version:0.9.11
- VSCode version:1.17

## Problem
.px2rem(@name, @px) {
  @{name}: @px / @baseSize;
}
提示：
less } expected
less at-rule or selector expected

请支持less的这种写法，谢谢

**Comment by octref** [comment]
`"vetur.validation.style": false` or open an issue at https://github.com/Microsoft/vscode-css-languageservice

**Comment by skcary** [comment]
thx
