### ISSUE TITLE
syntax highlighting errors with css modules

### ISSUE THREAD

**Issue by babakness** [vuejs/vetur#469]
- [x] I have searched through existing issues
- [x] I have read through docs at https://vuejs.github.io/vetur/
- [x] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

## Info

- Platform: macOS 10.12.x
- Vetur version: 0.9.11
- VSCode version: 1.17.1

## Problem

It would be nice to syntax highlight for variables imported into css modules:

https://github.com/css-modules/css-modules/blob/master/docs/values-variables.md

Using `composes` also generates a syntax highlight error

Current result:

<img width="506" alt="screen shot 2017-10-13 at 12 46 34 pm" src="https://user-images.githubusercontent.com/2024235/31563602-9f329982-b014-11e7-8a3b-9074793c0141.png">

## Reproducible Case

Use css modules syntax

**Comment by octref** [comment]
This seems to be a postcss feature, so add `lang="postcss"`.
