### ISSUE TITLE
Intellisense doesn't work when Vue in devDependencies

### ISSUE THREAD

**Issue by thepheer** [vuejs/vetur#470]
- [x] I have searched through existing issues
- [x] I have read through docs at https://vuejs.github.io/vetur/
- [x] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

## Info

- Platform: Windows 10
- Vetur version: 0.9.11
- VSCode version: 1.17.1

## Problem

As the title says.

![1](https://i.imgur.com/rXLW13t.png)
![2](https://i.imgur.com/BqEYLDj.png)

It took me 2 days to figure that out, lol.

## Reproducible Case

1. Start empty project
2. `npm install --save-dev vue`

**Comment by HerringtonDarkholme** [comment]
Thanks for the report. New release will fix this.
