### ISSUE TITLE
Stylus wraps arguments in brackets

### ISSUE THREAD

**Issue by Kelin2025** [vuejs/vetur#471]
- [x] I have searched through existing issues
- [x] I have read through docs at https://vuejs.github.io/vetur/
- [x] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

## Info

- Platform: Linux
- Vetur version: 0.9.11
- VSCode version: 1.17.1

## Problem
Got a problem with stylus formatting in vue-components.  
If you pass a value from object to function (e.g. `lighten`), vetur will wrap it in brackets every time you'll save a file.
![image](https://user-images.githubusercontent.com/4208480/31589683-5a2e2d96-b20e-11e7-9a7b-38e7267cff1a.png)
![image](https://user-images.githubusercontent.com/4208480/31589686-614727cc-b20e-11e7-9051-11db0ccae433.png)
![image](https://user-images.githubusercontent.com/4208480/31589687-66c00fa2-b20e-11e7-8d4f-cae4d18e2bae.png)
Does it want me to become a lisp programmer? :thinking:

**Comment by octref** [comment]
What's your stylusSupremacy settings?
This should be a problem with stylusSupremacy. @ThisIsManta

**Comment by octref** [comment]
> Does it want me to become a lisp programmer? 🤔

We don't have such secret plans :D

**Comment by Kelin2025** [comment]
I found problem. 
> This should be a problem with stylusSupremecy
It happens when `stylusSupremacy.insertSemicolons` is `true`
> We don't have such secret plans
First rule of secret lisp club - nobody should know you are lisper :smiling_imp:

**Comment by ThisIsManta** [comment]
Copy that. Will take a look tonight.

**Comment by ThisIsManta** [comment]
Working on it!

**Comment by ThisIsManta** [comment]
This has been fixed in Stylus Supremacy [version 2.5.0](https://github.com/ThisIsManta/stylus-supremacy/releases/tag/v2.5.0).

I'll open a PR against **Vetur**.

**Comment by Kelin2025** [comment]
@ThisIsManta thanks a lot!  :heart:  this plugin
