### ISSUE TITLE
Types of property 'mixins' are incompatible

### ISSUE THREAD

**Issue by joma74** [vuejs/vetur#475]
- [X] I have searched through existing issues
- [X] I have read through docs at https://vuejs.github.io/vetur/
- [X] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

## Info

- Platform: Ubuntu
- Vetur version: 0.9.11
- VSCode version: 1.17.2
- Vue version: 2.5.2

## Problem
Typescript language service errors Mixin in vue component saying "Types of property 'mixins' are incompatible"

See project reference https://github.com/joma74/webpack-starter-101/commit/8254767a5c02d79035ba2443fe7936a2f3ec7c12, yarn and open `webpack-starter-101/src/main/js/components/twitterlike/TwitterLikeWithLabel.vue`.  Note that mixin `webpack-starter-101/src/main/js/components/twitterlike/InputLabelMixin.js` is annotated by comment `@type Component`.  

Let me point out that imo the same situation was OK when i used  the `https://github.com/DanielRosenwasser/vue#540a38fb21adb7a7bc394c65e23e6cffb36cd867` version.  See `https://github.com/joma74/webpack-starter-101/commit/1c8ad956ce4ae654eefac02211730a7e28e9fede#diff-b9cfc7f2cdf78a7f4b91a753d10865a2`. The issue started when I recently switched to vue@2.5.2. 
```
...
Types of property 'mixins' are incompatible.
      Type 'Component<DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, Record<string, any>>[]' is not assignable to type '(VueConstructor<Vue> | ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComput...'
...
```
![twitterlikewithlabel vue - webpack-starter-101 - visual studio code_030](https://user-images.githubusercontent.com/5314859/31741588-1252013e-b455-11e7-8218-bf1e29d48f5c.png)

## Reproducible Case

See project reference https://github.com/joma74/webpack-starter-101/commit/8254767a5c02d79035ba2443fe7936a2f3ec7c12, yarn and open `webpack-starter-101/src/main/js/components/twitterlike/TwitterLikeWithLabel.vue`.

**Comment by HerringtonDarkholme** [comment]
Thank you for report!

**Comment by HerringtonDarkholme** [comment]
A reduced usage.

```ts
import Vue, {ComponentOptions} from "vue"
declare const InputLabelMixin: ComponentOptions<Vue>;
export default Vue.extend({
    mixins: [InputLabelMixin],
});
```

**Comment by joma74** [comment]
Aye, ComponentOptions is the way to go.
