### ISSUE TITLE
Formatting fails on type (prettier?)

### ISSUE THREAD

**Issue by ferdaber** [vuejs/vetur#477]
- [x] I have searched through existing issues
- [x] I have read through docs at https://vuejs.github.io/vetur/
- [x] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

## Info

- Platform: macOS
- Vetur version: 0.10.0
- VSCode version: 1.17.2

## Problem
```console
vetur initialized
Prettier format failed
[Error - 18:04:31] [object Object]
Prettier format failed
[Error - 18:04:57] [object Object]
```
![error](https://i.imgur.com/N5RGJ4r.gif)

## Reproducible Case

- Disable all extensions except for Vetur
- Remove all user settings except for `editor.formatOnType: true`
- Create a new .vue file and go to the script tag
- Attempt to create a new object literal, and the code is duplicated in a weird way.

**Comment by octref** [comment]
I can confirm it. Fixing it. Meanwhile you can turn off formatOnType.

**Comment by ferdaber** [comment]
I instead opted to just set the default formatter for js and ts file to be "none" for the time being, for those who want an easier workaround.

**Comment by octref** [comment]
![f](https://user-images.githubusercontent.com/4033249/31747429-a9b814ac-b421-11e7-8276-5abd00ce0dd8.gif)

This seems to be what `formatOnType` does. It formats correctly, but nobody would want it.

I'll remove onTypeFormat for now. @HerringtonDarkholme let me know if you think we should add it back and if there is any way you see we can address this issue.

**Comment by octref** [comment]
onTypeFormat will no longer work with vue files since 0.10.1.

**Comment by njleonzhang** [comment]
@octref Will you fix this issue?  why not support this feature.
