### ISSUE TITLE
Question: New formatting options

### ISSUE THREAD

**Issue by amritk** [vuejs/vetur#479]
Not sure where else to ask this, how do you set the new prettier options for the updated plugin?

I tried:
```
"vetur.format.defaultFormatterOptions": {
    "prettier": {
        "singleQuote": true
    }
}
```
But it doesn't seem to do anything

**Comment by octref** [comment]
For prettier we read from `prettier`. Is there any reason that you are using different settings js in Vue and general js?

**Comment by amritk** [comment]
so we need to install prettier then? I only have one settings.js I'm only working on vue with this workspace. My typescript settings are set normally:
```
    "typescript.format.insertSpaceAfterConstructor": true,
    "typescript.format.insertSpaceBeforeFunctionParenthesis": true,
```
I will try installing the prettier extension

**Comment by octref** [comment]
You can change the defaultFormatter for js / ts to vscode-typescript. After that it'll read settings from javascript / typescript.

But currently there is a bug in recognizing ts section: https://github.com/vuejs/vetur/issues/476

So for all scripts, currently only `vetur.format.defaultFormatter.js` and `javascript.format` settings will be effective. I'll fix it soon.

**Comment by octref** [comment]
You don't have to install Prettier: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

You can still set the settings. It's just in the settings you don't get IntelliSense.

Although I highly suggest installing the prettier extension. It's pretty solid.

**Comment by amritk** [comment]
Ah yea the intellisense was complaining before, thats what threw me off. I installed the extension and it works great now, thanks!

**Comment by octref** [comment]
It's in the changelog, but I just updated the doc too: https://vuejs.github.io/vetur/formatting.html
