### ISSUE TITLE
intellisense does not work correctly if existing custom properties

### ISSUE THREAD

**Issue by maxma241** [vuejs/vetur#481]
- [x] I have searched through existing issues
- [x] I have read through docs at https://vuejs.github.io/vetur/
- [x] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

## Info

- Platform: macOS Sierra 10.12.6
- Vetur version: 0.10.1
- VSCode version: 1.17.2

## Problem

intellisense does not work correctly in .vue file if existing custom properties,
like using [vue-apollo](https://github.com/Akryum/vue-apollo)

type of **this** will be **FunctionalComponentOptions**

or in the future, could set for custom properties like [#276](https://github.com/vuejs/vetur/issues/276) ? so, event this.$xxxx can be custom setted, like this.$axios, this.$apollo ... etc.

I know if using class-component or set lang="ts" can show the intellisense what i expected. but consider team work, i just want to use common single file Component

thanks

> the problem
![data intellisense](https://i.imgur.com/kzV2TH9.png)
***
> correctly
![data intellisense](https://i.imgur.com/JmdnfyU.png)

## Reproducible Case

```JS
sample code

export default {
  apollo: {
     // vue-apollo properties....
  },
  data () {
    return {
      test: 1
    }
  },
  methods: {
  },
  created () {
    // intellisense show incorrectly.
    this.test
  }
}
```

**Comment by HerringtonDarkholme** [comment]
When you use custom properties on Vue options, usually added by plugin, ComponentOptions need be augmented.

https://vuejs.org/v2/guide/typescript.html#Augmenting-Types-for-Use-with-Plugins

```ts
declare module "vue/types/options" {
  interface ComponentOptions<V extends Vue> {
    apollo?: {}
  }
}
```

**Comment by maxma241** [comment]
@HerringtonDarkholme thanks!
I add a .d.ts file at root directory. 
reload window, then the types I declared are injected to component! 😃

**Comment by rchl** [comment]
Don't invent your own type definition for something that is already defined, you just need to use it. See https://github.com/vuejs/vetur/issues/1161#issuecomment-646808762

**Comment by code-is-art** [comment]
This is still a problem with javascript projects. One might be able to add types to the compilerOptions in typescript projects but not in javascript so intellisense remains broken with apollo-vue and vetur.
