### ISSUE TITLE
fomatter problem to insert space before function parenthesis

### ISSUE THREAD

**Issue by tczhangzhi** [vuejs/vetur#482]
## Info

- Platform: macOS
- Vetur version:0.10.1
- VSCode version:1.17

## Problem

My config can't work in `setting.json`
```
"vetur.format.js.InsertSpaceBeforeFunctionParenthesis": true
```

## Reproducible Case

After updating  only the config as below I can use , can't I?
```
"vetur.format.defaultFormatter.js": "prettier"
```
But I want to insert space before function parenthesis, so what can I do?

**Comment by axu6705** [comment]
I also appeared after the update.

**Comment by tczhangzhi** [comment]
Thanks I have tried it, but It doesn't work. I also try to add this line
```
"typescript.format.insertSpaceBeforeFunctionParenthesis": true
```

**Comment by octref** [comment]
There is a bug that the embedded formatter recognize lang="ts" blocks as js. I'll fix it soon. Meanwhile, you can set `javascript.format.insertSpaceBeforeFunctionParenthesis": true`.

This is item 1 in https://github.com/vuejs/vetur/issues/476 so I'll track it over there. Thanks.
