### ISSUE TITLE
Feature Request: Typescript completion in Angular/Vue html templates

### ISSUE THREAD

**Issue by victorgarciaesgi** [vuejs/vetur#485]
It would be very useful to have typescript completion inside the frameworks templates.
For exemple: 

Here typescript should be suggesting me the properties I provided with "ITodos".
It's a single file component so Typescript should know which Class to look into for data

![image](https://user-images.githubusercontent.com/15092120/31658719-17b6bd46-b332-11e7-9303-2ec651c12c52.png)

Also it should work with Web components! Typescript could suggest the component Props inside the Html.

**Comment by octref** [comment]
We don't support Angular. The other one is tracked in #145.
