### ISSUE TITLE
Missing vetur configuration InsertSpaceBeforeFunctionParenthesis

### ISSUE THREAD

**Issue by BruceHem** [vuejs/vetur#487]
I'm using the vetur 0.10.1, and "vetur.format.js.InsertSpaceBeforeFunctionParenthesis": true is missing. Why?

**Comment by FEShuai** [comment]
I had the same problem too and now I can only temporarily close the save auto formatting code， hopefully there is a solution。

**Comment by Monine** [comment]
vutur: v0.10.0
vscode: v1.17.2

setting.json:

add `"vetur.format.defaultFormatter.js": "vscode-typescript"`

**Comment by octref** [comment]
https://vuejs.github.io/vetur/formatting.html

**Comment by BruceHem** [comment]
What is the point of using prettier if i have to change it to "vscode-typescript"?

**Comment by octref** [comment]
@BruceHem that option is a formatting option of `vscode-typescript`. If you are using prettier, the newly added prettier-eslint integration can be used to enforce space before function paren. See https://vuejs.github.io/vetur/formatting.html

**Comment by wfzong** [comment]
a VUE project

VScode:1.19.2
Vetur:0.11.6
Prettier - Code formatter :1.1.0



`    "vetur.format.defaultFormatter.js": "vscode-typescript",
    "prettier.eslintIntegration": true,
    "javascript.format.insertSpaceBeforeFunctionParenthesis": true,
    "typescript.format.insertSpaceBeforeFunctionParenthesis": true
`

the **insertSpaceBeforeFunctionParenthesis** is still not works?

**Comment by BruceHem** [comment]
@wfzong it works with prettier eslint integration.
