### ISSUE TITLE
VLS: Support scaffolds for other editors/IDE

### ISSUE THREAD

**Issue by g-plane** [vuejs/vetur#490]
- [x] I have searched through existing issues
- [x] I have read through docs at https://vuejs.github.io/vetur/
- [x] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

## Info

Vetur version: 0.10.1

## Problem

Scaffolds work well in VS Code. But they may not be friendly to other editors/IDE.

## Reproducible Case

For example in Atom, I have installed `atom-ide-ui`, `language-vue`, `ide-vue` packages.

Auto-completion is fine:
![image](https://user-images.githubusercontent.com/17216317/31831044-a472945c-b5f4-11e7-982b-987b39ef2d05.png)
But the placeholder... (Though that is OK in VS Code.)
![image](https://user-images.githubusercontent.com/17216317/31831114-e38ad7d0-b5f4-11e7-857c-73c8c03ee712.png)

How about making the placeholder flexible instead of being hard-coded?

**Comment by octref** [comment]
If I recall correctly, this is a standard syntax in `CompletionItem` for putting the cursor after the completion.

Atom should support it, not the other way around.
