### ISSUE TITLE
How to set PX not to convert to px ？

### ISSUE THREAD

**Issue by zhump** [vuejs/vetur#493]
```
.name{
 width:100PX;
}
```
prettier formatted this

```
.name{
 width:100px;
}
```

But I do not want PX to be converted 。
https://github.com/cuth/postcss-pxtorem#a-message-about-ignoring-properties

**Comment by zhump** [comment]
close autoUpdate  !

```
	"extensions.autoUpdate": false
```

download 0.9.11 version

```
https://octref.gallery.vsassets.io/_apis/public/gallery/publisher/octref/extension/vetur/0.9.11/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
```

Choose to install from VSIX ！

**Comment by zhump** [comment]
Can css/less/... Style beautification, do not use prettier?

**Comment by HerringtonDarkholme** [comment]
https://github.com/vuejs/vetur/blob/master/docs/formatting.md#general

https://github.com/vuejs/vetur/blob/master/CHANGELOG.md

**Comment by octref** [comment]
We don't support postcss plugins yet.
