### ISSUE TITLE
intellisense can't show vue mamber like 'data','methods'....

### ISSUE THREAD

**Issue by huanent** [vuejs/vetur#495]
- [ ] I have searched through existing issues
- [ ] I have read through docs at https://vuejs.github.io/vetur/
- [ ] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

## Info

- Platform: Win10 creator update
- Vetur version: 0.10.1
- VSCode version:1.17.2

## Problem

I use cue-cli create webpack project , in .vue file Vue member intellisense can't work
![image](https://user-images.githubusercontent.com/9655318/31854413-41b3262e-b6cb-11e7-9960-31f44d774e56.png)

**Comment by octref** [comment]
Did you install Vue as dependency? What's your OS?

**Comment by huanent** [comment]
sorry fo my lost,I use win10 ，and sure install all dependency

**Comment by huanent** [comment]
Today,I found a way make intellisense work,juest input double comma,and use "ctrl+alt+space" to show member list ,please look at the following
![default](https://user-images.githubusercontent.com/9655318/31868332-bf57bfae-b7cf-11e7-973d-6df8ae055adf.png)

**Comment by HerringtonDarkholme** [comment]
Sadly this is a known issue.

`Vue.extend` is overloaded to accept both functional and normal component option.

TypeScript cannot provide completions in overloaded function.
