### ISSUE TITLE
Wrong formatting with two <style> tag with lang="stylus"

### ISSUE THREAD

**Issue by zhenyong** [vuejs/vetur#499]
## Info

- Platform: macOS
- Vetur version: 0.10.1
- VSCode version: 1.17.2

## Problem

If two `<style>` tag with `lang="stylus"`, content of first one may cover the next one.

before
![image](https://user-images.githubusercontent.com/4012276/31976881-9f46cd3c-b8ff-11e7-8fe0-2255145f21a0.png)

after:
![image](https://user-images.githubusercontent.com/4012276/31976883-a492f31a-b8ff-11e7-9c5d-9ea1fbe9e744.png)

**Comment by HerringtonDarkholme** [comment]
We don't support multiple style tags.

**Comment by zhenyong** [comment]
@HerringtonDarkholme 

Nothing break If `lang="scss"`.  Any easy config to fix it?

**Comment by HerringtonDarkholme** [comment]
As already said, we don't support multiple style tags. You should use one style tag if no obvious reason blocks you.

Technically multiple tags can be supported but it need a lot of code refactor.

**Comment by zhenyong** [comment]
@HerringtonDarkholme 

Ok. I did not make it clear. 
Multiple style tag with `lang="scss"` is no problem but  `lang="stylus"` will not work.
Is there any easy way to support without code refactor?

![image](https://user-images.githubusercontent.com/4012276/32045808-d614fc1e-ba06-11e7-8330-8aaa9da8d03c.png)

**Comment by HerringtonDarkholme** [comment]
> Is there any easy way to support without code refactor?

No

**Comment by KennyWho** [comment]
It will be useful for css module. when I use scope and module attribute, I won't use format, because it will make my file wrong output.

**Comment by KennyWho** [comment]
hi @octref 
I try to fix this bug three months ago, but the [pull request](https://github.com/vuejs/vetur/pull/1035) did not pass. It troubled me in my project.
plz fix it as soon as possible.thanks.
