### ISSUE TITLE
"Format document" does not obey ESLint config or Editorconfig

### ISSUE THREAD

**Issue by MikaelEdebro** [vuejs/vetur#500]
My ESLint config is set to not use semicolons. However, when I run Format document (Shift + Alt + F), it inserts semicolons and does not respect my Editorconfig settings to use 4 spaces instead of 2.

This appeared about 2-3 days ago. Before that everything was working fine.

I'm running the latest version of VS Code (1.17.2) and Vetur (0.10.1).

**Comment by HerringtonDarkholme** [comment]
We don't support formatting configuration file.  Probably eslint plugin and vetur collide with each other.

You either need to adjust vetur's config, https://vuejs.github.io/vetur/formatting.html, or you can simply disable vetur's formatting and use another plugin vscode-eslint.

**Comment by octref** [comment]
https://github.com/vuejs/vetur/issues/478 will let you use prettier and eslint together.

Otherwise, you can change `vetur.format.defaultFormatter.js` to `vscode-typescript` and edit formatting settings in `javascript.format.*`.

**Comment by philipithomas** [comment]
@octoref Can you please cut a new release so that these changes are available?
