### ISSUE TITLE
 Can't go to component in the template

### ISSUE THREAD

**Issue by kinanson** [vuejs/vetur#502]
- [y ] I have searched through existing issues
- [y ] I have read through docs at https://vuejs.github.io/vetur/
- [y ] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

## Info

- Platform: Win
- Vetur version:0.10.1
- VS Code version:1.17.2

## Problem

I can't go to component in the template but  in the script that is ok.
When I want to key f12 in the template that will go to vue.d.ts.
This feature ok on old version.
I hope can fix this issue thanks.

Below is my settings
` "vetur.format.defaultFormatter.html": "js-beautify-html"`

Below is demo gif

![1](https://user-images.githubusercontent.com/5998113/32035959-4beb2f6a-ba4f-11e7-9f5d-154e78e8ae0b.gif)

**Comment by HerringtonDarkholme** [comment]
Do you have any example repro?

Can you reproduce it in https://github.com/octref/veturpack ?

**Comment by HerringtonDarkholme** [comment]
I think I know how this happens.

Before we uses bare component object in template definition lookup. Now we uses `Vue.extend` as wrapper. So definition jumps to Vue's definition rather than component.
