### ISSUE TITLE
`key` must not be allowed in `<slot>`

### ISSUE THREAD

**Issue by DrSensor** [vuejs/vetur#505]
- [x] I have searched through existing issues
- [x] I have read through docs at https://vuejs.github.io/vetur/
- [x] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

## Info

- Platform: Linux
- Vetur version: 0.10.1
- VS Code version: 1.17.2

## Problem
When implementing `v-for` in `slot`
```
<slot v-for="(content, id) in contents" :name="id"/>
```
`:key` mustn't be added. Because when added it will show this error
![selection_007](https://user-images.githubusercontent.com/4953069/32093248-de7fe3bc-bb25-11e7-95af-3837acaed70b.png)

However, in linting, it shows this error.
```
[vue-language-server] Elements in iteration expect to have 'v-bind:key' directives.
```

**Comment by HerringtonDarkholme** [comment]
https://github.com/vuejs/eslint-plugin-vue/issues/216
