### ISSUE TITLE
vetur works slow via SAMBA

### ISSUE THREAD

**Issue by SidKwok** [vuejs/vetur#507]
- [x] I have searched through existing issues
- [x] I have read through docs at https://vuejs.github.io/vetur/
- [x] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

## Info

- Platform: macOS
- Vetur version: 0.10.1
- VS Code version: 1.17.2

## Problem

I access my .vue files from a headless Centos Linux VM to my local macOS, and all the feature vetur provides such as emmet and IntelliSense can't work.

for example, I type few characters and except the IntelliSense, but it comes out after one minute:

![1509503651187](https://user-images.githubusercontent.com/13268747/32257994-31f85472-bef3-11e7-84d8-5893e2098b24.jpg)
![6c3ee1a76fe5cf321dc927655a9667cb](https://user-images.githubusercontent.com/13268747/32257999-37a94e12-bef3-11e7-9d7a-af75e1803e9f.png)

And the error I type a minute before just come out in an unpredictable moment.

But vetur works fine in my local.

## Reproducible Case

1. install vetur
2. jsconfig.json
```
{
    "include": [
        "./src/**/*"
    ]
}
```
3. Try to access your .vue files via SAMBA

**Comment by SidKwok** [comment]
Note that I have almost 100 `.vue` files in `src`, and when I put only one `.vue` file in `src`, the IntelliSense comes out in few seconds (still feel delay). But [vscode-eslint](https://github.com/Microsoft/vscode-eslint) and [typescript-styled-plugin](https://github.com/Microsoft/typescript-styled-plugin) seem ok when I access file via SAMBA.

**Comment by HerringtonDarkholme** [comment]
I don't think vetur's script implementation digress much from tsserver. In fact, our implementation is much simpler (and of course more limited).

The performance bottleneck is alleged to be file system access. Thus in https://github.com/vuejs/vetur/blob/master/server/src/modes/script/serviceHost.ts this file.

I suggest you can try plain TypeScript completion. That should be as slow as vetur. If not, I don't know what we can do here...

**Comment by SidKwok** [comment]
yup. It should be the file system access issue. But [path itellisense](https://github.com/ChristianKohler/NpmIntellisense) works fine, it seems that it also needs to due with the file system issue.

**Comment by HerringtonDarkholme** [comment]
@SidKwok  Note path intellisense reads much less. 

https://github.com/ChristianKohler/NpmIntellisense/blob/master/src/provide.ts

Actually one packagejson read. https://github.com/ChristianKohler/NpmIntellisense/blob/master/src/provide.ts#L19

And one readDir https://github.com/ChristianKohler/NpmIntellisense/blob/master/src/provide.ts#L61

But it only occurs when user import like "loadsh/submodule"

**Comment by w1ndy** [comment]
I'm also experiencing the same issue... Intellisense becomes very laggy with TypeScript in Vue files over samba. However normal TypeScript files work just fine...

**Comment by HerringtonDarkholme** [comment]
@w1ndy can you reproduce it outside Samba?

**Comment by w1ndy** [comment]
@HerringtonDarkholme 
It's reproducible without Samba... Actually native TypeScript files do have some lags, but not as serious as Vue files. For example, if I remove a few letters by pressing a few backspaces very quickly from the end of "testObject.testFunction", which becomes "testObject.testFun", it seems that native TypeScript files will cancel error detection in between and immediately throw errors complaining that testFun is not found on testObject. However, Vue files will throw errors one by one complaining that testFunctio, testFuncti, testFunct not found on testObject...

**Comment by w1ndy** [comment]
Another bug related to TypeScript is that if I change declarations in a native TypeScript file, which is imported by a Vue file, I have to restart VSCode to get the Vue file to recognize those changes...

**Comment by HerringtonDarkholme** [comment]
@w1ndy  Thanks for reporting. Would you kindly provide the project you observe lagging? It would be very helpful for us to debug/understand the issue.

For declaration non detected by vetur, it is a long standing problem.  https://github.com/vuejs/vetur/issues/355

**Comment by w1ndy** [comment]
@HerringtonDarkholme 
Sorry I can't disclose the source code right now, and I wasn't able to reproduce it with a small project... I wonder whether a CPU profile will be helpful? [This CPU profile](https://www.dropbox.com/s/m0lg3z0td2hv8zz/CPU-20180126T150641.cpuprofile?dl=0) shows the activity when I was typing ``axisLayoutU`` after ``this.layout.``. The profile ended shortly after the error was gone.

**Comment by HerringtonDarkholme** [comment]
I inspected the CPU profile but cannot find Vetur related performance bottleneck. I can only see tslint-vue's call trace.

This is probably because Vetur's heavy work is done on Vue language server. 

@octref Do you know a quick way to profile server? 

@w1ndy  on the other hand, you can read how to setup local extension development.  https://github.com/vuejs/vetur/blob/master/docs/CONTRIBUTING.md#code

Clone the repo, install deps, and debugging in vscode can help you get profiling.

**Comment by octref** [comment]
@HerringtonDarkholme I don't think there is a documented way to do it. I'll try passing debug params to LS initialization and try attaching Chrome debugger to it.
