### ISSUE TITLE
Comment out html code formatting issues

### ISSUE THREAD

**Issue by yoyo837** [vuejs/vetur#509]
- [X] I have searched through existing issues
- [X] I have read through docs at https://vuejs.github.io/vetur/
- [X] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

## Info

- Platform: Win
- Vetur version: latest
- VS Code version: 1.17.2 64bit

## Problem

Comment out html code and then format it, each time the indentation distance increasing always, except for the first line.

## Reproducible Case

In Vue file

Step:
1. comment out html code
2. format
3. format
4. format
5. format
...

Eeach time the indentation distance increasing always.

Here are some of the settings that may be relevant:
```javascript
  "prettier.singleQuote": true,
  "prettier.semi":false,
  "prettier.printWidth": 120,
  "vetur.format.defaultFormatter.html": "js-beautify-html",
```

If I remove `vetur.format.defaultFormatter.html`, formatting will not work.

**Comment by octref** [comment]
js-beautify bug and they don't fix it. We are already deprecating js-beautify so if you use it, deal with the bug.

**Comment by yoyo837** [comment]
But if not used `"vetur.format.defaultFormatter.html": "js-beautify-html"` will not be able to format html in any vue files, Another option for `vetur.format.defaultFormatter.html` is `none`, no third choice.
