### ISSUE TITLE
Html attributes in templates no longer wrap

### ISSUE THREAD

**Issue by nivv** [vuejs/vetur#510]
- [x] I have searched through existing issues
- [x] I have read through docs at https://vuejs.github.io/vetur/
- [x] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

## Info

- Platform: macOS
- Vetur version: 0.10.1
- VS Code version: 1.17.2 (1.17.2)

## Problem
Before (some other version of vetur) the attributes wrapped as below:
```html
                                    <widget-list :model="page"
                                        :active-image="activeImage"
                                        :active-file="activeFile"
                                        model-name="App\Page"
                                        v-model="widgets.data"
                                        :block-types="selectedPagetype.blockTemplates.data"
                                        :widgets="widgets.data"></widget-list>
```

In this version it becomes as below when formatting (cmd+b)
```html
<widget-list :model="page" :active-image="activeImage" :active-file="activeFile" model-name="App\Page" v-model="widgets.data" :block-types="selectedPagetype.blockTemplates.data" :widgets="widgets.data"></widget-list>
```

I've configured vetur to use "js-beautify-html"

```
"vetur.format.defaultFormatter.html": "js-beautify-html",
```
But this seem to ignore my `.jsbeautifyrc`

Where did the old formatter go?

**Comment by octref** [comment]
Settings for js-beautify https://vuejs.github.io/vetur/formatting.html#js-beautify-html

**Comment by nivv** [comment]
@octref thanks, and sorry for not checking the docs

**Comment by see311** [comment]
@nivv How to set wrapping html attr? sorry, I still not undetstand

**Comment by Devinnn** [comment]
@see311 try this.
```
"vetur.format.defaultFormatterOptions": {
        "js-beautify-html": {
            "wrap_attributes": "force-aligned"
        }
    }
```
