### ISSUE TITLE
Short-syntax nested <template/> tag breaks highlight

### ISSUE THREAD

**Issue by IlyaSemenov** [vuejs/vetur#513]
- [x] I have searched through existing issues
- [x] I have read through docs at https://vuejs.github.io/vetur/
- [x] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

## Info

- Platform: macOS
- Vetur version: 0.10.1
- VS Code version: 1.17.2

## Problem

If I use a nested `<template v-else v-text="some" />` tag, it breaks further `<script>` tag highlight. If I rework it as `<template></template>`, the highlight restores.

<img width="428" alt="screen shot 2017-11-02 at 19 22 57" src="https://user-images.githubusercontent.com/128121/32326048-fe813b10-c003-11e7-9a3c-fcfba1491bd9.png">
<img width="434" alt="screen shot 2017-11-02 at 19 23 16" src="https://user-images.githubusercontent.com/128121/32326052-00e783aa-c004-11e7-94c1-15008fac15db.png">

Error message from Panel -> Output -> Vue Language Server:

```
[Error - 7:26:42 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'version' of undefined
  Code: -32603 
```

## Reproducible Case

```vue
<template>
<h1>
	<a v-if="good" href="http://google.com">Google</a>
	<template v-else v-text="title"/>
</h1>
</template>

<script>
export default {
	data () {
		return {
			good: false,
			title: 'Test',
		}
	},
}
</script>
```

**Comment by LinusBorg** [comment]
Out of interest, what'S the usecase for:
```html
<template v-else v-text="title"/>
```

**Comment by IlyaSemenov** [comment]
`<template>`'s are useful when dealing with plain text, without having to emit redundant `<span>`'s. I prefer `<e v-text="x"/>` to `<e>{{ text }}</e>` as I believe the former expresses more concisely that the entire text node must be constructed from a variable.

Example:
```vue
Hello, <template v-if="user" v-text="user.name"/><template v-else="defaultUserName"/>!
```

will give

```html
Hello, LinusBorg!
```

**Comment by LinusBorg** [comment]
Ha, interesting, never seen that and a bit suprised this even works :D

**Comment by IlyaSemenov** [comment]
Nevermind, they told it's not going to be supported: https://github.com/vuejs/vue/issues/6988
