### ISSUE TITLE
Matching tag not working

### ISSUE THREAD

**Issue by davidsielert** [vuejs/vetur#514]
- [x] I have searched through existing issues
- [x] I have read through docs at https://vuejs.github.io/vetur/
- [x] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

## Info

- Platform: Mac
- Vetur version:  0.10.1
- VS Code version: 1.17.2

## Problem
Matching tag highlighting doesn't work.. related to #194 #204 

<img width="228" alt="screen shot 2017-11-03 at 7 43 01 am" src="https://user-images.githubusercontent.com/456592/32379602-338a9c22-c06b-11e7-9338-ff8bd483eebf.png">
<img width="428" alt="screen shot 2017-11-03 at 7 43 10 am" src="https://user-images.githubusercontent.com/456592/32379609-35dae3e2-c06b-11e7-97f8-5dee16650838.png">

## Reproducible Case
just a blank .vue file with simple html..

**Comment by octref** [comment]
Because you don't have valid html. Remove the extra `<` and it should work.
