### ISSUE TITLE
Vetur doesn't support CSS autocomplete  

### ISSUE THREAD

**Issue by kaivean** [vuejs/vetur#516]
## Info

- Platform: macOS
- Vetur version: 0.10.1
- VS Code version: 1.17.2

## Problem
Vetur doesn't support CSS and JS autocompletion ， looking forward to being similar with .html file 

## Reproducible Case
When type 'bac'  in the <style> tag, there is no intelliSense

**Comment by HerringtonDarkholme** [comment]
Probably you have wrong configuration. Please do provide more information.

Vetur does support css completion.
