### ISSUE TITLE
Feature Request: Disable autocomplete for specific languages in .vue files

### ISSUE THREAD

**Issue by neiloox** [vuejs/vetur#517]
- [x] I have searched through existing issues
- [x] I have read through docs at https://vuejs.github.io/vetur/
- [x] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

## Info

- Platform: macOS
- Vetur version: 0.10.1
- VS Code version: 1.17.2

## Problem
Autocomplete is useful for JS so I want it. I don't need it for CSS because Emmet is usually faster then it. Worse, autocomplete will interfere with my use of Emmet in CSS.

Currenty, I can disable it for all file types, or only for `.vue` files by `editor.quickSuggestions` option in preference, but I can not disable it for sepcific languages in `.vue` files.

## Solution
Add some options in preference for setting the autocomplete of specific languages in .vue files.
Such as:
```
vetur.quickSuggestions.template: {
  html: false,
  jade: true,
},

vetur.quickSuggestions.script: {
  js: true,
  ts: true,
},

vetur.quickSuggestions.style: {
  css: false,
  scss: false,
},
```

**Comment by HerringtonDarkholme** [comment]
@octref  opinion?

**Comment by octref** [comment]
@neiloox Do you think always letting emmet suggestion precede css completion will be ok for you?

**Comment by octref** [comment]
We already make emmet suggestions higher priority than those suggested by css LS.
