### ISSUE TITLE
Typescript autocompletion missing details.

### ISSUE THREAD

**Issue by ImJCabus** [vuejs/vetur#518]
## Info

- Platform: macOS
- Vetur version: 0.10.1
- VS Code version: 1.17.2
- Typescript included as --save-dev: ^2.6.1

## Problem

Autocompletion missing details which are provided in vanilla .ts files.

Example:

Inside test.ts
<img width="778" alt="screen shot 2017-11-05 at 19 59 29" src="https://user-images.githubusercontent.com/6830248/32418170-f8ae9102-c264-11e7-9266-1f5e6d24427e.png">

Inside test.vue
<img width="541" alt="screen shot 2017-11-05 at 20 11 10" src="https://user-images.githubusercontent.com/6830248/32418197-86d82150-c265-11e7-9912-0076ebeb0f78.png">

Note that the method details are missing. There is also no obvious way to make them visible. (No info icon, I've tried `ctrl + space` without luck).
I expected to see the same level of details in .vue files.
Is this a known issue?
Is this simply as detailed as vetur can currently get?
Is there some setting wrong in my VSCode?

I don't know if this has something to do with issue https://github.com/vuejs/vetur/issues/26, but in the screenshots there the method details seem to show up.

## Reproducible Case

Create one `.ts` and one `.vue` file. Try accessing a property of (for simplicity) a random string. Check the documentation details.

**Comment by HerringtonDarkholme** [comment]
This is simply a bug that we miss! 

Thanks for reporting! Will fix it soon.
