### ISSUE TITLE
Please release a new version with bug fixed first

### ISSUE THREAD

**Issue by zhanziyang** [vuejs/vetur#522]
- [x] I have searched through existing issues
- [x] I have read through docs at https://vuejs.github.io/vetur/
- [x] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

First of all, thank you for your hard work on this wonderful plugin.
I noticed that a few bugs had already been fixed with the merged PRs. Please release a new version with bug fixed first. ASAP. As for new features, just take your time. Thank you!

**Comment by octref** [comment]
0.11.0 has been released.
