### ISSUE TITLE
HTML Formatting doesn't work with lang="html"

### ISSUE THREAD

**Issue by geekguy** [vuejs/vetur#525]
- [x] I have searched through existing issues
- [x] I have read through docs at https://vuejs.github.io/vetur/
- [x] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

## Info

- Platform: macOS
- Vetur version:0.11
- VS Code version: 1.17.2 (1.17.2)

## Problem

HTML Onsave formatting doesn't work for following code

```html
<template lang="html">
                <div></div>
</template>
```

But, if you remove lang="html", it fixes the problem and formats properly on save.

**Comment by octref** [comment]
`lang="html"` is not needed. Same for `<script lang="js">`, etc.

**Comment by Phunky** [comment]
Although it's not required for vetur other editor plugins do require it to enable syntax highlighting, so to keep compatibility amongst teams could support for this please be reconsidered.

**Comment by octref** [comment]
We follow Vue SFC spec instead of what other editor is doing: https://vue-loader.vuejs.org/en/start/spec.html
