### ISSUE TITLE
pug formatter

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#527]
We want to include a pug formatter in Vetur.

Options:
- https://github.com/reshape/sugarml (preferred, since I'm doing reshape for html too)
- https://github.com/vingorius/pug-beautify (seems not as actively maintained)

**Comment by iamstevendao** [comment]
I also really want the same "attribute on separate line formatting" in HTML to happen in Pug files.
Something likes this can be done with `"html.format.wrapAttributes": "force-aligned"`:
```html
      <button type="button"
              (click)="modalForm.hide()"
              class="close"
              data-dismiss="modal"
              aria-hidden="true">&times;
      </button>
```
Can we have somethings similar with **Pug**?

**Comment by MadReal** [comment]
Any updates on this?

**Comment by OlzhasAlexandrov** [comment]
Could you please let us know whether you have any plans on supporting `.pug`?

**Comment by tdamsma** [comment]
Is supporting pug still on the roadmap?

**Comment by Bombfuse** [comment]
Also interested in pug support

**Comment by homerjam** [comment]
This extension helps, too bad whatever changes were made haven't been contributed back to the original source but hey ho.

https://marketplace.visualstudio.com/items?itemName=dtx92.vscode-pugvuebeautify

**Comment by octref** [comment]
I dont' mind just adding https://github.com/vingorius/pug-beautify, if that's what you all want. Can you all give https://marketplace.visualstudio.com/itemdetails?itemName=dtx92.vscode-pugvuebeautify a try to see if it's working fine or buggy for you?

**Comment by kbtzr** [comment]
@octref It seems to work when executing it manually. If I have wrong indentation on both pug and stylus code for example it will format only the template region as it should.

So the only thing left for integration would be allowing it on `vetur.format.defaultFormatter.pug` so it gets executed when formatting the whole document, that's correct?

Also I'd like to know if its possible to execute it as the default html formatter with the current Vetur version. Thanks!

**Comment by jessielaf** [comment]
Is this still on the roadmap?

**Comment by octref** [comment]
https://github.com/prettier/plugin-pug seems actively maintained. I'll try to integrate that.

**Comment by the-nicolas** [comment]
> https://github.com/prettier/plugin-pug seems actively maintained. I'll try to integrate that.

...any success?

**Comment by bkarlson** [comment]
hello?

**Comment by Cigoler** [comment]
Would be awesome to use Pug with a formatter in Vue

**Comment by timsayshey** [comment]
@octref Did you run into a blocker with the `plugin-pug` integration? What was the issue?

**Comment by geoidesic** [comment]
So..  how do I get vetur to format pug?

**Comment by homerjam** [comment]
@geoidesic try using prettier maybe - it's working for me using pug in vue sfc's

**Comment by geoidesic** [comment]
Looks like I needed to install `pug-prettier` via npm. Works after that.
