### ISSUE TITLE
Formatting adds indentation to commented HTML in *.vue files

### ISSUE THREAD

**Issue by mcrapts** [vuejs/vetur#528]
## Info

- Platform: Windows 10
- Vetur version: 0.11.0
- VS Code version: 1.18.0
- Vetur settings:
`    "vetur.format.defaultFormatter.html": "js-beautify-html"`

## Problem

When I use Shift-Alt-F to format my .vue files, commented HTML in the <template> section gets indented. 

![2017-11-09 22_04_29- untitled-1 - untitled workspace - visual studio code](https://user-images.githubusercontent.com/16231555/32629711-63da8a16-c59a-11e7-9510-c2e405db626c.png)
![2017-11-09 22_04_39- untitled-1 - untitled workspace - visual studio code](https://user-images.githubusercontent.com/16231555/32629712-6401ba3c-c59a-11e7-889b-4008a127a10a.png)
![2017-11-09 22_04_50- untitled-1 - untitled workspace - visual studio code](https://user-images.githubusercontent.com/16231555/32629713-6419d856-c59a-11e7-8c6b-40199b56e9ac.png)

## Reproducible Case

1. Open VSCode 1.18.0 with Vetur installed and with js-beautify-html set up as the formatter
2. Create a new .vue file, be sure to set language mode to Vue
3. Reproduce the code in the above screenshots
4. Press Shift-Alt-F multiple times

**Comment by octref** [comment]
https://vuejs.github.io/vetur/formatting.html#js-beautify-html

> Alternative html formatter. Deprecated, turned off by default and will be removed soon.
js-beautify has many long-standing bugs that never get fixed. Use at your own risk.

**Comment by octref** [comment]
You can also see https://github.com/vuejs/vetur/issues/488

**Comment by mcrapts** [comment]
Thanks for the the reference to #488. Can you explain why formatting for HTML files works, but HTML in *.vue files doesn't?

**Comment by octref** [comment]
Open VS Code, create a html file like this, and run format:
```html
<div>
          <!--
            hi
          -->
</div>
```

it becomes:

```html
<div>
  <!--
            hi
          -->
</div>
```

The first line of the comment is correctly indented, the rest not.
Vetur adds two spaces before everything inside `<template>`. That's why you see first line of the comment not moved but other lines not.
