### ISSUE TITLE
Including sfc.d.ts disables code completion in single file components

### ISSUE THREAD

**Issue by KokoDoko** [vuejs/vetur#530]
- [x] I have searched through existing issues
- [x] I have read through docs at https://vuejs.github.io/vetur/
- [x] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

## Info

- Platform: macOS
- Vetur version: latest (nov 2017)
- VS Code version: latest (nov 2017)

## Problem

The official vue [docs](https://github.com/vuejs/vue-class-component/blob/master/example/sfc.d.ts) suggest that you enable **.vue file extension support** in Typescript by including this sfc.d.ts file:

```
    declare module "*.vue" {
      import Vue from 'vue'
      export default Vue
    }
```

But adding this seems to conflict with the Vetur plugin. In my `.vue` components, the path / file checking for imports is completely disabled when I use the `sfc.d.ts file`
Also, changes in .vue files are not reflected in autocomplete anymore.

**index.ts**

```
    // only works WITH the sfc.d.ts file
    import App from './components/app.vue'
```

**app.vue**

```
    <template></template>
    <script lang="ts">
        // import checking and code completion only works WITHOUT the sfc.d.ts file!
        import Card from "./card.vue"  
    </script>
    <style></style>
```

Is this a glitch in Vetur? How do I enable .vue file type in typescript without messing up the single-file-component code completion?

**Comment by HerringtonDarkholme** [comment]
Please read the thread thoroughly.

https://github.com/vuejs/vetur/issues/423#issuecomment-340333844

**Comment by KokoDoko** [comment]
Thanks. I have tried adding mapping using `{ "include": [ "src/**/*" ], "compilerOptions": { "baseUrl": ".", "paths": { "components": [ "*", "components/*" ] } } }` in tsconfig. But that's not really the problem. The problem is that intellisense just completely stops inside .vue files. When I compile using webpack, the modules **are** still found and compiled.

**Comment by ryall** [comment]
Agreed, this could be the reason behind the issue: https://github.com/vuejs/vetur/issues/606
