### ISSUE TITLE
 vetur 格式化.vue文件时,未使用自定义的.eslintrc 规则

### ISSUE THREAD

**Issue by xlitter** [vuejs/vetur#533]
- [x] I have searched through existing issues
- [x] I have read through docs at https://vuejs.github.io/vetur/
- [x] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

## Info

- Platform: Win
- Vetur version: 0.11.1
- VS Code version: 1.18.0

## Problem
 vetur 格式化.vue文件时,未使用自定义的.eslintrc 规则

## Reproducible Case
看了下源码, 发现 问题这个文件中
`**\.vscode\extensions\octref.vetur-0.11.1\client\node_modules\vue-language-server\dist\utils\prettier\index.js`
```javascript 
function prettierEslintify(
  code,
  filePath,
  range,
  initialIndent,
  formatParams,
  prettierVSCodeConfig,
  parser
) {
  try {
    const prettierEslint = require('prettier-eslint');
    const prettierOptions = getPrettierOptions(
      prettierVSCodeConfig,
      parser,
      filePath
    );
    const prettierifiedCode = prettierEslint({ <=== here!! 这边少了filePath
      text: code, 
      fallbackPrettierOptions: prettierOptions
    });
    return [
      toReplaceTextedit(prettierifiedCode, range, formatParams, initialIndent)
    ];
  } catch (e) {
    console.log('Prettier-Eslint format failed');
    console.error(e);
    return [];
  }
}
exports.prettierEslintify = prettierEslintify;
```
上面少了filePath会产生两个问题:
- preetier 不能读取到项目中自定义的`.eslintrc`,无法使用自定义规则
- 当添加filePath后还是存在一个问题, eslint-plugin-html在解析文件时,由于文件名后缀是.vue,所以仍会当做 html 文件来解析, 但是这时候传入的`text`,已经是纯js了, 造成无法正确解析

### 这样可以暂时解决这个问题
```
 const prettierifiedCode = prettierEslint({
      text: code, 
      filePath: filePath.replace(/\.vue/, '.js'), 
      fallbackPrettierOptions: prettierOptions
    });
````

**Comment by octref** [comment]
https://github.com/vuejs/vetur/issues/521#issuecomment-342560578

**Comment by Timm-Lee** [comment]
I met the same issue. But I can not find 'vue-language-server' in ~/.vscode/extensions/octref.vetur-0.11.5/client/node_modules
