### ISSUE TITLE
Support for PHP syntax highlighting in custom blocks

### ISSUE THREAD

**Issue by morrislaptop** [vuejs/vetur#536]
- [X] I have searched through existing issues
- [X] I have read through docs at https://vuejs.github.io/vetur/
- [X] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

## Info

- Platform: MacOS
- Vetur version: 0.11.1
- VS Code version: 1.18.0

## Problem

When adding a custom block to use php syntax highlighting I get the error `Failed to generate vue grammar. vetur.grammar.customBlocks contain invalid language values`

## Reproducible Case

Add to user settings:

```
"vetur.grammar.customBlocks": {
  "docs": "md",
  "i18n": "json",
  "php": "php"
}
```

**Comment by HerringtonDarkholme** [comment]
Currently we only support these languages. https://github.com/vuejs/vetur/blob/master/client/src/grammar.ts#L8-L24

It isn't hard to add a new one but would you like to tell us why PHP is used?

**Comment by morrislaptop** [comment]
In my CMS you can add various components to a page. Each component is a Vue component and it contains a PHP custom block which tells the CMS which fields to display in the editor. 

If you can guide me towards adding a new one I can submit a PR

**Comment by octref** [comment]
Can you give me a sample of what your php custom block looks like?

**Comment by morrislaptop** [comment]
```
<acf>
  return component('centre-and-box', [
    'sub_fields' => [
      fragment_field(),
      text_field('heading'),
      text_field('box'),
      image_field('desktop_image'),
      image_field('mobile_image'),
      text_field('caption')
    ]
  ]);
</acf>

<php>
  return function ($content) {
    $content['field_CentreAndBox_mobile_image'] = get_svg_contents($content['field_CentreAndBox_mobile_image']);
    $content['field_CentreAndBox_desktop_image'] = get_svg_contents($content['field_CentreAndBox_desktop_image']);

    return $content;
  };
</php>
```

**Comment by octref** [comment]
I have it mostly working, except the closing `>` in the opening `<php>` and `<acf>`. I'll finish it later.

But beware, all Vetur will do is syntax highlighting. I won't do IntelliSense or other language features for custom blocks.

![image](https://user-images.githubusercontent.com/4033249/32742432-473114d6-c85e-11e7-92d0-433ae678d254.png)

**Comment by morrislaptop** [comment]
That's great!
