### ISSUE TITLE
Emmet not working in .vue files

### ISSUE THREAD

**Issue by BenoitRanque** [vuejs/vetur#538]
- [x] I have searched through existing issues
- [x] I have read through docs at https://vuejs.github.io/vetur/
- [x] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

## Info

- Platform: Win
- Vetur version: 0.11.2
- VS Code version: 1.18.0

## Problem

Emmet does not offer sugestions in .vue files

## Reproducible Case

New install of VSCode. Other extensions disabled.
Emmet will not work within template tags of .vue file

## Solutions

Solved by using the folowing settings in VSCode config file ( `Ctrl + ,` )

```

    "emmet.includeLanguages": {
        "vue": "html"
    }

```
Alternative solution (probably bad idea)
```

    "emmet.triggerExpansionOnTab": true

```

**Comment by octref** [comment]
![emmet](https://user-images.githubusercontent.com/4033249/32748866-557d4ffa-c872-11e7-937e-66f637c32fc6.gif)

Emmet should work out of the box without any settings. You are not getting this behavior?

**Comment by BenoitRanque** [comment]
No

**Comment by octref** [comment]
Do you have other Vue extensions installed?
Can you also provide a gif using https://www.cockos.com/licecap/?

**Comment by BenoitRanque** [comment]
My only extension are Material theme, Material Icons, and Vue VSCode Snippets by sarah.drasner.

Disabling or uninstalling the snippets extension has no effect.

While recording to attempt to resolve, discovered this in only an issue with my old .vue files.

Creating a new file, or even using the vbase snippet of Vue VSCode Snippets in an existing file, solves the problem. Does Vscode "tag" vue files somehow? The older files I edited in Atom.

**Comment by BenoitRanque** [comment]
Issue found.
`lang="html"` property in `template` tag

```
<template lang="html">
  <div>
    <h1>This causes conflict</h1>
  </div>
</template>

<template>
  <div>
    <h1>This works as expected</h1>
  </div>
</template>
```

Works as expected once removed.

**Comment by HerringtonDarkholme** [comment]
May I ask why you specify the lang property? The default value is already `html` .

**Comment by BenoitRanque** [comment]
Was default when expanding `template` in atom. Never bothered to remove.

**Comment by octref** [comment]
That's why I always ask for people to provide screenshots...
Just drop `lang="html"`. It's non-standard and Vetur won't support it.
