### ISSUE TITLE
Vetur version: 0.11.2 adding extra </template> tag on save

### ISSUE THREAD

**Issue by sebastianmacias** [vuejs/vetur#539]
- [x] I have searched through existing issues
- [x] I have read through docs at https://vuejs.github.io/vetur/
- [x] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

## Info

- Platform: Ubuntu 16.04
- Vetur version: 0.11.2
- VS Code version: 1.18.0

## Problem

Vue Language Server:
vetur initialized 

[Screencast](https://drive.google.com/file/d/1TKdQJA3NPQwpjPRa5k1PraPPy3gNoQm6/view)

## Reproducible Case

The latest release (update an hour ago) is adding an extra template tag in my .vue files. Please see the screencast. Thanks

**Comment by sebastianmacias** [comment]
If anyone else is having this issue, you can follow these [steps](https://tpodolak.com/blog/2017/04/09/downgrading-visual-studio-code-extension/) to downgrade to 0.11.1 (I just tested it and 0.11.1 doesn't have these issues).

The URL to download 0.11.1 is:

https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/octref/extension/vetur/0.11.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

After downloading the previous version you will need to rename Microsoft.VisualStudio.Services.VSIXPackage to Microsoft.VisualStudio.Services.VSIXPackage**.vsix** before running the manual install.

**Comment by monochromatique** [comment]
Same here.

Happens in VS Code, after formatting

**Comment by jvbianchi** [comment]
I have the same problem.

Really annoying.

**Comment by dejangeci** [comment]
Happens when `"vetur.format.defaultFormatter.html": "js-beautify-html"` + `Format Document`

**Comment by octref** [comment]
This is fixed and published in 0.11.3.
@sebastianmacias Thanks for the link to the blog. I'll put it in FAQ.

**Comment by sebastianmacias** [comment]
@octref no problem. Thanks for fixing the issue so quickly.
