### ISSUE TITLE
Component/instance options sort

### ISSUE THREAD

**Issue by gjactat** [vuejs/vetur#540]
Hello,
It would be great to have an option that would automatically sorts the component options. Following [these rules](https://vuejs.org/v2/style-guide/#Priority-C-Rules-Recommended-Minimizing-Arbitrary-Choices-and-Cognitive-Overhead), we could keep our components well organized easily.

Maybe with a comment between each section to make it easier to read.

Thanks for your attention

**Comment by octref** [comment]
For html part probably need vue-eslint-parser to sort it. /cc @mysticatea.

For js part it's getting down to AST and reformat it using that rule. It could be useful to some people but it's very tricky to get right. Probably involves modifying the AST using TS language service. @HerringtonDarkholme what's your opinion?

**Comment by octref** [comment]
This belongs to a formatter, or linter with autofix. If someone implements this I'm happy to adopt it.
