### ISSUE TITLE
Can't find module about non-relative path

### ISSUE THREAD

**Issue by vtroop** [vuejs/vetur#545]
## Info

- Platform: Win 10
- Vetur version: 0.11.3
- VS Code version: 1.18.0
- Typescript: 2.6.1
- Vue: 2.5.3

## Problem

Hi, I use typescript to write the .vue file. And vetur always alert this error.
I have tried all of the solution on Google, but failed all the time.
I have tried all the combination of resolve of the tsconfig.json and reinstall yarn the package of the project.
And I have read the #423 , however, i can't find the solution working for me.

![image](https://user-images.githubusercontent.com/8081852/32821858-ad9bb4fc-ca10-11e7-832d-967e0280d931.png)
![image](https://user-images.githubusercontent.com/8081852/32822178-424023d0-ca12-11e7-99d1-2db9272b320d.png)

```json
//tsconfig.json
{
    "compilerOptions":{
        "moduleResolution": "node",
        "baseUrl": ".",
        "paths": {
           "@/*": ["src/*"]
         },
    }
}
```
```typescript
//list.vue
<template/>
<script lang="ts">
import Vue from "vue";
import Component from "vue-class-component";
import Msg from "@/utils/msg";
<script/>
```

```typescript
//msg.ts
/**
 * Created by vtroo on 2017/7/13.
 */
import {Message} from 'element-ui';
export default (type, err: string) => {
  return Message({
    message: err,
    type: type,
    duration: 2 * 1000,
    showClose: true
  });
}

```
```typescript
//global.d.ts
declare module "*.vue" {
    import Vue from 'vue'
    export default Vue
}
declare module "*.html" {
    let template: string;
    export default template;
}

```
```bash
# I have delete some unnecessary files
.
├── appinfo
├── build.sh
├── home.html
├── package.json
├── package-lock.json
├── README.md
├── src
│   ├── api
│   │   ├── category
│   │   │   ├── allCategory.ts
│   │   │   ├── apiDetail.ts
│   │   │   └── myCategory.ts
│   │   └── tools
│   │       ├── apiTest.ts
│   │       └── serviceQuery.ts
│   ├── App.vue
│   ├── components
│   │   ├── common
│   │   ├── test.vue
│   │   ├── tools
│   │   │   └── treeview
│   │   │       ├── TreeViewItemValue.vue
│   │   │       ├── TreeViewItem.vue
│   │   │       └── TreeView.vue
│   │   └── Welcome.vue
│   └── utils
│       └── msg.ts
├── tsconfig.json
├── tslint.json
├── yarn-error.log
└── yarn.lock
```
## Reproducible Case
I don't know why vetur can't read the tsconfig.json and resolve the non-relative path, did I do something wrong?

**Comment by HerringtonDarkholme** [comment]
Can you provide a repo for this?

On the other hand, can you import non relative path in typescript file?

**Comment by vtroop** [comment]
@HerringtonDarkholme I will email you the project, yeah, I can import other file

**Comment by vtroop** [comment]
do you nedd backend service?@HerringtonDarkholme

**Comment by HerringtonDarkholme** [comment]
I cannot reproduce this problem.

![screenshot from 2017-11-15 20-57-01](https://user-images.githubusercontent.com/2883231/32837409-6feefd2a-ca48-11e7-82b5-4d341492a156.png)


Everything seems to work fine.

**Comment by vtroop** [comment]
@HerringtonDarkholme My mistake, after exit and restart my vscode, all the problem goes away.
As far as I'm concerened, the problem may be caused by the vscode, because I hava a couple of days not closing the vscode.
Thanks anyway

**Comment by HerringtonDarkholme** [comment]
wow, didn't think vscode can be such a long-life process :)

Anyway, I think this issue has been solved.

**Comment by vtroop** [comment]
yes, can't agree more, MS' product needs rebooting
Hope this config can help others
