### ISSUE TITLE
How to format existing codebase

### ISSUE THREAD

**Issue by dev-fang** [vuejs/vetur#546]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: win10
- Vetur version: 0.11.3
- VS Code version: 1.18.0

## Problem
Hi, is there a way to format existing codebase just like using prettier cmd, but format vue files?

**Comment by octref** [comment]
Not yet. You can wait for #491.
