### ISSUE TITLE
Go to Definition inconsistencies

### ISSUE THREAD

**Issue by lbogdan** [vuejs/vetur#549]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: latest (0.11.3)
- VS Code version: latest (1.18.0)

## Problem

When using "Go to Definition" on a symbol defined in another file than the one opened (an import, for example), vetur calculates the range incorrectly:
![](https://i.imgur.com/5UHDSxD.png)

After a bit of debugging, I think I found what the issue is:
```javascript
    findDefinition(doc: TextDocument, position: Position): Definition {
      ...
      const fileFsPath = getFileFsPath(doc.uri);
      ...
      const definitionResults: Definition = [];
      definitions.forEach(d => {
        const definitionTargetDoc = getScriptDocByFsPath(fileFsPath);
        if (definitionTargetDoc) {
          definitionResults.push({
            uri: Uri.file(d.fileName).toString(),
            range: convertRange(definitionTargetDoc, d.textSpan)
          });
        }
      });
```
(from https://github.com/vuejs/vetur/blob/master/server/src/modes/script/javascript.ts#L295-L304)

You can see here that if the definition is in a different file, `convertRange()` is called in the context of the current opened file, so the returned range is obviously incorrect.

## (Quick and dirty) Fix

I managed to fix this with a quick and dirty fix which you can see [here](https://github.com/lbogdan/vetur/commit/2b6de27cd1038fa9ad8d3d51b4a2c73cf5d80dc0).

While trying to fix this, the main issue was, if the file containing the definition was never opened, `getScriptDocByFsPath()` returns `undefined`, so we can't use that. We can get a `SourceFile` using `service.getProgram().getSourceFile()`, but I didn't find a reliable way to convert that to a `TextDocument`, so that we can use `convertRange()`. So I just got the source file text, and defined `textPositionAt()`, which does the same thing as `TextDocument.positionAt()`, but for text.

This is the result after the fix:
![](https://i.imgur.com/lfQ4bSv.png)

I'm new to the  whole VSCode extensions / language servers development ecosystem, so I am pretty sure there must be a more elegant solution to this.

**Comment by lbogdan** [comment]
@HerringtonDarkholme Can we leave this opened until a proper fix is in place? Your fix basically replaces a "random" range with a fixed range, but it's still incorrect and can be confusing for the user.

**Comment by HerringtonDarkholme** [comment]
@lboddan I have pushed another fix which computes position by source file text. Check it out in the repo.
