### ISSUE TITLE
Interpolations in Pug templates have no syntax highlighting 

### ISSUE THREAD

**Issue by warent** [vuejs/vetur#552]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.11.3
- VS Code version: 1.18

## Problem

Bound values in a pug template have no syntax highlighting. I would expect the below object to be JS hightlighting.

<img width="631" alt="screen shot 2017-11-17 at 6 56 30 pm" src="https://user-images.githubusercontent.com/13342266/32976361-0edacbd6-cbc9-11e7-8d1f-778b500696e1.png">
<img width="356" alt="screen shot 2017-11-17 at 6 55 55 pm" src="https://user-images.githubusercontent.com/13342266/32976362-0f0d2130-cbc9-11e7-8ef4-b78ecdee4fa1.png">

The highlighting there is as expected with html

## Reproducible Case
Create a simple vue component, set template to jade or pug, bind an attribute to some javascript, note that it looks like a normal string.

**Comment by HerringtonDarkholme** [comment]
Pug syntax highlight isn't first class now. We just include it as third party syntax in template region.

@octref do you want to fully support pug? It requires us to rewrite from scratch, though.

**Comment by octref** [comment]
Yeah, I'm looking into full pug support. Ideally we should find a common denominator between pug/html (a parser generating the same format of AST) and support both and base the vue-html LS on it.
But I also think we need to find a way to make each of the LS modular. Otherwise we are just including more and more things into Vetur core and it would be harder to maintain.

In this particular case we can tweak the pug grammar to support it.

**Comment by minifjurt123** [comment]
I'd love for Pug syntax highlighting to be supported fully!

**Comment by Secular12** [comment]
Is there any updates on this?

**Comment by piemekanika** [comment]
Hope you'll support pug sometime

**Comment by octref** [comment]
Thanks to @Patcher56 this is now available:

![image](https://user-images.githubusercontent.com/4033249/52432756-26874f00-2ac0-11e9-80d0-095868cbdee7.png)

**Comment by marceau-maubert** [comment]
Is it possible to support this for multi-line strings using backticks also?

This is how it is currently.

![image](https://user-images.githubusercontent.com/3979239/112653823-1755ed80-8e4f-11eb-9155-8f352d5d39aa.png)

This works, but https://github.com/prettier/plugin-pug then silently refuses to format the template.

![image](https://user-images.githubusercontent.com/3979239/112653854-1f159200-8e4f-11eb-9143-73f75feb23e7.png)
