### ISSUE TITLE
Obsolet error message "'v-model' directives don't support dynamic input types."

### ISSUE THREAD

**Issue by totalamd** [vuejs/vetur#554]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.11.3
- VS Code version: 1.18.1

## Problem

vue-language-server shows error in case of dynamic `:type` attribute of `<input>` element with a `v-model` attribute while it actually seems to work fine:

```
file: 'file:///***/src/components/FormEditor.vue'
severity: 'Error'
message: ''v-model' directives don't support dynamic input types.'
at: '37,18'
source: 'vue-language-server'
code: 'undefined'
```
![scr](https://user-images.githubusercontent.com/6624080/32989157-c93ddfa8-cd19-11e7-9241-1414cc9407dd.png)

## Reproducible Case

- create .vue single file component
- create <template> section
- create `<input>` element
- add dynamic `:type` attribute
- add `v-model` attribute

**Comment by HerringtonDarkholme** [comment]
Reported at https://github.com/vuejs/eslint-plugin-vue/issues/238
