### ISSUE TITLE
lint css

### ISSUE THREAD

**Issue by zyy7259** [vuejs/vetur#555]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.11.3
- VS Code version: 1.18.1

## Feature request

You have mentioned in #190 that you will open a new issue for linting css. But after searching `is:issue css lint` in [issues](https://github.com/vuejs/vetur/issues?utf8=%E2%9C%93&q=is%3Aissue%20css%20lint) I could not find a related issue. So I open this issue to record this feature.

**Comment by octref** [comment]
It seems people are using https://marketplace.visualstudio.com/items?itemName=shinnn.stylelint.
I don't know if I should include it in Vetur.

**Comment by octref** [comment]
For now I suggest using the stylelint extension.

**Comment by Airkro** [comment]
for some reason, stylelint extension not work in `*.vue`
