### ISSUE TITLE
Cannot formatOnPaste in .vue files

### ISSUE THREAD

**Issue by SCUT-hao** [vuejs/vetur#560]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS High Sierra
- Vetur version: 0.11.3
- VS Code version: 1.18.1

## Problem

With the config "editor.formatOnPaste" setting `true`, when I paste codes in .js files, the editor will automatically format the codes with correct indentations. Moreover, when I move lines up and down with shortcuts `option + up` and `option + down`, the lines will also indent automatically.
 
But in .vue files, it doesn't work at all: the pasted codes have their original indentations. I don't know whether it's my fault for missing some settings or vetur doesn't have such feature.

**Comment by HerringtonDarkholme** [comment]
https://github.com/vuejs/vetur/search?q=formatOnType&type=Issues&utf8=%E2%9C%93
https://github.com/vuejs/vetur/issues/477#issuecomment-337762217
