### ISSUE TITLE
html syntax highlight

### ISSUE THREAD

**Issue by kailniris** [vuejs/vetur#563]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: win10
- Vetur version: 0.11.3
- VS Code version: 1.18.1

## Problem

Can't get any html syntax check to work by default
![html_syntax_1](https://user-images.githubusercontent.com/19587188/33341681-f92fb49e-d47f-11e7-9b76-5b5b7356534c.jpg)

So I tried installed this extension
https://marketplace.visualstudio.com/items?itemName=mkaufman.HTMLHint

and added this block to my user settings
```
  "htmlhint.documentSelector": [
    "html",
    "vue",
    "vue-html"
  ]
```

It works but after I restart vscode the html syntax highlight stops working.
![html_syntax_2](https://user-images.githubusercontent.com/19587188/33341882-898b8978-d480-11e7-81ea-1834e8985332.jpg)

## Reproducible Case
1. Install vetur
2. Do these steps https://vuejs.github.io/vetur/setup.html
3. Install HTMLHint
4. Add the following block to the vscode user config
```
  "htmlhint.documentSelector": [
    "html",
    "vue",
    "vue-html"
  ]
```
5. restart vscode

**Comment by octref** [comment]
There was a bug with syntax-highlight such code, if this is what you meant

```html
<template>
  <template>
  </template> <!-- code after this line won't get syntax-highlighted -->
</template>
```

And I just fixed that in https://github.com/vuejs/vetur/commit/f0711575c95dac5549c973bfc1f65ef43e72c16a

For the syntax-checking, you probably want to open an issue against the HTMLHint extension.

**Comment by kailniris** [comment]
This is unrelated with the issue you mentioned
```
<!--This is the whole template-->
<template>
  <div>
</template>

<!--not this-->
<template>
  <template>
    <div>
  </template>
</template>
```

HTMLHint works fine, i am using it for years. I wanted to try out vetur to use eslint-plugin-vue for vue html linting but i found vetur does not supports basic html syntax highlight. I tried to overcome this limitation with HTMLHint but it stops working after vscode restart if both HTMLHint and vetur is installed.

**Comment by octref** [comment]
> vetur does not supports basic html syntax highlight

Can you upload a screenshot? Linting and syntax-highlighting are two different things. In the two pictures you provided both have syntax-highlighting?

**Comment by kailniris** [comment]
Looks like I mixed up syntax highlight to error highlight/linting, sorry for that!
I am talking about error highlight/linting

Sometimes after 5 minutes the html error highlight starts to work again but not always.
I am talking about htmlhint html error highlight like missing tag pairs. eslint-plugin-vue html error highlight works.

**Plain htmlhint**
![htmlhint](https://user-images.githubusercontent.com/19587188/33678610-818f3700-dabc-11e7-9bb0-08327828bb3f.jpg)

**Plain vetur**
![vetur](https://user-images.githubusercontent.com/19587188/33678617-8761d9da-dabc-11e7-9c9e-0dd9896e8302.jpg)

**htmlhint+vetur**
![htmlhint-vetur](https://user-images.githubusercontent.com/19587188/33678628-8e97a6ee-dabc-11e7-8298-875a5f7939e9.jpg)

**htmlhint+vetur after restart**
![htmlhint-vetur-after-restart](https://user-images.githubusercontent.com/19587188/33678659-ac4531ca-dabc-11e7-87fa-d21ca6661afe.jpg)
