### ISSUE TITLE
The Vue Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by deangoku** [vuejs/vetur#568]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.11.3
- VS Code version: 1.19.0-insider

## Problem
![tim 20171204033654](https://user-images.githubusercontent.com/6375486/33528996-c3283690-d8a4-11e7-9ddd-95da8322ebe5.png)
I have run yarn under C:\Users\DGB\.vscode-insiders\extensions\octref.vetur-0.11.3\client

## Reproducible Case
- Disable all extensions except Vetur
- Open any .vue file

**Comment by octref** [comment]
@dbaeumer is this a regression for https://github.com/Microsoft/vscode/issues/33951?
I'm using 3.5.0.

**Comment by Cherrionella** [comment]
Have same problem here but on linux platform. And yeah, seems that vetur is run in debug mode. After monkeypatching in `client/out/vueMain.js` and setting `const debugServerModule = serverModule` vetur server started normally.

**Comment by octref** [comment]
@Cherrionella BTW are you using Insiders or Stable version? Did you upgrade Vetur and it stopped working, or is it a Insider upgrade made it stop working?

**Comment by octref** [comment]
For me it's the newest update in Insider that breaks it.

@dbaeumer The distributed version with Vetur is 3.4.2, but I guess it doesn't matter since it seems to be a change in Code that makes LS always run in debug mode.

**Comment by Cherrionella** [comment]
@octref Yes. 1.19.0-insiders. I'll check later but it seems to be working with stable one

**Comment by jrieken** [comment]
This is likely https://github.com/Microsoft/vscode/commit/d9a16d31d3bda6e5d0076fc3da02f285975fb772 which causes the extension host to run with `--inspect=<port>` in all cases. We can (temporarily) undo that change but this is an issue with Vetur as customers are free to run the extension host in debug mode, see the `--inspect-extensions` and `--inspect-brk-extensions` flags

**Comment by dbaeumer** [comment]
@jrieken. Thanks

**Comment by octref** [comment]
Decided to always point to the server in `/server`. Mainly for ease of development -- no `installServerIntoExtension`, no `npm link`.

@HerringtonDarkholme FYI and I'll make sure to release VLS each time I do a release.

**Comment by codeitlikemiley** [comment]
im experiencing this issue after i upgraded my code insiders to latest version....

any fix for this?

**Comment by sosoriov** [comment]
@codeitlikemiley  I had the similar issue and my solution was:

- update vscode to the latest version
- Disable Vetur extension
- Uninstall Vetur extension
- Restart vscode
- Install Vetur 

and it works!
