### ISSUE TITLE
format html file problem

### ISSUE THREAD

**Issue by forzeny** [vuejs/vetur#570]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  Win/macOS/
- Vetur version: 0/11/3
- VS Code version:1/18/1

## Problem

when i split the .vue file, some of {{}} can not render in windows but render in macOS
```vue
<template src="./template.html"></template>
```
for a long time to find this problem and i discover that when i use format....
before format 
![image](https://user-images.githubusercontent.com/18499153/33597111-4eec2fb2-d9d9-11e7-8ebb-c3fe4883d59d.png)
after format
![image](https://user-images.githubusercontent.com/18499153/33597127-57539faa-d9d9-11e7-84e7-1f41b994100b.png)

the pic about after format, you know that, it will not render in windows, because the new line
![image](https://user-images.githubusercontent.com/18499153/33597220-ada01028-d9d9-11e7-974b-a8a594e864bd.png)

but it can render in mac OS and i create a rep https://github.com/forzeny/bug-report

so the problem was js-beautify-html?

## my config
```js
{
  // 将设置放入此文件中以覆盖默认设置
  "files.autoSave": "off",
  "window.zoomLevel": -1,
  "editor.wordWrap": true,
  "vsicons.projectDetection.autoReload": true,
  "[javascriptreact]": {},
  "vsicons.dontShowNewVersionMessage": true,
  "extensions.ignoreRecommendations": false,
  "editor.fontSize": 15,
  "editor.tabSize": 2,
  "vetur.format.defaultFormatter.js": "vscode-typescript",
  "vetur.format.defaultFormatterOptions": {
    "js-beautify-html": {
      "indent_size": 1,
      "html": {
        "end_with_newline": false,
        "js": {
          "indent_size": 1
        },
        "css": {
          "indent_size": 1
        }
      },
      "css": {
        "indent_size": 1
      }
    }
  },
  "emmet.syntaxProfiles": {
    "vue-html": "html",
    "vue": "html"
  },
  "eslint.validate": ["javascript", "javascriptreact", "html", "vue"],
  "eslint.options": {
    "plugins": ["html", "vue"]
  },
  "vetur.format.defaultFormatter.html": "js-beautify-html",
  "prettier.useTabs": true,
  "prettier.tabWidth": 2,
  "prettier.singleQuote": true,
  "prettier.semi": false,
  "sync.gist": "5ef1601d2e0c195f1775418242a8c58c",
  "sync.lastUpload": "2017-11-09T12:06:47.212Z",
  "sync.autoDownload": false,
  "sync.autoUpload": false,
  "sync.lastDownload": "",
  "sync.forceDownload": false,
  "sync.anonymousGist": false,
  "sync.host": "",
  "sync.pathPrefix": "",
  "sync.quietSync": false,
  "sync.askGistName": false,
  "workbench.colorTheme": "Monokai",
  "merge-conflict.decorators.enabled": false,
  "merge-conflict.codeLens.enabled": false,
  "git.enabled": false,
  "python.disablePromptForFeatures": [
    "pylint"
  ],
  "workbench.startupEditor": "newUntitledFile",
  "editor.renderIndentGuides": true
}
```

## except 
how to slove this problem

**Comment by octref** [comment]
Vetur does not contain a formatter for html files. You should open an issue at VS Code repo since it's formatted by VS Code's html formatter.

**Comment by forzeny** [comment]
3q

**Comment by JakubKoralewski** [comment]
![image](https://user-images.githubusercontent.com/43069023/54047631-dfcc6800-41d7-11e9-8512-e7efbc90f1d8.png)
