### ISSUE TITLE
Formatting conflict with ES-Lint

### ISSUE THREAD

**Issue by serak** [vuejs/vetur#571]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.11.3
- VS Code version: 1.18.1

## Problem

![image](https://user-images.githubusercontent.com/3592372/33612327-3c43d686-d9e2-11e7-9089-c7e2e1bcb2f8.png)

**Comment by octref** [comment]
Issues without repro cases will be closed. Thanks.
