### ISSUE TITLE
JS FORMATTER IGNORES MY SETTING in VUE: "javascript.format.insertSpaceBeforeFunctionParenthesis": true

### ISSUE THREAD

**Issue by fabioroldan** [vuejs/vetur#575]
**Steps to Reproduce:

1.Type function foo () { }
2.Format the code (shift alt f)
3.Code is formatted to function foo() { } with no mechanism to override

JS FORMATTER IGNORE MY USER SETTINGS in .VUE and .HTML files, in js it works.
"javascript.format.insertSpaceBeforeFunctionParenthesis": true
And of course I get an error in the standard style
[eslint] Missing space before function parentheses. (space-before-function-paren)**

**Comment by octref** [comment]
https://vuejs.github.io/vetur/formatting.html
https://github.com/octref/veturpack/blob/master/.eslintrc#L12-L19
