### ISSUE TITLE
Reduce size of vsce package by excluding devDependencies while publishing

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#577]
When I do `vsce package`, from 0.11.3 to 0.11.4 the vsix package jumped from 30MB to 40MB.

vsce seems to bundle all dependencies in it. We should avoid shipping devDependencies.

**Comment by HerringtonDarkholme** [comment]
Is this solved by #600 ? @octref

**Comment by octref** [comment]
Yep thanks!
