### ISSUE TITLE
[vue-language-server] '<template>' should have end tag.

### ISSUE THREAD

**Issue by NoamGoren** [vuejs/vetur#578]
## Info

- Platform: Win10
- Vetur version:0.11.4
- VS Code version:1.19.0

## Problem
Hello
i've started learn vue today with vetur package and i'm having the following issue:

![image](https://user-images.githubusercontent.com/28135687/34013022-9a5d1f8c-e11e-11e7-8811-70375780493d.png)

I tried to search for this particular issue but i couldn't find anything useful online.
I would be very happy to hear any solutions how to fix it.
Thank you!

**Comment by SquareBeard** [comment]
Same problem here, worked fine in 0.11.3

**Comment by legendofcolt** [comment]
Same issue here.
### Info
Platform: `MacOS 10.13.1`
Vetur version: `0.11.4`
VS Code version: `1.19.0`

**Comment by octref** [comment]
Does it happen to you on https://github.com/octref/veturpack?
Can you make a repro case based on it?

**Comment by slavap** [comment]
Same problem, worked in 0.11.3, but broken in 0.11.4
VS Code: 1.19.0

**Comment by bobmoff** [comment]
Same here.

MacOS 10.13.1
VS Code 1.19.0

**Comment by octref** [comment]
You can disable it temporarily by setting `vetur.validation.template: false`.
Or roll back to 0.11.3.
https://github.com/vuejs/vetur/issues/579#issuecomment-351839757

I can repro and will fix it soon.

**Comment by chelopme** [comment]
Same issue here!

**Comment by NoamGoren** [comment]
@octref  Thank you very much!
Issue closed

**Comment by octref** [comment]
Let's keep it open. This is probably an upstream bug with eslint-plugin-vue that needs to be fixed.

**Comment by octref** [comment]
I'll push a proper fix later today.

**Comment by benji7425** [comment]
Are you able to provide the .vsix download url for 0.11.3 by any chance?

**Comment by benji7425** [comment]
Found it

https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/octref/extension/vetur/0.11.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

**Comment by sunhaoxiang** [comment]
Same problem.

MacOS 10.13.2
VS Code 1.19.0
Vetur 0.11.4

**Comment by forzeny** [comment]
m

**Comment by Hufe921** [comment]
I have the same problem,hope to solve it quickly

**Comment by Hufe921** [comment]
![image](https://user-images.githubusercontent.com/27001251/34022760-0ec4a428-e17c-11e7-8974-79a80cf7da5b.png)

**Comment by mrmengjun** [comment]
same error.

**Comment by BruceHem** [comment]
same error here. 😱

**Comment by kinanson** [comment]
Can modify vue-language-service config myself that a like es-lint?
It isn't apply all the same rule for everybody.
Otherwise vetur can support auto fix template error.

**Comment by Cheng007** [comment]
![qq](https://user-images.githubusercontent.com/13946264/34024842-69f3b73e-e187-11e7-86e0-cc342dfb42be.png)
This issue occoured not only in <template>, but also in <style>

**Comment by mingyec** [comment]
I fixed that by set vetur config, you can set `"vetur.validation.template": false` to your vscode user setting

**Comment by transtone** [comment]
why release a so buggy version?

**Comment by Hufe921** [comment]
@mingyec This method makes the <template> error not detected,so this methods can't solve this problem

**Comment by Hufe921** [comment]
@mingyec This method will make the `<template>` error not found

**Comment by leaper1** [comment]
You need to add ' lang="html" ' , but it's too troublesome and regrets to update it. Hope that the official can fix it.

**Comment by LeoLun** [comment]
same error. 

Platform: Win7
Vetur version: 0.11.4
VS Code version: 1.19.0

**Comment by AchillesG** [comment]
@leaper1 
But after adding 'lang="html"', template will lose emmet support. For me, it's even worse.

**Comment by tyler36** [comment]
Same here, but was working yesterday before VC & Vetur update.
Adding ```lang="html"``` to template fixes issue.

@AchillesG, my Emmet stills works although on further testing, it's because I have following in my settings:
```
    "emmet.includeLanguages": {
        "blade.php": "html",
        "vue": "html"
    }
```


OS: Win10x64
VC: 1.19.0
Vetur: 0.11.4

**Comment by shevchenic** [comment]
@tyler36 

Yes, adding `lang="html"` can fix this issue, but after adding it, VS Code will not prompt close tags.

For example: without `lang="html"`, when i have already input `<div>`, and after type `<`, VS Code will prompt the close tag `</div>`, and i can just click enter to insert the close tag. 

Not sure if this is Vetur's issue or other plugin's issue?

**Comment by tyler36** [comment]
@shevchenic
Yep, confirmed here too.
I'm new to VC and am using an extension [auto-close](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag) to ... well ... auto-close html tags. It was a featured I missed from Sublime so never knew about prompt close tag thing

**Comment by octref** [comment]
Do not listen to people saying `lang="html"`. Do not set `"vue": "html"` in `emmet.IncludeLanguages`.

This has been fixed and I'll publish a new version soon.

**Comment by w3313003** [comment]
same error in 0.11.4
i hope to fix it quickly.
thanks

**Comment by zouhangwithsweet** [comment]
![image](https://user-images.githubusercontent.com/21095710/34032420-034addee-e1b1-11e7-9a3c-1c5ad1f91cab.png)
OS: Win10x64
VC: 1.19.0
Vetur: 0.11.4
