### ISSUE TITLE
Strings must use singlequote quotes

### ISSUE THREAD

**Issue by creativemind1** [vuejs/vetur#582]
Whenever I'm formatting the document, I'm seeing the following issues:
1) Strings must use singlequote
2) Extra semicolon
3) Missing space before function parentheses
Can this be solved?

**Comment by rthel** [comment]
2. this problem seems a `jshint` option, try add these line in VS Code setting:

```
"jshint.options": {
    "asi": true,
    "esversion": 6
}
```

**Comment by octref** [comment]
https://vuejs.github.io/vetur/formatting.html

You should change prettier's config either in VS Code's setting under prettier.* or write a .prettierrc.

**Comment by rafaooliveira** [comment]
hey bro 

1 - if you use some code JS on vue.js you have to try to switch " " to ' ' 
2 - don't use ";" 
3 - default function js vue 
function () {
   return 
}

**Comment by laoshaw** [comment]
why do I have to use '', I have been using "" all othe places, also airbnb recommends using ;, is there a way to override vue.js's coding style?
