### ISSUE TITLE
A question about this update 

### ISSUE THREAD

**Issue by rthel** [vuejs/vetur#583]
## Info

- Platform: macOS 10.13.2
- Vetur version: 0.11.4
- VS Code version: 1.19.0 (1.19.0)

## Problem

In official guide  [camelCase vs. kebab-case](https://vuejs.org/v2/guide/components.html#camelCase-vs-kebab-case) :

It mention that `Again, if you’re using string templates, then this limitation does not apply.`

but the plugin report:

`[vue-language-server] Attribute ':currentPage' must be hyphenated.`

The newest update seems too strict, even it make *.vue more vuenic, I think optional is better.

**Comment by HerringtonDarkholme** [comment]
Hi, we follow eslint-plugin-vue's default configuration in vetur. 

https://github.com/vuejs/vetur/blob/master/docs/linting-error.md#linting

You can disable vetur's linting and uses eslint-plugin in vscode as alternative.

**Comment by rthel** [comment]
@HerringtonDarkholme thanks for answering. : )
