### ISSUE TITLE
[vue-language-server] 'template' should have end tag

### ISSUE THREAD

**Issue by IceDust** [vuejs/vetur#585]
- I have searched through existing issues
- I have read through [docs](https://vuejs.github.io/vetur)
- I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: win 10
- Vetur version: v0.11.4
- VS Code version: 1.19.0

## Problem
It pop this tip: "[vue-language-server] 'template' should have end tag", when 'template' tag have one or more child element

![image](https://user-images.githubusercontent.com/15396113/34030672-f2ef2f5c-e1a8-11e7-9a44-46e6ce094c24.png)
![image](https://user-images.githubusercontent.com/15396113/34030698-0d7cd0a4-e1a9-11e7-8363-d87322e133e0.png)

## Reproducible Case
- Any .vue file could review this problem

**Comment by kftang** [comment]
I have the same issue, just started experiencing this...

**Comment by IceDust** [comment]
@kftang 
Thank you!
Can I close this issue now?

**Comment by octref** [comment]
#578.
