### ISSUE TITLE
'<template>' should have end tag.

### ISSUE THREAD

**Issue by mgesmundo** [vuejs/vetur#587]
## Info

- Platform: macOS 10.12.6
- Vetur version: 0.11.4
- VS Code version: 1.19.0

## Problem

vue-language-server return this error for all components:

```html
'<template>' should have end tag.
```

## Reproducible Case

Create a simple component like this:

```html
<template>
  <div class="my-class">
    {{ message }}
  </div>
</template>
<script>
export default {}
</script>
```
Regards.

**Comment by octref** [comment]
https://github.com/vuejs/vetur/issues?utf8=%E2%9C%93&q=%27%3Ctemplate%3E%27+should+have+end+tag

**Comment by mgesmundo** [comment]
Sorry for duplication. I'm looking for next update that solve this issue.
All the best.
