### ISSUE TITLE
Parsing error: x-invalid-end-tag

### ISSUE THREAD

**Issue by sunhaoxiang** [vuejs/vetur#588]
## Info

- Platform: macOS 10.13.2
- Vetur version: 0.11.5
- VS Code version: 1.19.0

## Problem

```
[eslint-plugin-vue]
[vue/no-parsing-error]
Parsing error: x-invalid-end-tag
```

## Reproducible Case
I used [iview](https://www.iviewui.com/)
```
<template>
    <div>
        <Form>
            <FormItem>
                <Input type="text" v-model="value">
                </Input>
            </FormItem>
        </Form>
    </div>
</template>
```
worked fine in 0.11.3

**Comment by HerringtonDarkholme** [comment]
Please do provide a reproduction example.

**Comment by sunhaoxiang** [comment]
I have updated a reproduction example.
Thanks for the hard work.

**Comment by maxdobeck** [comment]
I'm seeing the parsing error as well.  Using iview <input> tag as well.  Started after the recent upgrade to Visual Studio code 1.19.0 I think.

Vetur: 0.11.5
VS Code: 1.19.0
Ubuntu platform

```
[eslint-plugin-vue]
[vue/no-parsing-error]
Parsing error: x-invalid-end-tag.
```
![screenshot from 2017-12-16 16-40-13](https://user-images.githubusercontent.com/12098882/34075596-48682df8-e280-11e7-8d2c-d3cb2657a611.png)

**Comment by HerringtonDarkholme** [comment]
Actually it is a feature of eslint-plugin-vue.

https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/no-parsing-error.md#wrench-options

Note the option `x-invalid-end-tag`. `Input` is a reserved name for void elemnt in html spec.

Please use another name or turn off vetur's template warning.

**Comment by suconghou** [comment]
Have the same problems too , @HerringtonDarkholme  How can I disable this rule without affect other rules ?

**Comment by HerringtonDarkholme** [comment]
@suconghou We recommend vscode-eslint plugin.

https://github.com/vuejs/vetur/blob/master/docs/linting-error.md#linting-for-template

Turn off Vetur's template validation with vetur.validation.template: false

yarn add -D eslint eslint-plugin-vue@next

Set ESLint rules in .eslintrc.

Install ESLint plugin, add vue to eslint.validate in VS Code config

**Comment by crossz** [comment]
@HerringtonDarkholme this doesn't work for me. And the sequence of the plugins installation by yarn, and rules setting, "false" or the default "off" etc confused me quite a lot. Also, couldn't find any clue about the vetur.validation.template on the vetur plug github page. Please help.

**Comment by Emiya0306** [comment]
## Info
Platform: macOS 10.13.4
Vetur version: 0.12.4
VS Code version: 1.23.1

![alt](https://github.com/Emiya0306/log4js-dateFile-issue/blob/master/WX20180609-163628@2x.png?raw=true)

The same problem in here. Maybe we can switch off the `vetur.validation.template: false`, but I think it is not good idea. Can we fix this one?

**Comment by InstanceOfMichael** [comment]
Just adding my me too:

This triggers the lint error
```
<template>
    <p>
      <h1>
        Items
      </h1>
    </p>
</template>
```
Switching `h1` for `strong` makes it go away
```
<template>
  <section class="container">
    <p>
      <strong>
        Items
      </strong>
    </p>
</template>
```

**Comment by 18612031364** [comment]
> ## Info
> Platform: macOS 10.13.4
> Vetur version: 0.12.4
> VS Code version: 1.23.1
> 
> ![alt](https://github.com/Emiya0306/log4js-dateFile-issue/blob/master/WX20180609-163628@2x.png?raw=true)
> 
> @HerringtonDarkholme The same problem in here. Maybe we can switch off the `vetur.validation.template: false`, but I think it is not good idea. Can we fix this one?

MenuItem  ->  menu-item

**Comment by msqar** [comment]
I'm under the same error, anyone knows how to fix this? is getting really annoying! How can I disable this?

**Comment by fujiayishally** [comment]
Try this:
```
// .eslintrc.js
module.exports = {
//...
 rules: {
    'vue/no-parsing-error': [2, { 'x-invalid-end-tag': false }]
  }
}
```

**Comment by aesyondu** [comment]
> Just adding my me too:
> 
> This triggers the lint error
> 
> ```
> <template>
>     <p>
>       <h1>
>         Items
>       </h1>
>     </p>
> </template>
> ```
> 
> Switching `h1` for `strong` makes it go away
> 
> ```
> <template>
>   <section class="container">
>     <p>
>       <strong>
>         Items
>       </strong>
>     </p>
> </template>
> ```

Just had the same issue. I thought about it for a bit and realized that maybe it doesn't make sense to put `h1`,`h2`,... inside a `p` tag.

**Comment by InstanceOfMichael** [comment]
> Just had the same issue. I thought about it for a bit and realized that maybe it doesn't make sense to put h1,h2,... inside a p tag.

If that's the case, then the error message should say that.

**Comment by jiangqiming** [comment]
i have the same question, need your help, wu wu wu~~~

**Comment by thexeos** [comment]
I'm pretty sure this is not meant to trigger on actual `<input>` elements.

```
ERROR in src/components/SomeComponent.vue:12:6
vue/no-parsing-error: Parsing error: x-invalid-end-tag.
    10 |       type="hidden"
    11 |       name="username"
  > 12 |     ></input>
```

Is there a way to make `vetur` recognize standard HTML tags without causing compilation failures?

**Comment by kirillgroshkov** [comment]
Same issue for this simple code: `<p><div></div></p>`

<img width="436" alt="image" src="https://user-images.githubusercontent.com/4757745/168468288-2a3f81de-5fbe-49ce-9e2c-9735a51ed01b.png">

**Comment by janisskuja** [comment]
> 

I'm having this exact issue... don't want to replace the `p` tag with `div` though.

**Comment by mechanicworld** [comment]
Are there any different options that someone has without replacing `<p></p>` with `<div></div>`
