### ISSUE TITLE
Syntax highlighting breaks with self-closed template/script/style tag

### ISSUE THREAD

**Issue by Akryum** [vuejs/vetur#591]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.11.5
- VS Code version: 1.19.0

## Problem

The syntax highlighting breaks if a `<template|script|style>` tag is self-closed or empty and closed on the same line. The use case is using the `src` attribute.

The highlighting breaks after the first self-closed tag.

This seems to have started happening since update to vetur 0.11.5 and VS Code 1.19.0 from previous versions.

## Reproducible Case

Breaks (self-closing):

```html
<style src="myfile.styl" />

<template>
  <div class="base-image">
    <transition name="zoom">
      <img
        :key="src"
        class="img"
        :src="src"
      />
    </transition>
  </div>
</template>

<script>
export default {
  props: {
    src: {
      type: String,
      required: true,
    },
  },
}
</script>

<style lang="stylus" scoped>
@import "../styles/imports"

.base-image
  flex-box()
  box-center()
  background $md-grey-100
  border-radius 3px
</style>
```

![image](https://user-images.githubusercontent.com/2798204/34044318-cee1cd4e-e1a4-11e7-915b-b582d7cf3326.png)

The code before the self-closing tag is fine:

![image](https://user-images.githubusercontent.com/2798204/34044498-8061e16c-e1a5-11e7-8707-264cd6328c51.png)

Breaks (empty):

```html
<style src="myfile.styl"></style>

<template>
  <div class="base-image">
    <transition name="zoom">
      <img
        :key="src"
        class="img"
        :src="src"
      />
    </transition>
  </div>
</template>

<script>
export default {
  props: {
    src: {
      type: String,
      required: true,
    },
  },
}
</script>

<style lang="stylus" scoped>
@import "../styles/imports"

.base-image
  flex-box()
  box-center()
  background $md-grey-100
  border-radius 3px
</style>
```

![image](https://user-images.githubusercontent.com/2798204/34044333-d9b0ac04-e1a4-11e7-98a6-c598c1a0a1c9.png)

Works (closing tag on next line):

```html
<style src="myfile.styl">
</style>

<template>
  <div class="base-image">
    <transition name="zoom">
      <img
        :key="src"
        class="img"
        :src="src"
      />
    </transition>
  </div>
</template>

<script>
export default {
  props: {
    src: {
      type: String,
      required: true,
    },
  },
}
</script>

<style lang="stylus" scoped>
@import "../styles/imports"

.base-image
  flex-box()
  box-center()
  background $md-grey-100
  border-radius 3px
</style>
```

![image](https://user-images.githubusercontent.com/2798204/34044345-e19fd106-e1a4-11e7-9ac5-ba5879a45863.png)

Breaks (example with template and script tags):

```html
<template src="./myfile.html" />

<script src="./myScript.js" />

<style lang="stylus" scoped>
@import "../styles/imports"

.base-image
  flex-box()
  box-center()
  background $md-grey-100
  border-radius 3px
</style>
```

![image](https://user-images.githubusercontent.com/2798204/34044418-2a2beeb4-e1a5-11e7-97c6-4863809171ff.png)

Works (example with template and script tags):

```html

<template src="./myfile.html">
</template>

<script src="./myScript.js">
</script>

<style lang="stylus" scoped>
@import "../styles/imports"

.base-image
  flex-box()
  box-center()
  background $md-grey-100
  border-radius 3px
</style>

```

![image](https://user-images.githubusercontent.com/2798204/34044440-3e900d22-e1a5-11e7-986d-f2ddce759541.png)

**Comment by ValentineStone** [comment]
> Breaks (empty)

Just to clarify, non empty one line tags break formatting too

![image](https://user-images.githubusercontent.com/15844751/34072034-1279966a-e2a2-11e7-9795-ffabf00dc9a0.png)

**Comment by octref** [comment]
@Akryum I'll release this later today.
![image](https://user-images.githubusercontent.com/4033249/34118409-859cfd94-e3d3-11e7-85fe-12ea10b10c77.png)

@ValentineStone 
If it's on the same line, it has to be a self-closing tag. I won't support your case. If you have styles, write it in multi-lines.

**Comment by octref** [comment]
While fixing https://github.com/vuejs/vetur/issues/593 I made the grammar like this:

If you write
```html
<style>h1 { }</style>
```
The css parts won't get highlighted. But it won't break anything after it.

**Comment by Akryum** [comment]
@octref Did this make it into an update of the extension yet?

**Comment by octref** [comment]
Sorry has been on vacation. Will get an updated changelog from @HerringtonDarkholme then release a new version.

**Comment by lusever** [comment]
This fix stops working if add a slash
<img width="376" alt="screen shot 2018-03-14 at 18 38 35" src="https://user-images.githubusercontent.com/185282/37413526-4f9d880c-27b8-11e8-9572-b58627f39035.png">

**Comment by octref** [comment]
@lusever Can you create a new issue for it? Thanks.

**Comment by str1x** [comment]
same problem =C
Platform: macOS
Vetur version: 0.11.7
VS Code version: 1.23.1
