### ISSUE TITLE
This extension is not highlighting the syntax.

### ISSUE THREAD

**Issue by howilliams** [vuejs/vetur#593]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.11.5
- VS Code version: Version 1.19.0

## Problem
It's not highlighting the syntax for .vue files I opened.
I have just installed the extension and it's not highlighting the file.

I tried to delete .vscode/extensions folder and tried again but no luck.

## Reproducible Case
Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
beautify|Hoo|1.1.1
solidity|Jua|0.0.31
vscode-docker|Pet|0.0.22
html-css-class-completion|Zig|1.14.0
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
gitlens|eam|6.4.0
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
git-project-manager|fel|1.4.0
php-debug|fel|1.12.1
vue-snippets|hol|0.1.5
docthis|joe|0.6.0
Angular2|joh|2.11.2
vscode-language-babel|mgm|0.0.10
node-debug2|ms-|1.19.4
debugger-for-chrome|msj|4.0.0
vetur|oct|0.11.5
sass-indented|rob|1.4.5
react-native-snippet|san|0.6.0
vscode-react-native|vsm|0.5.7
JavaScriptSnippets|xab|1.5.0

**Comment by octref** [comment]
Delete https://marketplace.visualstudio.com/items?itemName=hollowtree.vue-snippets

**Comment by howilliams** [comment]
I have already removed it and same works again.
<img width="839" alt="screenshot at dec 17 13-41-37" src="https://user-images.githubusercontent.com/27955609/34078264-08fd4116-e330-11e7-925e-7e2f43ee88ed.png">

**Comment by howilliams** [comment]
It was working find and after I updated the Visual Studio Code to the new version, it's not working.

**Comment by howilliams** [comment]
Nice to hear that you reopened this.

I am a fan of VS Code and your package.
But I am using atom now.

Does this mean that it is fixed?

**Comment by octref** [comment]
I'll publish an update later today.

**Comment by howilliams** [comment]
Perfect.
