### ISSUE TITLE
Code coloring breaks inside <script> tag

### ISSUE THREAD

**Issue by Hofled** [vuejs/vetur#601]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win 7
- Vetur version: 0.11.5
- VS Code version: 1.19.0

## Problem

The code coloring inside a <script> tag breaks when a .vue file contains empty, inline <template> or <style> tags when they are placed before the <script> tag.
Syntax highlighting persists to work, only the language coloring breaks.
The tags are empty because their content is separated into an external file.

[![https://gyazo.com/c3a887baa27dd3dccfcb22f4353329e9](https://i.gyazo.com/c3a887baa27dd3dccfcb22f4353329e9.gif)](https://gyazo.com/c3a887baa27dd3dccfcb22f4353329e9)

## Reproducible Case

1. Create a new .vue file.
2. Add an empty, inline <template> and <style> tag.
3. Create a <script> tag with some code underneath them.
4. The code within the <script> tag will not be colored at all.

**Comment by octref** [comment]
Already fixed by https://github.com/vuejs/vetur/commit/ed67bf02a4385b6b0fd57c78ba126d82989d160e

**Comment by octref** [comment]
I'll release later today.

**Comment by Hofled** [comment]
Wonderful, thank you very much @octref, forgive me for my foolish mistake for duplicating an already solved issue... ~_~
