### ISSUE TITLE
can't autocomplete like data,methods

### ISSUE THREAD

**Issue by callect** [vuejs/vetur#603]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: windows 10
- Vetur version: 0.11.5
- VS Code version: 1.19.0

## Problem

![1](https://user-images.githubusercontent.com/15102717/34199444-c7e6587c-e5a8-11e7-8fbd-7a7a4b7f3f66.gif)

## Reproducible Case

All of vue files same like the gif, right now.
But it could be worked a few days ago, I don't know it wrong with vscode version or not.
I search issue before, like #495, but I am not use TScript.

**Comment by HerringtonDarkholme** [comment]
Can you produce it in veturpack?

**Comment by lewis-geek** [comment]
I have same problem

**Comment by lewis-geek** [comment]
I have the same problem.

**Comment by HerringtonDarkholme** [comment]
https://github.com/vuejs/vetur/issues/627#issuecomment-357124941
