### ISSUE TITLE
Recursive components cannot display correct code hints

### ISSUE THREAD

**Issue by humreske** [vuejs/vetur#604]
- Both VSCode and Vetur are the latest edition.
- If it is used in a component, all of the code hints in template are invalid.

img:
![aa](https://user-images.githubusercontent.com/16723490/34238900-280f14b4-e63f-11e7-859d-b17906f7ee19.png)

**Comment by humreske** [comment]
![aa](https://user-images.githubusercontent.com/16723490/34238881-13b7ebf8-e63f-11e7-8835-c4de1d2434ef.png)

**Comment by HerringtonDarkholme** [comment]
Please do provide a minimal reproduction.

<img width="621" alt="screen shot 2017-12-25 at 10 11 24 am" src="https://user-images.githubusercontent.com/2883231/34330828-08c64828-e95c-11e7-80cb-72eaf09bc4ec.png">
