### ISSUE TITLE
html syntax error in the style 

### ISSUE THREAD

**Issue by SunOfHomeBoy** [vuejs/vetur#605]
- [ done ] I have searched through existing issues
- [ done ] I have read through [docs](https://vuejs.github.io/vetur)
- [ done ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version: 0.11.5
- VS Code version: 1.19.0
提交 816be6780ca8bd0ab80314e11478c48c70d09383
日期 2017-12-14T12:06:43.492Z
Shell 1.7.9
渲染器 58.0.3029.110
Node 7.9.0
架构 x64

## Problem

html error tips, display in the style.

## Reproducible Case

in the style ,hint html error.
![Uploading image.png…]()

**Comment by SunOfHomeBoy** [comment]
![image](https://user-images.githubusercontent.com/30047595/34242858-d2040632-e658-11e7-8179-6a7618541938.png)

**Comment by HerringtonDarkholme** [comment]
Please provide a minimal reproduction.

**Comment by HerringtonDarkholme** [comment]
Also, note the error comes from eslint-plugin-vue. Probably it is an issue there.
