### ISSUE TITLE
No auto imports within .vue files (Vue SFCs)

### ISSUE THREAD

**Issue by ryall** [vuejs/vetur#606]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows
- Vetur version: 0.11.5
- VS Code version: 1.19.1

## Problem

The vetur intellisense works but I am not getting intellisense from the editor, for example, for auto-imports in TypeScript. Is there a way to fix this? In .ts files the intellisense works fine but I want to keep SFCs.

Example: 
![screen recording 2017-12-21 at 03 09 14 pm](https://user-images.githubusercontent.com/161332/34262522-e7229f6a-e66c-11e7-8866-7d2309f267c3.gif)
(you can see that the auto-import intellisense does not appear and the symbol cannot be found)

**Comment by KokoDoko** [comment]
Same problem here, in my case Vetur even disables intellisense for all types in `.d.ts` files. It makes working with Typescript in SFC's useless, since type checking is not working.

**Comment by HerringtonDarkholme** [comment]
Other than auto import, what other features don't work in SFC?

**Comment by jvbianchi** [comment]
Rename Symbol (F2) also doesn't work

**Comment by HerringtonDarkholme** [comment]
Fix in #609 

We will open another issue for rename symbol.

**Comment by ryall** [comment]
That was fast, thank you!

**Comment by jcjolley** [comment]
I am still experiencing this issue.  Would you like details here, or should I open a new issue?

**Comment by octref** [comment]
@jcjolley Please try to open a new issue and give a repro case out of https://github.com/octref/veturpack

**Comment by EBMike** [comment]
@octref This still doesn't work... I see the pull request, but it apparently didn't fix it. Am I just missing something here?

**Comment by EBMike** [comment]
@octref While this fixed the reference... auto-importing / quick-fix (in vscode) still does not work...

![image](https://user-images.githubusercontent.com/15325216/55235485-093f4900-5204-11e9-8a87-848677bbbd90.png)

If you click quick fix (or `ctrl+.`) it shows...

![image](https://user-images.githubusercontent.com/15325216/55235538-2a079e80-5204-11e9-88ca-5265e208226a.png)
