### ISSUE TITLE
Wrapping attributes after max threshold

### ISSUE THREAD

**Issue by adi518** [vuejs/vetur#607]
- [x ] I have searched through existing issues
- [x ] I have read through [docs](https://vuejs.github.io/vetur)
- [x ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

Been a few good months with Vue and I'm quite frustrated with formatting attributes. Right now they are in long lines which really makes it hard to read and maintain. The Formatter options only allow you to change the line length, which is too generic and doesn't work well for a variety of cases. Can we implement a max-attribute threshold option? I think it'd be an elegant solution to a very annoying problem. Is it in the road-map?

**Comment by octref** [comment]
> Alternative html formatter. Deprecated, turned off by default and will be removed soon.
js-beautify has many long-standing bugs that never get fixed. Use at your own risk.
I plan to contribute to reshape formatter and drop js-beautify eventually.

https://vuejs.github.io/vetur/formatting.html
