### ISSUE TITLE
2 spaces indent for script section

### ISSUE THREAD

**Issue by dakuenjery** [vuejs/vetur#611]
## Info

- Platform: macOS
- Vetur version: 0.11.5
- VS Code version:1.19.1

## Problem

2 spaces indent for script section. Always. I want 4 spaces. And I don't want semi
![image](https://user-images.githubusercontent.com/2018050/34329440-62631a1e-e911-11e7-8d79-430551d5a511.png)

.eslintrc.js

    module.exports = {
        root: true,
        parser: 'babel-eslint',
        parserOptions: {
            sourceType: 'module'
        },
        env: {
            browser: true,
        },
        // https://github.com/standard/standard/blob/master/docs/RULES-en.md
        // extends: 'standard',
        // required to lint *.vue files
        // plugins: [
        //     'html'
        // ],
        // setting: {
        //     'html/indent': '4'
        // },
        // add your custom rules here
        rules: {
            // allow async-await
            'generator-star-spacing': 'off',
            // allow debugger during development
            'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
            'indent': ['error', 4]
        }
    }

Removing .eslintrc.js does not help.

I created .prettierrc file

    # .prettierrc
    tabWidth: 4
    semi: false

Nothing works

**Comment by HerringtonDarkholme** [comment]
I cannot reproduce. Can you reproduce in veturpack, or provide a minimal reproduction?

**Comment by dakuenjery** [comment]
I just click "Format document" in context menu. Vetur with default settings.

**Comment by HerringtonDarkholme** [comment]
I think this should be fine now.
