### ISSUE TITLE
Emmet: Wrap with abbreviation not working

### ISSUE THREAD

**Issue by dimensi** [vuejs/vetur#612]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux, Manjaro 17
- Vetur version: 0.11.5
- VS Code version: 1.19.1

## Problem

![vokoscreen-2017-12-27_13-59-57](https://user-images.githubusercontent.com/11390039/34379883-a82620ce-eb0e-11e7-94e2-f1f70868f872.gif)

## Reproducible Case

select code, click f1, select emmet: wrap with abbreviation

Not working only vue files. Stop working from 1.8 vs code.

**Comment by khaledh** [comment]
I can confirm it's not working in `.vue` files for me either (works in plain HTML files though):

- Platform: Windows 10
- VS Code version: 1.19.1
- Vetur version: 0.11.5

**Comment by HerringtonDarkholme** [comment]
You need to configure emmet to treat vue file as html. Paste these into vscode settings.

```json
    "emmet.includeLanguages": {
        "vue-html": "html",
        "vue": "html"

    }
```

**Comment by edDimensi** [comment]
@HerringtonDarkholme, nope it's worked bad.

**Comment by HerringtonDarkholme** [comment]
Sadly wrapping with abbreviation is a feature coming from vscode itself. The code locates at emmet extension, not in vetur. I suggest you open an issue in vscode repo.

**Comment by khaledh** [comment]
@HerringtonDarkholme Thanks. The solution you provided is good enough for me.

**Comment by dhulme** [comment]
In my config the properties in emmet.includeLanguages were arrays, which seems to have stopped it from working. Must have been a change in emmet code in vs code. Working now with configuration from above.

**Comment by Nejik** [comment]
Also have this issue, code("vue": "html") helps, but it also enable html emmet completions in style and script sections what is bad, seems like "vue-html": "html" is broken for some reason...

**Comment by dawa55** [comment]
thanx @HerringtonDarkholme.
I was going crazy with jsp files also.
didnt work didint work didnt got a answer until here

**Comment by Nejik** [comment]
Nothing changed since my last post, emmet "Wrap with Abbreviation" not working... Latest update.

**Comment by octref** [comment]
@Nejik You should open an issue at VS Code side.

**Comment by Nejik** [comment]
@octref trouble only with vetur, all other dialects and other file types works fine

**Comment by octref** [comment]
@Nejik OK will take a look.

**Comment by ermcgrat** [comment]
> You need to configure emmet to treat vue file as html. Paste these into vscode settings.
> 
> ```json
>     "emmet.includeLanguages": {
>         "vue-html": "html",
>         "vue": "html"
> 
>     }
> ```

Works perfectly for me, thanks!

As others have mentioned, you can now wrap code within the script and style sections as well, but I don't really see an issue with that. Nothing is making you wrap code in cases where it doesn't make sense.

**Comment by Nejik** [comment]
fixed with new vscode update  https://code.visualstudio.com/updates/v1_28#_emmet
The Emmet: Wrap with Abbreviation feature is no longer restricted to files with the .html extension.

**Comment by octref** [comment]
Ok, seems they solved the upstream issue. Now you should be able to use it without adding the `includedLanguages`.
