### ISSUE TITLE
Nuxt Path Mapping

### ISSUE THREAD

**Issue by SteveALee** [vuejs/vetur#613]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

https://vuejs.github.io/vetur/setup.html describnes how to set up when placing components in a folder. eg

```
import a from 'components/a.vue'
import b from 'components/b.vue
```

How does this fit in with Nuxt use of `~`?

```
import a from '~/components/a.vue'
import b from '~/components/b.vue
```

Or should we simply not use it?

PS I tried to find ~ use in the docs but the nuxt site is not reposnding

**Comment by octref** [comment]
https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#vetur-cant-recognize-components-imported-using-webpacks-alias

You can use jsconfig.json
