### ISSUE TITLE
Strange errors

### ISSUE THREAD

**Issue by SteveALee** [vuejs/vetur#614]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version:
- VS Code version:

## Problem

This is strange but I get weird errors about ; in vue files popping up in vscode but only when the following 4 things are true. I cannot copy the error text but there is a snapshot attached

* `"autoFix": true` in workspace settings for eslint vue setting
* `formatOnSave` also true in workspace settings
* .eslintrc.js includes `"parserOptions": { "ecmaVersion": 8 },` so can use async / await
* .eslintrc.js also includes `extends": [ "plugin:prettier/recommended"]`

I have added these to your veturpack example and can reproduce it - when you save files such as the .eslintrc

![image](https://user-images.githubusercontent.com/618922/34442934-80b4a956-ecbd-11e7-9e26-f49ee0dbcb44.png)

I find that the autoFix does nothing for me - I do not get lightbulbs and lint errors are not fixed in vue SFC files. So I just comment that out for now to stop the problem.

If you need more details - like a new branch on veturpack, do let me know - I've spent so much time on this I must get on but can supply over next day or so if you really want.

**Comment by HerringtonDarkholme** [comment]
Please do provide a reproduction repo or provide reproduction steps. Please also try to turn off other extensions during reproduction.

**Comment by HerringtonDarkholme** [comment]
Close due to inactivity.
