### ISSUE TITLE
Completion for added prototype methods

### ISSUE THREAD

**Issue by timster** [vuejs/vetur#618]
## Info

- Platform: macOS
- Vetur version: 0.11.5
- VS Code version: 1.19.1

## Problem

It's possible to add additional prototype methods to Vue:

```javascript
  Vue.prototype.$myMethod = function (methodOptions) {
    // something logic ...
  }
```

This is accessible from within a component using `this.$myMethod()`.

However, code completion does not work. When I type `this.` then `$myMethod()` is not listed as one of the options. All the other built-in Vue options work, so I know vetur is working properly.

Is completion for prototype methods possible, and is there a special way it needs to be set up? I did not see anything in the documentation. 

I'm inclined to think I'd need to extend the Vue type definitions. This is for a JavaScript project (not TypeScript).

**Comment by HerringtonDarkholme** [comment]
TypeScript compiler, and thus Vetur which uses the former, cannot detect additional prototype methods. So you have to provide a declaration for it.

You can refer to the official doc of how to adding new methods for TypeScript to pick up.

https://vuejs.org/v2/guide/typescript.html#Augmenting-Types-for-Use-with-Plugins

> I'm inclined to think I'd need to extend the Vue type definitions. This is for a JavaScript project 

Sadly, you have to add at least one TypeScript declaration file. And then you can use JavaScript in application.
