### ISSUE TITLE
IntelliSense does not work after associate css to postcss 

### ISSUE THREAD

**Issue by zyy7259** [vuejs/vetur#619]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.11.5
- VS Code version: 1.19.1

## Problem

IntelliSense does not work after associate css to postcss 

## Reproducible Case

- install extension https://marketplace.visualstudio.com/items?itemName=octref.vetur
- add configuration "*.css": "postcss" to files.associations
- css intelliSense does not work in css file anymore.

migrated from https://github.com/Microsoft/vscode/issues/40929

**Comment by HerringtonDarkholme** [comment]
As said in the original issue, vetur doesn't add functionality outside of `*.vue` file. It happens to add syntax highlighting to postcss file type but that's purely coincidental. 

Please consider installing a proper extension.
