### ISSUE TITLE
Would you provider a  option of settings that changing default file extension .vue to others such as .atom

### ISSUE THREAD

**Issue by webaifei** [vuejs/vetur#620]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version:
- VS Code version:

**Comment by HerringtonDarkholme** [comment]
What's your use case?

**Comment by HerringtonDarkholme** [comment]
I think the short answer would be no.

However, you can use vscode's file associations setting to map atom file to vue file. Syntax highlighting and basic completion should work.

**Comment by webaifei** [comment]
thanks a lot!

**Comment by hj2060** [comment]
@HerringtonDarkholme Set up .wx or other file associations  .vue。Javascript intellisense does not work

**Comment by HerringtonDarkholme** [comment]
@hj2060 JS completion isn't supported, it is out of our scope.
