### ISSUE TITLE
安装vetur之后为什么语法不高亮，这是什么问题呢？

### ISSUE THREAD

**Issue by MrFashions** [vuejs/vetur#621]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info
![image](https://user-images.githubusercontent.com/32427571/34551854-4fb1f706-f158-11e7-9b4a-6c54d246c76e.png)
![image](https://user-images.githubusercontent.com/32427571/34551858-697fa55c-f158-11e7-9703-96ee7f9d0112.png)

- Platform: 
- Vetur version:
- VS Code version:

**Comment by HerringtonDarkholme** [comment]
Can you reproduce it in veturpack?

**Comment by MrFashions** [comment]
veturpack中重现？没太明白您的意思   @HerringtonDarkholme

**Comment by octref** [comment]
@MrFashions Can you provide a small vue file (copy paste it here) which does not get highlighted?

Also, check your `files.associations` to see if you associated vue to other file types.

**Comment by octref** [comment]
And please use English, thanks.

**Comment by buzzzzer** [comment]
The same issue with new Vetur version on any vue file
![image](https://user-images.githubusercontent.com/1981785/35041668-94936024-fb96-11e7-9680-cf78109c584e.png)

![image](https://user-images.githubusercontent.com/1981785/35041581-49b5cd12-fb96-11e7-87b1-4ba2ed43e980.png)

**Comment by HerringtonDarkholme** [comment]
You didn't successfully install Vetur. Please reinstall it.

**Comment by buzzzzer** [comment]
@HerringtonDarkholme, It works.
Reinstalling Vetur helped
Thank you !
