### ISSUE TITLE
Formatting always adds indent to jsdoc comments in *.vue script snippet

### ISSUE THREAD

**Issue by wenkanglin** [vuejs/vetur#624]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win7
- Vetur version: 0.11.5
- VS Code version: 1.19.1

## Problem

no error message from `Vue Language Server `.

When I formatting the `.vue` file, the indent of jsdoc comments will always increase just like below:

![soogif](https://user-images.githubusercontent.com/21100124/34668506-b2182818-f4a8-11e7-9e58-b2838a8bd8d7.gif)

This is my `vetur` config:

```json
{
  "vetur.format.scriptInitialIndent": true,
  "vetur.format.styleInitialIndent": true
}
```

And I have tried to disable all extensions except `vetur`, but the problem still exists. Looks like only jsdoc format comments has this problem.

## Reproducible Case

1. Create a `.vue` file
2. Add jsdoc format comments at the script snippet or a method defined at `methods` like above gif
3. format code
4. format code
5. ...

**Comment by wenkanglin** [comment]
vscode with new version `1.19.2` still has the problem which will not appear when I disable the `vetur` extension.

**Comment by HerringtonDarkholme** [comment]
@octref This is caused by adding initial indentation to script/style.

We can use prettier without extract script content now, but prettier doesn't support initial indentation.

**Comment by octref** [comment]
I don't think this applies anymore. I cannot repro it.
If this still happens to you, use https://github.com/vuejs/vue-cli to create a sample project where this happens and share it on GitHub with me. Thanks.
