### ISSUE TITLE
Support style scoped snippet instead of style snippet when input scaffold

### ISSUE THREAD

**Issue by wenkanglin** [vuejs/vetur#625]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win7
- Vetur version: 0.11.5
- VS Code version: 1.19.1

## Problem

I hope when I input the `scaffold` in a `.vue` file with empty content, the `vetur` could output snippets:

```vue
<template>

</template>

<script>

</script>

<style scoped>

</style>
```

Because most of time, my colleagues use `css scoped` at a `.vue` file in a project.

## Reproducible Case

1. Maybe like `scaffold with css (scoped)`
2. Output snippets includes style with css scoped

**Comment by HerringtonDarkholme** [comment]
Supporting every combination of style/template/script is too large and unwieldy for plugins and too noisy for users.

However, we do support sections with different attributes.

Meanwhile, custom snippets are still available to every vscode user. https://code.visualstudio.com/docs/editor/userdefinedsnippets

**Comment by wenkanglin** [comment]
Thx for your reply, I didn't know the custom snippets before. I will try it with your suggestion.
