### ISSUE TITLE
新建项目的vetur智能提示全部不起作用。

### ISSUE THREAD

**Issue by bwqgithub** [vuejs/vetur#627]
新建项目的vetur智能提示全部不起作用，之前的项目没问题。
![qq 20180109173657](https://user-images.githubusercontent.com/11193687/34714218-b7ef4f80-f563-11e7-95ab-fa4bafca916e.png)

**Comment by HerringtonDarkholme** [comment]
You need a project setup. Specifically, we don't support completion in a file that is opened alone.
You need to open a directory as a project for vetur to enable completion.

https://github.com/vuejs/vetur/blob/master/docs/setup.md

**Comment by bwqgithub** [comment]
![qq 20180112090158](https://user-images.githubusercontent.com/11193687/34854858-4e53e1a6-f777-11e7-8124-15269cd2b4b9.png)
With the vue cli new project, the smart prompt is invalid and the previous one is ok.

**Comment by HerringtonDarkholme** [comment]
TypeScript has limitation when providing completion in overloaded function.

In this case, `Vue.extend`, which wraps user code in Vetur, is overloaded to accept both functional component option and normal component option.

For Vue version < 2.4, we uses our custom wrapping code to provide completion. However, Vue > 2.5 has much stronger completion for `this` so we choose to use `Vue.extend`.

**Comment by bwqgithub** [comment]
I didn't use TypeScript, how should I solve this problem?

**Comment by HerringtonDarkholme** [comment]
It's not you use TS, Vetur uses TS for completion. 

> how should I solve this problem

Reporting an issue to TS repo, but I think it is probably a "won't fix" or "need proposal" like issue. Overloaded function is hard to resolve.

On the other hand, what we miss is only top level completion, you can still have completion inside methods like `data`.

**Comment by HerringtonDarkholme** [comment]
```ts
interface Functional {
    functional: true
    render(context: { prop: string}): void
}

interface Component {
    render(): void
}

declare function extend(a: Component): void
declare function extend(a: Functional): void

extend({
    functional: true,
    render(context) { // error, context is implicit any
    }
})
```

**Comment by HerringtonDarkholme** [comment]
Also

https://github.com/Microsoft/TypeScript/issues/8005
https://github.com/Microsoft/TypeScript/issues/6405
