### ISSUE TITLE
Strange formatting in .vue files with TypeScript

### ISSUE THREAD

**Issue by AnnAngela** [vuejs/vetur#628]
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have searched through existing issues
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows Pro 10.0.16299.125
- Vetur version: 0.11.5
- VS Code version: 1.19.1

## Problem

I installed the vetur, and everything seemed good.  But when I tried to format a .vue file, it seemed strange.
1. <del>The formatting was forced to ues 2 spaces for indentation.</del>
2. The formatting for TypeScript was very ugly and unreadable.
![image](https://user-images.githubusercontent.com/9762652/34774792-bb569b36-f64b-11e7-8c5a-dd1409cd25fe.png)
I did not change any setting for vetur. And I had disabled other plugins except vetur and tried again, but nothing changed.
And there is only one message in `Panel -> Output -> Vue Language Server` which said `vetur initialized`.

## Reproducible Case

1. Install vetur.
2. Open a .vue file which includes some `<script lang="ts"/>`.
3. Right-click the document to call a context menu.
4. Click "Format Document".

---

UPDATE: I found out the plugin `prettier` and installed it and make some setting, and then the first problem was fixed. But it did not fix the second problem.=。=

**Comment by LinusBorg** [comment]
That's just how prettier formats the code. If you don't like that, don't use prettier.

https://vuejs.github.io/vetur/formatting.html

**Comment by AnnAngela** [comment]
@LinusBorg I tried, and got the same result.
And I made the value of the setting `prettier.printWidth` as 160, and everything is ok.
Thanks for your patience！

**Comment by AnnAngela** [comment]
Close #628
