### ISSUE TITLE
Code indentation problem 

### ISSUE THREAD

**Issue by jenkey2011** [vuejs/vetur#629]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win10 X64
- Vetur version: 0.11.5
- VS Code version:1.19.2

## Problem
When I format the code, the indentation under the `script`  is the same as the `script`. How can indented two spaces ?

### What I really want >>
![snipaste_2018-01-11_16-21-45](https://user-images.githubusercontent.com/20010737/34815224-91971442-f6eb-11e7-9271-7510ae3f8f48.png)

### After formatting >>
![snipaste_2018-01-11_16-08-22](https://user-images.githubusercontent.com/20010737/34815088-0a530bd0-f6eb-11e7-9f3a-4cf93f0149ed.png)

**Comment by HerringtonDarkholme** [comment]
You can configure it in your workspace setting.

The available options are under vscode settings. You can also look at the package.json. 

https://github.com/vuejs/vetur/blob/master/package.json#L273-L277
