### ISSUE TITLE
auto newline after dot

### ISSUE THREAD

**Issue by rashnk** [vuejs/vetur#633]
in vscode  > format document > it inserts newline after every dot as below
```
 getData() {
      db
        .ref('dars/chapter/' + this.$route.params.chapterid + '/' + this.classkey)
        .once('value')
        .then(snapshot => {
```

**Comment by LinusBorg** [comment]
that's just prettier breaking up long lines. you can increase its maxWidth setting to give your code more space.

**Comment by rashnk** [comment]
searched maxwidth in settings and rerturned 0 result,

**Comment by LinusBorg** [comment]
It's a setting for prettier, which is bussed for formatting, and actually called "printwidth"

https://prettier.io/docs/en/options.html#print-width

**Comment by HerringtonDarkholme** [comment]
Indeed, we are using prettier. And you can configure its rule by prettierrc. 

Relevant doc:  https://github.com/vuejs/vetur/blob/master/docs/formatting.md#prettier

And thank @LinusBorg  for helping!
