### ISSUE TITLE
Error when using Deep Selectors

### ISSUE THREAD

**Issue by jvbianchi** [vuejs/vetur#634]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS 10.12.6
- Vetur version: 0.11.5
- VS Code version: 1.19.2

## Problem
Error when using [Deep Selectors](https://vue-loader.vuejs.org/en/features/scoped-css.html#deep-selectors)

![screen shot 2018-01-13 at 10 11 18](https://user-images.githubusercontent.com/13983663/34905936-2dd5e450-f84a-11e7-984f-862eb8b05f7a.png)

**Comment by HerringtonDarkholme** [comment]
We will need to await vscode to support deep selector first.

**Comment by HerringtonDarkholme** [comment]
Also `/deep/` is deprecated, please consider using `>>>`
