### ISSUE TITLE
Is Pug currently supported?

### ISSUE THREAD

**Issue by nachocab** [vuejs/vetur#635]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

I see on the [syntax highlighting page](https://vuejs.github.io/vetur/highlighting.html) that pug is supported, but when I try to save something like this, nothing happens:

<img width="418" alt="screen shot 2018-01-13 at 10 46 42" src="https://user-images.githubusercontent.com/27538/34907587-1d3947f4-f84f-11e7-979e-321e7a056d28.png">

I created my project using [poi](https://github.com/egoist/poi). Should I add anything special in my `jsconfig.json` or my `settings.json` to get it to work?

**Comment by HerringtonDarkholme** [comment]
We do support pug syntax highlighting, but formatting/completion isn't supported.

**Comment by octref** [comment]
@nachocab You can track https://github.com/vuejs/vetur/issues/527
