### ISSUE TITLE
Syntax highlight quoteless attribute values

### ISSUE THREAD

**Issue by rightaway** [vuejs/vetur#639]
- [ x] I have searched through existing issues
- [ x] I have read through [docs](https://vuejs.github.io/vetur)
- [ x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: latest
- VS Code version: latest

## Problem

I think it might be the `v-if`, but all text in the template after a certain part is in the same color rather than being the appropriate color based on syntax. 

![screenshot](https://user-images.githubusercontent.com/3680078/34920141-35b3309a-f96e-11e7-8fbf-967869d0ce9f.png)

**Comment by HerringtonDarkholme** [comment]
@octref Any idea?

Other than the bug, quoting attribute is a good practice and prevent this bug.

**Comment by HerringtonDarkholme** [comment]
Please do add quote to html value.

**Comment by rightaway** [comment]
Since quoting isn't strictly necessary in Vue I don't think it should be necessary to get proper syntax highlighting with this plugin. This plugin should support whatever Vue allows.

![file](https://user-images.githubusercontent.com/3680078/34940299-472b8120-f9ef-11e7-8bb5-a6a2cd5f971c.png)

Here's another example of highlighting issues.
* The `Do new value` each word has a different color
* `attr2=val-other` the `-other` has a different color
* The last few closing tags are red instead of matching the color of the opening tags
* Sometimes an attribute is in green, sometimes yellow, sometimes red
* Sometimes an attribute's value is in green, sometimes yellow, sometimes purple
* 3 occurrences of `error: value` have 3 different combinations of colors

**Comment by HerringtonDarkholme** [comment]
Pull request is welcome.

**Comment by rightaway** [comment]
Can you please reopen this issue? Or should I create a new issue to track this different issue?

**Comment by HerringtonDarkholme** [comment]
I have fixed most problem in https://github.com/vuejs/vetur/commit/6beabd3bd68450d29b80380ef5d9789a1b513074.

If you want to support arbitrary JavaScript expression in unquoted attribute value. Please make a pull request.

**Comment by octref** [comment]
https://github.com/vuejs/vetur/commit/6beabd3bd68450d29b80380ef5d9789a1b513074#diff-3b27ab9208372908cb4b542430fa3915 actually eats `<` and `>` in html template.

![image](https://user-images.githubusercontent.com/4033249/35007892-b535a87e-faaf-11e7-942b-540322e64159.png)

I've reverted it temporarily for releasing -- let's find the proper fix for the syntax highlighting later.

**Comment by HerringtonDarkholme** [comment]
@octref What's the problem in screenshot? It looks good to me, though.

**Comment by rightaway** [comment]
@HerringtonDarkholme I'd like to try out the fix you committed above, do you need to push a new version for an update to be available in the vscode plugin, or is there some way for me to tell vscode to use the latest master from git?

**Comment by HerringtonDarkholme** [comment]
https://github.com/vuejs/vetur/blob/master/docs/CONTRIBUTING.md#code-dev-guide

**Comment by rightaway** [comment]
I've ready both those links now but still can't tell how to update the plugin to the latest master. In my `~/.vscode/extensions/octref.vetur-0.11.5` there's a `.github` but not a `.git` so I can't do a `git pull` from there. Any ideas?

**Comment by HerringtonDarkholme** [comment]
Clone the repo. Open it. Hit `F5`.

**Comment by rightaway** [comment]
The extension got automatically updated to 0.11.6 which includes your fix but still the text from my initial post in this thread looks the same, it hasn't solved the problem. Does it work for you?

**Comment by rightaway** [comment]
Even with the latest from master the quoteless attribute value highlighting isn't working. Is it just failing for me? Says above that it was fixed so just wanted to check if it's something wrong on my part.

**Comment by octref** [comment]
Paste a screenshot. This should be have fixed: https://github.com/vuejs/vetur/issues/666#issuecomment-360111765
