### ISSUE TITLE
There is no auto fix tip in vue file

### ISSUE THREAD

**Issue by soakit** [vuejs/vetur#64]
js files
![image](https://cloud.githubusercontent.com/assets/11240668/23287907/5440bfa2-fa7b-11e6-843d-b95b1aaf5838.png)

**Comment by octref** [comment]
Those are code actions available through Salsa. I don't think this is even available in VSCode's html extension (correct me if I'm wrong)

Maybe you can open an issue on VSCode side to see what they'll do.

**Comment by octref** [comment]
ESLint autofix is already available.
