### ISSUE TITLE
New release of Prettier breaks formatting

### ISSUE THREAD

**Issue by mixedCase** [vuejs/vetur#642]
Title. They seem to have added support for Vue single file components upstream: https://github.com/prettier/prettier-vscode/issues/325

I'm now getting "Unexpected token" Prettier errors in HTML comments and Vue attributes (like `@change`) despite having HTML formatting disabled.

**Comment by HerringtonDarkholme** [comment]
Can you provide a more detailed reproduction step?

**Comment by mixedCase** [comment]
Using Arch Linux, latest Prettier add-on (1.1.0), latest Vetur (0.11.5), latest VSCode (1.19.2), open any single file component where the template has an HTML comment and/or some Vue attribute like `@change`.

Run format with Ctrl+Shift+I or saving with format on save, doesn't matter; if you had any code in <script> that Prettier should've affected you will see it did not get fixed and you will see a new error on the Prettier console (telegraphed by the cross next to the word "Prettier" on the right of the status bar).

I have reproduced this now on 3 different machines with similar configurations.

**Comment by HerringtonDarkholme** [comment]
I have installed prettier vscode but still cannot make prettire format in vue.

Do you have additional configuration?

**Comment by mixedCase** [comment]
If you mean that you cannot get it to format: Yes, that's exactly what I'm reporting. It should work out of the box, just like it was before Prettier updated. Check in the status bar on the bottom right wether you have this:
![Error indicator](https://i.imgur.com/dfdkHyl.png)

If you can see the `X`, click on it, and you will see the error.

**Comment by HerringtonDarkholme** [comment]
OK. I got prettier format Vue file, it works fine. 

However, I cannot reproduce the error. Can you paste your html code?

**Comment by mixedCase** [comment]
```
<template>
  <div />
</template>

<script>
</script>
```

That is enough to trigger this:

![](https://i.imgur.com/IkOmzmk.png)

This is my .prettierrc by the way:

```
{
  "useTabs": false,
  "printWidth": 80,
  "tabWidth": 4,
  "singleQuote": true,
  "trailingComma": "es5",
  "jsxBracketSameLine": false,
  "parser": "babylon",
  "semi": false
}
```

**Comment by mixedCase** [comment]
Huh. I just tested removing the `parser` setting and it's now working. Leaving this issue open in case that should not be the case. (Indeed setting parser to Babylon worked before the Prettier update)

**Comment by HerringtonDarkholme** [comment]
The problem isn't vetur. It lies in prettier-vscode. 

parser option shouldn't be preferred for parsing vue file.

**Comment by HerringtonDarkholme** [comment]
Why it works before? Because erstwhile prettier didn't handle Vue file so it was vetur formatted vue file.

Now prettier handles vue file thus the error.

**Comment by mixedCase** [comment]
Got it. Thanks for the clarification.

**Comment by HerringtonDarkholme** [comment]
You're welcome. And it would be nice if you can report this to prettier, thanks.

**Comment by HerringtonDarkholme** [comment]
Alternatively, you can disable prettier in Vue.

https://github.com/prettier/prettier-vscode#prettierdisablelanguages-default-
