### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#643]
@HerringtonDarkholme hey, thanks a lot for taking care of the issues while I was away...

Think we should make a release to make the bug fixes and features available. Do you mind adding your changes to the changelog, and let me know if there is anything you think we should get fixed before publishing? Thanks.

**Comment by HerringtonDarkholme** [comment]
No problem.

I can do it later, though. Quite busy with day job now.

**Comment by octref** [comment]
Sure, thanks!
