### ISSUE TITLE
No formatting in <style lang="stylus" scoped></style>

### ISSUE THREAD

**Issue by smartion** [vuejs/vetur#645]
在windows平台中使用时，设置{"stylusSupremacy.insertBraces": true,"stylusSupremacy.insertColons": true,"stylusSupremacy.insertSemicolons": true}后，分号，冒号以及大括号没有被自动加上。

--- 

translate by google:

When used in the windows platform, the semicolon, colon, and curly brackets are not automatically appended when {stylusSupremacy.insertBraces ": true," stylusSupremacy.insertColons ": true," stylusSupremacy.insertSemicolons ": true} is set.

**Comment by HerringtonDarkholme** [comment]
I cannot reproduce this. It is more probably you've installed a conflicting extension, e.g. prettier-vscode.
Can you reproduce it with all other extensions disabled?

Chances are slim that only windows have this problem. Stylus supermacy shouldn't have used system specific API.

**Comment by smartion** [comment]
是的，我安装了prettier-vscode这个扩展，我将这个扩展禁用以后便能够格式化了。但是我有一个疑问，prettier-vscode扩展与vetur扩展一起使用了很久了，原来也能格式化，为什么突出便产生冲突了呢？

**Comment by octref** [comment]
https://github.com/prettier/prettier-vscode/pull/310

You should not use prettier-vscode for formatting Vue. It does not allow you to have initialIndent on script/style sections and do not allow you to select non-prettier formatters (for example, the TS formatter for TS section)
