### ISSUE TITLE
html can not be formatted

### ISSUE THREAD

**Issue by lesonky** [vuejs/vetur#649]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version:0.11.6
- VS Code version:0.19.2

## Problem
I update vetur to 0.11.6 and this version `Fix "Language client is not ready yet" error. #576` which was suspected to be the reason of this question, but when I format my vue file as usual , template element does not be formatted, it works well under vscode 0.19.0 and vetur 0.11.5
there is not any error in console

here is my setting:
```
    "vetur.format.defaultFormatter.html": "js-beautify-html",
    "vetur.format.defaultFormatterOptions": {
        "js-beautify-html": {
            "wrap_attributes": "force-aligned",
            "wrap_line_length": 80
        }
    }
```

**Comment by HerringtonDarkholme** [comment]
Probably duplicate of https://github.com/vuejs/vetur/issues/641#issuecomment-358204394

**Comment by lesonky** [comment]
I add this setting
```
 "prettier.disableLanguages": ["vue"]
```
and it works
thanks!

**Comment by joma74** [comment]
In addendum to @lesonky`s post
add 
```
npm add -D js-beautify
```
add
```
VS Code -> Reload window
```
and it works
