### ISSUE TITLE
vetur template validation settings

### ISSUE THREAD

**Issue by taivu** [vuejs/vetur#652]
- [ X] I have searched through existing issues
- [X ] I have read through [docs](https://vuejs.github.io/vetur)
- [X ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.11.6
- VS Code version: 1.19.2

## Problem

` "vetur.validation.template": true` uses `plugin:vue/essential`.

can we have this be configurable? I'd like Vetur to use `plugin:vue/recommended`. I tried to set vetur's setting to be false and installing `eslint` and `eslint-plugin-vue@next`, as instructed [here](https://vuejs.github.io/vetur/linting-error.html#linting-for-template). but when doing it that way, i get npm errors. I thought Vetur should be configurable.

**Comment by octref** [comment]
What's the npm error?

**Comment by taivu** [comment]
```
$ npm install --save-dev eslint-plugin-vue@next
npm WARN eslint-loader@1.9.0 requires a peer of eslint@>=1.6.0 <5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-import@2.8.0 requires a peer of eslint@2.x - 4.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-node@5.2.1 requires a peer of eslint@>=3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-standard@3.0.1 requires a peer of eslint@>=3.19.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-vue@4.0.0 requires a peer of eslint@^3.18.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN vue-eslint-parser@2.0.2 requires a peer of eslint@>=3.9.0 but none is installed. You must install peer dependencies yourself.

+ eslint-plugin-vue@4.0.0
added 1 package, removed 254 packages and updated 1 package in 8.653s
```

then i get when running `npm run dev`:

```
94% asset optimization

 ERROR  Failed to compile with 3 errors                                                                                                                                  1:07:58 PM

 error  in ./node_modules/ansi-html/index.js

Module build failed: Error: ENOENT: no such file or directory, open '/Users/taivu/Documents/Sandbox/Sites/unumapp/node_modules/ansi-html/index.js'

 @ (webpack)-dev-server/client/overlay.js 6:15-35
 @ (webpack)-dev-server/client?http://localhost:8080
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

 error  in ./node_modules/html-entities/index.js

Module build failed: Error: ENOENT: no such file or directory, open '/Users/taivu/Documents/Sandbox/Sites/unumapp/node_modules/html-entities/index.js'

 @ (webpack)-dev-server/client/overlay.js 7:15-39
 @ (webpack)-dev-server/client?http://localhost:8080
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

 error  in ./node_modules/loglevel/lib/loglevel.js

Module build failed: Error: ENOENT: no such file or directory, open '/Users/taivu/Documents/Sandbox/Sites/unumapp/node_modules/loglevel/lib/loglevel.js'

 @ (webpack)-dev-server/client?http://localhost:8080 8:10-29
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```

**Comment by octref** [comment]
It seems you don't have correct dependencies installed. (You are missing html-entities, ansi-html, etc).

Maybe try `rm -rf node_modules` and run a fresh `npm install`?

**Comment by HerringtonDarkholme** [comment]
> "vetur.validation.template": true uses plugin:vue/essential. can we have this be configurable? 

This sounds reasonable. We can support minimal configuration only in Vetur itself. And it can also be applied to vue language server. What's your opinion @octref  ?

**Comment by taivu** [comment]
the dependencies were installed. then installing `eslint-plugin-vue@next` broke the links to dependencies (or maybe because i manually updated the versions in `package.json` before installing?)

another note: my vetur is installed via `Vue.js Extension Pack` in vscode

**Comment by octref** [comment]
@HerringtonDarkholme I don't think we should add more config. This feature is just to show people that Vue has a linter for its template, and we should try to link to a setup doc that could guide people to setup `eslint-plugin-vue` locally. Also we can't live-update the `eslint-plugin-vue` deps without releasing new versions, so I think we should not make user too dependent on it.

**Comment by octref** [comment]
@taivu Now I'm looking at your setup, you should run `npm i -D eslint eslint-plugin-vue`. You need to install both `eslint` and `eslint-plugin-vue` locally for Vetur to work.

Meanwhile I have updated dependencies on `eslint` and `eslint-plugin-vue` on https://github.com/octref/veturpack. You can look at it to see how to correctly setup. Vetur docs are also updated.
