### ISSUE TITLE
end of central directory record signature not found

### ISSUE THREAD

**Issue by unixc3t** [vuejs/vetur#655]
Can 't install the vetur from vscode

**Comment by octref** [comment]
Can't help without any info.

**Comment by unixc3t** [comment]
Platform: linux mint
Vetur version:latest
VS Code version:latest

![dd](https://user-images.githubusercontent.com/4446148/35310553-eea52a42-00ec-11e8-913f-e4a93677b443.png)

@octref

**Comment by octref** [comment]
That error belongs to https://github.com/Microsoft/vscode, so open an issue there.
