### ISSUE TITLE
Vscode cannot install vetur.

### ISSUE THREAD

**Issue by fengshenhai-0727** [vuejs/vetur#657]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version:latest
- VS Code version:latest

## Problem

![image](https://user-images.githubusercontent.com/23276885/35086721-98931976-fc68-11e7-92e8-86acaead5d8f.png)

**Comment by octref** [comment]
Can you try Help -> Developer tools and also paste any error message there?

**Comment by fengshenhai-0727** [comment]
![image](https://user-images.githubusercontent.com/23276885/35087530-6f590388-fc6b-11e7-99b4-be81d0b5a440.png)

**Comment by octref** [comment]
I don't quite know what's happening...So this happens after you tried to install Vetur?

I'd say try to reinstall VS Code / Vetur.

**Comment by octref** [comment]
And this would be an issue for VS Code. So please open an issue at https://github.com/Microsoft/vscode/issues/new. Thanks!

**Comment by fengshenhai-0727** [comment]
Ok, thank you

**Comment by fengshenhai-0727** [comment]
I can install success through VSIX.
