### ISSUE TITLE
Support SugarSS Syntax Highlighting

### ISSUE THREAD

**Issue by wopian** [vuejs/vetur#662]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.11.6
- VS Code version: 1.19.2

## Problem

[SugarSS](https://github.com/postcss/sugarss) is a PostCSS parser for indented syntax and neither the PostCSS grammar used in Vetur or the extension below support the indented SugarSS syntax with the `source.css.postcss` language source

Adding `lang='sss'` and `lang='sugarss'` that sets the region's language to `source.css.sugarss` will add highlighting when [postcss-sugarss-language](https://marketplace.visualstudio.com/items?itemName=mhmadhamster.postcss-language) is installed, like with SASS support. This'll also support Stylelint.

![](https://i.imgur.com/HuM8ouk.png) ![](https://i.imgur.com/oP3FqlN.png)

**Comment by karlos1337** [comment]
@octref Since stylus is nearly abandoned (https://github.com/stylus/stylus/issues/2282), many people (including myself) are looking for an alternative and sugarss seems the one, that's why could be as important, is not like "widen the matrix" is more like a replacement.

**Comment by softwaredeveloptam** [comment]
It would definitely be nice to have this issue resolved if possible. 
A lot of projects at my work are using SugarSS so it would be great to get syntax highlight support.

Would it be okay if I tried to make a PR for this?

**Comment by yoyo930021** [comment]
> It would definitely be nice to have this issue resolved if possible.
> A lot of projects at my work are using SugarSS so it would be great to get syntax highlight support.
> 
> Would it be okay if I tried to make a PR for this?

The PR is welcome without https://github.com/vuejs/vetur/issues/662#issuecomment-360242512.

**Comment by yoyo930021** [comment]
Fixed in https://github.com/vuejs/vetur/pull/2828
