### ISSUE TITLE
hi, all. I got this problem in my project. 

### ISSUE THREAD

**Issue by justnowanna** [vuejs/vetur#663]
- [Y] I have searched through existing issues
- [Y] I have read through [docs](https://vuejs.github.io/vetur)
- [Y] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows 10
- Vetur version: 0.11.6
- VS Code version: 1.19.2

## Problem

![tim 20180123095131](https://user-images.githubusercontent.com/7813730/35254071-b0832558-0023-11e8-9908-429e26ba7844.png)

The prev version of VS Code, it works. Then today I upgrade my VS Code to v1.19.2, it not works. 

It just like the `.txt` file.

I tried the other extends: such as `Vue 2 Snippets`. It works.

Hope your help. Thanks.

**Comment by justnowanna** [comment]
Anyone can help me ? Thanks.

**Comment by octref** [comment]
Uninstall -> Reinstall.

**Comment by justnowanna** [comment]
@octref Thanks. It works. aha. I have try to uninstall VS Code -> reinstall VS Code, but not `vetur`.

Thank you very much.
