### ISSUE TITLE
Docs tags not working anymore

### ISSUE THREAD

**Issue by benavern** [vuejs/vetur#664]
- [ x] I have searched through existing issues
- [ x] I have read through [docs](https://vuejs.github.io/vetur)
- [ x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win 7
- Vetur version: 0.11.6
- VS Code version: 1.19.2 x64

## Problem

![image](https://user-images.githubusercontent.com/5999900/35280877-c839f96e-0051-11e8-851f-e750c8f0e3bd.png)

## Reproducible Case

add a `<docs>` tag in a .vue file and wright something with an apostroph.

It will colorize the texte wrong

my settings are the default ones : 
```
"vetur.grammar.customBlocks": {
    "docs": "md",
    "i18n": "json"
  },
```

I tried running again the grammar generation and reloaded but no result...

**Comment by octref** [comment]
Sorry for the problem. Will release a new version soon.
