### ISSUE TITLE
Syntax highlighting dies with SVG elements inline

### ISSUE THREAD

**Issue by askdesigners** [vuejs/vetur#666]
- [x ] I have searched through existing issues
- [x ] I have read through [docs](https://vuejs.github.io/vetur)
- [ x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.11.6
- VS Code version: 1.19.2 

## Problem

Syntax highlighting dies when there are inlin rendered svg elements.

![image](https://user-images.githubusercontent.com/2891457/35330851-59e9c958-0105-11e8-8d24-733c26f4ca5b.png)

## Reproduce

```
<template>
  <svg :viewBox=viewBox>
    <path
      v-if="!circle"
      :d="path"
      :stroke="color"
      :stroke-width="strokeWidth / 5"
      :opacity="opacity"
    />
    <circle
      v-if="circle"
      :cx="0"
      :cy="0"
      :r="2"
      :fill="color"
      stroke="transparent"
      :stroke-width="0"
      :opacity=opacity
    />
  </svg>
</template>
```

**Comment by askdesigners** [comment]
issue number = 🤘

**Comment by octref** [comment]
Quoteless attribute values have been fixed but not released yet:

![image](https://user-images.githubusercontent.com/4033249/35331571-b7a52766-00bc-11e8-8afe-cdfd9a7afd11.png)
