### ISSUE TITLE
Not using the settings in my eslintrc

### ISSUE THREAD

**Issue by rightaway** [vuejs/vetur#667]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: latest
- VS Code version: latest

## Problem

I have an `~/.eslintrc` file that works when I call `eslint` from the command line. And it works for non-Vue files from within vscode. But Vue files seem to be using their own settings. If I change a Vue setting in my eslintrc, it doesn't get reflected in vscode. I also tried setting `"vetur.validation.template": false` to see if that would work but it doesn't.

**Comment by octref** [comment]
Fork https://github.com/octref/veturpack, show us your setup or there is nothing I can do.

**Comment by rightaway** [comment]
I pulled the latest veturpack and none of the eslint violations are showing up in vscode. However, from the command line there are errors. For example in Counter.vue

```
   5:7   error  Disallow self-closing on HTML void elements (<img/>)  vue/html-self-closing
   5:52  error  Attribute "width" should be on a new line             vue/max-attributes-per-line
   5:64  error  Attribute "height" should be on a new line            vue/max-attributes-per-line
  10:38  error  Attribute "on" should be on a new line                vue/max-attributes-per-line
  17:13  error  '_' is defined but never used                         no-unused-vars
```

And in Home.vue

```
  3:5  error  Require self-closing on Vue.js custom components (<counter>)  vue/html-self-closing
```

However if I delete a line from app.js for example or another JS file, I'll get the appropriate errors showing up in vscode about e.g. `no-undef`.

**Comment by octref** [comment]
Thanks for reporting this -- I got it reproduced. This might be a bigger problem with VS Code. I'll look into it soon.

**Comment by octref** [comment]
What's your VS Code setting? Did you enable it for Vue?
```json
{
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    {
      "language": "vue",
      "autoFix": true
    },
  ]
}
```

**Comment by rightaway** [comment]
I didn't have that enabled. Works now.
