### ISSUE TITLE
Modify the scaffold snippet for TypeScript

### ISSUE THREAD

**Issue by mfarhadpur** [vuejs/vetur#669]
I think it's more useful to change it to the way components should be defined in Vue 2.5.0+ ([link](https://vuejs.org/v2/guide/typescript.html#Basic-Usage)):

```ts
import Vue from 'vue'

export default Vue.extend({

})
```

**Comment by HerringtonDarkholme** [comment]
I think so.
Though pretty many TS users actually use vue-class-component rather than vanilla Vue.

Maybe we can change scaffold in future if Vue officially support native class syntax.

**Comment by HerringtonDarkholme** [comment]
https://github.com/vuejs/vetur/pull/671

**Comment by WORMSS** [comment]
is there anyway for us to have our own ?

we use
```
<template>

</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component({
  components: {},
})
export default class <filename> extends Vue {
}
</script>
```

and I have no idea how I set it to do that rather than `Vue.extends`

**Comment by octref** [comment]
Wait for https://github.com/vuejs/vetur/issues/1151, which I have already started to work on in https://github.com/vuejs/vetur/tree/scaffold-snippet.
