### ISSUE TITLE
how does emmet support <template lang="pug"> ?

### ISSUE THREAD

**Issue by yoyoys** [vuejs/vetur#672]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.11.6
- VS Code version: 11.19.3

## Problem
emmet doesn't support pug file

## Reproducible Case

I tried to use pug as vue file's template engine.
And here's the screenshot:
![image](https://user-images.githubusercontent.com/22124891/35431702-7b777d9a-02b8-11e8-8726-f7ed531f2b78.png)
But when i press tab, i got a normal html string. 
![image](https://user-images.githubusercontent.com/22124891/35431834-1989aa76-02b9-11e8-8f74-bdb1dbabb1b3.png)
Does i missing something?

Thanks for your help.

**Comment by HerringtonDarkholme** [comment]
> emmet doesn't support pug file

Emmet does not support pug. Pug is already very DRY, emmet cannot provide much benefit in pug.

I cannot reproduce the problem, after I press tab.

Please turn off other extensions or revert user settings to default. If the problem still exists, please provide more information.
