### ISSUE TITLE
Adding semicolon to import statement when using Standard ESLint Preset

### ISSUE THREAD

**Issue by bencarter78** [vuejs/vetur#675]
- Platform: Mac
- Vetur version: 0.11.6
- VS Code version: 1.19.3

Hello 

I have enabled the standard ESLint preset which seems to format my code in my .vue files correctly, however, it adds a semicolon to import statements which causes ESLint to report an error.

Any ideas how I can stop it adding the semicolon to my import statements?

Thanks

**Comment by SBado** [comment]
Seems related to #695.

**Comment by octref** [comment]
Auto Import is a feature of the TypeScript language server that Vetur is using. Unfortunately for the auto-import there is currently no pre-formatting so you always get the semicolon.
