### ISSUE TITLE
Fix Vue default object property IntelliSense

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#676]
Ctrl-Space works but typing does not. Just noticed this behavior but it seems to be broken for a while.

![bug](https://user-images.githubusercontent.com/4033249/35494657-ec29d9d4-0470-11e8-89a8-1f943ba6b0ac.gif)

**Comment by HerringtonDarkholme** [comment]
https://github.com/vuejs/vetur/issues/627#issuecomment-357124941

**Comment by HerringtonDarkholme** [comment]
This will be improved after new Vue is released.

Cheers!

**Comment by octref** [comment]
Thanks for keeping the vue type definition in check!

While we are on it, wondering what do you think of https://github.com/Microsoft/vscode/issues/44289?

Seems we have

```
  readonly $refs: { [key: string]: Vue | Element | Vue[] | Element[] };
```

think we should use `HTMLElement` instead of `Element`.

I should really spend some time to have a deeper read of the type definition file...

**Comment by HerringtonDarkholme** [comment]
IIRC Vue's `ref` can be applied to `SVGElement` so `Element` seems better.
Anyway, users probably need to cast `$refs` to specific type before they use. I think it is good to have `Element` in the definition.

**Comment by octref** [comment]
I see, that make sense. Thanks for the explanation.
