### ISSUE TITLE
Component mixin methods/members are not recognized by VSCode Intellisense

### ISSUE THREAD

**Issue by lexasss** [vuejs/vetur#678]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.11.7
- VS Code version: 1.19.3

## Problem

Component mixin methods/members are not recognized by VSCode Intellisense

fullscreen.js
![image](https://user-images.githubusercontent.com/5399223/35626953-07bbb25e-06a0-11e8-87a7-bc284a65ed60.png)

component.vue
![image](https://user-images.githubusercontent.com/5399223/35626972-17e69cc0-06a0-11e8-979f-96a762ddcddf.png)

Message shown wthen hovering 'makeFullscreen':
![image](https://user-images.githubusercontent.com/5399223/35626982-265c863e-06a0-11e8-94c3-8da24b6ff1c6.png)

No error messages in Panel -> Output -> Vue Language Server

## Reproducible Case

0. create and init a simple Vue project ("vue init webpack mixin-test")

1. create jsconfig.json file in the project root folder:

```
    {
      "compilerOptions": {
        "alwaysStrict": true,
        "checkJs": true,
        "target": "es2016",
        "module": "es2015",
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "baseUrl": "./", 
        "paths": {
          "@/*" : ["*"],  
          "~/*" : ["*"]    
        }
      },
      "include": [
        "**/*",
        "**/*.vue"
      ]
    }
```

2. create a mixinTest.vue file in `/src/components`:

```
<template>
  <div id="page">
    <button @click="click"> Click me </button>
    <div ref="fullscreen"> Content </div>
  </div>
</template>

<script>
const fullscreen = {
  methods: {
    makeFullscreen(element) {
      // ...
    }
  }
};

export default {
  mixins: [fullscreen],
  methods: {
    click(e) {
      this.makeFullscreen(this.$refs.fullscreen);
    }
  }
};
</script>
```

3. the method call "makeFullscreen" in the "this.makeFullscreen(this.$refs.fullscreen);" line will be underlined with red.

**Comment by HerringtonDarkholme** [comment]
It's a known issue.

We cannot support mixin for now in TypeScript, which is the engine underhood.

If you uses mixin a lot, you can consider using class style API provided in other libraries.
