### ISSUE TITLE
Please leave alone line wrapping

### ISSUE THREAD

**Issue by mariusa** [vuejs/vetur#679]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux 
- Vetur version: 0.11.7
- VS Code version: 1.19.2

## Problem

VS code already has settings for line wrapping, and those work fine:
```
    "editor.wordWrap": "wordWrapColumn",
    "editor.wordWrapColumn": 120,
```

When vetur is enabled, it wraps lines around column 80. Please, let VS code handle that. Focus on areas not handled by VS code.

## Reproducible Case
```
            if (typeof ar.applicability === "object" && ar.applicability) {
              if (typeof ar.applicability.when === "object" && ar.applicability.when) {
                if (typeof ar.applicability.when.months_since_last === "number" 
                && moment().diff(al.done_date, "months")  > ar.applicability.when.months_since_last) {
                  l("ar.applicability.when.months_since_last2", ar.applicability.when.months_since_last,
                    moment().diff(al.done_date, "months")
                  )
                }
              }
            }

```

**Comment by octref** [comment]
Vetur uses prettier for `<script>` section, so you need to set its `printWidth` accordingly.

**Comment by kazzit** [comment]
However, It doesn't seem to follow my "printWidth" under vscode's extension settings. I tested by setting it to 30, which affects all .js file but none of the .vue files.

**Comment by SandyGifford** [comment]
Yeah, this issue should not have been closed so quickly.  The provided solution does not fix it at all.

**Comment by octref** [comment]
https://vuejs.github.io/vetur/formatting.html#settings

![image](https://user-images.githubusercontent.com/4033249/57315219-fe4fc200-70a7-11e9-8b05-2da06c0e3e82.png)

**Comment by SandyGifford** [comment]
from my config
``` javascript
    "vetur.format.defaultFormatterOptions": {
        "prettier": {
            "tabWidth": 4,    // works
            "printWidth": 400 // does not work
        }
    },
```

Yeah - it doesn't seem to make a difference.  I've tried both in `.prettierrc` and in the VSCode settings file.

**Comment by octref** [comment]
@SandyGifford Please give a repro by forking https://github.com/octref/veturpack.

![format](https://user-images.githubusercontent.com/4033249/57480386-69d69280-7254-11e9-87c6-b98bd057f828.gif)

**Comment by bcreeves** [comment]
I have the same issue.

**Comment by DarkLite1** [comment]
Having the same issue. I have code like this:

```javascript
watch(() => Screen.width, () => setMiniState(undefined))
```

That gets formatted to this:
```javascript
watch(
   () => Screen.width,
   () => setMiniState(undefined)
)
```

Even when adding `printWidth` to `.prettierrc.js`:
```javascript
module.exports = {
    singleQuote: true,
    semi: false,
    trailingComma: "es5",
    arrowParens: "always",
    printWidth: 120
}
```

Although I now that the settings from the `.prettierrc.js` file are respected. Because semicolons are added/removed based on these settings. So I would expect Vetur to respect the `printWidth` line too.

**Comment by kalimulhaq** [comment]
I have the same ISSUE. This is such a weird and ugly behavior.

**Comment by yoyo930021** [comment]
Please provide reproducible case and **open a new issue.**
https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md

**Comment by tenzint** [comment]
I'd like to thank this issue page and contributors here. I needed this:

```js
"vetur.format.defaultFormatterOptions": {
        "prettier": {
            "tabWidth": 4,    // works
            "printWidth": 100 // does not work
        }
    },
```
I had an issue where Vetur would format in a way that it combines 2-6 lines into one line and that would cause me the `max-len` error of eslint. After setting the printWidth to 100 or less, everything becomes simple to solve eslint errors. Vetur will not deny Insertion of new lines any more upon formatting. 
(I actually like to format my codes)

**Comment by Mater1996** [comment]
"prettyhtml": {
      "wrapAttributes": false,
      "printWidth": 80
    },

**Comment by rzfzr** [comment]
> ```js
> "vetur.format.defaultFormatterOptions": {
>         "prettier": {
>             "tabWidth": 4,    // works
>             "printWidth": 100 // does not work
>         }
>     },
> ```

this worked for me, after disabling the prettier extension

**Comment by phillip-haydon** [comment]
None of the suggestions above work for me, all i have is VSCode with vetur installed, nothing else, nothing works.

**Comment by yoyo930021** [comment]
I will lock this issue.
If you have same problem, please open a new issue with template.
