### ISSUE TITLE
Vetur suddenly ignoring prettier.arrowParens 

### ISSUE THREAD

**Issue by abenz1267** [vuejs/vetur#683]
- [ x] I have searched through existing issues
- [ x] I have read through [docs](https://vuejs.github.io/vetur)
- [ x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: 0.11.7
- VS Code version: 1.19.3

## Problem

I haven't changed anything, but suddenly the "prettier.arrowParens" setting is ignored within *.vue files, it will always remove the parentheses even though the setting is set to "always". It was working before. Nothing changed. Every other setting seems to be working, f.e. "prettier.semi". I've reinstalled Vetur and Prettier ...without success.

Any idea?

Regards

**Comment by IwYvI** [comment]
I think this problem is caused by the newest update of prettier.
> vue is now disabled by default. Opt-in by removing vue from disableLanguages setting

I added this to my `setting.json` in vscode and reload the window, then it solved
`"prettier.disableLanguages": []`

**Comment by abenz1267** [comment]
Answer by @IwYvI helped!

**Comment by xereda** [comment]
@IwYvI I tried this, but I did not succeed.

**Comment by xereda** [comment]
This worked for me: https://alligator.io/vuejs/eslint-vue-vetur/
