### ISSUE TITLE
Auto-import component in <script> when using component in template/javascript

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#684]
Similar to JS/TS's auto import in VS Code: https://code.visualstudio.com/updates/v1_18#_auto-import-for-javascript-and-typescript

**Comment by octref** [comment]
As a note, need to look into how to resolve path aliases...

**Comment by alexbudure** [comment]
+1

**Comment by sanwv** [comment]
+1
---
hop import absolute,like `@/compoents/CommonComp.vue`.  path alias `@` defined in `jsconfig.json`

**Comment by adams549659584** [comment]
+1

**Comment by Terry-Su** [comment]
+1

**Comment by dotgreg** [comment]
+1

**Comment by rothsandro** [comment]
+1

**Comment by zamboney** [comment]
+1

**Comment by slanden** [comment]
+1

**Comment by Terry-Su** [comment]
after a long while I reviewed the progress today, and still found auto import via alias not working. However, found a very useful tool, not perfect but enough for auto **importing vue components** and js variables **using alias**(remember to use shortcut to import vue components):
[vue-helper ](https://github.com/jiaolong1021/vue-helper )

![](https://common.xxpie.com/helps-internalComponent.gif)

**Comment by jd-0001** [comment]
+1

**Comment by RobertLemmens** [comment]
+1, moving from webstorm to vscode + vetur, i find this one of the biggest features im missing.

**Comment by wanxe** [comment]
This is failing again after the last [release](https://github.com/vuejs/vetur/releases/tag/v0.25.0). Works again by reverting the version to the previous one.

**Comment by materia2021** [comment]
any update on this?

**Comment by danranVm** [comment]
![vetur](https://user-images.githubusercontent.com/25052421/98933459-a0612d80-251b-11eb-8a45-d6ac1f1f7752.gif)

@yoyo930021 hi, it doesn’t work, when I don’t use export default, but name the component.

**Comment by pikax** [comment]
@danranVm that's not a valid SFC component [SFC spec](https://vue-loader.vuejs.org/spec.html#script please use `export default` if you are exporting )

You `HelloWorld.vue` component won't work, you can test by:
```vue
<template>a = {{ a }}</template>
<script lang="ts">
import {defineComponent} from 'vue'
export const HelloWorld = defineComponent({
  setup() {
    return {
      a: 1,
    };
  },
});
</script>

```

**Comment by danranVm** [comment]
@pikax I see. thank you for your answer.

**Comment by kwarnkham** [comment]
Auto import works but how to make the component's name PascalCase.
Right now only kebab-case is available.
