### ISSUE TITLE
Cannot format custom block

### ISSUE THREAD

**Issue by ambar** [vuejs/vetur#690]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: latest
- VS Code version: latest

## Problem

user config
```json
"vetur.grammar.customBlocks": {
  "docs": "md",
  "i18n": "json",
  "config": "json"
},
```

vue file: 

```xml
<config>
{
  "array": [
    "foo",
    "bar",
  ],
}
</config>
```

## Reproducible Case

there's some options like `"vetur.format.defaultFormatter.js": "prettier",` can we add a md/json formatter option?

**Comment by octref** [comment]
No. Once you have it people are gonna ask for more, such as completion, error checking...
Having syntax highlighting is as far as I'll go with custom blocks.
