### ISSUE TITLE
High CPU Usage on macOS & dependency resolution failure

### ISSUE THREAD

**Issue by ajmas** [vuejs/vetur#691]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS 10.13.3 - MacBookAir6,2
- Vetur version: 0.11.7
- VS Code version: 1.20.0

## Problem

From time to time I will encounter high CPU usage as soon I try to resolve a dependency (ctrl-click -> select 'go to definition') in a `.vue` file. The 'Code Helper' process will at that point be around 90% CPU until I kill the process or quit Visual Studio Code. 

At the time this happens no code dependencies can be resolved. For example, the following type of import will sometimes resolve in the dependency not being found and being in a stuck:

```
import CrudView from '../../components/CrudView';
```

## Reproducible Case

I haven't been able to establish a pattern, though would appreciate any suggestions that could help me identify which code might be causing the issue, which I could then share with you.

**Comment by octref** [comment]
When I'm fixing #547 I'll put in some options to turn on logging. Currently there is no way to easily collect log so I can't offer much help yet.

**Comment by Tang-RoseChild** [comment]
same problem +1

**Comment by zhaopengme** [comment]
same problem +1

**Comment by jamki** [comment]
same problem +1

**Comment by vfasky** [comment]
same problem +1

**Comment by negope** [comment]
same problem +1

**Comment by octref** [comment]
For people who were having CPU spike yesterday, 0.12.3 should fix it for you. The original poster's problem is a different one.

@ajmas Is your project open source or sharable with me?

**Comment by ajmas** [comment]
I work on multiple projects, some of which are closed source. The one I remember having issues with was closed source. I haven’t spent too much time on that project recently, so I can’t say if the issue still presents itself.

**Comment by octref** [comment]
@ajmas Thanks - if you do manage to narrow down to a repro case where this constantly happen, feel free to reopen the issue or open a new one.
