### ISSUE TITLE
Toggling suggestion between PascalCase and kebab-case for Vue components in template tags

### ISSUE THREAD

**Issue by goandbuild** [vuejs/vetur#696]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: 0.11.7
- VS Code version: 1.20

## Request

Right now Vetur suggests components only in kebab-case format. An option to toggle suggestions from command palette between kebab-case and PascalCase for Vue components inside `template` tags would be great!

**Comment by cesalberca** [comment]
Even more so when the Vue team recommends using pascal case format for naming components: https://vuejs.org/v2/style-guide/#Multi-word-component-names-essential

With some guidance I would like to tackle this issue :)

**Comment by samuells** [comment]
Hi I would be super interested in this feature .. any status .. any way to help? 😉

**Comment by dsanders11** [comment]
@samuells, I'd say the code to change is [this line](https://github.com/vuejs/vetur/blob/5cdcf428df8976ca1b1ea4bd08e5baf8998ebf6c/server/src/modes/script/findComponents.ts#L74) by the looks of it.

However, there's apparently a whole client-server architecture here, and that bit is on the server, so plumbing through from the client to the server is beyond me without looking into it in-depth. The actual change is probably trivial, the plumbing the setting all the way through, not so much.

**Comment by paparent** [comment]
+1 on this! It's been two months I've setup a new project in Vuejs, and now with the eslint config, it error (or warning) on kebab-casing in .vue files. Yes I can disable but I like the idea!

Especially that I've to setup a demo project with VueJS with all the tooling around it so I can sell the idea of using VueJS to replace current frontend technology :)

**Comment by paparent** [comment]
Closed there: https://github.com/vuejs/vetur/commit/cff817223cd0532dcab0b67da9627b7abf551fd1 named initial instead of PascalCase though, like in guide [Component name casing in templates strongly recommended](https://vuejs.org/v2/style-guide/#Component-name-casing-in-templates-strongly-recommended)

**Comment by octref** [comment]
OH I didn't realize we still have this issue. Thanks for closing.
