### ISSUE TITLE
Option to disable Vetur's snippets

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vetur#698]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: All
- Vetur version: 0.11.7
- VS Code version: 1.20.0-insider

## Problem

I really like that Vetur includes a great set of snippets out-of-the-box and I'm glad they are enabled by default, but snippets can also be very personal or project-specific. Large teams, especially, sometimes use custom snippets as a way to guide team members to use internal conventions. In these cases, the presence of Vetur's own snippets can create confusion about which to use.

I'm not sure if this is possible in VS Code, but could Vetur provide an option to disable its own snippets, for users that prefer to write their own?

**Comment by octref** [comment]
`vetur.completion.useScaffoldSnippets` has been added.

**Comment by chrisvfritz** [comment]
Thank you! 🙏

**Comment by geozak** [comment]
This was removed in: 54385909ed8f4359f2d07e2703169b3402bc2383

**Comment by octref** [comment]
@geozak Thanks. Just for those who came to here as well, you can use 

```json
{
  "vetur.completion.scaffoldSnippetSources": {
    "workspace": "",
    "user": "",
    "vetur": ""
  }
}
```

to disalbe all snippets

**Comment by chrisvfritz** [comment]
Out of curiosity, why were strings that are either empty/non-empty with emoji defaults used for these settings, instead of booleans that are either true or false? 😄 I got this question in a workshop recently and I didn't know the answer.

**Comment by octref** [comment]
You can put any text / emoji there — I chose a few emoji for good visual scannability.
