### ISSUE TITLE
EACCES permission error when trying to install extension (Mac OS High Sierra)

### ISSUE THREAD

**Issue by cyrus86** [vuejs/vetur#699]
## Info

- Platform: macOS
- Vetur version: current (error is about trying to install the extension)
- VS Code version: 1.12.1 (latest stable)

## Problem
Error message: 
`EACCES: permission denied, open '/var/folders/xq/8yrkk6xn1p9btfkhp6jdgckdpx3v2_/T/a56e830b-0d87-4be8-9357-6b481661b2f8'` with variable last folder name in path, but always in subfolder T (which apparently is the $TMPDIR on mac as I just found out)
I can, however, install and update other extensions without a problem so my current understanding is that the error might be with Vetur itself.

![a56e830b-0d87-4be8-9357-6b481661b2f8_info_and_extension__vetur_ _screenshot-log](https://user-images.githubusercontent.com/2669027/36400289-5e93d0ac-1613-11e8-8ced-956a76857fc7.png)

**Comment by HerringtonDarkholme** [comment]
We don't have any special setting up in the extension.

Would you like delete the var folder in the report and retry?

**Comment by cyrus86** [comment]
I actually tried that several times, yes. But sadly that didn't help. It throws the same error.  
This seems to be the same problem: https://github.com/Microsoft/vscode/issues/41797

**Comment by octref** [comment]
This needs to be fixed by VS Code, not Vetur. Although it's interesting that this only happens for Vetur but not other extensions (@cyrus86 Does installing [prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) give you the same error?)

**Comment by octref** [comment]
Anyway let's track this in VS Code repo, since I don't believe there is anything special that Vetur does to cause this error.

**Comment by cyrus86** [comment]
Initial problem was resolved by uninstalling security software (TrendMicro). Refer to https://github.com/Microsoft/vscode/issues/43993#issuecomment-440535115 thread for details.

**Comment by octref** [comment]
Thanks for the updates and closing one issue for me!
