### ISSUE TITLE
gql inside vue file not properly highlighted

### ISSUE THREAD

**Issue by mastito03** [vuejs/vetur#701]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: 0.11.7
- VS Code version: 1.20.1

## Problem

I'm using vue-apollo and using gql syntax inside vue file. but gql syntax not properly highlighted.

this what inside .vue file
![.vue file](https://i.imgur.com/OaULrzm.png)

this what inside .js file
![.js file](https://i.imgur.com/nuU1IbF.png)

## Reproducible Case

install [GraphQL for VSCode](https://marketplace.visualstudio.com/items?itemName=kumar-harsh.graphql-for-vscode) extension for syntax highlight

**Comment by octref** [comment]
What GraphQL is using:

```
"injectionSelector": "L:source -string -comment"
```

It's injecting grammar to `source.js`. Vetur is embedding `source.js`. This should work automatically.
I have created an upstream issue: https://github.com/Microsoft/vscode/issues/44056

**Comment by flakeparadigm** [comment]
While it certainly doesn't address the issue with grammars not inheriting injections as expected, a fix for his has been merged into GraphQL for VSCode extension mention in the original issue report.

**Comment by octref** [comment]
@flakeparadigm Thanks, sorry for the late response, it's working as expected:

![image](https://user-images.githubusercontent.com/4033249/52375718-2ed68000-2a15-11e9-9873-50877fcd0be5.png)

Would you mind me sending similar PRs for other graphql extensions that fix the injection grammar?

**Comment by flakeparadigm** [comment]
I don't mind at all, feel free to! :)
