### ISSUE TITLE
Non-null assertion operator syntax highlighting error in class based SF-component

### ISSUE THREAD

**Issue by d-n-x** [vuejs/vetur#703]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows 10
- Vetur version: 0.11.7
- VS Code version: 1.20.1

## Problem

It seems like that the non-null assertion operator inside vue component works correctly within the TypeScript compiler but the syntax highlighting seems to be wrong.

https://i.imgur.com/7luF67C.jpg

## Reproducible Case

Create a class in a single-file component and add a variable with the non-null assertion operator:

```
export default class Test extends Vue {
  @Prop() msg!: string; // '=' expected.
  @Prop() test?: number; // Working.
}
```

**Comment by HerringtonDarkholme** [comment]
We will make a new release for this. Please wait patiently.
