### ISSUE TITLE
Extension not starting on Windows 10

### ISSUE THREAD

**Issue by salvadornico** [vuejs/vetur#706]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows 10
- Vetur version: 0.11.7
- VS Code version: 1.20.1

## Problem

The extension doesn't start at all. There is no Vue Language Server panel option under Output.
This only happens on my Windows machine. On my Ubuntu machine, it runs normally.

![screenshot_1](https://user-images.githubusercontent.com/25360297/36678101-ce232742-1b4a-11e8-9396-bf63bb9ef03e.png)

## Reproducible Case

I've tried opening several different Vue projects, but it isn't running for any of them. I've also tried disabling all extensions except Vetur. If there's anywhere else where I can check or get a log from, I'd be glad to provide it.

Thank you!

**Comment by octref** [comment]
Help -> Toggle Developer Tools -> any outputs?

**Comment by salvadornico** [comment]
Hi, I managed to solve it by manually deleting the extension folder and then reinstalling. The regular uninstall and install wasn't doing anything. Sorry for the trouble.
