### ISSUE TITLE
eslint/formatting for vue/js files just stopping 

### ISSUE THREAD

**Issue by cannap** [vuejs/vetur#708]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows
- Vetur version: 0.11.7
- VS Code version: 1.20.1

## Problem
Eveything stops after open this file **see reproductio** eslint/vetur in vue and normal js files
```html
ERR **undefined**
```

## Reproducible Case
Video: https://www.useloom.com/share/5e7755dd49794d91894933ea890d948a
- 1. Create a new Vue file 
- 2. Paste this in https://gist.github.com/cannap/a25ccc0f348694c32c178b364eab0c95
- 3. Try to format 
- 4. create new some.js file try to format/lint some.js 

Extensions/Settings/Eslint config
https://gist.github.com/cannap/bdcc63dc53455fe5b749edda17d00512

**Comment by cannap** [comment]
it has something todo with my template part :/

**Comment by cannap** [comment]
its more a performance issue from my side i think

**Comment by octref** [comment]
> its more a performance issue from my side i think

Strange. So in your screencast, were you formatting that large vue file (your repor gist) and then you can't format js anymore and ESLint stopped working on it?

Those are actually covered by the JS extension in VS Code and the ESLint extension so something happened to them. Did you figure out what's going on?

**Comment by cannap** [comment]
my first trought was i had a open div or something like this i just removed all open divs closed all self-closing tags <some /> now my file looks like

https://gist.github.com/cannap/ac80ee58e787c807856e6bfac22c1dac

i will make some more tests later

**Comment by octref** [comment]
Let's keep this open. I don't know the cause but I can take a depeer look this weekend.

**Comment by octref** [comment]
Seems to be working in latest version. Open a new issue if this still happens. Thanks!
