### ISSUE TITLE
Selected words shown on scrollbar?

### ISSUE THREAD

**Issue by dmrickey** [vuejs/vetur#709]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows
- Vetur version: 0.11.7
- VS Code version: 1.20.1

## Problem

Open a file with a variable used in multiple lines.  Highlight/click on that variable.
Without Vetur: all usages of that word are highlighted and shown on the scroll bar where they're used in the file.
With Vetur: Click - only paired tags are highlighted and shown on the scroll bar.  Highlight - all usages are highlighted and only paired tags are shown on the scroll bar.

I need to be able to see where things are used at a glance, with Vetur installed, I don't see a way to accomplish that now.

**Comment by HerringtonDarkholme** [comment]
What's your reproduction?
Can you provide a image for explaination?

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/37058096-3952d294-213e-11e8-880e-a73e2d509ea4.png)

![image](https://user-images.githubusercontent.com/4033249/37058692-301a8d14-2140-11e8-819b-a07bdac18f57.png)

It's not showing for me for both macOS and Win.
Any error in Vue Language Server output?

![image](https://user-images.githubusercontent.com/4033249/37058882-c032f97c-2140-11e8-8c5d-cf764ccce642.png)

**Comment by adkuca** [comment]
issue still persists

**Comment by yoyo930021** [comment]
> issue still persists

Please open a new issue with bug report template.
