### ISSUE TITLE
TypeScript Intellisense not updating

### ISSUE THREAD

**Issue by neilsimp1** [vuejs/vetur#710]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows/Linux, not tested on Mac
- Vetur version: 0.11.7
- VS Code version: 1.20.1

## Problem

TypeScript Intellisense not updating in `<script>` section of `.vue` files for referencing other `.ts` files.
See https://stackoverflow.com/questions/46988578/intellisense-not-working-for-vue-files for example.

## Reproducible Case

1.
Create a Test.ts file:
```
export default class Test {

}
```

2. In your `.vue` file, import this class
```
<script lang="ts">
import Test from './test';
export default class App extends Vue {
    created() {
        const t = new Test();
    }
}
</script>
```

3. Add a new method to Test.ts
```
export default class Test {
   foo() { }
}
```

4. Try to reference the new function in your `.vue` file
```
<script lang="ts">
import Test from './test';
export default class App extends Vue {
    created() {
        const t = new Test();
        t.foo();
    }
}
</script>
```
You will receive an error in VSCode Intellisense saying `Property 'foo' does not exist on type 'Test'.`

Closing/reopening the file does not seem to fix this. Only restarting VS Code corrects the error. Webpack is still able to compile the code for me, so the error issue seems to be either with VS Code or with Vetur.

**Comment by HerringtonDarkholme** [comment]
Please see https://github.com/vuejs/vetur/issues/355

**Comment by neilsimp1** [comment]
Thanks, I looked through other issues a few times, I don't know how I missed that.
