### ISSUE TITLE
The IntelliSens is not updated when changing files

### ISSUE THREAD

**Issue by M6stafa** [vuejs/vetur#711]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.11.7
- VS Code version: 1.20.1

## Problem

The IntelliSens is not updated when changing files.

Add Test to enum
"@/enums" file:
![image](https://user-images.githubusercontent.com/7975309/36816484-22b1e5ba-1cf3-11e8-9b11-af010f14c770.png)

vue file:
![image](https://user-images.githubusercontent.com/7975309/36816637-a43d68de-1cf3-11e8-8791-0461541837fb.png)

## Reproducible Case

when i change or add somthing in enums or types(.d.ts), the IntelliSens doesn't update and show error until i restart the vscode. it is not happen in .ts files and everything is in sync.
i use typescript.

**Comment by HerringtonDarkholme** [comment]
Please see https://github.com/vuejs/vetur/issues/355
