### ISSUE TITLE
/deep/ triggering vscode linter

### ISSUE THREAD

**Issue by dfee** [vuejs/vetur#715]
I might be reporting this issue to the wrong place or have a usage issue on my hands, but I think this might be a linting issue that is derived from vetur.

## Info

- Platform: MacOS 10.13.3
- Vetur version: 0.11.7
- VS Code version: vscode-insiders (up-to-date)

## Problem
![image](https://user-images.githubusercontent.com/262602/37012826-768363a6-20ab-11e8-9505-2296f2daf191.png)

![image](https://user-images.githubusercontent.com/262602/37012820-6ea0372c-20ab-11e8-8499-dbab61d066c4.png)

## Reproducible Case
Use `/deep/` in your scss.

**Comment by HerringtonDarkholme** [comment]
FYI `/deep/` and `>>>` selectors are obsolete. 

https://stackoverflow.com/questions/25609678/what-do-deep-and-shadow-mean-in-a-css-selector

https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/68qSZM5QMRQ/pT2YCqZSomAJ
From Chrome team: 

> There's complexity cost for dealing with knowing what rules match, and how much is invalidated with DOM changes. Once these rules are removed we can also be much more aggressive about sharing styles, for example we could share all the style work we do for every <app-menu> (and the Shadow DOM inside it) in the page.
The style boundary provided by Shadow DOM is good for performance and maintainability, /deep/ and ::shadow defeat the fast path and encourage bad practices.
