### ISSUE TITLE
Component completion not working (Typescript)

### ISSUE THREAD

**Issue by Aranir** [vuejs/vetur#716]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.11.7
- VS Code version: 1.20.1

## Problem
Compontent completion not working.

## Description

I saw that there was a merge for component completion (#393) but I did not manage to get it to work. 

## Reproducible Case

 I followed the [Microsoft project setup tutorial](https://github.com/Microsoft/TypeScript-Vue-Starter):

And simply added another SFC:

```
<template>
    <div>
        <div class="greeting">Hello {{providedProp}}</div>
    </div>
</template>

<script lang="ts">
  import { Vue, Component, Prop } from "vue-property-decorator";

  @Component
  export default class Other extends Vue {
    @Prop() providedProp: string;
  }
</script>
```

Then used that prop in the `Hello component`:

![screen shot 2018-03-06 at 09 37 21](https://user-images.githubusercontent.com/1159256/37022193-7d57387a-2122-11e8-8a74-25c2e5de0e32.png)

But as can be seen from the screenshot, no suggestions for the prop completion is provided. Is my project not correctly setup, or did I miss something else?

**Comment by HerringtonDarkholme** [comment]
Class style component isn't supported yet.

**Comment by Aranir** [comment]
@HerringtonDarkholme  thank you for the quick answer.

Is there another way to obtain component completion (without using class style?).

If you could give me an example in typescript how I need to define my components for the completion to work I would appreciate it.

Also is it planned to have completion for class style components?

**Comment by HerringtonDarkholme** [comment]
Vetur can analyze `export default Vue.extend()`.
https://github.com/vuejs/vetur/blob/master/server/test/fixtures/component/comp2.vue

You need to use the object style API, though.

I personally plan to support class style component for Vue3, which will support class style officially.

**Comment by nomadoda** [comment]
Mind if I bring this up again? Using the very same example, I'm struggling for my template to recognize imported components at all. It compiles, but I find it very frustrating. Is this also not supported? Or am I having an issue with my IDE/vetur setup? Thank you, I'm really struggling with this.

![screen shot 2018-10-01 at 09 55 43](https://user-images.githubusercontent.com/25898698/46276405-3f0aba00-c560-11e8-8649-1f1d68c6b043.png)

**Comment by octref** [comment]
That remains the same. We don't have support for `vue-property-decorator` yet.
