### ISSUE TITLE
HTML snippet does not work in vue-html region

### ISSUE THREAD

**Issue by jericopulvera** [vuejs/vetur#718]
VScode snippets do not work on .vue files after installing vetur

it works when I disable vetur

**Comment by xpopit** [comment]
<img width="548" alt="screenshot at mar 24 21-52-36" src="https://user-images.githubusercontent.com/17220015/37865320-ce207afc-2fad-11e8-98a0-d68aed3f4b3c.png">
<img width="474" alt="screenshot at mar 24 21-51-22" src="https://user-images.githubusercontent.com/17220015/37865321-ce4f89d2-2fad-11e8-808c-eadc517e2424.png">

not work

**Comment by jericopulvera** [comment]
>Enabled
![enabled](https://user-images.githubusercontent.com/23246308/37882414-b8395924-30d5-11e8-8ec3-204883dae2bf.png)

>Disabled
![disabled](https://user-images.githubusercontent.com/23246308/37882418-bd8236ee-30d5-11e8-97f9-1ffab3934325.png)

not work

**Comment by jericopulvera** [comment]
I noticed that it works if it's outside the <template> and <script> tag.

**Comment by octref** [comment]
The problem is we declare the region `<template>` as vue-html, so html snippets won't work here. I have opened an upstream issue to track this support: Microsoft/vscode/issues/47096

**Comment by aphofstede** [comment]
@octref Looks like upstream issue was closed.

**Comment by octref** [comment]
@jericopulvera @xpopit 
Are the snippets your own snippets or snippets from other extensions?
If they are your own snippets, you can add `"scope": ["vue-html"]` to them.
For snippets from other extensions, there is no easy way to make them available under another language. I've reopened the upstream issue.

**Comment by naimlatifi5** [comment]
Yeap I tried as well and seems does not work on a new Vue.js file

**Comment by brada1703** [comment]
I had this problem as well. It may be a dumb question, but are you sure that VS Code detected that the language to be Vue? Mine was still in HTML for some reason (even though it was a .vue file) and wouldn't work. Whenever I switched the language to Vue, it worked perfectly. Hope this helps someone! :)

**Comment by tucq88** [comment]
+1 here. 
Out side of `<template>` tag my personal snippet works ok. But I can't do it inside `template` tag within a .vue file

**Comment by scarpeace** [comment]
+1. Mine doesn't work either inside of outside the `<template>` tag. I've tried uninstalling a few plugins but nothing seems to change. I have a bootstrap 4 snippet plugin that works just fine inside the `<template>` tag.

**Comment by Viicos** [comment]
It looks like it's still not working so far. According to the [docs](https://vuejs.github.io/vetur/guide/snippet.html), anything between `<template></template>` should have `vue-html` snippets available. But the snippets are behaving incorrectly:

Working correctly outside tags:

![image](https://user-images.githubusercontent.com/65306057/146681766-1e688c06-2933-442b-a616-875d4fd11719.png)

Does not work in the `class` tag (where it is always used for css classes):

![image](https://user-images.githubusercontent.com/65306057/146681785-259912dd-9b5e-40b1-ac37-3b9e6f50f12f.png)

Works outside the template:

![image](https://user-images.githubusercontent.com/65306057/146681828-b9b0cdd2-d570-417e-9103-6c4f08c9fbac.png)

The snippet package used can be found [here](https://github.com/Viicos/primeflexsnippets) (both `html` and `vue-html` languages are added in the `package.json)`. When using the snippets in an ordinary html file, everything works fine.

@octref any thoughts on this?

**Comment by zzzgit** [comment]
It's still an issue until Jan 2024.

**Comment by Viicos** [comment]
> It's still an issue until Jan 2024.

Vetur isn't maintained anymore, you should switch to Volar.
