### ISSUE TITLE
Go to vue definition from js file not working

### ISSUE THREAD

**Issue by TimYi** [vuejs/vetur#720]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: 0.11.7
- VS Code version: 1.20.1

## Problem

![output](https://user-images.githubusercontent.com/7494892/37157721-80976394-2324-11e8-88ca-0af11f6247bd.gif)

As you can see, go to a vue file definition does not work in a js file.

Plugins I use:

![2018-03-08 23-02-51](https://user-images.githubusercontent.com/7494892/37157863-e180f8aa-2324-11e8-96fe-28c7eabe20c6.png)

**Comment by HerringtonDarkholme** [comment]
The problem is that Vetur can only provide definition for `.vue` file. So you have to configure TypeScript in other plugins.

Currently, you can try this tsserver plugin. https://github.com/HerringtonDarkholme/vue-ts-plugin

**Comment by TimYi** [comment]
@HerringtonDarkholme, it's a reasonable answer, but vue-ts-plugin is still in alpha state, and it's origin project is not maintained for several months.
I hope vue core team can provide a complete solution for developing in vscode.

**Comment by HerringtonDarkholme** [comment]
Hi @TimYi  I maintain the vue-ts-plugin. You can try that out.

**Comment by TimYi** [comment]
@HerringtonDarkholme Thank you for your tips, but till not working.
![output](https://user-images.githubusercontent.com/7494892/37264894-f15e2d74-25ea-11e8-9038-0ee8bef85cc1.gif)
![2018-03-12 10-17-13](https://user-images.githubusercontent.com/7494892/37264895-f19a074a-25ea-11e8-88dd-3b0679a60511.png)
![output](https://user-images.githubusercontent.com/7494892/37264903-f89b6200-25ea-11e8-9590-df8d9cf4c31a.gif)

**Comment by HerringtonDarkholme** [comment]
Can you give a repo for your setup?
