### ISSUE TITLE
TS 2.7.1 Definite assignments not parsed correctly

### ISSUE THREAD

**Issue by elevatebart** [vuejs/vetur#723]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.11.7
- VS Code version: 1.21.0

## Problem

Definite assignments are not parsed.
<img width="398" alt="Definite assignment assertions" src="https://user-images.githubusercontent.com/5592465/37245518-e41a6872-245e-11e8-9d49-7e5389632384.png">

## Reproducible Case

Use vue cli to create a repo with typescript.
Create a method in the HelloWorld component:
``` ts
methods: {
    test: () => {
      let foo!: string;
    }
  }
```

This method should parse fine.
I created a quick [repo](https://github.com/elevatebart/veturreprodefinit) for faster reproduction.

**Comment by octref** [comment]
This has been fixed by upgrading Vetur's dependency to 2.7.2. Please wait for a new release.

**Comment by lanthaler** [comment]
@octref when do you plan to release the next version?

**Comment by lyonsbp** [comment]
Any update on this?

**Comment by tony19** [comment]
I manually installed [`0.11.8`](https://github.com/vuejs/vetur/releases/download/0.11.8/vetur-0.11.8.vsix), which resolved the error.

**Comment by octref** [comment]
The next version has been published.
