### ISSUE TITLE
Is it possible to break SFC files?

### ISSUE THREAD

**Issue by khullah** [vuejs/vetur#724]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Suggestion

I want to select a `.vue ` SFC file and show it in 3 separate windows (template, script, style). Would it be possible to add this feature? Alternatively, show the file as a "zip"/folder, with 3 inner files in it.

**Comment by octref** [comment]
It's not possible now.
