### ISSUE TITLE
Command "Vetur: Generate grammar from vetur.grammar.customBlocks" not found

### ISSUE THREAD

**Issue by tolerious** [vuejs/vetur#728]
After I installed vetur, and restart vscode, I run the command , it occurs   "command not found error".
![image](https://user-images.githubusercontent.com/2922120/37282713-5efd6d8c-2630-11e8-8895-94c9ce09bbf1.png)

**Comment by octref** [comment]
You need to open a Vue file first, otherwise the extension won't be loaded.

**Comment by tolerious** [comment]
@octref  hi,octref,  I retry this command during opening a Vue file,   but still prompt this error.
![image](https://user-images.githubusercontent.com/2922120/37317143-1e7e2288-269e-11e8-8b72-f8098f3bcadf.png)

**Comment by octref** [comment]
When you open Output -> Vue Language Server, any output?

![image](https://user-images.githubusercontent.com/4033249/37355782-c993933a-26a1-11e8-9934-492e2b14e616.png)

Also do you see any error in Help -> Developer Tools?

**Comment by tolerious** [comment]
hi, @octref , there is nothing in "OUTPUT" 
![image](https://user-images.githubusercontent.com/2922120/37377665-47c84b1e-2766-11e8-8b36-d3201e70f739.png)

and this is in "dev tools" 
![image](https://user-images.githubusercontent.com/2922120/37377752-c2405ddc-2766-11e8-8c78-e8a232f46037.png)

**Comment by octref** [comment]
I'm guessing Vetur is not installed properly. You might be hitting this bug: https://github.com/Microsoft/vscode/issues/43813#issuecomment-372764264

Can you try running the command `Developer: Reinstall Extension` and choose Vetur and see if that fixes it for you?

**Comment by tolerious** [comment]
hi,    @octref , I follow your suggestions, but  not work, reinstall extension and relaunch,    there is still a mistake, my OS is MacOS, and the vsCode version is the latest.
![image](https://user-images.githubusercontent.com/2922120/37383312-f5c95818-2782-11e8-8c81-088a59cfe6f3.png)

**Comment by octref** [comment]
In output don't choose 输出 choose "Vue Language Server". Do you see the message `vetur initialized`?

**Comment by tolerious** [comment]
no, I did non see the `vetur initialized` message in any window

**Comment by tolerious** [comment]
Do you mean after I open a *.vue file I should see the `Vue Language Server`  panel, at the bottom of vsCode?

**Comment by octref** [comment]
You need to choose Vue Language Server in the dropdown:

![image](https://user-images.githubusercontent.com/4033249/37383910-fe77500c-2708-11e8-88a0-d790e6601d96.png)

**Comment by tolerious** [comment]
@octref  there is no `Vue Lannguage Server` choice.

**Comment by octref** [comment]
Interesting...So the server is not started, the extension is registered, but the command cannot be found...

The only issue I see is the error about `git.viewFileHistory`. If you disable the Git History extension, does it work?

**Comment by octref** [comment]
Sorry for asking you for all these questions...but:

1. Do you have other Vue extensions installed?
2. Does this problem happen to Insiders version of VS Code too? https://code.visualstudio.com/insiders/

**Comment by tolerious** [comment]
![image](https://user-images.githubusercontent.com/2922120/37384212-767bf9d4-2788-11e8-93ae-a7406ae83d9d.png)
I uninstalled all extentions and reinstall Vetur, but still not work for me.

**Comment by octref** [comment]
Sorry for the inconvenience. This might be a serious issue with VS Code's extension management. I'll report to them and get back to you.

One final thing if you could check for me. Can you find the file `~/.vscode/extensions/octref.vetur-0.11.7/out/vueMain.js` in your disk? If so can you paste its content in here?

**Comment by tolerious** [comment]
hi,  @octref , I donwloaded the vscode  insiders version, and I saw the `Vue Language Server` choice.

**Comment by tolerious** [comment]
hi,  @octref , there is no file called vueMain.js in `.vscode` floder.
![image](https://user-images.githubusercontent.com/2922120/37385070-4ac53dbe-278d-11e8-9b73-30fae8366ea2.png)

**Comment by octref** [comment]
@tolerious Good catch. So the extension shows Vetur as installed, but you see no `octref.vetur-0.11.7` folder under `~/.vscode`?

**Comment by tolerious** [comment]
yes, you are right. very very strange.

**Comment by octref** [comment]
One final thing that I need your help:

If you run the command `Developer: Open Logs Folder`, there should be a bunch of folders like this:

![image](https://user-images.githubusercontent.com/4033249/37385397-01f48954-2711-11e8-9647-7d943d2e88ea.png)

In each folder 20180313xxxx, you should see a log file called `sharedprocess.log`.
Can you paste the content of the `sharedprocess.log` from the folders that start from 20180314 (I think current time in China is 03/14)?

Thanks again for your help! These info can help VS Code fix the issue so it would not affect other users.

**Comment by tolerious** [comment]
[sharedprocess1.log](https://github.com/vuejs/vetur/files/1809789/sharedprocess1.log)
[sharedprocess2.log](https://github.com/vuejs/vetur/files/1809790/sharedprocess2.log)
[sharedprocess3.log](https://github.com/vuejs/vetur/files/1809791/sharedprocess3.log)
[sharedprocess4.log](https://github.com/vuejs/vetur/files/1809792/sharedprocess4.log)
hi, @octref I have uploaded all the `sharedprocess.log` files  today, hope to help you.

[sharedprocess5.log](https://github.com/vuejs/vetur/files/1809793/sharedprocess5.log)
[sharedprocess6.log](https://github.com/vuejs/vetur/files/1809794/sharedprocess6.log)

**Comment by octref** [comment]
I see from log Vetur is installed into `/Users/tolerious/.vscode/extensions/octref.vetur-0.11.7`. However in your screenshot
![](https://user-images.githubusercontent.com/2922120/37385070-4ac53dbe-278d-11e8-9b73-30fae8366ea2.png) it's `~/tongjimm-admin/.vscode`. Is it that you don't have the folder `~/.vscode`? Or are you launching VS Code using a separate extension dir with `code --extensions-dir`?

**Comment by tolerious** [comment]
oh, sorry, I have the `.vscode` floder in my home dir, post the vueMain.js file to you.
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const fs = require("fs");
const path = require("path");
const vscode = require("vscode");
const vscode_1 = require("vscode");
const vscode_languageclient_1 = require("vscode-languageclient");
const grammar_1 = require("./grammar");
const protocol_colorProvider_proposed_1 = require("vscode-languageserver-protocol/lib/protocol.colorProvider.proposed");
const EMPTY_ELEMENTS = [
    'area',
    'base',
    'br',
    'col',
    'embed',
    'hr',
    'img',
    'input',
    'keygen',
    'link',
    'menuitem',
    'meta',
    'param',
    'source',
    'track',
    'wbr'
];
function activate(context) {
    /**
     * Custom Block Grammar generation command
     */
    context.subscriptions.push(vscode.commands.registerCommand('vetur.generateGrammar', () => {
        const customBlocks = vscode_1.workspace.getConfiguration().get('vetur.grammar.customBlocks') || {};
        try {
            const generatedGrammar = grammar_1.getGeneratedGrammar(path.resolve(context.extensionPath, 'syntaxes/vue.json'), customBlocks);
            fs.writeFileSync(path.resolve(context.extensionPath, 'syntaxes/vue-generated.json'), generatedGrammar, 'utf-8');
            vscode.window.showInformationMessage('Successfully generated vue grammar. Reload VS Code to enable it.');
        }
        catch (e) {
            vscode.window.showErrorMessage('Failed to generate vue grammar. `vetur.grammar.customBlocks` contain invalid language values');
        }
    }));
    /**
     * Vue Language Server Initialization
     */
    const serverModule = context.asAbsolutePath(path.join('server', 'dist', 'vueServerMain.js'));
    const debugOptions = { execArgv: ['--nolazy', '--inspect=6005'] };
    const serverOptions = {
        run: { module: serverModule, transport: vscode_languageclient_1.TransportKind.ipc },
        debug: { module: serverModule, transport: vscode_languageclient_1.TransportKind.ipc, options: debugOptions }
    };
    const documentSelector = ['vue'];
    const config = vscode_1.workspace.getConfiguration();
    const clientOptions = {
        documentSelector,
        synchronize: {
            // the settings to synchronize
            configurationSection: ['vetur', 'html', 'javascript', 'typescript', 'prettier', 'stylusSupremacy']
        },
        initializationOptions: {
            config
        },
        revealOutputChannelOn: vscode_languageclient_1.RevealOutputChannelOn.Never
    };
    // Create the language client and start the client.
    const client = new vscode_languageclient_1.LanguageClient('vue', 'Vue Language Server', serverOptions, clientOptions);
    const disposable = client.start();
    context.subscriptions.push(disposable);
    const isDecoratorEnabled = vscode_1.workspace.getConfiguration().get('vetur.colorDecorators.enable');
    if (isDecoratorEnabled) {
        client.onReady().then(registerColorProvider);
    }
    vscode_1.languages.setLanguageConfiguration('vue-html', {
        wordPattern: /(-?\d*\.\d\w*)|([^\`\~\!\@\$\^\&\*\(\)\=\+\[\{\]\}\\\|\;\:\'\"\,\.\<\>\/\s]+)/g,
        onEnterRules: [
            {
                beforeText: new RegExp(`<(?!(?:${EMPTY_ELEMENTS.join('|')}))([_:\\w][_:\\w-.\\d]*)([^/>]*(?!/)>)[^<]*$`, 'i'),
                afterText: /^<\/([_:\w][_:\w-.\d]*)\s*>$/i,
                action: { indentAction: vscode_1.IndentAction.IndentOutdent }
            },
            {
                beforeText: new RegExp(`<(?!(?:${EMPTY_ELEMENTS.join('|')}))(\\w[\\w\\d]*)([^/>]*(?!/)>)[^<]*$`, 'i'),
                action: { indentAction: vscode_1.IndentAction.Indent }
            }
        ]
    });
    function registerColorProvider() {
        const colorSubscription = vscode_1.languages.registerColorProvider(documentSelector, {
            provideDocumentColors(doc) {
                const params = {
                    textDocument: client.code2ProtocolConverter.asTextDocumentIdentifier(doc)
                };
                return client.sendRequest(protocol_colorProvider_proposed_1.DocumentColorRequest.type, params)
                    .then(symbols => symbols.map(symbol => {
                    const range = client.protocol2CodeConverter.asRange(symbol.range);
                    const color = new vscode.Color(symbol.color.red, symbol.color.green, symbol.color.blue, symbol.color.alpha);
                    return new vscode.ColorInformation(range, color);
                }));
            },
            provideColorPresentations(color, context) {
                const params = {
                    textDocument: client.code2ProtocolConverter.asTextDocumentIdentifier(context.document),
                    color,
                    range: client.code2ProtocolConverter.asRange(context.range)
                };
                return client.sendRequest(protocol_colorProvider_proposed_1.ColorPresentationRequest.type, params)
                    .then(presentations => presentations.map(p => {
                    const presentation = new vscode.ColorPresentation(p.label);
                    presentation.textEdit =
                        p.textEdit && client.protocol2CodeConverter.asTextEdit(p.textEdit);
                    presentation.additionalTextEdits =
                        p.additionalTextEdits && client.protocol2CodeConverter.asTextEdits(p.additionalTextEdits);
                    return presentation;
                }));
            }
        });
        context.subscriptions.push(colorSubscription);
    }
}
exports.activate = activate;
//# sourceMappingURL=vueMain.js.map
```

**Comment by octref** [comment]
The file looks fine.
If you add a line `console.log('hello vetur')` right after
```
function activate(context) {
```
and you restart VS Code and open a vue file. Do you see anything in Help -> Toggle Developer Tools?

**Comment by tolerious** [comment]
![image](https://user-images.githubusercontent.com/2922120/37387806-e2d30afe-2798-11e8-88bb-934d804cea8e.png)
![image](https://user-images.githubusercontent.com/2922120/37387817-ed667370-2798-11e8-843c-7e3c09e9053e.png)
@octref there is nothing in the dev tools terminal.

**Comment by octref** [comment]
Even after you open a Vue file, still nothing in Dev Tool, is that correct?

**Comment by tolerious** [comment]
yes, nothing in Dev Tool

**Comment by octref** [comment]
Thanks for all the information. The issue is that you associated vue to html files in `files.associations`. You should not do that. (Which tutorial or setup guide did you follow?)

**Comment by tolerious** [comment]
And this is my latest config file.
```
{
    "workbench.colorTheme": "Quiet Light",
    "editor.fontSize": 14,
    "editor.fontFamily": "Menlo, Monaco, 'Courier New', monospace",
    "update.channel": "default",
    "html.format.enable": true,
    "html.format.indentHandlebars": true,
    "html.suggest.html5": true,
    "html.autoClosingTags": true,
    "editor.wordWrap": "on",
    "files.autoSave": "onWindowChange",
    "window.title": "${activeEditorLong}${separator}${rootName}",
    "explorer.confirmDelete": true,
    "editor.minimap.enabled": false,
    "git.enableSmartCommit": true,
    "git.autofetch": true,
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/.idea":true,
        "**/node_modules": true
    },
    "zenMode.hideTabs": true,
    "zenMode.hideStatusBar": true,
    "zenMode.hideActivityBar": true,
    "zenMode.fullScreen": true,
    "zenMode.centerLayout": true,
    "workbench.editor.enablePreview": true,
    "workbench.editor.enablePreviewFromQuickOpen": true,
}
```

**Comment by octref** [comment]
On the lowerright of this picture, I see HTML filetype:

![](https://user-images.githubusercontent.com/2922120/37384049-6da55fc2-2787-11e8-835b-7033ca1952a2.jpeg)

So somehow your Vue files are marked as HTML. But you are saying you don't have any `files.associations` config?

**Comment by octref** [comment]
One thing you might check is your workspace setting. Maybe you have the `files.associations` there:

![image](https://user-images.githubusercontent.com/4033249/37415667-37b0df86-2769-11e8-9c71-d1100b85a3b4.png)

**Comment by songololo** [comment]
I am also getting `command not found: Vetur`.

I've check that the Vue Language Server is running. Any thoughts?

I'm in Mac OS using Visual Studio Code v1.51.1

**Comment by yoyo930021** [comment]
> I am also getting `command not found: Vetur`.
> 
> I've check that the Vue Language Server is running. Any thoughts?
> 
> I'm in Mac OS using Visual Studio Code v1.51.1

Please open a new issue.
