### ISSUE TITLE
Format document does not work

### ISSUE THREAD

**Issue by Thavaprakash** [vuejs/vetur#729]
## Info

- Platform: ubuntu 16
- Vetur version:  v0.11.7
- VS Code version:Version 1.19.2

## Problem
Format Document is not enabled, so can't format .vue file

## Reproducible Case
step1: opened .vue file, place some html codes, try to format

**Comment by octref** [comment]
https://vuejs.github.io/vetur/formatting.html

**Comment by Thavaprakash** [comment]
Thank you @octref , i used below one, it works. But document says js-beautify-html [deprecated].

[{
  "vetur.format.defaultFormatter.html": "js-beautify-html"
}
](url)
