### ISSUE TITLE
support sorting import modules within <script> tag inside *.vue files

### ISSUE THREAD

**Issue by lunchboxsuhi** [vuejs/vetur#730]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version: 0.11.7
- VS Code version: 1.21.0

## Problem

Cannot find configuration to allow sorting of imports such functionality can be found on  https://github.com/amatiasq/vsc-sort-imports. This only works on TS and JS files I was wondering if there was an implementation for Vue.js through Vetur to sort imports inside the `<script></script>` tag. Wasn't able to find anything in the docs regarding imports formatting only code rules

**Comment by HerringtonDarkholme** [comment]
We cannot port all additional features in js/ts to vue file.

* We don't have that much man effort.
* It is usually editor bound implementation, which isn't compatible with our Language-server-protocol design.
* Not all users like all additional features.
*  It might incur performance overhead.

I recommend raising an issue in the plugin's repo for supporting vue file, if the plugin author is willing to do that.

**Comment by HerringtonDarkholme** [comment]
For your specific problem.

https://github.com/amatiasq/vsc-sort-imports/issues/17#issuecomment-365167797

**Comment by lunchboxsuhi** [comment]
@HerringtonDarkholme  Thank you.

 I didn't realize it would be on vsc-sort-import implementation vs vetur engine. Unfortunately that solution only works for files that are delimited with `<script lang="ts">` but it set me on the right track.
