### ISSUE TITLE
CSS Suggestions do not work in a second style block with lang=scss

### ISSUE THREAD

**Issue by Coalescent** [vuejs/vetur#731]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Mac OS X 10.12.6
- Vetur version: 0.11.7
- VS Code version: 1.21.1

## Problem

When working in a **second** `style` block in a .vue file, CSS suggestion do not work. They do always work in the first `style` block but not subsequent ones.
![vetur-issue](https://user-images.githubusercontent.com/6394091/37502506-4321b1a6-2890-11e8-9563-24664332ef8d.png)

## Reproducible Case

1. Create a single page vue component (.vue)
1. Put two `style` blocks with `lang=scss` as attributes for each.
1. Write styles in the second block and no css suggestions will come up - but they will for the first block.

Note that this behaviour won't happen if the `lang` attributes aren't there and it does not matter if they are (or are not) `scoped`.

**Comment by HerringtonDarkholme** [comment]
is:issue css second is:closed 

https://github.com/vuejs/vetur/issues/430

**Comment by octref** [comment]
@HerringtonDarkholme Actually this does seem like a valid feature request. Also see some upvotes on #430. I'll reopen #430.
