### ISSUE TITLE
formatting is not working in large vue file (431 line) ?

### ISSUE THREAD

**Issue by Navyroot** [vuejs/vetur#732]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version:0.11.7
- VS Code version:1.21.1

## Problem

formatting is not working in large vue file (431 line)

![screenshot from 2018-03-16 14-16-43](https://user-images.githubusercontent.com/31533986/37508329-308f13ae-2925-11e8-9ed7-db32921c0a87.png)

**Comment by HerringtonDarkholme** [comment]
Can you provide a reproduction?

**Comment by Navyroot** [comment]
now it work fine, thank you
