### ISSUE TITLE
I have installed the vetur and the .vue can be identified as vue file but the code cannot highlight

### ISSUE THREAD

**Issue by LawrenceQxy** [vuejs/vetur#733]

**Comment by HerringtonDarkholme** [comment]
https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#vetur-crash

**Comment by octref** [comment]
This might be a issue where your Vetur extension is not correctly installed. You can run the command `Developer: Reinstall Extensions`. If this does not solve your problem feel free to reopen the issue.

**Comment by dahua910** [comment]
I got the same problem on mac.
Delete the whole extensions folder solved the problem.

Windows %USERPROFILE%\.vscode\extensions
Mac ~/.vscode/extensions
Linux ~/.vscode/extensions
