### ISSUE TITLE
How To Configure Prettier To Omit Semicolons

### ISSUE THREAD

**Issue by nihiluis** [vuejs/vetur#734]
- [YES] I have searched through existing issues
- [ YES] I have read through [docs](https://vuejs.github.io/vetur)
- [YES] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  LINUX
- Vetur version: NEWEST
- VS Code version:older

## Problem
I know it's possible to omit semicolons from the code with prettier. How do I configure it for use with Vetur?

**Comment by octref** [comment]
If you have a `.prettierrc` in your project root, Vetur will use it. Otherwise, you can add the user setting `prettier.semi: false` to your user config. https://vuejs.github.io/vetur/formatting.html
