### ISSUE TITLE
Haml support - Colorization

### ISSUE THREAD

**Issue by ycrepeau** [vuejs/vetur#739]
My *.vue files contains three parts:

- template (using _haml_)
- script (using coffeescript)
- style (using sass, not scss)

Script and style sections are properly colorized.
The template section is not.

Is it possible to add proper colorization (highlight) to code written in _haml_ ?

**Comment by HerringtonDarkholme** [comment]
It looks like we cannot support arbitrary language highlighting in vue file. Even custom blocks have only predefined language support.

https://github.com/vuejs/vetur/blob/master/package.json#L91

@octref  any idea to break the limit?

**Comment by ZSkycat** [comment]
Maybe consider splitting the code into multiple files
like this:
```js
// ./hello.vue.js
// ./hello.vue.html
// ./hello.vue.css

import template from "./hello.vue.html";

export default {
    name: "Hello",
    render: template,
};
```

**Comment by octref** [comment]
We can add haml in the `embeddedLanguages` in package.json. If users install haml extension it'll become available.

![image](https://user-images.githubusercontent.com/4033249/40036997-aaa0ac70-57bf-11e8-8840-2d909ecaf595.png)
