### ISSUE TITLE
VS Code Problem panel is wrong

### ISSUE THREAD

**Issue by superbiger** [vuejs/vetur#740]
[-] I have searched through existing issues
 [-] I have read through [docs](https://vuejs.github.io/vetur)
 [-] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.11.7
- VS Code version: 1.21.1 (1.21.1)

## Problem
Firstly I create a *.ts (export default class ……）and import it in other *.vue.When I change this class constructor method, Reopen the vue file, Problem panel doesn't work

## Reproducible Case
[step 0]: Use vue-cli beta 6 init an typescript+vue project
[step 1]: Create file **Test.ts** and save
```typescript
export default class Test {
      constructor(id: number) { }
}
```
[step 2]: In **App.vue**
I try to import **Test** 
```javascript
mounted() {
     new Test(1111)
}
```
[step 3]: Reopen **Test.ts** change **constructor()** like this
```typescript
export default class Test {
      constructor(id:number, name:string) {}
}
```
step 4: Reopen App.vue
You will see that Problem Panel doesn't work，But complier is right

Tip:   
When I reopen VS Code, can be correct。When other extensions are disabled, this bug is still

**Comment by HerringtonDarkholme** [comment]
Hi @superbiger, we have already fixed this, but not release it yet.

@octref  Can you give this a look?

**Comment by superbiger** [comment]
@HerringtonDarkholme Could you help me how to install VS Code plugin from git ? i'm not familar with it.

**Comment by kb10uy** [comment]
@HerringtonDarkholme @superbiger 
I hit a similar problem ([kb10uy/vue-sfc-ts](https://github.com/kb10uy/vue-sfc-ts)), and now it seems to be fixed correctly in the latest master branch. :laughing:

The **vsce** package is required to build and install the extension from this repository:
```
git clone https://github.com/vuejs/vetur
cd vetur
yarn && cd server && yarn && yarn compile && cd ../client && yarn && yarn compile && cd ../ && vsce package
```
Now you'll find `vetur-0.11.7.vsix`, you can install it by "Install from VSIX".

**Comment by HerringtonDarkholme** [comment]
Thank @kb10uy , I have updated the instructions in FAQ.

**Comment by HerringtonDarkholme** [comment]
I have published a binary in github tag. You can download 0.11.8 here.
https://github.com/vuejs/vetur/releases/tag/0.11.8
