### ISSUE TITLE
Syntax-highlighting does't work

### ISSUE THREAD

**Issue by LeeChangCheng** [vuejs/vetur#746]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:Win10
- Vetur version:0.11.7
- VS Code version:1.21

## Problem

![image](https://user-images.githubusercontent.com/19348435/38173134-5fccbea0-35eb-11e8-8047-c257d37493f1.png)

**Comment by LeeChangCheng** [comment]
I remember vetur worked well before ，but it becomes this after updating several times ...

**Comment by octref** [comment]
I just added a section in FAQ for this case:

https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#no-syntax-highlighting--no-language-features-working

It's caused by VS Code not installing Vetur properly and you can follow the instruction to reinstall.
