### ISSUE TITLE
less syntax seem to not working in .vue file

### ISSUE THREAD

**Issue by i-tim-tang** [vuejs/vetur#749]
- [*] I have searched through existing issues
- [*] I have read through [docs](https://vuejs.github.io/vetur)
- [*] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.11.7
- VS Code version: 1.21.1

## Problem

less syntax seem to not working in .vue file
```
<style lang="less">
  .name {
       color: red;
       h1 {
           text-align: center;
       }
</style>
```
there are errors warning highlight, and no intelliSense
And .less file is OK

## Reproducible Case

- open an .vue file
- edit sytle with lang syntax

**Comment by octref** [comment]
You forgot a closing brace, should be 
``` vue
<style lang="less">
  .name {
       color: red;
       h1 {
           text-align: center;
       }
}
</style>
```

**Comment by i-tim-tang** [comment]
@octref lacking closing brace was just a typo
it actually not working in VSCode , there was an syntax error warning highlight

**Comment by octref** [comment]
@i-tim-tang Can you show a screenshot?

**Comment by i-tim-tang** [comment]
@octref i only installed two VSCode extensions: Prettier and Vetur
but in .less file, syntax and intelliSense work expectly.
