### ISSUE TITLE
Make releases available under GitHub releases

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#750]
We can provide vsix files so users can easily switch to a pre-built version.
Also a copy of changelog could go there.

**Comment by HerringtonDarkholme** [comment]
I have released a preview 0.11.8 version and its changelog. https://github.com/vuejs/vetur/releases/tag/0.11.8

@octref we still need publish it via vsce. Do you have time to give it a look?

**Comment by DrSensor** [comment]
Hello, is it possible/good-idea to make the release cycle of Vetur be the same as typescript/vscode? (using ci like greenkeeper or bot for checking vscode/typescript release then doing auto pr)

> [vscode now ships ts 2.8.3](https://code.visualstudio.com/updates/v1_23#_typescript-283)

**Comment by octref** [comment]
I did that for 0.11.8. We'll continue to do it for each releases.
I think what we want is continuous release only for VLS (not for Vetur extension). I opened #786 for that.
