### ISSUE TITLE
! is not understood correctly in typescript variable declaration

### ISSUE THREAD

**Issue by digijap** [vuejs/vetur#754]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux 
- Vetur version: 0.11.7
- VS Code version: 1.22.1-1522974421_amd64

## Problem
When using the component below, I get an error at `@Prop() private msg!: string;`.  

```
<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

@Component
export default class HelloWorld extends Vue {
  @Prop() private msg!: string;
}
</script>
```

Problems tab:
![image](https://user-images.githubusercontent.com/7533983/38523117-d700eac2-3c4a-11e8-8816-bf86ac26a6d1.png)

I do not get this error when running typescript or eslint. It seems to be that something does not understand the `!` operator in typescript. Maybe this is not related to Vetur and someone can send me in the right direction to find out.

## Reproducible Case
I've made a small [repo](https://github.com/digijap/vetur-bug) that can be checked out. I get the 3 errors when opening the `vue` [file](https://github.com/digijap/vetur-bug/blob/master/3problems.vue).

Otherway to reproduce this is by using the vue-cli:

`npx -p @vue/cli vue create .`
```
Please pick a preset:
  Manually select features
Check the features needed for your project:
  TS, Router, Vuex, CSS Pre-processors, Linter, Unit
Use class-style component syntax?
  Yes
Use Babel alongside TypeScript for auto-detected polyfills?
  Yes
Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default):
  SCSS/SASS
Pick a linter / formatter config:
  Airbnb
Pick additional lint features:
  Lint on save, Lint and fix on commit
Pick a unit testing solution:
  Jest
Where do you prefer placing config for Babel, PostCSS, ESLint, etc.?
  In dedicated config files
Save this as a preset for future projects?
  No
```

**Comment by HerringtonDarkholme** [comment]
I don't have publish access to vetur. But I can add a vscode extension binary in release page.

**Comment by HerringtonDarkholme** [comment]
You can install a preview release by vsix file attached [here](https://github.com/vuejs/vetur/releases/tag/0.11.8)

**Comment by b-zee** [comment]
I came across this issue too. I'm anticipating such issues will be encountered in the future when this extension's Typescript version will mismatch the project.

I am wondering whether it would be possible for this extension to use the Typescript compiler that is used by the workspace project, just like the language server seems to be doing. Thus ensuring the same version will be used when building a project and error checking the Vue files.
