### ISSUE TITLE
I use typescript in sfc, but it prompt wrong

### ISSUE THREAD

**Issue by Mmpc1994** [vuejs/vetur#759]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

In the .ts file i define a class and it has three different property(test, test1, test2)

In the .vue file i import the class but it prompt it has the other property (test, lala, test2)

and if i restart the visual studio code or the vetor extension, it become corrent.
`export class AuthService {
    constructor() {}
    test: string = 'asdasd'
    test2: string = '123112'
    test3: string = '123213'
}
`
![image](https://user-images.githubusercontent.com/17062182/38624354-777276ac-3dda-11e8-991e-3e1c89e45430.png)

**Comment by ktsn** [comment]
Probably duplicate of #355

**Comment by Mmpc1994** [comment]
https://github.com/vuejs/vetur/issues/355
i will close it

**Comment by HerringtonDarkholme** [comment]
You can download preview version here. https://github.com/vuejs/vetur/releases/tag/0.11.8

The preview has a watcher for script update outside of vue file.
