### ISSUE TITLE
Emmet not using preferences

### ISSUE THREAD

**Issue by usernamehw** [vuejs/vetur#761]
- Platform: Win10
- Vetur version: 0.11.7
- VS Code version: 1.23.0

## Problem
Having this in `Settings`:
```json
"emmet.preferences": {
    "format.forceIndentationForTags": [
        "body",
        "div",
    ],
},
```
**html** file:
```html
<!-- .div -->
<div class="div">
    |
</div>
```
**vue** file:
```vue
<template>
    <!-- .div -->
    <div class="div">|</div>
</template>
```

Not sure if it's a problem with `Emmet` or `Vetur`.

**Comment by usernamehw** [comment]
Should've used file associations, I guess. 😕 
```json
"files.associations": {
    "*.vue": "html"
},
```

**Comment by octref** [comment]
This was fixed with https://github.com/vuejs/vetur/commit/bf2b90f4273504318210a7a5693fb242112054a7. You can either use this one for now https://github.com/vuejs/vetur/releases/tag/0.11.8 or wait for a new release.
