### ISSUE TITLE
Incorrect error highlighting in a .vue file

### ISSUE THREAD

**Issue by MartynovMax** [vuejs/vetur#766]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS Sierra (10.12.6)
- Vetur version: 0.11.7
- VS Code version: 1.22.2

## Problem

Take a look on the screenshot below. The plugin highlights 4th row of the .vue file instead of the 4th row of the `<template>` tag.

![screen shot 2018-04-16 at 00 41 24](https://user-images.githubusercontent.com/24715564/38783783-f2142c7e-410f-11e8-87e6-f812494eb013.png)

## Reproducible Case

Create a .vue file where `<template>` tag will not be at the top.

**Comment by HerringtonDarkholme** [comment]
Please try https://github.com/vuejs/vetur/releases/tag/0.11.8
