### ISSUE TITLE
Typescript features not working in 0.11.8

### ISSUE THREAD

**Issue by KaelWD** [vuejs/vetur#768]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows 10
- Vetur version: 0.11.8 (from vsix)
- VS Code version: 1.22.2

Updating tsc manually (https://github.com/vuejs/vetur/issues/682#issuecomment-364267867) with 0.11.7 works fine. 

### 0.11.8:
No type information:
![image](https://user-images.githubusercontent.com/16421948/38854000-611475fe-4262-11e8-90ce-59023728758c.png)
No hover hints:
![image](https://user-images.githubusercontent.com/16421948/38854053-966aa994-4262-11e8-9aa5-b2148dba65a4.png)

### 0.11.7:
![image](https://user-images.githubusercontent.com/16421948/38854166-f5ce2028-4262-11e8-859e-0e55b4d47533.png)
![image](https://user-images.githubusercontent.com/16421948/38854178-019be296-4263-11e8-853c-48d7d3db5420.png)

**Comment by HerringtonDarkholme** [comment]
I cannot reproduce.

<img width="517" alt="screen shot 2018-04-18 at 11 45 06 am" src="https://user-images.githubusercontent.com/2883231/38910845-0fb8ff94-42fe-11e8-8619-d234ec990d84.png">

**Comment by KaelWD** [comment]
I can prepare one in a couple hours. 

Does that still work for you if you use `<script Lang="ts">` and `export default Vue.extend({`?

**Comment by HerringtonDarkholme** [comment]
It still works. The problem probably is vetur crash. Otherwise in `lang="ts"` property at least will have `any` hover tip. And the completion list suggests no single vetur feature is working.

You can see vetur's log in output panel.

**Comment by KaelWD** [comment]
Nothing in the output panel, but I do see `ERR Language client is not ready yet: Error: Language client is not ready yet at LanguageClient.sendNotification` in devtools, thrown twice for every keypress.

**Comment by KaelWD** [comment]
I'm still getting this with 0.12.1, even with all my other extensions disabled. 

I get this error a few seconds after opening a .vue file, then the "language client is not ready" if I try to do anything afterwards: 
![image](https://user-images.githubusercontent.com/16421948/40103352-7c3e338a-5930-11e8-91b1-9e6d30789da4.png)

Repro: https://github.com/KaelWD/vetur-ts-crash
![2018-05-16_17-58-00](https://user-images.githubusercontent.com/16421948/40104092-c22dc5f2-5932-11e8-9cb0-da04e61aff65.gif)

**Comment by octref** [comment]
@KaelWD Sorry about that - It seems language server is not started properly for you.

What's the output from Output -> Vue Language Server?

![image](https://user-images.githubusercontent.com/4033249/40194048-f9e1b0b8-59bd-11e8-9500-bc91d27ffdab.png)

**Comment by octref** [comment]
Also, would be helpful if you turn on `"vetur.trace.server": "verbose"` and show me the output from `Vue Language Server`.

**Comment by KaelWD** [comment]
Looks like it's working now for some reason, would the 0.12.3 changes have anything to do with that? I'll let you know if it starts breaking again.

**Comment by KaelWD** [comment]
I guess that's fixed it then, I downgraded back to 0.12.1 and it started crashing again. 

@octref Output shows `vue initialized` for the few seconds before the crash, but then the tab switches back to tasks. `vetur.trace.server` isn't recognised in 0.12.1.

**Comment by KaelWD** [comment]
This seems to have regressed in 0.12.4

**Comment by KaelWD** [comment]
I can't tell what the vue language server outputs with `trace.server`, the log disappears as soon as it crashes

![image](https://user-images.githubusercontent.com/16421948/41039876-23500384-69de-11e8-8f8d-d74a715b9cf6.png)

**Comment by octref** [comment]
Just to make sure the extension source is not corrupted - can you run the command `Developer: Reinstall Extensions` for Vetur?

**Comment by KaelWD** [comment]
Done, same problem still. Updating vscode to 1.24.0 with vetur 0.12.5 seems to be working again though.
