### ISSUE TITLE
lead to visual studio code burst

### ISSUE THREAD

**Issue by yang131323** [vuejs/vetur#776]
Serious memory leak, resulting in visual studio code burst memory, unable to operate

**Comment by yang131323** [comment]
Do you mean to reproduce this bug?

**Comment by yang131323** [comment]
I originally wanted to give you a picture, but markdown doesn't seem to be very friendly with local picture support. I've solved this drawback and I changed a plugin.

**Comment by HerringtonDarkholme** [comment]
I'm asking for a code repository to reproduce the behavior. Not a screenshot image.

**Comment by yang131323** [comment]
You run a Vue project directly in the vs code and Vetur in the vs code. Maybe this problem will not happen immediately. Once you have crashed vs code, you just need to uninstall Vetur. This project can be any one, if you do not have one, you can find one on the Internet.

**Comment by yang131323** [comment]
Sorry, it's not convenient to give you.
