### ISSUE TITLE
Syntax highlighting breaks on script/style when template includes self-closing template tag

### ISSUE THREAD

**Issue by richardtallent** [vuejs/vetur#777]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows
- Vetur version: 0.11.7
- VS Code version: 1.21.1

## Problem

When a Vue file's `<template>` contains a self-closing template tag, Vetur will not format the script and style sections afterward.

## Reproducible Case

Create a .vue file with the something like this:
```
<template>
	<div>
		<slot><template v-html="body"></slot>
	</div>
</template>
<script>
iAmNotFormatted => false;
</script>
<style>
.neitherAmI {
  color: red;
}
</style>
```
Note that the script and style tags have no syntax highlighting. Changing the inner element from `<template>` to anything else resolves the issue. So does converting it to `<template v-html="body"></template>`, but this then breaks the recommended rule of using self-closing tags. 

It appears that the code parsing the template for the end of the template doesn't expect self-closing templates.

My use case is like the above, using `<slot>`, but the issue is the same with other tags or combinations. I just wanted to show that there's a sane reason I would use `<template vhtml>` rather than pushing the `vhtml` up to the parent.

**Comment by HerringtonDarkholme** [comment]
Can you try the latest preview https://github.com/vuejs/vetur/releases/tag/0.11.8 here?

I remember this was fixed once.

**Comment by richardtallent** [comment]
I installed the preview, restarted Code, confirmed it upgraded to 0.11.8, but it unfortunately exhibits the same issue.

**Comment by HerringtonDarkholme** [comment]
`<slot><template v-html="body"></slot>` is an invalid usage. 

If you do want to omit closing tag (which can be auto completed by vetur or generated by emmet), the correct usage is 

`<template v-html="body" />`. 


I have updated the syntax file to support self closing template tag. However, due to limitation of regex based syntax highlighting, you have to write self closing template tag in a separate line.  Writing any other tag like `<slot><template/></slot>` will break the syntax.

**Comment by richardtallent** [comment]
Agreed, the test code was intended to have "/>", not sure how I missed that while writing up the issue.

Thanks for addressing this, I'll be sure to put the template on its own line.
