### ISSUE TITLE
IntelliSense for event modifiers in html

### ISSUE THREAD

**Issue by marbuser** [vuejs/vetur#780]
- [YES] I have searched through existing issues
- [YES] I have read through [docs](https://vuejs.github.io/vetur)
- [YES] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Both macOS and Windows 10. (Primarily macOS)
- Vetur version: 0.11.7
- VS Code version: 1.23.0

## Problem
Not entirely sure if this is a "bug". However, if it isn't then consider this a suggestion.
When operating in VScode's default JavaScript "Language mode", Intellisense works perfectly as seen below;
<img width="937" alt="image" src="https://user-images.githubusercontent.com/34422459/39662033-7e1dbf40-508e-11e8-96ea-2356dfa3eb86.png">

However, when trying to achieve the same thing in the Vue "Language mode" that Vetur provides, Intellisense suddenly breaks with vanilla JS code like below;
<img width="980" alt="image" src="https://user-images.githubusercontent.com/34422459/39662045-b139d6e8-508e-11e8-9396-3b5c17d8759c.png">

Something else I've noticed is that directives themselves get suggested in intellisense, but modifiers and other options for them don't. Is this intended? For example;
<img width="641" alt="image" src="https://user-images.githubusercontent.com/34422459/39662064-01ab206e-508f-11e8-9e0b-88b985741310.png">

<img width="725" alt="image" src="https://user-images.githubusercontent.com/34422459/39662072-148e8d38-508f-11e8-8fd4-3e0d2afade40.png">

Both cases have had quite a bit of coverage as I've seen a few posts on the VueJS reddit recently and I've also been discussing with some friends and this is something we all mutually agree is a huge pain in the butt.

## Reproducible Case

1. Install Vetur.
2. Open a new file and change the "Language mode" to Vue.

**Comment by HerringtonDarkholme** [comment]
I believe this is an inherent limitation.

Vue language service requires users to open a file in project. If you open a new file in vscode, vetur will not provide intellisense since no project exists.

**Comment by marbuser** [comment]
Thanks for that. For the first case, I will just use projects for everything from now on, not that big of a deal.

For the second case, do you think we can ever expect directive modifiers in Intellisense since even in projects they are still absent.

For example;
`v-on:click.prevent`

The ".prevent" and other modifiers don't get suggested. Not necessarily that big of a deal, but I think a lot of users would welcome this with open arms if it was to be implemented. :)

**Comment by marbuser** [comment]
To further add onto the above, there is also another "vital" part of Vue that doesn't have intellisense working as expected.

When using an expression such as;
```
this.$router
this.$refs
etc...
```

Intellisense does not work at all. Basically if you use $, intellisense breaks. Not sure if this is a vetur problem or a VSCode problem, but again I think this is another feature/(maybe bug?) a lot of users would welcome.

**Comment by octref** [comment]
For your 1st question, add `dom` to tsconfig.json/jsconfig.json 's `compilerOptions.lib`. For example, see: https://github.com/octref/veturpack/blob/master/tsconfig.json

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "strict": true,
    "noUnusedLocals": true,
    "noImplicitAny": true,
    "outDir": "dist",
    "sourceMap": true,
    "lib": [
      "es5", "es2015.collection", "es2015.promise", "dom", "es2016.array.include"
    ],
    "allowJs": true
  }
}
```

For your 2nd question, we do offer `@` intellisense, but we current don't have intellisense for event modifiers.

![image](https://user-images.githubusercontent.com/4033249/40037628-1d29af6e-57c3-11e8-8b45-29f5b3c43880.png)

I'll just use this issue to track event modifiers intellisense.
