### ISSUE TITLE
.vue files are inconsistent after formatting and saving

### ISSUE THREAD

**Issue by lincenying** [vuejs/vetur#781]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 1.3.1
- VS Code version: 1.23.0

## Problem

original: 
![image](https://user-images.githubusercontent.com/10840991/39671768-122a299a-5151-11e8-9f28-a87f57a82d41.png)

After formatting
![image](https://user-images.githubusercontent.com/10840991/39671800-bf46d380-5151-11e8-8aa3-d41a394d0063.png)

After saving
![image](https://user-images.githubusercontent.com/10840991/39671768-122a299a-5151-11e8-9f28-a87f57a82d41.png)

But the .js file is correct

vscode setting
```
    "eslint.autoFixOnSave": true,
    "eslint.validate": [
        "javascript",
        "javascriptreact",
        {
            "language": "vue",
            "autoFix": true
        }
    ],
    "vetur.format.defaultFormatter.html": "js-beautify-html",
```

eslintrc:
https://github.com/lincenying/eslint-config-lcy-vue/blob/master/index.js

**Comment by octref** [comment]
Are there other formatting extensions that you are using?

**Comment by octref** [comment]
No repro case -> closing.
