### ISSUE TITLE
Feature: Integrate vue-cli 3.0 "inspect" command as a live preview

### ISSUE THREAD

**Issue by Herteby** [vuejs/vetur#785]
This might not be an essential feature, feel free to close it if you think it's too niche.

### Problem
The new webpack config system in vue-cli 3.0 is great for maintainability, but it makes changing the config a bit cumbersome, and for beginners it may seem more complicated than having a file you can edit directly. You first need to run `vue inspect | code -` to check the current config, then make your changes to vue.config.js, then run `vue inspect | code -` again to verify that your changes got merged as expected, and you may need to repeat this cycle multiple times.

### Solution
When viewing/editing vue.config.js, Vetur could show a live preview similar to how VSCode does with Markdown files.
ie. Vetur would watch vue.config.js for changes, run vue inspect and display the result in the preview tab.

**Comment by octref** [comment]
You can use https://github.com/auchenberg/vscode-browser-preview. This is a bit out of scope for Vetur.
