### ISSUE TITLE
Emmet tab autocomplete not working in vue files

### ISSUE THREAD

**Issue by dpyzo0o** [vuejs/vetur#787]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: mac
- Vetur version: 0.11.8
- VS Code version: 1.23.1

## Problem

Emmet not working in .vue files, but it works in .html files. It's strange to me because it works in .vue files before, let's say 10 days ago. It seems that the upgrade of vscode makes something wrong. I did not change any settings.
![vetur](https://user-images.githubusercontent.com/24768249/40022353-ff732518-57c7-11e8-8fbc-f8143cfce513.gif)

My vscode settings:
<img width="715" alt="screen shot 2018-05-14 at 22 49 02" src="https://user-images.githubusercontent.com/24768249/40022742-2bc54d0c-57c9-11e8-8ab0-26f7bc84fcd3.png">

**Comment by cannap** [comment]
it works for me  when i add 

>  "vue": "html"

to
```
  "emmet.includeLanguages": {
    "edge": "html",
    "vue-html": "html",
  	"vue": "html"
  },
```

**Comment by zl-kolev** [comment]
Same thing on a Windows 10 x64 machine. The last update of Vetur must have something to do with Emmet. Personally, I don't think the VS Code update broke it.

Apart from that, the extension is great! Thumbs up! :)

**Comment by kumailn** [comment]
javascript intellisense and css autocomplete doesn't work either anymore :(

**Comment by weenta** [comment]
got the same problem

**Comment by yuicer** [comment]
same problem today , it just suddenly failed with tab(emmet)
macbook pro

**Comment by nereuseng** [comment]
I get this from my output, hope it helps.

`vetur initialized
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: UNKNOWN: unknown error, stat 'f:\vscode\doodle\20180313-udn-reading\vue-router\node_modules\.bin\acorn'
[Info  - 11:41:43] Connection to server got closed. Server will restart.`

**Comment by Rennzh** [comment]
@cannap I have the same problem that the css-tips has dispeared

**Comment by octref** [comment]
Seems in 1.23.1 we broke something in VS Code. This is working fine for me in VS Code Insiders. Can you give it a try and see if the issue also happens to you on Insiders?
https://code.visualstudio.com/insiders/

Meanwhile I'm looking into it.

**Comment by octref** [comment]
@nereuseng Can you try uninstall / reinstall? Your problem is probably different, when VS Code fail to install Vetur successfully. See https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#no-syntax-highlighting--no-language-features-working

**Comment by nereuseng** [comment]
Thanks a lot, last method 'install from vsix' solved my problem.

**Comment by octref** [comment]
Intended to publish as 0.11.9 but had a glitch and published an incomplete version to 0.12.0 by mistake...Anyway this should be fixed now in 0.12.1.
Let me know if you still see the issue on 0.12.1.

**Comment by dpyzo0o** [comment]
@octref Thanks for the quick fix! It works now, good job!

**Comment by nereuseng** [comment]
Updating to 0.12.1 today, the problem still exist. Please tell me what can I do to help you.

![ezgif-2-03a6b8712c](https://user-images.githubusercontent.com/11313394/40092892-4c919962-58f2-11e8-8a0b-ce7a1f1e1a06.gif)

**Comment by octref** [comment]
@nereuseng Can you make it larger? Also seems you have Vetur E extension which would mess up Vetur.

**Comment by vonweb** [comment]
@octref I have the same problem，but without Vetur E extension，haven't found which process cause it

**Comment by octref** [comment]
@nereuseng @vonweb What's your OS? Also any output on Output -> Vue Language Server or Help -> Toggle Developer Tools?

**Comment by vonweb** [comment]
@octref I'm using win10 17134.48
output from "Vue Language Server":
![tim 20180517174117](https://user-images.githubusercontent.com/5784758/40210698-0046838c-5a79-11e8-9fd0-37bfdd8d4b4b.png)
from Developer Tools:
![tim 20180517174008](https://user-images.githubusercontent.com/5784758/40210733-39363084-5a79-11e8-8c9f-0391a9b00aea.png)

**Comment by nereuseng** [comment]
Works in 0.12.3. Vue Language Server logs vetur initialized only.

![image](https://user-images.githubusercontent.com/11313394/40222992-0777de40-5ab4-11e8-9abe-6579d732e664.png)


OS: Windows 10, 1803, 17134.48

**Comment by octref** [comment]
@vonweb Upgrade to 0.12.3.

**Comment by vonweb** [comment]
@octref Thank you for your great work, it works

**Comment by Ezra-Siton-UIX** [comment]
**2 steps:**

1/2.  **install  Vetur**
![image](https://user-images.githubusercontent.com/16711871/74352702-8eeac980-4dc1-11ea-8fa0-294b05ca9d27.png)

2/2. **Update `setting.json`**
![image](https://user-images.githubusercontent.com/16711871/74352819-c0fc2b80-4dc1-11ea-95ed-07c4b98d568a.png)

**Done:**

![image](https://user-images.githubusercontent.com/16711871/74352968-eab55280-4dc1-11ea-806c-b5de38751b59.png)

**Comment by digimedialoop** [comment]
"emmet.includeLanguages": {
    "edge": "html",
    "vue-html": "html",
  	"vue": "html"
  }
Works for me to! Thx so much!

**Comment by crazould** [comment]
@Ezra-Siton-UIX Thanks man!

**Comment by olivsinz** [comment]
Thanks a lot everyone.

**Comment by Samuelnoah45** [comment]
"v" suggestion is not working   in vue  how can I fix it ??

**Comment by spoffyenar** [comment]
"emmet.includeLanguages": {
"edge": "html",
"vue-html": "html",
"vue": "html"
}
Works for me  . tnx
