### ISSUE TITLE
NO CSS style TIP in the Vue file

### ISSUE THREAD

**Issue by pannysp** [vuejs/vetur#788]
- Platform:macOS
- Vetur version: 0.11.8
- VS Code version: 1.23.1

Steps to Reproduce:
<style scoped> .demo{no style tip in here} </style>
in style of the Vue file,
I input "fon", that would show me:"font"or"font-size",but that is nothing, all nothing tip.

**Comment by octref** [comment]
#787, try updating to 0.12.1.
