### ISSUE TITLE
Vetur does not respect default indentation settings.

### ISSUE THREAD

**Issue by infinnie** [vuejs/vetur#790]
- [ ] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version: 0.14.2
- VS Code version: 1.29.1

## Problem

It supports neither the editor’s indentation settings nor CSS IntelliSense, both of which I rely a lot on.

**Comment by infinnie** [comment]
Update: not fixed _yet_.

**Comment by octref** [comment]
https://vuejs.github.io/vetur/formatting.html#settings

![image](https://user-images.githubusercontent.com/4033249/49242681-3b5cad80-f3c0-11e8-97b2-5cd3986d2289.png)

VS Code has indent detection on by default, and that always cause Vetur's formatter to receive wrong indentation settings. So I made these two settings.
