### ISSUE TITLE
Vetur not working syntax highlighting / Intellisense after VSCode update (1.23.1)

### ISSUE THREAD

**Issue by dsa28s** [vuejs/vetur#791]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win (Windows 10)
- Vetur version: 0.12.1
- VS Code version: 1.23.1

## Problem
After update VSCode 1.23.1, Vetur Plugin not working.
Not syntax highlighting, no intellisense and more....

Here is a screenshot, (No error message in Output Console) ;;

![Error Screenshot](https://i.imgur.com/6piZvno.png)

What should I do? 

I already doing re-install vscode, vetur plugin, and all plugins removed, and only install vetur plugin...
But, not working.

**Comment by mdschweda** [comment]
![untitled-1](https://user-images.githubusercontent.com/3602273/40079137-2083e192-5887-11e8-9ebf-a818af4d6576.png)

**Comment by octref** [comment]
https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#no-syntax-highlighting--no-language-features-working

**Comment by srkt** [comment]
Followed all the steps @octref mentioned but none worked for me. Installing old version  (0.22.3) worked for me .

**Comment by Chaaaaap** [comment]
Run command: Developer: Reinstall Extension for Vetur in VS Code as suggested in https://github.com/vuejs/vetur/blob/master/docs/FAQ.md did the trick for me

**Comment by ChrisKader** [comment]
I notice this only happens for me whenever I have an create a new document (unsaved, untitled), paste in code then set the language mode to "vue". If I save the document to my computer and restart VSCode, I have no issue.
