### ISSUE TITLE
Cant use postcss lang tag anymore

### ISSUE THREAD

**Issue by r0skar** [vuejs/vetur#792]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux

## Problem

Using following code:

```html
<style lang="postcss" scoped>
.test {
  color: #000000;
}
</style>
```
I get this error:

```
ERROR in ./node_modules/vuepress/lib/default-theme/Layout.vue?vue&type=style&index=2&id=25045c01&lang=postcss&scoped=true (./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vuepress/lib/default-theme/Layout.vue?vue&type=style&index=2&id=25045c01&lang=postcss&scoped=true)
Module parse failed: Unexpected token (172:0)
You may need an appropriate loader to handle this file type.
|
|
| .test {
|   color: #000000;
| }
 @ ./node_modules/vuepress/lib/default-theme/Layout.vue?vue&type=style&index=2&id=25045c01&lang=postcss&scoped=true 1:0-146 1:162-165 1:167-310 1:167-310
 @ ./node_modules/vuepress/lib/default-theme/Layout.vue
 @ ./node_modules/vuepress/lib/app/.temp/routes.js
 @ ./node_modules/vuepress/lib/app/app.js
 @ ./node_modules/vuepress/lib/app/clientEntry.js
 @ multi ./node_modules/vuepress/lib/app/clientEntry.js
```

The above code works just fine when omitting the lang tag. However, that breaks syntax highlighting.

Also see https://github.com/vuejs/vue-cli/issues/1285 and https://github.com/vuejs/vetur/issues/506

**Comment by hawezo** [comment]
I saw numerous issues for this but I can't seem to find any solution to fix it. [This comment](https://github.com/vuejs/vetur/issues/506#issuecomment-357618232) implies that it can be fixed, having ` vue-loader` configured doesn't solve the issue?

**Comment by octref** [comment]
@r0skar Did you have it fixed in vuepress?
