### ISSUE TITLE
Use stylus, after import something, no syntax highlighting

### ISSUE THREAD

**Issue by thereisnowinter** [vuejs/vetur#793]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: windows 10
- Vetur version:  0.12.1
- VS Code version: version 1.23

## Problem

With importing, no syntax highlighting. Everything is ok, just no highlighting. 
![With importing](http://p5vvvsx56.bkt.clouddn.com/importing.jpg)

Without importing,  syntax highlighting exist
![With importing](http://p5vvvsx56.bkt.clouddn.com/noImporting.jpg)

All code
![All code](http://p5vvvsx56.bkt.clouddn.com/AllCode.png)

after googleing for a long time, I really can not figure out by myself.  

Many Thanks in advance.

**Comment by HerringtonDarkholme** [comment]
I cannot reproduce. Can you paste the whole file content?

![screen shot 2018-05-17 at 7 54 36 pm](https://user-images.githubusercontent.com/2883231/40175896-38723110-5a0c-11e8-8da1-0f254b81aad5.png)

**Comment by thereisnowinter** [comment]
@HerringtonDarkholme  Thanks for your information.

I have tried what your recommend, But I really don't how to uninstall this extension by run command.

What I did is go to vscode extension file to delete the file, And reinstall it in extension market.

I also tried to  download pre-packaged vsix file and install through vsix.

All does not work.

I have updated all my code's screenshot to question area.

Thanks a lot.

**Comment by HerringtonDarkholme** [comment]
Can you update the whole file? And paste the code in the issue?

**Comment by thereisnowinter** [comment]
@HerringtonDarkholme Sorry, I thought I have updated yesterday. Now the the screenshot is there.

**Comment by thereisnowinter** [comment]
@HerringtonDarkholme I have **language-stylus**. Is it possible the other plugin's problem? They may conflict each other.

**Comment by HerringtonDarkholme** [comment]
You can ask vscode's question on stackoverflow. https://stackoverflow.com/questions/tagged/visual-studio-code

We currently don't have enough effort to answer every possible questions.

**Comment by thereisnowinter** [comment]
@HerringtonDarkholme Ok, Still  Thanks a lot for your helping.

**Comment by octref** [comment]
@thereisnowinter Actually this is because you did not install `stylus` extension, see https://vuejs.github.io/vetur/highlighting.html

I also made the notice to install sass/stylus extension more prominent in the `setup` page, in case that's where you missed it.

**Comment by octref** [comment]
@thereisnowinter This is what you need: https://marketplace.visualstudio.com/items?itemName=sysoev.language-stylus

**Comment by thereisnowinter** [comment]
@octref Actually I had this. I just reinstall vscode yesterday, now hightlighting works. Thanks for your information.
