### ISSUE TITLE
No formatter for 'vue'-files installed

### ISSUE THREAD

**Issue by cocody** [vuejs/vetur#794]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win 10
- Vetur version:  0.12.2
- VS Code version: 1.23.1

## Problem

Today, I update VS Code to 1.23.1, when I use "Format Document" command, but show "No formatter for 'vue'-files installed"

 "Format Document" is fine in VS Code 1.23.0

**Comment by HerringtonDarkholme** [comment]
I can format vue file. 

Can you try reinstalling vetur? https://vuejs.github.io/vetur/FAQ.html#no-syntax-highlighting-no-language-features-working

**Comment by ikbelkirasan** [comment]
Same issue, Vetur used to work perfectly but now the document formatting feature stopped working with the latest update of VS Code.

**Comment by cocody** [comment]
done! thank you!

**Comment by HerringtonDarkholme** [comment]
It should be again problem from chokidar...

**Comment by ozguruysal** [comment]
@HerringtonDarkholme 0.12.3 fixed the problem for me. Thank you!

**Comment by jessehallam** [comment]
Vetur 0.12.5, VSCode 1.24.1. Windows 10.

I cannot format: There is no document formatter for 'vue'-files installed.

**Comment by wiseman** [comment]
I get `There is no document formatter for 'vue'-files installed` with a fresh install of Vetur 0.12.5 and Visual Studio Code 1.24.1 on OS X.
