### ISSUE TITLE
Cover Vetur's Language Features with ene-to-end tests

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#802]
https://github.com/octref/vscode-language-server-e2e-test

- [x] Infrastructure from https://github.com/octref/vscode-language-server-e2e-test
- [x] Basic formatting
- [x] Basic definition
- [x] Full formatting
- [x] Full definition
- [x] Completion
  - [x] Template
  - [x] Style
  - [x] Script
- [x] Diagnostics
- [x] Hover
- [x] Highlight
- [x] References
- [x] Document Link
- [x] Document Symbol
- [x] Color Presentation — later, will need to update LanguageServer node module first
- [x] Signature Help — later, this is only available to `<script>` section and that is tightly coupled with the TS version we are using (about to update).

---

- [x] Setup travis so e2e test runs together with unit tests
- [x] Setup coverage report — seems too tricky with mocha + TypeScript and then our extension setup

Functionalities:

- [x] Reenable `documentLink`

**Comment by octref** [comment]
@HerringtonDarkholme FYI, think these tests are much easier to write.

@ktsn I'll update the type-checking PR with E2E tests. Otherwise it's impossible to mock up everything for testing.

**Comment by HerringtonDarkholme** [comment]
Sounds Great! E2E test is better for script/style integration than unit test. Thanks for bringing about e2e framework!
