### ISSUE TITLE
Distinguish between JS and TS grammar to have better syntax highlighting in template interpolations

### ISSUE THREAD

**Issue by troy351** [vuejs/vetur#804]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  Win
- Vetur version: 0.12.3
- VS Code version: 1.23.1

## Problem
this is abnormal
![qq 20180523101403](https://user-images.githubusercontent.com/8372385/40399845-1b1d8fc8-5e72-11e8-9537-7511ee20712e.png)

this is normal
![qq 20180523101427](https://user-images.githubusercontent.com/8372385/40399867-2d72b590-5e72-11e8-84a2-8b14735e4c61.png)

However, the code just works fine in both cases

FYI, theme is `One Dark Pro`

**Comment by HerringtonDarkholme** [comment]
This is a problem in vscode. You can try this in JS.

```js
type in someArray
```

<img width="182" alt="screen shot 2018-05-30 at 1 35 57 pm" src="https://user-images.githubusercontent.com/2883231/40700939-6bc35ed4-640e-11e8-8092-c695d563e111.png">

type is highlighted as keyword.

**Comment by octref** [comment]
Yea, the problem is VS Code has no distinction between TS/JS grammar. This has come up multiple times.
It's possible for us to switch to https://github.com/michaelgmcd/vscode-language-babel for JavaScript though. I ca look into this.
