### ISSUE TITLE
Formatting of JavaScript in .vue files is broken after release of Prettier 1.13.0

### ISSUE THREAD

**Issue by zavarka** [vuejs/vetur#807]
## Info

- Platform: macOS
- Vetur version: 0.12.3
- VS Code version: 1.23

## Problem

Formatting of JavaScript in the `<script>` block is broken with the release of Prettier 1.13.0.  Format Document does not make any corrections.

In contrast, the `<style>` block is being formatted as expected.

Installing Prettier 1.12.1 in the project and reloading VSCode fixes the issue:

```npm install -D -E prettier@1.12.1```

## Reproducible Case

1. Create a VueJs project by running `vue init webpack-simple` and accepting the defaults.
2. Open App.vue and introduce a misalignment or a trailing space inside the `<script>` block.
3. Run "Format Document".
4. Observe that no corrections are made in the `<script>` block.
5. Install Prettier 1.12.1 using the npm command given above and reload the window.
6. Run "Format Document".
7. Observe that the formatting issues added in step 2 are corrected.

**Comment by lesonky** [comment]
I have the same problem,

**Comment by patrickcate** [comment]
I'm having the same issue. The following error is shown in the vue language server output log:
```
prettier-eslint [ERROR]:
Prettier-Eslint format failed
[Error - 12:17:56] No parser could be inferred for file: **the path to the local file**
```
Changing the default formatter to typescript like @lesonky suggested didn't fix.

**Comment by zavarka** [comment]
@octref Thanks for taking a look!  I'm still able to reproduce the problem with prettier@1.13.4, and downgrading to prettier@1.12.1 still fixes it.

**Comment by octref** [comment]
@zavarka For this project https://github.com/octref/veturpack

If you clone it and run `yarn add -D prettier@1.13.4`. This still happens to you?

**Comment by zavarka** [comment]
@octref Yes, the same issue occurs with the project https://github.com/octref/veturpack.  Initially, the formatting works, but after running `yarn add -D prettier@1.13.4` it no longer works.

**Comment by HADB** [comment]
I have the same problem!

I will get the following error when formatting if I set `prettier.eslintIntegration` to `true`.

```
Prettier-Eslint format failed
[Error - 16:24:40] No parser could be inferred for file: ...
```

VSCode version: 1.24.1
Vetur version: 0.12.5
Prettier plugin version: 1.5.0

**Comment by Airkro** [comment]
@octref Maybe you should reopen this issues.

Since v1.13.x, Pettier make a [breaking change](https://prettier.io/blog/2018/05/27/1.13.0.html#don-t-default-to-the-javascript-parser-4528-by-duailibe).  And prettier/prettier@1350edc didn't fix it, just trigger a warning.

When I install Pettier 1.13.x, VLS output `No parser could be inferred for file`.

**Comment by octref** [comment]
@Airkro We bundle prettier 1.11.1. How are you updating?

**Comment by Airkro** [comment]
@octref Sorry, I mean install it in my project root, just `yarn add -D prettier`

**Comment by octref** [comment]
@Airkro Thanks, will track it in #835.
