### ISSUE TITLE
Automatic Type Acquisition for modules installed without @types definition

### ISSUE THREAD

**Issue by kevinly24** [vuejs/vetur#808]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  Win
- Vetur version: 0.12.3
- VS Code version: 1.23.1

## Problem

JS module resolution doesn't work in vue files, and intellisense does not get loaded for those modules either

test.vue:
`import test from 'custom-module'`

vs

test.js:
`import test from 'custom-module'`

## Reproducible Case

![Alt Text](https://media.giphy.com/media/p3cn60KhgU6rZz063h/giphy.gif)

**Comment by sbowler** [comment]
I believe I have the same issue. I've created a jsconfig file and so my alias paths seem to work fine in .js files, but if I include a js file in a vue SFC then I get no intellisense.
For example importing a .js file like so doesn't seem to give me intellisense like it does doing the same thing from a .js file.
```
import utility from '@/util/utility';
utility.getFormattedTime();
```

**Comment by PeterChen1997** [comment]
I have the same issue~!!

**Comment by octref** [comment]
VS Code has [Automatic Type Acquisition](https://code.visualstudio.com/updates/v1_7#_better-javascript-intellisense), which Vetur doesn't have. For now, you need to add `@types/async` to your local project.

**Comment by pumpkinlink** [comment]
thanks, running
```bash
npm install @types/mylibrary --save-dev
```
then Ctrl+Shift+P → "Reload Window" did the trick for me

**Comment by octref** [comment]
It's quite complicated to do this, and many things could go wrong so I won't do it.
