### ISSUE TITLE
Unable to stop less validate when I set less.validate to false in user settings.

### ISSUE THREAD

**Issue by zuoez02** [vuejs/vetur#809]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  macOS 10.13.4
- Vetur version: 0.12.3
- VS Code version: 1.23.1

## Problem

![image](https://user-images.githubusercontent.com/4801955/41010596-0eea7096-696b-11e8-97d1-dbdbafaceb59.png)

I want to use stylelint in vue file and it works. But the less validate is still working. I set `less.validate: false` in user settings.  It works in .less file but is not working in .vue `<style>` block.

## Reproducible Case
1. Disable all extensions except vetur and reload window.
2. Set user setting `less.validate: false`
3. write below code in style block
```less
<style lang="less" scoped>
@block: {
  .style {
    float: right;
  }
};
</style>
```
3. It said "[less] } expected(3, 3)" in PROBLEMS card

**Comment by octref** [comment]
`"vetur.validation.style": false`. I've also updated docs.

**Comment by zuoez02** [comment]
@octref Actually I just want close less validation because it is the bug of VSCode less validation. How to keep css validation and close less validation? Should we have ability to choose specific style languages to validate? Just like:
```json
"vetur.validation.style": ["css", "scss"]
```

**Comment by octref** [comment]
You can use VS Code's workspace setting, so this would only apply to your project using less. Vetur does not offer per-language toggling of diagnostics.
