### ISSUE TITLE
Add scaffold for Typescript & vue-class-component / vue-property-decorator

### ISSUE THREAD

**Issue by ascott18** [vuejs/vetur#810]
This was briefly mentioned in https://github.com/vuejs/vetur/issues/669, but was not the primary point of that issue. 

It would be nice to get a scaffold for using vue-class-component and vue-property-decorator. Something like

``` html
<script lang="ts">
import { Vue, Component, Prop, Watch } from 'vue-property-decorator';

@Component({
 
})
export default class extends Vue {
  
}
</script>
```

I included Prop and Watch as imports in this example as they're likely to be used quite commonly. The other property decorators are less likely and can always be imported as needed.

**Comment by octref** [comment]
I'll do #1151 instead.
