### ISSUE TITLE
Vetur highlighting breaks when using Vue Router route params

### ISSUE THREAD

**Issue by drw112** [vuejs/vetur#811]
- [X ] I have searched through existing issues
- [ X] I have read through [docs](https://vuejs.github.io/vetur)
- [ X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.12.4
- VS Code version: 1.24.0

## Problem

![image](https://user-images.githubusercontent.com/9697868/41061668-fa412eb8-6998-11e8-822b-afb6b6e5a67a.png)

All syntax highlighting breaks/inverts on double quotes after using a router link with a param option.  Started after he upgrade to VS Code 1.24

## Reproducible Case

Create a router link with a params object.  All syntax highlighting after that breaks/inverts on double quotes.  It doesn't seem to matter if the to param uses single quotes of double quotes.  What matters is putting an object in for the params.

**Comment by octref** [comment]
Fixed in 0.12.5.
