### ISSUE TITLE
External templates break syntax highlighting

### ISSUE THREAD

**Issue by ThomasKientz** [vuejs/vetur#813]
## Info

- Platform: macOS
- Vetur version: 0.12.3
- VS Code version: 1.23.1

## Problem

```
<template 
  src="./mission.html" 
  lang="html"/>

<script>
//code not being highlight
<script>
```
Breaks syntax highlighting (and maybe formating too)

But this is using **recommended** vue's es-linting rules.

2 things is causing the break :

- `/` inside `src` attribute.
- multi lines

**Comment by octref** [comment]
```vue
<template src="./mission.html"></template>

<script>
</script>
```

**Comment by ThomasKientz** [comment]
This works but doesn't respect [enforce self-closing style (vue/html-self-closing)(https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/html-self-closing.md) from vue recommended style.

**Comment by octref** [comment]
That does not concern the enclosing region divider. However the syntax highlight does have some problem now...

**Comment by octref** [comment]
I'll just make sure this works:

```
<template src="./mission.html" />
```

I will never support multiline.

**Comment by octref** [comment]
This is now supported:

![image](https://user-images.githubusercontent.com/4033249/57395413-e7c76a80-717c-11e9-9e8b-b928abd598c0.png)

Multi line is not possible without a lot of hacks, so I'll pass on that.

**Comment by octref** [comment]
Just to link to https://github.com/Microsoft/vscode-textmate/issues/32 on why mutiline is almost impossible.
