### ISSUE TITLE
Vue user snippet not working with vscode 1.24.0 vetur 0.12.5

### ISSUE THREAD

**Issue by hanxue** [vuejs/vetur#814]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.12.5
- VS Code version: 1.24.0

## Problem

Only output from  **Panel -> Output -> Vue Language Serve** is 

```
Vetur initialized
```
I have a `vue.json` user snippet with the following content:

```javascript
{
	"Print to console": {
		"prefix": "conso",
		"body": [
			"console.log('DEBUG: value of ${1:varname}: ' + ${2|var,JSON.stringify(var)|})",
		],
		"description": "Log output to console"
	}
}
```

It has been working with Vetur + VSCode 1.23.0 and prior, and only stopped working when I upgrade to VSCode 1.24.0

To be sure that the user snippet is actually working, this is what I did:

1. Disable Vetur
2. Enable the extension `Vue` https://github.com/LiuJi-Jim/vscode-vue.git
3. Reload VSCode
4. User snippet is working. See the screenshots below

![image](https://user-images.githubusercontent.com/760008/41145626-53dd399e-6b33-11e8-800f-6fd2c8efeaf2.png)
![image](https://user-images.githubusercontent.com/760008/41145639-6226f24c-6b33-11e8-861a-f4c746ae90dc.png)

I also went ahead and

1. Renamed the snippet shortcut from `conso` to `debug`
2. Tested to make sure it is working with `Vue` extension
3. Disable `Vue` extension
4. Re-enable the `Vetur` extension
5. Test again by typing `debug` in a Vue source file, and it does not work

I also have the following in my VSCode user settings:

```json
    "editor.snippetSuggestions": "top",
    "editor.tabCompletion": true
```

**Comment by octref** [comment]
I don't think that's ever supposed to work. In the `<script>` section only JavaScript snippets will be available. You should move that snippet to the JS snippet definition file.

**Comment by bammoo** [comment]
see also https://github.com/vuejs/vetur/issues/718
