### ISSUE TITLE
can't find definition in template and local (this.)

### ISSUE THREAD

**Issue by peipei1109** [vuejs/vetur#817]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.12.5
- VS Code version:1.24.0

## Problem

can't find any definition for "this.xxx" and templete
for example I defined   formParams 

<img width="427" alt="image" src="https://user-images.githubusercontent.com/15414890/41186680-405cb828-6bcd-11e8-8192-a5fa7f1f2130.png">
but when I use F12 to go to this definition .I can't find any definition for formParams, as shown:

<img width="379" alt="image" src="https://user-images.githubusercontent.com/15414890/41186729-fe20a784-6bcd-11e8-956c-958563ca9abe.png">

the same situation in template
<img width="703" alt="image" src="https://user-images.githubusercontent.com/15414890/41186733-22bea050-6bce-11e8-9344-1afdf50760d1.png">

how can I fix this problem ?

**Comment by octref** [comment]
What's your local vue version?

**Comment by octref** [comment]
Jump to definition is shipped in https://github.com/vuejs/vetur/blob/master/CHANGELOG.md#vue-template-interpolation-language-features.
