### ISSUE TITLE
Format on save feature

### ISSUE THREAD

**Issue by popo63301** [vuejs/vetur#818]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  macOS
- Vetur version: 0.12.5
- VS Code version: 1.24.0

## Suggestion

Would be great if we can have a format on save feature.

**Comment by Ewocker** [comment]
Hi @popo63301 ,
    This is my first day using vscode. While trying to use vetur, I find your issue here and as well as the doc here https://github.com/vuejs/vetur/blob/master/docs/linting-error.md .

**Comment by franciscolourenco** [comment]
@popo63301 VScode already supports this. It uses Vetur as the formater. You just need to enable this option:

<img width="984" alt="Screen Shot 2019-03-13 at 14 41 18" src="https://user-images.githubusercontent.com/208149/54283357-1c181380-459e-11e9-8093-7ce893cf5b2f.png">

**Comment by octref** [comment]
As @franciscolourenco said, this is already supported.

**Comment by ecerulm** [comment]
If Visual Studio Code format on save is not working for your vue files it maybe because there are several formatters registered for `.vue` files and you need to explicitly set "Vetur" as the formatter (see below):
```
{
    "editor.formatOnSave": true,
    "vetur.format.defaultFormatter.html": "js-beautify-html",
    "[vue]": {
        "editor.defaultFormatter": "octref.vetur"
    }   
}
```
