### ISSUE TITLE
Do not add zero before the decimal point (scss)

### ISSUE THREAD

**Issue by xereda** [vuejs/vetur#819]
- Platform: Linux
- Vetur version: 0.12.5
- VS Code version: 1.24.0

## Problem

How do I disable the automatic inclusion of zero at the beginning of values with decimal? 

Here in the company, we use stylelint with the parameter "number-leading-zero" with the value "never". And we believe that this rule should continue like this.

The question is how to disable this automatic fix on vetur?

Thank you very much in advance,

![leading-zero](https://user-images.githubusercontent.com/14337850/41235246-c179bcec-6d64-11e8-8328-76070914e158.gif)

**Comment by octref** [comment]
We don't support StyleLint yet: https://github.com/vuejs/vetur/issues/712
This is working as intended for prettier. If you don't want it the only thing you can do now is to turn off scss formatter by setting:

```
"vetur.format.defaultFormatter.scss": "none"
```
