### ISSUE TITLE
Couldn't start client Vue Language Server

### ISSUE THREAD

**Issue by pan-J** [vuejs/vetur#821]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version:
- VS Code version:

**Comment by vostokwork** [comment]
Same problem.

**Comment by vmato** [comment]
I'm also getting this message on startup

**Comment by yoyo930021** [comment]
> I'm also getting this message on startup
> v0.33.1

Doing and reply in that issue.
https://github.com/vuejs/vetur/issues/2724#issuecomment-804893788
