### ISSUE TITLE
No intellisense for imports

### ISSUE THREAD

**Issue by ajitid** [vuejs/vetur#822]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: 0.12.5
- VS Code version: 1.24.1

## Problem

No Intellisense is provided in line `import {moduleName} from ''` when <kbd>ctrl</kbd> +<kbd>space</kbd>d between quotes and braces to get list of installed packages and exported modules respectively. This works fine in JS files.

**Comment by pumpkinlink** [comment]
I think this is duplicate of #808
