### ISSUE TITLE
Vetur does not work vscode-language-babel extension for Syntax Highlighting

### ISSUE THREAD

**Issue by lehni** [vuejs/vetur#825]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS/Linux
- Vetur version: 0.12.5
- VS Code version: 1.24.1

## Problem

I am using `vscode-language-babel` for JavaScript syntax highlighting because of its support of some stage-1 proposals, e.g. the nullish coalescing operator (https://github.com/tc39/proposal-nullish-coalescing, see https://github.com/michaelgmcd/vscode-language-babel/pull/28)

While this works well in normal JS files, Vetur fails to color such operators correctly, and they sometimes confuse huge parts of the following code.

I looked at the code of both extensions, and saw that while Vetur uses `source.js` as the identifier for code,  `vscode-language-babel` uses `source.js.jsx`.

So i went ahead and replaced the few occurrences of `source.js` that I found in Vetur that seemed to be responsible with `source.js.jsx` and restarted VSCode, and the syntax highlighting started to work correctly!

I can't tell what's really needed to make this work reliably, but it looks like it's actually doable.

Could this be looked into and considered? I am happy to help out if possible.

**Comment by lehni** [comment]
I just tested this change with the default VSCode highlighter, and it still works as well.

**Comment by lehni** [comment]
It looks like this could / should be changed at the other end: https://github.com/michaelgmcd/vscode-language-babel/issues/29

**Comment by octref** [comment]
The scope of babel plugin is fine. VS Code's own JSX grammar uses the same scope: https://github.com/Microsoft/vscode/blob/master/extensions/javascript/syntaxes/JavaScriptReact.tmLanguage.json

We already dynamically generate Textmate grammar with user settings for syntax highlighting in custom blocks. See https://github.com/vuejs/vetur/blob/master/client/grammar.ts

Actually now looking back to this: https://github.com/vuejs/vetur/issues/506, I would say having an option `vetur.grammar.builtinBlocks` would make sense, so people can write:

```js
"vetur.grammar.builtinBlocks": {
  "style": {
    "css": "source.css.postcss"
  },
  "script": {
    "js": "source.js.jsx"
  }
}
```

If you are interested in contributing, the places you need to make changes are https://github.com/vuejs/vetur/blob/master/package.json#L131 and the grammar regeneration code above. We don't have tests covering the textmate grammar yet.

**Comment by lehni** [comment]
@octref since https://github.com/michaelgmcd/vscode-language-babel/issues/29 got accepted, the actual issue is resolved for me... We could close this issue, but since you see room for improvement here I'll leave it up to you to decide what to do with this. I hope that's OK?

**Comment by octref** [comment]
That's fine, glad it's resolved for you. Thanks!
