### ISSUE TITLE
Markdown tag is not being formatted

### ISSUE THREAD

**Issue by xereda** [vuejs/vetur#829]
- Platform: Linux
- Vetur version:0.12.5
- VS Code version: 1.24.1

## Problem

Custom block `<markdown>...</markdown>` is not being formatted by vetur.

## Reproducible Case

Create a .vue SFC file and add the <markdown> block / tag with markdown style statements.

## Evidence

![vue-file](https://user-images.githubusercontent.com/14337850/41912379-f0c5df36-7925-11e8-83af-a828f43218e0.png)

![config](https://user-images.githubusercontent.com/14337850/41912427-21989130-7926-11e8-95d1-8f1a78e55f4e.png)

**Comment by octref** [comment]
I think it's better to not have a markdown formatter.
