### ISSUE TITLE
IntelliSense not working for Vuex $store variable in single file components

### ISSUE THREAD

**Issue by JulianSchoenbaechler** [vuejs/vetur#832]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info
- Platform: Win 10
- Vetur version: 0.12.5
- VS Code version: 1.24.1
- Vue-CLI v3.0.0-rc.3

## Problem
When using Vuex in single file components, the `$store` variable is not detected by Vetur's IntelliSense unless the store is explicitly declared like in `main.js`. Accesing and using the Vuex store works without any problems, it's just IntelliSense that does not provide Vuex support. All other Vue suggestions are displayed without any problems.
Following `src` project structure (standard Vuex setup in Vue-CLI 3):
![project-structure](https://user-images.githubusercontent.com/10711264/42188529-82d10990-7e54-11e8-92d3-a1f3327cd871.jpg)

A screenshot of the error:
![intellisense-vetur](https://user-images.githubusercontent.com/10711264/42188600-ed2420de-7e54-11e8-95bd-37797353d1c1.jpg)

## Reproducible Case
- Create a new Vue project with the [Vue-CLI 3](https://github.com/vuejs/vue-cli/releases/tag/v3.0.0-rc.3) `vue create project-name`
- Setup with Vuex (or add Vuex with `vue add vuex`)
- Access the automatically created Vuex store in any single file component with `this.$store`.

**Comment by JulianSchoenbaechler** [comment]
Not sure what went wrong but reinstalling Vetur did fix that problem 😒, sorry for that.

**Comment by octref** [comment]
@JulianSchoenbaechler 
No worries - I have seen this happen from time to time. You might need to open any Vue file that imports Vuex to get the completions, as Vuex and its typings are not loaded by TS Server by default.

**Comment by stefnotch** [comment]
I followed the exact same steps and got the same issue. Reinstalling Vetur sadly did not resolve the issue.
![image](https://user-images.githubusercontent.com/10220080/56042549-98d41400-5d3b-11e9-8ae0-d08159a3ff8c.png)

Therefore I'd love to see this issue being re-opened.

**Comment by octref** [comment]
@stefnotch Try it in https://github.com/octref/veturpack, and modify your project to follow the setup. As long as you have a recent version of vue/vuex installed with types, this should work.

**Comment by stefnotch** [comment]
@octref Thank you very much for the quick response. I can confirm that that does work. 😄

**Comment by stefnotch** [comment]
It seems that all that was missing is the `tsconfig.json`

e.g.
```
{
  "compilerOptions": {
    "target": "es2018",
    "strict": true,
    "noUnusedLocals": true,
    "noImplicitAny": true,
    "lib": ["es2018", "dom"],
    "allowJs": true
  }
}
```

Then, if a file has something like the following, `this.$store` will exist.
```
import Vue from "vue";
import Vuex from "vuex";

Vue.use(Vuex);
```
