### ISSUE TITLE
Upgrade to js-beautify 1.7.6

### ISSUE THREAD

**Issue by affanshahid** [vuejs/vetur#833]
JS-Beautify have fixed an issue https://github.com/beautify-web/js-beautify/issues/1186
in version 1.7.6. Is it possible to update the dep?

**Comment by octref** [comment]
It is not released yet: https://www.npmjs.com/package/js-beautify.

**Comment by octref** [comment]
Just saying, current latest release is 1.8.0-rc4. I'll wait until 1.8.0 stable is released and upgrade.

**Comment by guahsu** [comment]
@octref 
Is there any chance to update this version to vetur?
https://github.com/vuejs/vetur/issues/99
thanks :)

**Comment by Luiggi370z** [comment]
any update on this?

**Comment by octref** [comment]
This has been available since last Vetur release.
