### ISSUE TITLE
There is no selection formatter for 'vue'-files installed.

### ISSUE THREAD

**Issue by karyhm** [vuejs/vetur#834]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win 10
- Vetur version: 0.12.5
- VS Code version: 1.24.1

## Problem
Can't format .vue files. I'm trying to format .vue files from a Vue project made using CLI. 
Error "There is no selection formatter for 'vue'-files installed." appears.
It does not work when you save the file either

### Vue file
![image](https://user-images.githubusercontent.com/34516872/42242571-f1f9f334-7ed3-11e8-94db-2f74edc0ba0f.png)

### Extensions
![image](https://user-images.githubusercontent.com/34516872/42242597-0b444d80-7ed4-11e8-9d81-e84a5a28240c.png)

### My settings
![image](https://user-images.githubusercontent.com/34516872/42242618-201d8a0a-7ed4-11e8-9ccf-f702ca7dadf1.png)

**Comment by octref** [comment]
We only have a whole document formatter, no range formatter.

**Comment by octref** [comment]
https://vuejs.github.io/vetur/formatting.html#formatting

**Comment by martinnaughton** [comment]
Added this line to get html formatting to work
```
{
  // Default formatter for <template> region
  "vetur.format.defaultFormatter.html": "prettier",
}
```

**Comment by stefandevo** [comment]
@martinnaughton I get "value is not accepted"; I can only choose None and js-beautify-html.

**Comment by alirezajs** [comment]
I resolve my problem with the followed code in the Visual studio code setting
 {
    "vetur.format.defaultFormatter.html": "js-beautify-html"
}

**Comment by jochamlu** [comment]
document formatting works with the vetur pack. Lock at your shortcuts

**Comment by hyvyys** [comment]
Specifying formatter for only SCSS should be an option. It works when I set
`"vetur.format.defaultFormatter.html": "js-beautify-html"`
even though I don't have it installed.
