### ISSUE TITLE
Question: how to trigger additionalTextEdits ?

### ISSUE THREAD

**Issue by roxma** [vuejs/vetur#839]
I'm testing vls, LanguageClient-neovim and [ncm2](https://github.com/ncm2/ncm2), with either [ncm2-snipmate](https://github.com/ncm2/ncm2-snipmate) or [ncm2-ultisnips](https://github.com/ncm2/ncm2-snipmate)

Currently snippets like `attr="$1"$0` works well

But I want to add `additionalTextEdits` supports too. I don't know how to trigger this kind of completion. So I'm asking here for a use case that I can start to work with.

**Comment by octref** [comment]
Check out lsp-sample:

https://github.com/Microsoft/vscode-extension-samples/blob/master/lsp-sample/server/src/server.ts#L180-L198

You can add `additionalTextEdits` in `onCompletion` or `onCompletionResolve`.
Or are you saying vls should provide some `additionalTextEdits`?

**Comment by octref** [comment]
I see. Here's a gif. You can try it in this project: https://github.com/Microsoft/language-server-protocol-inspector

![autoimport](https://user-images.githubusercontent.com/4033249/42607633-88f066b8-85b6-11e8-9a29-2315aa94ba97.gif)

Meanwhile you might find this Inspector useful: https://microsoft.github.io/language-server-protocol/inspector

You can set `vetur.trace.server: "verbose"` and save the log somewhere, then load it in the inspector to analyze it.

**Comment by roxma** [comment]
@octref  Thanks for your help

This is what I've been working on:

https://github.com/autozimu/LanguageClient-neovim/pull/514

**Comment by octref** [comment]
@roxma Very nice, the only thing I'm missing from VS Code is consistent Vim commands :p
