### ISSUE TITLE
Pug comment style configuration

### ISSUE THREAD

**Issue by lxmfly123** [vuejs/vetur#840]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.12.5
- VS Code version: 1.25.1

## Problem
Pug template was commented as `//` when I press cmd+/, how can I configure this to `//-`?

**Comment by lxmfly123** [comment]
I find a solution.
In the *vue-language-configuration.json* file of the extension, change `comments.lineComment` from `"//"` to `"//-"`.

**Comment by octref** [comment]
I updated Vetur to use the updated language Id `pug` instead of `jade` (see #812), but VS Code reverted it back to using `jade`...

https://github.com/Microsoft/vscode/issues/50268

I'll change it back to `jade` for now.
