### ISSUE TITLE
No indentation changes when attempting to format

### ISSUE THREAD

**Issue by nbystrom** [vuejs/vetur#842]
- [ x ] I have searched through existing issues
- [ x ] I have read through [docs](https://vuejs.github.io/vetur)
- [ x ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows 10
- Vetur version: 0.12.5
- VS Code version: 1.25.1

## Problem

Formatting to change indentation size does not change anything.

Expected: indents should change from 2 spaces to 4.
Outcome: no visible change occurs to the document.

## Reproducible Case

1. Click "spaces: 2" button in bottom right
2. Change number of spaces from 2 to 4
3. Press [shift] + [alt] + [f] to format (or [ctrl] + [shift] + [p], then click format document)

**Comment by octref** [comment]
That's correct — script & style parts use prettier, so you should set `prettier.tabWidth` in either your setting or in a `.prettierc` file.
