### ISSUE TITLE
Vetur doesn't support @typedef in JSDoc

### ISSUE THREAD

**Issue by ffxsam** [vuejs/vetur#844]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS 10.13.6
- Vetur version: 0.12.5
- VS Code version: 1.25.1

## Problem

.vue files do not recognize valid JSDoc syntax (using `@typedef` to define types).

See reproduction repo below. Basically, when I type `getAudiences(`, IntelliSense shows `options` as being of type `any`, which is incorrect. However, if you import this function in a regular .js file, you'll see it shows `ApiOptions`, and it's possible to trigger auto-suggest which shows the individual `ApiOptions` properties, too.

Example in .vue file:

![image](https://user-images.githubusercontent.com/12532733/42947429-ec0aa908-8b32-11e8-999f-67b976004207.png)

Example in .js file:

![image](https://user-images.githubusercontent.com/12532733/42947619-5c236c16-8b33-11e8-9611-f62ee763ab6b.png)

## Reproducible Case

https://github.com/ffxsam/vetur-jsdoc-bug

**Comment by octref** [comment]
Seems fixed together with upgrading TS in https://github.com/vuejs/vetur/issues/1163:

![image](https://user-images.githubusercontent.com/4033249/57497767-e6d22e00-728d-11e9-964d-20ff45d2bf52.png)
