### ISSUE TITLE
css property 'appearance' was treated as unkown property

### ISSUE THREAD

**Issue by Eschere** [vuejs/vetur#848]
- [x] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win 10
- Vetur version:0.12.5
- VS Code version:1.25.1

## Problem

problem Panel:
  demo.vue
   [css] Unkown property 'appearance'(5,5)

## Reproducible Case

1.create a .vue file
2.create a tag <style>
3.write style sheet like 
 ```
<style>
  .demo {appearance: button}
</style>
```

**Comment by octref** [comment]
This requires us upgrading to latest `vscode-css-languageservice`.

**Comment by yoyo930021** [comment]
This problem is solved.
![截圖 2020-12-29 上午11 15 44](https://user-images.githubusercontent.com/9126398/103256185-39aeab00-49c7-11eb-8a7f-c25f47e892a2.png)
