### ISSUE TITLE
Make use of installed formatters?

### ISSUE THREAD

**Issue by langdonx** [vuejs/vetur#850]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

This seems like a dumb question, but a very real possibility, so I have to ask...

Is it not possible to make use of already-installed formatter extensions in VS Code to do Vetur's bidding?  Meaning if I already have a formatter for HTML, JavaScript, and CSS installed and configured how I like, is there not some VS Code API available to just format those sections?

If not, should we not urge VS Code to somehow expose this as a possibility?  It seems like it would reduce a ton of potentially duplicative efforts and make this extension that much better.

**Comment by langdonx** [comment]
You'll have to excuse my ignorance, as I've never authored a VS Code extension, so I don't know what is or isn't possible.

I'm not suggesting hooking Vetur into arbitrary dependencies, but instead make use of a (perhaps a non-existing) VS Code API that might format a string of code (extracted from a Vue file) for a given Language.

If it were possible, it would make Vetur more of a delegate and the formatting possibilities would be endless.

Given [this thread](https://github.com/Microsoft/vscode/issues/41882), I'm guessing maybe it's not currently possible with VS Code, but it seems like a rather straight forward and likely valuable idea.  Are there other file formats similar to `.vue` that combine multiple languages within?  Might be an easier sell to VS Code if it wasn't just for `.vue`.

**Comment by octref** [comment]
As you mentioned, if you have 5 HTML formatters, there is no way for Vetur to say "use the third one". There is no API for getting a list of available formatters for a specific language or for getting currently active formatter.
So there is no way to rely on other extensions for providing formatting capabilities.

**Comment by langdonx** [comment]
So that's it, just closed?  Does the idea not have merit?  VS Code is open source and always evolving, certainly it's worth pursuing?

**Comment by octref** [comment]
You can open issues on VS Code repo. Until they offer an API, there is nothing I can do.
