### ISSUE TITLE
Sass intellisense

### ISSUE THREAD

**Issue by marioffdsw** [vuejs/vetur#851]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.12.5
- VS Code version: 1.25.1

## Problem
Css properties- intellisense does not work on sass style
![sass-intellisense](https://user-images.githubusercontent.com/10393319/43490021-8880fc96-94e4-11e8-8eae-4b9c36c1a180.png)
but if i use plain css it shows a long list of properties
![css-intellisense](https://user-images.githubusercontent.com/10393319/43490049-9ec55c90-94e4-11e8-905a-bbed5116deb5.png)

This is from the documentation
![documentation](https://user-images.githubusercontent.com/10393319/43490113-e90e6aa8-94e4-11e8-9c0d-5e83136122e1.PNG)

Sass is not one of the languages that appears as supported, Are there any plans for supporting it? What could be done to enable intellisense in sass styles?

**Comment by octref** [comment]
Sass Autocompletion: This requires a sass Language Server, which no one has now, and I do not have time to build one.

**Comment by bgibb95** [comment]
Is there any workaround to this problem? I really need IntelliSence for my sass in my vue files.

**Comment by Andreychik32** [comment]
@bgibb95, the best workaround in this case is to use scss syntax for your code. It has the same functionality as sass does. Scss is not uglier than sass, I think.

**Comment by 3nuc** [comment]
Webstorm supports cross-file variable extraction, go to definition etc., so should be possible 2 years later
![image](https://user-images.githubusercontent.com/5359825/94943765-7fe39380-04d8-11eb-8846-3aa48ee44104.png)

**Comment by octref** [comment]
@3nuc You can open a new feature request. SCSS is supported but not SASS.
