### ISSUE TITLE
Emmet doesn't works as expected in SCSS style part

### ISSUE THREAD

**Issue by Varkal** [vuejs/vetur#852]
- [/] I have searched through existing issues
- [/] I have read through [docs](https://vuejs.github.io/vetur)
- [/] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOs
- Vetur version: 0.12.5
- VS Code version: 1.25.1

- Vue server console:  only "Vetur initialized"

## Problem
In the scss part of a vue file, the intelisense doesn't contains emmet abbrevation at the top. 
So, on tab, it's an other suggestion that used for completion.

<img width="1440" alt="capture d ecran 2018-08-01 a 07 58 07" src="https://user-images.githubusercontent.com/3471491/43503711-ab47e43e-9560-11e8-992b-ff71e6bc90e7.png">

If i close intelisense with ESC, and hit tab, the emmet abbreviation is expanded.
If i remove the lang="scss" attribute, it works as expected 
Emmet works well in scss file, and in html part of vue file

## Reproducible Case

- Add a scss style block in a vue component. (i tried in veturpack, and same result)

Thank you in advance

**Comment by octref** [comment]
I can repro the bug. Will look into it.

**Comment by Varkal** [comment]
Hi ! Any news on this ?

**Comment by octref** [comment]
Will be fixed together with #430. They have the sam underlying issue.
