### ISSUE TITLE
#region folding support in Vue file

### ISSUE THREAD

**Issue by rgalich** [vuejs/vetur#853]
- [x] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.12.5
- VS Code version: 1.25.1

## Problem

Hello,
I am using the region system on typecipt files:

```
//#region XXX
          my code
//#endregion
```

I want to use the same system in a vue file to organize my code.
How can I do?

Thank you

**Comment by octref** [comment]
This is the folding support for LSP, which hasn't been published yet: https://github.com/Microsoft/language-server-protocol/issues/418

Once it's published & official we can adopt it.

**Comment by ziad-akiki** [comment]
Hello, any updates on this?

**Comment by octref** [comment]
Tracked in #899 which has more info.
