### ISSUE TITLE
Add Option for new Prettier WIP.

### ISSUE THREAD

**Issue by marbuser** [vuejs/vetur#854]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  macOS
- Vetur version: 0.12.5
- VS Code version: 1.25.1

## Feature Request

Is it possible we could have an option (that is disabled by default) for those of us that want to use the new Prettier HTML support that is WIP?
https://github.com/prettier/prettier/pull/4753

It's pretty decent for a WIP, and for a lot of us, even this buggy WIP is better than js-beautify...
Please consider adding it! :)

**Comment by octref** [comment]
It's not published in prettier yet, so I can't adopt it.
