### ISSUE TITLE
If you don't immediatly close an HTML tag and edit elsewhere, it crashes the plugin

### ISSUE THREAD

**Issue by dtruel** [vuejs/vetur#857]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.12.5
- VS Code version: 1.25.1

## Reproducible Case
Thank you very much for an amazing plugin! It makes my life so much easier.

Problem.
If I create a new div, but don't close it like this: `<div` and then edit somewhere else, it crashes all of vetur.  Then when I go put the `>` on the end of the div, it should fix it. But it doesn't. The whole thing remains busted, and it uses 100% of a CPU forever on my computer. I have to restart VS Code to get it back. Even then though, there is still an orphan process using 100% of a CPU.  My guess is that it's trying to validate the entire rest of the file since I forgot to close the tag.  Obviously I should close my tags, but it would be great if the whole extension didn't crash on me when I did!

**Comment by octref** [comment]
Are you sure it's Vetur? Can you try disabling all other extensions and reproducing this issue?

If it still repros, please give me a repository where I can try it myself.

**Comment by dtruel** [comment]
Good Idea. I will try that and see.

**Comment by dtruel** [comment]
@octref You were exactly right. It was the autoclose plugin that was freezing the whole thing.  Thanks a million for your help. You have saved me from so much frustration!

**Comment by octref** [comment]
@dtruel No worries, next time you can try Help -> Open Process Explorer too:

![image](https://user-images.githubusercontent.com/4033249/43604625-19008518-964b-11e8-841a-2751c3a54179.png)
