### ISSUE TITLE
Elements in iteration expect to have 'v-bind:key' directives.

### ISSUE THREAD

**Issue by liangzeng** [vuejs/vetur#858]
![snip20180803_9](https://user-images.githubusercontent.com/8503065/43619705-c2236aa0-9701-11e8-8a5e-250fc29a238a.png)

**Comment by ZSkycat** [comment]
https://cn.vuejs.org/v2/guide/list.html#key

**Comment by octref** [comment]
https://github.com/vuejs/vetur/issues/261

**Comment by gdh5733** [comment]
I got a same problem as you

**Comment by stellaoliveirabertt** [comment]
Pedro, isso não resolveu. (Pelo menos não no meu caso), estou começando a achar que isso é extensão no Visual Code

**Comment by stellaoliveirabertt** [comment]
try

<li class="list-group-item" v-for="type in types"  v-bind:key="type"></li>

**Comment by stellaoliveirabertt** [comment]
try


          `<li class="list-group-item" v-for="type in types"  v-bind:key="type"></li>`

**Comment by NeuroTypicalCure** [comment]
I get the same error as OP if i don't add v-bind:key
But this is what happens if i add v-bind:key :

`<article class="media" v-for="item in feedData.items" :key="item">`
![image](https://user-images.githubusercontent.com/5155910/55681751-4a350d00-592a-11e9-8409-8ac11e68dfb9.png)

Am i not allowed to iterate over an array of objects?

**Comment by PedroAbdalla** [comment]
probaly you have 2 item same value, so try use the index in your loop, like it:

<li v-for="(value, index) in feedData.items"  v-bind:key="index">

https://codepen.io/PedroAbdalla/pen/qwabgE?editors=1111

**Comment by lniuniu** [comment]
you should add  
 :key = "item" 
then you can handle this problem

**Comment by hanifabu** [comment]
plz post a solve example post

**Comment by hanifabu** [comment]
Thanks Vuejs/Vetur  now i face new problem  .can't data separating
please help me.


[image: image.png]

[image: facebook] <https://www.facebook.com/hanif.abu88882>
[image: twitter] <https://twitter.com/AbuHanif88882>
[image: linkedin] <https://www.linkedin.com/in/hanif-abu88882/>
[image: instagram] <https://www.instagram.com/hanif_abu88882/>
Md.Abu Hanif

Student

Dept. of CSE | Prime University

Dhaka-1216.
+8801773088881
hanif.abu88882@gmail.com
312/4-D 1st Colony, Mirpur-1, Dhaka -1216

**Comment by AurioPinto** [comment]
@hanifabu  Hey, I’m not sure what exactly you are trying to do. Can you explain it in a bit more detail please?

**Comment by modavidc** [comment]
> try to add v-bind:key="type" in your li

Thanks. It work for me.

**Comment by AurioPinto** [comment]
<ul>
          <li v-for="task in tasks" :key="task">{{task.text}}</li>
        </ul>

**Comment by zhitomir-oreshenski-mm** [comment]
It is required to have v-bind key directive in order to iterate over list items. Please refer to an example with Todo list below:

<ul>
  <li
    class="list-group-item"
    v-for="todo in todos"
    v-bind:key="todo"
  > {{ todo }}
  </li>
</ul>

**Comment by elliotPopina** [comment]
@AurioPinto thanks you save my day

**Comment by MaBbKhawaja** [comment]
**### This worked for me**
```
<template>
  <div>
    <div 
    v-for="todo in todos" 
    v-bind:key="todo.id"
    >{{todo}}</div>
  </div>
</template>
```

**Comment by tejalhadagali** [comment]
Thank u

**Comment by AimeneNouri** [comment]
it doesn't work for me!!
![Capture](https://user-images.githubusercontent.com/48455549/78458910-f5e37b00-76ac-11ea-98b5-fce263d0e62b.PNG)

Im using this:
![issuesvue](https://user-images.githubusercontent.com/48455549/78458909-f1b75d80-76ac-11ea-89af-f4c2385b4920.PNG)

**Comment by zhnedyalkow** [comment]
Hello, 

It seems you have a typo for :key="i".

Br,
Zhi

**Comment by dineshrampalli** [comment]
<p>This child components of Content.vue are:</p>
    <ul>
      <li v-for="child in childComponents">{{ child }}</li>
    </ul>
    {{ weather_data }}
    <temp-var-chart :tempVar="tempVar"></temp-var-chart>
![Screenshot 2020-04-28 at 3 12 55 PM](https://user-images.githubusercontent.com/64398404/80472758-ca2d7b00-8962-11ea-9ade-6a7944b3ecc3.png)

**Comment by dineshrampalli** [comment]
<li v-for="child in childComponents">{{ child }}</li>

**Comment by dineshrampalli** [comment]
what should i change there in order to solve that problem

**Comment by dineshrampalli** [comment]
[vue/require-v-for-key]
Elements in iteration expect to have 'v-bind:key' directives.

**Comment by dineshrampalli** [comment]
this is the error im getting

**Comment by br-designer** [comment]
@dineshrampalli you need to add a key to your v-for. Vue is just trying to track each node's identity.

You can use:
`<li v-for="child in childComponents" v-bind:key="child>{{ child }}</li>`
or the shortened version:
`<li v-for="child in childComponents" :key="child>{{ child }}</li>`
If your child data has a numerical value like an id, you can also do something like this:
`<li v-for="child in childComponents" :key="child.id>{{ child }}</li>`

Here's some additional information of keys: https://vuejs.org/v2/api/#key

**Comment by iballi2017** [comment]
> v-for="type" in types :key="type" ! ................. It should work all you have to do is add the key element (: key=" whatever name you give to the v-for element ")

Thanks, you've just saved me with your brief explanation in 2020

**Comment by dev-assassin** [comment]
> try
> 
> ```
>       `<li class="list-group-item" v-for="type in types"  v-bind:key="type"></li>`
> ```

it works for me.
But i got another error.
```Avoid using non-primitive value as key, use string/number value instead.```

**Comment by SarwarAhmed** [comment]
```
<template>
  <!-- ✓ GOOD -->
  <div
    v-for="todo in todos"
    :key="todo.id"
  />
  <!-- ✗ BAD -->
  <div v-for="todo in todos"/>
</template>
```
[vue/require-v-for-key](https://eslint.vuejs.org/rules/require-v-for-key.html)

**Comment by alaa-fradi** [comment]
> v-for="type" in types :key="type" ! ................. It should work all you have to do is add the key element (: key=" whatever name you give to the v-for element ")

worked for me

**Comment by ashumsd7** [comment]
what is role of key here to solve this problem

**Comment by ibeeliot** [comment]
v-bind:key="item"

**Comment by mrmezan06** [comment]
> ```
>     <ul>
>       <li v-for="task in tasks" :key="task">{{task.text}}</li>
>     </ul>
> ```

It was worked for me.Thanks

**Comment by NikulGoyani369** [comment]
I also get the same error so I change bellow code.

```
 <select v-model="selectedDegree" size="5">
            <option v-for="(option, index) in options" v-bind:key="option" value="option" @dblclick="openLink(option) ">
          {{ index + 1 }}. {{ option }}</option>
  </select>
```
`I add this line in my code.`   **v-bind:key="option"**

**Comment by shanz007** [comment]
> what is role of key here to solve this problem
      As to the official docs of Vue , it aids in identifying VNodes by virtual DOM algorithm
    ref : https://v2.vuejs.org/v2/api/#key
