### ISSUE TITLE
Syntax highlighting with LanguageClient-neovim?

### ISSUE THREAD

**Issue by anderspitman** [vuejs/vetur#859]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

I have confirmed that neovim is talking to `vls`, but it's not doing syntax highlighting. I'm guessing there's an option I need to configure on one or both sides? I'm new to language server.

**Comment by octref** [comment]
Vetur does its syntax highlighting using TextMate grammars: https://github.com/vuejs/vetur/tree/master/syntaxes, which isn't compatible with Vim.

There is no semantic syntax highlighting yet.

**Comment by anderspitman** [comment]
Ah I see. Thank you
