### ISSUE TITLE
Go to definition not functioning from template in class-based typescript SFCs

### ISSUE THREAD

**Issue by NiloCK** [vuejs/vetur#864]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.12.6
- VS Code version: 1.25.1

## Problem

I'm uncertain whether this issue properly belongs to Vetur or to `vue-class-component`. It's strictly about the editor experience rather than transpiled output, so I thought it might be better here.

Vetur has some inconsistent `go to definition` behaviors which I've not seen documented. My setup here is `vue-cli@3.0.0-rc10`, `vue-class-component@6.0.0`, and `vue-property-decorator@7.0.0`.

Go to definition works on `<user-regristration />` in the following SFC:
``` html
<template>
  <user-registration />
</template>

<script lang="ts">
import Vue from 'vue';
import UserRegistration from './UserRegistration.vue';

export default Vue.extend({
  components: {
    UserRegistration
  }
})
</script>
```
but fails in the class based equivalent (`No definition found for 'user-registration'`):

``` html
<template>
  <user-registration />
</template>

<script lang="ts">
import Vue from 'vue';
import UserRegistration from './UserRegistration.vue';
import Component from 'vue-class-component';

@Component({
  components: {
    UserRegistration
  }
})
export default class TestComponent extends Vue {}
</script>

```

**Comment by s13571** [comment]
+1

**Comment by NiloCK** [comment]
A related question, which I expect is not a bug, because I'm sure I've read something documenting the behavior before. I just can't find any reference to it now.

Why does go to definition fail in the following, with `<UserRegistration />` in place of `<user-registration />`?

``` html
<template>
  <UserRegistration />
</template>

<script lang="ts">
import Vue from 'vue';
import UserRegistration from './UserRegistration.vue';

export default Vue.extend({
  components: {
    UserRegistration
  }
})
</script>
```

The HTML parser's RED_TEXT might be some sort of hint for me...

**Comment by nomadoda** [comment]
YES! I'm having this exact issue as well on macOS 10.13.2. Could someone please confirm whether it's a bug or a missing feature?

**Comment by cecilpeng** [comment]
+1
