### ISSUE TITLE
how to config custom rules for style lint?

### ISSUE THREAD

**Issue by lovetingyuan** [vuejs/vetur#874]
I want to config some rules for scss , how to set the custom config?
I only found: "vetur.validation.style": false , but it just only trun on or off the style linting

**Comment by octref** [comment]
Yeah, the linting rules aren't configurable. I suggest using https://github.com/stylelint/stylelint and https://marketplace.visualstudio.com/items/shinnn.stylelint if you want more customization.

**Comment by octref** [comment]
Also you can look into this project to learn how to setup better linting: https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/master/docs/linting.md

**Comment by lovetingyuan** [comment]
🆗 thank you!
