### ISSUE TITLE
Feature request - Breadcrumbs support

### ISSUE THREAD

**Issue by ffxsam** [vuejs/vetur#875]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  all
- Vetur version: 0.12.6
- VS Code version: 1.26.0

## Feature Request

Add support for new VS Code breadcrumbs feature. When I'm inside a method in a .vue file, VS Code breadcrumbs don't really know where I am:

![image](https://user-images.githubusercontent.com/12532733/44116687-d330aa1e-9fd6-11e8-96a9-146821d373b2.png)

Whereas in a .js or .ts file, there's full symbol awareness:

![image](https://user-images.githubusercontent.com/12532733/44116763-0061db66-9fd7-11e8-84ec-a66e5b5438a6.png)

**Comment by yoyo930021** [comment]
This feature is support.
I will close issue.
If isn't work for you, please open a new issues.
