### ISSUE TITLE
Vetur generates invalid comments in PostCSS

### ISSUE THREAD

**Issue by ky-is** [vuejs/vetur#878]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS 10.13
- Vetur version: 0.12.6
- VS Code version: 1.25.1

## Problem

Single line `// ...` comments are not valid for postcss's default parser. VSCode's "Toggle Line Comment" inside `lang="postcss"` with Vetur should generate `/* ... */` instead.

## Reproducible Case

```html
<style lang="postcss">
// @import '..';
</style>
```

**Comment by robertweiss** [comment]
Platform: macOS 10.12.6
Vetur version: 0.12.6
VS Code version: 1.28.0 Insider

I have the same problem, it also appears in separate *.css files which have language mode PostCSS set. When I switch off Vetur, I get the correct /* */ comments, when switched on, I get the // comment style.

**Comment by octref** [comment]
Sounds good. CSS spec also does not include `//` comment. It's allowed only in SCSS.
