### ISSUE TITLE
how to disable intelligent popup

### ISSUE THREAD

**Issue by hendiko** [vuejs/vetur#880]
- [] I have searched through existing issues
- [] I have read through [docs](https://vuejs.github.io/vetur)
- [] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.12.6
- VS Code version: 1.26.1

## Problem

![image](https://user-images.githubusercontent.com/3890570/44638436-6adad300-a9e9-11e8-8a0b-8fd99f27c5bd.png)

How to get rid of this popup? It pops up every time I press the enter key, and I have to press esc to quit, it's very annoyed.

## Reproducible Case

Just press enter key in `script` tag from .vue file.

**Comment by octref** [comment]
These are snippets provided by other Vue extensions you installed. Try uninstall them.

**Comment by hendiko** [comment]
Thank you very much!! Just as you said, I uninstalled another Vue extension and this annoying disappeared.
