### ISSUE TITLE
vetur will not install - Windows 10 64bit - fresh setup - vs code

### ISSUE THREAD

**Issue by nigel-dewar** [vuejs/vetur#881]
vetur will not install and is stuck on 'installing' when in vs code.

I have tried installing as admin, to no avail.

I have tired intalling using the vsix but this fails because vs code is not recoginized as existing on the machine.

No matter what, I cannot install vetur.

thank you

**Comment by octref** [comment]
> vs code is not recoginized as existing on the machine

What do you mean by that?

Also, open Help -> Toggle Developer Tools, any output there?

**Comment by nigel-dewar** [comment]
Hi Pine. My bad sorry. It installs, it just takes a while. Must be decent sized plugin.

Sorry about that. Please close.

On 29 Aug 2018 3:51 AM, Pine <notifications@github.com> wrote:

vs code is not recoginized as existing on the machine

What do you mean by that?

Also, open Help -> Toggle Developer Tools, any output there?
