### ISSUE TITLE
I think there should be an error message when the '</script>' tag is missing in a single vue file :)

### ISSUE THREAD

**Issue by zhanderson** [vuejs/vetur#882]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  macOS
- Vetur version: 0.12.6
- VS Code version: 1.26.1

## Problem

I deleted my '</script>' tag in a single vue file carelessly, and everything looked alright except a console warning--`[Vue warn]: Unknown custom element: <imported-component-name>.` The problem was not resolved until I found the '</script>' tag lost. But, the thing is, when I delete the '<script>' tag, the file will be like this
![image](https://user-images.githubusercontent.com/8995729/44717785-9a283780-aaf0-11e8-977d-0a88f4538754.png)
when I delete the 'template' tag, the file will be like this
![image](https://user-images.githubusercontent.com/8995729/44717853-d2c81100-aaf0-11e8-8fcf-e7ef578836ab.png)
Can '</script>' be treated like the other tags? THX
## Reproducible Case
Just do what the pictures show.

**Comment by octref** [comment]
No, this is how textmate grammar works.
