### ISSUE TITLE
Strange autocomplete results in lang="stylus" style tag

### ISSUE THREAD

**Issue by rhysburnie** [vuejs/vetur#884]
Hi,

I often get really bizarre autocompletes for stylus.
Its quite frustrating because even when I type the full correct thing and hit enter it autocompletes to the wrong thing.
The only way I can get to new line is type correct thing then hit esc then enter.

One example that really stands out as WTF? is the following:

![image](https://user-images.githubusercontent.com/245933/44758646-e87f1a00-ab74-11e8-804f-8f4366e8380e.png)

**Comment by octref** [comment]
This is what I see:

![image](https://user-images.githubusercontent.com/4033249/44816901-7e786c00-ab98-11e8-84a6-1aa10820d494.png)

Please provide Repro Steps and required information. Otherwise I can't help. https://github.com/vuejs/vetur/issues/new
