### ISSUE TITLE
SCSS code linted as CSS

### ISSUE THREAD

**Issue by xbill82** [vuejs/vetur#886]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: 0.12.6
- VS Code version: 1.26.1

## Problem
On _some files_ (could not determine why) the style linting fails. Style tags conaining scss rules are linted as css ones. This false negatives are raised.

![selection_124](https://user-images.githubusercontent.com/5023426/44781877-c6da5e80-ab85-11e8-91df-31e268c2d1f5.png)

## Reproducible Case

Can't really say how to achieve this. I get this "randomly" on Vue components that use SCSS in style tags.

**Comment by octref** [comment]
`style="scss"`, not `type`.

**Comment by xbill82** [comment]
Thanks!
