### ISSUE TITLE
code highlight error

### ISSUE THREAD

**Issue by yoyo837** [vuejs/vetur#888]
- [x] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.12.6
- VS Code version: 1.16.1

## Problem

![image](https://user-images.githubusercontent.com/6134547/44841707-94f4f500-ac76-11e8-84f5-90a77c860543.png)

![image](https://user-images.githubusercontent.com/6134547/44842005-4a27ad00-ac77-11e8-88e5-b511246340e5.png)

Please don't care about the code error, it is related to eslint config:
![image](https://user-images.githubusercontent.com/6134547/44841757-adfda600-ac76-11e8-9d3d-42807d128cb6.png)

**Comment by octref** [comment]
This is a bug with VS Code and it's already fixed. You can download https://code.visualstudio.com/insiders/ or wait for next release.

**Comment by yoyo837** [comment]
Thanks for your reply.
