### ISSUE TITLE
Download of vetur extension fails due to file corruption detected by anti-virus-scanner

### ISSUE THREAD

**Issue by mapl** [vuejs/vetur#889]
Please remove or upgrade package

**affected file "cb-never-called-1.0.1.tgz"**

Related to
https://github.com/Microsoft/vscode-go/issues/1871
npm/node-tar#150

**Comment by octref** [comment]
@mapl Is this still an issue?

**Comment by octref** [comment]
Feel free to reopen if this still happens.
