### ISSUE TITLE
shows error on v-bind:value on select options

### ISSUE THREAD

**Issue by yogeshgalav** [vuejs/vetur#891]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version:
- VS Code version:

## Problem
![screen shot 1397-06-09 at 5 11 27 pm](https://user-images.githubusercontent.com/26108890/44910480-000afe00-ad41-11e8-9b7d-5b156976888d.png)

**Comment by octref** [comment]
https://vuejs.github.io/vetur/linting-error.html
