### ISSUE TITLE
Code formatting: VSCode vs Vetur vs ESLint [question]

### ISSUE THREAD

**Issue by rowild** [vuejs/vetur#892]
- [x ] I have searched through existing issues
- [x ] I have read through [docs](https://vuejs.github.io/vetur)
- [x ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:macOS 10.13.6
- Vetur version: 0.12.16
- VS Code version: 1.26.1

## Problem

This is a question! (I did look for forums, but didn't find any devoted ones; please direct me to one, if this is the wrong place to ask question. Thank you!)

I would like to bring Vetur and VS Code to listen to the same settings. Specifically, it concerns formatting of code, that I would like to keep in one line, like this:

```js
import { TweenMax, TimelineMax } from 'gsap'
```
ESLint is ok with that formatting and does not complain. But when I run my Vetur keyboard shortcut to format a whole Vue document, Vetur puts the code in question on several lines again, like this:

```js
import {
  Tweenmax,
  TimelineMax
} from 'gsap'
```

I assume that ESLint is responsible for that, but I couldn't find the configuration that is responsible for that feature, yet. I tried:

```js
{
  rules: {
      [...]
    "object-property-newline": [
      "warn", {
        "allowAllPropertiesOnSameLine": true
      }
    ],
    [...],
    "vue/max-attributes-per-line": [
      1,  {
        "singleline": 4,
        "multiline": {
          "max": 3,
          "allowFirstLine": true
        }
      }
    ],
  }
}
```
...but I actually think they are responsible or the attribute handling on html tags...

Does anybody have any idea, what I have to do to keep my imports on one line? (Any, for that matter, other things, that are on one line, too?)

**Comment by rowild** [comment]
Anybody?

**Comment by octref** [comment]
@rowild Sorry for the late response. We are using prettier (https://prettier.io/) for formatting the JS section. What you are seeing is the expected behavior of prettier. You can configure when prettier wraps your long line into multiline statements though, see: https://prettier.io/docs/en/options.html#print-width

**Comment by octref** [comment]
Also see https://vuejs.github.io/vetur/formatting.html#formatters. You can simply try setting `prettier.printWidth` in VS Code setting and Vetur should pick it up.

**Comment by rowild** [comment]
Thanks for your answers! I do know both sourced, as a matter of fact: I read the whole prettier documentation; I just wonder, if I understood it. 
In my .prettierrc I have printWidth set to 240 (which is sooooo against the recommendation), and nevertheless the arguments are wrapped. Now I have prettier disabled and I would expect eslint to complain in some way. But nothing, everything quite. Nevertheless: onSave the arguments are wrapped again.
Is there anywhere w resource that digs really deep into this code formatting problem? To me it seems to be a really confusing and messy topic...
