### ISSUE TITLE
js-beautify-html bug

### ISSUE THREAD

**Issue by sjoooo123** [vuejs/vetur#893]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version:v0.12.6
- VS Code version:1.26.1

## Problem

![1](https://user-images.githubusercontent.com/22810581/44955611-a3e2de00-aee8-11e8-8180-52c6c0accc55.jpg)

**Comment by octref** [comment]
https://vuejs.github.io/vetur/formatting.html#js-beautify-html-deprecated

> Alternative html formatter. Deprecated, turned off by default and will be removed soon. js-beautify is not actively maintained and has many long-standing bugs. Use at your own risk.
