### ISSUE TITLE
Using VLS with Eclipse CHE on Docker

### ISSUE THREAD

**Issue by clacetera** [vuejs/vetur#894]
## Info

- Platform: Eclise Che v.6.10
- Vls Server Code version: vue-language-server@0.0.33

## Problem

I'm trying to use vls with eclipse che LS-Sidecars but seems not work

## Reproducible Case

Following instruction on https://www.eclipse.org/che/docs/language-servers.html

changing docker images as follow:

------------------%<---------------------------------------------------------
FROM eclipse/node

RUN sudo apt-get install socat -y && \
    sudo npm install -g vue-language-server

CMD socat TCP4-LISTEN:4417,reuseaddr,fork EXEC:"vls --stdio"
------------------%<---------------------------------------------------------

and in config of workspace:

-----------------%<----------------------------------------------------------
 "servers": {
            "ls": {
              "attributes": {
                "languageRegexes": "[ {\"languageId\":\"javascript\", \"regex\":\".*\\\\.vue$\"}]",
                "internal": "true",
                "id": "vue-ls",
                "type": "ls"
              },
              "protocol": "tcp",
              "port": "4417"
            }
-----------------%<----------------------------------------------------------

After lunching workspace and open .vue file

On Dev Machine log says:
2018-09-02 21:22:19,730[rverInitializer]  [INFO ] [.a.l.LanguageServerInitializer 113]  - Started language servers initialization, file path '/test/test.vue'
2018-09-02 21:22:19,732[rverInitializer]  [INFO ] [.a.l.LanguageServerInitializer 129]  - Finished language servers initialization, file path '/test/test.vue'

On LS-Machine sproofing with ngrep

user@4f7a3584ed0a:/projects$ sudo ngrep -d eth1 port 4417
interface: eth1 (172.26.0.0/255.255.0.0)
filter: (ip or ip6) and ( port 4417 )
#
T 172.26.0.3:45414 -> 172.26.0.2:4417 [AP]
  Content-Length: 3008....
##
T 172.26.0.3:45414 -> 172.26.0.2:4417 [A]
  {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///projects/test/test.vue","languageId":"javascript","version":0,"text":"\u003ctempla
  te\u003e\r\n  \u003cv-ons-navigator swipeable swipe-target-width\u003d\"50px\"\r\n    :page-stack\u003d\"pageStack\"\r\n    :pop-page\u003d\"storePop\"\r\n    :options\u003
  d\"options\"\r\n    @postpush\u003d\"showPopTip\"\r\n    :class\u003d\"{ \u0027border-radius\u0027: borderRadius }\"\r\n  \u003e\u003c/v-ons-navigator\u003e\r\n\u003c/templ
  ate\u003e\r\n\r\n\u003cscript\u003e\r\nimport AppSplitter from \u0027./AppSplitter.vue\u0027;\r\n\r\nexport default {\r\n  beforeCreate() {\r\n    this.$store.commit(\u0027
  navigator/push\u0027, AppSplitter);\r\n  },\r\n  data() {\r\n    return {\r\n      shutUp: this.md\r\n    }\r\n  },\r\n  computed: {\r\n    pageStack() {\r\n      return th
  is.$store.state.navigator.stack;\r\n    },\r\n    options() {\r\n      return this.$store.state.navigator.options;\r\n    },\r\n    borderRadius() {\r\n      return new URL
  (window.location).searchParams.get(\u0027borderradius\u0027) !\u003d\u003d null;\r\n    }\r\n  },\r\n  methods: {\r\n    storePop() {\r\n      this.$store.commit(\u0027navi
  gator/pop\u0027);\r\n    },\r\n    showPopTip() {\r\n      !this.shutUp \u0026\u0026 this.$ons.notification.toast({\r\n        message: \u0027Try swipe-to-pop from left sid
  e!\u0027,\r\n        buttonLabel: \u0027Shut up!\u0027,\r\n        timeout: 2000\r\n      }).then(i \u003d\u003e this.shutUp \u003d i \u003d\u003d\u003d 0);\r\n    }\r\n  }
  \r\n};\r\n\u003c/script\u003e"},"text":"\u003ctemplate\u003e\r\n  \u003cv-ons-navigator swipeable swipe-target-width\u003d\"50px\"\r\n    :page-stack\u003d\"pageStack\"\r\n
      :pop-page\u003d\"storePop\"\r\n    :options\u003d\"options\"\r\n    @postpush\u003d\"showPopTip\"\r\n    :class\u003d\"{ \u0027border-radius\u0027: borderRadius }\"\r\n
    \u003e\u003c/v-ons-navigator\u003e\r\n\u003c/template\u003e\r\n\r\n\u003cscript\u003e\r\nimport AppSplitter from \u0027./AppSplitter.vue\u0027;\r\n\r\nexport default {\r\
  n  beforeCreate() {\r\n    this.$store.commit(\u0027navigator/push\u0027, AppSplitter);\r\n  },\r\n  data() {\r\n    return {\r\n      shutUp: this.md\r\n    }\r\n  },\r\n
   computed: {\r\n    pageStack() {\r\n      return this.$store.state.navigator.stack;\r\n    },\r\n    options() {\r\n      return this.$store.state.navigator.options;\r\n
    },\r\n    borderRadius() {\r\n      return new URL(window.location).searchParams.get(\u0027borderradius\u0027) !\u003d\u003d null;\r\n    }\r\n  },\r\n  methods: {\r\n
   storePop() {\r\n      this.$store.commit(\u0027navigator/pop\u0027);\r\n    },\r\n    showPopTip() {\r\n      !this.shutUp \u0026\u0026 this.$ons.notification.toast({\r\n
         message: \u0027Try swipe-to-pop from left side!\u0027,\r\n        buttonLabel: \u0027Shut up!\u0027,\r\n        timeout: 2000\r\n      })
##
T 172.26.0.3:45414 -> 172.26.0.2:4417 [AP]
  .then(i \u003d\u003e this.shutUp \u003d i \u003d\u003d\u003d 0);\r\n    }\r\n  }\r\n};\r\n\u003c/script\u003e"}}
##
T 172.26.0.2:4417 -> 172.26.0.3:45414 [AP]
  Content-Length: 127....{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///projects/test/test.vue","diagnostics":[]}}

**Comment by octref** [comment]
It's better to open an issue with Eclipse Che. I don't know much about it and how it handles language servers.

**Comment by clacetera** [comment]
Ok, i move this thread on Eclipse Che.

Pls, let me only confirm that it's possible to start with option --stdio witch accept stream from SOCAT, because i have understand that eclipse che is only interfacing by tcp scoket to the server language.

Regards.

**Comment by octref** [comment]
> but not for text highlight

Yes, they come from textmate grammar. See here: https://github.com/vuejs/vetur/tree/master/syntaxes and https://code.visualstudio.com/docs/extensionAPI/language-support#_syntax-highlighting

**Comment by clacetera** [comment]
I Octref, i'm not able to undestend how using your suggestion.

Can you give me more info ?

Actually I start a sidecar che language server launching

CMD socat TCP4-LISTEN:4417,reuseaddr,fork EXEC:"node /opt/vetur/extension/server/dist/vueServerMain.js --stdio"

Eclipse Che client connect to Server, and work but probably LS didn't not recognize grammar at startup,

**Comment by octref** [comment]
You should ask Eclipse Che, not me.
