### ISSUE TITLE
Auto import problem with TypeScript version

### ISSUE THREAD

**Issue by csicky** [vuejs/vetur#895]
- [ *] I have searched through existing issues
- [ *] I have read through [docs](https://vuejs.github.io/vetur)
- [ *] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win 10
- Vetur version: 0.12.6
- VS Code version: 1.26.1

## Problem

I have been redirected to open an issue for the vue extension, which in my case is Vetur. Please read this issue I opened for VS Code and check if it's actually a Vetur problem how it interacts with TypeScript or not.

https://github.com/Microsoft/vscode/issues/57822

Thank you for your time and for the great work enabling Vue development in VS Code.

**Comment by octref** [comment]
This is an issue with TS, so nothing I can do from Vetur side. I explained here: https://github.com/Microsoft/vscode/issues/57822#issuecomment-418814424.
