### ISSUE TITLE
HTML formatter

### ISSUE THREAD

**Issue by qdechochen** [vuejs/vetur#896]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win/macOS/Linux
- Vetur version: 0.12.6
- VS Code version: 1.27.1

## Problem

Since jsBeautify seems to been live again, and reshape is still not ready. Any plans to be back to jsBeautify?

**Comment by maeldur** [comment]
i believe @octref is currently working on integrating prettyHTML see https://github.com/vuejs/vetur/issues/491#issuecomment-414072754

**Comment by rowild** [comment]
Since VScode just updated its jsBeautify, it would probably make great sense to use it in Vetur, too...

**Comment by octref** [comment]
#833 and #491.
