### ISSUE TITLE
Completion errors in other clients [vue-language-server] [regression]

### ISSUE THREAD

**Issue by pearofducks** [vuejs/vetur#897]
## Note

This is a regression starting at version 0.0.31. Version 0.0.30 works and will provide completions where 0.0.31 fails with the error below.

## Issue boilerplate

- [ x ] I have searched through existing issues
- [ x ] I have read through [docs](https://vuejs.github.io/vetur)
- [ x ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: MacOS
- Vetur version: n/a
- VS Code version: n/a
- vue-language-server version: "0.0.33"

## Problem

`{'message': "Request textDocument/completion failed with message: Cannot read property 'completion' of undefined", 'code': -32603}`

## Reproducible Case

- Set up LSP support in Neovim or Sublime Text [1]
- Attempt to trigger completion by typing `<` on an empty Vue document (with the vue-language-server started and attached).
- Get error above and no completions instead of scaffolding results as in VSCode. Additionally no template results are provided either if `<template` is typed out.

[1] - I've reproduced the error in both clients to ensure the root cause was the language server and not something in an individual implementation.

Neovim packages used:
```
Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'
Plug 'autozimu/LanguageClient-neovim'
```

Sublime packages used:
```
LSP - v0.7.1
Vue Syntax Highlight - v3.3.1
```

**Comment by pearofducks** [comment]
(Sorry for changing title a lot, wanted to find a suitable title for what I was finding would reproduce) :)

**Comment by trev-dev** [comment]
vue-language-server has also stopped working in OniVim
![vls](https://user-images.githubusercontent.com/28788713/45328743-13248780-b512-11e8-8480-d0921a990c1d.png)

It seems as though it's crashing when requests are sent.

**Comment by trev-dev** [comment]
## Update
My _particular_ vls issue came from ZSH being my default shell. It wasn't working when I fired up OniVim from the application launcher, but did work when I launched from my shell. 

I switched back to bash and everything worked as intended. 

It's safe to say that my contribution to this issue is just a configuration issue on my end.

**Comment by pearofducks** [comment]
The above regression is not affected by default shell, whether zsh or bash is specified the original bug is reproducible.

**Comment by pearofducks** [comment]
Closing in favor of another issue with better data.
