### ISSUE TITLE
Make `#region` work on `<script>` section

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#899]
From https://github.com/Microsoft/vscode/issues/39939. There is no folding regions being returned back from `//#region`, as VS Code does for TypeScript.

![image](https://user-images.githubusercontent.com/4033249/45328746-1586e180-b512-11e8-9110-b7adb53e3da0.png)

This is the `foldingRange` support for LSP: https://microsoft.github.io/language-server-protocol/specification#textDocument_foldingRange.

**Comment by erisman20** [comment]
Just wanted to add that they do not work in the template or style sections either.

![image](https://user-images.githubusercontent.com/25164706/45367654-609f0400-b5a7-11e8-8c0d-83a19967c2fa.png)

**Comment by Hammster** [comment]
I'm really missing this feature, i tried playing around with the following values: https://github.com/vuejs/vetur/blob/2cf32f2b6f345a215e184a7ec9b028419ec803ee/languages/vue-language-configuration.json#L33-L38

And it actually works by providing the following config:

```js
  "folding": {
    "markers": {
      "start": "(^<(template|style|script)[^>]*>\\b|^\\s*//\\s*#?region\\b)",
      "end": "(^<\/(template|style|script)[^>]*>\\b|^\\s*//\\s*#?endregion\\b)"
    }
  }
```

But there are several issues, the folding is only available afer reloading the window, also the indention seams to be off in some of my components which does not allow me to have the content of the region to be on the same or lower level then the region.

**Comment by octref** [comment]
@Hammster VS Code now has 3 types of folding

- Indentation based folding. This has been there forever.
- Folding Markers. They are optional, statically declared, and not really reliable.
- Intelligent folding that the Language Server responds, which we plan to do in Vetur. LSP Spec is here: https://microsoft.github.io/language-server-protocol/specification#textDocument_foldingRange

**Comment by ksnyde** [comment]
@octref the **region** folding is the only way a user can explicitly state folding blocks. I'm not sure if that's what you mean by "folding markers" but if so what is unreliable about them?

**Comment by mika76** [comment]
Regions are awesome (especially in long html templates - admit it they happen 😉) and I can't wait for this - especially since this will also allow #1294 which is slightly more irritating

@octref any idea when supporting intelligent folding is going to be implemented?

**Comment by momink** [comment]
In VScode following is not working in .vue files but works in .js files.
//#region ccc
//#endregion

**Comment by phifa** [comment]
This is a great feature addition. Already being worked on? Can we help or test?

**Comment by leosdad** [comment]
Much needed. Any news on that?

**Comment by jtsom** [comment]
Just realized that regions are not available in .vue files. Any news/movement on this? Would be SUPER helpful.

**Comment by phiter-monetizze** [comment]
Hey that's an important feature. Is it being implemented?

**Comment by Creestoph** [comment]
+1

**Comment by lysla** [comment]
+1

**Comment by sidquisaad** [comment]
+1 THis is actually super important especially in large components.

**Comment by sebsobseb** [comment]
+1 would love to see this

**Comment by klihonga11** [comment]
+1 This is definitely needed. Any update?

**Comment by lala-lee-jobs** [comment]
+1 This is useful

**Comment by tonyl** [comment]
I know I am just another request, but it will come in handy for some code bases.

**Comment by octref** [comment]
The issue is open so there's no update yet. I'll try to make time to implement it.
Meanwhile you can sponsor my OSS development https://github.com/sponsors/octref or add a bounty for this issue: https://issuehunt.io/r/vuejs/vetur

**Comment by mika76** [comment]
@octref that's great news - I think #1294 is related to this (collapsing of tags) in case you're working on this.

**Comment by capar** [comment]
@mika76 

Hi all, sorry, a beginner question here: Is this normal that the following does not allow me to collapse the lines 39-43? What should I do instead? Thank you. (VS Code with Vetur extension enabled)

![image](https://user-images.githubusercontent.com/39604387/98093559-2553a380-1e99-11eb-89d8-6122f814d238.png)

**Comment by yoyo930021** [comment]
> @mika76
> 
> Hi all, sorry, a beginner question here: Is this normal that the following does not allow me to collapse the lines 39-43? What should I do instead? Thank you. (VS Code with Vetur extension enabled)
> 
> ![image](https://user-images.githubusercontent.com/39604387/98093559-2553a380-1e99-11eb-89d8-6122f814d238.png)

Is this code in script part?

**Comment by mika76** [comment]
@capar it seems it only works when it has a name, so...

```js
// #region some name
someCode();
// #endregion 
```

**Comment by edudins** [comment]
Same here, .vue files doesn't work. And I was so excited. :D

**Comment by Owen3H** [comment]
Came across this issue and realised I had `editor.foldingStrategy` to `indentation`.
Make sure it is set to `auto` as that's what fixed it for me.

**Comment by edudins** [comment]
> Came across this issue and realised I had `editor.foldingStrategy` to `indentation`.
> Make sure it is set to `auto` as that's what fixed it for me.

Doesn't fix it for me. I already have folding strategy at auto.

**Comment by LiMao00** [comment]
I want it
