### ISSUE TITLE
Error: Cannot find module 'vscode-languageserver-protocol/lib/protocol.colorProvider.proposed'

### ISSUE THREAD

**Issue by chemzqm** [vuejs/vetur#901]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  Mac
- Vetur version: `^0.0.33`
- VS Code version: none

## Problem

The server module using `vscode-languageserver-protocol` at https://github.com/vuejs/vetur/blob/73a0854b9eba3311951546a1e82a6832b523acbb/server/src/services/vls.ts#L26, but it doesn't have specified dependency of `vscode-languageserver-protocol` in package.json and the latest version of `vscode-languageserver-protocol` doesn't have file `protocol.colorProvider.proposed'`.

**Comment by octref** [comment]
What's your locally installed version of `vscode-languageserver-protocol` at `/server`? You can run `yarn list vscode-languageserver-protocol`.

**Comment by chemzqm** [comment]
The latest version: 3.13.0

**Comment by octref** [comment]
This should be gone in 0.0.34. Sorry for the trouble.
The code was leftover from using LSP 3.0 when Color support was not available. I upgraded to LSP 5 and removed the code.
