### ISSUE TITLE
Not use jsconfig.json in subfolder

### ISSUE THREAD

**Issue by zhuscat** [vuejs/vetur#904]
## Info

- Platform: macOS
- Vetur version: v0.12.6
- VS Code version: 1.27.2

## Problem

Here is the structure of my project:

```
root
├── h5
│   └── jsconfig.json
└── pc
    └── jsconfig.json
```

And I specify some path aliases in `jsconfig.json`.

The`.js` files in **h5** and **pc** can have IntelliSense, but `.vue` files seems not.

**Comment by octref** [comment]
Tracked in https://github.com/vuejs/vetur/issues/423. Currently you have to open h5 / pc as two windows.
