### ISSUE TITLE
vetur breaks the html code

### ISSUE THREAD

**Issue by x-foby** [vuejs/vetur#910]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win 10
- Vetur version: 0.12.7
- VS Code version: 1.27.2

## Problem

When performing HTML-code format, inserts incorrect closing tag:
![vetur](https://user-images.githubusercontent.com/34175644/45998204-ccef2c80-c0aa-11e8-812a-e53dfbe9d48c.gif)

## Reproducible Case

1. Set `vetur.format.defaultFormatter.html` as `js-beautify-html` in your settings.json
2. Open any *.vue file contain `<template>` tag
3. Run Format Document in Command Palette (or press Ctrl+Shift+I)

**Comment by octref** [comment]
I cannot reproduce this. What's your js-beautify-html setting, if any?

![format](https://user-images.githubusercontent.com/4033249/46042806-29fada80-c0cb-11e8-8245-85330eb23d07.gif)

**Comment by x-foby** [comment]
@octref the problem was that one of the settings (`end_with_newline`) was incorrectly written (in the CLI-style - `end-with-newline`).
It's strange that to fix the problem I had to first set it to `false` (removing and fixing did not help) and only then correct the typo.
![vetur](https://user-images.githubusercontent.com/34175644/46061491-7d266900-c16f-11e8-9e43-4e0962bad4e4.gif)
The problem is resolved. Thnks!
