### ISSUE TITLE
<img />导致后面的标签不对齐

### ISSUE THREAD

**Issue by rushairer** [vuejs/vetur#911]
- [ √ ] I have searched through existing issues
- [ √ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ √ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.12.7
- VS Code version:  1.27.2 (1.27.2)

## Problem

.vue文件中的html标签不对齐了。

## Reproducible Case

当使用了<img /> 之后，就会导致后面的标签不对齐。

**Comment by octref** [comment]
Please use English and provide reproducible case. Otherwise I can't help.
