### ISSUE TITLE
Autocomplete not work with update 0.12.7

### ISSUE THREAD

**Issue by KytoSai** [vuejs/vetur#914]
- [x ] I have searched through existing issues
- [x ] I have read through [docs](https://vuejs.github.io/vetur)
- [ x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: MacOS Mojave
- Vetur version: 0.12.7
- VS Code version: 1.27.2

## Problem

Vue output langugague serve
```
Vetur initialized
``

I can autocomplete in .vue file with update 0.12.7. With 0.12.1 before every normal

Vetur is package very bad :( ! Issue everywhere

**Comment by chieh301** [comment]
+1

**Comment by heflyaway** [comment]
0.12.6 is ok

**Comment by francoisromain** [comment]
removing node_modules and clearing npm cache fixed it for me.

**Comment by KytoSai** [comment]
> removing node_modules and clearing npm cache fixed it for me.

I try, but it don't work.

I installed v0.12.6, it work ok ! Update 0.12.7 is very bad ... :(

**Comment by preadfish** [comment]
For me the same, have to Install the 0.12.6 VSIX and disable automatic updates to make it work as expected.

**Comment by octref** [comment]
@KytoSai Since you never mention any details of what goes wrong, I can't help much.
