### ISSUE TITLE
js-beautify-html  格式化错位

### ISSUE THREAD

**Issue by MrHzq** [vuejs/vetur#915]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  Win
- Vetur version: 0.12.7 | 2018-09-24
- VS Code version: 1.27.2

## Problem

今天我更新了vetur
然后使用 js-beautify-html后，格式化得到的结果
![image](https://user-images.githubusercontent.com/24823464/46065103-cf817d00-c1a3-11e8-9d3d-9dfee2d23d19.png)<br>
template标签里面的格式化错位了
当代码行数多了，错位更严重，影响开发

**Comment by Cheesenx** [comment]
我也发现了这个问题。
今天更新到Vetur version: 0.12.7，
只要是input、img等无需闭合的标签，都会格式化错位。希望解决！

**Comment by octref** [comment]
https://vuejs.github.io/vetur/formatting.html#js-beautify-html-deprecated

> Alternative html formatter. Deprecated, turned off by default and will be removed soon. js-beautify is not actively maintained and has many long-standing bugs. Use at your own risk.

You should open issues for js-beautify. Thanks.

**Comment by shangxinbo** [comment]
I got the same issue. I wonder if js-beautify-html is deprecated, what can i use

**Comment by octref** [comment]
Actually for people in this thread, see https://github.com/vuejs/vetur/issues/921#issuecomment-426710032

You can set the below setting until the upcoming release, when I'll make it the default setting.

```
    "vetur.format.defaultFormatterOptions": {
      "js-beautify-html": {
        "unformatted": []
      }
    }
```

**Comment by omnjpa27516** [comment]
@octref Thank you so much.

**Comment by MrLeihe** [comment]
@octref Thanks！This has bothered me for a long time.
