### ISSUE TITLE
offline install (through visx) faild, need intenet 

### ISSUE THREAD

**Issue by zhohon** [vuejs/vetur#919]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  Win 
- Vetur version: 0.12.6
- VS Code version: 1.7.1

## Problem
offline install (through visx) faild, need intenet 

ApplicationInsights:Sender [ { Error: connect EACCES 168.63.242.221:80
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
    code: 'EACCES',
    errno: 'EACCES',
    syscall: 'connect',
    address: '168.63.242.221',
    port: 80 } ]
Extension 'vetur-0.12.6.vsix' was successfully installed!

**Comment by octref** [comment]
I can confirm this error, but it's a VS Code issue: https://github.com/Microsoft/vscode/issues/59755.
