### ISSUE TITLE
js-beautify-html formatting goes wrong

### ISSUE THREAD

**Issue by focussing** [vuejs/vetur#921]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.12.7
- VS Code version: 1.27.2

Installed vscode, vetur and selected js-beautify-html as html formatter in settings.
Yes js-beautify-html is deprecated, but still it is there...
The code is entered through emmet, so that's according the vetur's standard.
Remove all formatting via Cmd-A and then Shift-Tab until all lines are left aligned.
Then format document.

## Problem
Format the following code breaks gives bad result.
Seems like it has to do with tags like img, br, input?
If i use `/>` endtags it has influence on the disruption.
Also the deeper the nesting, the more disruption of the formatted structure.

Anyone an idea how to fix it?
Or what formatter should one use? 
A lot is written about this but to find the best solution or latest developments is hard.

First example:
```
<template>
    <div>
        <div>
            <div>
                <div>
                    <div>

                    </div>
                    <input type="text">
                </div>
                </div>
            </div>
        </div>
</template>

<script>
export default {};
</script>

<style>
</style>
```

Example #1: similar behaviour occurs when using the following code.
```
<template>
    <div>
        <div>
            <img src="test1.jpg" alt="altext">
            <p>one</p>
            <p>two</p>
        </div>
        <div>
            <img src="test2.jpg" alt="altext">
            <p>one</p>
            <p>two</p>
            <input type="text">
            <br>
</div>
        </div>
</template>

<script>
export default {};
</script>

<style>
</style>
```

**Comment by focussing** [comment]
The weird thing is when I past this code into [https://beautifier.io/](https://beautifier.io/) it formats okay....

```
<template>
<div>
<div>
<img src="test.jpg" alt="attext">
<p>one</p>
<p>two</p>
</div>

<div>
<img src="test.jpg" alt="attext">
<p>one</p>
<p>two</p>
<input type="text">
<br>
</div>
</div>
</template>

<script>
export default {};
</script>

<style>
</style>
```

**Comment by octref** [comment]
Does this setting work for you?

```
    "vetur.format.defaultFormatterOptions": {
      "js-beautify-html": {
        "unformatted": []
      }
    }
```

We used to set `unformatted` for these tags:

```
  unformatted: [
    'area',
    'base',
    'br',
    'col',
    'embed',
    'hr',
    'img',
    'input',
    'keygen',
    'link',
    'menuitem',
    'meta',
    'param',
    'source',
    'track',
    'wbr'
  ],
```

But it seems js-beautify updated its behavior. So it goes from "empty array for unformatted never gets aligned correctly" to "empty array for unformatted works now"...

**Comment by focussing** [comment]
YES! you are the best :)

Is there a place in the documentation where this is noted?

**Comment by octref** [comment]
This section talks about overriding js-beautify options and points to the source code: https://vuejs.github.io/vetur/formatting.html#js-beautify-html-deprecated.

**Comment by focussing** [comment]
thanks!
