### ISSUE TITLE
Surface PrettyHTML formatting warnings

### ISSUE THREAD

**Issue by maeldur** [vuejs/vetur#932]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: all
- Vetur version: 0.13
- VS Code version: 1.28.1

## Problem
see https://github.com/Prettyhtml/prettyhtml/issues/44 for maintainer's response

Improperly close a <textarea> tag by doing <textarea /> or <textarea> without a close tag, add markup following this tag.  Then perform a format document operation.  you'll notice either two behaviors: the <textarea> tag will get closed as <textarea></textarea>, or the <textarea /> tag will get changed to <textarea/>, and all following markup through the end of <template> will be removed.

![oct-18-2018 11-53-48](https://user-images.githubusercontent.com/437016/47177266-cda36900-d2cc-11e8-8865-8e56621a7812.gif)

## Reproducible Case

https://github.com/maeldur/veturpack - try formatting components/ Counter.vue and Counter2.vue 

Short of modifying prettyHTML to handle improperly closed <textarea> elements in the same way the vue handles them, we probably want to surface any warnings available and display them if they were generated.

**Comment by StarpTech** [comment]
This issue was addressed in 0.3.0. Parsing errors are thrown with all required information to display an exact message to the user. The public has been changed a bit. For all infos see: https://github.com/Prettyhtml/prettyhtml/releases/tag/v0.3.0

**Comment by octref** [comment]
I have upgraded it to prettyhtml 0.3.3. Still need to surface the warnings, which is in #937.

**Comment by StarpTech** [comment]
@maeldur @octref good news! In the latest version, it's allowed to self-close none-void elements. https://github.com/Prettyhtml/prettyhtml/releases I recommend updating.

**Comment by alexbudure** [comment]
@octref I think this is a pretty important issue. How can we use the latest version of prettyhtml? Will you be making a new release for vetur?

**Comment by octref** [comment]
@alexbudure https://github.com/vuejs/vetur/issues/971

**Comment by octref** [comment]
Try 0.14.0.
