### ISSUE TITLE
Inline svg kill vscode

### ISSUE THREAD

**Issue by dimensi** [vuejs/vetur#935]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOs mojave
- Vetur version: 0.13
- VS Code version: 1.28.2

## Problem
Inline svg kill vscode.
Not have any message in output from vue lang server

## Reproducible Case

1. Enable eslint autofix
1.1 Add rule for sorting attributes 
2. Enable html format by prettyhtml
3. Enable fix on save
4. Add in vue template inline svg. Add some attribute and let eslint fix it
5. ...
6. Vscode lost suggests, indent by tabs and other features. Need restart vscode for restore this features.

I try film it
https://drive.google.com/file/d/1ZNSdNbVmuvjYjgR1NAZKkg3Vzrso5M7X/view?usp=sharing

**Comment by Uninen** [comment]
Hi!

I'm helping with triaging Vetur issues. If you still experience this issue, please open a new issue with a proper repro case, thanks!

**Comment by dertrockx** [comment]
Hello! Was this issue solved? I'm having the same issue. Thanks!

**Comment by Uninen** [comment]
Please provide clear steps for reproducing the problem. 

Here are the docs from our bug ticket template:

  - Generate a project from https://github.com/octref/veturpack/generate
  - Make a minimal code change to demonstrate your problem
  - Push your commit
  - Include link to your changes in the issue
