### ISSUE TITLE
Old autocomplete in stylus block

### ISSUE THREAD

**Issue by dimensi** [vuejs/vetur#936]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macos mojave
- Vetur version: 0.13
- VS Code version: 1.28.2

## Problem
Suggests in stylus file and stylus block are different.
Stylus file
![image](https://user-images.githubusercontent.com/11390039/47261615-8d660580-d4db-11e8-9b96-199a3065c5c0.png)
![image](https://user-images.githubusercontent.com/11390039/47261617-96ef6d80-d4db-11e8-83e4-adfc044aa902.png)
And stylus block
![image](https://user-images.githubusercontent.com/11390039/47261622-b4bcd280-d4db-11e8-958a-7e9d27cbb1b3.png)
![image](https://user-images.githubusercontent.com/11390039/47261623-c0a89480-d4db-11e8-9433-474ae58f1566.png)

## Reproducible Case
Create new stylus file, try get suggests for grid property
Create new vue file, create stylus block and try get suggests for grid property

**Comment by dimensi** [comment]
Fixed in https://github.com/vuejs/vetur/releases/tag/v0.14.0

**Comment by octref** [comment]
Yep, thanks for keep the issue list tidy.
