### ISSUE TITLE
formating can generate invalid template if single quote with nested double quote used in attribute value

### ISSUE THREAD

**Issue by maeldur** [vuejs/vetur#938]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: all
- Vetur version: 0.13 
- VS Code version: 1.28.1

## Problem

no errors are thrown, and invalid markup is created

![oct-23-2018 12-42-35](https://user-images.githubusercontent.com/437016/47386333-3de12e80-d6c1-11e8-85d0-c9cc2129560a.gif)

According to prettyHTML maintainer, this is a well known limitation/behavior.  Not sure if/how we want to address this as invalid markup is generated and no warnings are thrown by the formatter (there is an obvious editor error though, and maybe that's the best we can do).  See issue filed with them here: https://github.com/Prettyhtml/prettyhtml/issues/52

## Reproducible Case

happy to provide a veturpack fork if desired but this seems like a simple repro

**Comment by StarpTech** [comment]
If you want to use single quotes only you can configure it.

**Comment by octref** [comment]
@StarpTech Is there any way to make prettyHTML format the interpolation range with prettier?

**Comment by StarpTech** [comment]
Hi @octref prettyhtml should be dump. It's not responsible to validate or sanitize your markup. This is a known behaviour to reduce the complexity out of the formatter into framework specific compilers. IMO be consistent with one style and you will have an issue.

**Comment by octref** [comment]
@StarpTech Sounds good. Just a suggestion — maybe offer an API for people to hook in their sanitizer. I understand you have the formatter for both Angular, Vue, etc, so it's impossible to provide one solution to all. But if you give an API, Vue/Angular can hook in their own mini-formatter for the interpolations.
