### ISSUE TITLE
How to format the html?

### ISSUE THREAD

**Issue by AurevoirXavier** [vuejs/vetur#943]
When I use SHIFT-ALT-F, it shows 'there is no document formatter for html-files'. When I turn on default html formatter in setting, It wasn't call prettyhtml to format the code. Btw, I have already set:

```json
"vetur.format.defaultFormatter.html": "prettyhtml",
"vetur.format.defaultFormatterOptions": {
    "prettyhtml": {
        "tabWidth": 4,
        "printWidth": 100,
        "singleQuote": false
    }
},
```

**Comment by mehtadone** [comment]
I'm finding the same thing

**Comment by octref** [comment]
Vue does not contribute a formatter for HTML. You can only use it for .vue files now.
You should wait for this to be published: https://github.com/StarpTech/prettyhtml-vscode.
