### ISSUE TITLE
Install fails with reference to file noImportant.js

### ISSUE THREAD

**Issue by VarCharMax** [vuejs/vetur#944]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: octref.vetur-0.13.0
- VS Code version: 1.28.2

## Problem
Attempting to install vetur in VS Code always fails with message "Failed to install 'octref.vetur"
## Reproducible Case

Attempting to install manually produces the error message 
EPERM: operation not permitted, open 'C:\Users\<username>\.vscode\extensions\.octref.vetur-0.13.0\server\node_modules\stylint\src\checks\noImportant.js'

Attempting to run the install as administrator either through VS Code or via command line produces the same error message.

**Comment by octref** [comment]
Tracked upstream at https://github.com/Microsoft/vscode/issues/62607.
