### ISSUE TITLE
Is it possible to upgrade prettyhtml version?

### ISSUE THREAD

**Issue by jsmedmar** [vuejs/vetur#945]
Sorry I'm asking this here. Is it possible to upgrade the `prettyhtml` version?  If not, are you guys planning to do so?

**Comment by pgoshulak** [comment]
> Sorry I'm asking this here. Is it possible to upgrade the `prettyhtml` version? If not, are you guys planning to do so?

Seconded. One upgrade I see is that `prettyhtml` allows a single newline between elements at the same level, but vetur seems to force this to collapse. Makes long templates a bit dense to visually parse :/

**Comment by jsmedmar** [comment]
thats my exact motivation 😂

**Comment by Coder-256** [comment]
Hmm it looks like it was updated in 584f648f062d7c25298ad7908588073fb436f11d, but even since then it has gained many features specifically for Vue! +1

**Comment by StarpTech** [comment]
Hi guys, prettyhtml has been improved a lot. I recommend to update to the latest version. You can check it out here https://prettyhtml.netlify.com/
