### ISSUE TITLE
 the format not work for template with html

### ISSUE THREAD

**Issue by pycodev** [vuejs/vetur#946]
- [ x ] I have searched through existing issues
- [ x ] I have read through [docs](https://vuejs.github.io/vetur)
- [ x ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  mac
- Vetur version: 0.13.0
- VS Code version: 1.28.2

## Problem

as for template with html, the formatting for html can not work. 
like:
```
<template lang="html">
```
but template without `lang="html"`, the formatting work well.

**Comment by octref** [comment]
We only support `<template>`, no `<template lang="html">`. Sorry.
