### ISSUE TITLE
关于vscode 在vue文件中书写ts 代码感知提示慢的问题

### ISSUE THREAD

**Issue by nailfar** [vuejs/vetur#948]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  Win
- Vetur version: 0.11.7
- VS Code version:1.27.2

## Problem

当项目文件增加到800个的时候，在<script lang="ts"></script> 内书写 ts 代码，代码的感知提示（vscode 官网定义是 IntelliSense）特别慢需要好几秒才能提示；可有什么好的解决方法

**Comment by octref** [comment]
Not yet. https://github.com/vuejs/vetur/issues/547
