### ISSUE TITLE
prettyhtml settings

### ISSUE THREAD

**Issue by Coder-256** [vuejs/vetur#949]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS Mojave 10.14.1
- Vetur version: 0.13.0
- VS Code version: 1.28.2

## Problem

I'm fully aware that the settings for `prettyhtml` can be [manually configured](https://vuejs.github.io/vetur/formatting.html#prettyhtml), but these should be automatically set based on the Prettier config (ex. `printWidth`). This is already the case for scripts and styles, just not HTML.

## Reproducible Case

N/A, just notice that the defaults must be manually overridden in both the ESLint config and the `prettyhtml` settings.

**Comment by thedamon** [comment]
I feel as though printWidth for HTML and JS shouldn't necessarily be the same. indentation definitely should, though

**Comment by Coder-256** [comment]
@thedamon This issue is kind of superseded by #950 anyway, take a look over there. I'll still leave this issue open for now until I hear from a vetur dev.

**Comment by thedamon** [comment]
Oh man! i didn't realize that happened.. that's exciting.

**Comment by StarpTech** [comment]
Hi @thedamon I accepted your PR in prettyhtml. You can enable it via `wrapAttributes: true` options. We also added support for sorting attributes alphabetically with `sortAttributes: true`

**Comment by octref** [comment]
People have a lot of confusions when configuring formatting settings...I want to avoid more implicit inheritance.

**Comment by octref** [comment]
Still, I'll update new settings from https://github.com/Prettyhtml/prettyhtml#api.
