### ISSUE TITLE
Prettier as an option for template formatting

### ISSUE THREAD

**Issue by Coder-256** [vuejs/vetur#950]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Problem

This isn't really much of a problem: complete support for HTML and Vue is planned for Prettier 1.15! 🎉🎉🎉 And to me, it looks really good. See prettier/prettier#5259 for their progress and a link to a preview.

This issue is to hopefully begin implementing opt-in support for these changes so that Vetur will be ready once the new version of Prettier is released.

However, IMHO, the best way to do this is a bit different: once Prettier 1.15 is released, one solution is to simply _disable formatting by default_, and encourage users to install [the official Prettier VS Code extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) alongside Vetur. This way, Vetur should still support language-specific formatters for individual script/style/template blocks (ESLint, TSLint, stylus-supremacy, etc.) but users could also switch to using their own language-agnostic, whole-file/unified formatting with Prettier. I think that users can still opt to only format certain languages in Vue files.
This approach has many benefits:
- Prettier now maintains its own formatting support
- Prettier can use unified settings (printWidth, tab style, quotes, etc.) for all languages.
- Users can choose their own version of Prettier
- The BYOF (Bring Your Own Formatter) approach allows Vetur to focus on more important features (intellisense, syntax highlighting, etc.)
- Users who don't like Prettier's opinionated style can still use their own formatters (such as prettyhtml) for individual languages through Vetur (including the current support for using Prettier as a formatter for individual blocks so that users can combine formatters, for example ESLint for JS and Prettier for CSS).

Overall, decoupling Prettier from Vetur will soon be made possible, which is a good change for users and developers alike.

Side note: this may impact (or maybe fix) #543.

**Comment by phouri** [comment]
1.15 just got released, any eta on when this will be included in vetur? :)

**Comment by Coder-256** [comment]
@phouri For now it seems you can just install [the Prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) and add this to your settings:

```
{
  "vetur.format.defaultFormatter.html": "none",
  "vetur.format.defaultFormatter.css": "none",
  "vetur.format.defaultFormatter.postcss": "none",
  "vetur.format.defaultFormatter.scss": "none",
  "vetur.format.defaultFormatter.less": "none",
  "vetur.format.defaultFormatter.stylus": "none",
  "vetur.format.defaultFormatter.js": "none",
  "vetur.format.defaultFormatter.ts": "none"
}
```

@octref Thoughts?

**Comment by phouri** [comment]
@dimensi in your prettier extension remove vue from prettier.disableLanguages
```
"prettier.disableLanguages": []

**Comment by dimensi** [comment]
@phouri thx, found it now in documentation for extension

**Comment by Coder-256** [comment]
@phouri I think that you're right in that the Prettier extension needs to update its default disabled languages.

**Comment by fundon** [comment]
```"vetur.format.defaultFormatter.html": "prettier"```

**Comment by shealan** [comment]
> prettier

Try `"vetur.format.defaultFormatter.html": "js-beautify-html",`

**Comment by c01nd01r** [comment]
These steps helped me:
1. Update Prettier in current project to last version.
2. https://github.com/vuejs/vetur/issues/950#issuecomment-436654525
3. https://github.com/vuejs/vetur/issues/950#issuecomment-436662542

**Comment by atilkan** [comment]
@Coder-256 I guess we don't need vetur. Am i wrong?

**Comment by Coder-256** [comment]
@atilkan I just wish that Vetur provided the option to call a npm script or such for formatting, that way each project can use its own formatter without relying on Vetur. It's really up to you.

**Comment by octref** [comment]
I updated the title to reflect what would be done. I'll work on this in February.

**Comment by octref** [comment]
`"vetur.format.defaultFormatter.html": "prettier"` is available in 0.16.2.

**Comment by luismartinezs** [comment]
> `"vetur.format.defaultFormatter.html": "prettier"`

This was the solution for me

**Comment by octref** [comment]
You can use `vetur.format.enable: false` to disable Vetur formatter completely (if you want to use prettier) in the upcoming 0.17.1 release.
