### ISSUE TITLE
Support for vue directive / interpolation JS in template region

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#96]
IntelliSense, error-checking and linting with ESLint.

**Comment by rwatts3** [comment]
Does this add support for user vue-directives, or directives that are not apart of the core library.

such as `<my-component>` ?

**Comment by octref** [comment]
@rwatts3  No.

**Comment by rwatts3** [comment]
Is there a plan to implement ?

**Comment by octref** [comment]
Not in the short term.

**Comment by octref** [comment]
Track this in #145.
