### ISSUE TITLE
Some ERR when  there are 2 'style' tag...

### ISSUE THREAD

**Issue by win7killer** [vuejs/vetur#964]
## Info

- Platform: macOS
- Vetur version: 0.13.0
- VS Code version: 1.28.2

## Problem
In '*.vue' single file, if there are 2 'style' tag, this tips won't work ok. 

## Reproducible Case
![12](https://user-images.githubusercontent.com/6337378/48395986-ee3bd300-e753-11e8-8d8c-b47f6eeb26a3.gif)

**Comment by octref** [comment]
Yeah, sorry for that. Tracked in https://github.com/vuejs/vetur/issues/430.
