### ISSUE TITLE
Pug: Block Comment doesn't supported

### ISSUE THREAD

**Issue by RayPS** [vuejs/vetur#967]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: `macOS`
- Vetur version: `0.13.0`
- VS Code version: `1.28.2`

## Problem
<img width="603" alt="screen shot 2018-11-16 at 14 38 29" src="https://user-images.githubusercontent.com/1941540/48602324-b92abd00-e9ad-11e8-89c7-9b35ce289e68.png">

- Code shortcut (_default_: `⇧` `⌥` `A`) not respond
- Missing comment syntax highlighting

Luckily it still rendered correctly.

Commenting an attribute is quite often in Vue and it's not a special case.

Would there be possible to support this in the future?

## Reproducible Case
Create a Vue file with a pug template: 
```pug
<template lang="pug">
    h1 Try to comment this line as a comment block.
</template>
```

**Comment by octref** [comment]
This is because VS Code doesn't support it.

When you select the text and press block comment, what do you expect to happen? Something like this?

```vue
<template lang="pug">
    //-
      h1 Try to comment this line as a comment block.
</template>
```

I suggest opening an issue for VS Code.

**Comment by BassOfBass** [comment]
There are only buffered `//` and unbuffered `//-` comments in pug as [per docs](https://pugjs.org/language/comments.html).
Also there is no way to comment attributes: https://github.com/pugjs/pug/issues/3289

**Comment by yoyo930021** [comment]
Thanks @BassOfBass 
I close this issue.
