### ISSUE TITLE
prettyhtml formating custom element <Input/>

### ISSUE THREAD

**Issue by lyphol** [vuejs/vetur#969]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.13.0 | 2018-10-04
- VS Code version: 1.29.1

## Problem
Use prettyHtml to format the custom tag <Input/> and the result is <Input> , the compiler will report an error, but this problem does not occur at https://prettyhtml.netlify.com/
1.vetur prettyHtml
![vetur prettyhtml](https://user-images.githubusercontent.com/26831090/48675428-c0abbb00-eb93-11e8-968e-4b4526fcdd33.gif)
2.https://prettyhtml.netlify.com/
![image](https://user-images.githubusercontent.com/26831090/48675443-e89b1e80-eb93-11e8-85f5-d16ec555a2ee.png)

**Comment by dxc0522** [comment]
yes   i just want to ask.
please

**Comment by dxc0522** [comment]
I have the same question as you

**Comment by octref** [comment]
Will be solved by #971.

**Comment by octref** [comment]
Try 0.14.0.
