### ISSUE TITLE
Rename symbol support 

### ISSUE THREAD

**Issue by palasjir** [vuejs/vetur#97]
Hi,
do you support [rename symbol](https://code.visualstudio.com/docs/editor/editingevolved#_rename-symbol) symbol? For example changing variable name inside `script` tag isn't working for me.

**Comment by octref** [comment]
Not yet. This probably will be done together with jump to definition feature.

**Comment by winuxue** [comment]
do you have an ETA?

**Comment by Grawl** [comment]
> Not yet.

> @octref commented on 18 Mar 2017

😢

**Comment by octref** [comment]
Tracking in #610.

**Comment by cooldevcodes** [comment]
Does it work now? I tried with latest version of VSCode insider and Vetur but it seems doesn't work.
