### ISSUE TITLE
J'ai un problème avec mon éditeur de texte

### ISSUE THREAD

**Issue by 23tonmyetogo** [vuejs/vetur#970]
Issue Type: <b>Bug</b>

Mon éditeur VSCode ne me permet plus de taper du code je ne sais pas à quoi c'est dût!

Extension version: 0.13.0
VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz (4 x 2095)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.94GB (1.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by octref** [comment]
Please open an issue at using English, thanks: https://github.com/microsoft/vscode.
