### ISSUE TITLE
The Vue Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by Yakoot** [vuejs/vetur#973]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: 0.13.0
- VS Code version: 1.29.1

## Problem

```
/home/yakoot/.vscode/extensions/octref.vetur-0.13.0/server/node_modules/eslint/lib/ignored-paths.js:227
                    throw e;
                    ^

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at new IgnoredPaths (/home/yakoot/.vscode/extensions/octref.vetur-0.13.0/server/node_modules/eslint/lib/ignored-paths.js:203:55)
    at CLIEngine.executeOnText (/home/yakoot/.vscode/extensions/octref.vetur-0.13.0/server/node_modules/eslint/lib/cli-engine.js:581:28)
    at Object.doValidation (/home/yakoot/.vscode/extensions/octref.vetur-0.13.0/server/dist/modes/template/services/htmlValidation.js:25:27)
    at Object.doValidation (/home/yakoot/.vscode/extensions/octref.vetur-0.13.0/server/dist/modes/template/index.js:34:37)
    at languageModes.getAllModesInDocument.forEach.mode (/home/yakoot/.vscode/extensions/octref.vetur-0.13.0/server/dist/services/vls.js:109:47)
    at Array.forEach (<anonymous>)
    at VLS.doValidate (/home/yakoot/.vscode/extensions/octref.vetur-0.13.0/server/dist/services/vls.js:107:59)
    at VLS.validateTextDocument (/home/yakoot/.vscode/extensions/octref.vetur-0.13.0/server/dist/services/vls.js:242:34)
    at Timeout.pendingValidationRequests.(anonymous function).setTimeout [as _onTimeout] (/home/yakoot/.vscode/extensions/octref.vetur-0.13.0/server/dist/services/vls.js:231:18)
[Error - 9:33:07 PM] Connection to server got closed. Server will not be restarted.
```

my config:
{
  "workbench.iconTheme": "material-icon-theme",
  "editor.tabSize": 2,
  "editor.detectIndentation": false,
  "files.autoSave": "onFocusChange",
  "emmet.syntaxProfiles": {
    "javascript": "jsx",
    "xml": {
      "attr_quotes": "single"
    }
  },
  "emmet.includeLanguages": {
    "vue-html": "html",
    "javascript": "javascriptreact"
  },
  "typescript.validate.enable": false,
  "typescript.check.npmIsInstalled": false,
  "emmet.triggerExpansionOnTab": true,
  "twig-language-2.tabSize": 2,
  "window.zoomLevel": 0,
  "files.associations": {
    "*.vue": "vue"
  },
  "vetur.format.defaultFormatterOptions": {
    "js-beautify-html": {
      "wrap_attributes": "force-aligned"
    },
    "prettyhtml": {
      "printWidth": 100,
      "singleQuote": false
    }
  },
  "vetur.trace.server": "verbose",
  "vetur.format.defaultFormatter.html": "js-beautify-html",
}

it stopped working when I switched to another project, not pure vue

**Comment by octref** [comment]
How does your eslint config file look like? Any syntax errors in there?

**Comment by Yakoot** [comment]
> How does your eslint config file look like? Any syntax errors in there?
my vue folder is in web/themes/custom/themename/src/vue (it's drupal project)

I fount .eslintrc file in web directory
```
{
  "extends": "./core/.eslintrc"
}
```
and .eslintrc.json in web
```
{
  "extends": "./core/.eslintrc.json"
}

```

in core folder i found only the .eslintrc.json
```
{
  "extends": [
    "airbnb",
    "plugin:prettier/recommended"
  ],
  "root": true,
  "env": {
    "browser": true,
    "es6": true,
    "node": true
  },
  "globals": {
    "Drupal": true,
    "drupalSettings": true,
    "drupalTranslations": true,
    "domready": true,
    "jQuery": true,
    "_": true,
    "matchMedia": true,
    "Backbone": true,
    "Modernizr": true,
    "CKEDITOR": true
  },
  "rules": {
    "prettier/prettier": "error",
    "consistent-return": ["off"],
    "no-underscore-dangle": ["off"],
    "max-nested-callbacks": ["warn", 3],
    "import/no-mutable-exports": ["warn"],
    "no-plusplus": ["warn", {
      "allowForLoopAfterthoughts": true
    }],
    "no-param-reassign": ["off"],
    "no-prototype-builtins": ["off"],
    "valid-jsdoc": ["warn", {
      "prefer": {
        "returns": "return",
        "property": "prop"
      },
      "requireReturn": false
    }],
    "no-unused-vars": ["warn"],
    "operator-linebreak": ["error", "after", { "overrides": { "?": "ignore", ":": "ignore" } }]
  }
}

```

**Comment by Yakoot** [comment]
sometimes it works

**Comment by ArthurMao** [comment]
Same problem here.
When I use GitLens -->Open line changes with working file, this Error message showed up.

**Comment by octref** [comment]
@ArthurMao Can you open a new issue with reproducible steps? I'm doing exact the same thing and it does not happen.

![image](https://user-images.githubusercontent.com/4033249/50704350-ea1d8a80-100b-11e9-84f9-e7b885dd9074.png)

@Yakoot If you can find **reproducible** steps, feel free to add details and reopen. Otherwise I can't investigate.

**Comment by gnefeng** [comment]
Same issue here.

![snipaste_2019-01-11_14-31-09](https://user-images.githubusercontent.com/29921478/51017181-19a13980-15ae-11e9-9099-b168a27e61db.png)
![snipaste_2019-01-11_14-40-20](https://user-images.githubusercontent.com/29921478/51017378-d85d5980-15ae-11e9-8e42-7d5fdebf9af3.png)

When I use Gitlens and open uncommited changes, the error message showed up.
