### ISSUE TITLE
Support GraphQL custom block

### ISSUE THREAD

**Issue by leopiccionia** [vuejs/vetur#975]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Problem
Some emerging Vue frameworks, remarkably [Gridsome](https://gridsome.org/docs/pages), use GraphQL custom blocks for data pre-fetching. Nonethewise, Vetur currently doesn't support GraphQL custom block highlighting.

A possible obstacle is that currently VS Code, by default, doesn't include a `graphql` language server (for file extension `gql`).

**Comment by octref** [comment]
We do have custom block support, so this is not hard to do. I just need to register `graphql` as one of the embeddable languages.

**Comment by tyankatsu0105** [comment]
@octref 
Hi👋
I'm always helped by Vetur :)
I'm looking forward to this work!!

**Comment by Airkro** [comment]
@octref
Many frameworks use `custom block` to implement a wide variety of functions. I think the `lang` attribute should be supported.

```jsx
<config lang="json">
{
  "foo": "baz"
}
</config>
 
<i18n lang="yaml">
...
</i18n>
```

**Comment by octref** [comment]
Can someone post an example and link to docs, how does a graphql custom block look like?

**Comment by leopiccionia** [comment]
@octref Here, `<page-query>` and `<static-query>` are custom GraphQL blocks: https://gridsome.org/docs/data-query-data

**Comment by leopiccionia** [comment]
@octref The Vue blocks are builtin. AFAIK the queries run against a local (GraphQL) server, on server-side (similarly to Nuxt's `asyncData`).

**Comment by monachilada** [comment]
> @leopiccionia I'm not familiar with gridsome — are these builtin custom blocks, or do you declare `<my-query>` somewhere in the code and can start using them?

There are two types:
`<page-query>` for pages and templates
`<static-query>` for layout and components

It's just regular GraphQL between the tags. And yes, you declare those in your `.vue` file and can use them directly in your templating.

**Comment by octref** [comment]
Here you go:

![image](https://user-images.githubusercontent.com/4033249/52375003-79ef9380-2a13-11e9-9103-a5023d3b43de.png)

Steps:

- Install one of the VS Code Graphql extensions
- Have this setting:

  ```
  "vetur.grammar.customBlocks": {
    "docs": "md",
    "i18n": "json",
    "page-query": "graphql"
  },
  ```

- Run command `Vetur: Generate Grammar`

**Comment by brianzelip** [comment]
[The solution above](https://github.com/vuejs/vetur/issues/975#issuecomment-461197031) worked for me...except for `<static-query>`. So be sure to add it after `page-query`, like so:

```js
"vetur.grammar.customBlocks": {
    "docs": "md",
    "i18n": "json",
    "page-query": "graphql",
    "static-query": "graphql"
  }
```

**Comment by Berkmann18** [comment]
For those wondering why it doesn't highlight it even after applying @octref 'solution, try restarting VSCode. It didn't work for me when I changed the setting, but after opening VSCode the next day it worked.

**Comment by octref** [comment]
Per reloading, I added some docs to https://vuejs.github.io/vetur/highlighting.html

**Comment by dosstx** [comment]
How do you run command this command in VSCODE?
`Vetur: Generate Grammar`

**Comment by leopiccionia** [comment]
@dosstx You run it via the [Command Palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette).

**Comment by m3hari** [comment]
Isn't it better to make `Vetur: Generate Grammar` command **automatic**? Are their limitations in VsCode API to detect config change 🤔

**Comment by octref** [comment]
Yes, that is not allowed: https://github.com/microsoft/vscode/issues/68647

**Comment by djmtype** [comment]
Thanks to the post I have syntax highlighting working on the queries, but how do we get proper indentation?
