### ISSUE TITLE
$style properties incorrect color highlight 

### ISSUE THREAD

**Issue by c01nd01r** [vuejs/vetur#98]
Hello! Thx for a good extension! 

When I use $style object from CSS modules, I get incorrect color highlight  for some properties like `$style.text` or `$style.title`.
Look at the screenshot:
![2017-03-22 14 26 28](https://cloud.githubusercontent.com/assets/3511312/24195711/e52bba4a-0f0b-11e7-9c8c-ff7c65ce14fd.png)

vetur 0.5.6.
vscode 1.10.2 (1.10.2)

**Comment by octref** [comment]
Bug with html grammar. Will fix later today.

**Comment by octref** [comment]
It's a problem with your syntax theme, I think.

![image](https://cloud.githubusercontent.com/assets/4033249/24211712/4b5b0e0a-0f03-11e7-8711-a199708e29d0.png)

Which one are you using?

**Comment by c01nd01r** [comment]
I use [Material Neutral Theme](https://marketplace.visualstudio.com/items?itemName=bernardodsanderson.theme-material-neutral)
Other default themes:
![2017-03-23 10 48 51](https://cloud.githubusercontent.com/assets/3511312/24237632/2539b536-0fb8-11e7-8c37-e9046fa2d6a3.png)
![2017-03-23 10 48 41](https://cloud.githubusercontent.com/assets/3511312/24237630/25399fba-0fb8-11e7-8a1a-c57e085183b1.png)
![2017-03-23 10 48 58](https://cloud.githubusercontent.com/assets/3511312/24237634/253afad6-0fb8-11e7-9492-f73cea84ba32.png)
![2017-03-23 10 49 28](https://cloud.githubusercontent.com/assets/3511312/24237631/2539b2ca-0fb8-11e7-90dd-2bab5298321f.png)
![2017-03-23 10 49 38](https://cloud.githubusercontent.com/assets/3511312/24237633/253a72e6-0fb8-11e7-9499-01651b133834.png)

**Comment by octref** [comment]
Vetur grammar controls how each word is tokenized, but the theme decides how to color each word.

IMO as long as `:class` has one color and `$style.title` has a different one, there isn't really anything "wrong" with the theme.

Dark+ certainly can be improved. But that's an issue for VSCode.
