### ISSUE TITLE
Prettier html formatting is not useful, need better html formatting option

### ISSUE THREAD

**Issue by atilkan** [vuejs/vetur#984]
## Problem
I read the news about prettier supporting vue files. After the update came i saw how it formats. This is not usable or configurable. Tried prettyhtml but can't configure it too.  First screenshot demonstrate how ugly and unreadable prettier formats html. 

<img width="477" alt="screen shot 2018-11-26 at 19 07 46" src="https://user-images.githubusercontent.com/1254613/49026431-ec8bf980-f1ae-11e8-88f4-8557a2e6fe54.png">

<img width="519" alt="screen shot 2018-11-26 at 19 08 07" src="https://user-images.githubusercontent.com/1254613/49026447-f4e43480-f1ae-11e8-8def-4129e9de6ebd.png">

**Comment by octref** [comment]
There is no prettier support yet. See #950.

It is configurable, read docs please https://vuejs.github.io/vetur/formatting.html.

**Comment by atilkan** [comment]
@octref But it seems it works. prettyhtml use it internally.

**Comment by atilkan** [comment]
For anyone interested
```
"vetur.format.defaultFormatter.html": "js-beautify-html",
  "vetur.format.defaultFormatterOptions": {
    "js-beautify-html": {
      "wrap_attributes": "aligned-multiple"
    }
  },
```

**More info:** 
https://github.com/beautify-web/js-beautify
https://vuejs.github.io/vetur/formatting.html#settings

**Comment by qinshenxue** [comment]
```
"vetur.format.defaultFormatterOptions": {
        "js-beautify-html": {
            "wrap_attributes": "aligned-multiple"
        },
        "prettyhtml": {
            "printWidth": 400,
            "wrapAttributes": false
        }
    },
```

**Comment by StanielPetrov** [comment]
> For anyone interested
> 
> ```
> "vetur.format.defaultFormatter.html": "js-beautify-html",
>   "vetur.format.defaultFormatterOptions": {
>     "js-beautify-html": {
>       "wrap_attributes": "aligned-multiple"
>     }
>   },
> ```
> 
> **More info:**
> https://github.com/beautify-web/js-beautify
> https://vuejs.github.io/vetur/formatting.html#settings

Cheers! This fixed it! :)

**Comment by atilkan** [comment]
Prettier now supports better formatting.
