### ISSUE TITLE
couldn't format vue file since yesterday

### ISSUE THREAD

**Issue by bobjiang1988** [vuejs/vetur#985]
## Info

- Platform: Linux
- Vetur version: 0.14.1
- VS Code version: 1.27.2

Here is the log:

Prettier format failed
[Error - 8:40:30 AM] Cannot read property 'tabWidth' of null

**Comment by octref** [comment]
Repro case?

**Comment by halws** [comment]
I've the same problem(
Also i've noticed if eslint ext. is dissabled everything is ok.

**Comment by bobjiang1988** [comment]
> Repro case?

Mybe version 0.14.2 fixed it
