### ISSUE TITLE
Single quotes are being replaced with double quotes

### ISSUE THREAD

**Issue by failpunk** [vuejs/vetur#986]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS Mojave 10.14.1 (18B75)
- Vetur version: 0.14.1
- VS Code version: Version 1.29.1 (1.29.1)

## Problem

VS Code has started to replace all my single quotes with double quotes out of nowhere.
_Side note: this happened after updating to MacOS Mojave._

Here are my settings with singleQuote set to true.
<img width="984" alt="screen shot 2018-11-26 at 5 06 14 pm" src="https://user-images.githubusercontent.com/1109167/49051648-a1b5b600-f19d-11e8-8293-53dca1b7d36c.png">

## Reproducible Case

Replaces all my Javascript single quotes with double quotes within .vue files in VS Code when using format document.

**Comment by octref** [comment]
https://github.com/vuejs/vetur/blob/master/CHANGELOG.md#formatter-changes

I guess I should also add some documentation for setting global configurations for the default formatters.

**Comment by failpunk** [comment]
Yeah, that did it @octref 

Solution:

- Add `.prettierrc` file
- move all `prettier.*` settings from VS Code to file.

**Comment by hezhongfeng** [comment]
@failpunk @octref 
That means vsc's user setting `"prettier.singleQuote": true,` not work？

**Comment by octref** [comment]
Yep, that's the temporary solution. However, unlike in the past when you can specify `prettier.*` globally, there's no way to do that now.

My plan is to:

- Allow `vetur.format.defaultFormatterOptions.prettier.*`.
- When a prettier config file is found, ignore `vetur.format.defaultFormatterOptions.prettier.*` and use that file + `vetur.format.options`.
- Otherwise, use `vetur.format.defaultFormatterOptions.prettier.*` + `vetur.format.options`.

**Comment by usercao** [comment]
@octref I think the setting of formatter is too frequently,and  the readability  may be  get worse when add  configuration files,I hope recover the global config mode,it must add config file in many projects,it is a repetitive action,too complicated.back to the past of VS Code.

**Comment by 0njzy0** [comment]
@octref Hope to add an option to turn off formatting, such as `vetur.format.disable.` In this case, you don’t need to do this and it will be easier to use prettier and eslint:
```json
 "vetur.format.defaultFormatter.html": "none",
 "vetur.format.defaultFormatter.css": "none",
 "vetur.format.defaultFormatter.js": "none",
 "vetur.format.defaultFormatter.less": "none",
 "vetur.format.defaultFormatter.postcss": "none",
 "vetur.format.defaultFormatter.scss": "none",
 "vetur.format.defaultFormatter.stylus": "none",
 "vetur.format.defaultFormatter.ts": "none"
```

**Comment by octref** [comment]
@0njzy0 That's covered in https://github.com/vuejs/vetur/issues/950. Now even if you set the above, it doesn't stop Vetur from registering a formatter.

**Comment by octref** [comment]
Use 0.14.2 and see https://vuejs.github.io/vetur/formatting.html#settings.

If you want to set global prettier setting, either:

- Make a `.prettierrc` config at your home directory 
- Use the below config and do NOT include a `.prettierrc` in your home directory

  ```json
  "vetur.format.defaultFormatterOptions": {
    "prettier": {
      // Prettier option here
      "semi": false
    }
  }
  ```

**Comment by 0njzy0** [comment]
@octref Wow,Thanks!

**Comment by sirarthurnell** [comment]
The [solution ](https://github.com/vuejs/vetur/issues/986#issuecomment-441873618)of @hezhongfeng is the only one that worked for me.

**Comment by santironhacker** [comment]
After stepping into the same problem, the solution has been solved into the commit for vetur:
[Set a prettierrc config for vetur #39](https://github.com/bcgov/nr-get-token/pull/39/files/7c0fbfbd73ec1cb9c0dcbbf3f8f9a4a9a4defa5b)

Simply add to your package.json below all other keys:
`  "prettier": {
    "singleQuote": true
  }`

**No need** of **prettierrc file**.

**Comment by vip32** [comment]
yes, and the semicolumn too:

```
"prettier": {
    "semi": false,
    "singleQuote": true
  }
```

**Comment by octref** [comment]
> "prettier": { "singleQuote": true }

@santironhacker 
I wasn't aware that works as well 😅
Wanna send a PR to update documentation?

**Comment by featherart** [comment]
Generally I wish I didn't have to spend time trying to figure out why VS Code suddenly decided to add double quotes by default on save. I added a .prettierrc file and all of the other things people recommended and in the end I just had to go back to global settings and repeatedly unselect "auto" on quote types. I miss the global settings file. I had already done this unsetting but it reset itself to "auto" automagically. Less automagic, more control. That would be great!

**Comment by isabellachen** [comment]
ctrl  + shift + p > Preferences: Open Settings

```
  "vetur.format.defaultFormatterOptions": {
    "prettier": {
      "singleQuote": true
    }
  }
```

**Comment by octref** [comment]
@featherart 

![image](https://user-images.githubusercontent.com/4033249/62643722-73c46c00-b8fd-11e9-831b-50267a19c3ed.png)

https://vuejs.github.io/vetur/formatting.html#settings

**Comment by octref** [comment]
@featherart It used to be a lot of confusion, when people had 3 sources of configs:

- `.prettierrc` in project
- `prettier.*` configs
- `vetur.format.*` configs

So the recommended way is to just set a `.prettierrc`, which both Vetur and the Prettier extensions read. Reading from other extension's setting is implicit and causes confusion.

**Comment by aldo-rd** [comment]
> 
It works too with the file **.vscode/settings.json** at project root.

```
{
    "vetur.format.defaultFormatterOptions": {
       "prettier": {
         "singleQuote": true
       }
    }
}
