### ISSUE TITLE
prettier can't read setting in vscode settings

### ISSUE THREAD

**Issue by qianfeii** [vuejs/vetur#988]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  Win
- Vetur version:0.14.1
- VS Code version:1.29.1

## Problem
vetur default setting '"vetur.format.defaultFormatter.js": "prettier"' and i set prettier in vscode settings,but it didn't work. only if i add '.prettierrc.js' in project root, the settings i need can works.

**Comment by octref** [comment]
Read the changelog and new issues.
