### ISSUE TITLE
Maybe some conflict within vetur format and eslint

### ISSUE THREAD

**Issue by L-Devil-GitHub** [vuejs/vetur#989]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: last
- VS Code version: last

## Problem

Maybe some conflict within vetur format and eslint

## Reproducible Case

like this:
    vetur may format:
        a
            ? asdfasdf(
                a,
               )
            : b
    eslint may want:
        a
            ? asdfasdf(
                a,
            )
            : b
    There is two more space before ')' when vetur format

**Comment by octref** [comment]
Please make a reproducible case by:
- Forking https://github.com/octref/veturpack
- Make edits
- Push them

I can't repro this with information you gave me.
