### ISSUE TITLE
Could not format vue file correctly

### ISSUE THREAD

**Issue by cangzhang** [vuejs/vetur#99]
As shown in the gif, other extensions have been disabled.
![1](https://cloud.githubusercontent.com/assets/1357073/24197817/27c41f50-0f3e-11e7-8e02-9b53cc5519b3.gif)
![snipaste20170322_202923](https://cloud.githubusercontent.com/assets/1357073/24197841/4401ea58-0f3e-11e7-93d5-3a7f629900b2.png)

**Comment by octref** [comment]
Will look into it. Probably a bug from js-beautify.

**Comment by csicky** [comment]
Just came here to report exactly this. It indents parts of html on each save.

**Comment by qiming-kooboo** [comment]
@octref  Any progress of this issue?
I found that the issue only happens when html contains ‘mustache’.

**Comment by adamgoose** [comment]
I'm experiencing something similar. Screencast: http://d.enge.me/qEW4

Truncated code from said screencast:

```html
                    <h4 class="media-heading">
                        {{ ticket.title }}
                        <small class="pull-right">{{ ticket.created_at | timestamp }}</small>
                    </h4>
                    <button class="btn btn-xs"
                            :class="{'btn-success': form.public, 'btn-danger': !form.public}"
                            @click="form.public = !form.public">
                        <span v-show="!form.public">
                            <i class="fa fa-lock"></i> Private
                        </span>
                        <span v-show="form.public">
                            <i class="fa fa-unlock"></i> Public
                        </span>
                    </button>
```

**Comment by adamgoose** [comment]
Of course, setting `"html.format.enable": false` prevents this issue from happening.

**Comment by octref** [comment]
@adamgoose
> Of course, setting "html.format.enable": false prevents this issue from happening.

Sorry that's a bug that has been fixed on master.

`js-beautify` is working as expected -- this bug comes from mixing VSCode's html formatter with js-beautify. Will push a fix tonight with formatter options for 0.6 release.

**Comment by tziuka** [comment]
@octref Hi, any update on the issue? Thank you

**Comment by octref** [comment]
This is not fixed with 0.6 yet. I'll look into it later...

**Comment by adamgoose** [comment]
Bump?

**Comment by csicky** [comment]
@octref  Please don't forget about this :)

**Comment by HADB** [comment]
Something goes wrong when set "vetur.format.html.wrap_attributes" to "force-expand-multiline".
<img width="575" alt="qq20170505-112052 2x" src="https://cloud.githubusercontent.com/assets/1836701/25732733/5d043362-3185-11e7-8dff-b9804bfe5075.png">

**Comment by octref** [comment]
@HADB Can you try again with 0.6.5. Or post the code.

@adamgoose Your problem is fixed with 0.6.5.

@cangzhang The original issue is not resolved yet due to js-beautify's bug.

**Comment by HADB** [comment]
@octref still not work in 0.6.7.

force-aligned:
```
<template>
    <div class="gz-uploader"
         @click="uploaderClicked">
        <input ref="fileInput"
               v-if="inputType===0"
               type="file"
               :multiple="multiple"
               @change="fileInputChanged">
        <div class="bottom-area">
            <span>上传图片</span>
        </div>
    </div>
</template>
```

force-expand-multiline:
```
<template>
    <div
        class="gz-uploader"
        @click="uploaderClicked"
    >
        <input
            ref="fileInput"
            v-if="inputType===0"
            type="file"
            :multiple="multiple"
            @change="fileInputChanged"
        >
            <div class="bottom-area">
                <span>上传图片</span>
            </div>
            </div>
</template>
```

**Comment by octref** [comment]
@HADB Then that's a bug for js-beautify which I can't help much with. force-aligned seems to work well so maybe just stick to it.

**Comment by HADB** [comment]
@octref OK, thanks

**Comment by HADB** [comment]
@octref Does this problem link to this issue?  https://github.com/beautify-web/js-beautify/issues/1103

**Comment by octref** [comment]
Opened an issue for `force-expand-multiline`: https://github.com/beautify-web/js-beautify/issues/1186

**Comment by csicky** [comment]
`    "vetur.format.html.wrap_attributes": "auto",
    "vetur.format.css.preserve_newlines": true`
These are not working. `force` and `force-aligned` only are working but both are too extreme. Pushing with these enabled would make the entire team jump on me. Most important, if it does not work to auto align only if needed (`auto` setting), at least to let me insert newlines. It's so frustrating to format a big component with many attributes only to save and lose it.

**Comment by joezimjs** [comment]
Why does vetur take on so much of the formatting on it's own? Can't you just find a way to offload formatting to the other appropriate formatters (e.g. letting VS Code's HTML formatter format the HTML parts, let my installed Prettier plugin format the JS, let a stylus formatter plugin format the style tag with a `lang=stylus` attribute, etc.). Trying to handle all the formatting yourself requires you to work with formatters for 10+ language syntaxes, which doesn't sound maintainable.

**Comment by octref** [comment]
@joezimjs VS Code's HTML formatter uses the same formatter as Vetur do (js-beautify), so it has this problem too.

**Comment by ffxsam** [comment]
This might be related, but I'm still having issues. This template code:

```html
        <el-button type="text" size="small">Edit</el-button>
        <el-button type="text" size="small">Refresh Count</el-button>
        <el-button type="text" size="small">Delete</el-button>
```

gets formatted into this mess:

```html
        <el-button
          type="text"
          size="small"
        >Edit</el-button>
          <el-button
            type="text"
            size="small"
          >Refresh Count</el-button>
            <el-button
              type="text"
              size="small"
            >Delete</el-button>
```

**Comment by octref** [comment]
I don't see any hope in js-beautify fixing it soon.
New release is out with prettier.

You can see the [changelog](https://github.com/vuejs/vetur/blob/master/CHANGELOG.md#vetur-formatting-changes), but just to reiterate, js-beautify is deprecated. I plan to direct effort to making prettier support html and eventually removing js-beautify.

**Comment by ffxsam** [comment]
@octref Thank you for your work & time on this!! I _just_ saw this and tried the format command in a Vue component. Sure enough, the HTML was left alone, and all the script code was prettified.

**Comment by sosoriov** [comment]
@octref  thanks for the info. Plugins have been updated. I use this configuration and it works perfectly.

```js
"vetur.format.defaultFormatter.html": "js-beautify-html",
  "vetur.format.defaultFormatterOptions": {
    "js-beautify-html": {
      // js-beautify-html settings, see https://github.com/vuejs/vetur/blob/master/server/src/modes/template/services/htmlFormat.ts
      "wrap_attributes": "force-aligned"
    }
  }
```

**Comment by ffxsam** [comment]
I wouldn't say it works perfectly, though. The indentation of js-beautify-html is totally broken. This code is not a bunch of nested items:

![image](https://user-images.githubusercontent.com/12532733/31900431-e9060ac2-b7e3-11e7-9f69-aa6da40918ff.png)

**Comment by joezimjs** [comment]
@ffxsam I wonder if it's because of the self-closing tags (e.g. `<menu-icon ... />`). Does it work right if you use a separate closing tag? (e.g. `<menu-icon ...></menu-icon>`)
