### ISSUE TITLE
About proseWrap

### ISSUE THREAD

**Issue by hezhongfeng** [vuejs/vetur#990]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win10
- Vetur version:0.14.2
- VS Code version: 1.29.1

## Problem

hello , I have a question about `proseWrap`
I have Use 0.14.2 and set
```
  "vetur.format.defaultFormatterOptions": {
    "prettyhtml": {
      "wrap_line_length": 160,
      "wrap_attributes": "auto",
      "end_with_newline": false
    },
    "prettier": {
      "singleQuote": true,
      "proseWrap": "never"
    }
  },
  "vetur.format.defaultFormatter.html": "prettyhtml",
  "vetur.format.defaultFormatter.css": "prettier",
  "vetur.format.defaultFormatter.postcss": "prettier",
  "vetur.format.defaultFormatter.scss": "prettier",
  "vetur.format.defaultFormatter.less": "prettier",
  "vetur.format.defaultFormatter.stylus": "stylus-supremacy",
  "vetur.format.defaultFormatter.js": "prettier",
  "vetur.format.defaultFormatter.ts": "prettier",
```
but  when I use format It will 
format` return tempStr + this.time.day + '天 ' + this.time.hour + ':' + this.time.minute + ':' + this.time.second;`
to 
```
      return (
        tempStr +
        this.time.day +
        '天 ' +
        this.time.hour +
        ':' +
        this.time.minute +
        ':' +
        this.time.second
      );
```

**Comment by octref** [comment]
That's not `proseWrap`. It's just prettier wrapping on `printWidth`. `proseWrap` is for markdown files.
You can increase `printWidth` (I usually use 120).

**Comment by hezhongfeng** [comment]
@octref 
Thanks for your answer.
I have try it.it works
