### ISSUE TITLE
prettier config not work

### ISSUE THREAD

**Issue by yuicer** [vuejs/vetur#996]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.14.2
- VS Code version: 1.29.1

## Problem

the formatter always add the semi and doubleQuote in the .vue file
and the formatter will not read the config such as 
```json
  "prettier.semi": false,
  "prettier.singleQuote": true
```
or the 
```json
"vetur.format.defaultFormatterOptions": {
  "prettier": {
    // Prettier option here
    "semi": false
  }
}
```

it just work with the .prettierrc file in the root path of the project

**Comment by octref** [comment]
If your project has prettierrc at root level, Vetur should follow it. You can either:

- Switch to another formatter
- Include `dir/.prettierrc` so everything under `dir` is formatted using that setting

**Comment by octref** [comment]
```json
"vetur.format.defaultFormatterOptions": {
  "prettier": {
    // Prettier option here
    "semi": false
  }
}
```

This is only used when Vetur cannot find a prettierrc.

**Comment by parttimenobody** [comment]
Same thing over here unfortunately.

Same OS/Code version/Vetur version.  

If there's any more information I can provide, please let me know.

**Comment by octref** [comment]
@parttimenobody Can you then:

- Clone https://github.com/octref/veturpack
- Remove prettierrc
- Make workspace setting changes
- Publish your fork so I can repro

![prettier](https://user-images.githubusercontent.com/4033249/49177783-edce3b00-f302-11e8-952d-64cdb2a6b043.gif)

**Comment by yuicer** [comment]
@octref 
it's strange...... it's ok in [https://github.com/octref/veturpack](https://github.com/octref/veturpack)
however. i can't find any different configure between my project and this....

and i delete every file untill i uninstall the node_modules .....it just work....
what the hell..

anyway, it just get done.

**Comment by Aaron-Bird** [comment]
I have the same problem
Today, my prettier settings don't work
There is no ".prettierr" under the project

**Comment by yuicer** [comment]
@octref 
no, i didn't have neither of them

**Comment by octref** [comment]
OK, let me know if you can reproduce the issue.

**Comment by yuicer** [comment]
@octref 
👌，thanks
