### ISSUE TITLE
css，<style> or <style scoped> don't work

### ISSUE THREAD

**Issue by ChangLCS** [vuejs/vetur#998]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win10
- Vetur version: 0.14.2
- VS Code version: 1.29.1

## Problem

hello , I have a question about format css
I have  0.14.2 and set,but it don't work css

## Reproducible Case

this is my vscode setting
```
  "vetur.format.options.tabSize": 2,
  "vetur.format.options.useTabs": false,
  "vetur.format.defaultFormatter.html": "prettyhtml",
  "vetur.validation.template": false,
  "vetur.format.defaultFormatter.js": "prettier",
  "vetur.format.defaultFormatter.css": "prettier",
  "vetur.format.defaultFormatterOptions": {
    "prettyhtml": {
      "printWidth": 10000,
      "singleQuote": false,
      "wrapAttributes": false,
      "sortAttributes": true
    },
    "prettier": {
      "printWidth": 120,
      "tabWidth": 2,
      "useTabs": false,
      "semi": true,
      "singleQuote": true,
      "trailingComma": "all",
      "bracketSpacing": true,
      "jsxBracketSameLine": true,
      "arrowParens": "always",
      "endOfLine": "crlf"
    }
  }
```

if 
``` 
"vetur.format.defaultFormatterOptions": {
    "prettier": {
      "parser": "css"
    }
  }
```
then css work , js <script> don't work , just Either-or

**Comment by illuSioN4ng** [comment]
+1

**Comment by octref** [comment]
Please fork https://github.com/octref/veturpack to reproduce this issue.

I have this exact setting and it works.

**Comment by ChangLCS** [comment]
@octref ，this person @illuSioN4ng  say right，if delete `.prettierrc`  ,it don't work，the formatted because the `.prettierrc`， no vscode setting

**Comment by octref** [comment]
@illuSioN4ng 

Thanks for the repro. Now I can fix it.

**Comment by octref** [comment]
Try 0.14.3.

**Comment by illuSioN4ng** [comment]
@octref the new version it works well

**Comment by ChangLCS** [comment]
Thanks @octref @illuSioN4ng
